### ISSUE TITLE
CSS in JS snippets do not work from Extension, only User Snippets

### ISSUE THREAD

**Issue by jonkwheeler** [Microsoft/vscode#73352]
- VSCode Version: 1.33.1
- OS Version: 10.14.4

Steps to Reproduce:

1. Install an extension I created - [styled-components-snippets](https://marketplace.visualstudio.com/items?itemName=jonkwheeler.styled-components-snippets)
2. Reload VSCode
3. Create a `.js` file
4. Try `imsc` snippet to make sure extension is installed.
5. Try `sc` snippet to create a Styled-Component.

At this point you should have this
```
import styled from 'styled-components';

const StyledDiv = styled.div`
	
`;
```

![sc-snippets-broke 2019-05-06 14_46_20](https://user-images.githubusercontent.com/3136271/57229675-939e7800-700e-11e9-900e-31f8ddada6eb.gif)

6. Try `scp` **inside** the template literal like this
```
const StyledDiv = styled.div`
  scp
`;
```

Does anything happen? It does not for me, and others.

![sc-snippets-broke-3 2019-05-06 14_55_48](https://user-images.githubusercontent.com/3136271/57229927-14f60a80-700f-11e9-95d1-4c2bfb28e710.gif)

7. Place cursor **inside** template literal like Step 6, open Command Palette -> Developer: Inspect TM Scopes.

8. Confirm it says `language: css`.

![sc-snippets-broke-1 2019-05-06 14_47_52](https://user-images.githubusercontent.com/3136271/57229701-a2852a80-700e-11e9-8ba5-25ddc8a32849.gif)

9. Preferences -> User Snippets -> css.json

Add the following

```
"Use props inside styled-component": {
	"prefix": "scp",
	"body": "${props => props.${1}};",
	"description": "Use props inside styled-component"
}
```

![sc-snippets-broke-2 2019-05-06 14_52_07](https://user-images.githubusercontent.com/3136271/57229718-aadd6580-700e-11e9-91e8-1ed93acfe72b.gif)

10. Save, Reload VSCode, and try step 6 again. It should work! The User Snippet works, but the extension does not.

11. Confirm the extension is correctly mapped to the CSS language [on Github](https://github.com/jonkwheeler/styled-components-snippets-vscode/blob/master/package.json#L44).

12. If you can confirm Step 11, and Step 12, why else would the extension fail here? Thank you.

Does this issue occur when all extensions are disabled?: Unable to answer as I need the extension to test it.

**Comment by jonkwheeler** [comment]
@jrieken Hey 👋 Yes, it is caused by an extension. It is an extension I built. I am trying to fix it, but VSCode seems to ignore it.

**Comment by jrieken** [comment]
hm... that's a valid argument ;-)

**Comment by jrieken** [comment]
@jonkwheeler I see this error on the console

```
ERR FileOperationError: Unable to read file (Error: File not found (/Users/jrieken/.vscode-oss-dev/extensions/jonkwheeler.styled-components-snippets-0.2.5/snippets/css.snippets.json.))
    at FileService.<anonymous> (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/files/common/fileService.js:344:27)
    at Generator.throw (<anonymous>)
    at rejected (file:///Users/jrieken/Code/vscode/out/vs/workbench/services/files/common/fileService.js:17:65) file:///Users/jrieken/.vscode-oss-dev/extensions/jonkwheeler.styled-components-snippets-0.2.5/snippets/css.snippets.json
```

**Comment by jrieken** [comment]
Yepp - the paths are invalid because they have a trailing dot, e.g. https://github.com/jonkwheeler/styled-components-snippets-vscode/blob/master/package.json#L45

**Comment by jonkwheeler** [comment]
Holy crap

**Comment by jonkwheeler** [comment]
Trying again on v0.2.7, adding `styled-css`, in addition to `css`. So far I'm noticing it show up 10% of the time now.

**Comment by jonkwheeler** [comment]
I now receive `Manifest is not found jonkwheeler.styled-components-snippets`

**Comment by jrieken** [comment]
It installs just fine for my but I see this

```
extensionService.js:643 [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: jsx
_logMessageInConsole @ extensionService.js:643
_handleExtensionPointMessage @ extensionService.js:602
messageHandler @ extensionService.js:489
_msg @ extensionsRegistry.js:16
error @ extensionsRegistry.js:24
toValidSnippet @ snippetsService.js:29
snippetExt.point.setHandler.extensions @ snippetsService.js:149
_handle @ extensionsRegistry.js:86
setHandler @ extensionsRegistry.js:74
_initExtensionSnippets @ snippetsService.js:141
SnippetsService._pendingWork.push.Promise.resolve.lifecycleService.when.then @ snippetsService.js:92
Promise.then (async)
SnippetsService @ snippetsService.js:91
_createInstance @ instantiationService.js:82
async_1.IdleValue @ instantiationService.js:184
IdleValue._executor @ async.js:582
IdleValue._handle.exports.runWhenIdle @ async.js:591
requestIdleCallback (async)
exports.runWhenIdle @ async.js:559
IdleValue @ async.js:591
_createServiceInstance @ instantiationService.js:184
_createServiceInstanceWithOwner @ instantiationService.js:166
_createServiceInstanceWithOwner @ instantiationService.js:169
_createServiceInstanceWithOwner @ instantiationService.js:169
_createAndCacheServiceInstance @ instantiationService.js:157
_getOrCreateServiceInstance @ instantiationService.js:107
_createInstance @ instantiationService.js:63
createInstance @ instantiationService.js:53
CodeEditorWidget @ codeEditorWidget.js:153
_createInstance @ instantiationService.js:82
createInstance @ instantiationService.js:53
createEditorControl @ textEditor.js:137
createEditor @ textEditor.js:92
create @ baseEditor.js:76
doCreateEditorControl @ editorControl.js:79
doShowEditorControl @ editorControl.js:57
openEditor @ editorControl.js:45
doShowEditor @ editorGroupView.js:597
restoreEditors @ editorGroupView.js:293
EditorGroupView @ editorGroupView.js:56
_createInstance @ instantiationService.js:82
createInstance @ instantiationService.js:53
createFromSerialized @ editorGroupView.js:65
doCreateGroupView @ editorPart.js:350
fromJSON @ editorPart.js:644
deserializeNode @ grid.js:318
deserializeNode @ grid.js:312
deserialize @ grid.js:343
doCreateGridControlWithState @ editorPart.js:637
doCreateGridControlWithPreviousState @ editorPart.js:610
doCreateGridControl @ editorPart.js:589
createContentArea @ editorPart.js:572
create @ part.js:38
forEach @ workbench.js:189
renderWorkbench @ workbench.js:181
instantiationService.invokeFunction.accessor @ workbench.js:81
invokeFunction @ instantiationService.js:37
startup @ workbench.js:68
dom_1.domContentLoaded.then @ main.js:62
Promise.then (async)
initServices.then.services @ main.js:52
Promise.then (async)
open @ main.js:51
main @ main.js:232
(anonymous) @ workbench.js:30
Promise.then (async)
bootstrapWindow.load.removeDeveloperKeybindingsAfterLoad @ workbench.js:26
result @ /Users/jrieken/Code/vscode/out/bootstrap-window.js:132
Module._invokeFactory @ /Users/jrieken/Code/vscode/out/vs/loader.js:993
Module.complete @ /Users/jrieken/Code/vscode/out/vs/loader.js:1003
ModuleManager._onModuleComplete @ /Users/jrieken/Code/vscode/out/vs/loader.js:1603
ModuleManager._onModuleComplete @ /Users/jrieken/Code/vscode/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/jrieken/Code/vscode/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/jrieken/Code/vscode/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/jrieken/Code/vscode/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/jrieken/Code/vscode/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/jrieken/Code/vscode/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/jrieken/Code/vscode/out/vs/loader.js:1615
ModuleManager._onModuleComplete @ /Users/jrieken/Code/vscode/out/vs/loader.js:1615
ModuleManager._resolve @ /Users/jrieken/Code/vscode/out/vs/loader.js:1565
ModuleManager.defineModule @ /Users/jrieken/Code/vscode/out/vs/loader.js:1229
load @ /Users/jrieken/Code/vscode/out/vs/loader.js:1500
(anonymous) @ css.js:103
BrowserCSSLoader._onLoad @ css.js:45
callback @ css.js:68
loadEventListener @ css.js:34
load (async)
BrowserCSSLoader.attachListeners @ css.js:40
BrowserCSSLoader.createLinkTag @ css.js:70
BrowserCSSLoader.load @ css.js:90
CSSPlugin.load @ css.js:102
ModuleManager._loadPluginDependency @ /Users/jrieken/Code/vscode/out/vs/loader.js:1505
ModuleManager._resolve @ /Users/jrieken/Code/vscode/out/vs/loader.js:1549
ModuleManager.defineModule @ /Users/jrieken/Code/vscode/out/vs/loader.js:1229
ModuleManager._onLoad @ /Users/jrieken/Code/vscode/out/vs/loader.js:1306
(anonymous) @ /Users/jrieken/Code/vscode/out/vs/loader.js:1476
OnlyOnceScriptLoader.triggerCallback @ /Users/jrieken/Code/vscode/out/vs/loader.js:594
(anonymous) @ /Users/jrieken/Code/vscode/out/vs/loader.js:588
NodeScriptLoader._loadAndEvalScript @ /Users/jrieken/Code/vscode/out/vs/loader.js:814
(anonymous) @ /Users/jrieken/Code/vscode/out/vs/loader.js:780
readFileAfterClose @ fs.js:440
extensionService.js:643 [jonkwheeler.styled-components-snippets]: Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
```

**Comment by jonkwheeler** [comment]
That was me trying to mess with this. Let me remove it, and see if that helps this lag.

![sc-lag 2019-05-06 16_35_42](https://user-images.githubusercontent.com/3136271/57236500-1cbcab80-701d-11e9-9a4b-fa55daf49061.gif)

**Comment by jonkwheeler** [comment]
v0.2.8 going up

**Comment by jonkwheeler** [comment]
Really odd to see in your terminal 
```
Unknown language in `contributes.styled-components-snippets.language`. Provided value: styled-css
```

That shows as a legit language in vscode. 
![styled-css 2019-05-06 16_51_58](https://user-images.githubusercontent.com/3136271/57237580-6dcd9f00-701f-11e9-8cc2-92ea6741dc9d.gif)

**Comment by jonkwheeler** [comment]
@jrieken any insight here? 🤠

2 Things.

1. The snippets take over 10 seconds to show up, each time a component is created.
2. Your error is displaying an language as unknown even though vscode says it's legit. How can I view these messages you're receiving?

**Comment by jrieken** [comment]
1) that can happen when another extension takes its time to compute suggestions. generally we wait for all suggestions to be computed before showing them

2) that happens when the language that is being referred to hasn't been registered yet, e.g no extension has added this languaging (using the languages-contribution point)
