### ISSUE TITLE
"Error: Failed opening file "C\C++.log" for writing" occurs when createOutputChannel("C/C++") is used

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#73441]
- VSCode Version: 1.33.1
- OS Version: Windows (Linux/Mac too)

Steps to Reproduce:

1. Use our C/C++ extension with a workspace with a .cpp file to activate it and set the C_Cpp.loggingLevel to "Debug" or run the "C/C++: Log Diagnostics" command, which calls code "vscode.window.createOutputChannel("C/C++") or "C/C++ Diagnostics"...or use any extension that does something equivalent.

Bug: VS Code gives some error like the following, which causes users of our extension to be confused/concerned (users send us the error in their bug reports). Changing our code to use "C++" instead fixes the issue, but that is unideal. This a somewhat recent regression over the past few months, but up till now we've just ignored it.

[Extension Host] Error: Failed opening file c:\Users\user\AppData\Roaming\Code\logs\20190506T193340\exthost11\output_logging_20190507T164807\6-C\C++ Diagnostics.log for writing: No such file or directory
	at Object.createRotatingLogger (f:\Program Files\Microsoft VS Code 1.26\resources\app\node_modules.asar\spdlog\index.js:34:9)
	at Object.t.createRotatingLogger (f:\Program Files\Microsoft VS Code 1.26\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:290:530)
	at new r (f:\Program Files\Microsoft VS Code 1.26\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:629:222)
	at f:\Program Files\Microsoft VS Code 1.26\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:631:639
	at Generator.next (<anonymous>)
	at s (f:\Program Files\Microsoft VS Code 1.26\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:11:9) (at f:\Program Files\Microsoft VS Code 1.26\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:631:716)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Looks like a spdy log exception, forwarding to @sandy081

**Comment by sandy081** [comment]
It's failing because of not escaping the name. But it is not blocking in creating or using the channel as we fallback to another approach.

**Comment by sandy081** [comment]
To verify, create a sample extension that creates an output channel with name that has characters not supported in windows file names. Eg: `vscode.window.createOutputChannel('C/C++');`

Make sure no errors are seen in the console.
