### ISSUE TITLE
Blank screen when I updated to 1.33.1-1

### ISSUE THREAD

**Issue by MrZeusTheCoder** [microsoft/vscode#73498]
- VSCode Version: 1.33
- OS Version: Manjaro Linux; Linux 419 kernel

Steps to Reproduce:

1. Install on Manjaro via `pacman -S code`
2. Open VS Code.

Does this issue occur when all extensions are disabled?: Yes

Here is a screen shot of it:
![Screenshot from 2019-05-08 20-39-40](https://user-images.githubusercontent.com/37903528/57417211-93020f00-71d1-11e9-924a-011cb95db794.png)

And here is the verbose output from `code --disable-extentions --disable-gpu --verbose`:
```
[5719:0508/203607.919544:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.
Error: /usr/lib/code/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: undefined symbol: _ZN2v811HandleScope12CreateHandleEPNS_8internal24NeverReadOnlySpaceObjectEPNS1_6ObjectE
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at n (/usr/lib/code/out/vs/loader.js:15:874)
    at bindings (/usr/lib/code/node_modules.asar/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/lib/code/node_modules.asar/spdlog/index.js:3:35)
    at Object.<anonymous> (/usr/lib/code/node_modules.asar/spdlog/index.js:40:3)
    at Module.r._compile (/usr/lib/code/out/vs/loader.js:16:90)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Function.i [as __$__nodeRequire] (/usr/lib/code/out/vs/loader.js:31:542)
    at Object.t.createSpdLogService (/usr/lib/code/out/vs/code/electron-main/main.js:235:701)
    at then.then.e (/usr/lib/code/out/vs/code/electron-main/main.js:489:416)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[main 2019-05-09T00:36:08.010Z] Starting VS Code
[main 2019-05-09T00:36:08.011Z] from: /usr/lib/code
[main 2019-05-09T00:36:08.011Z] args: { _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  version: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  verbose: true,
  status: false,
  'prof-modules': false,
  'prof-startup': false,
  'disable-extensions': false,
  'disable-gpu': true,
  logExtensionHostCommunication: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  nolazy: false,
  issue: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'prof-code-loading': false,
  nodeless: false,
  'disable-extentions': true }
[main 2019-05-09T00:36:08.012Z] Resolving machine identifier...
[main 2019-05-09T00:36:08.012Z] Resolved machine identifier: f361b72cfac72643ae98a50eec310013368d623d60e6e141af4ac761cdd74b66
[main 2019-05-09T00:36:08.044Z] update#ctor - updates are disabled as there is no update URL
[main 2019-05-09T00:36:08.054Z] windowsManager#open
Error: /usr/lib/code/node_modules.asar.unpacked/native-keymap/build/Release/keymapping.node: undefined symbol: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at n (/usr/lib/code/out/vs/loader.js:15:874)
    at NativeBinding._init (/usr/lib/code/node_modules.asar/native-keymap/index.js:15:22)
    at NativeBinding.onDidChangeKeyboardLayout (/usr/lib/code/node_modules.asar/native-keymap/index.js:37:10)
    at Object.exports.onDidChangeKeyboardLayout (/usr/lib/code/node_modules.asar/native-keymap/index.js:61:18)
    at r.onDidChangeKeyboardLayout (/usr/lib/code/out/vs/code/electron-main/main.js:183:447)
    at t.afterWindowOpen (/usr/lib/code/out/vs/code/electron-main/main.js:482:728)
    at e.invokeFunction.e (/usr/lib/code/out/vs/code/electron-main/main.js:476:80)
    at u.invokeFunction (/usr/lib/code/out/vs/code/electron-main/main.js:221:103)
    at initServices.then.e (/usr/lib/code/out/vs/code/electron-main/main.js:476:57)
[main 2019-05-09T00:36:08.150Z] [storage state.vscdb] open(/home/zeus/.config/Code - OSS/User/globalStorage/state.vscdb, retryOnBusy: true)
[main 2019-05-09T00:36:08.153Z] [storage state.vscdb] open(): Unable to open DB due to [object Object]
[main 2019-05-09T00:36:08.154Z] [storage state.vscdb] open(): Unable to use backup due to Error: ENOENT: no such file or directory, unlink '/home/zeus/.config/Code - OSS/User/globalStorage/state.vscdb'
[5757:0508/203608.213115:ERROR:gl_implementation.cc(292)] Failed to load /usr/lib/electron/swiftshader/libGLESv2.so: /usr/lib/electron/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[5757:0508/203608.214300:ERROR:viz_main_impl.cc(195)] Exiting GPU process due to errors during initialization
[5719:0508/203608.528514:INFO:CONSOLE(7)] "Loading "node-pty" failed", source: /usr/lib/code/out/vs/loader.js (7)
[5719:0508/203608.528540:INFO:CONSOLE(7)] "Detail: ", source: /usr/lib/code/out/vs/loader.js (7)
[5719:0508/203608.536434:INFO:CONSOLE(7)] "Error: Cannot find module '../build/Debug/pty.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at n (/usr/lib/code/out/vs/loader.js:15:874)
    at Object.loadNative (/usr/lib/code/node_modules.asar/node-pty/lib/utils.js:22:16)
    at Object.<anonymous> (/usr/lib/code/node_modules.asar/node-pty/lib/unixTerminal.js:24:19)
    at Object.<anonymous> (/usr/lib/code/node_modules.asar/node-pty/lib/unixTerminal.js:255:3)
    at Module.r._compile (/usr/lib/code/out/vs/loader.js:16:90)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at n (/usr/lib/code/out/vs/loader.js:15:874)
    at Object.<anonymous> (/usr/lib/code/node_modules.asar/node-pty/lib/index.js:14:20)
    at Object.<anonymous> (/usr/lib/code/node_modules.asar/node-pty/lib/index.js:52:3)
    at Module.r._compile (/usr/lib/code/out/vs/loader.js:16:90)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at i (/usr/lib/code/out/vs/loader.js:31:542)
    at t.load (/usr/lib/code/out/vs/loader.js:16:449)
    at e.load (/usr/lib/code/out/vs/loader.js:13:866)
    at i (/usr/lib/code/out/vs/loader.js:28:617)
    at Object.errorback (/usr/lib/code/out/vs/loader.js:28:738)
    at e.triggerErrorback (/usr/lib/code/out/vs/loader.js:14:230)
    at /usr/lib/code/out/vs/loader.js:13:936
    at t.load (/usr/lib/code/out/vs/loader.js:16:478)
    at e.load (/usr/lib/code/out/vs/loader.js:13:866)
    at i (/usr/lib/code/out/vs/loader.js:28:617)
    at s._loadModule (/usr/lib/code/out/vs/loader.js:28:747)
    at s._resolve (/usr/lib/code/out/vs/loader.js:30:166)
    at s.defineModule (/usr/lib/code/out/vs/loader.js:24:768)
    at r (/usr/lib/code/out/vs/loader.js:31:950)
    at f (/usr/lib/code/out/vs/loader.js:17:524)
    at Object.<anonymous> (file:///usr/lib/code/out/vs/workbench/workbench.main.js:2752:1)
    at Object.<anonymous> (file:///usr/lib/code/out/vs/workbench/workbench.main.js:5663:715)
    at t._loadAndEvalScript (/usr/lib/code/out/vs/loader.js:17:568)
    at /usr/lib/code/out/vs/loader.js:17:196
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)", source: /usr/lib/code/out/vs/loader.js (7)
[5719:0508/203608.536461:INFO:CONSOLE(7)] "Here are the modules that depend on it:", source: /usr/lib/code/out/vs/loader.js (7)
[5719:0508/203608.536479:INFO:CONSOLE(7)] "vs/workbench/contrib/terminal/node/terminalProcess", source: /usr/lib/code/out/vs/loader.js (7)
[5719:0508/203611.362865:INFO:CONSOLE(181)] "Error: /usr/lib/code/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: undefined symbol: _ZN2v811HandleScope12CreateHandleEPNS_8internal24NeverReadOnlySpaceObjectEPNS1_6ObjectE", source: file:///usr/lib/code/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (181)
[5719:0508/203611.366098:INFO:CONSOLE(181)] "Error: /usr/lib/code/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node: undefined symbol: _ZN2v811HandleScope12CreateHandleEPNS_8internal24NeverReadOnlySpaceObjectEPNS1_6ObjectE", source: file:///usr/lib/code/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (181)
```

Others seem to have this issue (seen here https://github.com/headmelted/codebuilds/issues/64#issuecomment-489349502 guessing by the timestamps).

I have not tried the insiders version, but I may try it tomorrow. Other than that all I can say is great work, guys! I love the tool! So keep it up :+1:

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by tuonium** [comment]
Last working version I can build on Raspbian is 1.29. Same issue. Black screen even with gpu support disabled. The last working headmelted build for me was also 1.29. These are of course arm builds.

**Comment by MrZeusTheCoder** [comment]
@bpasero The insider build worked.

**Comment by MrZeusTheCoder** [comment]
After I ran the insiders build 1.32 opened to a blank screen, but once I was updated to 1.33 it once again opened normally. ¯\_(ツ)_/¯
