### ISSUE TITLE
Invoking the terminal sometimes yields an error "Cannot set property 'innerHTML' of undefined"

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/vscode#7357]
- VSCode Version: 1.2.0-insider
- OS Version: Windows 10
- Git Bash Shell (relevant?) 

Steps to Reproduce:

This only happens sometimes and is perhaps secondary to #7345?

1. <kbd>Ctrl</kbd>+<kbd>~</kbd> to invoke the integrated terminal
2. See that the terminal is invoked but blank and that this error popup is displayed:

![image](https://cloud.githubusercontent.com/assets/17498172/15873967/02c716b4-2ccf-11e6-9a23-8f83b209960b.png)

**Comment by Tyriar** [comment]
I just hit this on Linux, here's a trace:

```
//usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:87 Cannot set property 'innerHTML' of undefined: TypeError: Cannot set property 'innerHTML' of undefined
    at Terminal.refresh (/usr/share/code-insiders/resources/app/node_modules/term.js/src/term.js:1704:32)
    at t.setTheme (file:////usr/share/code-insiders/resources/app/out/vs/workbench/parts/terminal/electron-browser/terminalPanel.js:4:4880)
    at t.updateTheme (file:////usr/share/code-insiders/resources/app/out/vs/workbench/parts/terminal/electron-browser/terminalPanel.js:4:8268)
    at t.setVisible (file:////usr/share/code-insiders/resources/app/out/vs/workbench/parts/terminal/electron-browser/terminalPanel.js:4:7538)
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:89:7842
    at __dirname.undefined.t.Class.define.then (file:////usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:23:19425)
    at t.showComposite (file:////usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:89:7037)
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:89:5287
    at __dirname.undefined.t.Class.define.then (file:////usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:23:19425)
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:89:5042
```

**Comment by Tyriar** [comment]
This looks like an upstream but with term.js, I'll diff the code with what we're moving towards (xterm.js) and see if the bug is present in that too.

**Comment by Tyriar** [comment]
This will be fixed when https://github.com/Microsoft/vscode/pull/7288 is merged as it's no longer necessary to call refresh to update the theme.
