### ISSUE TITLE
spawn ENOTDIR on ⌘P

### ISSUE THREAD

**Issue by jimbomorrison** [microsoft/vscode#73761]
Issue Type: <b>Bug</b>

I'm getting a consistent "spawn ENOTDIR" on ⌘P searches.

It appears to occur on larger projects - accessed remotely.

 - smb mount - occurs.
 - sshfs mount - occurs.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|-psn_0_69649|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.7
vscode-eslint|dba|1.9.0
vscode-html-css|ecm|0.2.0
gitlab-workflow|fat|2.1.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vue-snippets|hol|0.1.11
mysql-syntax|jak|1.3.1
vue|liu|0.1.5
php-docblocker|nei|1.8.0
vetur|oct|0.20.0
php-formatter|Sop|0.2.4

</details>

**Comment by roblourens** [comment]
Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by jimbomorrison** [comment]
Been on leave - sorry @roblourens 

Not sure whether etiquette is to re-raise or [if I can] re-open.  Output as follows:

```
[2019-05-28 11:13:06.359] [renderer4] [trace] CommandService#executeCommand editor.action.clearoutput
[2019-05-28 11:13:06.359] [renderer4] [trace] telemetry/workbenchActionExecuted {"id":"editor.action.clearoutput","from":"contextMenu"}
[2019-05-28 11:13:11.926] [renderer4] [trace] CommandService#executeCommand workbench.action.quickOpen
[2019-05-28 11:13:11.929] [renderer4] [trace] telemetry/workbenchActionExecuted {"id":"workbench.action.quickOpen","from":"keybinding"}
[2019-05-28 11:13:11.929] [renderer4] [trace] SearchService#search {"_reason":"openFileHandler","folderQueries":[{"folder":{"$mid":1,"fsPath":"/Volumes/jim/spirit","external":"file:///Volumes/jim/spirit","path":"/Volumes/jim/spirit","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"fsPath":"/Volumes/jim/r","external":"file:///Volumes/jim/r","path":"/Volumes/jim/r","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"fsPath":"/Volumes/jim/bin","external":"file:///Volumes/jim/bin","path":"/Volumes/jim/bin","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false}],"usingSearchPaths":false,"maxResults":0,"type":1,"filePattern":"","sortByScore":true,"cacheKey":"id#18"}
[2019-05-28 11:13:11.935] [renderer4] [debug] SearchService#search rg --files --hidden --case-sensitive -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/node_modules' -g '!**/bower_components' --no-ignore-parent --follow --no-config --no-ignore-global
 - cwd: /Volumes/jim/spirit
 - Sibling clauses: {}
[2019-05-28 11:13:11.937] [renderer4] [debug] SearchService#search rg --files --hidden --case-sensitive -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/node_modules' -g '!**/bower_components' --no-ignore-parent --follow --no-config --no-ignore-global
 - cwd: /Volumes/jim/r
 - Sibling clauses: {}
[2019-05-28 11:13:12.622] [renderer4] [trace] SearchService#search {"_reason":"openFileHandler","folderQueries":[{"folder":{"$mid":1,"fsPath":"/Volumes/jim/spirit","external":"file:///Volumes/jim/spirit","path":"/Volumes/jim/spirit","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"fsPath":"/Volumes/jim/r","external":"file:///Volumes/jim/r","path":"/Volumes/jim/r","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"fsPath":"/Volumes/jim/bin","external":"file:///Volumes/jim/bin","path":"/Volumes/jim/bin","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false}],"usingSearchPaths":false,"maxResults":512,"type":1,"filePattern":"te","sortByScore":true,"cacheKey":"id#13"}
[2019-05-28 11:13:12.624] [renderer4] [trace] SearchService#search: 3ms
[2019-05-28 11:13:12.904] [renderer4] [trace] SearchService#search {"_reason":"openFileHandler","folderQueries":[{"folder":{"$mid":1,"fsPath":"/Volumes/jim/spirit","external":"file:///Volumes/jim/spirit","path":"/Volumes/jim/spirit","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"fsPath":"/Volumes/jim/r","external":"file:///Volumes/jim/r","path":"/Volumes/jim/r","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"fsPath":"/Volumes/jim/bin","external":"file:///Volumes/jim/bin","path":"/Volumes/jim/bin","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false}],"usingSearchPaths":false,"maxResults":512,"type":1,"filePattern":"test","sortByScore":true,"cacheKey":"id#13"}
[2019-05-28 11:13:14.127] [renderer4] [trace] SearchService#search: 2197ms
[2019-05-28 11:13:14.127] [renderer4] [error] spawn ENOTDIR: Error: spawn ENOTDIR
    at Object.t.deserializeSearchError (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3867:8)
    at Promise.all.then.t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4521:246)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-05-28 11:13:14.281] [renderer4] [trace] SearchService#search: 1376ms
[2019-05-28 11:13:19.127] [renderer4] [trace] telemetry/UnhandledError {"msg":"spawn ENOTDIR","callstack":"Error: spawn ENOTDIR\n    at Object.t.deserializeSearchError (out/vs/workbench/workbench.main.js:3867:8)\n    at Promise.all.then.t (out/vs/workbench/workbench.main.js:4521:246)\n    at process._tickCallback (<REDACTED: user-file-path>:68:7)","count":1}
[2019-05-28 11:13:24.965] [renderer4] [trace] CommandService#executeCommand notification.clear
[2019-05-28 11:13:24.966] [renderer4] [trace] telemetry/workbenchActionExecuted {"id":"notification.clear","from":"message"}
[2019-05-28 11:13:32.356] [renderer4] [trace] CommandService#executeCommand editor.action.selectAll
[2019-05-28 11:13:32.357] [renderer4] [trace] telemetry/workbenchActionExecuted {"id":"editor.action.selectAll","from":"keybinding"}
[2019-05-28 11:13:33.290] [renderer4] [trace] CommandService#executeCommand editor.action.clipboardCopyAction
```

**Comment by roblourens** [comment]
How is /Volumes/jim/spirit mounted, smb? Guessing that for some reason ripgrep thinks that is not a normal folder.

If you are using sshfs you can try out the Remote-SSH extension instead: https://code.visualstudio.com/docs/remote/ssh

**Comment by jimbomorrison** [comment]
I normally use sshfs (as in this report) but have tried a samba mount too with the same results ((cosmetically) would you like the same debugging run with smb to check?)... 

I will take a look at Remote-SSH and report back.  Thanks.

**Comment by jimbomorrison** [comment]
`Remote-SSH` works like a charm -- and wow, looks insane so I will be sticking with it.  If you need me to go back at test anything in the old sshfs/smb config just let me know, thanks.

**Comment by roblourens** [comment]
Great! We've had a bunch of hard to understand issues with sshfs. If you aren't using it I will just close this. But if you do go back to that setup we can investigate some more.

**Comment by jimbomorrison** [comment]
Great, thanks Rob. `Remote-SSH` is life-changing already.  I really can't see myself going back. 🙏
