### ISSUE TITLE
terminal configuration tests are failing

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#7408]
workspace test are failing:

```
  1) Workbench - TerminalConfigHelper TerminalConfigHelper - getShell:
     TypeError: Cannot read property 'linux' of undefined
      at TerminalConfigHelper.getShell (out/vs/workbench/parts/terminal/electron-browser/terminalConfigHelper.js:131:66)
      at Context.<anonymous> (out/vs/workbench/parts/terminal/test/terminalConfigHelper.test.js:128:39)
```

**Comment by weinand** [comment]
@Tyriar I've fixed your tests. Please review.

**Comment by Tyriar** [comment]
Fixing now
