### ISSUE TITLE
Continuation of issue #68744 -  Unable to write program user data - erroneous error

### ISSUE THREAD

**Issue by notjames** [microsoft/vscode#74103]
This issue is a continuation of locked issue #68744.

Wasn't able to try this...

- VSCode Version: 1.34.0
- OS Version: Linux distro: Ubuntu version 18.10

Steps to Reproduce:

1.`code .`
2. that's it

Error dialog: Unable to write program user data. Please make sure the .... are writable (see issue 68744)

Does this issue occur when all extensions are disabled?: Yes/No

Issue persists

However, running `code --verbose .` *finally* exposes the real problem:

```
$ code --verbose .                                                                                                                                                             
[25362:0521/220714.680302:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.                       
[main 2019-05-22T05:07:28.018Z] Error: listen EACCES /run/user/1000/snap.tmux/vscode-93e3e801-1.34.0-main.sock                                        
    at Server.setupListenHandle [as _listen2] (net.js:1313:19)                                                                                        
    at listenInCluster (net.js:1378:12)                                                                                                               
    at Server.listen (net.js:1477:5)                                                                                                                  
    at Promise (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:184:637)                                                              
    at new Promise (<anonymous>)                                                                                                                      
    at Object.t.serve (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:184:574)                                                       
    at n (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:490:263)                                                                    
    at R (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:492:559)                                                                    
    at l.invokeFunction (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:221:331)                                                     
    at then (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:494:347)                                                                 
[main 2019-05-22T05:07:28.020Z] Lifecycle#kill()
```

NAMELY: `Error: listen EACCES /run/user/1000/snap.tmux/vscode-93e3e801-1.34.0-main.sock`

The root cause of this particular issue was the inadvertent removal of the tmux socket file. I had to restart tmux. Killing tmux and starting code from tilix/konsole worked fine.

The error dialog is misleading. I have wasted an hour trying to fix this problem. Please fix the error output.

**Comment by joaomoreno** [comment]
> The root cause of this particular issue was the inadvertent removal of the tmux socket file. 

What do you mean?

**Comment by notjames** [comment]
No. I'm still not sure what the issue is with the socket file missing during a tmux session. I misstated that sentence somewhat as there was probably not an "inadvertent removal" of the socket file. I'll have to troubleshoot that more.

For some yet to be determined reason, when I attempt to start vscode from within a tmux session, vscode attempts to access its socket file from the directory listed above. There may be two different issues, possibly three, here. The only relevant one with respect to this issue is the misleading error in the dialog box. In short, however, I'm not able to launch vscode from within a tmux session. The other possible to issues is 1) something is misplacing the socket file or 2) tmux is doing something wonky with access to the socket file. When I ran the brief tests the other night, the socket file did not exist in the `/run/user/1000` path.

**Comment by joaomoreno** [comment]
What's the `XDG_RUNTIME_DIR` env value both outside and inside tmux?

**Comment by notjames** [comment]
They are both `/run/user/1000`

**Comment by joaomoreno** [comment]
The error dialog is correct. If Code can't write to the user data dir, that is the most severe error, independently of the root cause.

**Comment by notjames** [comment]
I completely disagree with respect to the "user data dir" because the dialog specifically states two completely invalid directories, specifically `/home/<user>/.config/Code` and `/home/<user>/.vscode` *neither* of which were the problem in my case. In my case the issue was in `/run/user/<user_id>`. The error code is misleading and makes for a poor user experience.

**Comment by joaomoreno** [comment]
I see. Let me check, then.
