### ISSUE TITLE
mocha unit test Error: Cannot find module 'vscode'

### ISSUE THREAD

**Issue by mdt123** [microsoft/vscode#74576]
I am working on a vscode extension, and I am using mocha for unit tests. However, I am having issues with the 'vscode' import in the modules that uses it.

I have tried to have the test file in the same directory as the source file, however this did not help.

        //mod.ts
        import * as vscode from 'vscode';

        export class mod {
            foo() {
                return vscode.StatusBarAlignment.Left.toString();
            }
        }

        //test.ts
        import * as mod from './mod';

        describe('tests', () => {
	        it('test', () => {
		        var mo = new mod.mod();
		        assert.equal(mo.foo().length > 0, true, "Incorrect");
	        });
        });

This is the generated error:

```
 Error: Cannot find module 'vscode'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\repo\src\mod.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (C:\Users\repo\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\repo\node_modules\ts-        node\src\index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (c:\Users\repo\src\extension.test.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (C:\Users\repo\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\repo\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at C:\Users\repo\node_modules\mocha\lib\mocha.js:330:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\repo\node_modules\mocha\lib\mocha.js:327:14)
    at Mocha.run (C:\Users\repo\node_modules\mocha\lib\mocha.js:804:10)
    at Object.exports.singleRun (C:\Users\repo\node_modules\mocha\lib\cli\run-helpers.js:207:16)
    at exports.runMocha (C:\Users\repo\node_modules\mocha\lib\cli\run-helpers.js:300:13)
    at Object.exports.handler.argv [as handler] (C:\Users\repo\node_modules\mocha\lib\cli\run.js:296:3)
    at Object.runCommand (C:\Users\repo\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (C:\Users\repo\node_modules\yargs\yargs.js:1087:28)
    at Object.parse (C:\Users\repo\node_modules\yargs\yargs.js:566:25)
    at Object.exports.main (C:\Users\repo\node_modules\mocha\lib\cli\cli.js:63:6)
    at Object.<anonymous> (C:\Users\repo\node_modules\mocha\bin\_mocha:10:23)
    at Module._compile (internal/modules/cjs/loader.js:698:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by mjbvz** [comment]
Are you trying to run the tests using mocha directly? Or are you using the `vscode` `test` script generated in extensions?

**Comment by mdt123** [comment]
I am running the testes on debug mode using mocha:
`C:\Program Files\nodejs\node.exe --inspect-brk=40665 node_modules\mocha\bin\_mocha --require ts-node/register --require ts-node/register --timeout 999999 --colors C:\Users\t-ouhadd\Desktop\repositories\VSCode-SystemVerilog/test/*.test.ts`

**Comment by octref** [comment]
Your mocha tests needs to be in the test runner for it to access `vscode` API. You can find more info in the upcoming, not-yet-released docs.

[Release notes](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_35.md#splitting-vscode-package-into-typesvscode-and-vscode-test) | [Docs](https://github.com/microsoft/vscode-docs/blob/vnext/api/working-with-extensions/testing-extension.md)
