### ISSUE TITLE
Cannot find module: lazystream

### ISSUE THREAD

**Issue by tincho** [microsoft/vscode#74705]
- VSCode Version: latest from master (1.35.0)
- OS Version: Ubuntu 18.04, NodeJS 10.14.2 (via NVM)

Yarn version 1.10.1

Steps to Reproduce:

1. clone && cd ...
2. yarn
3. yarn watch

```
yarn watch
yarn run v1.10.1
$ gulp watch --max_old_space_size=4095
[23:09:15] Node flags detected: --max_old_space_size=4095
[23:09:15] Respawned to PID: 17636
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'lazystream'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/tin/Programas/vscode/node_modules/vinyl-fs/lib/src/read-contents/read-stream.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

Hi there! I always re-build vscode after git pulling the latest version. Recently I've been running into the above error .
Tried to `yarn add lazystream` but same results

Any ideas?

**Comment by mjbvz** [comment]
Which commit are you on from the VS Code repo?
