### ISSUE TITLE
 'All References' to 'app' smoketest failure

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#74702]
**Repo**
1. Run smoketest on latest insiders

**Bug**

```
  1) Running Code
       Editor
         finds 'All References' to 'app':
     Error: Timeout: get elements '.monaco-editor .zone-widget .zone-widget-container.peekview-widget.reference-zone-widget.results-loaded .body .ref-tree.inline .monaco-list-row .reference' after 20 seconds.
      at /Users/matb/projects/vscode/test/smoke/out/vscode/code.js:158:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)
```

**Comment by mjbvz** [comment]
The UI seems to be showing the correct thing, so this just looks like a test failure to me
