### ISSUE TITLE
html failed to save

### ISSUE THREAD

**Issue by threethreenine** [microsoft/vscode#74774]
Issue Type: <b>Bug</b>

Issue Type: Bug

step 1 : modifying and save '.html' files , 
step 2 , 3, or 4 :  only to save, file content is missing;

Notice:
        Failed to save "example.html": Unable to write to file (Unknown (FileSystemError): Error: EBUSY: resource busy or locked, open 'e:\example.html')

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.3.6
css-compressor|bes|0.0.2
gltf-vscode|ces|2.2.5
npm-intellisense|chr|1.3.0
jsrefactor|cms|2.18.2
vscode-devtools-for-chrome|cod|0.0.5
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.0
es7-react-js-snippets|dsz|2.3.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.7
code-runner|for|0.9.10
beautify|Hoo|1.5.0
emoji-code|idl|0.7.5
compareit|in4|0.0.2
docthis|joe|0.7.1
vscode-language-pack-zh-hans|MS-|1.34.2
python|ms-|2019.5.17517
cpptools|ms-|0.23.1
csharp|ms-|1.19.1
vscode-typescript-tslint-plugin|ms-|1.1.0
debugger-for-chrome|msj|4.11.3
color-highlight|nau|2.3.0
vetur|oct|0.21.0
open-html-in-browser|pea|1.2.0
LiveServer|rit|5.6.1
indenticator|Sir|0.6.0
code-spell-checker|str|1.7.12
vscodeintellicode|Vis|1.1.6
vscode-icons|vsc|8.7.0
quokka-vscode|Wal|1.0.222
wallaby-vscode|Wal|1.0.128
JavaScriptSnippets|xab|1.7.2

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
@threethreenine are you possibly having the integrated terminal open with powershell? Does it reproduce if you just start (with no panel visible) and save?

**Comment by threethreenine** [comment]
@bpasero 

Is the log information?
I saw that the log recorded a variable undefined, and I failed to save the HTML file.
The following is the log I copied.

[2019-06-06 14:13:41.039] [renderer6] [error] Unable to write to file (Unknown (FileSystemError): Error: EBUSY: resource busy or locked, open 'e:\ThreeJSProjects\three.js\examples\webgl_lines_colors.html'): Error: Unable to write to file (Unknown (FileSystemError): Error: EBUSY: resource busy or locked, open 'e:\ThreeJSProjects\three.js\examples\webgl_lines_colors.html')
    at b.<anonymous> (file:///D:/ProgramFiles/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3339:893)
    at Generator.throw (<anonymous>)
    at a (file:///D:/ProgramFiles/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:34:505)


[2019-06-06 14:18:03.570] [renderer6] [error] Cannot read property 'peekBack' of undefined: TypeError: Cannot read property 'peekBack' of undefined
	at IndentSpy._peekBack (C:\Users\SDF\.vscode\extensions\sirtori.indenticator-0.6.0\out\src\extension.js:250:28)
	at IndentSpy._buildHoverString (C:\Users\SDF\.vscode\extensions\sirtori.indenticator-0.6.0\out\src\extension.js:234:35)
	at IndentSpy._buildHoverprovider (C:\Users\SDF\.vscode\extensions\sirtori.indenticator-0.6.0\out\src\extension.js:215:28)
	at Object.provideHover (C:\Users\SDF\.vscode\extensions\sirtori.indenticator-0.6.0\out\src\extension.js:205:29)
	at define.provideHover.a.asPromise (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:479)
	at t.asPromise.Promise (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:53:320)
	at new Promise (<anonymous>)
	at Object.t.asPromise (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:53:292)
	at S.provideHover (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:575:450)
	at define.$provideHover._withAdapter.e (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:592:165)
	at j._withAdapter (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:588:126)
	at j.$provideHover (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:592:143)
	at d._doInvokeHandler (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:1006)
	at d._invokeHandler (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:698)
	at d._receiveRequest (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:293)
	at d._receiveOneMessage (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:642:141)
	at define.constructor._protocol.onMessage.e (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:640:400)
	at u.fire (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
	at a (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:176:766)
	at e (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:176:812)
	at u.fire (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
	at n.constructor.e.onMessage.e (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:748:721)
	at u.fire (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
	at a (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:176:766)
	at e (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:176:812)
	at u.fire (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
	at y._receiveMessage (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:185:670)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:981)
	at u.fire (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
	at f.acceptChunk (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:179:532)
	at define.constructor._register._socket.onData.e (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:869)
	at Socket.t (d:\ProgramFiles\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:187:141)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)

**Comment by bpasero** [comment]
@threethreenine are you possibly having the integrated terminal open with powershell?

**Comment by threethreenine** [comment]
@bpasero i have the integrated terminal open with powershell.
However, when I press ‘ctrl + s’ to save the HTML file, there is no situation in powershell.

**Comment by bpasero** [comment]
@threethreenine does it reproduce if you close the terminal in VSCode, restart VSCode and then save?

**Comment by threethreenine** [comment]
@bpasero 
After closing the terminal panel, I press 'ctrl+s' consecutively, the html file will suddenly become blank.  Just don't report the wrong error in file saving.
When I restart VSCode, it will still reappear.

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by threethreenine** [comment]
When I used the  newer version of our UI framework ( Electron version 4.0.x) in Windows 10 system,It did not produces  again.

**Comment by threethreenine** [comment]
@bpasero

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/

**Comment by threethreenine** [comment]
Thank you very much, this is great.
