### ISSUE TITLE
Terminal is blank after restoring window

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#74786]
Issue Type: <b>Bug</b>

After minimizing the VS Code window, then at some point restoring it, the terminal panel will be blank - I cannot enter any commands nor see any output. I have to kill the window (click the Trash icon), and reopen a new terminal. Unfortunately I cannot reproduce it on demand, but it has happened frequently, recently.

VS Code version: Code - Insiders 1.35.0-insider (0284236851a94b116f468345f6e98688a737015d, 2019-05-31T21:28:16.350Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (0.12GB free)|
|Process Argv|-psn_0_3396413|
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.800.0
path-intellisense|chr|1.4.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
output-colorizer|IBM|0.1.2
Angular2|joh|7.1.6
azure-account|ms-|0.8.4
csharp|ms-|1.19.1
vscode-typescript-tslint-plugin|ms-|1.1.0
debugger-for-chrome|msj|4.11.3
vetur|oct|0.21.0
material-icon-theme|PKi|3.8.0
quicktype|qui|12.0.46
vue-vscode-snippets|sdr|1.6.0
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.6

(3 theme extensions excluded)

</details>

**Comment by jtsom** [comment]
Different issue, not Windows.

**Comment by Tyriar** [comment]
The next time it happens could you check the devtools console for any errors and post it here? That will likely point to what the problem is.

**Comment by jtsom** [comment]
It did just happen again - unfortunately I forgot to check the console, and I didn't at first notice the terminal window was blank. I did resize it and the text did come back. I will keep an eye out.

**Comment by jtsom** [comment]
Just happened again, after restoring the window. This is all that was in the dev console:
```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:238 [Extension Host] Trace: BAD uri lacks scheme, falling back to file-scheme.
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:120:484
	at new f (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:120:557)
	at new m (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:122:853)
	at Function.parse (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:122:157)
	at nullConverter (/Users/johntsombakos/.vscode-insiders/extensions/octref.vetur-0.21.0/node_modules/vscode-languageclient/lib/protocolConverter.js:22:47)
	at asLocation (/Users/johntsombakos/.vscode-insiders/extensions/octref.vetur-0.21.0/node_modules/vscode-languageclient/lib/protocolConverter.js:313:34)
	at locations.map (/Users/johntsombakos/.vscode-insiders/extensions/octref.vetur-0.21.0/node_modules/vscode-languageclient/lib/protocolConverter.js:356:52)
	at Array.map (<anonymous>)
	at asLocationResult (/Users/johntsombakos/.vscode-insiders/extensions/octref.vetur-0.21.0/node_modules/vscode-languageclient/lib/protocolConverter.js:356:34)
	at asDefinitionResult (/Users/johntsombakos/.vscode-insiders/extensions/octref.vetur-0.21.0/node_modules/vscode-languageclient/lib/protocolConverter.js:325:16) (at Console.trace (console.js:253:8))
t.log @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:238
```

**Comment by Tyriar** [comment]
I suspect this shares the same root cause as https://github.com/Microsoft/vscode/issues/69665

**Comment by jtsom** [comment]
FWIW - I checked and I did have that setting enabled - terminal.integrated.experimentalRefreshOnResume
while I  was seeing that issue.

**Comment by Tyriar** [comment]
@jtsom that setting will only do something after the OS resumes though, not when restoring the window from being minimized.
