### ISSUE TITLE
Build error: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by Ghostium** [microsoft/vscode#74878]
- VSCode Version: Git Master
- OS Version: Debian Stable
- Node Version: v10.16.0
- Yarn Version: 1.16.0
My CI builds are failing, which are built in a Archlinux image but I could reproduce the results in two seperate clean Debian Docker containers.
a848f18df4efa9eb947bd01cbebcede418e66148: works
51d751759de8c79d7e5374877be974660138c00e: error
Steps to reproduce:
1. sudo docker run -it debian:latest bash
2. useradd -m builder
3. apt update -y
4. apt install sudo git curl gcc g++ make python pkg-config libx11-dev libxkbfile-dev libsecret-1-dev -y
5. curl -sL https://deb.nodesource.com/setup_10.x | bash -
6. curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
7. echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
8. apt update -y
9. apt install nodejs yarn -y
10. cd /home/builder
11. sudo -u builder git clone https://github.com/microsoft/vscode
12. cd vscode
13. Either sudo -u builder git checkout -f 51d751759de8c79d7e5374877be974660138c00e or sudo -u builder git checkout -f a848f18df4efa9eb947bd01cbebcede418e66148
14. sudo -u builder yarn
15. sudo -u builder yarn gulp vscode-linux-x64-min

The error for 51d751759de8c79d7e5374877be974660138c00e
```
[07:20:41] Error: ModuleDependencyWarning: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
    at formatError (/home/builder/vscode/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:20:10)
    at Gulp.<anonymous> (/home/builder/vscode/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:31:15)
    at Gulp.emit (events.js:203:15)
    at Gulp.EventEmitter.emit (domain.js:448:20)
    at Object.error (/home/builder/vscode/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/home/builder/vscode/node_modules/now-and-later/lib/map.js:46:14)
    at f (/home/builder/vscode/node_modules/once/once.js:25:25)
    at f (/home/builder/vscode/node_modules/once/once.js:25:25)
    at tryCatch (/home/builder/vscode/node_modules/async-done/index.js:24:15)
    at done (/home/builder/vscode/node_modules/async-done/index.js:40:12)
    at Domain.onError (/home/builder/vscode/node_modules/async-done/index.js:51:5)
    at Object.onceWrapper (events.js:286:20)
    at Domain.emit (events.js:198:13)
    at Domain.EventEmitter.emit (domain.js:448:20)
    at Domain._errorHandler (domain.js:246:21)
    at Object.setUncaughtExceptionCaptureCallback (domain.js:145:29)
```

Build logs:
[51d751759de8c79d7e5374877be974660138c00e.txt](https://github.com/microsoft/vscode/files/3256049/51d751759de8c79d7e5374877be974660138c00e.txt)
[a848f18df4efa9eb947bd01cbebcede418e66148.txt](https://github.com/microsoft/vscode/files/3256050/a848f18df4efa9eb947bd01cbebcede418e66148.txt)

**Comment by Ghostium** [comment]
Update: Something between 51d751759de8c79d7e5374877be974660138c00e 0ac801d9f21554f1c087a5a75b95693b2b37cb71 fixed it.
