### ISSUE TITLE
Search viewlet is broken

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#74947]
Cannot read property 'push' of undefined: TypeError: Cannot read property 'push' of undefined
    at SearchView._register (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/search/browser/searchView.js:1355:33)
    at new Panel (file:///Users/sandy081/work/vscode/out/vs/base/browser/ui/splitview/panelview.js:24:38)
    at new ViewletPanel (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/parts/views/panelViewlet.js:19:13)
    at new SearchView (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/search/browser/searchView.js:20:13)
    at InstantiationService._createInstance (file:///Users/sandy081/work/vscode/out/vs/platform/instantiation/common/instantiationService.js:82:20)
    at InstantiationService.createInstance (file:///Users/sandy081/work/vscode/out/vs/platform/instantiation/common/instantiationService.js:53:31)
    at SearchViewlet.createView (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/parts/views/viewsViewlet.js:130:149)
    at SearchViewlet.onDidAddViews (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/parts/views/viewsViewlet.js:138:36)
    at SearchViewlet.create (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/parts/views/viewsViewlet.js:46:22)
    at SidebarPart.showComposite (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/parts/compositePart.js:120:27)
    at SidebarPart.doOpenComposite (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/parts/compositePart.js:69:18)
    at SidebarPart.openComposite (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/parts/compositePart.js:42:25)
    at SidebarPart.doOpenViewlet (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:148:25)
    at SidebarPart.<anonymous> (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:115:33)
    at Generator.next (<anonymous>)
    at file:///Users/sandy081/work/vscode/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:15:12)
    at SidebarPart.openViewlet (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:113:20)
    at Workbench.<anonymous> (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/workbench.js:259:62)
    at Generator.next (<anonymous>)
    at file:///Users/sandy081/work/vscode/out/vs/workbench/browser/workbench.js:10:71
    at new Promise (<anonymous>)
    at __awaiter (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/workbench.js:6:12)
    at restorePromises.push (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/workbench.js:257:49)
    at Workbench.<anonymous> (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/workbench.js:264:24)
    at Generator.next (<anonymous>)
    at file:///Users/sandy081/work/vscode/out/vs/workbench/browser/workbench.js:10:71
    at new Promise (<anonymous>)
    at __awaiter (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/workbench.js:6:12)
    at Workbench.restoreWorkbench (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/workbench.js:235:20)
    at Workbench.<anonymous> (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/workbench.js:96:36)
    at Generator.next (<anonymous>)
    at file:///Users/sandy081/work/vscode/out/vs/workbench/browser/workbench.js:10:71
    at new Promise (<anonymous>)
    at __awaiter (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/workbench.js:6:12)
    at instantiationService.invokeFunction (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/workbench.js:76:67)
    at InstantiationService.invokeFunction (file:///Users/sandy081/work/vscode/out/vs/platform/instantiation/common/instantiationService.js:37:27)
    at Workbench.startup (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/workbench.js:76:38)
    at CodeRendererMain.<anonymous> (file:///Users/sandy081/work/vscode/out/vs/workbench/electron-browser/main.js:71:61)
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/sandy081/work/vscode/out/vs/workbench/electron-browser/main.js:7:58)

**Comment by mjbvz** [comment]
I pushed a fix for this with https://github.com/microsoft/vscode/commit/b86bdf8a0be2cc9ee243ca72a803f61c43291ce0

3132d268130b22b2870b4e5257e80d23603db5f6, I made `Panel` (which is super class of `SearchView`) extend `Disposable` instead of just implementing `IDisposable`. However I did not realize that a subclass already implemented a `_register` method. This meant that if a superclass of `SearchView` called `_register` in its constructor, it would end up calling that method on the `SearchView` instance which had not been properly initialized yet.
