### ISSUE TITLE
Error while creating new file/folder after focusing on breadcrumbs

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#75038]
![newFileexceptionthrow](https://user-images.githubusercontent.com/25115070/59078377-79bdb280-88a4-11e9-900c-0bd5c660ee99.gif)

**Comment by egamma** [comment]
To reproduce:
- click on the bread crumb item 
- while the bread crump is open click 'create new file' command in the explorer

```
  ERR Cannot read property 'isReadonly' of undefined: TypeError: Cannot read property 'isReadonly' of undefined
    at file:///Users/egamma/Desktop/Visual Studio Code - Insiders 2.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5246:809
    at Generator.next (<anonymous>)
    at file:///Users/egamma/Desktop/Visual Studio Code - Insiders 2.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:34:460
    at new Promise (<anonymous>)
    at n (file:///Users/egamma/Desktop/Visual Studio Code - Insiders 2.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:34:237)
    at Y (file:///Users/egamma/Desktop/Visual Studio Code - Insiders 2.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5246:401)
    at handler (file:///Users/egamma/Desktop/Visual Studio Code - Insiders 2.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5256:947)
    at c.invokeFunction (file:///Users/egamma/Desktop/Visual Studio Code - Insiders 2.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1391:997)
    at Proxy._tryExecuteCommand (file:///Users/egamma/Desktop/Visual Studio Code - Insiders 2.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3034:52)
    at r.then.i (file:///Users/egamma/Desktop/Visual Studio Code - Insiders 2.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3033:717)
```
