### ISSUE TITLE
Downloading extensions from build often fails lately

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#75063]
I am lately often seeing the extensions download fail in our builds making them red, e.g.:

https://dev.azure.com/vscode/VSCode/_build/results?buildId=20286

```
##[section]Starting: Download Built-in Extensions
==============================================================================
Task         : Command Line
Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
Version      : 2.148.0
Author       : Microsoft Corporation
Help         : https://go.microsoft.com/fwlink/?LinkID=613735
==============================================================================
Generating script.
Script contents:
yarn download-builtin-extensions
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /Users/vsts/agent/2.152.1/work/_temp/3d9987e2-38f8-4c1e-820f-26e9389ac9ce.sh
yarn run v1.10.1
$ node build/lib/builtInExtensions.js
[09:52:09] Syncronizing built-in extensions...
[09:52:09] You can manage built-in extensions with the ‌--builtin‌ flag‌
[09:52:09] Downloading extension: ‌ms-vscode.node-debug@1.35.2‌ ...‌
[09:52:09] Downloading extension: ‌ms-vscode.node-debug2@1.33.0‌ ...‌
[09:52:09] Downloading extension: ‌ms-vscode.references-view@0.0.27‌ ...‌
[09:52:10] ‌[marketplace]‌ ms-vscode.references-view ‌✔︎‌
[09:52:11] ‌[marketplace]‌ ms-vscode.node-debug2 ‌✔︎‌
internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^

Error: Request https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/node-debug/1.35.2/vspackage failed with status code:503
    at Request._callback (/Users/vsts/agent/2.152.1/work/1/s/node_modules/gulp-remote-src/index.js:70:33)
    at Request.self.callback (/Users/vsts/agent/2.152.1/work/1/s/node_modules/gulp-remote-src/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/Users/vsts/agent/2.152.1/work/1/s/node_modules/gulp-remote-src/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/Users/vsts/agent/2.152.1/work/1/s/node_modules/gulp-remote-src/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##[error]Bash exited with code '1'.
##[section]Finishing: Download Built-in Extensions

```

//cc @sandy081

**Comment by joaomoreno** [comment]
We've had our limits increased, via email.
