### ISSUE TITLE
yarn smoketest not working

### ISSUE THREAD

**Issue by androdvlpr** [microsoft/vscode#75197]
vscode-master>Yarn smoketest failing, below is the error message am getting
Can't find Code at \vscode-master\.build\electron\Code - OSS.exe.
error Command failed with exit code 1.

**Comment by egamma** [comment]
Works for me did you follow the steps in https://github.com/Microsoft/vscode/blob/master/test/smoke/README.md?

**Comment by androdvlpr** [comment]
i followed the steps mentioned in the link. 

- Able to compile using the command "yarn compile" getting inside the folder test/smoke

- next step i tried running the command "yarn smoketest" after doing cd../..

- it did not worked for me as, electron was not properly installed, so i excuted "scripts\test" after which it installed electron but waited for long and not seeing the command terminal back, i terminated the job  by running the command ctrl-c

- Then executed the command "yarn smoketest" and below is the error am getting now
0 passing (2m)
  2 pending
  3 failing

  1) Running Code
       "before all" hook:
     Error: Cannot find module 'D:\VS Code Smoke Test\vscode-master\out\bootstrap-amd.js'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
      at Function.Module._load (internal/modules/cjs/loader.js:562:25)
      at Module.require (internal/modules/cjs/loader.js:690:17)
      at require (internal/modules/cjs/helpers.js:25:18)
      at Object.exports.connect (out\vscode\driver.js:10:19)
      at D:\VS Code Smoke Test\vscode-master\test\smoke\out\vscode\code.js:69:59
      at Generator.next (<anonymous>)
      at fulfilled (out\vscode\code.js:8:58)

  2) Running Code
       "after all" hook:
     TypeError: Cannot read property 'stop' of undefined
      at Context.<anonymous> (out\main.js:231:28)
      at Generator.next (<anonymous>)
      at D:\VS Code Smoke Test\vscode-master\test\smoke\out\main.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out\main.js:7:12)
      at Context.<anonymous> (out\main.js:230:16)

  3) Launch
       verifies that application launches when user data directory has non-ascii characters:
     Error: Cannot find module '\vscode-master\out\bootstrap-amd.js'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
      at Function.Module._load (internal/modules/cjs/loader.js:562:25)
      at Module.require (internal/modules/cjs/loader.js:690:17)
      at require (internal/modules/cjs/helpers.js:25:18)
      at Object.exports.connect (out\vscode\driver.js:10:19)
      at \vscode-master\test\smoke\out\vscode\code.js:69:59
      at Generator.next (<anonymous>)
      at fulfilled (out\vscode\code.js:8:58)



error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by joaomoreno** [comment]
Let's try this:

```
git clean -xfd && yarn && yarn compile
./scripts/code.bat # make sure code runs
yarn smoketest
```

**Comment by androdvlpr** [comment]
@joaomoreno : It is working, am able to see the test cases getting executed. few am able to see and 3 are pending. this is enough. **thanks a lot for your quick help**. i will use this for my work. 
Below is what i got, most of the cases it is Timeout!! error
31 Passing
5 Pending
7 Failing

  1) Running Code
       Dataloss
         verifies that 'hot exit' works for dirty files:
     Error: Timeout: is active element '.editor-instance .monaco-editor[data-uri
$="Untitled-1"] textarea' after 20 seconds.
      at \vscode-master\test\smoke\out\vscode\code.js:158:2
3
      at Generator.next (<anonymous>)
      at fulfilled (out\vscode\code.js:8:58)

  2) Running Code
       CSS
         verifies warnings for the empty rule:
     Error: Timeout: is active element '.editor-instance .monaco-editor[data-uri
$="style.css"] textarea' after 20 seconds.
      at \vscode-master\test\smoke\out\vscode\code.js:158:2
3
      at Generator.next (<anonymous>)
      at fulfilled (out\vscode\code.js:8:58)

  3) Running Code
       CSS
         verifies that warning becomes an error once setting changed:
     Error: Timeout: get element '.view-overlays .cdr.squiggly-error' after 20 s
econds.
      at \vscode-master\test\smoke\out\vscode\code.js:158:2
3
      at Generator.next (<anonymous>)
      at fulfilled (out\vscode\code.js:8:58)

  4) Running Code
       Editor
         finds 'All References' to 'app':
     Error: Timeout: get elements '.monaco-editor .zone-widget .zone-widget-cont
ainer.peekview-widget.reference-zone-widget.results-loaded .body .ref-tree.inlin
e .monaco-list-row .reference' after 20 seconds.
      at \vscode-master\test\smoke\out\vscode\code.js:158:2
3
      at Generator.next (<anonymous>)
      at fulfilled (out\vscode\code.js:8:58)

  5) Running Code
       Editor
         renames local 'app' variable:
     Error: Timeout: is active element '.editor-instance .monaco-editor[data-uri
$="www"] textarea' after 20 seconds.
      at \vscode-master\test\smoke\out\vscode\code.js:158:2
3
      at Generator.next (<anonymous>)
      at fulfilled (out\vscode\code.js:8:58)

  6) Running Code
       Editor
         verifies that 'Peek Definition' works:
     Error: Timeout: is active element '.editor-instance .monaco-editor[data-uri
$="app.js"] textarea' after 20 seconds.
      at \vscode-master\test\smoke\out\vscode\code.js:158:2
3
      at Generator.next (<anonymous>)
      at fulfilled (out\vscode\code.js:8:58)

  7) Running Code
       Debug
         configure launch json:
     Error: Timeout: is active element '.editor-instance .monaco-editor[data-uri
$="app.js"] textarea' after 20 seconds.
      at vscode-master\test\smoke\out\vscode\code.js:158:2
3
      at Generator.next (<anonymous>)
      at fulfilled (out\vscode\code.js:8:58)



error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

VS Code Smoke Test\vscode-master>
