### ISSUE TITLE
URI.parse() failes with `Cannot read property 'toLowerCase' of undefined`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#75344]
I admit it's not a useful code snippet, but it should not fail with a exception:

URI.parse("abc", false)

TypeError: Cannot read property 'toLowerCase' of undefined
  at _isQueryStringScheme (../node_modules/vscode-uri/lib/umd/index.js:119:24)
  at Function.URI.parse (../node_modules/vscode-uri/lib/umd/index.js:275:214)

**Comment by jrieken** [comment]
This happens when the uri doesn't have a scheme which would make it explode down the way anyways...
