### ISSUE TITLE
Debug smoke tests were failing on stable

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#75351]
1) Running Code
       Debug
         start debugging:
     Error: Timeout: get elements 'div[id="workbench.view.debug"] .monaco-list-row .stack-frame' after 20 seconds.
      at /Users/sandy081/work/vscode/test/smoke/out/vscode/code.js:163:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)

  2) Running Code
       Debug
         focus stack frames and variables:
     Error: Timeout: get elements 'div[id="workbench.view.debug"] .debug-variables .monaco-list-row .expression' after 20 seconds.
      at /Users/sandy081/work/vscode/test/smoke/out/vscode/code.js:163:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)

  3) Running Code
       Debug
         stepOver, stepIn, stepOut:
     Error: Timeout: get elements 'div[id="workbench.view.debug"] .monaco-list-row .stack-frame' after 20 seconds.
      at /Users/sandy081/work/vscode/test/smoke/out/vscode/code.js:163:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)

  4) Running Code
       Debug
         continue:
     Error: Timeout: click '.debug-toolbar .action-label[title*="Continue"]' after 20 seconds.
      at /Users/sandy081/work/vscode/test/smoke/out/vscode/code.js:163:23
      at Generator.next (<anonymous>)
      at fulfilled (out/vscode/code.js:8:58)

```
Error: Element not found: .debug-toolbar .action-label[title*="Continue"]
    at m.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2193:451)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:34:621
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:34:398)
    at m._getElementXY (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2193:356)
    at m.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2193:746)
    at Generator.next (<anonymous>)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:34:621
    at new Promise (<anonymous>)
    at n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:34:398)
    at m._click (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2193:687)
    at m.click (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2193:277)
    at call (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1380:94)
    at C.onPromise (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:316:605)
    at C.onRawMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:316:241)
    at C.protocolListener.protocol.onMessage.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:315:820)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:983)
    at EventEmitter.n (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:526)
    at EventEmitter.emit (events.js:182:13)
```

**Comment by isidorn** [comment]
Can not reproduce on my machine 
None of the toolbar css elements have changed so it does not make any sense to me that the debug smoke test fails.
@sandy081 can you repro this all the time?

<img width="373" alt="Screenshot 2019-06-14 at 16 16 52" src="https://user-images.githubusercontent.com/1926584/59515639-d9791680-8ebf-11e9-893f-5ebde765ca02.png">
