### ISSUE TITLE
Building on Win7 x64 with VS2017 Comm. Ed.: node_modules\native-is-elevated\build\is-elevated.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the declaration is correct, and that the file exists on disk.

### ISSUE THREAD

**Issue by mrkafk** [microsoft/vscode#75413]
- VSCode Version: 1.35.1
- OS Version: Windows 7 x64
- Visual Studio: **2017 Community Edition**

Steps to Reproduce:

1. Check out `1.35.1` tag

2. Run script:

```
@echo on

set PYTHON=C:\Program Files (x86)\Python271\python.exe

set PATH=%PATH%;C:\Program Files\7-Zip

call npm.cmd config set loglevel verbose

mkdir tmp

call npm.cmd config set cache tmp

call npm.cmd cache clean --force

call npm install gulp

yarn
```

3. Get error:
```
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

+ gulp@4.0.2
added 320 packages from 218 contributors and audited 6659 packages in 161.469s
found 0 vulnerabilities

npm verb exit [ 0, true ]
npm timing npm Completed in 163772ms
npm info ok
yarn install v1.16.0
$ node build/npm/preinstall.js
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies causedk files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info vscode-fsevents@0.3.10: The platform "win32" is incompatible with this module.
info "vscode-fsevents@0.3.10" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/18] ? gc-signals
[2/18] ? keytar
[3/18] ? native-is-elevated
[4/18] ? native-keymap
error C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated
Output:
C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated>if not defined npm_config_node_gyp (node "C:\ACME\Dev\projects\node-v10.16.0-win-x64\node_modules\npm\bin\node-gyp-bin\\..\..\node_modulep.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\ACME\\Dev\\projects\\node-v10.16.0-win-x64\\node.exe',
gyp verb cli   'C:\\ACME\\Dev\\projects\\node-v10.16.0-win-x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb download using dist-url https://atom.io/download/electron
gyp verb check python checking for Python executable "C:\Program Files (x86)\Python271\python.exe" in the PATH
gyp verb `which` succeeded C:\Program Files (x86)\Python271\python.exe C:\Program Files (x86)\Python271\python.exe
gyp verb check python version `C:\Program Files (x86)\Python271\python.exe -c "import sys; print "2.7.10
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir compiling against --target node version: 3.1.8
gyp verb command install [ '3.1.8' ]
gyp verb download using dist-url https://atom.io/download/electron
gyp verb install input version string "3.1.8"
gyp verb install installing version: iojs-3.1.8
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: iojs-3.1.8
gyp verb build dir attempting to create "build" dir: C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated\build
gyp verb build dir "build" dir needed to be created? C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated\config.gypi
gyp verb common.gypi checking for gypi file: C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Program Files (x86)\Python271\python.exe
gyp info spawn args [ 'C:\\ACME\\Dev\\projects\\node-v10.16.0-win-x64\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\ACME\\Dev\\projects\\vscode\\node_modules\\native-is-elevated\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\ACME\\Dev\\projects\\node-v10.16.0-win-x64\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\user\\.node-gyp\\iojs-3.1.8\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\user\\.node-gyp\\iojs-3.1.8',
gyp info spawn args   '-Dnode_gyp_dir=C:\\ACME\\Dev\\projects\\node-v10.16.0-win-x64\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\user\\.node-gyp\\iojs-3.1.8\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\ACME\\Dev\\projects\\vscode\\node_modules\\native-is-elevated',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\ACME\\Dev\\projects\\vscode\\node_modules\\native-is-elevated\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb download using dist-url https://atom.io/download/electron
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\user\.node-gyp\iojs-3.1.8
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 6/13/2019 1:07:36 PM.
Project "C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated\build\binding.sln" (1) is building "C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated\build\is-elevated.vcxproj" (2) oets).
C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated\build\is-elevated.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the palaration is correct, and that the file exists on disk.
Done Building Project "C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated\build\is-elevated.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated\build\binding.sln" (default targets) -- FAILED.

Build FAILED.

"C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated\build\binding.sln" (default target) (1) ->
"C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated\build\is-elevated.vcxproj" (default target) (2) ->
  C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated\build\is-elevated.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the
eclaration is correct, and that the file exists on disk.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.58
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\ACME\Dev\projects\node-v10.16.0-win-x64\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\ACME\\Dev\\projects\\node-v10.16.0-win-x64\\node.exe" "C:\\ACME\\Dev\\projects\\node-v10.16.0-win-x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\ACME\Dev\projects\vscode\node_modules\native-is-elevated
```

**Comment by Tyriar** [comment]
You created https://github.com/microsoft/vscode/issues/75334 already...?

**Comment by mrkafk** [comment]
That was for 1.35.0, it produced a different error. This report is for 1.35.1. Please reopen.
