### ISSUE TITLE
IntelliSense works only partially

### ISSUE THREAD

**Issue by Juan-F-Moncada** [microsoft/vscode#75430]
Issue Type: <b>Bug</b>

With VCS 1.35.0 and with no extension enabled, IntelliSense only shows available options (variables, methods) but no information about method syntax (parameters, etc.) and no information about errors (PROBLEMS tab is always empty and the underlying red waves marking code errors never appear).

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (6.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Juan-F-Moncada** [comment]
Update of this issue

IntelliSense works fine in code included in "node_modules"; it is failing only in my project.

Any problem with "tsconfig.json" or another configuration file?

**Comment by mjbvz** [comment]
Please share some example code and steps to reproduce the problem

/needsMoreInfo

**Comment by Juan-F-Moncada** [comment]
![image](https://user-images.githubusercontent.com/51742535/59486207-dd357a80-8e78-11e9-867e-885930ee4813.png)
In the first image, you can see that after writing "f" I get suggestions.
![image](https://user-images.githubusercontent.com/51742535/59486270-10780980-8e79-11e9-9b60-4eabe25486c5.png)
But when I write "fg." I have no suggestion. If I write any method or property in "FormGroup" I get no clue about its syntax.

**Comment by Juan-F-Moncada** [comment]
![image](https://user-images.githubusercontent.com/51742535/59490818-e37e2380-8e85-11e9-96e4-886591c9e380.png)
In addition, if I make a mistake, there is no indication about it.

**Comment by mjbvz** [comment]
It looks like you don't have proper TypeScript suggestions in either example. Have you disabled the builtin `javascript and typescript language features` extension? In the extensions view, search `@builtin javascript` to check this

**Comment by Juan-F-Moncada** [comment]
No, I haven't. Both extensions appearing when searching `@builtin javascript` (JavaScript Language Basics and TypeScript and JavaScript Language Features) are enabled:
![image](https://user-images.githubusercontent.com/51742535/59661513-4257db80-91ab-11e9-8b3f-54847061743d.png)
![image](https://user-images.githubusercontent.com/51742535/59661550-58fe3280-91ab-11e9-88a0-d43982422087.png)

**Comment by mjbvz** [comment]
Do any JavaScript and TypeScript features work for you, such as hovers? What about in other projects?

**Comment by Juan-F-Moncada** [comment]
No hover (you cannot see it but the cursor was over "grid" when the screenshot was taken):
![image](https://user-images.githubusercontent.com/51742535/59740603-dc318e00-9268-11e9-8950-a5969d150584.png)
Under "node_modules" folder, IntelliSense works in some subfolders:
![image](https://user-images.githubusercontent.com/51742535/59740997-fc158180-9269-11e9-932e-479136ef4680.png)

But it doesn't in others:
![image](https://user-images.githubusercontent.com/51742535/59740873-ab058d80-9269-11e9-9723-c9e31f24d4c8.png)

**Comment by mjbvz** [comment]
Can you please try checking the dev tools console to see if there are any errors:

1. Reproduce the issue
1. In VS Code, run the `Developer: Toggle Developer tools` command
1. Open the dev tools console and share the output from there

**Comment by Juan-F-Moncada** [comment]
I have hovered over Angular's FormControl here:
![image](https://user-images.githubusercontent.com/51742535/59832409-191e8300-9344-11e9-9227-18afb53f94d9.png)
And this is what I got in the developer tools console:
```
  ERR TypeScript Server Error (3.5.1)
Cannot read property 'getSourceFile' of undefined
TypeError: Cannot read property 'getSourceFile' of undefined
    at getValidSourceFile (tsserver.js:121857:38)
    at Object.getQuickInfoAtPosition (tsserver.js:122099:30)
    at IOSession.Session.getQuickInfoWorker (tsserver.js:131015:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:130021:61)
    at tsserver.js:131637:88
    at IOSession.Session.executeWithRequestId (tsserver.js:131628:28)
    at IOSession.Session.executeCommand (tsserver.js:131637:33)
    at IOSession.Session.onMessage (tsserver.js:131659:35)
    at Interface.<anonymous> (tsserver.js:132950:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20): Error: TypeScript Server Error (3.5.1)
Cannot read property 'getSourceFile' of undefined
TypeError: Cannot read property 'getSourceFile' of undefined
    at getValidSourceFile (tsserver.js:121857:38)
    at Object.getQuickInfoAtPosition (tsserver.js:122099:30)
    at IOSession.Session.getQuickInfoWorker (tsserver.js:131015:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:130021:61)
    at tsserver.js:131637:88
    at IOSession.Session.executeWithRequestId (tsserver.js:131628:28)
    at IOSession.Session.executeCommand (tsserver.js:131637:33)
    at IOSession.Session.onMessage (tsserver.js:131659:35)
    at Interface.<anonymous> (tsserver.js:132950:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
	at Function.create (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:197742)
	at v.dispatchResponse (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:203110)
	at v.dispatchMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:201862)
	at constructor._reader.onData.e (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:201218)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:720)
	at t.Reader.onLengthData (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:206522)
	at Socket.t.Reader.constructor.e.on.e (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:206170)
	at Socket.emit (events.js:182:13)
	at Socket.EventEmitter.emit (domain.js:442:20)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

**Comment by dylmye** [comment]
Having the same issue in React JS with same console output, this is preventing Go-to definition from working since latest prod update (1.35.1). Disabling all user extenions doesn't fix this.

**Comment by mjbvz** [comment]
@Juan-F-Moncada  Yes, that error would explain why you don't see any errors or intellisense. 

Can you please try collecting the TS server logs so we can investigate what the root cause of this may be:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a `tsserver.log` file 

If you can share the log, we may be able to trace down what is causing this problem

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by Juan-F-Moncada** [comment]
Hi @mjbvz: I've generated the log and checked that it contains plenty of source code, which I wouldn't like to share.

I've located the first error in the log; here you are it (please, let me know if this is enough for you or not):

Err 126   [8:40:36.81] Exception on executing command {"seq":2,"type":"request","command":"updateOpen","arguments":{"openFiles":[{"file":<Full path of my file>,"fileContent":<Full file contents>,"scriptKindName":"TS","projectRootPath":<Project root path of my project>}]}}:

    Debug Failure.

    Error: Debug Failure.
        at Object.assertDefined (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2080:24)
        at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:15130:89
        at String.replace (<anonymous>)
        at formatStringFromArgs (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:15130:21)
        at Object.createFileDiagnostic (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:15146:20)
        at parseErrorAtPosition (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17588:42)
        at parseErrorAt (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17595:13)
        at parseErrorAtCurrentToken (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17582:13)
        at createMissingNode (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17826:17)
        at parseExpectedTokenJSDoc (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17751:17)
        at parseBracketNameInPropertyAndParamTag (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:22665:25)
        at parseParameterOrPropertyTag (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:22691:30)
        at parseTag (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:22528:36)
        at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:22386:44
        at Object.scanRange (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:8458:26)
        at parseJSDocCommentWorker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:22360:32)
        at Object.parseJSDocComment (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:22315:31)
        at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17437:128
        at Object.mapDefined (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:670:30)
        at addJSDocComment (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17437:28)
        at createNodeWithJSDoc (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17793:17)
        at parseClassElement (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:21828:24)
        at parseListElement (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:18191:20)
        at parseList (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:18175:35)
        at parseClassMembers (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:21928:20)
        at parseClassDeclarationOrExpression (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:21875:32)
        at parseClassDeclaration (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:21864:20)
        at parseDeclarationWorker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:21480:28)
        at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:21465:86
        at doInsideOfContext (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17543:20)
        at parseDeclaration (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:21465:24)
        at parseStatement (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:21447:32)
        at parseListElement (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:18191:20)
        at parseList (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:18175:35)
        at parseSourceFileWorker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17419:37)
        at Object.parseSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17289:26)
        at Object.createSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17114:29)
        at Object.createLanguageServiceSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121725:29)
        at acquireOrUpdateDocument (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101803:37)
        at Object.acquireDocumentWithKey (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:101776:20)
        at getOrCreateSourceFileByPath (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122026:41)
        at Object.getOrCreateSourceFile [as getSourceFile] (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121978:24)
        at findSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90572:29)
        at processImportedModules (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90860:25)
        at findSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90625:17)
        at processImportedModules (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90860:25)
        at findSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90625:17)
        at processImportedModules (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90860:25)
        at findSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90625:17)
        at processImportedModules (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90860:25)
        at findSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90625:17)
        at processImportedModules (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90860:25)
        at findSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90625:17)
        at processImportedModules (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90860:25)
        at findSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90625:17)
        at processImportedModules (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90860:25)
        at findSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90625:17)
        at processImportedModules (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90860:25)
        at findSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90625:17)
        at processImportedModules (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90860:25)
        at findSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90625:17)
        at processImportedModules (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90860:25)
        at findSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90625:17)
        at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90471:85
        at getSourceFileFromReferenceWorker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90438:34)
        at processSourceFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90471:13)
        at processRootFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:90301:13)
        at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:89317:60
        at Object.forEach (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:292:30)
        at Object.createProgram (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:89317:16)
        at synchronizeHostData (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:121943:26)
        at Object.getProgram (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122035:13)
        at ConfiguredProject.Project.updateGraphWorker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:126284:53)
        at ConfiguredProject.Project.updateGraph (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:126228:42)
        at ConfiguredProject.updateGraph (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:126723:63)
        at ProjectService.createLoadAndUpdateConfiguredProject (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:128177:25)
        at ProjectService.assignProjectToOpenedScriptInfo (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:128984:44)
        at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:129200:76
        at Array.forEach (<anonymous>)
        at ProjectService.applyChangesInOpenFiles (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:129200:37)
        at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:129946:46)
        at c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131637:88
        at IOSession.Session.executeWithRequestId (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131628:28)
        at IOSession.Session.executeCommand (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131637:33)
        at IOSession.Session.onMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131659:35)
        at Interface.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:132950:27)
        at Interface.emit (events.js:182:13)
        at Interface._onLine (readline.js:290:10)
        at Interface._normalWrite (readline.js:433:12)
        at Socket.ondata (readline.js:149:10)
        at Socket.emit (events.js:182:13)
        at addChunk (_stream_readable.js:279:12)
        at readableAddChunk (_stream_readable.js:264:11)
        at Socket.Readable.push (_stream_readable.js:219:10)
        at Pipe.onread (net.js:636:20)
