### ISSUE TITLE
[error] [vscode.typescript-language-features] provider FAILED

### ISSUE THREAD

**Issue by gaohan1994** [microsoft/vscode#75466]
- VSCode Version: 1.35.1
- OS Version: mac OS 10.35.6

Steps to Reproduce:

Hi there,
My Vscode TsServer does't work when Vscode autoupdate to version 1.35.1 yesterday.
(It's work fine before Vscode update version).

I checked some issue like  #70599 #69822 and so on

I tried update typescript to lastest version, and set the typescript lastest version to Vscode, but it's still not work.

```
yarn add typescript@next --dev
```

error log below:
```

[2019-06-14 10:22:42.728] [exthost] [error] Error: TypeScript Server Error (3.6.0-dev.20190613)
Cannot read property 'getSourceFile' of undefined
TypeError: Cannot read property 'getSourceFile' of undefined
    at getValidSourceFile (tsserver.js:122205:38)
    at Array.map (<anonymous>)
    at Object.getDocumentHighlights (tsserver.js:122533:53)
    at IOSession.Session.getDocumentHighlights (tsserver.js:131140:71)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:130541:61)
    at tsserver.js:132005:88
    at IOSession.Session.executeWithRequestId (tsserver.js:131996:28)
    at IOSession.Session.executeCommand (tsserver.js:132005:33)
    at IOSession.Session.onMessage (tsserver.js:132027:35)
    at Interface.<anonymous> (tsserver.js:133318:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
	at Function.create (/private/var/folders/0m/mzj00ztj6rj0tnqx4vqkr5vw0000gn/T/AppTranslocation/27F1F3C9-342B-49DC-8875-569078D5E437/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:176329)
	at v.dispatchResponse (/private/var/folders/0m/mzj00ztj6rj0tnqx4vqkr5vw0000gn/T/AppTranslocation/27F1F3C9-342B-49DC-8875-569078D5E437/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:181697)
	at v.dispatchMessage (/private/var/folders/0m/mzj00ztj6rj0tnqx4vqkr5vw0000gn/T/AppTranslocation/27F1F3C9-342B-49DC-8875-569078D5E437/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:180449)
	at constructor._reader.onData.e (/private/var/folders/0m/mzj00ztj6rj0tnqx4vqkr5vw0000gn/T/AppTranslocation/27F1F3C9-342B-49DC-8875-569078D5E437/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:179805)
	at u.fire (/private/var/folders/0m/mzj00ztj6rj0tnqx4vqkr5vw0000gn/T/AppTranslocation/27F1F3C9-342B-49DC-8875-569078D5E437/d/Visual Studio Code 2.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47:720)
	at t.Reader.onLengthData (/private/var/folders/0m/mzj00ztj6rj0tnqx4vqkr5vw0000gn/T/AppTranslocation/27F1F3C9-342B-49DC-8875-569078D5E437/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:185678)
	at Socket.t.Reader.constructor.e.on.e (/private/var/folders/0m/mzj00ztj6rj0tnqx4vqkr5vw0000gn/T/AppTranslocation/27F1F3C9-342B-49DC-8875-569078D5E437/d/Visual Studio Code 2.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:185326)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

**Comment by gaohan1994** [comment]
Not work for me, cute bot : (

**Comment by gaohan1994** [comment]
I also tired redownload Vscode, but not work.

I tired download version 1.35.1 and 1.34. same error on both version.

**Comment by gaohan1994** [comment]
I fixed this bug by follow steps.(complete delete Vscode from my mac and reinstall it)

**remember to quit vscode first**

step1.
``
sudo rm -rf $HOME/Library/Application\ Support/Code
``

step2.
``
sudo rm -rf $HOME/.vscode
``

step3.
remove vscode from application

step4.
download vscode and install again

I download the 1.34 version not the lastest version, and it's finally work !
