### ISSUE TITLE
Terminal: integration tests do not run to completion on Windows

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#75689]
Steps:
* Windows 10 (latest `1903` Build `18362.175`)
* fresh checkout and `yarn install`
* run `scripts\test-integration.bat`

```
←[0m    Terminal←[0m
    ←[32m  ΓêÜ←[0m←[90m sendText immediately after createTerminal should not throw←[0m
[3928:0618/115930.995:INFO:CONSOLE(139)] "%c  ERR", source: file:///C:/GitDevelopment/monaco/out/vs/platform/log/common/log.js (139)
    ←[32m  ΓêÜ←[0m←[90m onDidCloseTerminal event fires when terminal is disposed←[0m←[31m (237ms)←[0m
[3928:0618/115931.622:INFO:CONSOLE(139)] "%c  ERR", source: file:///C:/GitDevelopment/monaco/out/vs/platform/log/common/log.js (139)
    ←[32m  ΓêÜ←[0m←[90m processId immediately after createTerminal should fetch the pid←[0m←[31m (655ms)←[0m
    ←[32m  ΓêÜ←[0m←[90m name in constructor should set terminal.name←[0m
[3928:0618/115931.773:INFO:CONSOLE(139)] "%c  ERR", source: file:///C:/GitDevelopment/monaco/out/vs/platform/log/common/log.js (139)
    ←[32m  ΓêÜ←[0m←[90m onDidOpenTerminal should fire when a terminal is created←[0m←[31m (113ms)←[0m
    ←[32m  ΓêÜ←[0m←[90m createTerminalRenderer should fire onDidOpenTerminal and onDidCloseTerminal←[0m←[31m (115ms)←[0m
[3928:0618/115932.200:INFO:CONSOLE(139)] "%c  ERR", source: file:///C:/GitDevelopment/monaco/out/vs/platform/log/common/log.js (139)
[3928:0618/115932.690:INFO:CONSOLE(139)] "%c  ERR", source: file:///C:/GitDevelopment/monaco/out/vs/platform/log/common/log.js (139)
    ←[32m  ΓêÜ←[0m←[90m terminal renderers should get maximum dimensions set when shown←[0m←[31m (917ms)←[0m
    ←[32m  ΓêÜ←[0m←[90m TerminalRenderer.write should fire Terminal.onData←[0m←[31m (114ms)←[0m
    ←[32m  ΓêÜ←[0m←[90m Terminal.sendText should fire Terminal.onInput←[0m←[31m (116ms)←[0m
    ←[32m  ΓêÜ←[0m←[90m onDidChangeActiveTerminal should fire when new terminals are created←[0m←[33m (57ms)←[0m
[3928:0618/115933.723:INFO:CONSOLE(139)] "%c  ERR", source: file:///C:/GitDevelopment/monaco/out/vs/platform/log/common/log.js (139)
    ←[32m  ΓêÜ←[0m←[90m onDidChangeTerminalDimensions should fire when new terminals are created←[0m←[31m (998ms)←[0m
[3928:0618/115934.197:INFO:CONSOLE(139)] "%c  ERR", source: file:///C:/GitDevelopment/monaco/out/vs/platform/log/common/log.js (139)
rejected promise not handled within 1 second: TypeError: name.charCodeAt is not a function
stack trace: TypeError: name.charCodeAt is not a function
    at Object.get (c:\GitDevelopment\monaco\out\vs\workbench\services\extensions\common\file:\C:\GitDevelopment\monaco\src\vs\workbench\services\extensions\common\rpcProtocol.ts:184:31)
    at formatValue (util.js:545:28)
    at formatProperty (util.js:1194:11)
    at formatObject (util.js:900:17)
    at formatValue (util.js:808:14)
    at inspect (util.js:371:10)
    at new AssertionError (internal/assert.js:252:19)
    at innerFail (assert.js:83:9)
    at Function.equal (assert.js:364:5)
    at vscode_1.window.onDidChangeTerminalDimensions (C:\GitDevelopment\monaco\extensions\vscode-api-tests\src\singlefolder-tests\window.test.ts:703:12)
    at Emitter.fire (c:\GitDevelopment\monaco\out\vs\base\common\file:\C:\GitDevelopment\monaco\src\vs\base\common\event.ts:558:16)
    at define.$acceptTerminalDimensions._getTerminalByIdEventually.then.terminal (c:\GitDevelopment\monaco\out\vs\workbench\api\node\file:\C:\GitDevelopment\monaco\src\vs\workbench\api\node\extHostTerminalService.ts:396:42)
[main 2019-06-18T10:00:13.543Z] [VS Code]: detected unresponsive
```

This is bad enough that it seems to hang the window and then killing the process via `Ctrl+C` I see lots of `conhost.exe` consuming lots of CPU:

![image](https://user-images.githubusercontent.com/900690/59673345-67efdf80-91c1-11e9-9c20-dc8d7ca524e0.png)

**Comment by bpasero** [comment]
I had to comment them out: https://github.com/microsoft/vscode/commit/356440d72d7b93f61095eedea4ad4e20cef93a5e

**Comment by Tyriar** [comment]
Reproduced the hang with an extension:

```
vscode.window.createTerminal().dispose();
```

**Comment by Tyriar** [comment]
Might have just started happening if the CI machines updated to Windows 1903 which is rolling out to users now.

**Comment by Tyriar** [comment]
Root cause: https://github.com/microsoft/vscode/issues/76548, forcing winpty during tests could work around this.
