### ISSUE TITLE
When I save with auto formatting enabled , auto formatting not working 

### ISSUE THREAD

**Issue by toplinuxsir** [microsoft/vscode#75735]
When I save with auto formatting enabled , auto formatting not working 

- VSCode Version: 1.35
- OS Version: Ubuntu 19.04

Steps to Reproduce:

The console output is: `
Extension Host] Unhandled Promise rejection: this.deleteTempFile(...).ignoreErrors is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: this.deleteTempFile(...).ignoreErrors is not a function
    at drainMicroTaskQueue (/home/lhs/.vscode/extensions/qub.qub-xml-vscode-1.2.8/node_modules/zone.js/dist/zone-node.js:433:35) TypeError: this.deleteTempFile(...).ignoreErrors is not a function
    at drainMicroTaskQueue (/home/lhs/.vscode/extensions/qub.qub-xml-vscode-1.2.8/node_modules/zone.js/dist/zone-node.js:433:35)
t.log @ workbench.main.js:238

`

**Comment by mjbvz** [comment]
This looks like it is caused by the `qub.qub-xml-vscode` extension. Please file an issue against them
