### ISSUE TITLE
Error: Failed to create terminal for task caused by bad value for terminal.integrated.shellArgs.windows

### ISSUE THREAD

**Issue by Ben-Voris** [microsoft/vscode#75946]
Issue Type: <b>Bug</b>

# Error: Failed to create terminal for task all

When settings.json contains 
`"terminal.integrated.shell.windows": "C:\\cygwin64\\bin\\bash.exe"` and 
`"terminal.integrated.shellArgs.windows"` is `" "` instead of
`[" "]`, this appears in the "Output" > "Log (Window)":
```
[2019-06-20 13:49:07.299] [renderer1] [error] m.some is not a function: TypeError: m.some is not a function
    at f.forEach.e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3158:681)
    at Array.forEach (<anonymous>)
    at D.createShellLaunchConfig (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3158:667)
    at D.createTerminal (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3160:726)
    at e.configurationProperties.isBackground.Promise (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3154:442)
    at new Promise (<anonymous>)
    at D.executeInTerminal (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3154:406)
    at resolveVariablesFromSet.then.i (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3150:852)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-06-20 13:49:07.299] [renderer1] [error] Failed to create terminal for task all: Error: Failed to create terminal for task all
    at D.executeInTerminal (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3156:214)
    at resolveVariablesFromSet.then.i (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3150:852)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Adding documentation on this error, suggesting that one look carefully
at the value of `"terminal.integrated.shellArgs.windows"` would be helpful.

At least for me, the relationship between a "task" terminals and a terminal 
started by `Create New Integrated Terminal` is unclear. Even with the
above error in settings.json, `Create New Integrated Terminal` works. Only a 
build fails.

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.38
remote-containers|ms-|0.59.0
remote-ssh|ms-|0.42.2
remote-ssh-edit|ms-|0.42.2
remote-ssh-explorer|ms-|0.42.2
remote-wsl|ms-|0.38.0
vscode-remote-extensionpack|ms-|0.15.0
cpptools|ms-|0.24.0-insiders
rewrap|stk|1.9.1

</details>

**Comment by nerdo** [comment]
This may be related to https://github.com/microsoft/vscode/issues/75717

**Comment by Tyriar** [comment]
@alexr00 tasks should work when shellArgs = `" "`, I think it should treat this the same as `""`

**Comment by alexr00** [comment]
Agreed.
