### ISSUE TITLE
Test: new test runner shows stacktrace as output now

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#76096]
Refs: https://github.com/microsoft/vscode/issues/76039

When using the new test runner, the output I get is:

 ```
 1) Extension Test Suite
       Sample test:

      AssertionError [ERR_ASSERTION]: 8 == -1
      + expected - actual

      -8
      +-1
      
  	at Context.test (out/test/suite/extension.test.js:14:16)






Spawn Error: Error: 1 tests failed.
	at mocha.run.failures (/Users/bpasero/Development/vscode-extension-samples/helloworld-test-sample/out/test/suite/index.js:26:27)
	at done (/Users/bpasero/Development/vscode-extension-samples/helloworld-test-sample/node_modules/mocha/lib/mocha.js:838:7)
	at Runner.<anonymous> (/Users/bpasero/Development/vscode-extension-samples/helloworld-test-sample/node_modules/mocha/lib/runner.js:918:5)
	at Runner.emit (events.js:187:15)
	at /Users/bpasero/Development/vscode-extension-samples/helloworld-test-sample/node_modules/mocha/lib/runner.js:903:12
	at /Users/bpasero/Development/vscode-extension-samples/helloworld-test-sample/node_modules/mocha/lib/runner.js:772:9
	at next (/Users/bpasero/Development/vscode-extension-samples/helloworld-test-sample/node_modules/mocha/lib/runner.js:362:14)
	at Immediate.<anonymous> (/Users/bpasero/Development/vscode-extension-samples/helloworld-test-sample/node_modules/mocha/lib/runner.js:425:5)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)

Exit code:   1
Done

Failed to run tests
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! helloworld-sample@0.0.1 test: `node ./out/test/runTest.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the helloworld-sample@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bpasero/.npm/_logs/2019-06-25T12_57_38_583Z-debug.log
```

vs:

```
  1) Extension Test Suite
       Sample test:

      AssertionError [ERR_ASSERTION]: 8 == -1
      + expected - actual

      -8
      +-1
      
  	at Context.test (out/test/suite/extension.test.js:14:16)






Spawn Error: [0625/150224.015493:ERROR:archive.cc(167)] Failed to parse header size from /Users/bpasero/Development/monaco/extensions/css-language-features/server/test/pathCompletionFixtures/src/data/foo.asar

Exit code:   1
Done

Failed to run tests
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! npm-ts@0.0.1 test: `node ./out/test/runTest.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the npm-ts@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bpasero/.npm/_logs/2019-06-25T13_02_27_997Z-debug.log
```

Is the full stack trace needed?

**Comment by octref** [comment]
Good catch, should have used `err.toString`.

**Comment by octref** [comment]
Verifier: Throw an error in the test runner like so: https://github.com/microsoft/vscode-extension-samples/blob/octref/test/helloworld-test-sample/src/test/suite/index.ts#L16

And make sure no stack trace is printed.
