### ISSUE TITLE
Error saving file / Cannot save file

### ISSUE THREAD

**Issue by Goevex** [microsoft/vscode#76162]
- VSCode Version: 1.35.1
- OS Version: Windows 10.0.17134

Steps to Reproduce:

1. Conditions are not clear
2. Save the file
3. Error:
`[2019-06-26 10:29:00.655] [renderer1] [error] selectionRange must be contained in fullRange: Error: selectionRange must be contained in fullRange
	at Function.validate (c:\Users\nicol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:345:152)
	at new w (c:\Users\nicol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:345:20)
	at new w (c:\Users\nicol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:333:525)
	at asDocumentSymbol (C:\Users\nicol\.vscode\extensions\ms-vscode.go-0.10.2\node_modules\vscode-languageclient\lib\protocolConverter.js:360:22)
	at Array.map (<anonymous>)
	at Object.asDocumentSymbols (C:\Users\nicol\.vscode\extensions\ms-vscode.go-0.10.2\node_modules\vscode-languageclient\lib\protocolConverter.js:357:23)
	at registerLanguageProvider.client.sendRequest.then (C:\Users\nicol\.vscode\extensions\ms-vscode.go-0.10.2\node_modules\vscode-languageclient\lib\client.js:983:62)
[2019-06-26 10:29:14.911] [renderer1] [warning] Aborted codeActionsOnSave after 750ms` occurs in window log
3. File changes are gone

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Sorry above info is not helpful to diagnose the issue

Can you please provide the Steps to repro and the set up you have. May be a gif in action showing error while saving the file.

**Comment by Goevex** [comment]
Well, i can give you an example

 i have a file component.go, which says

```
package auth

import (
	"dayzserverapi/webapi/component"
)

// New returns a new instance of the endpoint.
func New(bc component.Core) *Endpoint {
	return &Endpoint{
		Core: bc,
	}
}

// Endpoint contains the dependencies.
type Endpoint struct {
	component.Core
}

// Routes will set up the endpoints.
func (p *Endpoint) Routes(router component.IRouter) {
	router.Post("/v1/auth", p.PostIndex)
	router.Get("/v1/auth", p.GetIndex)
}
```
After I edit it

```
package auth

import (
	"dayzserverapi/webapi/component"
)

// New returns a new instance of the endpoint.
func New(bc component.Core) *Endpoint {
	return &Endpoint{
		Core: bc,
	}
}

// Endpoint contains the dependencies.
type Endpoint struct {
	component.Core
}

// Routes will set up the endpoints.
func (p *Endpoint) Routes(router component.IRouter) {
	router.Post("/v1/auth", p.PostIndex)
	router.Post("/v2/auth", p.PostIndexV2)
	router.Get("/v1/auth", p.GetIndex)
}
```
Then I press Ctrl+S to save it, it goes back to its initial code and I get this error

```
[2019-06-29 17:02:01.884] [renderer3] [error] selectionRange must be contained in fullRange: Error: selectionRange must be contained in fullRange
	at Function.validate (c:\Users\nicol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:345:152)
	at new w (c:\Users\nicol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:345:20)
	at new w (c:\Users\nicol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:333:525)
	at asDocumentSymbol (C:\Users\nicol\.vscode\extensions\ms-vscode.go-0.11.0\node_modules\vscode-languageclient\lib\protocolConverter.js:360:22)
	at Array.map (<anonymous>)
	at Object.asDocumentSymbols (C:\Users\nicol\.vscode\extensions\ms-vscode.go-0.11.0\node_modules\vscode-languageclient\lib\protocolConverter.js:357:23)
	at registerLanguageProvider.client.sendRequest.then (C:\Users\nicol\.vscode\extensions\ms-vscode.go-0.11.0\node_modules\vscode-languageclient\lib\client.js:983:62)
[2019-06-29 17:02:56.636] [renderer3] [warning] Aborted format on save after 750ms
```
After reload window, it works again. It just happens sometimes but i haven't able to figure out under which conditions yet.

**Comment by sandy081** [comment]
Can you please try reproducing it by disabling all installed extensions. This is to see if this is being caused by any installed extension?

**Comment by Goevex** [comment]
After some testing i found out that this only happens when saving go-files. disabling golang made my files saveable again. updating the extension and golangs tools didn't solve the problem. Finally updating golang itself from 1.12.4 to 1.12.6 and updating tools again worked.
