### ISSUE TITLE
Build: Telemetry task is failing silently

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#76279]
The Telemetry build task is failing silently, which gets easily discoverable [when using `exec`](https://github.com/microsoft/vscode/compare/joao/build-telemetry-exec). We must use `exec` otherwise errors like this just go unnoticed. The goal here is to merge that `joao/build-telemetry-exec` branch. But first we must fix those errors.

Paying closer attention to the build log of a **green** build, we actually see many errors:

```
> node ./out/setup-extension-repos.js

...
Cloning into 'TypeScript'...
Checking out files:   4% (2265/51585)   
...
Checking out files:  52% (26825/51585)   
error: unable to create file tests/baselines/reference/project/maprootUrlsourcerootUrlMixedSubfolderSpecifyOutputFileAndOutputDirectory/node/maprootUrlsourcerootUrlMixedSubfolderSpecifyOutputFileAndOutputDirectory.errors.txt: Filename too long
Checking out files:  53% (27341/51585)   
Checking out files:  54% (27856/51585)   
error: unable to create file tests/baselines/reference/project/sourceRootAbsolutePathMixedSubfolderSpecifyOutputFileAndOutputDirectory/node/sourceRootAbsolutePathMixedSubfolderSpecifyOutputFileAndOutputDirectory.errors.txt: Filename too long
error: unable to create file tests/baselines/reference/project/sourceRootRelativePathMixedSubfolderSpecifyOutputFileAndOutputDirectory/node/sourceRootRelativePathMixedSubfolderSpecifyOutputFileAndOutputDirectory.errors.txt: Filename too long
Checking out files:  55% (28372/51585)   
...
Checking out files: 100% (51585/51585), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

child_process.js:656
    throw err;
    ^

Error: Command failed: setup-extension-repos.bat
```

And right after that the exact same error happens... are we doing this `setup-extension-repos` twice?

```
Checking out files: 100% (51585/51585), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'


    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:653:13)
    at Object.<anonymous> (D:\a\1\a\vscode-telemetry-extractor\out\setup-extension-repos.js:14:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-telemetry-extractor@0.0.5 setup-extension-repos: `node ./out/setup-extension-repos.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vscode-telemetry-extractor@0.0.5 setup-extension-repos script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm\cache\_logs\2019-06-28T05_13_40_765Z-debug.log
....running.
...extracting
```

A couple more errors appear after that:

```
error parsing glob ''!**/extensions/**'': invalid use of **; must be one path component
```

```
<stdin>: output kind PathWithMatch requires a file path
<stdin>: output kind PathWithMatch requires a file path
```

cc @sbatten @Tyriar @kieferrm

**Comment by lramos15** [comment]
These are ripgrep errors with Windows that when the debugger is run seem to just dissappear so I wasn't able to quickly solve them. It doesn't seem to affect the output at a quick glance.
