### ISSUE TITLE
Debugger doesn't start in virtual environment

### ISSUE THREAD

**Issue by se16n** [microsoft/vscode#76340]
Issue Type: <b>Bug</b>

Hello.

When i hit F5 with "Python: Current file" template in virtual environment debugger doesn't start, program just executing.
Same actions works if i run debugging with system-wide python i.e without venv.  

Venv is in the root of project folder.

# launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "port": 5678,
            "host": "localhost",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ]
        },
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}
```
# settings.json
```
{
    "python.pythonPath": "E:\\Projects\\TgBot\\Scripts\\python.exe"
}
```
# --log-folder
```
I00000.000: Windows-7-6.1.7601-SP1 AMD64
            CPython 3.7.2 (32-bit)
            ptvsd 4.2.10

I00000.015: main(['c:\\Users\\User\\.vscode\\extensions\\ms-python.python-2019.6.22090\\pythonFiles\\ptvsd_launcher.py', '--client', '--log-dir', 'E:\\Projects\\TgBot', '--host', 'localhost', '--port', '51008', 'e:\\Projects\\TgBot\\Client.py'])

I00000.015: sys.argv after parsing: ['c:\\Users\\User\\.vscode\\extensions\\ms-python.python-2019.6.22090\\pythonFiles\\ptvsd_launcher.py']

D00000.015: sys.prefix: ('E:\\Projects\\TgBot',)

D00000.015: sys.base_prefix: C:\Users\User\AppData\Local\Programs\Python\Python37-32

D00000.015: site.getusersitepackages(): C:\Users\User\AppData\Roaming\Python\Python37\site-packages

D00000.015: site.getsitepackages(): ['E:\\Projects\\TgBot', 'E:\\Projects\\TgBot\\lib\\site-packages']

D00000.015: Folder with "site-packages" in sys.path: E:\Projects\TgBot\lib\site-packages

D00000.015: sysconfig platlib: E:\Projects\TgBot\Lib\site-packages

D00000.015: sysconfig platstdlib: E:\Projects\TgBot\Lib

D00000.015: sysconfig purelib: E:\Projects\TgBot\Lib\site-packages

D00000.015: sysconfig stdlib: C:\Users\User\AppData\Local\Programs\Python\Python37-32\Lib

D00000.015: os dir: C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib

D00000.015: threading dir: C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib

D00000.015: sys.argv after patching: ['e:\\Projects\\TgBot\\Client.py']

D00000.015: Installing pydevd hooks.

D00000.015: Monkey-patching multiprocess functions.

D00000.015: pydevd.settrace()

D00000.015: Starting client daemon on ('localhost', 51008).

D00001.014: Closing daemon after single session

D00001.014: Stopping daemon.

E00001.014: Exception escaped from start_client
            
            Traceback (most recent call last):
              File "c:\Users\User\.vscode\extensions\ms-python.python-2019.6.22090\pythonFiles\lib\python\ptvsd\log.py", line 110, in g
                return f(*args, **kwargs)
              File "c:\Users\User\.vscode\extensions\ms-python.python-2019.6.22090\pythonFiles\lib\python\ptvsd\pydevd_hooks.py", line 74, in start_client
                sock, start_session = daemon.start_client((host, port))
              File "c:\Users\User\.vscode\extensions\ms-python.python-2019.6.22090\pythonFiles\lib\python\ptvsd\daemon.py", line 217, in start_client
                connect(client, addr)
              File "c:\Users\User\.vscode\extensions\ms-python.python-2019.6.22090\pythonFiles\lib\python\ptvsd\socket.py", line 197, in connect
                sock.connect(addr)
            ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
            

D00001.014: Handling atexit

D00001.014: Stopping daemon.
```

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.98GB (27.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.6.22090

</details>

**Comment by huangrt01** [comment]
I met the same issue, and solved it by changing the version of the extension "Python" to 2018.8.0.
