### ISSUE TITLE
Cannot read property 'setTheme' of undefined

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#76347]
Not sure if this can be reproduced (happened only 2 times). 

I switched theme from light to dark but terminal remained light and editor decorations stuck. There is an extension active that always activates (`*`) and creates terminal, so it's possible that it was just a very bad timing.
```
vscode.window.createTerminal({
	name: 'terminal',
});
```

```log
ERR Cannot read property 'setTheme' of undefined: TypeError: Cannot read property 'setTheme' of undefined
    at Terminal._setTheme (\resources\app\node_modules.asar\vscode-xterm\lib\Terminal.js:588:28)
    at Terminal.setOption (\resources\app\node_modules.asar\vscode-xterm\lib\Terminal.js:307:22)
    at Terminal.setOption (\resources\app\node_modules.asar\vscode-xterm\lib\public\Terminal.js:193:20)
    at e._updateTheme (/resources/app/out/vs/workbench/workbench.main.js:3713:403)
    at _disposables.push._themeService.onThemeChange.e (/resources/app/out/vs/workbench/workbench.main.js:3695:561)
    at d.fire (/resources/app/out/vs/workbench/workbench.main.js:77:983)
    at W.applyTheme (/resources/app/out/vs/workbench/workbench.main.js:4384:292)
    at s.ensureLoaded.then.i (/resources/app/out/vs/workbench/workbench.main.js:4382:730)
```

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

**Comment by usernamehw** [comment]
/duplicate of https://github.com/xtermjs/xterm.js/issues/2220

**Comment by Tyriar** [comment]
Should be in insiders :+1:
