### ISSUE TITLE
Update after restart not working on Windows 10

### ISSUE THREAD

**Issue by philippart-s** [microsoft/vscode#76463]
- VSCode Version: 1.33.1
- OS Version: Wondows 10

Steps to Reproduce:

1. Uncheck Enable Windows Background Updates (don"t work on my install and saw this tips on closed issues 😉 )
2. Check update
3. Click on Update Now : 
![image](https://user-images.githubusercontent.com/26224751/60511444-42d79280-9cd2-11e9-8974-30607574d871.png)
4. Nothing append and an error appear in logs

Does this issue occur when all extensions are disabled?: Yes

my logs:

```
C:\softs\Microsoft VS Code\bin>code --verbose

[main 2019-07-02T12:08:09.902Z] Starting VS Code
[main 2019-07-02T12:08:09.903Z] from: c:\softs\Microsoft VS Code\resources\app
[main 2019-07-02T12:08:09.903Z] args: { _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  version: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  verbose: true,
  status: false,
  'prof-modules': false,
  'prof-startup': false,
  'disable-extensions': false,
  'disable-gpu': false,
  logExtensionHostCommunication: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  nolazy: false,
  issue: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'prof-code-loading': false,
  nodeless: false }
[main 2019-07-02T12:08:09.909Z] Resolving machine identifier...
[main 2019-07-02T12:08:09.909Z] Resolved machine identifier: 74e606e4b6f4ea549d22a9d48151cee294b78b278c7cfc56cc905c4fcdecaf89
[main 2019-07-02T12:08:09.935Z] update#setState idle
[main 2019-07-02T12:08:09.948Z] windowsManager#open
[main 2019-07-02T12:08:10.373Z] telemetry/optInStatus { optIn: true }
[main 2019-07-02T12:08:10.375Z] telemetry/update:win32SetupTarget { target: 'system' }
[main 2019-07-02T12:08:10.377Z] telemetry/machineIdFallback { usingFallbackGuid: false }
[main 2019-07-02T12:08:10.405Z] [storage state.vscdb] open(C:\Users\philippart-s\AppData\Roaming\Code\User\globalStorage\state.vscdb, retryOnBusy: true)
[main 2019-07-02T12:08:10.535Z] [storage state.vscdb] Trace (event): SELECT * FROM ItemTable
[main 2019-07-02T12:08:10.537Z] [storage state.vscdb] getItems(): 49 rows
[main 2019-07-02T12:08:10.640Z] [storage state.vscdb] updateItems(): insert(Map(2) {telemetry.lastSessionDate => Tue, 02 Jul 2019 12:06:37 GMT, telemetry.currentSessionDate => Tue, 02 Jul 2019 12:08:10 GMT}), delete(Set(0) {})
[main 2019-07-02T12:08:10.641Z] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[main 2019-07-02T12:08:10.641Z] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('telemetry.lastSessionDate','Tue, 02 Jul 2019 12:06:37 GMT'),('telemetry.currentSessionDate','Tue, 02 Jul 2019 12:08:10 GMT')
[main 2019-07-02T12:08:10.648Z] [storage state.vscdb] Trace (event): END TRANSACTION
[688:0702/140812.141:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140812.184:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140812.184:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140812.188:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140812.234:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140812.711:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[main 2019-07-02T12:08:12.715Z] IPC#vscode-workbenchReady
[main 2019-07-02T12:08:12.716Z] windowsService#isFocused 1
[main 2019-07-02T12:08:12.717Z] windowsService#whenSharedProcessReady
[main 2019-07-02T12:08:12.718Z] windowsService#getRecentlyOpened 1
[main 2019-07-02T12:08:12.723Z] windowsService#setRepresentedFilename 1
[main 2019-07-02T12:08:12.914Z] windowsService#setRepresentedFilename 1
[688:0702/140812.915:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140812.922:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[main 2019-07-02T12:08:13.050Z] windowsService#getRecentlyOpened 1
[688:0702/140813.053:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140813.137:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140813.137:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140813.139:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140813.140:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140813.141:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[main 2019-07-02T12:08:13.454Z] windowsService#startCrashReporter
[688:0702/140813.687:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[main 2019-07-02T12:08:13.687Z] IPC#vscode:broadcast vscode:changeColorTheme {"baseTheme":"vs-dark","background":"#1e1e1e"}
[688:0702/140813.687:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140813.687:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140813.688:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140813.978:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140814.507:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140814.540:INFO:CONSOLE(3264)] "%c[Extension Host] %cdebugger listening on port 13053", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (3264)
[688:0702/140814.777:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.091:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.429:INFO:CONSOLE(1408)] "%cDEBUG", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.429:INFO:CONSOLE(1408)] "%cDEBUG", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.430:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.442:INFO:CONSOLE(1408)] "%cDEBUG", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.442:INFO:CONSOLE(1408)] "%cDEBUG", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.443:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.501:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.501:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.523:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.525:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.525:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.844:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[main 2019-07-02T12:08:15.845Z] windowsService#getWindowCount
[688:0702/140815.906:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[main 2019-07-02T12:08:15.906Z] RequestService#request https://update.code.visualstudio.com/api/update/win32-x64/stable/51b0b28134d51361cf996d2f0a1c698247aeabd8
[688:0702/140815.913:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.945:INFO:CONSOLE(1408)] "%cDEBUG", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.945:INFO:CONSOLE(1408)] "%cDEBUG", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.945:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.945:INFO:CONSOLE(1408)] "%cDEBUG", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.945:INFO:CONSOLE(1408)] "%cDEBUG", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140815.945:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[main 2019-07-02T12:08:16.105Z] windowsService#isFocused 1
[main 2019-07-02T12:08:16.106Z] windowsService#getWindowCount
[688:0702/140816.110:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140816.756:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140816.756:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140816.756:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140816.756:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140816.757:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140816.757:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140816.758:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140816.825:INFO:CONSOLE(235)] "%c[Extension Host] %c[vscode-icons] v8.8.0 activated! %c(at activate (C:\Users\philippart-s\.vscode\extensions\vscode-icons-team.vscode-icons-8.8.0\out\src\index.js:11:13))", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (235)
[688:0702/140816.829:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140816.829:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140816.830:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140816.830:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140816.834:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140816.836:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140817.091:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140817.100:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140826.243:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[main 2019-07-02T12:08:26.243Z] update#checkForUpdates, state =  idle
[main 2019-07-02T12:08:26.244Z] update#setState checking for updates
[main 2019-07-02T12:08:26.244Z] RequestService#request https://update.code.visualstudio.com/api/update/win32-x64/stable/51b0b28134d51361cf996d2f0a1c698247aeabd8
[main 2019-07-02T12:08:26.284Z] update#setState downloading
[main 2019-07-02T12:08:26.289Z] update#setState ready
[688:0702/140828.707:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[main 2019-07-02T12:08:28.706Z] update#quitAndInstall, state =  ready
[main 2019-07-02T12:08:28.707Z] update#quitAndInstall(): before lifecycle quit()
[main 2019-07-02T12:08:28.707Z] Lifecycle#quit() - from update: true
[main 2019-07-02T12:08:28.717Z] Lifecycle#quit() - calling app.quit()
[main 2019-07-02T12:08:28.717Z] Lifecycle#app.on(before-quit)
[main 2019-07-02T12:08:28.717Z] Lifecycle#onBeforeShutdown.fire()
[main 2019-07-02T12:08:28.719Z] Lifecycle#window.on('close') - window ID 1
[main 2019-07-02T12:08:28.719Z] Lifecycle#unload() - window ID 1
[main 2019-07-02T12:08:28.720Z] SharedProcess#close prevented
[688:0702/140828.732:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[main 2019-07-02T12:08:28.739Z] Lifecycle#unload() - no veto (window ID 1)
[688:0702/140828.739:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140828.743:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140828.756:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140828.759:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140828.762:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140828.780:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[688:0702/140828.809:INFO:CONSOLE(1408)] "%cTRACE", source: file:///C:/softs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (1408)
[main 2019-07-02T12:08:28.835Z] Lifecycle#onBeforeWindowClose.fire() - window ID 1
[main 2019-07-02T12:08:28.987Z] Lifecycle#window.on('closed') - window ID 1
[main 2019-07-02T12:08:28.989Z] Lifecycle#onWillShutdown.fire()
[main 2019-07-02T12:08:29.146Z] Lifecycle#app.on(window-all-closed)
[main 2019-07-02T12:08:29.150Z] Lifecycle#app.on(will-quit)
[main 2019-07-02T12:08:29.153Z] [storage state.vscdb] close()
[main 2019-07-02T12:08:29.211Z] update#quitAndInstall(): after lifecycle quit() with veto: false
[main 2019-07-02T12:08:29.211Z] update#quitAndInstall(): running raw#quitAndInstall()
[main 2019-07-02T12:08:29.212Z] update#quitAndInstall(): running raw#quitAndInstall()
[main 2019-07-02T12:08:29.233Z] [uncaught exception in main]: Error: spawn UNKNOWN
[main 2019-07-02T12:08:29.233Z] Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:357:11)
    at Object.spawn (child_process.js:540:9)
    at P.doQuitAndInstall (C:\softs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:469:855)
    at ready.state.type.lifecycleService.quit.then.e (C:\softs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:318:562)

C:\softs\Microsoft VS Code\bin>
```

**Comment by joaomoreno** [comment]
This is pretty stange. Does it happen all the time? When that notification comes up, can you check the contents of `%TEMP%\vscode-update-win32-x64`?

**Comment by philippart-s** [comment]
HI,
Yes it happen all time.
I have no `%TEMP%\vscode-update-win32-x64`on my computer (I've search `vscode-update-win32-x64` also).

**Comment by joaomoreno** [comment]
Is there any `vscode-update-*` folder in your temp folder?

**Comment by philippart-s** [comment]
You're right i've  : `vscode-update-system-x64`

![image](https://user-images.githubusercontent.com/26224751/60666528-87e0fd80-9e67-11e9-9c65-c8a61ad74841.png)

**Comment by joaomoreno** [comment]
> It's seems that my enterprise adminstrateur block these kind of downloaded files

Please reach out to the administrator and have him allow those files. Otherwise, simply use the ZIP release.
