### ISSUE TITLE
Add retry mechanism for downloading extensions from the Marketplace

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#76508]
```
[08:32:46] Error: Request https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/node-debug/1.35.3/vspackage failed with status code:503
    at Request._callback (/Users/vsts/agent/2.153.2/work/1/s/node_modules/gulp-remote-src/index.js:70:33)
    at Request.self.callback (/Users/vsts/agent/2.153.2/work/1/s/node_modules/gulp-remote-src/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:459:23)
    at Request.<anonymous> (/Users/vsts/agent/2.153.2/work/1/s/node_modules/gulp-remote-src/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:459:23)
    at IncomingMessage.<anonymous> (/Users/vsts/agent/2.153.2/work/1/s/node_modules/gulp-remote-src/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at IncomingMessage.EventEmitter.emit (domain.js:459:23)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by joaomoreno** [comment]
https://www.npmjs.com/package/gulp-remote-retry-src

**Comment by bpasero** [comment]
This is still an issue:

https://dev.azure.com/vscode/VSCode/_build/results?buildId=35293&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=b16e48eb-d187-5f92-5721-e17908fef4e2

```
[11:20:56] Syncronizing built-in extensions...
[11:20:56] You can manage built-in extensions with the --builtin flag
[11:20:56] Downloading extension: ms-vscode.node-debug@1.42.0 ...
[11:20:56] Downloading extension: ms-vscode.node-debug2@1.42.0 ...
[11:20:56] Downloading extension: ms-vscode.references-view@0.0.46 ...
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: Request https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/references-view/0.0.46/vspackage failed with status code:429
    at Request.<anonymous> (/Users/runner/runners/2.163.1/work/1/s/node_modules/gulp-remote-retry-src/index.js:70:33)
    at Request._callback (/Users/runner/runners/2.163.1/work/1/s/node_modules/requestretry/node_modules/lodash/lodash.js:10050:25)
    at Request.requestRetryReply [as reply] (/Users/runner/runners/2.163.1/work/1/s/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/Users/runner/runners/2.163.1/work/1/s/node_modules/requestretry/index.js:146:10)
    at Request.self.callback (/Users/runner/runners/2.163.1/work/1/s/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:476:20)
    at Request.<anonymous> (/Users/runner/runners/2.163.1/work/1/s/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:476:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by joaomoreno** [comment]
Sent email to Marketplace.
