### ISSUE TITLE
go to definition not working

### ISSUE THREAD

**Issue by jonzamoreno** [microsoft/vscode#76571]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by dbaeumer** [comment]
@jonzamoreno can you please provide additional information about the scenario in which Go To Definition is not working.

**Comment by jonzamoreno** [comment]
Using developer tools I found the following error occurs:

  ERR <main> TypeScript Server Error (3.5.2)
Cannot read property 'getSourceFile' of undefined
TypeError: Cannot read property 'getSourceFile' of undefined
    at getValidSourceFile (tsserver.js:121877:38)
    at Proxy.getApplicableRefactors (tsserver.js:122651:24)
    at IOSession.Session.getApplicableRefactors (tsserver.js:131421:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:130239:61)
    at tsserver.js:131665:88
    at IOSession.Session.executeWithRequestId (tsserver.js:131656:28)
    at IOSession.Session.executeCommand (tsserver.js:131665:33)
    at IOSession.Session.onMessage (tsserver.js:131687:35)
    at Interface.<anonymous> (tsserver.js:132978:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17): Error: <main> TypeScript Server Error (3.5.2)
Cannot read property 'getSourceFile' of undefined
TypeError: Cannot read property 'getSourceFile' of undefined
    at getValidSourceFile (tsserver.js:121877:38)
    at Proxy.getApplicableRefactors (tsserver.js:122651:24)
    at IOSession.Session.getApplicableRefactors (tsserver.js:131421:53)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:130239:61)
    at tsserver.js:131665:88
    at IOSession.Session.executeWithRequestId (tsserver.js:131656:28)
    at IOSession.Session.executeCommand (tsserver.js:131665:33)
    at IOSession.Session.onMessage (tsserver.js:131687:35)
    at Interface.<anonymous> (tsserver.js:132978:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
	at Function.create (c:\Users\gomoreno\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:63438)
	at h.dispatchResponse (c:\Users\gomoreno\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:56620)
	at h.dispatchMessage (c:\Users\gomoreno\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:55518)
	at constructor._reader.onData.e (c:\Users\gomoreno\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:54994)
	at u.fire (c:\Users\gomoreno\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:468)
	at t.Reader.onLengthData (c:\Users\gomoreno\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:61658)
	at Socket.t.Reader.constructor.e.on.e (c:\Users\gomoreno\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:61306)
	at Socket.emit (events.js:182:13)
	at Socket.EventEmitter.emit (domain.js:442:20)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by mjbvz** [comment]
Based on the callstack, it looks like the same issue as https://github.com/microsoft/TypeScript/issues/32073

Will keep tracking this upstream

**Comment by jonzamoreno** [comment]
Thanks I'll keep tracking this issue and helping as much as possible
