### ISSUE TITLE
Use mask css property exception issue 

### ISSUE THREAD

**Issue by septs** [microsoft/vscode#76572]
- VSCode Version: 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338)
- OS Version: macOS 10.14.5 (18F132)

Steps to Reproduce:

1. written css, type `mask: no` to css file
2. crash error info to output console 

Does this issue occur when all extensions are disabled?: Yes

The error info:
```
[Error - 4:26:46 PM] Error while computing completions for file:///[HIDDEN FILE INFO]: Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:622043
    at Array.filter (<anonymous>)
    at t.getTermProposals (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:621989)
    at t.e.getCompletionsForDeclarationValue (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:563877)
    at t.e.getCompletionsForExpression (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:573359)
    at t.e.doComplete (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:559045)
    at l.runSafe (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:98344)
    at Immediate.setImmediate [as _onImmediate] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/cssServerMain.js:1:139541)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
```

**Comment by aeschli** [comment]
To reproduce:
Have a *SCSS* file:
```
foo {
    mask: no
}
- completion should show proposals

**Comment by septs** [comment]
yep

**Comment by septs** [comment]
vscode 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529)
Not merged into this version?

**Comment by aeschli** [comment]
No vscode 1.36.1 is June. Will be in 1.37
