### ISSUE TITLE
Can't connect wiht vscode remote

### ISSUE THREAD

**Issue by Tsenzuk** [microsoft/vscode#76631]
Issue Type: <b>Bug</b>

Version: 1.37.0-insider (user setup)
Commit: 8627d1e311d1cc1c8fcd1df5688c145a8bf3a6c9
Date: 2019-07-04T17:03:22.019Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

steps to reproduce:
1) on remote server remove ~/vscode-remote-insider/
2) configure ssh connection with key
3) start connection to remote server

expected results
* ssh connection established
* vscode is downloaded to remote server
* vscode-server is started on remote server
* connection to vscode-server established

actual results
* ssh connection established
* vscode is downloaded to remote server
* vscode-server is started on remote server (it's visible in `top`)
* connection to remote served is not established with error "Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.) VSCode"

VS Code version: Code - Insiders 1.37.0-insider (8627d1e311d1cc1c8fcd1df5688c145a8bf3a6c9, 2019-07-04T17:03:22.019Z)
OS version: Windows_NT x64 10.0.17763
Fetching remote diagnostics for 'SSH: x2-localdev' failed: Connection error: Unauthorized client refused.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.63GB (2.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|

Fetching remote diagnostics for 'SSH: x2-localdev' failed: Connection error: Unauthorized client refused.
</details>Extensions: none

**Comment by samueltlg** [comment]
I have this issue too with the latest insiders release.

**Comment by Britvich** [comment]
Me too.

**Comment by jfpaccini** [comment]
On the same exact version, I have the same problem with accessing to WSL
```
Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.)
```
It happened suddenly after the latest update.

**Comment by jfpaccini** [comment]
If that can be of any help, below a dump of the error messages in the developer console:
```
Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.)
onDidNotificationChange @ notificationsAlerts.ts:40
log.ts:173   ERR Connection error: Unauthorized client refused.: Error: Connection error: Unauthorized client refused.
    at f (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1557:860)
    at t.onControlMessage.o (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1556:822)
    at d.fire (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:79:760)
    at a (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:324:769)
    at e (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:324:815)
    at d.fire (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:79:760)
    at S._receiveMessage (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:333:718)
    at S._socketDisposables.push._socketReader.onMessage.e (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:330:981)
    at d.fire (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:79:760)
    at g.acceptChunk (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:327:532)
    at _register._socket.onData.e (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:326:869)
    at Socket.t (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:335:887)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
log.ts:173   ERR Cannot read property 'extensions' of null: TypeError: Cannot read property 'extensions' of null
    at P.<anonymous> (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3915:141)
    at Generator.next (<anonymous>)
    at r (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:35:293)
    at process._tickCallback (internal/process/next_tick.js:68:7)
log.ts:173   ERR Connection error: Unauthorized client refused.: Error: Connection error: Unauthorized client refused.
    at f (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1557:860)
    at t.onControlMessage.o (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1556:822)
    at d.fire (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:79:760)
    at a (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:324:769)
    at e (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:324:815)
    at d.fire (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:79:760)
    at S._receiveMessage (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:333:718)
    at S._socketDisposables.push._socketReader.onMessage.e (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:330:981)
    at d.fire (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:79:760)
    at g.acceptChunk (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:327:532)
    at _register._socket.onData.e (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:326:869)
    at Socket.t (file:///C:/Users/jf/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:335:887)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
extensionHostProcessManager.ts:76 Error received from starting extension host
_extensionHostProcessProxy._extensionHostProcessWorker.start.then.e @ extensionHostProcessManager.ts:76
extensionHostProcessManager.ts:77 Error: Connection error: Unauthorized client refused.
    at f (remoteAgentConnection.ts:447)
    at i.onControlMessage.o (remoteAgentConnection.ts:179)
    at d.fire (event.ts:558)
    at a (ipc.net.ts:421)
    at e (ipc.net.ts:428)
    at d.fire (event.ts:558)
    at S._receiveMessage (ipc.net.ts:718)
    at S._socketDisposables.push._socketReader.onMessage.e (ipc.net.ts:578)
    at d.fire (event.ts:558)
    at g.acceptChunk (ipc.net.ts:236)
    at _register._socket.onData.e (ipc.net.ts:197)
    at Socket.t (ipc.net.ts:28)
    at Socket.emit (events.js:182)
    at addChunk (_stream_readable.js:283)
    at readableAddChunk (_stream_readable.js:264)
    at Socket.Readable.push (_stream_readable.js:219)
    at TCP.onStreamRead (internal/stream_base_commons.js:94)
```

**Comment by jfpaccini** [comment]
> On the same exact version, I have the same problem with accessing to WSL
> 
> ```
> Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.)
> ```
> 
> It happened suddenly after the latest update.

I reverted back to 1.36.0 (https://update.code.visualstudio.com/1.36.0-insider/win32-x64/insider) and it connects to WSL fine. However, lost extensions installed on remote in WSL.

**Comment by joaomoreno** [comment]
Fix is coming in next hour.

**Comment by joaomoreno** [comment]
Nope, couldn't get this to work. Reverting the insider release for now. Sorry for that folks. Have to fix this tomorrow.

**Comment by joaomoreno** [comment]
Fixed in latest.
