### ISSUE TITLE
Web: terminal is broken

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#76670]
Open the terminal (running out of sources):

```
  ERR this._terminalProcessesReady[request.proxy.terminalId] is not a function: TypeError: this._terminalProcessesReady[request.proxy.terminalId] is not a function
    at MainThreadTerminalService._onTerminalRequestExtHostProcess (http://localhost:9888/out/vs/workbench/api/browser/mainThreadTerminalService.js:217:67)
    at http://localhost:9888/out/vs/workbench/api/browser/mainThreadTerminalService.js:51:98
    at Emitter.fire (http://localhost:9888/out/vs/base/common/event.js:455:38)
    at Proxy.<anonymous> (http://localhost:9888/out/vs/workbench/contrib/terminal/common/terminalService.js:113:55)
    at Generator.next (<anonymous>)
    at http://localhost:9888/out/vs/workbench/browser/web.main.js:10:71
    at new Promise (<anonymous>)
    at __awaiter (http://localhost:9888/out/vs/workbench/browser/web.main.js:6:12)
    at http://localhost:9888/out/vs/workbench/contrib/terminal/common/terminalService.js:105:83
```

**Comment by bflyblue** [comment]
Basically same:
```
[2019-07-05 12:00:41.097] [renderer1] [error] this._terminalProcessesReady[e.proxy.terminalId] is not a function: TypeError: this._terminalProcessesReady[e.proxy.terminalId] is not a function
    at g._onTerminalRequestExtHostProcess (file:///C:/Users/shaun/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3847:680)
    at _toDispose.add.t.onInstanceRequestExtHostProcess.e (file:///C:/Users/shaun/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3843:615)
    at d.fire (file:///C:/Users/shaun/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:79:760)
    at Proxy.<anonymous> (file:///C:/Users/shaun/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3892:952)
    at Generator.next (<anonymous>)
    at file:///C:/Users/shaun/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///C:/Users/shaun/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:35:237)
    at _extensionService.whenInstalledExtensionsRegistered.then (file:///C:/Users/shaun/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3892:736)
```

**Comment by sgtoj** [comment]
Same issue but only when in **remote WSL** mode with Windows VS Code Insider desktop client. 

```
Version: 1.37.0-insider (user setup)
Commit: 34e0ed575230b5c8168289995d59edf274539631
Date: 2019-07-05T08:57:32.211Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763
```
```
[2019-07-05 07:04:31.747] [renderer3] [error] this._terminalProcessesReady[e.proxy.terminalId] is not a function: TypeError: this._terminalProcessesReady[e.proxy.terminalId] is not a function
    at g._onTerminalRequestExtHostProcess (file:///C:/Users/my.user/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3847:680)
    at _toDispose.add.t.onInstanceRequestExtHostProcess.e (file:///C:/Users/my.user/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3843:615)
    at d.fire (file:///C:/Users/my.user/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:79:760)
    at Proxy.<anonymous> (file:///C:/Users/my.user/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3892:952)
    at Generator.next (<anonymous>)
    at file:///C:/Users/my.user/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///C:/Users/my.user/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:35:237)
    at _extensionService.whenInstalledExtensionsRegistered.then (file:///C:/Users/my.user/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3892:736)
```

**Comment by sgtoj** [comment]
Issue is resolved. Just update the Insider client again (twice in the past hour or so).

**Comment by ddotlic** [comment]
> edit: looks like a roll back?

Hoping this will be less overhead for everyone: my insider has flipped-flopped between 1.37 and 1.36 multiple times since yesterday. It stays on one of the two for a few hours, then goes to the other, then again back.

Currently same build as @sgtoj, just on a macOS.

Is this intentional? /cc @bpasero
