### ISSUE TITLE
Compilation failing on ubuntu 18.04

### ISSUE THREAD

**Issue by WhoseTheNerd** [microsoft/vscode#76832]
Title says it all. Here's debug log:
```
$ npm run compile

> code-oss-dev@1.37.0 compile /home/whosethenerd/Builds/vscode
> gulp compile --max_old_space_size=4095

[09:15:26] Node flags detected: --max_old_space_size=4095
[09:15:26] Respawned to PID: 22887
[09:15:26] Local gulp not found in ~/Builds/vscode
[09:15:26] Try running: npm install gulp
[09:15:26] Using globally installed gulp
module.js:549
    throw err;
    ^

Error: Cannot find module 'event-stream'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/whosethenerd/Builds/vscode/build/lib/util.js:7:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

npm ERR! Linux 5.1.16-050116-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "compile"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! code-oss-dev@1.37.0 compile: `gulp compile --max_old_space_size=4095`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the code-oss-dev@1.37.0 compile script 'gulp compile --max_old_space_size=4095'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the code-oss-dev package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp compile --max_old_space_size=4095
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs code-oss-dev
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls code-oss-dev
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/whosethenerd/Builds/vscode/npm-debug.log
$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'compile' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle code-oss-dev@1.37.0~precompile: code-oss-dev@1.37.0
6 silly lifecycle code-oss-dev@1.37.0~precompile: no script for precompile, continuing
7 info lifecycle code-oss-dev@1.37.0~compile: code-oss-dev@1.37.0
8 verbose lifecycle code-oss-dev@1.37.0~compile: unsafe-perm in lifecycle true
9 verbose lifecycle code-oss-dev@1.37.0~compile: PATH: /usr/share/npm/bin/node-gyp-bin:/home/whosethenerd/Builds/vscode/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle code-oss-dev@1.37.0~compile: CWD: /home/whosethenerd/Builds/vscode
11 silly lifecycle code-oss-dev@1.37.0~compile: Args: [ '-c', 'gulp compile --max_old_space_size=4095' ]
12 silly lifecycle code-oss-dev@1.37.0~compile: Returned: code: 1  signal: null
13 info lifecycle code-oss-dev@1.37.0~compile: Failed to exec compile script
14 verbose stack Error: code-oss-dev@1.37.0 compile: `gulp compile --max_old_space_size=4095`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid code-oss-dev@1.37.0
16 verbose cwd /home/whosethenerd/Builds/vscode
17 error Linux 5.1.16-050116-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "compile"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error code-oss-dev@1.37.0 compile: `gulp compile --max_old_space_size=4095`
22 error Exit status 1
23 error Failed at the code-oss-dev@1.37.0 compile script 'gulp compile --max_old_space_size=4095'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the code-oss-dev package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp compile --max_old_space_size=4095
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs code-oss-dev
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls code-oss-dev
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
$ node -v
v10.16.0
```

**Comment by dbaeumer** [comment]
Did you do a `yarn install` ?

**Comment by WhoseTheNerd** [comment]
`yarn install` does nothing.
```
$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
```
Using npm however gets these messages:
```
$ npm install

> code-oss-dev@1.37.0 preinstall /home/whosethenerd/Builds/vscode
> node build/npm/preinstall.js

ERROR: There are no scenarios; must have at least one.
child_process.js:669
    throw err;
    ^

Error: Command failed: yarn -v
ERROR: There are no scenarios; must have at least one.

    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at Object.<anonymous> (/home/whosethenerd/Builds/vscode/build/npm/preinstall.js:16:24)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! code-oss-dev@1.37.0 preinstall: `node build/npm/preinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the code-oss-dev@1.37.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/whosethenerd/.npm/_logs/2019-07-08T12_39_13_126Z-debug.log
$ cat /home/whosethenerd/.npm/_logs/2019-07-08T12_39_13_126Z-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose npm-session 9f77aceb70e04583
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall code-oss-dev@1.37.0
7 info lifecycle code-oss-dev@1.37.0~preinstall: code-oss-dev@1.37.0
8 verbose lifecycle code-oss-dev@1.37.0~preinstall: unsafe-perm in lifecycle true
9 verbose lifecycle code-oss-dev@1.37.0~preinstall: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/whosethenerd/Builds/vscode/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle code-oss-dev@1.37.0~preinstall: CWD: /home/whosethenerd/Builds/vscode
11 silly lifecycle code-oss-dev@1.37.0~preinstall: Args: [ '-c', 'node build/npm/preinstall.js' ]
12 silly lifecycle code-oss-dev@1.37.0~preinstall: Returned: code: 1  signal: null
13 info lifecycle code-oss-dev@1.37.0~preinstall: Failed to exec preinstall script
14 timing stage:rollbackFailedOptional Completed in 1ms
15 timing stage:runTopLevelLifecycles Completed in 278ms
16 verbose stack Error: code-oss-dev@1.37.0 preinstall: `node build/npm/preinstall.js`
16 verbose stack Exit status 1
16 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
16 verbose stack     at EventEmitter.emit (events.js:198:13)
16 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
16 verbose stack     at ChildProcess.emit (events.js:198:13)
16 verbose stack     at maybeClose (internal/child_process.js:982:16)
16 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
17 verbose pkgid code-oss-dev@1.37.0
18 verbose cwd /home/whosethenerd/Builds/vscode
19 verbose Linux 5.1.16-050116-generic
20 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
21 verbose node v10.16.0
22 verbose npm  v6.9.0
23 error code ELIFECYCLE
24 error errno 1
25 error code-oss-dev@1.37.0 preinstall: `node build/npm/preinstall.js`
25 error Exit status 1
26 error Failed at the code-oss-dev@1.37.0 preinstall script.
26 error This is probably not a problem with npm. There is likely additional logging output above.
27 verbose exit [ 1, true ]

```

**Comment by dbaeumer** [comment]
This doesn't look like the right yarn :-). Have you tried the instructions here: https://yarnpkg.com/en/

**Comment by sudeeppaudyal** [comment]
![Capture1](https://user-images.githubusercontent.com/45410318/60912421-e680ef80-a24a-11e9-9293-b6fb2d239ccb.PNG)
![Capture2](https://user-images.githubusercontent.com/45410318/60912424-e84ab300-a24a-11e9-92b3-611dcd85b7db.PNG)
