### ISSUE TITLE
Request has failed: CSS Language Features (Extension)

### ISSUE THREAD

**Issue by farhanafzalsaifee** [microsoft/vscode#76835]
I was trying to add a class to my css and suddenly this output was produced:

```
(/private/var/folders/3c/qtwt8jzd397__856ywztsdfr0000gn/T/AppTranslocation/D0E8F23E-FA9B-4722-81AF-FCDA115A7044/d/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/client/dist/cssMain.js:1:73494)
    at ChildProcess.emit (events.js:187:15)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

**Comment by aeschli** [comment]
I'm not able to reproduce. The stacktrace also doesn't give much to work with.

If you still see this, you could set `"css.trace.server": "verbose"` and check the CSS language server log for more details.
