### ISSUE TITLE
intellisense not working

### ISSUE THREAD

**Issue by mottykohn** [microsoft/vscode#76913]
Issue Type: <b>Bug</b>

The intellisense for typescript just shows generic suggestions:
![image](https://user-images.githubusercontent.com/17966568/60837979-a3b20f80-a197-11e9-942c-1adcf6e3511b.png)

This is what I keep on seeing in the Developers console
  

> ERR <main> TypeScript Server Error (3.5.2)
> Cannot read property 'getProjectVersion' of undefined
> TypeError: Cannot read property 'getProjectVersion' of undefined
> 

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.17763

<details>

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (0.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.800.0
alignment|ann|0.3.0
vscode-typescript-refactors|can|0.0.22
githistory|don|0.4.6
xml|Dot|2.5.0
gc-excelviewer|Gra|2.1.32
vscode-awk-hint|han|0.0.2
live-html-previewer|hdg|0.3.0
AWK|lug|0.0.2
rainbow-csv|mec|1.1.1
Angular-BeastCode|Mik|8.0.10
mssql|ms-|1.6.0
python|ms-|2019.6.22090
vsliveshare|ms-|1.0.488
debugger-for-chrome|msj|4.11.6
angular2-inline|nat|0.0.17
ng-refactor|ng-|0.1.0
vscode-versionlens|pfl|0.24.0
vscode-yaml|red|0.4.1
loopback-json-schemas|seq|1.0.0
vscode-scss-formatter|sib|1.4.1
quokka-vscode|Wal|1.0.233

</details>

**Comment by FadeZhanger** [comment]
I'm having the same issue with IntelliSense failing, but the TSServer error is slightly different:
```
ERR <semantic> TypeScript Server Error (3.5.2)
Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at pipelineEmitWithHint (tsserver.js:84795:39)
    at print (tsserver.js:84695:13)
    at Object.writeNode (tsserver.js:84555:13)
    at tsserver.js:108022:25
    at Object.mapToDisplayParts (tsserver.js:97541:13)
    at createSignatureHelpParameterForTypeParameter (tsserver.js:108020:35)
    at tsserver.js:107991:90
    at Array.map (<anonymous>)
    at itemInfoForTypeParameters (tsserver.js:107991:64)
    at getSignatureHelpItem (tsserver.js:107968:95)
    at tsserver.js:107941:79
    at Array.map (<anonymous>)
    at createSignatureHelpItems (tsserver.js:107941:36)
    at tsserver.js:107533:23
    at Object.runWithCancellationToken (tsserver.js:31649:28)
    at Object.getSignatureHelpItems (tsserver.js:107531:32)
    at Proxy.getSignatureHelpItems (tsserver.js:122260:37)
    at IOSession.Session.getSignatureHelpItems (tsserver.js:131218:62)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:130118:61)
    at tsserver.js:131665:88
    at IOSession.Session.executeWithRequestId (tsserver.js:131656:28)
    at IOSession.Session.executeCommand (tsserver.js:131665:33)
    at IOSession.Session.onMessage (tsserver.js:131687:35)
    at Interface.<anonymous> (tsserver.js:132978:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] 
```

On the latest insiders build with `"typescript.tsserver.useSeparateSyntaxServer": true`.
Not entirely sure if related to OP's.

**Comment by mjbvz** [comment]
@mottykohn Is that all that is logged in the developer console or is there also a call stack?

@FadeZhanger Please open a new issue so we can track this separatly

**Comment by mottykohn** [comment]
@mjbvz 
ERR <main> TypeScript Server Error (3.5.2)
Cannot read property 'getProjectVersion' of undefined
TypeError: Cannot read property 'getProjectVersion' of undefined
    at synchronizeHostData (tsserver.js:121886:22)
    at Object.getCompletionsAtPosition (tsserver.js:122104:13)
    at Object.proxy.(anonymous function).args [as getCompletionsAtPosition] (C:\Users\mkohn\.vscode\extensions\cancerberosgx.vscode-typescript-refactors-0.0.22\node_modules\typescript-plugin-util\dist\src\easy-plugin-install.js:18:39)
    at Object.getCompletionsAtPosition (C:\Users\mkohn\.vscode\extensions\cancerberosgx.vscode-typescript-refactors-0.0.22\node_modules\typescript-plugin-move-declaration\dist\src\index.js:78:40)
    at IOSession.Session.getCompletions (tsserver.js:131147:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:130097:61)
    at tsserver.js:131665:88
    at IOSession.Session.executeWithRequestId (tsserver.js:131656:28)
    at IOSession.Session.executeCommand (tsserver.js:131665:33)
    at IOSession.Session.onMessage (tsserver.js:131687:35)
    at Interface.<anonymous> (tsserver.js:132978:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17): Error: <main> TypeScript Server Error (3.5.2)
Cannot read property 'getProjectVersion' of undefined
TypeError: Cannot read property 'getProjectVersion' of undefined
    at synchronizeHostData (tsserver.js:121886:22)
    at Object.getCompletionsAtPosition (tsserver.js:122104:13)
    at Object.proxy.(anonymous function).args [as getCompletionsAtPosition] (C:\Users\mkohn\.vscode\extensions\cancerberosgx.vscode-typescript-refactors-0.0.22\node_modules\typescript-plugin-util\dist\src\easy-plugin-install.js:18:39)
    at Object.getCompletionsAtPosition (C:\Users\mkohn\.vscode\extensions\cancerberosgx.vscode-typescript-refactors-0.0.22\node_modules\typescript-plugin-move-declaration\dist\src\index.js:78:40)
    at IOSession.Session.getCompletions (tsserver.js:131147:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:130097:61)
    at tsserver.js:131665:88
    at IOSession.Session.executeWithRequestId (tsserver.js:131656:28)
    at IOSession.Session.executeCommand (tsserver.js:131665:33)
    at IOSession.Session.onMessage (tsserver.js:131687:35)
    at Interface.<anonymous> (tsserver.js:132978:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
	at Function.create (c:\Users\mkohn\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:63438)
	at h.dispatchResponse (c:\Users\mkohn\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:56620)
	at h.dispatchMessage (c:\Users\mkohn\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:55518)
	at constructor._reader.onData.e (c:\Users\mkohn\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:54994)
	at u.fire (c:\Users\mkohn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:468)
	at t.Reader.onLengthData (c:\Users\mkohn\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:61658)
	at Socket.t.Reader.constructor.e.on.e (c:\Users\mkohn\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:61306)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by mjbvz** [comment]
@mottykohn From the call stack, it looks like this could be caused by the TS plugin: `cancerberosgx.vscode-typescript-refactors-0.0.22`

Do you see this if you disable that plugin?

**Comment by mottykohn** [comment]
Yup, you got it, thanks!
