### ISSUE TITLE
Remote smoke test fails for 1.36.1

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#76987]
OS: Windows:

```
Projects\mseng\VSCode\vscode [release/1.36 ≡]> yarn smoketest --build C:\apps\VSCode\1.36.1\ --remote
yarn run v1.15.2
$ cd test/smoke && node test/index.js --build C:\apps\VSCode\1.36.1\ --remote


*** Test data: C:\Temp\t24244uWoi5ZCVA2wD
*** Preparing smoketest setup...
*** Cloning test project repository...
*** Running yarn...
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

warning Your current version of Yarn is out of date. The latest version is "1.16.0", while you're on "1.15.2".
info To upgrade, download the latest installer at "https://yarnpkg.com/latest.msi".
*** Smoketest setup done!

  Data Migration: This test MUST run before releasing by providing the --stable-build command line argument
    - verifies opened editors are restored
    - verifies that 'hot exit' works for dirty files

  Running Code
    1) "before all" hook
    2) "after all" hook

  Launch
    3) verifies that application launches when user data directory has non-ascii characters


  0 passing (40s)
  2 pending
  3 failing

  1) Running Code
       "before all" hook:
     Error: connect ENOENT \\.\pipe\lyqtkdgzrlvsfsg
      at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)

  2) Running Code
       "after all" hook:
     TypeError: Cannot read property 'stop' of undefined
      at Context.<anonymous> (out\main.js:231:28)
      at Generator.next (<anonymous>)
      at C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\out\main.js:11:71
      at new Promise (<anonymous>)
      at __awaiter (out\main.js:7:12)
      at Context.<anonymous> (out\main.js:230:16)

  3) Launch
       verifies that application launches when user data directory has non-ascii characters:
     Error: connect ENOENT \\.\pipe\4ieee16dg96zjhm
      at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)



error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by DonJayamanne** [comment]
Sorry for not creating a separate issue, but figured I might as well as here (unrelated to this, but related to smoke tests). 
Q. Do you run these smoke tests on CI or are they run manually on local machines.

**Comment by aeschli** [comment]
It's currently only ran manually during endgame. We had it in CI for a while but tests were not reliable enough at the time. Need to get it in again.

**Comment by aeschli** [comment]
Fixed the `connect ENOENT \\.\pipe\lyqtkdgzrlvsfsg` error.
There are still other tests failing

**Comment by aeschli** [comment]
Filed https://github.com/microsoft/vscode/issues/80304 for the remaining test failure.
