### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by johnschult** [microsoft/vscode#77099]
Issue Type: <b>Bug</b>

From time to time, I get a notification saying "Extension host terminated unexpectedly.". There are no additional details in the notification. Info from the developer tools console:

```
[Extension Host] debugger listening on port 26436
log.ts:173   ERR Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
    at X.getDataNode (file:///Users/johnschult/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:968:904)
    at X.reveal (file:///Users/johnschult/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:968:494)
    at e.<anonymous> (file:///Users/johnschult/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5357:306)
    at Generator.next (<anonymous>)
    at r (file:///Users/johnschult/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:293)
log.ts:173   ERR Error: [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/Users/johnschult/code/tcots-container/.vscode'
log.ts:173   ERR [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/Users/johnschult/code/tcots-container/.vscode'
log.ts:173   ERR Error: [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/Users/johnschult/code/tcots/.vscode'
log.ts:173   ERR [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/Users/johnschult/code/tcots/.vscode'
abstractExtensionService.ts:390 [ms-azuretools.vscode-apimanagement]: Unknown language in `contributes.vscode-apimanagement.language`. Provided value: aspnetcorerazor
_logMessageInConsole @ abstractExtensionService.ts:390
abstractTextMateService.ts:52 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Users/johnschult/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/johnschult/.vscode/extensions/ms-azure-devops.azure-pipelines-1.152.0/syntaxes/yaml.tmLanguage.json
register @ abstractTextMateService.ts:52
abstractTextMateService.ts:52 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///Users/johnschult/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///Users/johnschult/.vscode/extensions/ms-mssql.mssql-1.6.0/syntaxes/SQL.plist
register @ abstractTextMateService.ts:52
abstractTextMateService.ts:52 Overwriting grammar scope name to file mapping for scope source.ruby.
Old grammar file: file:///Users/johnschult/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/ruby/syntaxes/ruby.tmLanguage.json.
New grammar file: file:///Users/johnschult/.vscode/extensions/rebornix.ruby-0.24.0/syntaxes/ruby.cson.json
register @ abstractTextMateService.ts:52
abstractTextMateService.ts:52 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Users/johnschult/.vscode/extensions/ms-azure-devops.azure-pipelines-1.152.0/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/johnschult/.vscode/extensions/redhat.vscode-yaml-0.4.1/syntaxes/yaml.tmLanguage.json
register @ abstractTextMateService.ts:52
console.ts:134 [Extension Host] (node:82104) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:134
console.ts:134 [Extension Host] NightSwitch is now active!
console.ts:134 [Extension Host] (7/10/2019, 9:08:17 AM) [ExtensionActivated] Extension has been activated!
console.ts:134 [Extension Host] (7/10/2019, 9:08:17 AM) Spinning up telemetry client for id azure-pipelines, version 1.152.0
console.ts:134 [Extension Host] enabled Array(1)
console.ts:134 [Extension Host] No editors associated with document: /Users/johnschult/Library/Application Support/Code/User/settings.json
t.log @ console.ts:134
console.ts:134 [Extension Host] No editors associated with document: /Users/johnschult/code/tcots-container/docker/Dockerfile.git
t.log @ console.ts:134
console.ts:134 [Extension Host] No editors associated with document: /Users/johnschult/Library/Application Support/Code/User/settings.json
t.log @ console.ts:134
extensionHost.ts:201 Extension Host
extensionHost.ts:202 2019-07-10 09:08:29.928 Code Helper[82104:13833507] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
webviewElement.ts:363 [Embedded Page] Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
webviewElement.ts:363 [Embedded Page] You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
console.ts:134 [Extension Host] No editors associated with document: /Users/johnschult/Library/Application Support/Code/User/settings.json
t.log @ console.ts:134
console.ts:134 [Extension Host] rejected promise not handled within 1 second: StartCall
t.log @ console.ts:134
log.ts:173   ERR StartCall
extensionHost.ts:201 Extension Host
extensionHost.ts:202 Debugger attached.
bootstrap-window.js:212 [uncaught exception]: Error: write EPIPE
onUnexpectedError @ bootstrap-window.js:212
bootstrap-window.js:215 Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:788)
onUnexpectedError @ bootstrap-window.js:215
events.js:167 Uncaught Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:788)
abstractExtensionService.ts:155 Extension host terminated unexpectedly. Code:  null  Signal:  SIGSEGV
_onExtensionHostCrashed @ abstractExtensionService.ts:155
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
onDidNotificationChange @ notificationsAlerts.ts:40
2commentService.ts:385 Error: Canceled
    at Object.t.canceled (errors.ts:149)
    at Object.keys.forEach.e (rpcProtocol.ts:110)
    at Array.forEach (<anonymous>)
    at u.dispose (rpcProtocol.ts:108)
    at e.dispose (extensionHostProcessManager.ts:95)
    at P._stopExtensionHostProcess (abstractExtensionService.ts:120)
    at P._onExtensionHostCrashed (abstractExtensionService.ts:156)
    at P._onExtensionHostCrashed (extensionService.ts:367)
    at P._onExtensionHostCrashOrExit (abstractExtensionService.ts:147)
    at e.onDidExit (abstractExtensionService.ts:137)
    at d.fire (event.ts:558)
    at P._onExtHostProcessExit (extensionHost.ts:461)
    at ChildProcess._extensionHostProcess.on (extensionHost.ts:216)
    at ChildProcess.emit (events.js:182)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240)
```

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
vscode-toggle-quotes|Bri|0.3.2
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-markdownlint|Dav|0.28.0
vscode-eslint|dba|1.9.0
gitlens|eam|9.8.3
EditorConfig|Edi|0.13.0
prettier-vscode|esb|1.9.0
vsc-travis-ci-status|fel|1.1.0
nightswitch|gha|1.1.0
docker-linter|hen|0.5.0
rest-client|hum|0.21.3
chat|kar|0.15.5
haml|kar|1.2.0
ruby-rubocop|mis|0.8.1
azure-pipelines|ms-|1.152.0
azurerm-vscode-tools|msa|0.6.0
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.15.0
vscode-azurefunctions|ms-|0.17.1
vscode-azurestorage|ms-|0.7.0
vscode-cosmosdb|ms-|0.10.2
vscode-docker|ms-|0.7.0
vscode-aks-tools|ms-|0.0.1
vscode-kubernetes-tools|ms-|1.0.1
mssql|ms-|1.6.0
atom-keybindings|ms-|3.0.6
azure-account|ms-|0.8.4
azurecli|ms-|0.4.6
vscode-node-azure-pack|ms-|0.0.9
vsliveshare|ms-|1.0.488
vsliveshare-audio|ms-|0.1.59
ruby|reb|0.24.0
vscode-yaml|red|0.4.1
code-settings-sync|Sha|3.3.1
bracket-padder|via|0.1.1
azure-iot-toolkit|vsc|2.8.0
vscode-nginx|wil|0.7.1

(5 theme extensions excluded)

</details>

**Comment by solrevdev** [comment]
Me too, it's been happening for weeks now on both the stable and the insiders versions. Sometimes it is just a nag but sometimes if stops features from working. 



#### Code Version 1.36.1 (1.36.1)

```text
[Extension Host] debugger listening on port 35963
abstractTextMateService.ts:52 Overwriting grammar scope name to file mapping for scope text.log.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/log/syntaxes/log.tmLanguage.json.
New grammar file: file:///Users/solrevdev/.vscode/extensions/emilast.logfilehighlighter-2.5.0/syntaxes/log.tmLanguage
register @ abstractTextMateService.ts:52
abstractTextMateService.ts:52 Overwriting grammar scope name to file mapping for scope source.cs.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/csharp/syntaxes/csharp.tmLanguage.json.
New grammar file: file:///Users/solrevdev/.vscode/extensions/maximetinu.identical-sublime-monokai-csharp-theme-colorizer-0.11.1/syntaxes/csharp.tmLanguage.json
register @ abstractTextMateService.ts:52
abstractTextMateService.ts:52 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///Users/solrevdev/.vscode/extensions/mtxr.sqltools-0.19.6/language/sql.tmLanguage.json
register @ abstractTextMateService.ts:52
abstractTextMateService.ts:52 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/solrevdev/.vscode/extensions/redhat.vscode-yaml-0.4.1/syntaxes/yaml.tmLanguage.json
register @ abstractTextMateService.ts:52
console.ts:134 [IPC Library: File Watcher (nsfw)] Unhandled Promise Rejection:  Error: Path must be a valid path to a file or a directory.
    at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-nsfw/lib/src/index.js:79:11
t.log @ console.ts:134
log.ts:173   ERR Error: [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/home/solrevdev/Dropbox/_docs/.vscode'
log.ts:173   ERR [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/home/solrevdev/Dropbox/_docs/.vscode'
extensionHost.ts:201 Extension Host
extensionHost.ts:202 Debugger attached.
abstractExtensionService.ts:155 Extension host terminated unexpectedly. Code:  null  Signal:  SIGSEGV
_onExtensionHostCrashed @ abstractExtensionService.ts:155
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
onDidNotificationChange @ notificationsAlerts.ts:40
```

#### Code Insiders - 1.37.0-insider

```text
Version: 1.37.0-insider
Commit: 46cc0a1670b7047e610aaef1bf84f1190802e9ec
Date: 2019-07-11T05:37:24.194Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0
```

```text
[Extension Host] debugger listening on port 57902
console.ts:137 [IPC Library: File Watcher (nsfw)] Unhandled Promise Rejection:  Error: Path must be a valid path to a file or a directory.
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/nsfw/lib/src/index.js:79:11
t.log @ console.ts:137
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.log.
Old grammar file: file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/extensions/log/syntaxes/log.tmLanguage.json.
New grammar file: file:///Users/solrevdev/.vscode-insiders/extensions/emilast.logfilehighlighter-2.5.0/syntaxes/log.tmLanguage
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.cs.
Old grammar file: file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/extensions/csharp/syntaxes/csharp.tmLanguage.json.
New grammar file: file:///Users/solrevdev/.vscode-insiders/extensions/maximetinu.identical-sublime-monokai-csharp-theme-colorizer-0.11.1/syntaxes/csharp.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///Users/solrevdev/.vscode-insiders/extensions/mtxr.sqltools-0.19.6/language/sql.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/solrevdev/.vscode-insiders/extensions/redhat.vscode-yaml-0.4.1/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:45
extensionHost.ts:201 Extension Host
extensionHost.ts:202 Debugger attached.
abstractExtensionService.ts:155 Extension host terminated unexpectedly. Code:  null  Signal:  SIGSEGV
_onExtensionHostCrashed @ abstractExtensionService.ts:155
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
onDidNotificationChange @ notificationsAlerts.ts:40
DevTools failed to parse SourceMap: file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/xterm/lib/xterm.js.map
```


#### system 

```text
                 -/+:.          solrevdev@macmini
                :++++.          OS: 64bit Mac OS X 10.14.5 18F132
               /+++/.           Kernel: x86_64 Darwin 18.6.0
       .:-::- .+/:-``.::-       Uptime: 3d 48m
    .:/++++++/::::/++++++/:`    Packages: 388
  .:///////////////////////:`   Shell: zsh 5.7.1
  ////////////////////////`     Resolution: 2560x1440
 -+++++++++++++++++++++++`      DE: Aqua
 /++++++++++++++++++++++/       WM: Quartz Compositor
 /sssssssssssssssssssssss.      WM Theme: Blue
 :ssssssssssssssssssssssss-     Font: Monaco
  osssssssssssssssssssssssso/`  CPU: Intel Core i5-4278U @ 2.60GHz
  `syyyyyyyyyyyyyyyyyyyyyyyy+`  GPU: Intel Iris 
   `ossssssssssssssssssssss/    RAM: 8548MiB / 16384MiB
     :ooooooooooooooooooo+.    
      `:+oo+/:-..-:/+o+/-      
```


#### dotnet info 

```
dotnet --info   
.NET Core SDK (reflecting any global.json):
 Version:   2.2.107
 Commit:    2212cac826

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.107/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.1.403 [/usr/local/share/dotnet/sdk]
  2.1.505 [/usr/local/share/dotnet/sdk]
  2.2.100 [/usr/local/share/dotnet/sdk]
  2.2.102 [/usr/local/share/dotnet/sdk]
  2.2.104 [/usr/local/share/dotnet/sdk]
  2.2.105 [/usr/local/share/dotnet/sdk]
  2.2.107 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

#### extensions 

```text
code --list-extensions | xargs -L 1 echo ''                      
 abusaidm.html-snippets
 aledev29.razor-snippets-for-asp-net-core
 atlassian.atlascode
 auchenberg.vscode-browser-preview
 bierner.emojisense
 christian-kohler.npm-intellisense
 christian-kohler.path-intellisense
 CoenraadS.bracket-pair-colorizer
 dakara.transformer
 dbaeumer.vscode-eslint
 donjayamanne.githistory
 DotJoshJohnson.xml
 dsznajder.es7-react-js-snippets
 dunstontc.viml
 eamodio.gitlens
 ecmel.vscode-html-css
 EditorConfig.EditorConfig
 eg2.vscode-npm-script
 emilast.LogFileHighlighter
 Equinusocio.vsc-material-theme
 esbenp.prettier-vscode
 fabiospampinato.vscode-todo-plus
 formulahendry.auto-close-tag
 formulahendry.auto-rename-tag
 formulahendry.dotnet-test-explorer
 foxundermoon.shell-format
 GitHub.vscode-pull-request-github
 GrapeCity.gc-excelviewer
 hbenl.vscode-firefox-debug
 Ho-Wan.vscode-trello-viewer
 HookyQR.beautify
 humao.rest-client
 jchannon.csharpextensions
 jesschadwick.nuget-reverse-package-search
 jmrog.vscode-nuget-package-manager
 johnpapa.vscode-peacock
 k--kato.docomment
 karigari.chat
 kenhowardpdx.vscode-gist
 konstantin.wrapSelection
 lostintangent.vsls-whiteboard
 mads-hartmann.bash-ide-vscode
 maximetinu.identical-sublime-monokai-csharp-theme-colorizer
 mikestead.dotenv
 ms-azuretools.vscode-docker
 MS-CEINTL.vscode-language-pack-en-GB
 ms-python.python
 ms-vscode-remote.remote-containers
 ms-vscode-remote.remote-ssh
 ms-vscode-remote.remote-ssh-edit
 ms-vscode-remote.remote-ssh-explorer
 ms-vscode-remote.remote-wsl
 ms-vscode-remote.vscode-remote-extensionpack
 ms-vscode.csharp
 ms-vscode.powershell
 ms-vscode.vscode-typescript-tslint-plugin
 ms-vsliveshare.vsliveshare
 ms-vsliveshare.vsliveshare-audio
 ms-vsliveshare.vsliveshare-pack
 msjsdiag.debugger-for-chrome
 mtxr.sqltools
 nepaul.editorconfiggenerator
 octref.vetur
 patbenatar.advanced-new-file
 PKief.material-icon-theme
 pnp.polacode
 quicktype.quicktype
 redhat.vscode-yaml
 richie5um2.vscode-sort-json
 ritwickdey.LiveServer
 rogalmic.bash-debug
 ryu1kn.partial-diff
 Shan.code-settings-sync
 SmukkeKim.theme-setimonokai
 streetsidesoftware.code-spell-checker
 tintoy.msbuild-project-tools
 Tyriar.sort-lines
 VisualStudioExptTeam.vscodeintellicode
 vscode-icons-team.vscode-icons
 vscodevim.vim
 WakaTime.vscode-wakatime
 WallabyJs.quokka-vscode
 yatki.vscode-surround
 yzhang.markdown-all-in-one
 Zignd.html-css-class-completion

```

**Comment by danilofuchs** [comment]
Having the same issue since last release.

After reload, the console shows:
```
[Extension Host] (node:21284) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

Extensions:
```
akamud.vscode-theme-onedark
 be5invis.vscode-icontheme-nomo-dark
 bmewburn.vscode-intelephense-client
 castwide.solargraph
 CoenraadS.bracket-pair-colorizer-2
 Dart-Code.dart-code
 Dart-Code.flutter
 dbaeumer.vscode-eslint
 eamodio.gitlens
 EditorConfig.EditorConfig
 esbenp.prettier-vscode
 formulahendry.code-runner
 GitHub.vscode-pull-request-github
 johnpapa.vscode-peacock
 jspolancor.presentationmode
 karigari.chat
 kisstkondoros.vscode-gutter-preview
 KnisterPeter.vscode-commitizen
 mathiasfrohlich.Kotlin
 Metatype.copilot-vscode
 mikestead.dotenv
 ms-python.python
 ms-vscode-remote.remote-wsl
 ms-vscode.cpptools
 ms-vsliveshare.vsliveshare
 ms-vsliveshare.vsliveshare-audio
 ms-vsliveshare.vsliveshare-pack
 msjsdiag.debugger-for-chrome
 PKief.material-icon-theme
 qinjia.seti-icons
 redhat.java
 redhat.vscode-yaml
 Shan.code-settings-sync
 VisualStudioExptTeam.vscodeintellicode
 vscjava.vscode-java-debug
 vscjava.vscode-java-dependency
 vscjava.vscode-java-pack
 vscjava.vscode-java-test
 vscjava.vscode-maven
 WakaTime.vscode-wakatime
 wayou.vscode-todo-highlight
 yzhang.markdown-all-in-one
```

**Comment by Gruntfuggly** [comment]
Same issue. There doesn't seem to be any way to work out which extension caused the crash?

**Comment by FabienDehopre** [comment]
Same issue with version 1.36.1
About info:
```
Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134
```

Stacktrace: 
```
Extension host terminated unexpectedly. Code:  3221225477  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:155
```

**Comment by jacksteamdev** [comment]
Same issue here. 

FWIW, I've been able to reliably crash the extension host by pasting or opening files with certain emojis.

Emojis: `🧐`, `🤩`, and probably others. They're relatively new (both added in Unicode 10.0 and Emoji 5.0).

About:
```
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-20-generic
```

Extensions:
```
a-bentofreire.vsctoix-1.7.1
alefragnani.bookmarks-10.4.4
andrejunges.handlebars-0.4.1
ban.spellright-3.0.46
bengreenier.vscode-node-readme-3.0.2
bierner.emojisense-0.5.1
bierner.github-markdown-preview-0.0.2
bierner.markdown-checkbox-0.1.3
bierner.markdown-emoji-0.0.9
bierner.markdown-preview-github-styles-0.1.6
bierner.markdown-yaml-preamble-0.0.4
britesnow.vscode-toggle-quotes-0.3.2
bungcip.better-toml-0.3.2
christian-kohler.npm-intellisense-1.3.0
chunsen.bracket-select-2.0.1
codestream.codestream-1.3.2
davidanson.vscode-markdownlint-0.28.0
dbaeumer.vscode-eslint-1.9.0
donjayamanne.githistory-0.4.6
dzannotti.vscode-babel-coloring-0.0.4
equinusocio.vsc-material-theme-29.2.0
esbenp.prettier-vscode-1.9.0
github.vscode-pull-request-github-0.9.1
gruntfuggly.todo-tree-0.0.139
hbenl.vscode-test-explorer-2.14.0
herrmannplatz.npm-dependency-links-1.0.1
karigari.chat-0.15.5
mgmcdermott.vscode-language-babel-0.0.23
michelemelluso.gitignore-1.0.1
mrmlnc.vscode-duplicate-1.2.1
msjsdiag.debugger-for-chrome-4.11.6
ms-vscode.vscode-typescript-tslint-plugin-1.2.2
ms-vsliveshare.vsliveshare-1.0.540
nmsmith89.incrementor-0.1.0
perkovec.emoji-0.0.3
pkief.material-icon-theme-3.8.1
redhat.vscode-yaml-0.4.1
richie5um2.vscode-sort-json-1.14.0
ritwickdey.liveserver-5.6.1
robinbentley.sass-indented-1.5.1
rtbenfield.vscode-jest-test-adapter-0.2.0
rust-lang.rust-0.6.1
shan.code-settings-sync-3.4.1
shinnn.stylelint-0.51.0
sleistner.vscode-fileutils-2.14.5
stackbreak.comment-divider-0.2.0
thomascsd.vscode-readme-pattern-1.0.1
tlevesque.import-to-require-0.7.0
tyriar.sort-lines-1.8.0
ub1que.add-only-1.0.1
unional.vscode-sort-package-json-1.2.0
vangware.dark-plus-material-2.1.0
wallabyjs.quokka-vscode-1.0.237
wesbos.theme-cobalt2-2.1.6
wmaurer.change-case-1.0.0
yzhang.markdown-all-in-one-2.4.2
zengxingxin.sort-js-object-keys-1.0.6
zhuangtongfa.material-theme-2.26.0
```

**Comment by jacksteamdev** [comment]
The extensions present in all three lists are:

```
dbaeumer.vscode-eslint
esbenp.prettier-vscode
karigari.chat
ms-vsliveshare.vsliveshare
msjsdiag.debugger-for-chrome
redhat.vscode-yaml
yzhang.markdown-all-in-one
``` 

So it's got to be one of them!

**Comment by mjolka** [comment]
Thanks @jacksteamdev for the list. Disabling `karigari.chat` seems to have fixed the problem for me.

**Comment by alexandrudima** [comment]
@mjolka Will you please report this against `karigari.chat`? Most likely, they use a native node module (C++) and there must be some segmentation fault going on... Unfortunately, we cannot protect our process from that, so there is nothing to do on our side.

**Comment by clayms** [comment]
This is [Live Share Chat `karigari.chat`](https://github.com/vsls-contrib/chat) that comes with the installation of [MS Live Share Extension Pack](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare-pack).
