### ISSUE TITLE
Is there a Visual Studio Code problem matcher for `dotnet test` (using mstest)?

### ISSUE THREAD

**Issue by peterhuene** [microsoft/vscode#77304]
_From @AnthonyMastrean on Friday, July 12, 2019 7:44:04 PM_

Everywhere I look, people are using this built in `$msCompile` problem matcher, but it doesn't seem to work on my machine.

## Steps to reproduce

Write some failing mstest unit tests. Use the following VS Code custom task. Run tests w/ that task.

**tasks.json**
```json
        {
            "label": "test",
            "type": "process",
            "group": {
                "kind": "test",
                "isDefault": true
            },
            "command": "dotnet",
            "args": ["test"],
            "problemMatcher": "$msCompile"
        }
```
**output**
```
Test run for c:\Users\anthony.mastrean.CORP\Work\gitlab.com\anthonymastrean\simplenetq\test\SimpleNetQ.Tests\bin\Debug\netcoreapp3.0\SimpleNetQ.Tests.dll(.NETCoreApp,Version=v3.0)
Microsoft (R) Test Execution Command Line Tool Version 16.0.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Failed   TestMethod1
Error Message:
 Assert.Fail failed. 
Stack Trace:
   at SimpleNetQ.Tests.UnitTest1.TestMethod1() in c:\Users\anthony.mastrean.CORP\Work\gitlab.com\anthonymastrean\simplenetq\test\SimpleNetQ.Tests\UnitTest1.cs:line 11

Failed   TestMethod2
Error Message:
 Assert.Fail failed. 
Stack Trace:
   at SimpleNetQ.Tests.UnitTest1.TestMethod2() in c:\Users\anthony.mastrean.CORP\Work\gitlab.com\anthonymastrean\simplenetq\test\SimpleNetQ.Tests\UnitTest1.cs:line 17

Failed   TestMethod1
Error Message:
 Assert.Fail failed. 
Stack Trace:
   at SimpleNetQ.Tests.UnitTest2.TestMethod1() in c:\Users\anthony.mastrean.CORP\Work\gitlab.com\anthonymastrean\simplenetq\test\SimpleNetQ.Tests\UnitTest2.cs:line 11


Total tests: 3. Passed: 0. Failed: 3. Skipped: 0.
Test Run Failed.
Test execution time: 0.6011 Seconds
```

## Expected  behavior

Failed tests should be recorded as problems in the Problems panel.

## Actual behavior

Failed tests are not recorded as problems.
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

_Copied from original issue: dotnet/cli#11856_

**Comment by peterhuene** [comment]
_From @AnthonyMastrean on Friday, July 12, 2019 7:45:03 PM_

I now realize this could be a vscode or testfx issue (depending on where mstest problems are tracked or if it's even their problem).

**Comment by AnthonyMastrean** [comment]
@peterhuene the testfx people are [closing the issue](https://github.com/microsoft/testfx/issues/627#issuecomment-511771195) saying the problem is with vscode... 😞 

I don't know where to go to be heard... I either need the problem matcher to evolve to a full blown text parsing state machine or the mstest output needs to change to not be so stylish and to just print more simple information on a line.

🤷‍♂

**Comment by AnthonyMastrean** [comment]
Part of my problem is that I can't figure out what I'm doing wrong with a multiline matcher.

https://stackoverflow.com/questions/57013516/how-do-i-write-a-multline-problem-matcher-for-mstest

**Comment by peterhuene** [comment]
@weinand I think @AnthonyMastrean was requesting a feature for a built-in problem matcher for MSTest output (similar to how `$msCompile` works for output from csc/vbc) rather than a question.

Such a feature (plus potentially one that would match xunit output too) would go along way to making `dotnet test` failures show up as problems out of the box.
