### ISSUE TITLE
TerminalVirtualProcess.start is not called when using task CustomExecution2

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/vscode#77428]
- VSCode Version:
Version: 1.37.0-insider (user setup)
Commit: 894056d11c7fffb261a0100fd4dcbf8cff84a8c0
Date: 2019-07-15T05:26:27.959Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18936

- OS Version: - Windows x64 18936

Steps to Reproduce:

1. Create a task provider in an extension that uses CustomExecution2 leveraging the TerminalVirtualProcess.
2. Expose a task
3. When task execution begins, the terminal is created, but then VSCode throws the following exception and the extension's implementation of TerminalVirtualProcess::start is never called.

  ERR Cannot read property 'startSendingEvents' of undefined: TypeError: Cannot read property 'startSendingEvents' of undefined
	at ExtHostTerminalService.$startVirtualProcess (e:\repos\vscode\out\vs\workbench\api\node\extHostTerminalService.js:473:41)
	at RPCProtocol._doInvokeHandler (e:\repos\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:326:27)
	at RPCProtocol._invokeHandler (e:\repos\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:311:45)
	at RPCProtocol._receiveRequest (e:\repos\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:243:32)
	at RPCProtocol._receiveOneMessage (e:\repos\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:171:26)
	at define.constructor._protocol.onMessage (e:\repos\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:61:52)
	at Emitter.fire (e:\repos\vscode\out\vs\base\common\event.js:455:38)
	at deliverMessages (e:\repos\vscode\out\vs\base\parts\ipc\common\ipc.net.js:333:25)
	at source (e:\repos\vscode\out\vs\base\parts\ipc\common\ipc.net.js:339:13)
	at Emitter.fire (e:\repos\vscode\out\vs\base\common\event.js:455:38)
	at __awaiter.constructor.protocol.onMessage (e:\repos\vscode\out\vs\workbench\services\extensions\node\extensionHostProcessSetup.js:153:45)
	at Emitter.fire (e:\repos\vscode\out\vs\base\common\event.js:455:38)
	at deliverMessages (e:\repos\vscode\out\vs\base\parts\ipc\common\ipc.net.js:333:25)
	at source (e:\repos\vscode\out\vs\base\parts\ipc\common\ipc.net.js:339:13)
	at Emitter.fire (e:\repos\vscode\out\vs\base\common\event.js:455:38)
	at PersistentProtocol._receiveMessage (e:\repos\vscode\out\vs\base\parts\ipc\common\ipc.net.js:564:37)
	at define.constructor._socketDisposables.push._socketReader.onMessage.msg (e:\repos\vscode\out\vs\base\parts\ipc\common\ipc.net.js:442:83)
	at Emitter.fire (e:\repos\vscode\out\vs\base\common\event.js:455:38)
	at ProtocolReader.acceptChunk (e:\repos\vscode\out\vs\base\parts\ipc\common\ipc.net.js:183:37)
	at define.constructor._register._socket.onData.data (e:\repos\vscode\out\vs\base\parts\ipc\common\ipc.net.js:152:61)
	at Socket.listener (e:\repos\vscode\out\vs\base\parts\ipc\node\ipc.net.js:16:40)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by GabeDeBacker** [comment]
This appears to be related to the changes made to address this issue:
 #77228

**Comment by Tyriar** [comment]
This was verified in the main test plan
