### ISSUE TITLE
Various problems extracting and building Monaco Editor code, 'gulp editor-distro' fails with errors (some of which I can fix, but I'm stuck now)

### ISSUE THREAD

**Issue by ashleydavis** [microsoft/vscode#77454]
I've been learning how to build the Monaco Editor code and I've been having some problems running _gulp editor-distro_. I've fixed some errors already if someone could nudge me in the right direction I can solve all the problems and submit a PR.

Please note that I am already able to build and run vscode from source code - what I'm trying to do now is run the build script to extract the Monaco Editor code.

I have my own fork of vscode but I've reproduced these issues in the original vscode repo (master branch), just to make sure I didn't add any problems myself.

I'm working on Windows 10 with Node.js v10.15.2 installed.

So I cloned vscode, then ran `yarn install`, then `npm run compile`.  After that I ran

`gulp editor-distro`

I get a series of errors, some of which I'm able to fix, some not.

First all is there anything wrong with my setup? Are there any other commands I should run before this?

Here is the first error:

`inlineEntryPoint.1.ts: - 33,7 - "Generic type 'SimpleWorkerClient<W, H>' requires 2 type argument(s)."
`

I fixed this by updating the use of SimpleWorkerClient in the file monaco.usage.recipe.

Now I run the build script again and it gets through the tasks `extract-editor-src` and `compile-editor-amd`.

Now it fails on `compile-editor-esm`.

This is the first error: 

error TS5058: The specified path does not exist: 'C:/projects/data-forge-notebook/monaco/vscode-orig/out-editor-esm/tsconfig.base.json'

I think I could fix this by accounting for tsconfig.base.json in the file build/lib/standalone.ts. But I prefer to side step the issue for now so I remove the ESM build tasks. I just want to see if the build process can pass without them.

Now I'm get these errors and I'm a bit stumped:

```
[19:17:09] Finished extract-editor-src after 98602 ms
[19:17:09] Starting compile-editor-amd ...
[19:17:09] Starting compilation...
[19:17:46] Error: C:/projects/data-forge-notebook/monaco/vscode-orig/out-editor-src/vs/platform/theme/common/styler.ts(179,2): No value exists in scope for the shorthand property 'treeIndentGuidesStroke'. Either declare one or provide an initializer.
[19:17:46] Error: C:/projects/data-forge-notebook/monaco/vscode-orig/out-editor-src/vs/platform/storage/common/storage.ts(24,17): Cannot find name 'ServiceIdentifier'.
[19:17:46] Error: C:/projects/data-forge-notebook/monaco/vscode-orig/out-editor-src/vs/platform/storage/common/storage.ts(24,17): Property '_serviceBrand' of exported interface has or is using private name 'ServiceIdentifier'.
[19:17:46] Error: C:/projects/data-forge-notebook/monaco/vscode-orig/out-editor-src/vs/platform/progress/common/progress.ts(24,17): Cannot find name 'ServiceIdentifier'.
[19:17:46] Error: C:/projects/data-forge-notebook/monaco/vscode-orig/out-editor-src/vs/platform/progress/common/progress.ts(24,17): Property '_serviceBrand' of exported interface has or is using private name 'ServiceIdentifier'.
[19:17:46] Error: C:/projects/data-forge-notebook/monaco/vscode-orig/out-editor-src/vs/platform/notification/common/notification.ts(52,17): Cannot find name 'ServiceIdentifier'.
[19:17:46] Error: C:/projects/data-forge-notebook/monaco/vscode-orig/out-editor-src/vs/platform/notification/common/notification.ts(52,17): Property '_serviceBrand' of exported interface has or is using private name 'ServiceIdentifier'.
[19:17:46] Finished compilation with 7 errors after 36341 ms
[19:17:46] Error: C:/projects/data-forge-notebook/monaco/vscode-orig/out-editor-src/vs/platform/theme/common/styler.ts(179,2): No value exists in scope for the shorthand property 'treeIndentGuidesStroke'. Either declare one or provide an initializer.
[19:17:46] Error: C:/projects/data-forge-notebook/monaco/vscode-orig/out-editor-src/vs/platform/storage/common/storage.ts(24,17): Cannot find name 'ServiceIdentifier'.
[19:17:46] Error: C:/projects/data-forge-notebook/monaco/vscode-orig/out-editor-src/vs/platform/storage/common/storage.ts(24,17): Property '_serviceBrand' of exported interface has or is using private name 'ServiceIdentifier'.
[19:17:46] Error: C:/projects/data-forge-notebook/monaco/vscode-orig/out-editor-src/vs/platform/progress/common/progress.ts(24,17): Cannot find name 'ServiceIdentifier'.
[19:17:46] Error: C:/projects/data-forge-notebook/monaco/vscode-orig/out-editor-src/vs/platform/progress/common/progress.ts(24,17): Property '_serviceBrand' of exported interface has or is using private name 'ServiceIdentifier'.
[19:17:46] Error: C:/projects/data-forge-notebook/monaco/vscode-orig/out-editor-src/vs/platform/notification/common/notification.ts(52,17): Cannot find name 'ServiceIdentifier'.
[19:17:46] Error: C:/projects/data-forge-notebook/monaco/vscode-orig/out-editor-src/vs/platform/notification/common/notification.ts(52,17): Property '_serviceBrand' of exported interface has or is using private name 'ServiceIdentifier'.
[19:17:46] Finished compilation with 7 errors after 36353 ms
[19:17:46] 'editor-distro' errored after 2.25 min
[19:17:46] Error: Found 7 errors
    at Stream.<anonymous> (C:\projects\data-forge-notebook\monaco\vscode-orig\build\lib\reporter.js:74:29)
    at _end (C:\projects\data-forge-notebook\monaco\vscode-orig\node_modules\through\index.js:65:9)
    at Stream.stream.end (C:\projects\data-forge-notebook\monaco\vscode-orig\node_modules\through\index.js:74:5)
    at Stream.onend (internal/streams/legacy.js:42:10)
    at Stream.emit (events.js:194:15)
    at Stream.EventEmitter.emit (domain.js:459:23)
    at drain (C:\projects\data-forge-notebook\monaco\vscode-orig\node_modules\through\index.js:34:23)
    at Stream.stream.queue.stream.push (C:\projects\data-forge-notebook\monaco\vscode-orig\node_modules\through\index.js:45:5)
    at Stream.end (C:\projects\data-forge-notebook\monaco\vscode-orig\node_modules\through\index.js:15:35)
    at _end (C:\projects\data-forge-notebook\monaco\vscode-orig\node_modules\through\index.js:65:9)
```

Any advice on how to proceed? 

I need a nudge in the right direction then I'll get all these fixes into a PR.

**Comment by ashleydavis** [comment]
Anyone had a chance to look into this yet?

**Comment by rebornix** [comment]
The error `inlineEntryPoint.1.ts: - 33,7 - "Generic type 'SimpleWorkerClient<W, H>' requires 2 type argument(s)."` was already fixed.

**Comment by ashleydavis** [comment]
That's great. 

Any idea what's could be causing the errors in the gulp task `compile-editor-esm`?

Thanks

**Comment by ashleydavis** [comment]
@alexandrudima thanks so much for fixing this. It works great now.

I've created my own 'meta-repo' for building Monaco Editor directly from the vscode repo. 

You can find it here if you were interested in having a look: https://github.com/data-forge-notebook/monaco-build
