### ISSUE TITLE
Smoke test fail

### ISSUE THREAD

**Issue by abist** [microsoft/vscode#77670]
- VSCode Version: 1.37.0
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Run smoke test using `yarn smoketest`

Does this issue occur when all extensions are disabled?: Yes

Expected - The smoke tests should run fine
Actual - The smoke tests fail wherever a `click` is expected. Everything else works fine.

Error for every test - 
```
** Timeout!
Error: Blocked remote.getCurrentWebContents()
    at vscode\.build\electron\resources\electron.asar\browser\rpc-server.js:359:13
    at EventEmitter.ipcMain.on.args (vscode\.build\electron\resources\electron.asar\browser\rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (\vscode\.build\electron\resources\electron.asar\browser\api\web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)
```

**Comment by joaomoreno** [comment]
Are you running straight from `master` without any changes?

**Comment by abist** [comment]
Yes

**Comment by abist** [comment]
Yes

**Comment by Tyriar** [comment]
This happens because of an Electron security measure, this blocks me so I'll take it.
