### ISSUE TITLE
Can not install autopep8 for Python.

### ISSUE THREAD

**Issue by Phantom6234** [microsoft/vscode#77707]
I currently live in Korea, so that may be part of the problem. But, other than that, I only started using vscode a few months ago. And I only have the Python extension enabled. I would be very grateful if you could help me.

**Comment by Phantom6234** [comment]
& C:/Users/Owner/Anaconda3/Scripts/conda.exe install autopep8
Traceback (most recent call last):
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda\exceptions.py", line 1043,
in __call__
    return func(*args, **kwargs)
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "C:\Users\Owner\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda\cli\main_install.py", line
8, in <module>
    from .install import install
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda\cli\install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda\core\index.py", line 9, in
<module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "C:\Users\Owner\Anaconda3\lib\site-packages\libarchive\__init__.py", line 1,
in <module>
    from .entry import ArchiveEntry
  File "C:\Users\Owner\Anaconda3\lib\site-packages\libarchive\entry.py", line 6, in
<module>
    from . import ffi
  File "C:\Users\Owner\Anaconda3\lib\site-packages\libarchive\ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "C:\Users\Owner\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Owner\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Owner\Anaconda3\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda\cli\main.py", line 150, in
main
    return conda_exception_handler(_main, *args, **kwargs)
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda\exceptions.py", line 1335,
in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda\exceptions.py", line 1046,
in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda\exceptions.py", line 1090,
in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda\exceptions.py", line 1101,
in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda\exceptions.py", line 1171,
in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda\core\index.py", line 9, in
<module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda_package_handling\api.py", line 7, in <module>
    from .tarball import CondaTarBZ2 as _CondaTarBZ2
  File "C:\Users\Owner\Anaconda3\lib\site-packages\conda_package_handling\tarball.py", line 7, in <module>
    import libarchive
  File "C:\Users\Owner\Anaconda3\lib\site-packages\libarchive\__init__.py", line 1,
in <module>
    from .entry import ArchiveEntry
  File "C:\Users\Owner\Anaconda3\lib\site-packages\libarchive\entry.py", line 6, in
<module>
    from . import ffi
  File "C:\Users\Owner\Anaconda3\lib\site-packages\libarchive\ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "C:\Users\Owner\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Owner\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None


(This is what appeared in the terminal window)
