### ISSUE TITLE
VSC won't launch from  WSL2 in Win build 18947

### ISSUE THREAD

**Issue by kobenauf** [microsoft/vscode#77898]
Issue Type: <b>Bug</b>

This morning I installed Windows build 18947, and since then, I am unable to launch VSC from a WSL 2 shell using `code .`, which used to work.

I notice if I edit the `code` launch script and remove ELECTRON_RUN_AS_NODE=1 from this line it sort of works:
WSL_EXT_WLOC=$(ELECTRON_RUN_AS_NODE=1 "$ELECTRON" ".\resources\app\out\cli.js" --locate-extension $WSL_EXT_ID)

However, it causes VSC to launch (rather than nothing happening) but VSC does not open the current folder.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18947

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (53.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
tslint|eg2|1.0.44
prettier-vscode|esb|1.9.0
nbpreviewer|jit|1.2.2
vscode-docker|ms-|0.7.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.6.24221
remote-wsl|ms-|0.38.10
cpptools|ms-|0.24.1
Go|ms-|0.11.4
powershell|ms-|2019.5.0
vscode-jest|Ort|3.0.2
vscode-yaml|red|0.4.1
rust|rus|0.6.1
debug|web|0.23.1

(1 theme extensions excluded)

</details>

**Comment by kobenauf** [comment]
After posting this, I found [63539](https://github.com/microsoft/vscode/issues/63539) that sounds similar, but was closed without resolution.

**Comment by kobenauf** [comment]
Here's a weird thing I discovered.  If I run `code .` from wsl 2, it hangs and nothing opens.  But if I then enter ctrl+z to suspend the process, and then do `fg` to restart it, the VSC window opens.

**Comment by dustinwdev** [comment]
I'm getting the same results after installing Build 18945.

**Comment by jakeklassen** [comment]
Also seeing the same issue after the upgrade.

**Comment by MichaelTong** [comment]
Same in 18945

**Comment by kobenauf** [comment]
Another thing I see that might be relevant, in Process Explorer within VSC, I see this error:
WSL: Ubuntu
Fetching remote diagnostics for 'WSL: Ubuntu' failed: your 131072x1 screen size is bogus. expect trouble your 131072x1 screen size is bogus. expect trouble

**Comment by lee0c** [comment]
I'm noticing similar behavior (Build 18950, Insiders - but was seeing this before the last update) but when I try to put the suspended job in the background I get the following:

```
The factory method of "vs/server/remoteCli" has thrown an exception
{ Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at Object.spawn (child_process.js:533:9)
    at l (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteCli.js:85:650)
    at Object.<anonymous> (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteCli.js:87:1010)
    at Function.t._safeInvokeFunction (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:19:945)
    at Function.t._invokeFactory (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:20:175)
    at t.complete (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:20:412)
    at s._onModuleComplete (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:30:614)
    at s._onModuleComplete (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:30:858)
    at s._onModuleComplete (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:30:858)
    at s._onModuleComplete (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:30:858)
    at s._resolve (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:30:174)
    at s.defineModule (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:24:534)
    at o (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:28:673)
    at Object.l (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:36:291)
    at Function.t._safeInvokeFunction (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:19:945)
    at Function.t._invokeFactory (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:20:175)
    at t.complete (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:20:412)
    at s._onModuleComplete (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:30:614)
    at s._onModuleComplete (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:30:858)
    at s._resolve (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:30:174)
    at s.defineModule (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:24:534)
    at o (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:31:789)
    at c (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:17:118)
    at Object.<anonymous> (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteCli.nls.js:4:1)
    at t._createAndEvalScript (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:17:162)
    at /home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:16:762
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3) errno: 'EPERM', code: 'EPERM', syscall: 'spawn' }
Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at Object.spawn (child_process.js:533:9)
    at l (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteCli.js:85:650)
    at Object.<anonymous> (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteCli.js:87:1010)
    at Function.t._safeInvokeFunction (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:19:945)
    at Function.t._invokeFactory (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:20:175)
    at t.complete (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:20:412)
    at s._onModuleComplete (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:30:614)
    at s._onModuleComplete (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:30:858)
    at s._onModuleComplete (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:30:858)
    at s._onModuleComplete (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:30:858)
    at s._resolve (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:30:174)
    at s.defineModule (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:24:534)
    at o (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:28:673)
    at Object.l (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:36:291)
    at Function.t._safeInvokeFunction (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:19:945)
    at Function.t._invokeFactory (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:20:175)
    at t.complete (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:20:412)
    at s._onModuleComplete (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:30:614)
    at s._onModuleComplete (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:30:858)
    at s._resolve (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:30:174)
    at s.defineModule (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:24:534)
    at o (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:31:789)
    at c (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:17:118)
    at Object.<anonymous> (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteCli.nls.js:4:1)
    at t._createAndEvalScript (/home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:17:162)
    at /home/lecattar/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/loader.js:16:762
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

[1]  + 467 done       code .
```

In digging around in the startup script I've similarly noticed that I can get Code to start up by fiddling with specific lines, but things like `WSL_EXT_WLOC=$("$ELECTRON" ".\resources\app\out\cli.js" --locate-extension $WSL_EXT_ID)` open the cli.js file instead of using it to derive arguments (which I assume is the expected behavior). Nothing I've tried seems to be able to run code with any arguments except a file path, so I am guessing that the hanging occurs when code attempts to look up the extension without opening a CLI, but instead "opens" the cli.js file...without opening a CLI. & so it just sits there?

**Comment by easeev** [comment]
Same problem.

- Windows build 18950
- VSCode 1.36.1

These work while `code .` hangs:
- `$ cmd.exe /C "/mnt/c/Users/User/AppData/Local/Programs/Microsoft VS Code/bin/code.cmd"`
- `$ "/mnt/c/Users/User/AppData/Local/Programs/Microsoft VS Code/Code.exe"`

```
$ cat "/mnt/c/Users/User/AppData/Local/Programs/Microsoft VS Code/bin/code.cmd"                           *[master]  @echo off
setlocal
set VSCODE_DEV=
set ELECTRON_RUN_AS_NODE=1
"%~dp0..\Code.exe" "%~dp0..\resources\app\out\cli.js" %*
endlocal
```

**Comment by 8thHalfHour** [comment]
Same problem exists with `code-insiders .` from within WSL. Launches with this command perfectly from within CMD, and launching WSL Remote from within Code Insiders works perfectly, as well. However, absolutely nothing happens when I try it from within WSL.

**Comment by aldrinjunior** [comment]
I have this problem too
W10 insiders preview version 18950

**Comment by aeschli** [comment]
The problem is caused by an issue in WSL which is tracked here: https://github.com/microsoft/WSL/issues/4362.

According to https://github.com/microsoft/WSL/issues/4362#issuecomment-522151178, the fix is on the way.

In the meantime, workaround for using Remote - WSL is
- start VS Code out of Windows
- open a remote WSL window by either
  -  the `Open` command
  - the recent history
  - use `code .` in the integrated terminal.

**Comment by Alirezanet** [comment]
I have same issue in windows insider 18965 build and vscode 1.137.1. any updates ?

**Comment by meelos** [comment]
Also experiencing this problem. First time usings WSL.. Not a great first impression.

**Comment by aeschli** [comment]
The latest VSCode insiders build has a workaround so that `code-insiders .` works again for WSL2 on builds > 18947.
We still need a proper fix from WSL as there are other issues.
