### ISSUE TITLE
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#78184]
https://ticino-errors.azurewebsites.net/Errors?bucketIdHash=ddfe11a8-cfb4-b4d4-acf1-1cebc672b046

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
at t.e.dispose (\node_modules.asar\xterm\lib\xterm.js:1:12085) 
at \node_modules.asar\xterm\lib\xterm.js:1:127871 
at Array.forEach ()
at t.dispose (\node_modules.asar\xterm\lib\xterm.js:1:127842) 
at t.dispose (\node_modules.asar\xterm\lib\xterm.js:1:206182) 
at t.dispose (\node_modules.asar\xterm\lib\xterm.js:1:50539) 
at e.dispose (\node_modules.asar\xterm\lib\xterm.js:1:43516) 
/vs/workbench/contrib/terminal/browser/terminalInstance.ts#808:15 (dispose)
/vs/workbench/contrib/terminal/browser/terminalInstance.ts#1084:8 (_onProcessExit)
/vs/workbench/contrib/terminal/browser/terminalInstance.ts#975:54 (call)
/vs/base/common/event.ts#572:15 (fire)
/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts#293:22 (_onExit)
/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts#171:47 (call)
/vs/base/common/event.ts#572:15
at _processStartupComplete
```

**Comment by Tyriar** [comment]
Repro: create a terminal and kill it
