### ISSUE TITLE
TypeError: prevState.reset is not a function 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#78188]
https://ticino-errors.azurewebsites.net/Errors?bucketIdHash=dc3afd54-5b7f-8a57-e86f-02cb7c3840df

```
TypeError: prevState.reset is not a function
at Grammar._tokenize (\node_modules.asar\vscode-textmate\release\main.js:2574:23) 
at Grammar.tokenizeLine2 (\node_modules.asar\vscode-textmate\release\main.js:2550:22) 
/vs/workbench/services/textMate/browser/abstractTextMateService.ts#417:37 (tokenize2)
/vs/workbench/services/textMate/browser/abstractTextMateService.ts#390:22 (tokenize2)
/vs/editor/common/model/textModelTokens.ts#480:27 (safeTokenize)
/vs/editor/common/model/textModelTokens.ts#391:13 (_updateTokensUntilLine)
/vs/editor/common/model/textModelTokens.ts#374:7 (_tokenizeOneInvalidLine)
/vs/editor/common/model/textModelTokens.ts#313:36 (_revalidateTokensNow)
/vs/editor/common/model/textModelTokens.ts#297:9
```

**Comment by alexandrudima** [comment]
To check if this occurs with a build newer than Tuesday.

**Comment by alexandrudima** [comment]
Closing, trend going down...
