### ISSUE TITLE
Debug Console: Jump to line by clicking on stack trace (similar to Terminal Window)

### ISSUE THREAD

**Issue by bfelbo** [microsoft/vscode#78232]
In the VS Code terminal, one can click on an error stack trace and VS Code will open up the file at the right line. This is amazing for debugging. However, it doesn't seem to be supported in the terminal.

For instance, I would love to be able to click on `test/my_tests.js:306:30` in the stack trace below and go to that file.

```
  1 failing
base.js:383
  1) my_tests
       some test
         should do something:
     AssertionError: expected undefined to equal 1015
      at Proxy.assertEqual (node_modules/chai/lib/chai/core/assertions.js:1026:12)
      at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
      at Context.<anonymous> (test/my_tests.js:306:30)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/34026
