### ISSUE TITLE
Some file related variables don't resolve for integrated terminal with JSON file open

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#78247]
- VSCode Version: 1.37.0 Insiders
- OS Version: Windows 10

Found will testing https://github.com/microsoft/vscode/issues/78122

Steps to Reproduce:

Use:

```json
"terminal.integrated.shellArgs.windows": ["/K", "echo", "${file}"],
```
If you have a Markdown file, you will see the file variable echoed when the terminal is created.
If you open a JSON file, like settings.json, the terminal creation hangs on an empty terminal.

The DevTools output is:

  ERR '${file}' can not be resolved. Please open an editor.: Error: '${file}' can not be resolved. Please open an editor.
    at u (file:///C:/Users/gregvanl/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2853:268)
    at Proxy.evaluateSingleVariable (file:///C:/Users/gregvanl/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2854:533)
    at t.replace (file:///C:/Users/gregvanl/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2853:55)
    at String.replace (<anonymous>)
    at Proxy.resolveString (file:///C:/Users/gregvanl/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2853:10)
    at Proxy.recursiveResolve (file:///C:/Users/gregvanl/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2852:716)
    at Proxy.resolve (file:///C:/Users/gregvanl/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2851:851)
    at Object.t.getDefaultShellArgs (file:///C:/Users/gregvanl/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2782:338)
    at Proxy.getDefaultShellAndArgs (file:///C:/Users/gregvanl/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3549:615)
    at y.<anonymous> (file:///C:/Users/gregvanl/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3962:856)
    at Generator.next (<anonymous>)
    at file:///C:/Users/gregvanl/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///C:/Users/gregvanl/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:35:237)
    at y._launchProcess (file:///C:/Users/gregvanl/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3962:253)
    at y.<anonymous> (file:///C:/Users/gregvanl/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3961:221)
    at Generator.next (<anonymous>)
    at file:///C:/Users/gregvanl/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///C:/Users/gregvanl/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:35:237)
    at y.createProcess (file:///C:/Users/gregvanl/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3960:356)
    at setTimeout (file:///C:/Users/gregvanl/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3984:268)

Even worse: If you try to close one of the hung terminals, VS Code will hang and you'll get the Reopen/Wait/Close dialog.

**Comment by gregvanl** [comment]
This also repros for other file related variables such as:
${relativeFile}
${fileBasename}
${fileBasenameNoExtension}
${fileDirname}
${fileExtname}

**Comment by Tyriar** [comment]
The resolve call doesn't resolve files when it's the settings files for some reason.

**Comment by sandy081** [comment]
@isidorn I think this is related to configuration resolver

**Comment by isidorn** [comment]
Probably the [`getFilePath`](https://github.com/Microsoft/vscode/blob/1e3cc1a30d4fec3f4744e403e534f84c9b645217/src/vs/workbench/services/configurationResolver/browser/configurationResolverService.ts#L54) returns `undefined`  for the settings editor or something like that.
Forwarding to @alexr00 as she now owns the resolver service

Also this is not a regression, it always behaved like that for the settings files I believe

**Comment by alexr00** [comment]
Repros in Insiders, but not out of source...
