### ISSUE TITLE
Unhandled Rejection at: Promise

### ISSUE THREAD

**Issue by RahulTheVirus** [microsoft/vscode#78367]
Hi ,
I am compiling vscode letest insider build  on my arm device.
after lots of effort i have successfully compiled source.
but while building installer i am getting following errors 

```
node:17146) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead`

`Unhandled Rejection at: Promise Promise {
  _bitField: 152305664,
  _fulfillmentHandler0:
   { Error: spawn ENOMEM
       at ChildProcess.spawn (internal/child_process.js:366:11)
       at spawn (child_process.js:551:9)
       at Object.fork (child_process.js:113:10)
       at fork (/home/ubuntu/Downloads/vscode-dev/node_modules/worker-farm/lib/fork.js:17:36)
       at Farm.startChild (/home/ubuntu/Downloads/vscode-dev/node_modules/worker-farm/lib/farm.js:106:16)
       at Farm.processQueue (/home/ubuntu/Downloads/vscode-dev/node_modules/worker-farm/lib/farm.js:279:10)
       at Farm.addCall (/home/ubuntu/Downloads/vscode-dev/node_modules/worker-farm/lib/farm.js:307:8)
       at Farm.<anonymous> (/home/ubuntu/Downloads/vscode-dev/node_modules/worker-farm/lib/farm.js:38:10)
       at _class.boundWorkers (/home/ubuntu/Downloads/vscode-dev/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:71:24)
       at enqueue (/home/ubuntu/Downloads/vscode-dev/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:96:17)
       at bound (domain.js:402:14)
       at runBound (domain.js:415:12)
       at tryCatcher (/home/ubuntu/Downloads/vscode-dev/node_modules/bluebird/js/release/util.js:16:23)
       at Promise._settlePromiseFromHandler (/home/ubuntu/Downloads/vscode-dev/node_modules/bluebird/js/release/promise.js:512:31)
       at Promise._settlePromise (/home/ubuntu/Downloads/vscode-dev/node_modules/bluebird/js/release/promise.js:569:18)
       at Promise._settlePromise0 (/home/ubuntu/Downloads/vscode-dev/node_modules/bluebird/js/release/promise.js:614:10) errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' },
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined } reason: { Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:551:9)
    at Object.fork (child_process.js:113:10)
    at fork (/home/ubuntu/Downloads/vscode-dev/node_modules/worker-farm/lib/fork.js:17:36)
    at Farm.startChild (/home/ubuntu/Downloads/vscode-dev/node_modules/worker-farm/lib/farm.js:106:16)
    at Farm.processQueue (/home/ubuntu/Downloads/vscode-dev/node_modules/worker-farm/lib/farm.js:279:10)
    at Farm.addCall (/home/ubuntu/Downloads/vscode-dev/node_modules/worker-farm/lib/farm.js:307:8)
    at Farm.<anonymous> (/home/ubuntu/Downloads/vscode-dev/node_modules/worker-farm/lib/farm.js:38:10)
    at _class.boundWorkers (/home/ubuntu/Downloads/vscode-dev/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:71:24)
    at enqueue (/home/ubuntu/Downloads/vscode-dev/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:96:17)
    at bound (domain.js:402:14)
    at runBound (domain.js:415:12)
    at tryCatcher (/home/ubuntu/Downloads/vscode-dev/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/Downloads/vscode-dev/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/Downloads/vscode-dev/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/Downloads/vscode-dev/node_modules/bluebird/js/release/promise.js:614:10) errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' }
[08:54:23] The following tasks did not complete: vscode-linux-arm-min
[08:54:23] Did you forget to signal async completion?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I am not a pro developer , please help me to fix this.

- VSCode Version: Letest insider 1.37
- OS Version: Ubuntu 16.4 LTS ARM (TegraK1)

![Screenshot from 2019-08-02 12-41-12](https://user-images.githubusercontent.com/22678382/62352626-3c814400-b526-11e9-82ca-16c88fdfad39.png)

**Comment by joaomoreno** [comment]
ENOMEM means your machine does not have enough memory to build VS Code.
