### ISSUE TITLE
CSS smoketest failure

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#78385]
Occurs on Windows, and only happens when the whole smoketest suite is run. If you only run the CSS tests it passes. Looks like there is some bad test state happening. 

```
  1) Running Code
       CSS
         verifies that warning becomes an error once setting changed:
     Error: Timeout: is active element ' .monaco-editor[data-uri$="settings.json"] textarea' after 20 seconds.
      at D:\repos\Microsoft\vscode\test\smoke\out\vscode\code.js:163:23
      at Generator.next (<anonymous>)
      at fulfilled (out\vscode\code.js:8:58)
```

**Comment by sandy081** [comment]
Cannot repro this on my windows/mac. Lets take a look at this on your machine.

**Comment by sandy081** [comment]
This is fixed.
