### ISSUE TITLE
Miniconda3. ImportError: Unable to import required dependencies...

### ISSUE THREAD

**Issue by PavelD0770** [microsoft/vscode#78414]
When running the script in VS Code, an error is issued:

C:\Users\user>C:/Python/Miniconda3/envs/myenv/python.exe d:/Test/Test.py
Traceback (most recent call last):
File "d:/Test/Test.py", line 1, in <module>  import pandas
File "C:\Python\Miniconda3\envs\myenv\lib\site-ackages\pandas\__init__.py", line 17, in <module> "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies:
numpy: DLL load failed: The specified module was not found.

What am I doing.

1. Install Miniconda3
2. I create myenv virtual environment in Miniconda3
3. Download packages there: pandas, numpy, etc.
4. Launch VS Code (Microsoft's Python extension installed)
5. I create a Python script file with text (for example):
    import pandas
    print ('pass ..')
6. I select the virtual environment myenv and run the script on
    performance.
7. I observe the above error :(

Works from the console (miniconda), works from Visual Studio 2019, works from Pycharm too. From VS Code, it only works when changing to the virtual environment (venv) of Python 3.7, in which the packages from p. 3 are also installed. Those. the only problem is a bunch of VS Code and Miniconda3.

A similar problem with numpy, matplotlib, scipy. C, for example, sqlalchemy, requests and some other third-party packages are all OK.

Previously, VS code worked with the Miniconda3 virtual environment without any problems. Perhaps the problem appeared after installing and then uninstalling Anaconda Extension Pack.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.89GB (0.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ru|MS-|1.37.3
python|ms-|2019.6.24221
material-icon-theme|PKi|3.8.1

</details>
данные.

**Comment by PavelD0770** [comment]
> When running the script in VS Code, an error is issued:
> 
> C:\Users\user>C:/Python/Miniconda3/envs/myenv/python.exe d:/Test/Test.py
> Traceback (most recent call last):
> File "d:/Test/Test.py", line 1, in import pandas
> File "C:\Python\Miniconda3\envs\myenv\lib\site-ackages\pandas__init__.py", line 17, in "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
> ImportError: Unable to import required dependencies:
> numpy: DLL load failed: The specified module was not found.
> 
> What am I doing.
> 
> 1. Install Miniconda3
> 2. I create myenv virtual environment in Miniconda3
> 3. Download packages there: pandas, numpy, etc.
> 4. Launch VS Code (Microsoft's Python extension installed)
> 5. I create a Python script file with text (for example):
>    import pandas
>    print ('pass ..')
> 6. I select the virtual environment myenv and run the script on
>    performance.
> 7. I observe the above error :(
> 
> Works from the console (miniconda), works from Visual Studio 2019, works from Pycharm too. From VS Code, it only works when changing to the virtual environment (venv) of Python 3.7, in which the packages from p. 3 are also installed. Those. the only problem is a bunch of VS Code and Miniconda3.
> 
> A similar problem with numpy, matplotlib, scipy. C, for example, sqlalchemy, requests and some other third-party packages are all OK.
> 
> Previously, VS code worked with the Miniconda3 virtual environment without any problems. Perhaps the problem appeared after installing and then uninstalling Anaconda Extension Pack.
> 
> VS Code version: Code 1.36.1 ([2213894](https://github.com/microsoft/vscode/commit/2213894ea0415ee8c85c5eea0d0ff81ecc191529), 2019-07-08T22:59:35.033Z)
> OS version: Windows_NT x64 10.0.17134
> 
> System Info
> Extensions (3)
> данные.

**Comment by PavelD0770** [comment]
The problem is that when choosing a virtual conda environment, this environment is not activated. To fix the problem, you must manually execute activate myenv (myenv is the environment name) in the VS code terminal.

**Comment by PavelD0770** [comment]
Yes, specifying Path for conda is necessary. But in other IDEs it works without environment variables. Still, this is a problem with VS code or the Python extension package for Visual Studio Code
