### ISSUE TITLE
Miniconda3. ImportError: Unable to import required dependencies...

### ISSUE THREAD

**Issue by PavelD0770** [microsoft/vscode#78413]
Issue Type: <b>Bug</b>

При запуске скрипта в VS Code выдается ошибка: 

C:\Users\user>C:/Python/Miniconda3/envs/myenv/python.exe d:/Test/Test.py
Traceback (most recent call last):
File "d:/Test/Test.py", line 1, in <module>  import pandas
File "C:\Python\Miniconda3\envs\myenv\lib\site-ackages\pandas\__init__.py", line 17, in <module> "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies:
numpy: DLL load failed: Не найден указанный модуль.

Что я делаю.

1. Устанавливаю Miniconda3 
2. Создаю в Miniconda3  виртуальное окружение myenv
3. Загружаю туда пакеты: pandas, numpy, etc.
4. Запускаю VS Code (расширение Python от Microsoft установлено)
5. Создаю файл скрипта Python с текстом (например):
    import pandas
    print('pass..')
6. Выбираю виртуальное окружение myenv и запускаю скрипт на
    выполнение.
7. Наблюдаю вышеуказанную ошибку :(

Из консоли (miniconda) работает, из Visual Studio 2019 работает, из Pycharm тоже работает. Из VS Code работает только при смене на виртуальное окружение (venv) Python 3.7, в котором пакеты из п. 3 тоже установлены. Т.е. проблема только в связке VS Code и Miniconda3.

Аналогичная проблема с numpy, matplotlib, scipy. C, например, sqlalchemy, requests и некоторыми другими сторонними пакетами все Ок.

Раньше VS code работал с виртуальным окружением Miniconda3 без проблем. Возможно, проблема появилась после установки и последующего удаления Anaconda Extension Pack.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.89GB (0.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ru|MS-|1.37.3
python|ms-|2019.6.24221
material-icon-theme|PKi|3.8.1

</details>

**Comment by PavelD0770** [comment]
double #78414
