### ISSUE TITLE
search for extensions via command line

### ISSUE THREAD

**Issue by typekpb** [Microsoft/vscode#7842]
- VSCode Version: 1.2.1-1465908640
- OS Version: RHEL 7.2

I've noticed there is a way to manage extensions via cli: https://code.visualstudio.com/docs/editor/extension-gallery#_command-line-extension-management

One step I miss in the cli is however to search for extensions.
I'd love to have some command for that, possibly something like:

```
code --search-extensions <string>
```

where `<string>` could be substring in the extension name - as shown in the UI, or the explicit one, as used for installing via cli

**Comment by ergun1017** [comment]
Hey! I can pick this 😇

**Comment by pradeepmurugesan** [comment]
@joaomoreno  I would like to give it a try.. But how can I execute the cli from the local build. 

I compiled and tried out the following command

```
node out/cli.js --lsit-extensions
```

but I got an error 

```
Detail:  { Error: Cannot find module 'original-fs'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at NodeScriptLoader.load (/Users/pmurugesan/personal/microsoft/fork/vscode/out/vs/loader.js:732:39)
    at OnlyOnceScriptLoader.load (/Users/pmurugesan/personal/microsoft/fork/vscode/out/vs/loader.js:578:32)
    at loadNextPath (/Users/pmurugesan/personal/microsoft/fork/vscode/out/vs/loader.js:1426:41)
    at Object.errorback (/Users/pmurugesan/personal/microsoft/fork/vscode/out/vs/loader.js:1434:25)
    at OnlyOnceScriptLoader.triggerErrorback (/Users/pmurugesan/personal/microsoft/fork/vscode/out/vs/loader.js:591:36)
    at /Users/pmurugesan/personal/microsoft/fork/vscode/out/vs/loader.js:578:151 code: 'MODULE_NOT_FOUND' }
Error: Cannot find module 'original-fs'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at NodeScriptLoader.load (/Users/pmurugesan/personal/microsoft/fork/vscode/out/vs/loader.js:732:39)
    at OnlyOnceScriptLoader.load (/Users/pmurugesan/personal/microsoft/fork/vscode/out/vs/loader.js:578:32)
    at loadNextPath (/Users/pmurugesan/personal/microsoft/fork/vscode/out/vs/loader.js:1426:41)
    at Object.errorback (/Users/pmurugesan/personal/microsoft/fork/vscode/out/vs/loader.js:1434:25)
    at OnlyOnceScriptLoader.triggerErrorback (/Users/pmurugesan/personal/microsoft/fork/vscode/out/vs/loader.js:591:36)
    at /Users/pmurugesan/personal/microsoft/fork/vscode/out/vs/loader.js:578:151
```

I guess this may be is the lack of electron while executing the local cli. But not sure what will fix this. 

kindly help me here..

**Comment by sandy081** [comment]
@BuraChuhadar I suppose the request here is to search for extension from Marketplace and not only installed extensions.

@typekpb Can you please confirm? Also may i know what is the use case for the request?

**Comment by BuraChuhadar** [comment]
@sandy081 I am OK if we need to add search for extensions from Marketplace. I can add more detail in this implementation if you would like where it would say;

1- If an extension is installed, it would show as "installed" next to it
2- If an extension is from marketplace it can show as "not installed"

The code then would differentiate between installed and non-installed extensions and filter out from the Marketplace search.  Let me know your thoughts.

**Comment by sandy081** [comment]
Before going to implementation I would like to know the use case for this requirement.
