### ISSUE TITLE
keyboard layout loader: some tests are failing with ISO keyboard

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#78544]
On my setup (german layout, ISO keyboard), these tests are failing:

```
2 failing

  1) keyboard layout loader load default US keyboard layout:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Context.test (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/keybinding/test/browserKeyboardMapper.test.js:27:20)

  2) keyboard layout loader isKeyMappingActive:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true
      
      at Context.test (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/keybinding/test/browserKeyboardMapper.test.js:42:20)
```

**Comment by bpasero** [comment]
Pushed https://github.com/microsoft/vscode/commit/bb0e9fd5670ac52276d6682929a3bf8d52da0e4e to disable these tests.

**Comment by rebornix** [comment]
No longer test if the default chosen keyboard layout is U.S as it would fail locally when using ISO layouts.
