### ISSUE TITLE
VSCode 1.37.0 breaks matplotlib

### ISSUE THREAD

**Issue by benjaminpaik** [microsoft/vscode#78855]
After installing the 1.37.0 update, any python scripts that use matplotlib for graphing will no longer run in debug (I am using Anaconda3 with VSCode). I've pasted the resulting terminal output below. Reverting to VSCode 1.36.1 resolves the issue, and scripts run as expected.

- VSCode Version: 1.37.0
- OS Version: Windows 10 Version 1903 OS Build 18362.267

c:\Users\benja_000\Documents\Python Scripts>C:\ProgramData\Anaconda3\python.exe c:\Users\benja_000\.vscode\extensions\ms-python.python-2019.8.29288\pythonFiles\ptvsd_launcher.py --default --client --host localhost --port 54267 "c:\Users\benja_000\Documents\Python 
Scripts\Filter Response\main.py"
Traceback (most recent call last):
  File "c:\Users\benja_000\.vscode\extensions\ms-python.python-2019.8.29288\pythonFiles\ptvsd_launcher.py", line 43, in <module>    
    main(ptvsdArgs)
  File "c:\Users\benja_000\.vscode\extensions\ms-python.python-2019.8.29288\pythonFiles\lib\python\ptvsd\__main__.py", line 432, in 
main
    run()
  File "c:\Users\benja_000\.vscode\extensions\ms-python.python-2019.8.29288\pythonFiles\lib\python\ptvsd\__main__.py", line 316, in 
run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\benja_000\Documents\Python Scripts\Filter Response\main.py", line 7, in <module>
    from matplotlib import pyplot
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 138, in <module>
    from . import cbook, rcsetup
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 31, in <module>
    import numpy as np
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: The specified module could not be found.

c:\Users\benja_000\Documents\Python Scripts>C:/ProgramData/Anaconda3/Scripts/activate

(base) c:\Users\benja_000\Documents\Python Scripts>conda activate base

**Comment by octref** [comment]
Please report to https://github.com/microsoft/vscode-python first.
