### ISSUE TITLE
Explorer: Data tree node not found when adding root folder

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79007]
Steps to Reproduce:

1. running out of sources from master
2. ensure you have an empty workspace
3. open explorer viewlet
4. click File > Add Folder
5. add any folder

=> 🐛 console prints this

```
ERR Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
    at WorkbenchAsyncDataTree.getDataNode (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/asyncDataTree.js:432:23)
    at WorkbenchAsyncDataTree.<anonymous> (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/asyncDataTree.js:341:35)
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/asyncDataTree.js:7:58)
```

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/73469
