### ISSUE TITLE
July Release: Slow opening files, Extensions window not showing extensions

### ISSUE THREAD

**Issue by derekwallace** [microsoft/vscode#79187]
Windows 10.
Build 1.37.0

Hi,
Since updating to 1.37.0 i have noticed that vscode is behaving sluggish compared to what i am used to. I am using a project on a network drive from my PC. This has slow read/write access vs a local disk. I have had IT department check and the performance is consistent with its  normal behaviour. 

I have noticed 2 things in vscode.
1. opening files (small in size) is slow and the app can appear unresponsive for 1-2 secs.
2. the extensions window is not listing any extensions.
- the icon has a blue clock on it
- the top of the window has a blue line moving across it.

![image](https://user-images.githubusercontent.com/5574230/63079214-b60d2f00-bf35-11e9-9b8e-a27194c17fd8.png)

In console - output window the only message i see are these
[2019-08-15 08:11:29.127] [sharedprocess] [info] main {"machineId":"2e5351d6fe1c38aa501dc6f54345f98b4586d92f0da440ce7b747f8eca7e0124"}
[2019-08-15 08:12:09.149] [sharedprocess] [info] Starting to clean up unused language packs.

[2019-08-15 08:11:33.811] [exthost] [info] extension host started
[2019-08-15 08:11:33.901] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2019-08-15 08:11:33.901] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\derekw\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\debug-auto-launch\dist\extension
[2019-08-15 08:11:33.910] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2019-08-15 08:11:33.910] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\derekw\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\emmet\dist\extension
[2019-08-15 08:11:33.954] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2019-08-15 08:11:33.955] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\derekw\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main
[2019-08-15 08:11:34.026] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2019-08-15 08:11:34.026] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\derekw\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\merge-conflict\dist\extension
[2019-08-15 08:11:34.072] [exthost] [error] ProxyResolver#getCertificates (intermediate value) is not a function
[2019-08-15 08:11:34.237] [exthost] [info] eager extensions activated

**Comment by gjsjohnmurray** [comment]
Does it reproduce with all extensions disabled (`code --disable-extensions` or use the Reload Window With Extensions Disabled command)?

Are you behind a proxy? If so, perhaps related to #79115

**Comment by derekwallace** [comment]
yes i suspect its related.
when i work at home (not connected to work VPN, the extensions are loaded etc.)
If i close, connect to work, open vscode the issue occurs.

Ill disucss with my IT.
Thx.

**Comment by gjsjohnmurray** [comment]
Are you able to try it with the [Insiders build](https://code.visualstudio.com/insiders/)? This can be installed alongside the standard build.

**Comment by derekwallace** [comment]
yes i have insiders build and the behaviour is the same.
(i has a subset of extensions installed).

I removed the folder and re-opened vscode. same issue.
its therefore not caused by a specific extension.
C:\Users\derekw\.vscode\extensions

Is this issue caused by a change in vscode or a change in my pc configuration?

**Comment by gjsjohnmurray** [comment]
>     2. the extensions window is not listing any extensions.

@sandy081 could this aspect of the original report from @derekwallace be related to the other ones you have been investigating where people have had problems with the Extensions view after they upgraded to 1.37?

**Comment by derekwallace** [comment]
ive asked my IT and they dont believe there is any change to pc configuration.

Was there a change in 1.37 that could cause this?

**Comment by derekwallace** [comment]
i reverted to 1.36.1
1. Extensions activity still looks like this.
In tehe Output window i see same issue with ProxyResolver.

![image](https://user-images.githubusercontent.com/5574230/63171134-d4a52000-c032-11e9-9fc4-f5e13b32e655.png)

2. the extensions are actually loaded and working.
i can see the Python extension and other extensions working ok.

2. opening files is very very sluggish.

3. in Output window i see

[2019-08-16 14:24:16.877] [main] [info] update#setState idle
[2019-08-16 14:24:46.877] [main] [info] update#setState checking for updates
[2019-08-16 14:24:47.055] [main] [info] update#setState downloading
[2019-08-16 14:24:51.697] [main] [info] update#setState updating
[2019-08-16 14:24:51.710] [main] [error] [uncaught exception in main]: Error: spawn EBUSY
[2019-08-16 14:24:51.710] [main] [error] Error: spawn EBUSY
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at Object.spawn (child_process.js:543:9)
    at P.<anonymous> (C:\Users\derekw\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:476:4)
    at Generator.next (<anonymous>)
    at o (C:\Users\derekw\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:13:454)

[2019-08-16 14:24:33.650] [exthost] [info] extension host started
[2019-08-16 14:24:33.794] [exthost] [info] ExtensionService#_doActivateExtension vscode.python {"startup":false,"activationEvent":"onLanguage:python"}
[2019-08-16 14:24:33.794] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\derekw\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\python\out\pythonMain
[2019-08-16 14:24:33.803] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python {"startup":false,"activationEvent":"onLanguage:python"}
[2019-08-16 14:24:33.803] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\derekw\.vscode\extensions\ms-python.python-2019.8.30787\out\client\extension
[2019-08-16 14:24:35.415] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"activationEvent":"onLanguage:json"}
[2019-08-16 14:24:35.415] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\derekw\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\configuration-editing\dist\extension
[2019-08-16 14:24:35.440] [exthost] [info] ExtensionService#_doActivateExtension vscode.extension-editing {"startup":false,"activationEvent":"onLanguage:json"}
[2019-08-16 14:24:35.440] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\derekw\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\extension-editing\dist\extension
[2019-08-16 14:24:35.469] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"activationEvent":"onLanguage:json"}
[2019-08-16 14:24:35.469] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\derekw\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\client\dist\jsonMain
[2019-08-16 14:24:35.512] [exthost] [info] ExtensionService#_doActivateExtension vscode.npm {"startup":false,"activationEvent":"onLanguage:json"}
[2019-08-16 14:24:35.512] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\derekw\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\npm\dist\main
[2019-08-16 14:24:35.531] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"activationEvent":"onLanguage:typescript"}
[2019-08-16 14:24:35.531] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\derekw\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension
[2019-08-16 14:24:35.576] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2019-08-16 14:24:35.576] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\derekw\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\debug-auto-launch\dist\extension
[2019-08-16 14:24:35.585] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2019-08-16 14:24:35.585] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\derekw\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\emmet\dist\extension
[2019-08-16 14:24:35.596] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2019-08-16 14:24:35.596] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\derekw\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\main
[2019-08-16 14:24:35.657] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2019-08-16 14:24:35.657] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\derekw\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\merge-conflict\dist\extension
[2019-08-16 14:24:35.668] [exthost] [info] ExtensionService#_doActivateExtension CoenraadS.bracket-pair-colorizer-2 {"startup":true,"activationEvent":"*"}
[2019-08-16 14:24:35.668] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\derekw\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.0.28\out\src\extension
[2019-08-16 14:24:35.765] [exthost] [info] ExtensionService#_doActivateExtension kdcro101.favorites {"startup":true,"activationEvent":"*"}
[2019-08-16 14:24:35.765] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\derekw\.vscode\extensions\kdcro101.favorites-2.4.5\packed\
[2019-08-16 14:24:35.996] [exthost] [info] ExtensionService#_doActivateExtension peterfh.linesinfostatusbar {"startup":true,"activationEvent":"*"}
[2019-08-16 14:24:35.996] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\derekw\.vscode\extensions\peterfh.linesinfostatusbar-0.0.3\extension
[2019-08-16 14:24:36.007] [exthost] [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker {"startup":true,"activationEvent":"*"}
[2019-08-16 14:24:36.007] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\derekw\.vscode\extensions\streetsidesoftware.code-spell-checker-1.7.17\dist\extension
[2019-08-16 14:24:36.054] [exthost] [info] ExtensionService#_doActivateExtension vscode-icons-team.vscode-icons {"startup":true,"activationEvent":"*"}
[2019-08-16 14:24:36.054] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\derekw\.vscode\extensions\vscode-icons-team.vscode-icons-9.2.0\dist\src\vscode-icons.bundle.js
[2019-08-16 14:24:36.165] [exthost] [info] eager extensions activated
[2019-08-16 14:24:36.355] [exthost] [error] ProxyResolver#getCertificates (intermediate value) is not a function

**Comment by derekwallace** [comment]
What does this error mean? How can it be resolved?  what should i tell my IT team to resolve it?

ProxyResolver#getCertificates (intermediate value) is not a function

**Comment by derekwallace** [comment]
reopen. accidental closed.

**Comment by gjsjohnmurray** [comment]
Interesting to know that the extension-loading blue bar also happens in 1.36.1. If you think it used not to, perhaps that points to a change outside VSCode.

> 
> What does this error mean? How can it be resolved? what should i tell my IT team to resolve it?
> 
> ProxyResolver#getCertificates (intermediate value) is not a function

Do you also get that message with Insiders? #7044 fixed an issue that could be relevant.

**Comment by sandy081** [comment]
@gjsjohnmurray 

> @sandy081 could this aspect of the original report from @derekwallace be related to the other ones you have been investigating where people have had problems with the Extensions view after they upgraded to 1.37?

No, it does not look related. Others are mainly DNS specific and fixing the DNS fixed their issues.

**Comment by gjsjohnmurray** [comment]
@sandy081 

> No, it does not look related. Others are mainly DNS specific and fixing the DNS fixed their issues.

I'm wondering why so many of these issues seemed to appear when 1.37 shipped. Coincidence? Or does that version's Extensions feature access Marketplace in a different way that meant previously-working DNS settings had to be changed?

**Comment by sandy081** [comment]
No idea. Could be many. Change in Electron behaviour or something changed with the CDN or DNS configuration in the area of people reporting it. I asked those users to repro it with older version to see if this is a change in VS Code or not.

**Comment by derekwallace** [comment]
Some more tests.
1. install vscode 1.35.1
open vscode (no workpace)
- Extensions activity working fine
open workspace
- Extensions activity working fine.

2. install vscode 1.36.1
open vscode (no workpace)
- Extensions activity working fine
open workspace
- Extensions activity NOT working i.e. its not listing my extensions and i see the blue clock icon
- but the extensions are loaded and operational
- also if i type into the "Search Extensions in Marketplace" it WORKS i.e. if finds extensions

I still see this message
[2019-08-16 18:26:02.277] [exthost] [error] ProxyResolver#getCertificates (intermediate value) is not a function


3. install vscode 1.37.1 (behaviour looks same as 1.36.1)
open vscode (no workpace)
- Extensions activity working fine

open workspace
- Extensions activity NOT working i.e. its not listing my extensions and i see the blue clock icon
- but the extensions are loaded and operational
- also if i type into the "Search Extensions in Marketplace" it WORKS i.e. if finds extensions

4. reinstall vscode 1.35.1
working as described in 1.
HOWEVER i notice that the Python extension is disabled. this might be becuase i have the latest version of it and it might only work with newer version of vscode.....
I change Python extension to older version 2019.06.xxx
reopen vscode
The extension activity is ok and the python extension is ok.


5. reinstall vscode 1.36.1
still have python extension 2109.06.xxx
same behavour as described in 2

My conclusion is that nothing has probably change on my pc.
vscode 1.36.1 or 1.37.1 or the python extension might be at fault.

**Comment by derekwallace** [comment]
If im at home and i disconnect my vpn to work.
close vscode and open , everything is ok.
if i now connect to my vpn, vscode remains ok.

**Comment by derekwallace** [comment]
Using http://www.amibehindaproxy.com/
when im at home and disconnected from work there is no proxy server
when im at home and connecto to work there is no proxy server (ip and hostname change as routed through work)

The Extensions activiity allows me search marketplace and finds extensions.
If i select one hit install nothing happens. they dont install.

**Comment by gjsjohnmurray** [comment]
This is from a laptop that you use in the office and take home, right?

**Comment by derekwallace** [comment]
Correct .

**Comment by Gruntfuggly** [comment]
I'm currently seeing this but *only* in Insiders (1.38.0-insider). My standard install is fine?

**Comment by Gruntfuggly** [comment]
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:230 [Extension Host] ApplicationInsights:CorrelationIdManager Array(1) (at Function.e.warn (/usr/share/code-insiders/resources/app/extensions/json-language-features/client/dist/jsonMain.js:1:18444))
t.log @ /usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:230

**Comment by isidorn** [comment]
This issue has too much useless information.
Closing.
Users who still see this please open a new issue with **exact** reproducable steps. Thanks a lot
