### ISSUE TITLE
Totally broken after update

### ISSUE THREAD

**Issue by lasserewake** [microsoft/vscode#79490]
I updated visual studio code by clicking the popup notifier inside the program. It seemed to update ok but after update it wont start, wont update and wont reinstall properly. New version is 1.37.1.

Trying to start gives:
"(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) {

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:660:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:12)
    at startup (internal/bootstrap/node.js:282:19)"

Trying to uninstall gives: "The setup files are corrupted. Please obtain a new copy of the program."

Downloading and installing new version warns about existing version. If still proceeded, it installs visual studio code as a local user program and it works, however broken version remains and commandline is still hooked to broken version."

**Comment by officialpiyush** [comment]
Happens to me too

**Comment by joaomoreno** [comment]
@lasserewake @pocesar Please try to fully uninstall VS Code and reinstalling and wait for the next update.

**Comment by pocesar** [comment]
@joaomoreno I do that almost every other day. 

![image](https://user-images.githubusercontent.com/461084/64219329-6f0ebb80-ce9b-11e9-82fc-5a360cd312fd.png)

just tried to update again

**Comment by joaomoreno** [comment]
Have you tried disabling antivirus software while the update runs?

**Comment by pocesar** [comment]
@joaomoreno don't have AV installed, and Windows Defender realtime scanning is disabled
