### ISSUE TITLE
Can't remove keybinding from Keyboards Shortcuts editor

### ISSUE THREAD

**Issue by tomhanax** [microsoft/vscode#79493]
Issue Type: <b>Bug</b>

I successfully added a keyboard shortcut for "View: Split Editor Right". Now I want to remove it, but it does not work. I tried multiple ways - right click and Remove, Reset, also Del on keyboard, but nothing happens and shortcut is still there and works.

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 4.15.0-58-generic

**Comment by tomhanax** [comment]
After restarting VS Code the shortcut is gone, so it works only after restart, but this should not be needed, or user should be informed.

**Comment by sandy081** [comment]
@tomhanax Can you please open the `keybindings.json` file and see if remove/reset action in the Keybinings editor is removing the entry from the json file?

**Comment by tomhanax** [comment]
Yes, `keybindings.json` is immediately updated. I found that also assigning the key does not update list, but json file is updated. Seems like some GUI refreshing error...

**Comment by sandy081** [comment]
Looks like file events are not working. 
@bpasero May I know how to check if file events are triggered when a file changed?

**Comment by bpasero** [comment]
@sandy081 running with `--verbose` will print a log statement for each file event.

**Comment by sandy081** [comment]
@tomhanax Can you please run with `--verbose` or set log level to `trace` using `Set Log Level` command and see if the file events are triggered when `keybindings.json` file is changed?

**Comment by tomhanax** [comment]
If I enable --verbose mode, there are many lines, but they seem unrelated to problem - while editing keybindings, I do not see anything that looks like file events.

**Comment by sandy081** [comment]
You can do following:

- Set the log level to trace
- Open Window Output log `F1 > Open View > Window log`
- Clear the log
- Open Keybindings.json file and do edits
- Check in the logs for existence of `keybindings.json`

If possible provide us the logs

**Comment by sandy081** [comment]
I do not see any change events here after saving the file. Can you please do the same with following

- Use Json Editor
- Change Settings from UI and also from JSON Editor

Please provide us the logs.

**Comment by tomhanax** [comment]
I used JSON editor, then visual one. Settings from visual editor were applied into JSON editor, but still no visual feedback in visual editor. 

```
[2019-09-26 11:26:55.183] [renderer1] [trace] CommandService#executeCommand workbench.action.openGlobalKeybindings
[2019-09-26 11:26:55.306] [renderer1] [trace] [storage state.vscdb] updateItems(): insert(Map(1) {workbench.view.debug.state => {"workbench.debug.variablesView":{"collapsed":false,"isHidden":true,"size":378},"workbench.debug.watchExpressionsView":{"collapsed":false,"isHidden":true,"size":262},"workbench.debug.callStackView":{"collapsed":false,"isHidden":true,"size":284},"workbench.debug.breakPointsView":{"collapsed":false,"isHidden":true,"size":22}}}), delete(Set(0) {})
[2019-09-26 11:26:55.306] [renderer1] [trace] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[2019-09-26 11:26:55.309] [renderer1] [trace] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('workbench.view.debug.state','{"workbench.debug.variablesView":{"collapsed":false,"isHidden":true,"size":378},"workbench.debug.watchExpressionsView":{"collapsed":false,"isHidden":true,"size":262},"workbench.debug.callStackView":{"collapsed":false,"isHidden":true,"size":284},"workbench.debug.breakPointsView":{"collapsed":false,"isHidden":true,"size":22}}')
[2019-09-26 11:26:55.309] [renderer1] [trace] [storage state.vscdb] Trace (event): END TRANSACTION
[2019-09-26 11:27:04.412] [renderer1] [trace] CommandService#executeCommand workbench.action.openGlobalKeybindingsFile
[2019-09-26 11:27:04.448] [renderer1] [trace] load() - enter {"$mid":1,"external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:04.458] [renderer1] [trace] load() - resolved content {"$mid":1,"external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:04.459] [renderer1] [trace] load() - created text editor model {"$mid":1,"external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:04.459] [renderer1] [trace] onWillActivateByEvent:  onLanguage:jsonc
[2019-09-26 11:27:19.340] [renderer1] [trace] CommandService#executeCommand deleteRight
[2019-09-26 11:27:19.344] [renderer1] [trace] onModelContentChanged() - enter {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:19.344] [renderer1] [trace] onModelContentChanged() - new versionId 1 {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:19.344] [renderer1] [trace] onModelContentChanged() - model content changed and marked as dirty {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:19.344] [renderer1] [trace] doAutoSave() - enter for versionId 1 {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:29.346] [renderer1] [trace] doSave(1) - enter with versionId ' + versionId {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:29.369] [renderer1] [trace] doSave(1) - before write() {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:29.371] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/tomas/.config/Code/User/keybindings.json
[2019-09-26 11:27:29.372] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/tomas/.config/Code/User/keybindings.json
[2019-09-26 11:27:29.375] [renderer1] [trace] doSave(1) - after write() {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:29.375] [renderer1] [trace] doSave(1) - setting dirty to false because versionId did not change {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:29.572] [renderer1] [trace] [File Watcher (node.js)] >> normalized [CHANGED] /home/tomas/.config/Code/User/keybindings.json
[2019-09-26 11:27:29.575] [renderer1] [trace] load() - enter {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:35.752] [renderer1] [trace] CommandService#executeCommand workbench.action.files.save
[2019-09-26 11:27:35.755] [renderer1] [trace] save() - enter {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:35.755] [renderer1] [trace] doSave(1) - enter with versionId ' + versionId {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:35.760] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/tomas/.config/Code/User/keybindings.json
[2019-09-26 11:27:35.760] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/tomas/.config/Code/User/keybindings.json
[2019-09-26 11:27:35.961] [renderer1] [trace] [File Watcher (node.js)] >> normalized [CHANGED] /home/tomas/.config/Code/User/keybindings.json
[2019-09-26 11:27:35.962] [renderer1] [trace] load() - enter {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:37.773] [renderer1] [error] Cannot read property 'stack' of undefined: TypeError: Cannot read property 'stack' of undefined
	at t.onMessage.process.on.t.catch.t (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:783:954)
[2019-09-26 11:27:45.071] [renderer1] [trace] CommandService#executeCommand workbench.action.openGlobalKeybindings
[2019-09-26 11:27:58.116] [renderer1] [trace] onModelContentChanged() - enter {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:58.116] [renderer1] [trace] onModelContentChanged() - new versionId 2 {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:58.116] [renderer1] [trace] onModelContentChanged() - model content changed and marked as dirty {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:58.116] [renderer1] [trace] doAutoSave() - enter for versionId 2 {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:58.117] [renderer1] [trace] save() - enter {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:58.117] [renderer1] [trace] doSave(2) - enter with versionId ' + versionId {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:58.123] [renderer1] [trace] doSave(2) - before write() {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:58.128] [renderer1] [trace] doSave(2) - after write() {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:58.128] [renderer1] [trace] doSave(2) - setting dirty to false because versionId did not change {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:28:00.134] [renderer1] [error] Cannot read property 'stack' of undefined: TypeError: Cannot read property 'stack' of undefined
	at t.onMessage.process.on.t.catch.t (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:783:954)
[2019-09-26 11:28:03.745] [renderer1] [trace] load() - enter {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:28:22.073] [renderer1] [trace] CommandService#executeCommand editor.action.selectAll
```

**Comment by sandy081** [comment]
@tomhanax Weird!! I See the change event for `keybindings.json`. 

In the description you said it works when adding a keyboard shortcut for "View: Split Editor Right". It does not work only while removing the keybinding? 

Can you please open Keybindings UI and JSON editor side by side and perform following steps
1. Add keybinding
2. Remove keybinding

Can you please take a gif of above and provide it to us?

**Comment by tomhanax** [comment]
I have tested side by side scenario and find out, that when JSON editor (keybindings.json) is open, all GUI actions (add, remove, reset..) in visual editor are working - for example after assigning new keybinding visually, new entry is added in JSON editor and GUI is updated. Same for remove. However, when JSON editor is closed (not open), the bug is present - no GUI updates at all.

**Comment by sandy081** [comment]
@bpasero Looks like file watcher issue. Please let us know how to proceed

**Comment by bpasero** [comment]
@sandy081 running with `--verbose` will print file events to the console, so you can see if it is related or not.

**Comment by sandy081** [comment]
I think user has already ran it and here is the log

```
[2019-09-26 11:26:55.183] [renderer1] [trace] CommandService#executeCommand workbench.action.openGlobalKeybindings
[2019-09-26 11:26:55.306] [renderer1] [trace] [storage state.vscdb] updateItems(): insert(Map(1) {workbench.view.debug.state => {"workbench.debug.variablesView":{"collapsed":false,"isHidden":true,"size":378},"workbench.debug.watchExpressionsView":{"collapsed":false,"isHidden":true,"size":262},"workbench.debug.callStackView":{"collapsed":false,"isHidden":true,"size":284},"workbench.debug.breakPointsView":{"collapsed":false,"isHidden":true,"size":22}}}), delete(Set(0) {})
[2019-09-26 11:26:55.306] [renderer1] [trace] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[2019-09-26 11:26:55.309] [renderer1] [trace] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('workbench.view.debug.state','{"workbench.debug.variablesView":{"collapsed":false,"isHidden":true,"size":378},"workbench.debug.watchExpressionsView":{"collapsed":false,"isHidden":true,"size":262},"workbench.debug.callStackView":{"collapsed":false,"isHidden":true,"size":284},"workbench.debug.breakPointsView":{"collapsed":false,"isHidden":true,"size":22}}')
[2019-09-26 11:26:55.309] [renderer1] [trace] [storage state.vscdb] Trace (event): END TRANSACTION
[2019-09-26 11:27:04.412] [renderer1] [trace] CommandService#executeCommand workbench.action.openGlobalKeybindingsFile
[2019-09-26 11:27:04.448] [renderer1] [trace] load() - enter {"$mid":1,"external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:04.458] [renderer1] [trace] load() - resolved content {"$mid":1,"external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:04.459] [renderer1] [trace] load() - created text editor model {"$mid":1,"external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:04.459] [renderer1] [trace] onWillActivateByEvent:  onLanguage:jsonc
[2019-09-26 11:27:19.340] [renderer1] [trace] CommandService#executeCommand deleteRight
[2019-09-26 11:27:19.344] [renderer1] [trace] onModelContentChanged() - enter {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:19.344] [renderer1] [trace] onModelContentChanged() - new versionId 1 {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:19.344] [renderer1] [trace] onModelContentChanged() - model content changed and marked as dirty {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:19.344] [renderer1] [trace] doAutoSave() - enter for versionId 1 {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:29.346] [renderer1] [trace] doSave(1) - enter with versionId ' + versionId {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:29.369] [renderer1] [trace] doSave(1) - before write() {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:29.371] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/tomas/.config/Code/User/keybindings.json
[2019-09-26 11:27:29.372] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/tomas/.config/Code/User/keybindings.json
[2019-09-26 11:27:29.375] [renderer1] [trace] doSave(1) - after write() {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:29.375] [renderer1] [trace] doSave(1) - setting dirty to false because versionId did not change {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:29.572] [renderer1] [trace] [File Watcher (node.js)] >> normalized [CHANGED] /home/tomas/.config/Code/User/keybindings.json
[2019-09-26 11:27:29.575] [renderer1] [trace] load() - enter {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:35.752] [renderer1] [trace] CommandService#executeCommand workbench.action.files.save
[2019-09-26 11:27:35.755] [renderer1] [trace] save() - enter {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:35.755] [renderer1] [trace] doSave(1) - enter with versionId ' + versionId {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:35.760] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/tomas/.config/Code/User/keybindings.json
[2019-09-26 11:27:35.760] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/tomas/.config/Code/User/keybindings.json
[2019-09-26 11:27:35.961] [renderer1] [trace] [File Watcher (node.js)] >> normalized [CHANGED] /home/tomas/.config/Code/User/keybindings.json
[2019-09-26 11:27:35.962] [renderer1] [trace] load() - enter {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:37.773] [renderer1] [error] Cannot read property 'stack' of undefined: TypeError: Cannot read property 'stack' of undefined
	at t.onMessage.process.on.t.catch.t (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:783:954)
[2019-09-26 11:27:45.071] [renderer1] [trace] CommandService#executeCommand workbench.action.openGlobalKeybindings
[2019-09-26 11:27:58.116] [renderer1] [trace] onModelContentChanged() - enter {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:58.116] [renderer1] [trace] onModelContentChanged() - new versionId 2 {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:58.116] [renderer1] [trace] onModelContentChanged() - model content changed and marked as dirty {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:58.116] [renderer1] [trace] doAutoSave() - enter for versionId 2 {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:58.117] [renderer1] [trace] save() - enter {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:58.117] [renderer1] [trace] doSave(2) - enter with versionId ' + versionId {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:58.123] [renderer1] [trace] doSave(2) - before write() {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:58.128] [renderer1] [trace] doSave(2) - after write() {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:27:58.128] [renderer1] [trace] doSave(2) - setting dirty to false because versionId did not change {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:28:00.134] [renderer1] [error] Cannot read property 'stack' of undefined: TypeError: Cannot read property 'stack' of undefined
	at t.onMessage.process.on.t.catch.t (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:783:954)
[2019-09-26 11:28:03.745] [renderer1] [trace] load() - enter {"$mid":1,"fsPath":"/home/tomas/.config/Code/User/keybindings.json","external":"vscode-userdata:/home/tomas/.config/Code/User/keybindings.json","path":"/home/tomas/.config/Code/User/keybindings.json","scheme":"vscode-userdata"}
[2019-09-26 11:28:22.073] [renderer1] [trace] CommandService#executeCommand editor.action.selectAll
```

**Comment by bpasero** [comment]
Seems OK to me:

```
[2019-09-26 11:27:29.371] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/tomas/.config/Code/User/keybindings.json
[2019-09-26 11:27:29.372] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/tomas/.config/Code/User/keybindings.json
[2019-09-26 11:27:29.572] [renderer1] [trace] [File Watcher (node.js)] >> normalized [CHANGED] /home/tomas/.config/Code/User/keybindings.json
[2019-09-26 11:27:35.760] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/tomas/.config/Code/User/keybindings.json
[2019-09-26 11:27:35.760] [renderer1] [trace] [File Watcher (node.js)] [CHANGED] /home/tomas/.config/Code/User/keybindings.json
[2019-09-26 11:27:35.961] [renderer1] [trace] [File Watcher (node.js)] >> normalized [CHANGED] /home/tomas/.config/Code/User/keybindings.json
```

**Comment by sandy081** [comment]
@tomhanax I am puzzled here. I will try to include some patches and logs and provide you a build, can you please help us in reproducing then?

**Comment by tomhanax** [comment]
@sandy081 sure, why not. I am not an expert here but it seems to me that your focus is on file events, but original issue is not with JSON file editor, but with GUI editor not reacting to events and/or refreshing. IMHO you may consider focusing on GUI part of the problem. But as I said, I am no expert here, just have a developer hunch...

**Comment by sandy081** [comment]
I suspected file events because you said the keybinding does not work after adding/removing. So please correct me that when you added/removed a keybinding from UI editor (when JSON editor is not opened)

- Does the JSON file gets updated?
- And the added/removed keybinding works? I mean when you add keybinding, that specific keybinding works when you use it and same when you remove one.

**Comment by tomhanax** [comment]
Using GUI only, adding the keybiding does not work, however JSON file gets updated - I can see it at the end. The moment I re-save JSON file, the keybind starts to work. Same for keybinding removal.

**Comment by sandy081** [comment]
Here are the deb and rpm builds with some tracing enabled. 

[Linux x64 deb](https://az764295.vo.msecnd.net/insider/857a7fd697d879582c9ad728b4539967e74388e6/code-insiders_1.39.0-1570012688_amd64.deb)

[Linux x64 rpm](https://az764295.vo.msecnd.net/insider/857a7fd697d879582c9ad728b4539967e74388e6/code-insiders-1.39.0-1570012857.el7.x86_64.rpm)

Please use these (disable auto update) and try

- Open Keybindings UI
- Add/Remove a keybinding

And provide me with the window logs from `F1 > Open View > Log (Window)`

**Comment by tomhanax** [comment]
I tried provided deb in Virtualbox and it worked OK, so I suspected that maybe something is wrong with my specific version. So I tried same version on VM, also worked OK. So then I tried on my PC with new `--user-data-dir`, and voila - it worked OK. The problem is in my data-dir. I have `keybindings.json` symlinked to another location (which is synchronized to multiple PCs). When I make it regular file, it starts working OK.

So resume - since Code 1.37.1 the symlinked `keybindings.json` is not working as expected. I totally forgot about that symlinking I've made, sorry, now the issue seems much more clear, at least to me...

In the light of the latest facts - do you still need the logs from insiders, or you can now reproduce the issue?

**Comment by sandy081** [comment]
Yeah it would be still great to use the above builds and provide us the logs.
