### ISSUE TITLE
Cannot read property 'reprocess' of undefined

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#79809]
Issue Type: <b>Bug</b>

I see this at or right after startup when opening with a container:

[uncaught exception]: Error: Cannot read property 'reprocess' of undefined

TypeError: Cannot read property 'reprocess' of undefined
    at C.onDefaultConfigurationChanged (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4464:901)
    at C._register.g.Registry.as.onDidUpdateConfiguration.e (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4457:316)
    at d.fire (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:107:468)
    at h.registerConfigurations (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1569:768)
    at h.registerConfiguration (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1569:441)
    at y.getDefaultTerminalLinuxReady.then.e (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2744:716)

VS Code version: Code - Insiders 1.38.0-insider (185308c0dd317d73fe4c19dea347582dee9650de, 2019-08-26T09:44:57.483Z)
OS version: Linux x64 4.9.184-linuxkit
Remote OS version: Linux x64 4.9.184-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2193)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|1, 1, 0|
|Memory (System)|7.79GB (1.28GB free)|
|Process Argv|--extensionDevelopmentPath=/workspaces/vscode-remote-containers|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js & Mongo DB|
|OS|Linux x64 4.9.184-linuxkit|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2193)|
|Memory (System)|7.79GB (1.28GB free)|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.1
vscode-docker|ms-|0.7.0
remote-containers|ms-|0.69.0

</details>

**Comment by sandy081** [comment]
@chrmarti Is it happening while opening a MR workspace or a folder? Are there steps to repro?

**Comment by chrmarti** [comment]
It's on Linux with a single folder. I don't see it on Mac.

**Comment by sandy081** [comment]
Is it easy to repro on your machine? If so lets investigate on your machine?

**Comment by chrmarti** [comment]
Yes, please drop by.

**Comment by valeryan** [comment]
I get this when I use Remote - SSH to connect to my remote linux machine. 

[uncaught exception]: Error: Cannot read property 'reprocess' of undefined

TypeError: Cannot read property 'reprocess' of undefined
    at t.WorkspaceService.onDefaultConfigurationChanged (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4530:758)
    at _register.g.Registry.as.onDidUpdateConfiguration.e (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4523:207)
    at c.fire (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:116:519)
    at Object.registerConfigurations (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1590:520)
    at Object.registerConfiguration (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1590:193)
    at C.getDefaultTerminalLinuxReady.then.e (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2774:859)

Error: Cannot read property 'reprocess' of undefined

TypeError: Cannot read property 'reprocess' of undefined
    at t.WorkspaceService.onDefaultConfigurationChanged (configurationService.ts:498)
    at _register.g.Registry.as.onDidUpdateConfiguration.e (configurationService.ts:97)
    at c.fire (event.ts:580)
    at Object.registerConfigurations (configurationRegistry.ts:195)
    at Object.registerConfiguration (configurationRegistry.ts:182)
    at C.getDefaultTerminalLinuxReady.then.e (externalTerminalService.ts:369)
    at setTimeout (errors.ts:26)


I also get this error but I am not sure its related:

(node:15127) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by sandy081** [comment]
This is causing because of timing issue. In Remote scenario, it takes some time to load folder configuration mean while there are some core default configurations getting registered which is causing this. 

@chrmarti Since you were able to repro this, I would request you to verify this.
