### ISSUE TITLE
Smoke test fails due to locked log file

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#79868]
Testing https://github.com/microsoft/vscode/issues/79731

Happens both on Insider and Electron 6.x exploration build.

```
C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:313
        throw er
        ^

Error: EBUSY: resource busy or locked, unlink 'C:\Temp\t16168CupOofqCX7tN\d\logs\20190827T105055\exthost1\exthost.log'
    at Object.unlinkSync (fs.js:952:3)
    at rimrafSync (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:306:17)
    at C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:304:9)
    at C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:304:9)
    at C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:304:9)
    at C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:334:7)
    at fixWinEPERMSync (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:209:5)
    at rimrafSync (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:311:28)
    at C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:334:7)
    at Function.rimrafSync [as sync] (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\rimraf\rimraf.js:304:9)
    at process.once (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\out\main.js:46:35)
    at Object.onceWrapper (events.js:277:13)
    at process.emit (events.js:194:15)
    at process.exit (internal/process/per_thread.js:168:15)
    at mocha.run.failures (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\test\index.js:39:31)
    at done (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\mocha\lib\mocha.js:608:13)
    at Runner.<anonymous> (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\mocha\lib\runner.js:864:5)
    at Runner.emit (events.js:194:15)
    at C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\mocha\lib\runner.js:851:12
    at C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\mocha\lib\runner.js:690:9
    at C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\mocha\lib\runner.js:337:18
    at Hook.done [as callback] (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\mocha\lib\runnable.js:319:5)
    at Timeout.<anonymous> (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\smoke\node_modules\mocha\lib\runnable.js:251:10)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

@sandy081 assigning to you due to the fact that a log file is locked. Speedylog ?

**Comment by sandy081** [comment]
@dbaeumer Does it happens on normal build? If not lets get some insight from @deepak1556 / @bpasero what is happening differently with normal and exploration

**Comment by bpasero** [comment]
@sandy081 I think he said it happens also in insider:

> Happens both on Insider and Electron 6.x exploration build.

**Comment by sandy081** [comment]
Yeah missed it. Sorry.

**Comment by sandy081** [comment]
@dbaeumer I do not see this error in Mac / Windows. Can you help me in reproducing it.

**Comment by dbaeumer** [comment]
I was not able to reproduce using today's insider build and master. Closing for now.
