### ISSUE TITLE
Running Code Smoke Test fails

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#79866]
Testing https://github.com/microsoft/vscode/issues/79731

Happens both on Insiders and Electron 6.0 exploration build

```
 Running Code                                                                                                                                                                        
* Timeout!                                                                                                                                                                           
rror: Active element not found. Current active element is 'HTML > BODY.windows.file-icons-enabled.vs-dark.vscode-theme-defaults-themes-dark_plus-json > DIV.monaco-workbench.windows.
opanel > DIV.monaco-grid-view > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical > DIV.split-view-container > DIV.split-view-view.visible > DIV.monaco-grid-branch-node 
 DIV.monaco-split-view2.horizontal > DIV.split-view-container > DIV.split-view-view.visible > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical > DIV.split-view-containe
 > DIV.split-view-view.visible > DIV#workbench.parts.editor.part.editor.has-watermark > DIV.content > DIV.grid-view-container > DIV.monaco-grid-view > DIV.monaco-grid-branch-node > 
IV.monaco-split-view2.vertical.separator-border > DIV.split-view-container > DIV.split-view-view.visible > DIV.editor-group-container.active > DIV.editor-container > DIV.editor-inst
nce > DIV.monaco-scrollable-element > DIV'. Looking for .editor-instance[id="workbench.editor.walkThroughPart"] > div > div[tabIndex="0"]                                            
   at g.<anonymous> (file:///C:/Users/dirkb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1212:821)                     
   at Generator.next (<anonymous>)                                                                                                                                                   
   at file:///C:/Users/dirkb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:35:566                                       
   at new Promise (<anonymous>)                                                                                                                                                      
   at n (file:///C:/Users/dirkb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:35:343)                                   
   at g.isActiveElement (file:///C:/Users/dirkb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1212:513)                 
   at l.call (file:///C:/Users/dirkb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1217:653)                            
   at C.onPromise (file:///C:/Users/dirkb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:339:361)                        
   at C.onRawMessage (file:///C:/Users/dirkb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:338:1012)                    
   at C.protocolListener.protocol.onMessage.e (file:///C:/Users/dirkb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:338:
31)                                                                                                                                                                                  
   at d.fire (file:///C:/Users/dirkb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:107:468)                             
   at EventEmitter.n (file:///C:/Users/dirkb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:104:788)                     
   at EventEmitter.emit (events.js:182:13)                                                                                                                                           
   1) "before all" hook                                                                                                                                                              
   2) "after all" hook                                                                                                                                                               
```

**Comment by isidorn** [comment]
It seems like the smoke test is not updated to the new grid-view (looking at the errors). Thus forwarding this to @sbatten

**Comment by isidorn** [comment]
Dup of #79867
