### ISSUE TITLE
ERR Cannot read property 'minimumWidth' of undefined — on build from master

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#80027]
Issue Type: <b>Bug</b>

Using a build of VS Code from master (54c9d7f62c47221d48396085441c8ffa8cf4bea1), my user-data state seems to have become corrupted somehow. Now when I try to open VS Code, the editor area is blank and I see the error:

```
ERR Cannot read property 'minimumWidth' of undefined: TypeError: Cannot read property 'minimumWidth' of undefined
    at Workbench.getMaximumEditorDimensions (file:///Users/matb/projects/vscode/out/vs/workbench/browser/layout.js:446:129)
    at EditorPart.get minimumHeight [as minimumHeight] (file:///Users/matb/projects/vscode/out/vs/workbench/browser/parts/editor/editorPart.js:571:107)
    at WorkbenchLegacyLayout.computeMaxPanelHeight (file:///Users/matb/projects/vscode/out/vs/workbench/browser/legacyLayout.js:127:176)
    at WorkbenchLegacyLayout.layout (file:///Users/matb/projects/vscode/out/vs/workbench/browser/legacyLayout.js:325:41)
    at Workbench.layout (file:///Users/matb/projects/vscode/out/vs/workbench/browser/layout.js:650:40)
    at Workbench.<anonymous> (file:///Users/matb/projects/vscode/out/vs/workbench/browser/workbench.js:87:26)
    at Generator.next (<anonymous>)
    at file:///Users/matb/projects/vscode/out/vs/workbench/browser/workbench.js:10:71
    at new Promise (<anonymous>)
    at __awaiter (file:///Users/matb/projects/vscode/out/vs/workbench/browser/workbench.js:6:12)
    at instantiationService.invokeFunction (file:///Users/matb/projects/vscode/out/vs/workbench/browser/workbench.js:70:67)
    at InstantiationService.invokeFunction (file:///Users/matb/projects/vscode/out/vs/platform/instantiation/common/instantiationService.js:43:27)
    at Workbench.startup (file:///Users/matb/projects/vscode/out/vs/workbench/browser/workbench.js:70:38)
    at CodeRendererMain.<anonymous> (file:///Users/matb/projects/vscode/out/vs/workbench/electron-browser/desktop.main.js:71:56)
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/matb/projects/vscode/out/vs/workbench/electron-browser/desktop.main.js:7:58)
```

I don't have repo steps for this and am unsure what caused it or even if this is something you can hit in production. However it is really, really bad when this does happen so we should be 100% confident that no users will ever run into this

VS Code version: code-oss-dev 1.38.0 54c9d7f62c47221d48396085441c8ffa8cf4bea1
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.39GB free)|
|Process Argv|. --user-data-dir=./bla/|
|Screen Reader|no|
|VM|22%|
</details>

**Comment by mjbvz** [comment]
@sbatten Let me know what data from my user-data would be help you to investigate this. I worked around it by using a custom `--user-data-dir`

**Comment by mjbvz** [comment]
Actually this looks like a newly added function from 7324bc17026df4f5128b5648b484d0565d604e24?

**Comment by mjbvz** [comment]
@sbatten and I figured out this was due to having `"workbench.useExperimentalGridLayout": false` in my users setting. When using gridlayout, everything works fine. That's also why resetting the user data fixed the issue for me
