### ISSUE TITLE
Windows smoke test failure for VS Code 1.38

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#80127]
**Repo**
Using our release 1.38 branch for the smoke test code
Run smoketests against 1.37 and 1.38 insiders

**Bug**
```
*** Test data: C:\Users\matb\AppData\Local\Temp\t7364t5uPdXz0iPBp
*** Preparing smoketest setup...
*** Cloning test project repository...
*** Running yarn...
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
*** Smoketest setup done!

  Data Migration: This test MUST run before releasing by providing the --stable-build command line argument
** Timeout!
Error: Active element not found. Current active element is 'HTML > BODY.windows.file-icons-enabled.vs-dark.vscode-theme-defaults-themes-dark_plus-json > DIV.monaco-workbench.windows.nopanel > DIV#workbench.parts.sidebar.part.sidebar.left > DIV.content > DIV#workbench.view.explorer.composite.viewlet.explorer-viewlet > DIV.monaco-panel-view > DIV.monaco-split-view2.vertical > DIV.split-view-container > DIV.split-view-view.visible > DIV.panel > DIV.panel-body > DIV.explorer-folders-view.file-icon-themable-tree.show-file-icons.align-icons-and-twisties > DIV.monaco-list.list_id_2.mouse-support.selection-none'. Looking for .editor-instance[data-editor-id="workbench.editor.walkThroughPart"] > div > div[tabIndex="0"]
    at m.<anonymous> (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2292:924)
    at Generator.next (<anonymous>)
    at file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:35:237)
    at m.isActiveElement (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2292:616)
    at call (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1418:175)
    at C.onPromise (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:309:361)
    at C.onRawMessage (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:308:1012)
    at C.protocolListener.protocol.onMessage.e (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:308:531)
    at d.fire (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:81:67)
    at EventEmitter.n (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:78:404)
    at EventEmitter.emit (events.js:182:13)
    1) verifies opened editors are restored
** Timeout!
Error: Active element not found. Current active element is 'HTML > BODY.windows.file-icons-enabled.vs-dark.vscode-theme-defaults-themes-dark_plus-json > DIV.monaco-workbench.windows.nopanel > DIV#workbench.parts.editor.part.editor.has-watermark > DIV.content > DIV.grid-view-container > DIV.monaco-grid-view > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical.separator-border > DIV.split-view-container > DIV.split-view-view.visible > DIV.editor-group-container.active > DIV.editor-container > DIV#workbench.editor.walkThroughPart.editor-instance > DIV.monaco-scrollable-element > DIV'. Looking for .editor-instance[data-editor-id="workbench.editor.walkThroughPart"] > div > div[tabIndex="0"]
    at m.<anonymous> (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2292:924)
    at Generator.next (<anonymous>)
    at file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:35:460
    at new Promise (<anonymous>)
    at n (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:35:237)
    at m.isActiveElement (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2292:616)
    at call (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1418:175)
    at C.onPromise (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:309:361)
    at C.onRawMessage (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:308:1012)
    at C.protocolListener.protocol.onMessage.e (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:308:531)
    at d.fire (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:81:67)
    at EventEmitter.n (file:///C:/Users/matb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:78:404)
    at EventEmitter.emit (events.js:182:13)
    2) verifies that 'hot exit' works for dirty files
```

**Comment by sbatten** [comment]
this is caused by https://github.com/microsoft/vscode/commit/4994c7be4eddfbf5033c09eabf42c549258346b0

The smoke tests support this change https://github.com/microsoft/vscode/commit/fc4fd26b1293fca68ecf41f35b5933fb9ff91e63
 which is not in stable.
