### ISSUE TITLE
gulp crashes with  Could not find source file

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#80632]
Steps:

```
git checkout ec9acc5ccdf46762c3dcee0847e9bd93bdd67009
yarn run gulp watch-client
# wait for gulp to finish and in another terminal, run
git checkout 227e1a2fa06a31097d00ad5b8d663b72544e08d0
```

The gulp process terminates with:
```
[11:26:35] 'watch-client' errored after 1.6 min
[11:26:35] Error: Could not find source file: 'C:/Alex/src/vscode/src/vs/code/browser/workbench/web.main.ts'.
    at getValidSourceFile (C:\Alex\src\vscode\node_modules\typescript\lib\typescript.js:125593:29)
    at Object.getSemanticDiagnostics (C:\Alex\src\vscode\node_modules\typescript\lib\typescript.js:125809:36)
    at C:\Alex\src\vscode\node_modules\gulp-tsb\lib\builder.js:64:37
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Full gulp log:
[gulp-log.txt](https://github.com/microsoft/vscode/files/3594846/gulp-log.txt)

**Comment by jrieken** [comment]
Underlying issue is that we only use the files inferred from the project as compilation roots and that adding new files doesn't update that list.

**Comment by jrieken** [comment]
I have pushed an update to use gulp-tsb 4.0.2 and to also make the client compile start with the project sources.
