### ISSUE TITLE
unit tests pass on Ubuntu but fail pass but exit with 1

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#807]
Ubuntu 15.10, vscode@master

Running `./test/run.sh` passes all the unit tests and then fail integration tests with the following output:

```
~/workspaces/forks/vscode @master
$ ./test/run.sh 


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․

  1732 passing (3s)

[17:33:37] Using gulpfile ~/workspaces/forks/vscode/gulpfile.js
[17:33:37] Starting 'electron'...
[17:33:37] Finished 'electron' after 230 μs
[19463:1129/173337:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[19541:1129/173337:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[19463:1129/173339:INFO:CONSOLE(186)] "%c[Plugin Host] %cdebugger listening on port 5870", source: file:////home/daniel/workspaces/forks/vscode/out/vs/workbench/services/thread/electron-browser/threadService.js (186)
[19463:1129/173339:INFO:CONSOLE(129)] "Loading development extension at /home/daniel/workspaces/forks/vscode/extensions/vscode-api-tests", source: file:////home/daniel/workspaces/forks/vscode/out/vs/platform/plugins/common/nativePluginService.js (129)
Error: Cannot find module 'vscode/lib/testrunner'
Loading development extension at /home/daniel/workspaces/forks/vscode/extensions/vscode-api-tests
Overwriting extension /home/daniel/workspaces/forks/vscode/extensions/vscode-api-tests with /home/daniel/workspaces/forks/vscode/extensions/vscode-api-tests
WARNING: Promise with no error callback:2
{ exception: [Error: channel closed],
  error: null,
  promise: 
   { _creator: null,
     _nextState: null,
     _state: 
      { name: 'error',
        enter: [Function],
        cancel: [Function: _],
        done: null,
        then: null,
        _completed: [Function: _],
        _error: [Function: _],
        _notify: [Function: notifyError],
        _progress: [Function: _],
        _setCompleteValue: [Function: _],
        _setErrorValue: [Function: _] },
     _value: [Error: channel closed],
     _isException: true,
     _errorId: 2,
     done: [Function: ErrorPromise_done],
     then: [Function: ErrorPromise_then] },
  handler: undefined,
  id: 2,
  parent: undefined }
Error: channel closed
    at process.target.send (internal/child_process.js:509:16)
    at Object.Server._super.call.send (/home/daniel/workspaces/forks/vscode/out/vs/base/node/service.cp.js:16:53)
    at promise.then._this.protocol.send.id (/home/daniel/workspaces/forks/vscode/out/vs/base/common/service.js:94:36)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
    at WinJS.Class.define._run (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
    at WinJS.Class.define._error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1316:18)
    at error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1019:29)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
WARNING: Promise with no error callback:3
{ exception: [TypeError: Cannot read property 'split' of undefined],
  error: null,
  promise: 
   { _creator: null,
     _nextState: null,
     _state: 
      { name: 'error',
        enter: [Function],
        cancel: [Function: _],
        done: null,
        then: null,
        _completed: [Function: _],
        _error: [Function: _],
        _notify: [Function: notifyError],
        _progress: [Function: _],
        _setCompleteValue: [Function: _],
        _setErrorValue: [Function: _] },
     _value: [TypeError: Cannot read property 'split' of undefined],
     _isException: true,
     _errorId: 3,
     done: [Function: ErrorPromise_done],
     then: [Function: ErrorPromise_then] },
  handler: undefined,
  id: 3,
  parent: undefined }
TypeError: Cannot read property 'split' of undefined
    at promise.then._this.protocol.send.id (/home/daniel/workspaces/forks/vscode/out/vs/base/common/service.js:97:46)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
    at WinJS.Class.define._run (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
    at WinJS.Class.define._error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1316:18)
    at error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1019:29)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
    at WinJS.Class.define._run (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
    at WinJS.Class.define._error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1316:18)
WARNING: Promise with no error callback:undefined
[Error: Promise did not implement oncancel]
Uncaught Exception:  Error: channel closed

Error: channel closed
    at process.target.send (internal/child_process.js:509:16)
    at Object.Server._super.call.send (/home/daniel/workspaces/forks/vscode/out/vs/base/node/service.cp.js:16:53)
    at promise.then._this.protocol.send.id (/home/daniel/workspaces/forks/vscode/out/vs/base/common/service.js:94:36)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
    at WinJS.Class.define._run (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
    at WinJS.Class.define._error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1316:18)
    at error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1019:29)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
Error: channel closed

Error: channel closed
    at process.target.send (internal/child_process.js:509:16)
    at Object.Server._super.call.send (/home/daniel/workspaces/forks/vscode/out/vs/base/node/service.cp.js:16:53)
    at promise.then._this.protocol.send.id (/home/daniel/workspaces/forks/vscode/out/vs/base/common/service.js:94:36)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
    at WinJS.Class.define._run (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
    at WinJS.Class.define._error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1316:18)
    at error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1019:29)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
    at null._onTimeout (/home/daniel/workspaces/forks/vscode/out/vs/base/common/errors.js:14:31)
    at Timer.listOnTimeout (timers.js:89:15)
Uncaught Exception:  Error: Cannot read property 'split' of undefined

TypeError: Cannot read property 'split' of undefined
    at promise.then._this.protocol.send.id (/home/daniel/workspaces/forks/vscode/out/vs/base/common/service.js:97:46)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
    at WinJS.Class.define._run (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
    at WinJS.Class.define._error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1316:18)
    at error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1019:29)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
    at WinJS.Class.define._run (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
    at WinJS.Class.define._error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1316:18)
Error: Cannot read property 'split' of undefined

TypeError: Cannot read property 'split' of undefined
    at promise.then._this.protocol.send.id (/home/daniel/workspaces/forks/vscode/out/vs/base/common/service.js:97:46)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
    at WinJS.Class.define._run (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
    at WinJS.Class.define._error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1316:18)
    at error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1019:29)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
    at WinJS.Class.define._run (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
    at WinJS.Class.define._error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1316:18)
    at null._onTimeout (/home/daniel/workspaces/forks/vscode/out/vs/base/common/errors.js:14:31)
    at Timer.listOnTimeout (timers.js:89:15)
    at listOnTimeoutNT (timers.js:115:19)
    at doNTCallback1 (node.js:430:9)
    at Immediate._tickCallback [as _onImmediate] (node.js:352:17)
    at processImmediate [as _immediateCallback] (timers.js:374:17)

~/workspaces/forks/vscode @master
$ [19486:1129/173340:ERROR:gl_context_glx.cc(107)] Couldn't make context current with X drawable.
[19486:1129/173340:ERROR:gles2_cmd_decoder.cc(3502)]   GLES2DecoderImpl: Context lost during MakeCurrent.
[19486:1129/173340:WARNING:x11_util.cc(1472)] X error received: serial 174, error_code 171 (GLXBadDrawable), request_code 154, minor_code 26 (X_GLXMakeContextCurrent)
~/workspaces/forks/vscode @master
$ echo $?
1
```

**Comment by Tyriar** [comment]
This fails with the same error:

```bash
./scripts/code.sh \
  $(pwd)/extensions/vscode-api-tests/testWorkspace \
  --extensionDevelopmentPath=$(pwd)/extensions/vscode-api-tests \
  --extensionTestsPath=$(pwd)/extensions/vscode-api-tests/out
```

The tests pass after `npm install` is run in `extensions/vscode-api-tests`.

**Comment by Tyriar** [comment]
Figured this out, it was due to `./scripts/npm.sh` not running successfully initially. Installing deps in `./extensions/vscode-api-tests` is handled the `postinstall` script.
