### ISSUE TITLE
./test/run.sh passing output is noisy

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#808]
Ubuntu 15.10, vscode@master

Successful passing runs of `./test/run.sh` contain a lot of noisy output that look like failures, the output of vscode also continues after the script terminates and control is returned to the terminal:

```
~/workspaces/forks/vscode @master
$ ./test/run.sh 


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․

  1732 passing (3s)

[17:52:49] Using gulpfile ~/workspaces/forks/vscode/gulpfile.js
[17:52:49] Starting 'electron'...
[17:52:49] Finished 'electron' after 225 μs
[22381:1129/175249:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[22461:1129/175250:ERROR:renderer_main.cc(200)] Running without renderer sandbox
[22381:1129/175251:INFO:CONSOLE(186)] "%c[Plugin Host] %cdebugger listening on port 5870", source: file:////home/daniel/workspaces/forks/vscode/out/vs/workbench/services/thread/electron-browser/threadService.js (186)
[22381:1129/175251:INFO:CONSOLE(129)] "Loading development extension at /home/daniel/workspaces/forks/vscode/extensions/vscode-api-tests", source: file:////home/daniel/workspaces/forks/vscode/out/vs/platform/plugins/common/nativePluginService.js (129)
Loading development extension at /home/daniel/workspaces/forks/vscode/extensions/vscode-api-tests
Overwriting extension /home/daniel/workspaces/forks/vscode/extensions/vscode-api-tests with /home/daniel/workspaces/forks/vscode/extensions/vscode-api-tests


  editor tests
    ✓ make edit (241ms)

  window namespace tests
    ✓ active text editor (193ms)

  workspace-namespace
    ✓ textDocuments
    ✓ rootPath
    ✓ openTextDocument
    ✓ openTextDocument, illegal path
    ✓ events: onDidOpenTextDocument, onDidChangeTextDocument, onDidSaveTextDocument (57ms)
    ✓ findFiles (155ms)


  8 passing (723ms)

WARNING: Promise with no error callback:2
{ exception: [Error: channel closed],
  error: null,
  promise: 
   { _creator: null,
     _nextState: null,
     _state: 
      { name: 'error',
        enter: [Function],
        cancel: [Function: _],
        done: null,
        then: null,
        _completed: [Function: _],
        _error: [Function: _],
        _notify: [Function: notifyError],
        _progress: [Function: _],
        _setCompleteValue: [Function: _],
        _setErrorValue: [Function: _] },
     _value: [Error: channel closed],
     _isException: true,
     _errorId: 2,
     done: [Function: ErrorPromise_done],
     then: [Function: ErrorPromise_then] },
  handler: undefined,
  id: 2,
  parent: undefined }
Error: channel closed
    at process.target.send (internal/child_process.js:509:16)
    at Object.Server._super.call.send (/home/daniel/workspaces/forks/vscode/out/vs/base/node/service.cp.js:16:53)
    at promise.then._this.protocol.send.id (/home/daniel/workspaces/forks/vscode/out/vs/base/common/service.js:94:36)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
    at WinJS.Class.define._run (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
    at WinJS.Class.define._error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1316:18)
    at error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1019:29)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
Uncaught Exception:  Error: channel closed

Error: channel closed
    at process.target.send (internal/child_process.js:509:16)
    at Object.Server._super.call.send (/home/daniel/workspaces/forks/vscode/out/vs/base/node/service.cp.js:16:53)
    at promise.then._this.protocol.send.id (/home/daniel/workspaces/forks/vscode/out/vs/base/common/service.js:94:36)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
    at WinJS.Class.define._run (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
    at WinJS.Class.define._error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1316:18)
    at error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1019:29)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
Error: channel closed

Error: channel closed
    at process.target.send (internal/child_process.js:509:16)
    at Object.Server._super.call.send (/home/daniel/workspaces/forks/vscode/out/vs/base/node/service.cp.js:16:53)
    at promise.then._this.protocol.send.id (/home/daniel/workspaces/forks/vscode/out/vs/base/common/service.js:94:36)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
    at WinJS.Class.define._run (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1343:29)
    at WinJS.Class.define._error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1316:18)
    at error (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1019:29)
    at Object.notifyError [as _notify] (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1470:50)
    at Object.state_error_notify.enter (/home/daniel/workspaces/forks/vscode/out/vs/base/common/winjs.base.raw.js:1176:30)
    at null._onTimeout (/home/daniel/workspaces/forks/vscode/out/vs/base/common/errors.js:14:31)
    at Timer.listOnTimeout (timers.js:89:15)

~/workspaces/forks/vscode @master
$ [22405:1129/175253:ERROR:gl_context_glx.cc(107)] Couldn't make context current with X drawable.
[22405:1129/175253:ERROR:gles2_cmd_decoder.cc(3502)]   GLES2DecoderImpl: Context lost during MakeCurrent.
[22405:1129/175253:WARNING:x11_util.cc(1472)] X error received: serial 170, error_code 171 (GLXBadDrawable), request_code 154, minor_code 26 (X_GLXMakeContextCurrent)
```

**Comment by bpasero** [comment]
@joaomoreno the stacktrace at the end looks suspicious, maybe the service lib needs some protection against the parent being dead or not.

**Comment by bpasero** [comment]
Also seems to be a very recent issue, I did not see these last week.
