### ISSUE TITLE
'isExtensible' on proxy: trap result does not reflect extensibility of proxy target (which is 'true')

### ISSUE THREAD

**Issue by Ash258** [microsoft/vscode#80976]
Issue Type: <b>Bug</b>

I do not know if this should be reported here or after electron update there is requirement to change something in vscode-terminals repository.
Happens only in exploration and latest insider with electron 6.0.9, Works in previous insider and stable.

1. Install https://github.com/fabiospampinato/vscode-terminals/
1. Configure any terminal
	```json
	"terminals.terminals": [
		{
			"name": "Git Bash",
			"shellPath": "${env:SCOOP}\\apps\\git\\current\\bin\\bash.exe",
			"focus": true,
			"open": true,
		},
	],
	```
1. Invoke command `Run Single` from command pallet or shortcut
1. See error trace

<details>
<summary>Trace</summary>

```typescript
TypeError: 'isExtensible' on proxy: trap result does not reflect extensibility of proxy target (which is 'true')
	at Object.getExtension (c:\Users\Cabera.Jakub\.vscode-insiders\extensions\fabiospampinato.vscode-terminals-1.12.6\out\extension.js:9:72451)
	at Object.get (c:\Users\Cabera.Jakub\.vscode-insiders\extensions\fabiospampinato.vscode-terminals-1.12.6\out\extension.js:9:72979)
	at t.runTerminal (c:\Users\Cabera.Jakub\.vscode-insiders\extensions\fabiospampinato.vscode-terminals-1.12.6\out\extension.js:9:75835)
	at c:\Users\Cabera.Jakub\.vscode-insiders\extensions\fabiospampinato.vscode-terminals-1.12.6\out\extension.js:9:70363
	at v._executeContributedCommand (c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:578:927)
	at v.$executeContributedCommand (c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:579:295)
	at f._doInvokeHandler (c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:451:249)
	at f._invokeHandler (c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:450:964)
	at f._receiveRequest (c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:449:639)
	at f._receiveOneMessage (c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:448:468)
	at c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:446:691
	at l.fire (c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:49:893)
	at _.fire (c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:97)
	at c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:784:706
	at l.fire (c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:49:893)
	at _.fire (c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:97)
	at t.PersistentProtocol._receiveMessage (c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:185:451)
	at c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:635
	at l.fire (c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:49:893)
	at f.acceptChunk (c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:532)
	at c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:177:893
	at Socket.t (c:\SCOOP\apps\vscode-insiders\nightly-20190916\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:186:930)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

</details>

![A](https://i.imgur.com/HOkTWFx.gif)

VS Code version: Code - Insiders 1.39.0-insider (d157c2e941cae17acb79bf26a70bbfad732bdc83, 2019-09-16T06:06:10.647Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-5400K APU with Radeon(tm) HD Graphics    (2 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.46GB (2.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.28
vscode-markdownlint|Dav|0.30.2
gitlens|eam|9.9.3
EditorConfig|Edi|0.13.0
vsc-material-theme|Equ|30.0.0
vsc-material-theme-icons|equ|1.0.6
vscode-terminals|fab|1.12.6
vscode-pull-request-github|Git|0.11.1
todo-tree|Gru|0.0.153
intellij-idea-keybindings|k--|0.2.34
vscode-docker|ms-|0.8.1
remote-containers|ms-|0.76.0
powershell|ms-|2019.5.0
errorlens|Phi|1.1.3
vscode-yaml|red|0.5.3
code-settings-sync|Sha|3.4.2
shellcheck|tim|0.8.1
markdown-all-in-one|yzh|2.4.2

</details>

**Comment by aeschli** [comment]
If I get this right it is cause by this line:
`a.workspace.getConfiguration().get(n);return t.configPath||delete t.configPath`

Looks like a bug in the extension, configuration elements must not be modified.
