### ISSUE TITLE
require("Electron") is not working for extensions in latest Insiders

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#81075]
Version: 1.39.0-insider (system setup)
Commit: bdd1971f2cd9d08a8a90e02740f1850afe03da66
Date: 2019-09-17T06:02:08.670Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. In Live Share extension we use `download` npm module, which in turn uses `got` module.
2. This `got` module may use electron module if it is present. Their code is [here](https://github.com/sindresorhus/got/blob/5002e5445ca23a17439280739fd30d63cccd43d5/source/request-as-event-emitter.ts#L90).

In the latest insiders this fails to find `Electron` module:
```
Error: Cannot find module 'electron'
Require stack:
- c:\src\cascade1\vscode\extension\out\prod\extension-prod.js
- c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js
- c:\Program Files\Microsoft VS Code Insiders\resources\app\out\bootstrap-amd.js
- c:\Program Files\Microsoft VS Code Insiders\resources\app\out\bootstrap-fork.js
at Function._resolveFilename (internal/modules/cjs/loader.js:627:15)
at Function.<anonymous> (internal/modules/cjs/loader.js:531:27)
at Function.<anonymous> (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:785:714)
at Function.<anonymous> (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:753:961)
at Function._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:750:450)
at Module.require (internal/modules/cjs/loader.js:685:19)
at n (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\loader.js:15:524)
at Object.electron (c:\src\cascade1\vscode\extension\out\prod\extension-prod.js:145424:18)
at __webpack_require__ (c:\src\cascade1\vscode\extension\out\prod\extension-prod.js:21:30)
at get (c:\src\cascade1\vscode\extension\out\prod\extension-prod.js:57551:21)
at Immediate.<anonymous> (c:\src\cascade1\vscode\extension\out\prod\extension-prod.js:57630:3)
at processImmediate (internal/timers.js:439:21)"
```

Does this issue occur when all extensions are disabled?: No - it repros in our extension code.

**Comment by IlyaBiryukov** [comment]
Please let us know ASAP if you decide not to fix it. We'd need to configure `download` and `got` not to use electron then.

**Comment by IlyaBiryukov** [comment]
The user impact of not being able to `require("Electron")` in VSCode extensions is that downloading our dependencies won't work well with proxies. The benefits of using `require("Electron").net" over NodeJS `https` are described here: https://electronjs.org/docs/api/net

**Comment by IlyaBiryukov** [comment]
It looks like in the stable VSCode `process.versions.electron` is undefined, and in Insiders it is `'6.0.9'`. So in the stable VSCode `download` and `got` npm packages don't try to use `electron.net` module.

**Comment by bpasero** [comment]
It looks like this was an intentional change by Electron: https://github.com/electron/electron/pull/16450

@IlyaBiryukov if you could install a workaround on your end, that would be great. A NPM module should check for `process.versions.chrome` to figure out that it runs in Electron. 

![image](https://user-images.githubusercontent.com/900690/65214779-8b217800-daab-11e9-90f5-cdcca6b8d67d.png)

**Comment by IlyaBiryukov** [comment]
We just shipped Live Share with the workaround.
