### ISSUE TITLE
SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by elhaw** [microsoft/vscode#81220]
I am using nodemon to monitor changes in the code. But it shows in console the error below.

```
<!DOCTYPE html  >
^

SyntaxError: Unexpected token <
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```
**My environment**

  * Code Editor : visual studio code (1.38.1)
  * Node version : v10.16.3
  * NPM version : 6.9.0

After searching I Found that the interpreter was expecting js, but it received  HTML

**HTML**
```
<!DOCTYPE html  >
<html lang="en">
<head>
    <!-- <meta charset="UTF-8"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
       <h1>
        Hello, World
       </h1>
</body>
</html>
```

**Comment by kieferrm** [comment]
This sounds like a configuration issue on your side.
