### ISSUE TITLE
EINVAL: invalid argument, uv_pipe_open when starting code from WSL

### ISSUE THREAD

**Issue by offero** [microsoft/vscode#81290]
```
+ λ code-insiders .
net.js:282
    err = this._handle.open(fd);
                       ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:282:24)
    at createWritableStdioStream (internal/process/stdio.js:179:18)
    at process.getStderr [as stderr] (internal/process/stdio.js:40:14)
    at Object.get (internal/console/constructor.js:158:40)
    at Object.Console.<computed> (internal/console/constructor.js:276:46)
    at Object.warn (internal/console/constructor.js:287:61)
    at writeOut (internal/process/warning.js:27:3)
    at process.onWarning (internal/process/warning.js:79:3)
    at process.emit (events.js:205:15)
    at internal/process/warning.js:52:24
    at processTicksAndRejections (internal/process/task_queues.js:82:9) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'uv_pipe_open'
}

```

Version: 1.39.0-insider (user setup)
Commit: 8b6e0efc0a98639085fabeb5226a516785424796
Date: 2019-09-19T03:15:21.720Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. run `code-insiders .` in WSL 1. 

Does this issue occur when all extensions are disabled?: *Yes*

**Comment by offero** [comment]
I swear I did a search for this before submitting the issue...

**Comment by aeschli** [comment]
What distro do you use?
Do you still see a window opening? Is it a remote WSL window or a local window?

**Comment by aeschli** [comment]
It's a remote window? (Lower left corner shows WSL: Ubuntu)

**Comment by offero** [comment]
Yes but the same thing happens when I run it with the extensions disabled flag.

**Comment by aeschli** [comment]
> Yes but the same thing happens when I run it with the extensions disabled flag.

Are you suggesting it should not open a remote window if `--disable-extensions` is present? That would be a different issue.
