### ISSUE TITLE
Code insiders editor has been blurry 

### ISSUE THREAD

**Issue by thkrishn** [microsoft/vscode#81391]
[image](https://user-images.githubusercontent.com/7133450/65541809-d9c37d80-dec2-11e9-9bd7-8b8375b8c0e7.png)

I use both insiders and the release vs code ; insiders is visibly blurry 
vs code :
![image](https://user-images.githubusercontent.com/7133450/65542001-3757ca00-dec3-11e9-9dab-74b19ae336e8.png)

code Insiders:
![image](https://user-images.githubusercontent.com/7133450/65542047-4e96b780-dec3-11e9-85d8-9088c9e74199.png)

I am not sure if the difference is visible in the screen shots 

Steps to Reproduce:
1. Start up VS code insiders 
2. Editor is blurry 

So far I have tried 
1. https://stackoverflow.com/questions/29966747/how-can-i-disable-gpu-rendering-in-visual-studio-code
2. https://www.reddit.com/r/vscode/comments/9szgkp/visual_studio_code_blurry/
3. and disable rendering on my nvidia control panel 

nothing seems to work

**Comment by thkrishn** [comment]
It seems to be fixed int today's build; Text is back to normal 

![image](https://user-images.githubusercontent.com/7133450/65908040-674b1580-e37a-11e9-870c-2cafca4045cb.png)

**Comment by usernamehw** [comment]
Well, it's most likely fixed only temporary and will be back once electron version bumps to `6` https://github.com/microsoft/vscode/pull/81644

**Comment by bpasero** [comment]
@thkrishn 
I wonder if this issue is reproducible when running VSCode in a browser or bare Electron. For that purpose, can you please:
* `git clone https://github.com/bpasero/vscode-runner.git`
* `yarn`
* Web (Chrome only): `yarn web`
* Electron: `yarn electron`

And report back if you still reproduce the issue **in either or both web and Electron**?

**Comment by thkrishn** [comment]
I am running this in windows so after the clone yarn builds the software? 
If you have instruction about yarn... i would be happy to check it

**Comment by bpasero** [comment]
@thkrishn well, you do not really need to build a lot, this is a very small repository. In order to have yarn on the command line you need to:
* install `git` if not installed already (https://git-scm.com/)
* install `node.js` if not installed already (https://nodejs.org/en/download/)
* install `yarn` if not installed already (https://yarnpkg.com/lang/en/docs/install)

**Comment by thkrishn** [comment]
I tried installing `rimraf` still keeps throwing errors 

```
C:\Users\t.krishna\home\test_yarn_web\vscode-runner>npm install --force rimraf
npm WARN using --force I sure hope you know what you are doing.
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN
npm ERR! errno SELF_SIGNED_CERT_IN_CHAIN
npm ERR! request to https://registry.npmjs.org/rimraf failed, reason: self signed certificate in certificate chain

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\t.krishna\AppData\Roaming\npm-cache\_logs\2019-10-19T17_35_22_853Z-debug.log

C:\Users\t.krishna\home\test_yarn_web\vscode-runner>npm install --force fs-extra
npm WARN using --force I sure hope you know what you are doing.
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN
npm ERR! errno SELF_SIGNED_CERT_IN_CHAIN
npm ERR! request to https://registry.npmjs.org/fs-extra failed, reason: self signed certificate in certificate chain

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\t.krishna\AppData\Roaming\npm-cache\_logs\2019-10-19T17_35_45_241Z-debug.log

C:\Users\t.krishna\home\test_yarn_web\vscode-runner>yarn web
yarn run v1.19.1
warning package.json: No license field
warning ..\package.json: No license field
$ node web
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'rimraf'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\t.krishna\home\test_yarn_web\vscode-runner\lib\download.js:13:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bpasero** [comment]
@thkrishn to make things a bit easier, I am now hosting a version to try: https://vscode-runner-vscode-runner-azure.azurewebsites.net/

**Comment by thkrishn** [comment]
thanks @bpasero ; If I have to be really picky its still a little blurry 
But its not as bad when I opened this issue 

My base line comparison is with vscode; I don't see any blur.

**Comment by bpasero** [comment]
@alexandrudima is there a setting for the editor that could have an impact? I remember we had something to disable translate3d, but I am not sure we use that anymore.

**Comment by bpasero** [comment]
@thkrishn sorry can I ask you to try to reproduce again from `vscode-runner`, it would be great to know if you see this in bare Electron as well. What is the build problem you see when running `yarn`?

**Comment by thkrishn** [comment]
So i figured the build problems; The system I am using is behind a proxy 
after I fixed the build issues ... on `http://localhost:8080/` I just get a blank screen 

![image](https://user-images.githubusercontent.com/7133450/67248593-cfd95f80-f419-11e9-8cd6-92bbae5eab13.png)

**Comment by bpasero** [comment]
@thkrishn can you open the browser developer tools to see if something is printed to the console?

**Comment by alexandrudima** [comment]
@thkrishn Can you also please try `"editor.disableLayerHinting": true`

**Comment by thkrishn** [comment]
@alexandrudima  it says `Unknown Configuration Setting` its not highlighted

**Comment by alexandrudima** [comment]
Yeah, that is fine, it is a hidden setting. We have a bunch of editor settings which are not exposed in the JSON schema... So does `"editor.disableLayerHinting": true` improve things? (does it bring back subpixel antialising)?

**Comment by thkrishn** [comment]
@alexandrudima that looks like it improved the aliasing/blurring 
Looks back to normal

**Comment by alexandrudima** [comment]
Related -- https://github.com/microsoft/vscode/issues/75615

**Comment by Dean-NC** [comment]
@alexandrudima 
I started using VS Code for the 1st time earlier this year (on Windows), and I really disliked the font rendering, because it looked slightly blurry to me, like my eyes were out of focus. I just now ran across this editor.disableLayerHinting setting. For some reason I have to also set window.titleBarStyle = native, in order for disableLayerHinting to work, but turning off this layer hinting makes things noticeably easier for me to read. I'm glad I found it, and hope you leave it around and not get rid of it.

Looking very closely to the screen, I see that with layerHinting disabled text is a tiny bit jagged, and I can see why some people may not like it, but for me it's much better this way.
