### ISSUE TITLE
Failed to rename an identifier

### ISSUE THREAD

**Issue by n-romaniv** [microsoft/vscode#81665]
Issue Type: <b>Bug</b>

1. Create a new JS file.
2. Enter the following:
```javascript
function fn() { fn(); }
```
(it actually happens with a lot of identifiers, but this is just something I managed to reproduce it with).
3. Hit Rename (F2) on the function name.
Actual result:
The following error appears: 
```
TypeError: Cannot read property 'kind' of undefined
    at Object.isJSDocTag (tsserver.js:15372:21)
    at Object.isTagName (tsserver.js:98791:19)
    at walk (tsserver.js:126101:46)
    at visitNode (tsserver.js:17018:24)
    at Object.forEachChild (tsserver.js:17486:24)
    at walk (tsserver.js:126105:16)
    at visitNodes (tsserver.js:17027:30)
    at Object.forEachChild (tsserver.js:17442:24)
    at walk (tsserver.js:126109:24)
    at visitNode (tsserver.js:17018:24)
    at Object.forEachChild (tsserver.js:17256:21)
    at SourceFileObject.NodeObject.forEachChild (tsserver.js:124434:23)
    at initializeNameTable (tsserver.js:126100:20)
    at Object.getNameTable (tsserver.js:126093:13)
    at searchForName (tsserver.js:106052:24)
    at getReferencesInContainerOrFiles (tsserver.js:105829:25)
    at getReferencedSymbolsForSymbol (tsserver.js:105813:21)
    at Object.getReferencedSymbolsForNode (tsserver.js:105614:34)
    at Object.findReferencedSymbols (tsserver.js:105292:60)
    at Object.findReferences (tsserver.js:125608:41)
    at tsserver.js:133363:68
    at callbackProjectAndLocation (tsserver.js:133418:13)
    at tsserver.js:133391:24
    at forEachProjectInProjects (tsserver.js:133373:17)
    at combineProjectOutputWorker (tsserver.js:133388:13)
    at combineProjectOutputForReferences (tsserver.js:133344:13)
    at IOSession.Session.getReferences (tsserver.js:134444:34)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:133577:61)
    at tsserver.js:135178:88
    at IOSession.Session.executeWithRequestId (tsserver.js:135169:28)
    at IOSession.Session.executeCommand (tsserver.js:135178:33)
    at IOSession.Session.onMessage (tsserver.js:135201:35)
    at Interface.<anonymous> (tsserver.js:136516:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
	at Function.create (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:53:63463)
	at h.dispatchResponse (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:53:56618)
	at h.dispatchMessage (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:53:55516)
	at constructor._reader.onData.e (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:53:54992)
	at u.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:207)
	at t.Reader.onLengthData (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:53:61683)
	at Socket.t.Reader.constructor.e.on.e (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:53:61331)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```
Expected result:
No error shown and identifier renamed successfully.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 4.15.0-64-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2048)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|15.56GB (2.59GB free)|
|Process Argv|--disable-extensions /home/nazar.romaniv/Documents/nodal/nodal-platform/client|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by Tyriar** [comment]
I couldn't repro on Windows

**Comment by n-romaniv** [comment]
I also tried running this with [this](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) extension, and it still occurs for me.
This is an Ubuntu 18.04.

**Comment by mjbvz** [comment]
Same call stack as  https://github.com/microsoft/TypeScript/issues/33076

Doesn't repo for me using TypeScript@next or TypeScript 3.6, but please post a comment on that upstream issue if you have simple and reliable repo steps
