### ISSUE TITLE
Double click explorer sash now does not work when explorer has focus

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8180]
- VSCode Version: Code - Insiders 1.3.0-insider (41f53d27a8cb477130f84116c78f43ddacbaf24b, 2016-06-27T05:15:21.343Z)
- OS Version: Linux x64 4.4.0-24-generic Ubuntu 16.04

Steps to Reproduce:

1. Open a folder
2. Double click explorer sash

```
workbench.main.js:117 Cannot read property 'getOptimalWidth' of undefined: TypeError: Cannot read property 'getOptimalWidth' of undefined
    at t.getOptimalWidth (file:////usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:110:20908)
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:99:8276
    at r (file:////usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:37:23023)
    at t.e._emitToSpecificTypeListeners (file:////usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:37:25264)
    at t.e._emitEvents (file:////usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:37:25536)
    at t.e.emit (file:////usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:37:25906)
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:47:26436
    at file:////usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:45:20645
    at HTMLDivElement._wrapHandler (file:////usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:45:9363)
```

It works when a different viewlet is active.

**Comment by bpasero** [comment]
@isidorn reproduces when "Opened Editors" is hidden
