### ISSUE TITLE
TypeError: Cannot read property 'shutdown' of undefined

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81821]
From https://dev.azure.com/monacotools/Monaco/_build/results?buildId=59149&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=a83823bd-5dbd-5313-d0d6-a425f162cca0&l=1185

```
Cannot read property 'shutdown' of undefined: TypeError: Cannot read property 'shutdown' of undefined
	at y.$acceptProcessShutdown (/Users/vsts/agent/2.155.1/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:612:558)
	at f._doInvokeHandler (/Users/vsts/agent/2.155.1/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:636:275)
	at f._invokeHandler (/Users/vsts/agent/2.155.1/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:635:971)
	at f._receiveRequest (/Users/vsts/agent/2.155.1/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:634:639)
	at f._receiveOneMessage (/Users/vsts/agent/2.155.1/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:633:468)
	at _protocol.onMessage.e (/Users/vsts/agent/2.155.1/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:631:691)
	at l.fire (/Users/vsts/agent/2.155.1/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:519)
	at _.fire (/Users/vsts/agent/2.155.1/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:181:274)
	at e.onMessage.e (/Users/vsts/agent/2.155.1/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:788:104)
	at l.fire (/Users/vsts/agent/2.155.1/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:519)
	at _.fire (/Users/vsts/agent/2.155.1/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:181:274)
	at t.PersistentProtocol._receiveMessage (/Users/vsts/agent/2.155.1/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:185:629)
	at _socketDisposables.push._socketReader.onMessage.e (/Users/vsts/agent/2.155.1/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:182:824)
	at l.fire (/Users/vsts/agent/2.155.1/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:519)
	at f.acceptChunk (/Users/vsts/agent/2.155.1/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:178:588)
	at _register._socket.onData.e (/Users/vsts/agent/2.155.1/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:177:958)
	at Socket.t (/Users/vsts/agent/2.155.1/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:187:68)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

```

**Comment by bpasero** [comment]
Not sure if related, but there is also:


 ```
n.charCodeAt is not a function: TypeError: n.charCodeAt is not a function
   at e.onMessage.e (/Users/vsts/agent/2.155.1/work/1/vscode-reh-darwin/out/vs/server/remoteExtensionHostProcess.js:806:104)
    at l.fire (/Users/vsts/agent/2.155.1/work/1/vscode-reh-darwin/out/vs/server/remoteExtensionHostProcess.js:50:519)
    at _.fire (/Users/vsts/agent/2.155.1/work/1/vscode-reh-darwin/out/vs/server/remoteExtensionHostProcess.js:181:274)
    at t.PersistentProtocol._receiveMessage (/Users/vsts/agent/2.155.1/work/1/vscode-reh-darwin/out/vs/server/remoteExtensionHostProcess.js:185:629)
    at _socketDisposables.push._socketReader.onMessage.e (/Users/vsts/agent/2.155.1/work/1/vscode-reh-darwin/out/vs/server/remoteExtensionHostProcess.js:182:824)
    at l.fire (/Users/vsts/agent/2.155.1/work/1/vscode-reh-darwin/out/vs/server/remoteExtensionHostProcess.js:50:519)
    at p.acceptChunk (/Users/vsts/agent/2.155.1/work/1/vscode-reh-darwin/out/vs/server/remoteExtensionHostProcess.js:178:588)
    at _register._socket.onData.e (/Users/vsts/agent/2.155.1/work/1/vscode-reh-darwin/out/vs/server/remoteExtensionHostProcess.js:177:958)
    at Socket.t (/Users/vsts/agent/2.155.1/work/1/vscode-reh-darwin/out/vs/server/remoteExtensionHostProcess.js:187:68)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

```

**Comment by alexandrudima** [comment]
@bpasero Do you have source maps with those stack traces? The first one (found via the unique `$acceptProcessShutdown`) is:

https://github.com/microsoft/vscode/blob/e2f1ee3573513e3f8f849b8995efd68bf9e7640e/src/vs/workbench/api/common/extHostTerminalService.ts#L490-L492

I cannot comment about the second stacktrace since I cannot pinpoint `charCodeAt` / `fire`... @bpasero we would need to convert those stack traces and then based on the result assign someone from the team...

**Comment by Tyriar** [comment]
> n.charCodeAt is not a function: TypeError: n.charCodeAt is not a function

@alexandrudima I've been seeing this one on and off for months on web, I think it also showed up running the web smoke tests. Looks like a separate issue to the 'shutdown' one though.

**Comment by alexandrudima** [comment]
Does it reproduce when running the smoke test from source? Because then we could get a stack trace and identify the owner :).

**Comment by bpasero** [comment]
@alexandrudima the commit ID of that build seems to be `8eaec303ea9b12291540e729ad32b930169e67a4` and as such the sourcemap URI for workbench at least is: https://ticino.blob.core.windows.net/sourcemaps/8eaec303ea9b12291540e729ad32b930169e67a4/core/vs/workbench/workbench.desktop.main.js.map. I am not 100% sure about the URI for the extension host though, but probably similar.

**Comment by bpasero** [comment]
There you go: https://ticino.blob.core.windows.net/sourcemaps/8eaec303ea9b12291540e729ad32b930169e67a4/core/vs/workbench/services/extensions/node/extensionHostProcess.js.map

**Comment by alexandrudima** [comment]
Thanks for digging into that. Unfortunately the source map is not of good quality and cannot resolve the first stack element:

Deminified using https://github.com/alexandrudima/vscode-stack-beautifier

n.charCodeAt&nbsp;is&nbsp;not&nbsp;a&nbsp;function:&nbsp;TypeError:&nbsp;n.charCodeAt&nbsp;is&nbsp;not&nbsp;a&nbsp;function<br/>&nbsp;&nbsp;at&nbsp;<unknown><br/>&nbsp;&nbsp;at&nbsp;`call`&nbsp;([./common/event.ts:580:15](https://github.com/Microsoft/vscode/blob/8eaec303ea9b12291540e729ad32b930169e67a4/src/vs/./common/event.ts#L580))<br/>&nbsp;&nbsp;at&nbsp;`fire`&nbsp;([./parts/ipc/common/ipc.net.ts:453:18](https://github.com/Microsoft/vscode/blob/8eaec303ea9b12291540e729ad32b930169e67a4/src/vs/./parts/ipc/common/ipc.net.ts#L453))<br/>&nbsp;&nbsp;at&nbsp;`fire`&nbsp;([./parts/ipc/common/ipc.net.ts:733:20](https://github.com/Microsoft/vscode/blob/8eaec303ea9b12291540e729ad32b930169e67a4/src/vs/./parts/ipc/common/ipc.net.ts#L733))<br/>&nbsp;&nbsp;at&nbsp;`_receiveMessage`&nbsp;([./parts/ipc/common/ipc.net.ts:592:72](https://github.com/Microsoft/vscode/blob/8eaec303ea9b12291540e729ad32b930169e67a4/src/vs/./parts/ipc/common/ipc.net.ts#L592))<br/>&nbsp;&nbsp;at&nbsp;`call`&nbsp;([./common/event.ts:580:15](https://github.com/Microsoft/vscode/blob/8eaec303ea9b12291540e729ad32b930169e67a4/src/vs/./common/event.ts#L580))<br/>&nbsp;&nbsp;at&nbsp;`fire`&nbsp;([./parts/ipc/common/ipc.net.ts:239:20](https://github.com/Microsoft/vscode/blob/8eaec303ea9b12291540e729ad32b930169e67a4/src/vs/./parts/ipc/common/ipc.net.ts#L239))<br/>&nbsp;&nbsp;at&nbsp;`acceptChunk`&nbsp;([./parts/ipc/common/ipc.net.ts:200:50](https://github.com/Microsoft/vscode/blob/8eaec303ea9b12291540e729ad32b930169e67a4/src/vs/./parts/ipc/common/ipc.net.ts#L200))<br/>&nbsp;&nbsp;at&nbsp;`_listener`&nbsp;([./parts/ipc/node/ipc.net.ts:28:37](https://github.com/Microsoft/vscode/blob/8eaec303ea9b12291540e729ad32b930169e67a4/src/vs/./parts/ipc/node/ipc.net.ts#L28))<br/>

**Comment by Tyriar** [comment]
I suspect the charCodeAt thing is probably my problem actually, I'll action this issue soon.

**Comment by connor4312** [comment]
I see the original issue and linked issues were are flakey integration tests. @Tyriar are there any particular steps we can take to verify your fix?

**Comment by Tyriar** [comment]
@connor4312 probably can't repro it outside of the tests. I checked the build output for the PR and the message is gone, you can do a quick review of https://github.com/microsoft/vscode/pull/83788/files#diff-500e25740503223dd60ee4118d95d0a2, it should be impossible to get that error now because I'm using `?.`

**Comment by connor4312** [comment]
Yea, looks good to me, I'll mark as verified
