### ISSUE TITLE
Tests: ReferenceError: Proxy is not defined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8187]
For me on Mac using node.js v5.10.0 I see:

```
1) ExtHostLanguageFeatureCommands "before all" hook:
     ReferenceError: Proxy is not defined
      at TestThreadService.AbstractThreadService._createProxy (out/vs/workbench/services/thread/common/abstractThreadService.js:44:24)
      at TestThreadService.AbstractThreadService.get (out/vs/workbench/services/thread/common/abstractThreadService.js:27:53)
      at TestThreadService.get (out/vs/workbench/test/node/api/testThreadService.js:63:41)
      at new ExtHostModelService (out/vs/workbench/api/node/extHostDocuments.js:32:41)
      at Context.<anonymous> (out/vs/workbench/test/node/api/extHostApiCommands.test.js:45:111)

  2) ExtHostLanguageFeatures "before all" hook:
     ReferenceError: Proxy is not defined
      at TestThreadService.AbstractThreadService._createProxy (out/vs/workbench/services/thread/common/abstractThreadService.js:44:24)
      at TestThreadService.AbstractThreadService.get (out/vs/workbench/services/thread/common/abstractThreadService.js:27:53)
      at TestThreadService.get (out/vs/workbench/test/node/api/testThreadService.js:63:41)
      at new ExtHostModelService (out/vs/workbench/api/node/extHostDocuments.js:32:41)
      at Context.<anonymous> (out/vs/workbench/test/node/api/extHostLanguageFeatures.test.js:27:111)
```

**Comment by alexandrudima** [comment]
No longer an issue, since I removed the native proxies, but tests should IMHO be ran with `scripts\test.bat` that runs the tests with the same runtime we ship our product with.
