### ISSUE TITLE
Panel part layout error when double clicking sash to auto resize

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#82018]
Steps to Reproduce:

1. Start vscode with sidebar hidden
2. Open panel part
3. Double click panel part sash :bug:

```
  ERR Cannot read property 'height' of undefined: TypeError: Cannot read property 'height' of undefined
    at PanelPart.get preferredHeight [as preferredHeight] (file:///mnt/nvmefiles/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:67:37)
    at resizeToPreferredSize (file:///mnt/nvmefiles/vscode/out/vs/base/browser/ui/grid/grid.js:338:102)
    at SerializableGrid.onDidSashReset (file:///mnt/nvmefiles/vscode/out/vs/base/browser/ui/grid/grid.js:350:17)
    at Emitter.fire (file:///mnt/nvmefiles/vscode/out/vs/base/common/event.js:461:41)
    at Emitter.fire (file:///mnt/nvmefiles/vscode/out/vs/base/common/event.js:461:41)
    at e (file:///mnt/nvmefiles/vscode/out/vs/base/common/event.js:70:138)
    at Emitter.fire (file:///mnt/nvmefiles/vscode/out/vs/base/common/event.js:458:38)
    at i (file:///mnt/nvmefiles/vscode/out/vs/base/common/event.js:43:93)
    at Emitter.fire (file:///mnt/nvmefiles/vscode/out/vs/base/common/event.js:458:38)
    at e (file:///mnt/nvmefiles/vscode/out/vs/base/common/event.js:70:138)
    at Emitter.fire (file:///mnt/nvmefiles/vscode/out/vs/base/common/event.js:458:38)
    at i (file:///mnt/nvmefiles/vscode/out/vs/base/common/event.js:43:93)
    at Emitter.fire (file:///mnt/nvmefiles/vscode/out/vs/base/common/event.js:458:38)
    at Emitter.fire (file:///mnt/nvmefiles/vscode/out/vs/base/common/event.js:461:41)
    at i (file:///mnt/nvmefiles/vscode/out/vs/base/common/event.js:43:93)
    at Emitter.fire (file:///mnt/nvmefiles/vscode/out/vs/base/common/event.js:458:38)
    at sash.onDidReset (file:///mnt/nvmefiles/vscode/out/vs/base/browser/ui/splitview/splitview.js:484:42)
    at Emitter.fire (file:///mnt/nvmefiles/vscode/out/vs/base/common/event.js:458:38)
    at Sash.onMouseDoubleClick (file:///mnt/nvmefiles/vscode/out/vs/base/browser/ui/sash/sash.js:203:30)
    at Emitter.fire (file:///mnt/nvmefiles/vscode/out/vs/base/common/event.js:461:41)
    at HTMLDivElement.fn (file:///mnt/nvmefiles/vscode/out/vs/base/browser/event.js:9:35)
```

This check prevents the `dimension` to be initialized if the sidebar is not visible on startup which is needed to calculate the height for the panel
https://github.com/microsoft/vscode/blob/c617db19b08bfdae8e2c540470bf82dd405c3895/src/vs/workbench/browser/parts/sidebar/sidebarPart.ts#L192-L194

https://github.com/microsoft/vscode/blob/c617db19b08bfdae8e2c540470bf82dd405c3895/src/vs/workbench/browser/parts/panel/panelPart.ts#L62-L65

**Comment by bpasero** [comment]
@sbatten I would make this a candidate for fixing, does not reproduce in stable

**Comment by sbatten** [comment]
@bpasero I was able to reproduce in stable, be sure to enable gridlayout in stable if you have the option disabled for some reason.

Since this is not that serious and not a regression, will just fix this next iteration.
