### ISSUE TITLE
Definitions stop working after a while

### ISSUE THREAD

**Issue by MuTLY** [microsoft/vscode#82059]
Issue Type: <b>Bug</b>

Open VSCode, open a React file (JS or JSX), and on hovering a class or any other element on the code, a definition popup shows up correctly.

After a while (it can be minutes, or just by editing a file), it stops working and all it shows up on hovering is a small "Loading..." tooltip.

And I was able to grab this from the app's console:

`/C:/Users/MuTLY/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3579 [Extension Host] debugger listening on port 58674
log.ts:173   ERR <semantic> TypeScript Server Error (3.6.2)
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.find (tsserver.js:385:35)
    at getReferencedSymbolsForModuleIfDeclaredBySourceFile (tsserver.js:105629:78)
    at Object.getReferencedSymbolsForNode (tsserver.js:105607:40)
    at Object.getReferenceEntriesForNode (tsserver.js:105341:58)
    at getSemanticDocumentHighlights (tsserver.js:104031:57)
    at Object.getDocumentHighlights (tsserver.js:104019:20)
    at Object.getDocumentHighlights (tsserver.js:125577:42)
    at IOSession.Session.getDocumentHighlights (tsserver.js:134328:71)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:133752:61)
    at tsserver.js:135178:88
    at IOSession.Session.executeWithRequestId (tsserver.js:135169:28)
    at IOSession.Session.executeCommand (tsserver.js:135178:33)
    at IOSession.Session.onMessage (tsserver.js:135201:35)
    at Interface.<anonymous> (tsserver.js:136516:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17): Error: <semantic> TypeScript Server Error (3.6.2)
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.find (tsserver.js:385:35)
    at getReferencedSymbolsForModuleIfDeclaredBySourceFile (tsserver.js:105629:78)
    at Object.getReferencedSymbolsForNode (tsserver.js:105607:40)
    at Object.getReferenceEntriesForNode (tsserver.js:105341:58)
    at getSemanticDocumentHighlights (tsserver.js:104031:57)
    at Object.getDocumentHighlights (tsserver.js:104019:20)
    at Object.getDocumentHighlights (tsserver.js:125577:42)
    at IOSession.Session.getDocumentHighlights (tsserver.js:134328:71)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:133752:61)
    at tsserver.js:135178:88
    at IOSession.Session.executeWithRequestId (tsserver.js:135169:28)
    at IOSession.Session.executeCommand (tsserver.js:135178:33)
    at IOSession.Session.onMessage (tsserver.js:135201:35)
    at Interface.<anonymous> (tsserver.js:136516:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
	at Function.create (c:\Users\MuTLY\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:63463)
	at h.dispatchResponse (c:\Users\MuTLY\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:56618)
	at h.dispatchMessage (c:\Users\MuTLY\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:55516)
	at constructor._reader.onData.e (c:\Users\MuTLY\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:54992)
	at u.fire (c:\Users\MuTLY\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:207)
	at t.Reader.onLengthData (c:\Users\MuTLY\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:61683)
	at Socket.t.Reader.constructor.e.on.e (c:\Users\MuTLY\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:61331)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
`

I have to mention I already uninstalled and reinstalled VSCode a few times, even going thru the lengths of manually deleting folders and Registry keys as explained in several other issues here.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.5.0
subtle-brackets|raf|3.0.0
highlight-matching-tag|vin|0.9.5

</details>

**Comment by mjbvz** [comment]
Please try upgrading your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next).

Do you still see the issue after upgrading?

**Comment by MuTLY** [comment]
Hello @mjbvz - I'm going to try that and get back to you asap.

**Comment by MuTLY** [comment]
@mjbvz ,  after using the `typescript@next` for a while, the same issue happened.

This is the developer log:

`extensionHost.ts:295 [Extension Host] debugger listening on port 10353
console.ts:137 [Extension Host] (node:29573) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:137
console.ts:137 [Extension Host] TextEditor is closed/disposed
t.log @ console.ts:137
console.ts:137 [Extension Host] TextEditor is closed/disposed
t.log @ console.ts:137
console.ts:137 [Extension Host] TextEditor is closed/disposed
t.log @ console.ts:137
console.ts:137 [Extension Host] TextEditor is closed/disposed
t.log @ console.ts:137
log.ts:196   ERR <syntax> TypeScript Server Error (3.7.0-dev.20191009)
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.unescapeLeadingUnderscores (tsserver.js:14522:19)
    at tryGetName (tsserver.js:112613:27)
    at compareChildren (tsserver.js:112599:78)
    at Array.sort (native)
    at sortChildren (tsserver.js:112596:22)
    at endNode (tsserver.js:112179:17)
    at addNodeWithRecursiveChild (tsserver.js:112187:13)
    at addChildrenRecursively (tsserver.js:112268:25)
    at visitNodes (tsserver.js:17542:30)
    at Object.forEachChild (tsserver.js:17782:24)
    at addChildrenRecursively (tsserver.js:112413:24)
    at visitNode (tsserver.js:17533:24)
    at Object.forEachChild (tsserver.js:17780:21)
    at addChildrenRecursively (tsserver.js:112413:24)
    at visitNodes (tsserver.js:17542:30)
    at Object.forEachChild (tsserver.js:17773:24)
    at addChildrenRecursively (tsserver.js:112413:24)
    at visitNode (tsserver.js:17533:24)
    at Object.forEachChild (tsserver.js:17663:21)
    at addChildrenRecursively (tsserver.js:112264:28)
    at visitNodes (tsserver.js:17542:30)
    at Object.forEachChild (tsserver.js:17782:24)
    at addChildrenRecursively (tsserver.js:112413:24)
    at visitNode (tsserver.js:17533:24)
    at Object.forEachChild (tsserver.js:17780:21)
    at addChildrenRecursively (tsserver.js:112413:24)
    at rootNavigationBarNode (tsserver.js:112117:17)
    at Object.getNavigationTree (tsserver.js:112083:38)
    at Object.getNavigationTree (tsserver.js:130754:37)
    at IOSession.Session.getNavigationTree (tsserver.js:140231:44)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:139125:61)
    at tsserver.js:140562:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140553:28)
    at IOSession.Session.executeCommand (tsserver.js:140562:33)
    at IOSession.Session.onMessage (tsserver.js:140585:35)
    at Interface.<anonymous> (tsserver.js:141900:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17): Error: <syntax> TypeScript Server Error (3.7.0-dev.20191009)
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.unescapeLeadingUnderscores (tsserver.js:14522:19)
    at tryGetName (tsserver.js:112613:27)
    at compareChildren (tsserver.js:112599:78)
    at Array.sort (native)
    at sortChildren (tsserver.js:112596:22)
    at endNode (tsserver.js:112179:17)
    at addNodeWithRecursiveChild (tsserver.js:112187:13)
    at addChildrenRecursively (tsserver.js:112268:25)
    at visitNodes (tsserver.js:17542:30)
    at Object.forEachChild (tsserver.js:17782:24)
    at addChildrenRecursively (tsserver.js:112413:24)
    at visitNode (tsserver.js:17533:24)
    at Object.forEachChild (tsserver.js:17780:21)
    at addChildrenRecursively (tsserver.js:112413:24)
    at visitNodes (tsserver.js:17542:30)
    at Object.forEachChild (tsserver.js:17773:24)
    at addChildrenRecursively (tsserver.js:112413:24)
    at visitNode (tsserver.js:17533:24)
    at Object.forEachChild (tsserver.js:17663:21)
    at addChildrenRecursively (tsserver.js:112264:28)
    at visitNodes (tsserver.js:17542:30)
    at Object.forEachChild (tsserver.js:17782:24)
    at addChildrenRecursively (tsserver.js:112413:24)
    at visitNode (tsserver.js:17533:24)
    at Object.forEachChild (tsserver.js:17780:21)
    at addChildrenRecursively (tsserver.js:112413:24)
    at rootNavigationBarNode (tsserver.js:112117:17)
    at Object.getNavigationTree (tsserver.js:112083:38)
    at Object.getNavigationTree (tsserver.js:130754:37)
    at IOSession.Session.getNavigationTree (tsserver.js:140231:44)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:139125:61)
    at tsserver.js:140562:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140553:28)
    at IOSession.Session.executeCommand (tsserver.js:140562:33)
    at IOSession.Session.onMessage (tsserver.js:140585:35)
    at Interface.<anonymous> (tsserver.js:141900:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
	at Function.create (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:63415)
	at h.dispatchResponse (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:56570)
	at h.dispatchMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:55468)
	at constructor._reader.onData.e (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:54944)
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:519)
	at t.Reader.onLengthData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:61635)
	at Socket.t.Reader.constructor.e.on.e (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:61283)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
console.ts:137 [Extension Host] TextEditor is closed/disposed
t.log @ console.ts:137
console.ts:137 [Extension Host] TextEditor is closed/disposed
t.log @ console.ts:137
console.ts:137 [Extension Host] TextEditor is closed/disposed
t.log @ console.ts:137
console.ts:137 [Extension Host] TextEditor is closed/disposed
t.log @ console.ts:137
console.ts:137 [Extension Host] TextEditor is closed/disposed
t.log @ console.ts:137`

**Comment by mjbvz** [comment]
Does this happen in a specific file? Also can you check to see if when the error happens is tied to when you first see the loading indicator?

**Comment by MuTLY** [comment]
Happened again, but this time I didn't see anything in the VSC developer console.

Literally did this:

1. Opened a .JSX file, there was a component on it;
2. Right-clicked the component, selected "Go to definition";
3. The file with the definition (a .JS file with React code in it) opens up (non-editable, file name tab is in italics) - this file also has a React component on it, did not tried to follow its definition;
4. Proceeded to edit the JSX file - did not save it;
5. Switched back to the .JS file and on hovering the React component on it the "Loading..." tooltip keeps spinning without loading anything.

Console shows only this:

```
console.ts:137 [Extension Host] TextEditor is closed/disposed
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
_register._socket.onData.e @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
console.ts:137 [Extension Host] TextEditor is closed/disposed
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
_register._socket.onData.e @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
```

Is there any other way I can check logs besides the built-in Chromium Developer Tools?

**Comment by mjbvz** [comment]
To check the TS Server

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

**Comment by MuTLY** [comment]
Here's the log.
[ts.log](https://github.com/microsoft/vscode/files/3722671/ts.log)
