### ISSUE TITLE
Insiders fails to set default settings value for an array of strings after an extension is first installed

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#82073]
- VSCode Version: 1.39.0-insider
- OS Version: Windows

Steps to Reproduce:

1. Install the C/C++ extension.

Bug: Errors occur in the Toggle Developer Console window due to the fact that C_Cpp.commentContinationPatterns default value of [ "/**" ] isn't being used. The bug doesn't repro in the non-Insiders VS Code or after reloading the window. We can workaround this bug via checking for the undefined value and manually setting the default (but the root issue could cause other extensions to fail).

Our package.json is at 
https://github.com/microsoft/vscode-cpptools/blob/release/Extension/package.json

Activating extension 'ms-vscode.cpptools' failed: Cannot read property 'forEach' of undefined.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
@sean-mcmanus Can be add versions? What version of insiders and what version of the CPP extension? I have tried the extension from source and things work fine.

**Comment by sean-mcmanus** [comment]
I found out the bug only repros when the https://github.com/Microsoft/azure-pipelines-vscode extension is installed (and you also need a C/C++ folder open for our extension to fully activate). Should I file a bug with the Azure Pipeline extension? I don't know how they could break our extension in this manner.

**Comment by jrieken** [comment]
Ok, I have installed `azure-pipelines` (1.157.4) and I open Fib-sample folder that comes with the C/C++ extension. Everything works as expected, no errors. Can you setup a sample repo that reproduces this? Can you show the issue with things like stack traces and complete error log messages?

**Comment by jrieken** [comment]
I also still don't know what version of c/cpp this to try with?

**Comment by sean-mcmanus** [comment]
Yeah, I reproed it with the Fib sample, but you also need to have a .cpp file to fully activate our extension. The shipped 0.25.1 repros it. The workaround we added is to check for the missing default: https://github.com/microsoft/vscode-cpptools/pull/4398/files#diff-0109511e98085f7148e091ce0755806e .

The logs are:
```
[Extension Host] activating extension (at realActivation (c:\Users\user\.vscode-insiders\extensions\ms-vscode.cpptools-0.25.1\dist\main.js:6266:17))
console.ts:137 [Extension Host] starting language server (at realActivation (c:\Users\user\.vscode-insiders\extensions\ms-vscode.cpptools-0.25.1\dist\main.js:6279:13))
mainThreadExtensionService.ts:65 [[object Object]]Cannot read property 'forEach' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
_register._socket.onData.e @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'forEach' of undefined
	at getLanguageConfigFromPatterns (c:\Users\user\.vscode-insiders\extensions\ms-vscode.cpptools-0.25.1\dist\main.js:44796:14)
	at Object.getLanguageConfig (c:\Users\user\.vscode-insiders\extensions\ms-vscode.cpptools-0.25.1\dist\main.js:44786:12)
	at updateLanguageConfigurations (c:\Users\user\.vscode-insiders\extensions\ms-vscode.cpptools-0.25.1\dist\main.js:6310:97)
	at realActivation (c:\Users\user\.vscode-insiders\extensions\ms-vscode.cpptools-0.25.1\dist\main.js:6294:5)
	at onActivationEvent (c:\Users\user\.vscode-insiders\extensions\ms-vscode.cpptools-0.25.1\dist\main.js:6257:9)
	at onDidOpenTextDocument (c:\Users\user\.vscode-insiders\extensions\ms-vscode.cpptools-0.25.1\dist\main.js:6245:9)
	at l.fire (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:519)
	at t.ExtHostDocuments.constructor._documentsAndEditors.onDidAddDocuments.e (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:536:225)
	at l.fire (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:519)
	at f.$acceptDocumentsAndEditorsDelta (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:540:638)
	at p._doInvokeHandler (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:635:275)
	at p._invokeHandler (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:634:971)
	at p._receiveRequest (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:633:639)
	at p._receiveOneMessage (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:632:468)
	at define.constructor._protocol.onMessage.e (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:630:691)
	at l.fire (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:519)
	at _.fire (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:274)
	at define.constructor.e.onMessage.e (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:787:104)
	at l.fire (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:519)
	at _.fire (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:274)
	at t.PersistentProtocol._receiveMessage (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:185:629)
	at t.PersistentProtocol.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:824)
	at l.fire (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:519)
	at p.acceptChunk (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:588)
	at define.constructor._register._socket.onData.e (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:177:958)
	at Socket.t (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:187:68)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:66
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
_register._socket.onData.e @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94

```

**Comment by sandy081** [comment]
@sean-mcmanus Are you able to repro this still?  I do not see `C_Cpp.commentContinationPatterns` property in the linked `package.json`.

**Comment by sean-mcmanus** [comment]
Yeah, I repro it with VS Code 1.40.1 with the vsix at https://github.com/microsoft/vscode-cpptools/releases/download/0.25.1/cpptools-win32.vsix -- we added a workaround for the bug in the latest version of our extension.

I get a different error message with VS Code Insiders -- it says "Activating extension 'ms-vscode.cpptools' failed: vscode.window.showErrorMessage is not iterable (cannot read property Symbol(Symbol.iterator)).

**Comment by sandy081** [comment]
Assigning to November for investigation

**Comment by sandy081** [comment]
Tried to reproduce the issue with the above shared VSIX and I am not seeing any errors. 

@sean-mcmanus Can you please let us know if you still see the issue?

**Comment by sean-mcmanus** [comment]
Yeah, I don't see this issue anymore (5 years old).
