### ISSUE TITLE
"Initializing JS/TS language features" stuck on the status bar

### ISSUE THREAD

**Issue by PL47ER** [microsoft/vscode#82130]
Issue Type: <b>Bug</b>

Basically I recently started using VS Code from a week now. I am not sure why am I getting this error message. Looking at github Issues section, it confuses me more as there were different solutions provided or some reporters didn't provide more information and the issue was closed.

If more informatin is required, you have to guide me with step by step guide on how I can retrieve the information required to be able to resolve this issue.

Please help.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Are you opening a folder on a network drive?

**Comment by PL47ER** [comment]
Yes, I am opening files from network drive.

I am not sure what is intellisense. But I do open javascript files to edit from network drive. If you guide me on how to check with this intellisense then I can check and get back to you.

**Comment by mjbvz** [comment]
Yes we've had some issues with network drives in the past.

Can you please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by PL47ER** [comment]
Ok, following your lead.

Regarding providing you the log file, yes I can't post it in public, please provide alternate ways to send you the log file. Thanks.

**Comment by PL47ER** [comment]
I have got the error log. Please let me know how would you like to get it.

**Comment by PL47ER** [comment]
Just for time being, I am skipping the Info bits from the log, pasting error bits to at least give you some indication.

```
Err 146   [12:39:25.787] Exception on executing command unknown:

    Cannot read property 'length' of undefined

    TypeError: Cannot read property 'length' of undefined
        at createSourceFile (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17866:110)
        at Object.parseJsonText (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17699:26)
        at Object.parseJsonText (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17520:23)
        at ProjectService.loadConfiguredProject (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131789:33)
        at ProjectService.reloadConfiguredProject (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131916:22)
        at ConfiguredProject.updateGraph (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130304:45)
        at updateProjectIfDirty (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130666:45)
        at c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130887:25
        at Timeout.ThrottledOperations.run [as _onTimeout] (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:128185:17)
        at ontimeout (timers.js:427:13)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)

Err 150   [12:39:27.150] Exception on executing command unknown:

    Cannot read property 'length' of undefined

    TypeError: Cannot read property 'length' of undefined
        at createSourceFile (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17866:110)
        at Object.parseJsonText (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17699:26)
        at Object.parseJsonText (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17520:23)
        at ProjectService.loadConfiguredProject (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131789:33)
        at ProjectService.reloadConfiguredProject (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131916:22)
        at ConfiguredProject.updateGraph (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130304:45)
        at updateProjectIfDirty (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130666:45)
        at c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130887:25
        at Timeout.ThrottledOperations.run [as _onTimeout] (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:128185:17)
        at ontimeout (timers.js:427:13)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)

Err 208   [12:39:29.859] Exception on executing command unknown:

    Cannot read property 'length' of undefined

    TypeError: Cannot read property 'length' of undefined
        at createSourceFile (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17866:110)
        at Object.parseJsonText (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17699:26)
        at Object.parseJsonText (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17520:23)
        at ProjectService.loadConfiguredProject (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131789:33)
        at ProjectService.reloadConfiguredProject (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131916:22)
        at ConfiguredProject.updateGraph (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130304:45)
        at updateProjectIfDirty (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130666:45)
        at c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130887:25
        at Timeout.ThrottledOperations.run [as _onTimeout] (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:128185:17)
        at ontimeout (timers.js:427:13)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)

Err 212   [12:39:30.271] Exception on executing command unknown:

    Cannot read property 'length' of undefined

    TypeError: Cannot read property 'length' of undefined
        at createSourceFile (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17866:110)
        at Object.parseJsonText (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17699:26)
        at Object.parseJsonText (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17520:23)
        at ProjectService.loadConfiguredProject (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131789:33)
        at ProjectService.reloadConfiguredProject (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131916:22)
        at ConfiguredProject.updateGraph (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130304:45)
        at updateProjectIfDirty (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130666:45)
        at c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130887:25
        at Timeout.ThrottledOperations.run [as _onTimeout] (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:128185:17)
        at ontimeout (timers.js:427:13)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)

Err 279   [12:39:33.55] Exception on executing command unknown:

    Cannot read property 'length' of undefined

    TypeError: Cannot read property 'length' of undefined
        at createSourceFile (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17866:110)
        at Object.parseJsonText (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17699:26)
        at Object.parseJsonText (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17520:23)
        at ProjectService.loadConfiguredProject (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131789:33)
        at ProjectService.reloadConfiguredProject (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131916:22)
        at ConfiguredProject.updateGraph (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130304:45)
        at updateProjectIfDirty (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130666:45)
        at c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130887:25
        at Timeout.ThrottledOperations.run [as _onTimeout] (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:128185:17)
        at ontimeout (timers.js:427:13)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)

Err 283   [12:39:33.470] Exception on executing command unknown:

    Cannot read property 'length' of undefined

    TypeError: Cannot read property 'length' of undefined
        at createSourceFile (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17866:110)
        at Object.parseJsonText (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17699:26)
        at Object.parseJsonText (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17520:23)
        at ProjectService.loadConfiguredProject (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131789:33)
        at ProjectService.reloadConfiguredProject (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131916:22)
        at ConfiguredProject.updateGraph (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130304:45)
        at updateProjectIfDirty (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130666:45)
        at c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130887:25
        at Timeout.ThrottledOperations.run [as _onTimeout] (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:128185:17)
        at ontimeout (timers.js:427:13)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)

*
*
* and numerous times more till the end
*
*

Err 56604 [13:34:40.858] Exception on executing command unknown:

    Cannot read property 'length' of undefined

    TypeError: Cannot read property 'length' of undefined
        at createSourceFile (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17866:110)
        at Object.parseJsonText (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17699:26)
        at Object.parseJsonText (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:17520:23)
        at ProjectService.loadConfiguredProject (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131789:33)
        at ProjectService.reloadConfiguredProject (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131916:22)
        at ConfiguredProject.updateGraph (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130304:45)
        at updateProjectIfDirty (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130666:45)
        at c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130887:25
        at Timeout.ThrottledOperations.run [as _onTimeout] (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:128185:17)
        at ontimeout (timers.js:427:13)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)
```

**Comment by mjbvz** [comment]
Thanks for checking this. Those errors do look like they could be causing this behavior.

Can you please try upgrading your workspace to use the nightly version of typescript by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) Does this fix the issue for you?

Also, how is the network drive configured? Is it a mount? A unc path?

**Comment by PL47ER** [comment]
@mjbvz 

Sorry for the delay in response due to weekend.

I am using network drive with UNC path. Its not mounted drive. It is OneDrive for Business with internal domain url.

I have installed the extension today and enabled it for the workspace. I have then restarted the VS Code. None of the TypeScript commands were available until I load any .js file. That is when it loads the extension and starts giving me that error message in the status area.

So first I started loading .js file from my C drive and there were no errors in the status bar.

Then I tried loading .js file from network drive and the error comes back. Below are the error blocks.

```
Err 235   [12:52:36.761] Exception on executing command unknown:

    Cannot read property 'length' of undefined

    TypeError: Cannot read property 'length' of undefined
        at createSourceFile (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:18386:110)
        at Object.parseJsonText (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:18216:26)
        at Object.parseJsonText (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:18039:23)
        at ProjectService.loadConfiguredProject (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:137056:33)
        at ProjectService.reloadConfiguredProject (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:137188:22)
        at ConfiguredProject.updateGraph (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:135552:45)
        at updateProjectIfDirty (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:135920:45)
        at C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:136141:25
        at Timeout.ThrottledOperations.run [as _onTimeout] (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:133189:17)
        at ontimeout (timers.js:427:13)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)

Err 431   [12:52:49.982] Exception on executing command unknown:

    Cannot read property 'length' of undefined

    TypeError: Cannot read property 'length' of undefined
        at createSourceFile (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:18386:110)
        at Object.parseJsonText (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:18216:26)
        at Object.parseJsonText (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:18039:23)
        at ProjectService.loadConfiguredProject (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:137056:33)
        at ProjectService.reloadConfiguredProject (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:137188:22)
        at ConfiguredProject.updateGraph (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:135552:45)
        at updateProjectIfDirty (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:135920:45)
        at C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:136141:25
        at Timeout.ThrottledOperations.run [as _onTimeout] (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:133189:17)
        at ontimeout (timers.js:427:13)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)

Err 493   [12:52:53.161] Exception on executing command unknown:

    Cannot read property 'length' of undefined

    TypeError: Cannot read property 'length' of undefined
        at createSourceFile (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:18386:110)
        at Object.parseJsonText (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:18216:26)
        at Object.parseJsonText (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:18039:23)
        at ProjectService.loadConfiguredProject (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:137056:33)
        at ProjectService.reloadConfiguredProject (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:137188:22)
        at ConfiguredProject.updateGraph (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:135552:45)
        at updateProjectIfDirty (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:135920:45)
        at C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:136141:25
        at Timeout.ThrottledOperations.run [as _onTimeout] (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:133189:17)
        at ontimeout (timers.js:427:13)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)

Err 569   [12:52:56.254] Exception on executing command unknown:

    Cannot read property 'length' of undefined

    TypeError: Cannot read property 'length' of undefined
        at createSourceFile (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:18386:110)
        at Object.parseJsonText (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:18216:26)
        at Object.parseJsonText (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:18039:23)
        at ProjectService.loadConfiguredProject (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:137056:33)
        at ProjectService.reloadConfiguredProject (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:137188:22)
        at ConfiguredProject.updateGraph (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:135552:45)
        at updateProjectIfDirty (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:135920:45)
        at C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:136141:25
        at Timeout.ThrottledOperations.run [as _onTimeout] (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:133189:17)
        at ontimeout (timers.js:427:13)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)

Err 623   [12:52:59.120] Exception on executing command unknown:

    Cannot read property 'length' of undefined

    TypeError: Cannot read property 'length' of undefined
        at createSourceFile (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:18386:110)
        at Object.parseJsonText (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:18216:26)
        at Object.parseJsonText (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:18039:23)
        at ProjectService.loadConfiguredProject (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:137056:33)
        at ProjectService.reloadConfiguredProject (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:137188:22)
        at ConfiguredProject.updateGraph (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:135552:45)
        at updateProjectIfDirty (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:135920:45)
        at C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:136141:25
        at Timeout.ThrottledOperations.run [as _onTimeout] (C:\Users\xxx\.vscode\extensions\ms-vscode.vscode-typescript-next-3.7.20191013\node_modules\typescript\lib\tsserver.js:133189:17)
        at ontimeout (timers.js:427:13)
        at tryOnTimeout (timers.js:289:5)
        at listOnTimeout (timers.js:252:5)
        at Timer.processTimers (timers.js:212:10)
```

**Comment by PL47ER** [comment]
Just another update, I tried to map the drive with mount option as well and it still does same thing. So network drive type doesn't matter I guess, it is happening regardless.
