### ISSUE TITLE
Workspace symbol request should skip symbols without name

### ISSUE THREAD

**Issue by jvalkeal** [microsoft/vscode#82437]
While `name` is a mandatory field in a `SymbolInformation`, I think it would be nice if vscode would not fail if one of these symbols don't have a defined name. Currently workspace symbol request don't show anything if query results a set where `name` is not defined.

I opened an issue for [eclipse.jdt.ls/issues/1204](https://github.com/eclipse/eclipse.jdt.ls/issues/1204) where more detailed error output is shown for jdt server.

If we just follow specs then I think this error is expected but it is really super annoying as in a real world lsp server impls have bugs, bad behaviour and I'd prefer to show those 267 symbols to a user instead of just failing everything if one symbol from 268 don't have a name.

**Comment by jrieken** [comment]
It should not fail, items without label are filtered/dropped on the extension host, see https://github.com/microsoft/vscode/blob/db3dd377f0eeb361ba7d6a5f9b19e0e833b081d3/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L491-L494. What is the error that you are seeing here?

**Comment by jvalkeal** [comment]
Copied this from jdt issue:
```
[2019-10-09 15:02:52.826] [exthost] [error] [redhat.java] provider FAILED
[2019-10-09 15:02:52.826] [exthost] [error] Error: name must not be falsy
	at Function.validate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:361:366)
	at new b (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:361:315)
	at new b (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:350:44)
	at C (/home/jvalkealahti/.vscode/extensions/redhat.java-0.50.0/dist/extension.js:1:548818)
	at module.exports.t.createConverter.asSymbolInformations.e.map.e (/home/jvalkealahti/.vscode/extensions/redhat.java-0.50.0/dist/extension.js:1:553120)
	at Array.map (<anonymous>)
	at asSymbolInformations (/home/jvalkealahti/.vscode/extensions/redhat.java-0.50.0/dist/extension.js:1:553113)
	at i (/home/jvalkealahti/.vscode/extensions/vscjava.vscode-java-test-0.20.0/dist/extension.js:16:188376)
	at /home/jvalkealahti/.vscode/extensions/vscjava.vscode-java-test-0.20.0/dist/extension.js:16:188870
```

**Comment by jrieken** [comment]
Yeah, we can do nothing about that. The check I referred to earlier is in case extensions don't use our types/constructor. When they do however, the error is inside extension code and that's nothing we can catch or recover from (e.g the loop has already existed).
