### ISSUE TITLE
TFVC Source Control List / Tree Not visible After 1.39 Update

### ISSUE THREAD

**Issue by jfrahm1987** [microsoft/vscode#82585]
- VSCode Version: 1.39
- OS Version: Windows Server 2019

Steps to Reproduce:

1. Open Source control
2. No list or tree visible

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jfrahm1987** [comment]
![2019-10-15_08-07-54](https://user-images.githubusercontent.com/14897208/66834284-f895bc80-ef22-11e9-9890-47580bedcded.png)

**Comment by invokemethod** [comment]
i can confirm; im experiencing the same issue. here is the  stack trace of the  exception
`[2019-10-15 10:17:19.012] [renderer1] [error] Cannot set property 'resourceStates' of undefined: TypeError: Cannot set property 'resourceStates' of undefined
    at TfvcSCMProvider.onDidModelChange (/home/nuffsaid/.vscode/extensions/ms-vsts.team-1.149.2/out/src/tfvc/tfvcscmprovider.js:128:44)
    at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:539)
    at Model.<anonymous> (/home/nuffsaid/.vscode/extensions/ms-vsts.team-1.149.2/out/src/tfvc/scm/model.js:188:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/nuffsaid/.vscode/extensions/ms-vsts.team-1.149.2/out/src/tfvc/scm/model.js:8:58)
`

**Comment by joaomoreno** [comment]
Fix is out on 1.39.2.
