### ISSUE TITLE
Web: PHP syntax throws

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#82606]
From @fiveisprime

PHP files don't get syntax highlighting, throws the following error on open.

```sh
ERR 105,110,118,97,108,105,100,32,99,111,100,101,32,112,111,105,110,116,32,118,97,108,117,101: Error: 105,110,118,97,108,105,100,32,99,111,100,101,32,112,111,105,110,116,32,118,97,108,117,101
  at OnigScanner.findNextMatchSync (http://localhost:8000/node_modules/onigasm-umd/release/main.js:409:27)
  at matchRule (http://localhost:8000/node_modules/vscode-textmate/release/main.js:2723:33)
  at matchRuleOrInjections (http://localhost:8000/node_modules/vscode-textmate/release/main.js:2741:23)
  at scanNext (http://localhost:8000/node_modules/vscode-textmate/release/main.js:2834:17)
  at _tokenizeString (http://localhost:8000/node_modules/vscode-textmate/release/main.js:2827:9)
  at Grammar._tokenize (http://localhost:8000/node_modules/vscode-textmate/release/main.js:2580:25)
  at Grammar.tokenizeLine2 (http://localhost:8000/node_modules/vscode-textmate/release/main.js:2550:22)
  at k.tokenize2 (http://localhost:8000/out/vs/workbench/workbench.web.api.js:4216:304)
  at D.tokenize2 (http://localhost:8000/out/vs/workbench/workbench.web.api.js:4215:869)
  at h (http://localhost:8000/out/vs/workbench/workbench.web.api.js:1154:461)
```

**Comment by egamma** [comment]
This is the Intellisense extension https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense

Intellisense is still working. The error happens in 'onigasm'.

**Comment by LeuisKen** [comment]
I reported this bug last month, but you ignored. https://github.com/microsoft/vscode/issues/81168
It makes me upset to see that you only accept report from your own team.
