### ISSUE TITLE
CSS Smoke Test broken

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#82605]
Run the smoketest from source, via `yarn smoketest`
Notice that CSS tests are failing. I tried this multiple times and it always repros.

```
 1) Running Code
       CSS
         verifies warnings for the empty rule:
     Error: Timeout: get element 'div[id="workbench.panel.markers"] .monaco-tl-contents .marker-icon.severity-warning' after 20 seconds.
      at /Users/isidor/Development/vscode/test/automation/out/code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/isidor/Development/vscode/test/automation/out/code.js:8:58)

  2) Running Code
       CSS
         verifies that warning becomes an error once setting changed:
     Error: Timeout: get element 'div[id="workbench.panel.markers"] .monaco-tl-contents .marker-icon.severity-error' after 20 seconds.
      at /Users/isidor/Development/vscode/test/automation/out/code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/isidor/Development/vscode/test/automation/out/code.js:8:58)
```

**Comment by perceptron007** [comment]
@isidorn  Can you tell me how to run smoketest ?

**Comment by isidorn** [comment]
@perceptron007 https://github.com/Microsoft/vscode/blob/master/test/smoke/README.md

**Comment by octref** [comment]
Seems already fixed in latest dev.
