### ISSUE TITLE
UpdateOpen is called with same file name for close and open differing only in case

### ISSUE THREAD

**Issue by sheetalkamat** [microsoft/vscode#82634]
- VSCode Version:
- OS Version:
Version: 1.40.0-insider (user setup)
Commit: 3f6ed25939b8ef157a7a41e0dc43b517898d4005
Date: 2019-10-15T05:26:38.861Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:
Found as part of microsoft/TypeScript#25460
1. create a folder on case insensitive file system (eg windows)
2. add files
```ts
// Logger.ts
export class logger { }
```
```ts
//another.ts
import { logger } from "./Logger";
new logger();
```
```json
// tsconfig.json
{
  "compilerOptions": { "forceConsistentCasingInFileNames": true }
}
```
2. `code .` in the folder
3. Open Logger.ts and pin it in the editor
4. rename Logger.ts to logger.ts
5. Note in the tsserver log:  (there shouldn't be exception) Note the `UpdateOpen` command is applied in sequence as all open files, changedFiles and then closed files so one cannot open and close same file with different casing in their name in same command on case insensitive file system
```
Info 69   [10:30:18.128] request:
    {"seq":5,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":["c:/temp/est/Logger.ts"],"openFiles":[{"file":"c:/temp/est/logger.ts","fileContent":"export class logger {\r\n    \r\n}","scriptKindName":"TS","projectRootPath":"c:\\temp\\est"}]}}
Err 70    [10:30:18.153] Exception on executing command {"seq":5,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":["c:/temp/est/Logger.ts"],"openFiles":[{"file":"c:/temp/est/logger.ts","fileContent":"export class logger {\r\n    \r\n}","scriptKindName":"TS","projectRootPath":"c:\\temp\\est"}]}}:

    Debug Failure. False expression: Script should not exist and not be open already

    Error: Debug Failure. False expression: Script should not exist and not be open already
        at ProjectService.applyChangesInOpenFiles (c:\Typescript\built\local\tsserver.js:138090:34)
        at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Typescript\built\local\tsserver.js:138972:46)
        at c:\Typescript\built\local\tsserver.js:140630:88
        at IOSession.Session.executeWithRequestId (c:\Typescript\built\local\tsserver.js:140621:28)
        at IOSession.Session.executeCommand (c:\Typescript\built\local\tsserver.js:140630:33)
        at IOSession.Session.onMessage (c:\Typescript\built\local\tsserver.js:140653:35)
        at Interface.<anonymous> (c:\Typescript\built\local\tsserver.js:141968:27)
        at Interface.emit (events.js:182:13)
        at Interface._onLine (readline.js:290:10)
        at Interface._normalWrite (readline.js:433:12)
        at Socket.ondata (readline.js:149:10)
        at Socket.emit (events.js:182:13)
        at addChunk (_stream_readable.js:283:12)
        at readableAddChunk (_stream_readable.js:264:11)
        at Socket.Readable.push (_stream_readable.js:219:10)
        at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Good find and thanks for the repo steps. Should be fixed in tomorrow's insiders build

As a side note, we now automatically restart the ts server if there is a failure during `updateOpen`
