### ISSUE TITLE
why this through module failed

### ISSUE THREAD

**Issue by Dj-jom2x** [microsoft/vscode#82892]
```

    at Stream.<anonymous> (/root/vc2/bin/build/vscode-1.39.2-source/build/lib/reporter.js:74:29)
    at _end (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:65:9)
    at Stream.stream.end (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:74:5)
    at Stream.onend (internal/streams/legacy.js:42:10)
    at Stream.emit (events.js:203:15)
    at Stream.EventEmitter.emit (domain.js:466:23)
    at drain (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:34:23)
    at Stream.stream.queue.stream.push (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:45:5)
    at Stream.end (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:15:35)
    at _end (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:65:9)
error Command failed with exit code 1.
```

why this through module failed 

im trying to install vscode server im at where it builds the vscode it self freshly from here... and that 1 error is always there

**Comment by roblourens** [comment]
This doesn't look like the full error stack, can you paste the full thing?

**Comment by Dj-jom2x** [comment]
thats all i think heres the full log xD 

```
[build] Not running inside VS Code
[build] rootPath is "/root/vc2/code-server"
[build] outPath is "/root/vc2/bin"
[build] arch is "x86_64"
[build] target is "linux"
[build] vscodeVersion is "1.39.2"
[build] codeServerVersion is "1.39.3"
[build] Installing code-server dependencies...took 966ms
[build] Cloning VS Code...took 5258ms
[build] Installing VS Code dependencies...saazzzzaaatook 355900ms
[build] Building default extensions...ccgggtook 236572ms
[build] Patching VS Code...took 1920ms
[build] Copying code-server into VS Code...took 9559ms
[build] Building VS Code...asdhhfailed
Command failed: yarn gulp compile-build --max-old-space-size=32384
[14:50:11] 'compile-build' errored after 4.53 min
[14:50:11] Error: Found 1 errors
    at Stream.<anonymous> (/root/vc2/bin/build/vscode-1.39.2-source/build/lib/reporter.js:74:29)
    at _end (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:65:9)
    at Stream.stream.end (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:74:5)
    at Stream.onend (internal/streams/legacy.js:42:10)
    at Stream.emit (events.js:203:15)
    at Stream.EventEmitter.emit (domain.js:466:23)
    at drain (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:34:23)
    at Stream.stream.queue.stream.push (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:45:5)
    at Stream.end (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:15:35)
    at _end (/root/vc2/bin/build/vscode-1.39.2-source/node_modules/through/index.js:65:9)
error Command failed with exit code 1.

```

**Comment by roblourens** [comment]
I see you say you are trying to build the server, that won't be possible because not all of the components are open source.
