### ISSUE TITLE
TreeError [MarkersPanel] Tree element not found: [object Object]

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#83040]
I believe this was expected to be fixed by #71126, however that fixed is included in the current stable release and it still happens (FYI @sandy081 - the bot locked the existing issue, and I couldn't find another tracking this).

I still see this lots - most noticeably in my CI runs it just fills the logs. This one is using the current insiders build:

```
TreeError [MarkersPanel] Tree element not found: [object Object]: Error: TreeError [MarkersPanel] Tree element not found: [object Object]
    at t.ObjectTreeModel.getElementLocation (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:136:14)
    at t.ObjectTreeModel.isCollapsed (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:135:250)
    at W.isCollapsed (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1037:72)
    at z.revealMarkersForCurrentActiveEditor (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5863:628)
    at z.autoReveal (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5863:485)
    at z.onActiveEditorChanged (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5860:776)
    at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5859:754
    at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:114:709
    at c.fire (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:118:286)
    at e.doEmitActiveEditorChangeEvent (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4862:364)
    at e.handleActiveEditorChange (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4862:160)
    at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4862:474
    at c.fire (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:118:286)
    at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5508:875
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async e.openEditor (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5507:750)
    at async e.doOpenEditor (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4864:479)
    at async e.$tryShowTextDocument (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3484:517)
```

https://travis-ci.org/Dart-Code/Dart-Code/jobs/601130805

**Comment by jbracer19** [comment]
ok fine , want me to fix it?


On Oct 22, 2019, at 3:05 AM, Danny Tuppeny <notifications@github.com> wrote:

﻿

I believe this was expected to be fixed by #71126<https://github.com/microsoft/vscode/issues/71126>, however that fixed is included in the current stable release and it still happens (FYI @sandy081<https://github.com/sandy081> - the bot locked the existing issue, and I couldn't find another tracking this).

I still see this lots - most noticeably in my CI runs it just fills the logs. This one is using the current insiders build:

TreeError [MarkersPanel] Tree element not found: [object Object]: Error: TreeError [MarkersPanel] Tree element not found: [object Object]
    at t.ObjectTreeModel.getElementLocation (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:136:14)
    at t.ObjectTreeModel.isCollapsed (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:135:250)
    at W.isCollapsed (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1037:72)
    at z.revealMarkersForCurrentActiveEditor (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5863:628)
    at z.autoReveal (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5863:485)
    at z.onActiveEditorChanged (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5860:776)
    at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5859:754
    at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:114:709
    at c.fire (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:118:286)
    at e.doEmitActiveEditorChangeEvent (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4862:364)
    at e.handleActiveEditorChange (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4862:160)
    at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4862:474
    at c.fire (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:118:286)
    at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5508:875
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async e.openEditor (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5507:750)
    at async e.doOpenEditor (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4864:479)
    at async e.$tryShowTextDocument (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3484:517)


https://travis-ci.org/Dart-Code/Dart-Code/jobs/601130805

**Comment by jbracer19** [comment]
someone was wiping my drives at the end, pretty sure one computer is down, Main will boot , just let me know when your ready


On Oct 22, 2019, at 3:09 AM, Rocket <notifications@github.com> wrote:

﻿
ok fine , want me to fix it?


On Oct 22, 2019, at 3:05 AM, Danny Tuppeny <notifications@github.com> wrote:

﻿

I believe this was expected to be fixed by #71126<https://github.com/microsoft/vscode/issues/71126>, however that fixed is included in the current stable release and it still happens (FYI @sandy081<https://github.com/sandy081> - the bot locked the existing issue, and I couldn't find another tracking this).

I still see this lots - most noticeably in my CI runs it just fills the logs. This one is using the current insiders build:

TreeError [MarkersPanel] Tree element not found: [object Object]: Error: TreeError [MarkersPanel] Tree element not found: [object Object]
at t.ObjectTreeModel.getElementLocation (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:136:14)
at t.ObjectTreeModel.isCollapsed (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:135:250)
at W.isCollapsed (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1037:72)
at z.revealMarkersForCurrentActiveEditor (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5863:628)
at z.autoReveal (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5863:485)
at z.onActiveEditorChanged (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5860:776)
at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5859:754
at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:114:709
at c.fire (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:118:286)
at e.doEmitActiveEditorChangeEvent (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4862:364)
at e.handleActiveEditorChange (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4862:160)
at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4862:474
at c.fire (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:118:286)
at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5508:875
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:89:5)
at async e.openEditor (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5507:750)
at async e.doOpenEditor (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4864:479)
at async e.$tryShowTextDocument (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3484:517)


https://travis-ci.org/Dart-Code/Dart-Code/jobs/601130805

**Comment by jbracer19** [comment]
well they hung a carrot and i probably should have stopped jumping for it earlier (figured a couple hours earlier but had consumed all of my day already, so i entertained liked usual,   but nobody can say i lack persistence :)
On Oct 22, 2019, at 3:09 AM, Rocket <notifications@github.com> wrote:

﻿
ok fine , want me to fix it?


On Oct 22, 2019, at 3:05 AM, Danny Tuppeny <notifications@github.com> wrote:

﻿

I believe this was expected to be fixed by #71126<https://github.com/microsoft/vscode/issues/71126>, however that fixed is included in the current stable release and it still happens (FYI @sandy081<https://github.com/sandy081> - the bot locked the existing issue, and I couldn't find another tracking this).

I still see this lots - most noticeably in my CI runs it just fills the logs. This one is using the current insiders build:

TreeError [MarkersPanel] Tree element not found: [object Object]: Error: TreeError [MarkersPanel] Tree element not found: [object Object]
at t.ObjectTreeModel.getElementLocation (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:136:14)
at t.ObjectTreeModel.isCollapsed (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:135:250)
at W.isCollapsed (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1037:72)
at z.revealMarkersForCurrentActiveEditor (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5863:628)
at z.autoReveal (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5863:485)
at z.onActiveEditorChanged (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5860:776)
at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5859:754
at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:114:709
at c.fire (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:118:286)
at e.doEmitActiveEditorChangeEvent (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4862:364)
at e.handleActiveEditorChange (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4862:160)
at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4862:474
at c.fire (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:118:286)
at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5508:875
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:89:5)
at async e.openEditor (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5507:750)
at async e.doOpenEditor (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4864:479)
at async e.$tryShowTextDocument (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3484:517)


https://travis-ci.org/Dart-Code/Dart-Code/jobs/601130805

**Comment by jrieken** [comment]
cc @joaomoreno

**Comment by sandy081** [comment]
With fix from #71126, markers model and tree model should be in sync always. There is no more asynchronosity. Tree model is updated as soon as markers model is changed. 

@joaomoreno Please let me know if this still can happen from within `ObjectTree`?

**Comment by sandy081** [comment]
@DanTup It would be great if you can provide us reproducible steps. Otherwise we are just shooting in the dark.

**Comment by DanTup** [comment]
@sandy081 sure, though I don't know exactly what's triggering it. Can you explain exactly what this code is doing that might give me a hint? I see `revealMarkersForCurrentActiveEditor` in the call stack, but I'm not really sure what "markers" are - is this related to the Problems view, or a side-bar tree?

**Comment by sandy081** [comment]
Yes it is related to Problems view and Markers are Problem/Diagnostics.  This is about trying to reveal the current active file in the Problems view if the file has problems.

**Comment by DanTup** [comment]
Tried running the same test runs locally and I'm not seeing this. Is it possible to make the error include more info that might help track it down? (for ex. something more than `[Object object]`)

**Comment by sandy081** [comment]
Added `toString` to element to print more info about element
