### ISSUE TITLE
Error when expanding/collapsing in the Problems view (icon changes, but contents to not collapse)

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#83211]
I can't repro this, but maybe from the description/error you can tell what it is. I had a filter of `!_demo.dart` in the problems view, which filters to just the `demo.dart` file that has errors:

<img width="947" alt="Screenshot 2019-10-24 at 10 00 46 am" src="https://user-images.githubusercontent.com/1078012/67470208-4908ca80-f645-11e9-9aad-fb2cf89148cc.png">

However when I tried to collapse it, the icon changed but the child nodes did not disappear:

<img width="315" alt="Screenshot 2019-10-24 at 10 02 02 am" src="https://user-images.githubusercontent.com/1078012/67470273-6047b800-f645-11e9-8533-7335b1e22d7c.png">

Even after I removed the filter, it remained in a broken state. There's an error in the console that may be relevant:

```
ERR ListError [MarkersPanel] Invalid start index: 40: Error: ListError [MarkersPanel] Invalid start index: 40
    at O.splice (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:883:34)
    at O.splice (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1019:1004)
    at t.IndexTreeModel._setListNodeCollapseState (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:125:920)
    at t.IndexTreeModel._setCollapseState (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:125:427)
    at eventBufferer.bufferEvents (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:125:303)
    at t.EventBufferer.bufferEvents (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:118:787)
    at t.IndexTreeModel.setCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:125:281)
    at t.ObjectTreeModel.setCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:133:672)
    at N.onPointer (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1019:668)
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:116:539)
    at e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:112:65)
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:116:519)
    at HTMLDivElement.s (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:122:46)
```

**Comment by DanTup** [comment]
@joaomoreno I know :( I tried, but wasn't able to reproduce it. I don't think I did anything more than was written above - I wondered if maybe it was a race condition, but I'm not familiar with how the tree works.

If I do see it again, is there anything I can do to extract info about the state of the tree that might help?

**Comment by eamodio** [comment]
When trying to repro this I also notice this strange behavior with filtering the problems view
![problems-toggle](https://user-images.githubusercontent.com/641685/67502335-b9b6e380-f653-11e9-80a0-9880b522bb89.gif)

**Comment by joaomoreno** [comment]
@eamodio Can you maybe get me some repro steps? I can't seem to get to that state.

**Comment by eamodio** [comment]
Here are the steps:
1. Create a problem in 2 files.
1. Whichever file is first in the problem list filter it out using something like `!**/fileA.ts`
1. Then try to expand/collapse the remaining problem (which is now the first one)

**Comment by eamodio** [comment]
@joaomoreno Just after I reproduced the issue with those steps above, I cleaned up the errors I made to those 2 files and then this happened:

![image](https://user-images.githubusercontent.com/641685/67598246-117c4a00-f73b-11e9-8c74-b771a8086e14.png)

```
  ERR TreeError [MarkersPanel] Tree element not found: {
	"resource": "/c:/Users/Eric/code/microsoft/vscode/src/vs/workbench/contrib/terminal/browser/terminalActions.ts",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'asfas'.",
	"source": "ts",
	"startLineNumber": 300,
	"startColumn": 1,
	"endLineNumber": 300,
	"endColumn": 6
}: Error: TreeError [MarkersPanel] Tree element not found: {
	"resource": "/c:/Users/Eric/code/microsoft/vscode/src/vs/workbench/contrib/terminal/browser/terminalActions.ts",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'asfas'.",
	"source": "ts",
	"startLineNumber": 300,
	"startColumn": 1,
	"endLineNumber": 300,
	"endColumn": 6
}
    at t.ObjectTreeModel.getParentNodeLocation (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:135:861)
    at Object.getSetSize (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1035:358)
    at C.updateItemInDOM (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:474:956)
    at C._splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:469:645)
    at C.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:468:596)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:37:712
    at Array.forEach (<anonymous>)
    at t.CombinedSpliceable.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:37:699)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:894:994
    at t.EventBufferer.bufferEvents (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:120:603)
    at O.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:894:961)
    at O.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1033:27)
    at t.IndexTreeModel.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:126:211)
    at t.ObjectTreeModel._setChildren (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:133:13)
    at t.ObjectTreeModel.setChildren (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:132:908)
    at W.setChildren (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1046:639)
    at z.refreshPanel (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5895:448)
    at z.onDidChangeModel (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5900:390)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5899:729
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:114:709
    at c.fire (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:118:286)
    at t.MarkersModel.setResourceMarkers (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2827:148)
    at p.onMarkerChanged (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2945:304)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2945:237
    at c.fire (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:118:286)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:114:379
log.ts:196   ERR Cannot read property 'templateData' of null: TypeError: Cannot read property 'templateData' of null
    at C.removeItemFromDOM (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:475:381)
    at C._splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:468:861)
    at C.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:468:596)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:37:712
    at Array.forEach (<anonymous>)
    at t.CombinedSpliceable.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:37:699)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:894:994
    at t.EventBufferer.bufferEvents (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:120:603)
    at O.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:894:961)
    at O.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1033:27)
    at t.IndexTreeModel.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:126:211)
    at t.ObjectTreeModel._setChildren (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:133:13)
    at t.ObjectTreeModel.setChildren (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:132:908)
    at W.setChildren (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1046:639)
    at z.refreshPanel (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5895:448)
    at z.onDidChangeModel (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5900:390)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5899:729
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:114:709
    at c.fire (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:118:286)
    at t.MarkersModel.setResourceMarkers (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2827:148)
    at p.onMarkerChanged (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2945:304)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2945:237
    at c.fire (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:118:286)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:114:379
log.ts:196   ERR TreeError [MarkersPanel] Tree element not found: {
	"resource": "/c:/Users/Eric/code/microsoft/vscode/src/vs/workbench/contrib/terminal/browser/terminalActions.ts",
	"owner": "typescript",
	"code": "1",
	"severity": 4,
	"message": "Missing semicolon (semicolon)",
	"source": "tslint",
	"startLineNumber": 300,
	"startColumn": 6,
	"endLineNumber": 300,
	"endColumn": 6
}: Error: TreeError [MarkersPanel] Tree element not found: {
	"resource": "/c:/Users/Eric/code/microsoft/vscode/src/vs/workbench/contrib/terminal/browser/terminalActions.ts",
	"owner": "typescript",
	"code": "1",
	"severity": 4,
	"message": "Missing semicolon (semicolon)",
	"source": "tslint",
	"startLineNumber": 300,
	"startColumn": 6,
	"endLineNumber": 300,
	"endColumn": 6
}
    at t.ObjectTreeModel.getParentNodeLocation (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:135:861)
    at Object.getSetSize (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1035:358)
    at C.updateItemInDOM (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:474:956)
    at C._splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:469:645)
    at C.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:468:596)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:37:712
    at Array.forEach (<anonymous>)
    at t.CombinedSpliceable.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:37:699)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:894:994
    at t.EventBufferer.bufferEvents (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:120:603)
    at O.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:894:961)
    at O.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1033:27)
    at t.IndexTreeModel.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:126:211)
    at t.ObjectTreeModel._setChildren (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:133:13)
    at t.ObjectTreeModel.setChildren (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:132:908)
    at W.setChildren (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1046:639)
    at z.refreshPanel (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5895:551)
    at z.onDidChangeModel (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5900:390)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5899:729
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:114:709
    at c.fire (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:118:286)
    at t.MarkersModel.setResourceMarkers (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2827:148)
    at p.onMarkerChanged (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2945:304)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2945:237
    at c.fire (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:118:286)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:114:379
log.ts:196   ERR Cannot read property 'templateData' of null: TypeError: Cannot read property 'templateData' of null
    at C.removeItemFromDOM (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:475:381)
    at C._splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:468:861)
    at C.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:468:596)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:37:712
    at Array.forEach (<anonymous>)
    at t.CombinedSpliceable.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:37:699)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:894:994
    at t.EventBufferer.bufferEvents (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:120:603)
    at O.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:894:961)
    at O.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1033:27)
    at t.IndexTreeModel.splice (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:126:211)
    at t.ObjectTreeModel._setChildren (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:133:13)
    at t.ObjectTreeModel.setChildren (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:132:908)
    at W.setChildren (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1046:639)
    at z.refreshPanel (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5895:551)
    at z.onDidChangeModel (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5900:390)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5899:729
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:114:709
    at c.fire (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:118:286)
    at t.MarkersModel.setResourceMarkers (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2827:148)
    at p.onMarkerChanged (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2945:304)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2945:237
    at c.fire (file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:118:286)
    at file:///C:/Users/Eric/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:114:379
```

**Comment by joaomoreno** [comment]
@eamodio Perfect steps, thank you!
