### ISSUE TITLE
Modules get loaded twice during npm test from command line

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#83254]
Issue Type: <b>Bug</b>

This is similar to https://github.com/microsoft/vscode/issues/69569, except instead of affecting F5, it seems to only affect console npm test.  (This is the third time I've had this issue of some modules getting loaded twice during functional tests on Windows due to drive letter case inconsistency.)

Let me know if I need to create a repro scenario, but it appears that Module._compile (src/vs/loader.js) is changing the drive letter from "c:" to "C:" in some scenarios, which causes the module load cache to miss, which causes some modules to be loaded twice, which causes problems with singletons.

Here's the first load of extension.bundle.ts in my extension (loaded via Mocha):
```
    at Object.<anonymous> (C:\Users\stephwe\Repos\vscode-azurearmtools\dist\extension.bundle.js:181038:3)
    at Module.o._compile (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.t._load (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:785:720)
    at Function.n._load (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:754:302)
    at Function.i._load (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:750:870)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at n (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\loader.js:15:524)
    at Object.<anonymous> (C:\Users\stephwe\Repos\vscode-azurearmtools\test\AzureRMAssets.test.ts:8:1)
>>>>>>>    at Object.<anonymous> (C:\Users\stephwe\Repos\vscode-azurearmtools\dist\test\AzureRMAssets.test.js:312:3)   <<<<  drive changed from c: to C:
    at Module.o._compile (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.t._load (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:785:720)
    at Function.n._load (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:754:302)
    at Function.i._load (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:750:870)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at n (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\loader.js:15:524)
    at c:\Users\stephwe\Repos\vscode-azurearmtools\node_modules\mocha\lib\mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (c:\Users\stephwe\Repos\vscode-azurearmtools\node_modules\mocha\lib\mocha.js:247:14)
    at Mocha.run (c:\Users\stephwe\Repos\vscode-azurearmtools\node_modules\mocha\lib\mocha.js:576:10)
    at c:\Users\stephwe\Repos\vscode-azurearmtools\node_modules\vscode\lib\testrunner.js:35:19
    at f (c:\Users\stephwe\Repos\vscode-azurearmtools\node_modules\once\once.js:25:25)
    at Glob.<anonymous> (c:\Users\stephwe\Repos\vscode-azurearmtools\node_modules\glob\glob.js:151:7)
    at Glob.emit (events.js:182:13)
    at Glob._finish (c:\Users\stephwe\Repos\vscode-azurearmtools\node_modules\glob\glob.js:197:8)
    at done (c:\Users\stephwe\Repos\vscode-azurearmtools\node_modules\glob\glob.js:182:14)
    at Glob._processGlobStar2 (c:\Users\stephwe\Repos\vscode-azurearmtools\node_modules\glob\glob.js:637:12)
    at c:\Users\stephwe\Repos\vscode-azurearmtools\node_modules\glob\glob.js:626:10
    at RES (c:\Users\stephwe\Repos\vscode-azurearmtools\node_modules\inflight\inflight.js:31:16)
    at f (c:\Users\stephwe\Repos\vscode-azurearmtools\node_modules\once\once.js:25:25)
    at lstatcb_ (c:\Users\stephwe\Repos\vscode-azurearmtools\node_modules\glob\glob.js:519:7)
    at RES (c:\Users\stephwe\Repos\vscode-azurearmtools\node_modules\inflight\inflight.js:31:16)
    at f (c:\Users\stephwe\Repos\vscode-azurearmtools\node_modules\once\once.js:25:25)
    at FSReqWrap.oncomplete (fs.js:155:5)

Here's the second load (via starting the extension):

    at Object.<anonymous> (c:\Users\stephwe\Repos\vscode-azurearmtools\dist\extension.bundle.js:181038:3)
    at Module.o._compile (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.t._load (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:785:720)
    at Function.n._load (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:754:302)
    at Function.i._load (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:750:870)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at n (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\loader.js:15:524)
    at Object.<anonymous> (c:\Users\stephwe\Repos\vscode-azurearmtools\main.js:20:19)
    at Object.<anonymous> (c:\Users\stephwe\Repos\vscode-azurearmtools\main.js:35:3)
    at Module.o._compile (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.t._load (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:785:720)
    at Function.n._load (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:754:302)
    at Function.i._load (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:750:870)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Function.s [as __$__nodeRequire] (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\loader.js:32:963)
    at t.ExtHostExtensionService._loadCommonJSModule (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:755:484)
    at t.ExtHostExtensionService._doActivateExtension (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:666:300)
    at t.ExtHostExtensionService._activateExtension (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:665:360)
    at Object.actualActivateExtension (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:663:296)
    at t.ExtensionsActivator._activateExtension (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:496:731)
    at n.length.Promise.all.r.map.e (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:496:409)
    at Array.map (<anonymous>)
    at t.ExtensionsActivator._activateExtensions (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:496:397)
    at t.ExtensionsActivator.activateByEvent (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:494:126)
    at t.ExtHostExtensionService._activateByEvent (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:664:24)
    at _readyToRunExtensions.wait.then.t (c:\Users\stephwe\Repos\vscode-azurearmtools\.vscode-test\vscode-1.39.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:672:293)
```

Notice how the drive letter changed from "c:" to "C:" in the first scenario during module load.

```
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (13.04GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/stephwe/Repos/vscode-azurearmtools|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.8.0
tsco|alj|1.0.12
vscode-browser-preview|auc|0.5.9
azure-arm-template-helper|ed-|0.0.17
rest-client|hum|0.22.2
vscode-antlr4|mik|2.1.1
azure-pipelines|ms-|1.157.4
vscode-apimanagement|ms-|0.1.1
vscode-azureappservice|ms-|0.16.1
vscode-azurefunctions|ms-|0.19.1
vscode-azurestorage|ms-|0.7.2
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.8.1
extension-manifest-editor|ms-|0.1.5
mssql|ms-|1.7.0
python|ms-|2019.10.44104
azure-account|ms-|0.8.6
azurecli|ms-|0.4.6
csharp|ms-|1.21.5
powershell|ms-|2019.9.0
vscode-node-azure-pack|ms-|0.0.9
vscode-typescript-tslint-plugin|ms-|1.2.2
azurerm-vscode-tools|msa|0.7.0
arm-snippets|sam|1.4.19
scope-info|sie|0.2.0
tmcolor|sle|0.0.1
html-preview-vscode|tht|0.2.5
arm-params-generator|wil|0.8.0


</details>
<!-- generated by issue reporter -->
```

**Comment by octref** [comment]
@aeschli Seems to related to ext host not the vscode-test library, so assigning to you.

**Comment by aeschli** [comment]
@StephenWeatherford If you can add instructions how to reproduce, that would be great.
