### ISSUE TITLE
TypeError: Object of type module is not JSON serializable

### ISSUE THREAD

**Issue by TurboCooler** [microsoft/vscode#83585]
Issue Type: <b>Bug</b>

This error occurs when attempting to debug a Flask application:

```
Traceback (most recent call last):
  File "c:\Users\<local-os-username>\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 283, in _on_run
    self.process_net_command_json(self.global_debugger_holder.global_dbg, json_contents)
  File "c:\Users\<local-os-username>\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command_json.py", line 164, in process_net_command_json
    cmd = on_request(py_db, request)
  File "c:\Users\<local-os-username>\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command_json.py", line 623, in on_stacktrace_request
    self.api.request_stack(py_db, request.seq, thread_id, fmt=fmt, start_frame=start_frame, levels=levels)
  File "c:\Users\<local-os-username>\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_api.py", line 190, in request_stack
    if internal_get_thread_stack.can_be_executed_by(get_current_thread_id(threading.current_thread())):
  File "c:\Users\<local-os-username>\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 596, in can_be_executed_by
    py_db, self.seq, self.thread_id, frame, self._fmt, must_be_suspended=not timed_out, start_frame=self._start_frame, levels=self._levels)
  File "c:\Users\<local-os-username>\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_net_command_factory_json.py", line 211, in make_get_thread_stack_message
    module_events.extend(self.modules_manager.track_module(filename_in_utf8, module_name, frame))
  File "c:\Users\<local-os-username>\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_net_command_factory_json.py", line 62, in track_module
    module_events.append(NetCommand(CMD_MODULE_EVENT, 0, module_event, is_json=True))
  File "c:\Users\<local-os-username>\.vscode\extensions\ms-python.python-2019.10.44104\pythonFiles\lib\python\old_ptvsd\ptvsd\_vendored\pydevd\_pydevd_bundle\pydevd_net_command.py", line 57, in __init__
    text = json.dumps(as_dict)
  File "C:\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  **File "C:\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type module is not JSON serializable**
```

Flask seems to give me an IP address and I am still able to hit the endpoint but I am worried that this will lead to a different error while debugging some code.  I have Visual Studio 2019 and VS Code installed on the same machine.  

I do not believe I need to install ptvsd in the virtual directory but do I need to somehow specify a specific ptvsd i need to use?

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (15.60GB free)|
|Process Argv|C:\project\gitrepo\ProjectRepo\src\myproject|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.2.0
gc-excelviewer|Gra|2.1.32
electron-debug|kod|18.11.1
python|ms-|2019.10.44104
remote-wsl|ms-|0.39.9
powershell|ms-|2019.9.0
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please file this against the python extension
