### ISSUE TITLE
Bad configuration service key

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#83656]
Related to https://github.com/microsoft/vscode/issues/83537

Caused by https://github.com/microsoft/vscode/commit/d4df127b2070b9c5d6ba6aa539d3a246d1903936

I get this on startup:

```
  ERR Cannot assign to read only property 'method' of object '[object Object]': TypeError: Cannot assign to read only property 'method' of object '[object Object]'
    at addToValueTree (file:///home/joao/Work/vscode/out/vs/platform/configuration/common/configuration.js:100:24)
    at Object.getDefaultValues (file:///home/joao/Work/vscode/out/vs/platform/configuration/common/configuration.js:174:13)
    at new DefaultConfigurationModel (file:///home/joao/Work/vscode/out/vs/platform/configuration/common/configurationModels.js:145:46)
    at WorkspaceService.onDefaultConfigurationChanged (file:///home/joao/Work/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:348:41)
    at file:///home/joao/Work/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:42:158
    at Emitter.fire (file:///home/joao/Work/vscode/out/vs/base/common/event.js:458:38)
    at ConfigurationRegistry.registerDefaultConfigurations (file:///home/joao/Work/vscode/out/vs/platform/configuration/common/configurationRegistry.js:139:44)
    at ExtensionPoint._handler (file:///home/joao/Work/vscode/out/vs/workbench/api/common/configurationExtensionPoint.js:108:35)
    at ExtensionPoint._handle (file:///home/joao/Work/vscode/out/vs/workbench/services/extensions/common/extensionsRegistry.js:86:22)
    at ExtensionPoint.acceptUsers (file:///home/joao/Work/vscode/out/vs/workbench/services/extensions/common/extensionsRegistry.js:79:18)
    at Function._handleExtensionPoint (file:///home/joao/Work/vscode/out/vs/workbench/services/extensions/common/abstractExtensionService.js:283:28)
    at ExtensionService._doHandleExtensionPoints (file:///home/joao/Work/vscode/out/vs/workbench/services/extensions/common/abstractExtensionService.js:245:46)
    at ExtensionService._registerAndHandleExtensions (file:///home/joao/Work/vscode/out/vs/workbench/services/extensions/electron-browser/extensionService.js:435:18)
    at ExtensionService._startLocalExtensionHost (file:///home/joao/Work/vscode/out/vs/workbench/services/extensions/electron-browser/extensionService.js:427:18)
    at ExtensionService._scanAndHandleExtensions (file:///home/joao/Work/vscode/out/vs/workbench/services/extensions/electron-browser/extensionService.js:423:28)
    at async ExtensionService._initialize (file:///home/joao/Work/vscode/out/vs/workbench/services/extensions/common/abstractExtensionService.js:61:13)
```

**Comment by jrieken** [comment]
@sandy081 See this change: https://github.com/microsoft/vscode/commit/d4df127b2070b9c5d6ba6aa539d3a246d1903936. It can wreck VS Code, I believe extensions can do the same

**Comment by sandy081** [comment]
We allow setting that is a prefix of another setting. 

This is a bug in config model where the default value got frozen and is being asked to modified when a new config is registered.

**Comment by sandy081** [comment]
This has been fixed with several improvements made to the configuration model
