### ISSUE TITLE
Windows Smoke Test failure: Debug configure launch json

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#83821]
Windows:

```
Running Code
       Debug
         configure launch json:

      AssertionError [ERR_ASSERTION]: '${workspaceFolder}/bin/www' == '${workspaceFolder}\\bin\\www'
      + expected - actual

      -${workspaceFolder}/bin/www
      +${workspaceFolder}\bin\www

      at Context.<anonymous> (out\areas\debug\debug.test.js:30:24)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by weinand** [comment]
Problem with the "configure launch json" test on Windows. 
A correct launch.json is generated when running the test manually.

**Comment by isidorn** [comment]
I believe @roblourens has fixed this. I think I read it somewhere on slack. Right?

**Comment by alexr00** [comment]
That test now passes, so it looks fixed to me.

**Comment by roblourens** [comment]
Yes fixed by pushing a change to the smoketest-express repo
