### ISSUE TITLE
OutOfRangeException when typing commands in the integrated powershell console

### ISSUE THREAD

**Issue by matthewaturner** [microsoft/vscode#83856]
Issue Type: <b>Bug</b>

I'm not sure the exact scenario that causes this. I had been using the integrated powershell terminal to run some powershell build scripts. This doesn't always happen but I have seen it at least three times. Killing and re-creating the terminal fixes the problem.

OutOfRangeException is thrown immediately when I hit the first character that needs to wrap to the next line. In fact if I resize the window I get to type more characters before I get this problem.

Output: 
PS C:\Users\matur\source\repos\TrustedDevelopmentCloud> ;lkajsdf;lkjsdflslslsldkfjdkdksksj
An error occurred while reading input:

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 86.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.InsertInput(StringBuilder inputLine, Int32 promptStartCol, Int32 promptStartRow, String insertedInput, Int32 cursorIndex, Int32 insertIndex, Int32 replaceLength, Int32 finalCursorIndex)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.<ReadLine>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PowerShell.EditorServices.EditorServicesPSHostUserInterface.<StartReplLoop>d__95.MoveNext()

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (4.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
dotnet-test-explorer|for|0.7.1
docomment|k--|0.1.8
azure-account|ms-|0.8.7
csharp|ms-|1.21.5
powershell|ms-|2019.9.0
vim|vsc|1.11.3

(1 theme extensions excluded)

</details>

**Comment by matthewaturner** [comment]
duplicate
