### ISSUE TITLE
[web] Error: Not Implemented: IExtHostDebugService->$acceptDebugSessionCustomEvent

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#84249]
This may be known/expected, but I couldn't see an obvious issue covering it. When I try to launch the Dart debugger on the web, it doesn't work correctly and I get a console full of "Not implemented errors" such as:

```
  ERR Not Implemented: IExtHostDebugService->$acceptDebugSessionCustomEvent: Error: Not Implemented: IExtHostDebugService->$acceptDebugSessionCustomEvent
	at Object.get (https://online.visualstudio.com/static/web-standalone/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:621:236)
	at p._doInvokeHandler (https://online.visualstudio.com/static/web-standalone/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:546:155)
	at p._invokeHandler (https://online.visualstudio.com/static/web-standalone/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:545:971)
	at p._receiveRequest (https://online.visualstudio.com/static/web-standalone/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:544:639)
	at p._receiveOneMessage (https://online.visualstudio.com/static/web-standalone/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:543:468)
	at https://online.visualstudio.com/static/web-standalone/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:541:691
	at l.fire (https://online.visualstudio.com/static/web-standalone/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:47:207)
	at https://online.visualstudio.com/static/web-standalone/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:623:192
```

I don't know if it's relevant, but the extension is using the 1.40 VS Code typings (I want to be able to use `asExternalUri`). As far as I can tell, the web is 1.40 (albeit an insiders build).

My extension does make use of custom debug events, though it's not the only one failing (for example there's `ERR Not Implemented: IExtHostDebugService->$acceptDebugSessionActiveChanged`).

**Comment by DanTup** [comment]
> I don't know if it's relevant, but the extension is using the 1.40 VS Code typings 

Actually, this might not be the case.. I did run **Install from VSIX** and select it, but (possibly after I reloaded the window) it now shows as the original marketplace version.

**Comment by bpasero** [comment]
@jrieken hm any clues how come the `extensionHostWorker` is involved?

**Comment by jrieken** [comment]
I assume that's an event from the renderer that reaches all extension hosts

**Comment by bpasero** [comment]
@DanTup still happens?

**Comment by DanTup** [comment]
Nope, not seeing this now. I do see a warning ("Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!") but no error.

![Screenshot 2020-02-26 at 11 08 44](https://user-images.githubusercontent.com/1078012/75339410-5f8b9080-5888-11ea-9a37-91b80ea91ff1.png)
