### ISSUE TITLE
Invalid Grid State when using setEditorLayout with groups of unequal length

### ISSUE THREAD

**Issue by spencer-shupe-qhr** [microsoft/vscode#84425]
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0 and 18.2.0

Steps to Reproduce:

1. Start with the extension example produced from the introduction in https://code.visualstudio.com/api/get-started/your-first-extension
2. Within the Hello World command, add 
```
vscode.commands.executeCommand(
  'vscode.setEditorLayout',
  { orientation: 0, groups: [{ groups: [{}, {}], size: 0.5 }, { groups: [{}], size: 0.5 }] }
);
```
3. Build the extension and execute the command
4. Close the newly opened 2x1 panel (keyboard shortcut and clicking X produce different error states)

Does this issue occur when all extensions are disabled?: Yes

Information:
I am running into this error while trying to build an extension that opens documents in 3 pane, mixed horizontal/vertical layout, as demonstrated in the reproduction steps. If I am using the setEditorLayout command incorrectly to achieve this, I would greatly appreciate corrections.

After closing all open panes, the following error trace is printed in the console:
<details><summary>Trace</summary>

```
 ERR Invalid grid element: Error: Invalid grid element
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:523:464
    at u (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:523:603)
    at p.getViewLocation (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:528:506)
    at p.getViewSize (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:526:949)
    at e.doRestoreGroup (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5587:100)
    at e.doSetGroupActive (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5586:984)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5586:546
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:115:286)
    at e.focus (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5568:329)
    at e.doCloseActiveEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5572:694)
    at e.doCloseEditors (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5574:424)
    at e.closeEditors (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5573:975)
    at async Promise.all (index 0)
```
</details>

**Comment by spencer-shupe-qhr** [comment]
The above tickets reported by the vscodebot do not appear to be related, however I did come across https://github.com/microsoft/vscode/issues/80614 in my searches before opening this issue.

**Comment by bpasero** [comment]
❤️ for building an extension on top of `vscode.setEditorLayout`

**Comment by joaomoreno** [comment]
Great catch. This happens because there isn't enough validation done around the grid descriptor. The following is redundant:

```
{ groups: [{}], size: 0.5 }
```

All you needed to do here was:

```
{ size: 0.5 }
```

I've pushed a validation rule which will do this for you automatically.

**Comment by spencer-shupe-qhr** [comment]
Thanks for the correction and all your hard work guys, really excited to continue working with setEditorLayout!
