### ISSUE TITLE
Tests: lots of errors printed when running ipc tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#84455]
I think it is not very helpful to have tests produce errors to the console:

```
Uncaught (in promise) Canceled: Canceled
    at Object.canceled (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/errors.js:99:23)
    at file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/async.js:262:31
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/event.js:458:38)
    at MutableToken.cancel (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/cancellation.js:46:35)
    at CancellationTokenSource.cancel (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/cancellation.js:93:29)
    at Object.dispose (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/cache.js:24:25)
    at Context.<anonymous> (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/test/common/cache.test.js:37:20)
    at callFn (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4471:21)
    at Test.Runnable.run (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4464:7)
    at Runner.runTest (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4934:10)
    at file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:5040:12
    at next (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4854:14)
    at file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4864:7
    at next (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4796:14)
    at file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4832:5
    at timeslice (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:75:27)
```

```
Uncaught (in promise) Canceled: Canceled
    at Object.canceled (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/errors.js:99:23)
    at file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/async.js:17:31
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/event.js:458:38)
    at MutableToken.cancel (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/cancellation.js:46:35)
    at CancellationTokenSource.cancel (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/cancellation.js:93:29)
    at Object.cancel (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/async.js:29:24)
    at cancel (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/parts/ipc/common/ipc.js:353:46)
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/event.js:458:38)
    at MutableToken.cancel (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/cancellation.js:46:35)
    at CancellationTokenSource.cancel (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/cancellation.js:93:29)
    at Context.<anonymous> (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/parts/ipc/test/node/ipc.test.js:210:21)
    at callFn (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4471:21)
    at Test.Runnable.run (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4464:7)
    at Runner.runTest (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4934:10)
    at file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:5040:12
    at next (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4854:14)
    at file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4864:7
    at next (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4796:14)
    at file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4827:7
    at done (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4432:5)
    at callFn (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4489:7)
    at Hook.Runnable.run (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4464:7)
    at next (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4810:10)
    at file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:4832:5
    at timeslice (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/node_modules/mocha/mocha.js:75:27)
```

```
errors.js:99 Uncaught (in promise) Canceled: Canceled
    at Object.canceled (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/errors.js:99:23)
    at Delayer.cancel (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/async.js:189:38)
    at Client.dispose (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/parts/ipc/node/ipc.cp.js:172:37)
    at file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/parts/ipc/test/node/ipc.cp.test.js:23:48
    at <anonymous>
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

```
errors.js:99 Uncaught (in promise) Canceled: Canceled
    at Object.canceled (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/errors.js:99:23)
    at Delayer.cancel (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/async.js:189:38)
    at Client.requestPromise (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/parts/ipc/node/ipc.cp.js:60:33)
    at Object.call (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/parts/ipc/node/ipc.cp.js:46:33)
    at TestServiceClient.marco (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/parts/ipc/test/node/testService.js:51:33)
    at file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/parts/ipc/test/node/ipc.cp.test.js:57:48
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

```
errors.js:99 Uncaught (in promise) Canceled: Canceled
    at Object.canceled (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/errors.js:99:23)
    at Delayer.cancel (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/common/async.js:189:38)
    at Client.dispose (file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/parts/ipc/node/ipc.cp.js:172:37)
    at file:///Users/bpasero/Development/Microsoft/vscode-electron-4.0.x/out/vs/base/parts/ipc/test/node/ipc.cp.test.js:61:48
    at <anonymous>
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

Maybe register a handler for the duration of tests to catch these?

Not sure who owns these tests, feel free to move forward.

**Comment by joaomoreno** [comment]
We now omit all unhandled cancelled promises from the logs.
