### ISSUE TITLE
Updating language specific setting fails with exception.

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#84528]
I try writing the '[html]' setting using the VS Code update API but it fails with the following exception:

```
TypeError: Cannot read property 'scope' of undefined
    at ConfigurationEditingService.resolveAndValidate (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/workbench/services/configuration/common/configurationEditingService.js:345:64)
    at ConfigurationEditingService.doWriteConfiguration (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/workbench/services/configuration/common/configurationEditingService.js:106:25)
    at Object.factory (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/workbench/services/configuration/common/configurationEditingService.js:95:64)
    at Queue.consume (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/base/common/async.js:349:46)
    at file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/base/common/async.js:342:22
    at new Promise (<anonymous>)
    at Queue.queue (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/base/common/async.js:340:20)
    at ConfigurationEditingService.writeConfiguration (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/workbench/services/configuration/common/configurationEditingService.js:95:47)
    at WorkspaceService.writeConfigurationValue (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:477:53)
    at file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/workbench/services/configuration/browser/configurationService.js:163:38
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

```

The reason is that the `configurationProperties` don't have an `[html]` entry since it is a language id specific section and must not have its own definition.

![capture](https://user-images.githubusercontent.com/1931590/68618645-1591c100-04ca-11ea-9325-578bfc30a6a9.png)

**Comment by roblourens** [comment]
Was this using the extension API? Can you give an example of the code? I can't repro

**Comment by sandy081** [comment]
Yes, please use the extension API to update a lang specific configuration in workspace or workspace folder.

Eg: `vscode.workspace.getConfiguration().update('[lang]', ${value}, ConfigurationTarget.Workspace)`

**Comment by dbaeumer** [comment]
MArking as verified since I use this since a while in the ESLint extension.
