### ISSUE TITLE
TypeScript Server Error (3.7.2: Debug Failure. Did not expect ClassDeclaration to have an Identifier in its trivia

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#84939]
Issue Type: <b>Bug</b>

/cc @mjbvz 

[extension-prod.zip](https://github.com/microsoft/vscode/files/3852933/extension-prod.zip)

Each time I open this file in vscode I see the following errors in the console:
```
 ERR <syntax> TypeScript Server Error (3.7.2)
Debug Failure. Did not expect ClassDeclaration to have an Identifier in its trivia
Error: Debug Failure. Did not expect ClassDeclaration to have an Identifier in its trivia
    at addSyntheticNodes (tsserver.js:129706:30)
    at createChildren (tsserver.js:129695:9)
    at NodeObject.getChildren (tsserver.js:129639:56)
    at Object.findChildOfKind (tsserver.js:102885:26)
    at spanForNode (tsserver.js:113571:36)
    at getOutliningSpanForNode (tsserver.js:113529:28)
    at visitNonImportNode (tsserver.js:113386:28)
    at visitNodes (tsserver.js:17609:30)
    at Object.forEachChild (tsserver.js:17840:24)
    at NodeObject.forEachChild (tsserver.js:129662:23)
    at visitNonImportNode (tsserver.js:113399:23)
    at visitNode (tsserver.js:17600:24)
    at Object.forEachChild (tsserver.js:17730:21)
    at NodeObject.forEachChild (tsserver.js:129662:23)
    at visitNonImportNode (tsserver.js:113399:23)
    at visitNode (tsserver.js:17600:24)
    at Object.forEachChild (tsserver.js:17803:24)
    at NodeObject.forEachChild (tsserver.js:129662:23)
    at visitNonImportNode (tsserver.js:113399:23)
    at visitNode (tsserver.js:17600:24)
    at Object.forEachChild (tsserver.js:17820:24)
    at NodeObject.forEachChild (tsserver.js:129662:23)
    at visitNonImportNode (tsserver.js:113399:23)
    at visitNode (tsserver.js:17600:24)
    at Object.forEachChild (tsserver.js:17851:24)
    at NodeObject.forEachChild (tsserver.js:129662:23)
    at visitNonImportNode (tsserver.js:113399:23)
    at addNodeOutliningSpans (tsserver.js:113361:21)
    at Object.collectElements (tsserver.js:113349:13)
    at Object.getOutliningSpans (tsserver.js:130985:50)
    at IOSession.Session.getOutliningSpans (tsserver.js:140197:45)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139293:61)
    at tsserver.js:140870:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140861:28)
    at IOSession.Session.executeCommand (tsserver.js:140870:33)
    at IOSession.Session.onMessage (tsserver.js:140893:35)
    at Interface.<anonymous> (tsserver.js:142208:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17): Error: <syntax> TypeScript Server Error (3.7.2)
Debug Failure. Did not expect ClassDeclaration to have an Identifier in its trivia
Error: Debug Failure. Did not expect ClassDeclaration to have an Identifier in its trivia
    at addSyntheticNodes (tsserver.js:129706:30)
    at createChildren (tsserver.js:129695:9)
    at NodeObject.getChildren (tsserver.js:129639:56)
    at Object.findChildOfKind (tsserver.js:102885:26)
    at spanForNode (tsserver.js:113571:36)
    at getOutliningSpanForNode (tsserver.js:113529:28)
    at visitNonImportNode (tsserver.js:113386:28)
    at visitNodes (tsserver.js:17609:30)
    at Object.forEachChild (tsserver.js:17840:24)
    at NodeObject.forEachChild (tsserver.js:129662:23)
    at visitNonImportNode (tsserver.js:113399:23)
    at visitNode (tsserver.js:17600:24)
    at Object.forEachChild (tsserver.js:17730:21)
    at NodeObject.forEachChild (tsserver.js:129662:23)
    at visitNonImportNode (tsserver.js:113399:23)
    at visitNode (tsserver.js:17600:24)
    at Object.forEachChild (tsserver.js:17803:24)
    at NodeObject.forEachChild (tsserver.js:129662:23)
    at visitNonImportNode (tsserver.js:113399:23)
    at visitNode (tsserver.js:17600:24)
    at Object.forEachChild (tsserver.js:17820:24)
    at NodeObject.forEachChild (tsserver.js:129662:23)
    at visitNonImportNode (tsserver.js:113399:23)
    at visitNode (tsserver.js:17600:24)
    at Object.forEachChild (tsserver.js:17851:24)
    at NodeObject.forEachChild (tsserver.js:129662:23)
    at visitNonImportNode (tsserver.js:113399:23)
    at addNodeOutliningSpans (tsserver.js:113361:21)
    at Object.collectElements (tsserver.js:113349:13)
    at Object.getOutliningSpans (tsserver.js:130985:50)
    at IOSession.Session.getOutliningSpans (tsserver.js:140197:45)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139293:61)
    at tsserver.js:140870:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140861:28)
    at IOSession.Session.executeCommand (tsserver.js:140870:33)
    at IOSession.Session.onMessage (tsserver.js:140893:35)
    at Interface.<anonymous> (tsserver.js:142208:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
	at Function.create (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:53:63732)
	at h.dispatchResponse (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:53:56670)
	at h.dispatchMessage (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:53:55568)
	at c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:53:55044
	at l.fire (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at t.Reader.onLengthData (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:53:61946)
	at Socket.<anonymous> (c:\Users\Eric\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:53:61594)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.41.0-insider (bf7d03bf88732af0b46e473c663c49e18e839f9c, 2019-11-15T05:40:12.201Z)
OS version: Windows_NT x64 10.0.19023

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (18.14GB free)|
|Process Argv|--enable-proposed-api eamodio.remotehub|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/35133 to track upstream
