### ISSUE TITLE
Go To Definition won't work because of TSServer failure

### ISSUE THREAD

**Issue by Mikrovolnovka** [microsoft/vscode#85021]
Issue Type: <b>Bug</b>

```
ERR command 'workbench.action.reportIssues' not found: Error: command 'workbench.action.reportIssues' not found
    at u._tryExecuteCommand (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3305:697)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3305:578
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

```
 ERR <main> TypeScript Server Error (3.8.0-dev.20191116)
No Project.
Error: No Project.
    at Object.ThrowNoProject (tsserver.js:133380:23)
    at ProjectService.doEnsureDefaultProjectForFile (tsserver.js:136654:131)
    at ProjectService.ensureDefaultProjectForFile (tsserver.js:136649:75)
    at IOSession.Session.getFileAndProjectWorker (tsserver.js:140306:87)
    at IOSession.Session.getFileAndProject (tsserver.js:140289:29)
    at IOSession.Session.getApplicableRefactors (tsserver.js:140739:31)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139594:61)
    at tsserver.js:140984:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140975:28)
    at IOSession.Session.executeCommand (tsserver.js:140984:33)
    at IOSession.Session.onMessage (tsserver.js:141007:35)
    at Interface.<anonymous> (tsserver.js:142322:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17): Error: <main> TypeScript Server Error (3.8.0-dev.20191116)
No Project.
Error: No Project.
    at Object.ThrowNoProject (tsserver.js:133380:23)
    at ProjectService.doEnsureDefaultProjectForFile (tsserver.js:136654:131)
    at ProjectService.ensureDefaultProjectForFile (tsserver.js:136649:75)
    at IOSession.Session.getFileAndProjectWorker (tsserver.js:140306:87)
    at IOSession.Session.getFileAndProject (tsserver.js:140289:29)
    at IOSession.Session.getApplicableRefactors (tsserver.js:140739:31)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139594:61)
    at tsserver.js:140984:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140975:28)
    at IOSession.Session.executeCommand (tsserver.js:140984:33)
    at IOSession.Session.onMessage (tsserver.js:141007:35)
    at Interface.<anonymous> (tsserver.js:142322:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
	at Function.create (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:63732)
	at h.dispatchResponse (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:56670)
	at h.dispatchMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:55568)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:55044
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47:207)
	at t.Reader.onLengthData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:61946)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:61594)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|17%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.9.1
vscode-npm-script|eg2|0.3.9
path-autocomplete|ion|1.13.3
vscode-typescript-next|ms-|3.8.20191116
debugger-for-chrome|msj|4.12.1
remote-vscode|raf|1.1.0

</details>

**Comment by Mikrovolnovka** [comment]
Seems to happen after this commit: https://github.com/microsoft/vscode/commit/5aec74ad3b55bb9463e717ec950e665288accd0f

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Mikrovolnovka** [comment]
@mjbvz 

Insiders errors:

App version:
```
Version: 1.41.0-insider
Commit: 2014f5adccbce83d347e714206903f2bbee40dcb
Date: 2019-11-18T09:29:38.612Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
```

Console output:

```
[Extension Host] A non-recoverable error occured while executing tsserver command: updateOpen (at C.fatalError (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:184370))
t.log @ console.ts:137

[Extension Host] rejected promise not handled within 1 second: Error: <semantic> TypeScript Server Error (3.7.2)Cannot read property 'exports' of undefinedTypeError: Cannot read property 'exports' of undefined
    at declareModuleMember (tsserver.js:29333:63)
    at delayedBindJSDocTypedefTag (tsserver.js:30680:29)
    at bindSourceFile (tsserver.js:29049:17)
    at Object.bindSourceFile (tsserver.js:28983:9)
    at initializeTypeChecker (tsserver.js:64348:20)
    at Object.createTypeChecker (tsserver.js:33602:9)
    at Object.getTypeChecker (tsserver.js:95574:79)
    at synchronizeHostData (tsserver.js:130606:21)
    at Object.getProgram (tsserver.js:130688:13)
    at InferredProject.Project.updateGraphWorker (tsserver.js:135039:53)
    at InferredProject.Project.updateGraph (tsserver.js:134982:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (tsserver.js:136778:25)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:138156:26)
    at tsserver.js:138358:107
    at Object.mapDefined (tsserver.js:565:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:138358:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139212:46)
    at tsserver.js:140870:88    at IOSession.Session.executeWithRequestId (tsserver.js:140861:28)
    at IOSession.Session.executeCommand (tsserver.js:140870:33)
    at IOSession.Session.onMessage (tsserver.js:140893:35)
    at Interface.<anonymous> (tsserver.js:142208:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
(at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:808:521)


[Extension Host] stack trace: Error: <semantic> TypeScript Server Error (3.7.2)Cannot read property 'exports' of undefinedTypeError: Cannot read property 'exports' of undefined    
    at declareModuleMember (tsserver.js:29333:63)    
    at delayedBindJSDocTypedefTag (tsserver.js:30680:29)    
    at bindSourceFile (tsserver.js:29049:17)    
    at Object.bindSourceFile (tsserver.js:28983:9)    
    at initializeTypeChecker (tsserver.js:64348:20)    
    at Object.createTypeChecker (tsserver.js:33602:9)    
    at Object.getTypeChecker (tsserver.js:95574:79)    
    at synchronizeHostData (tsserver.js:130606:21)    
    at Object.getProgram (tsserver.js:130688:13)    
    at InferredProject.Project.updateGraphWorker (tsserver.js:135039:53)    
    at InferredProject.Project.updateGraph (tsserver.js:134982:42)    
    at ProjectService.assignOrphanScriptInfoToInferredProject (tsserver.js:136778:25)    
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:138156:26)    
    at tsserver.js:138358:107    
    at Object.mapDefined (tsserver.js:565:30)    
    at ProjectService.applyChangesInOpenFiles (tsserver.js:138358:48)    
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139212:46)    
    at tsserver.js:140870:88    
    at IOSession.Session.executeWithRequestId (tsserver.js:140861:28)    
    at IOSession.Session.executeCommand (tsserver.js:140870:33)    
    at IOSession.Session.onMessage (tsserver.js:140893:35)    
    at Interface.<anonymous> (tsserver.js:142208:27)    
    at Interface.emit (events.js:200:13)    
    at Interface._onLine (readline.js:314:10)    
    at Interface._normalWrite (readline.js:459:12)    
    at Socket.ondata (readline.js:170:10)    
    at Socket.emit (events.js:200:13)    
    at addChunk (_stream_readable.js:294:12)    
    at readableAddChunk (_stream_readable.js:275:11)    
    at Socket.Readable.push (_stream_readable.js:210:10)    
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
    at Function.create (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:63732)
    at h.dispatchResponse (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:56670)
    at h.dispatchMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:55568)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:55044
    at l.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47:207)
    at t.Reader.onLengthData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:61946)
    at Socket.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:61594)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
(at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:808:600)
```

All extensions are disabled:
![Screen Shot 2019-11-19 at 10 13 39](https://user-images.githubusercontent.com/1439238/69128565-474fec80-0ab5-11ea-8b7f-676d7ec15533.png)

**Comment by mjbvz** [comment]
Moving upstream to https://github.com/microsoft/TypeScript/issues/35214. Please continue following up on the upstream issue
