### ISSUE TITLE
JS Can not auto import function

### ISSUE THREAD

**Issue by zhangwen9229** [microsoft/vscode#85032]
- VSCode Version: 1.40.1
- OS Version: Mac OS 10.15.1 

Steps to Reproduce:

1.  When I wrote some function which export from other files
2. The function can be sensed, but cannot sense the file path which in.
2. Log Error:
```
[2019-11-18 20:06:33.780] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2019-11-18 20:06:33.780] [exthost] [error] Error: <semantic> TypeScript Server Error (3.6.3)
Debug Failure.
Error: Debug Failure.
    at Object.assertDefined (tsserver.js:2101:24)
    at getDefaultExportInfoWorker (tsserver.js:118907:80)
    at getDefaultLikeExportInfo (tsserver.js:118867:24)
    at tsserver.js:118661:35
    at forEachExternalModule (tsserver.js:119036:21)
    at getAllReExportingModules (tsserver.js:118656:13)
    at Object.getImportCompletionAction (tsserver.js:118642:31)
    at getCompletionEntryCodeActionsAndSourceDisplay (tsserver.js:102585:33)
    at Object.getCompletionEntryDetails (tsserver.js:102549:30)
    at Object.getCompletionEntryDetails (tsserver.js:125564:35)
    at tsserver.js:134771:57
    at Object.mapDefined (tsserver.js:680:30)
    at IOSession.Session.getCompletionEntryDetails (tsserver.js:134769:33)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:133732:61)
    at tsserver.js:135256:88
    at IOSession.Session.executeWithRequestId (tsserver.js:135247:28)
    at IOSession.Session.executeCommand (tsserver.js:135256:33)
    at IOSession.Session.onMessage (tsserver.js:135279:35)
    at Interface.<anonymous> (tsserver.js:136594:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
	at Function.create (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:63732)
	at h.dispatchResponse (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:56670)
	at h.dispatchMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:55568)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:55044
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47:207)
	at t.Reader.onLengthData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:61946)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:61594)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by zhangwen9229** [comment]
I've tried all of these methods.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by zhangwen9229** [comment]
@mjbvz Yes, I use the version 1.40.1 of VS Code which had disabled all extensions.
Last night, I config exclude in jsconfig.json, I found  that after a folder excluded, problem is ok.
If TS Server can ignore the error and not crashed, or tell me which file occurred.

**Comment by zhangwen9229** [comment]
@mjbvz I have found the file which occurred this problem. Because it import a property from a file which didn't have the property. Could we ignore this problem. Because of the folder is a common folder which can be imported by two projects.

**Comment by mjbvz** [comment]
Can you please share some example code that demonstrates the issue?

**Comment by zhangwen9229** [comment]
@mjbvz Thank you for your patience.
For example:
test.js
```
export  {
  API
} from './Local';
```

a.js 
```
import { ABC } from './test.js';
export default ABC.funcTest;
```

In fact, we knew that test.js doesn't have "ABC". In this case, the problem showed up.

**Comment by mjbvz** [comment]
I can't reproduce any errors using the current VS code insiders build (1.41)

Can you please test your example again on the insiders build to confirm you still see the problem.
