### ISSUE TITLE
Javascript/Typescript Language Service Crashes During Git Diff

### ISSUE THREAD

**Issue by cameron-sjo** [microsoft/vscode#85234]
Version: 1.40.1 (system setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open javascript file in Diff view from Source Control Explorer(?) 

Does this issue occur when all extensions are disabled?: No

Output from Typescript Extension:
```
[Info  - 1:38:13 PM] Using tsserver from: c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 1:38:13 PM] <syntax> Forking...
[Info  - 1:38:13 PM] <syntax> Starting...
[Info  - 1:38:13 PM] <semantic> Forking...
[Info  - 1:38:13 PM] <semantic> Starting...
[Info  - 1:38:40 PM] Killing TS Server
[Info  - 1:38:40 PM] TSServer exited
[Info  - 1:38:40 PM] Using tsserver from: c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 1:38:40 PM] <syntax> Forking...
[Info  - 1:38:40 PM] <syntax> Starting...
[Info  - 1:38:40 PM] <semantic> Forking...
[Info  - 1:38:40 PM] <semantic> Starting...
[Info  - 1:38:41 PM] Killing TS Server
[Info  - 1:38:41 PM] TSServer exited
[Info  - 1:38:41 PM] Using tsserver from: c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 1:38:41 PM] <syntax> Forking...
[Info  - 1:38:41 PM] <syntax> Starting...
[Info  - 1:38:41 PM] <semantic> Forking...
[Info  - 1:38:41 PM] <semantic> Starting...
[Info  - 1:38:41 PM] Killing TS Server
[Info  - 1:38:41 PM] TSServer exited
[Info  - 1:38:41 PM] Using tsserver from: c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 1:38:41 PM] <syntax> Forking...
[Info  - 1:38:42 PM] <syntax> Starting...
[Info  - 1:38:42 PM] <semantic> Forking...
[Info  - 1:38:42 PM] <semantic> Starting...
[Info  - 1:38:42 PM] Killing TS Server
[Info  - 1:38:43 PM] TSServer exited
[Info  - 1:38:43 PM] Using tsserver from: c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 1:38:43 PM] <syntax> Forking...
[Info  - 1:38:43 PM] <syntax> Starting...
[Info  - 1:38:43 PM] <semantic> Forking...
[Info  - 1:38:43 PM] <semantic> Starting...
[Info  - 1:38:43 PM] Killing TS Server
[Info  - 1:38:43 PM] TSServer exited
[Info  - 1:38:43 PM] Using tsserver from: c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib
[Info  - 1:38:43 PM] <syntax> Forking...
[Info  - 1:38:43 PM] <syntax> Starting...
[Info  - 1:38:43 PM] <semantic> Forking...
[Info  - 1:38:43 PM] <semantic> Starting...
[Info  - 1:38:44 PM] Killing TS Server
[Info  - 1:38:44 PM] TSServer exited
```

StackTraces from Developer Tools:
```
Error: <syntax> TypeScript Server Error (3.6.3)
Debug Failure. False expression: Script should not exist and not be open already
Error: Debug Failure. False expression: Script should not exist and not be open already
    at ProjectService.applyChangesInOpenFiles (tsserver.js:132793:34)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:133600:46)
    at tsserver.js:135256:88
    at IOSession.Session.executeWithRequestId (tsserver.js:135247:28)
    at IOSession.Session.executeCommand (tsserver.js:135256:33)
    at IOSession.Session.onMessage (tsserver.js:135279:35)
    at Interface.<anonymous> (tsserver.js:136594:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
	at Function.create (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:63732)
	at h.dispatchResponse (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:56670)
	at h.dispatchMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:55568)
	at c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:55044
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at t.Reader.onLengthData (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:61946)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:53:61594)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```
```
[[object Object]]<syntax> TypeScript Server Error (3.6.3)
Debug Failure. False expression: Script should not exist and not be open already
Error: Debug Failure. False expression: Script should not exist and not be open already
    at ProjectService.applyChangesInOpenFiles (tsserver.js:132793:34)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:133600:46)
    at tsserver.js:135256:88
    at IOSession.Session.executeWithRequestId (tsserver.js:135247:28)
    at IOSession.Session.executeCommand (tsserver.js:135256:33)
    at IOSession.Session.onMessage (tsserver.js:135279:35)
    at Interface.<anonymous> (tsserver.js:136594:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by synth3** [comment]
@mjbvz I can confirm that this problem also occurs with the latest VS Code insiders build.

**Comment by mjbvz** [comment]
@synth3 Thanks for checking. Can you please share the server logs from the first crash:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In the output panel, look for the `typescript` section
1. Find the path to the **first** `<semantic>` log printed. It should look something like:

```
[Info  - 21:45:57.438] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20191125T134551/exthost1/vscode.typescript-language-features/tsserver-log-N87iDG/tsserver.log
```

Look through that log file for errors or stack traces near the end. If you can share the log, I can also take a look to see what could be causing this

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by synth3** [comment]
@mjbvz I cannot tell if this issue is still relevant for the _now latest_ version of vscode insiders.

I could offer a log from Friday - but that contains source code. It's nothing special but still internal and I cannot post this public.

If that _old_ log is of any use then let me know how I can send it over to you.

**Comment by GABeech** [comment]
I'm seeing the same issue on the Current non-insiders release (Just updated this morning), and have been seeing it for about a week now. 

For Context, here my debug info: 

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (17.76GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icalendar|af4|1.0.1
jenkins-status|ale|3.1.2
vscode-sqlite|ale|0.8.0
material-icons|Arc|0.2.0
swagger-viewer|Arj|2.2.2
vscode-browser-preview|auc|0.5.9
mermaid-markdown-syntax-highlighting|bpr|1.0.1
vscode-markdownlint|Dav|0.32.0
mustache|daw|1.1.1
xml|Dot|2.5.0
gitlens|eam|10.2.0
tsl-problem-matcher|eam|0.1.0
EditorConfig|Edi|0.14.2
vsc-material-theme|Equ|30.0.0
vscode-mysql|for|0.4.0
angular-cli-task-provider|Gen|1.3.2
vscode-pull-request-github|Git|0.13.0
jenkinsfile-support|ivo|0.4.4
mysql-syntax|jak|1.3.1
jenkins-pipeline-linter-connector|jan|1.2.0
jenkins-declarative-support|jmM|0.1.0
puppet-vscode|jpo|0.21.0
terraform|mau|1.4.0
rainbow-csv|mec|1.3.1
openapi-lint|mer|1.0.4
swagger-doc-viewer|mim|1.0.4
vscode-docker|ms-|0.8.2
mssql|ms-|1.7.1
python|ms-|2019.11.50794
remote-wsl|ms-|0.40.3
csharp|ms-|1.21.8
powershell|ms-|2019.11.0
debugger-for-chrome|msj|4.12.1
highlight-dodgy-characters|nac|1.0.0
vetur|oct|0.22.6
material-icon-theme|PKi|3.9.2
seti-icons|qin|0.1.3
swaggitor|qns|0.1.1
java|red|0.53.1
vscode-xml|red|0.9.1
vscode-yaml|red|0.6.1
jinjahtml|sam|0.11.0
aspnet-helper|sch|0.6.4
vscode-checkstyle|she|1.3.2
vscode-scss-formatter|sib|1.4.2
sc-themes|Syn|1.4.1
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.19.1
vscode-mermaid-preview|vst|1.2.0
markdown-all-in-one|yzh|2.5.1
material-theme|zhu|3.1.2

(3 theme extensions excluded)

</details>


Additionally, I've attached a copy of my typescript server log file. 
[tsserver.log](https://github.com/microsoft/vscode/files/3892792/tsserver.log)

**Comment by mjbvz** [comment]
@synth3 Can you look for the errors in the log and share those?

**Comment by synth3** [comment]
@mjbvz here it is (the request contained sourcecode (`fileContent`) that I have removed):

```log
Info 33833[18:16:11.172] request:
    {"seq":4799,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"c:/somedir/webapps/Module/general/some-project/src/someproject/SomeModule.ts","fileContent":"source code here","projectRootPath":"c:\\somedir\\webapps\\Module\\general\\some-project","scriptKindName":"TS"}]}}
Err 33834 [18:16:11.173] Exception on executing command {"seq":4799,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"c:/somedir/webapps/Module/general/some-project/src/someproject/SomeModule.ts","fileContent":"source code here","projectRootPath":"c:\\somedir\\webapps\\Module\\general\\some-project","scriptKindName":"TS"}]}}:

    Debug Failure. False expression: Script should not exist and not be open already

    Error: Debug Failure. False expression: Script should not exist and not be open already
        at ProjectService.applyChangesInOpenFiles (c:\Users\someUser\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:138371:34)
        at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\someUser\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:139253:46)
        at c:\Users\someUser\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:140911:88
        at IOSession.Session.executeWithRequestId (c:\Users\someUser\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:140902:28)
        at IOSession.Session.executeCommand (c:\Users\someUser\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:140911:33)
        at IOSession.Session.onMessage (c:\Users\someUser\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:140934:35)
        at Interface.<anonymous> (c:\Users\someUser\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:142249:27)
        at Interface.emit (events.js:200:13)
        at Interface._onLine (readline.js:314:10)
        at Interface._normalWrite (readline.js:459:12)
        at Socket.ondata (readline.js:170:10)
        at Socket.emit (events.js:200:13)
        at addChunk (_stream_readable.js:294:12)
        at readableAddChunk (_stream_readable.js:275:11)
        at Socket.Readable.push (_stream_readable.js:210:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
Info 33835[18:16:11.173] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":4799,"success":false,"message":"Error processing request. Debug Failure. False expression: Script should not exist and not be open already\nError: Debug Failure. False expression: Script should not exist and not be open already\n    at ProjectService.applyChangesInOpenFiles (c:\\Users\\someUser\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:138371:34)\n    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\\Users\\someUser\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:139253:46)\n    at c:\\Users\\someUser\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:140911:88\n    at IOSession.Session.executeWithRequestId (c:\\Users\\someUser\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:140902:28)\n    at IOSession.Session.executeCommand (c:\\Users\\someUser\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:140911:33)\n    at IOSession.Session.onMessage (c:\\Users\\someUser\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:140934:35)\n    at Interface.<anonymous> (c:\\Users\\someUser\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:142249:27)\n    at Interface.emit (events.js:200:13)\n    at Interface._onLine (readline.js:314:10)\n    at Interface._normalWrite (readline.js:459:12)\n    at Socket.ondata (readline.js:170:10)\n    at Socket.emit (events.js:200:13)\n    at addChunk (_stream_readable.js:294:12)\n    at readableAddChunk (_stream_readable.js:275:11)\n    at Socket.Readable.push (_stream_readable.js:210:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)"}
```

**Comment by mjbvz** [comment]
@cameron-sjo Can you please test using insiders

@synth3 Are you still seeing this? It may be the same issue as #84826 but I'd need the full logs to confirm that

**Comment by cameron-sjo** [comment]
@mjbvz My apologies, life has been a little crazy for me. I have to 1.40.1 and still having the issue. Installing at the moment, and I'll see if I can still reproduce.

**Comment by mjbvz** [comment]
Thanks for testing. The insiders version (1.41) is what we are mainly interested in as it has all the latest bug fixes, including a few for bugs that could have triggered this problem.  The current insiders will also be released as the stable build sometime next week

Let me know if you see this in the insiders build

**Comment by synth3** [comment]
@mjbvz I did not experience  this issue again in the insiders-versions. Only the crashes described in #83403 still occur.
