### ISSUE TITLE
Javascript in <script> tags crashes "HTML Language Features" extension

### ISSUE THREAD

**Issue by ultraGentle** [microsoft/vscode#85301]
**What happens:**  
1. An error message notification pops up: "Request has failed: HTML language features (extension)"  
2. The bottom drawer pops open with error details (see below)
3. Sometimes I can continue working; other times, basic editor features no longer function, requiring restarting VSCode.  
4. However, once the error begins happening, it often keeps happening every few seconds, each time popping open the bottom drawer, again necessitating restart.  
5. For more details, please see the error output below.  

**Under what circumstances?**  
While editing javascript within the `<script>` tags in a mixed JS/CSS/HTML document.  Specifically, I've noticed it happens when I pause for a moment while typing, so the JS doesn't make sense yet.  For instance, writing `if (condition) {...}`, if I haven't written the condition yet -- BUT, un/fortunately the error doesn't occur in 100% of such instances.  

**How frequently?**  
Multiple times a day.  Usually not right away.   
But as noted above, once it begins, there's a 50/50 chance it will keep happening every few seconds, requiring restart.  

**When did it start?**   
Began 2-4 weeks ago. 

**Does it happen without extensions enabled?** 
I wish I could answer this right now, but it usually doesn't begin until a while into a session, and I rely on extensions to work, so I'm not sure how best to test that.  

**Version info**  
OS X 10.13.6
VSCode Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0

**Error details**  
`[Error - 12:06:12 PM] Error while resolving completion proposal: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isCaseClause'.
Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isCaseClause'.
    at Object.cast (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:1445:25)
    at getContextualType (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:102990:50)
    at getCompletionData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:103240:51)
    at getSymbolCompletionFromEntryId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:102844:34)
    at Object.getCompletionEntryDetails (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:102884:36)
    at Object.getCompletionEntryDetails (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:125916:35)
    at Object.doResolve (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain.js:1:541001)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain.js:1:491955
    at Immediate._onImmediate (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/htmlServerMain.js:1:548528)
    at processImmediate (internal/timers.js:439:21)
`

**Installed extensions**  (not all of these are enabled, but I didn't see a way to filter for that):
2gua.rainbow-brackets
albert.TabOut
albymor.increment-selection
Anjali.clipboard-history
arthurwhite.white
Atishay-Jain.All-Autocomplete
benjavr.jshintrc-generator
bierner.comment-tagged-templates
cdes.wrap-with-template-string
chunsen.bracket-select
closedcontour.very-smart-select
cmstead.jsrefactor
CoenraadS.bracket-pair-colorizer-2
dbaeumer.jshint
dbaeumer.vscode-eslint
donjayamanne.githistory
eamodio.gitlens
ecmel.vscode-html-css
eg2.tslint
esbenp.prettier-vscode
formulahendry.auto-rename-tag
formulahendry.code-runner
fosshaas.fontsize-shortcuts
gebilaoxiong.vscode-flatland-icon-theme
gerane.Theme-Github
Gruntfuggly.activitusbar
Gruntfuggly.scoper
Gruntfuggly.todo-tree
Gruntfuggly.ubertab
gtwsky.oolory
HookyQR.minify
huizhou.githd
ispushkin.pushkin-is-white-theme
jasonlhy.vscode-browser-sync
jeremyrajan.browsersync
josee9988.minifyall
letrieu.expand-region
lukapetrovic.image-resizer
mhutchie.git-graph
morissonmaciel.typescript-auto-compiler
mrmlnc.vscode-autoprefixer
ms-vscode.vscode-typescript-tslint-plugin
msjsdiag.debugger-for-chrome
olback.es6-css-minify
ow.vscode-subword-navigation
plibither8.remove-comments
pranaygp.vscode-css-peek
pustelto.bracketeer
ritwickdey.LiveServer
ryu1kn.partial-diff
ryuta46.multi-command
sashaweiss.bracket-jumper
saviorisdead.Theme-GitHubCleanWhite
Shan.code-settings-sync
SirTori.indenticator
sohamkamani.code-eol
sporiley.css-auto-prefix
streetsidesoftware.code-spell-checker
thomaspink.theme-github
toba.vsfire
usernamehw.errorlens
v4run.transpose
vincaslt.highlight-matching-tag
VisualStudioExptTeam.vscodeintellicode
vittorioromeo.expand-selection-to-scope
vmsynkov.colonize
WallabyJs.quokka-vscode
webreflection.literally-html
xyz.local-history
yuichinukiyama.vscode-preview-server

**Comment by ultraGentle** [comment]
Update: I've working with extensions disabled today, and I am not experiencing the problem.  

I suspect (but am not sure) that the problem extension might be "ErrorLens" (usernamehw.errorlens), because I believe it's the only one I installed around the time the problem started happening.
