### ISSUE TITLE
Launcher[1] disconnected unexpectedly

### ISSUE THREAD

**Issue by stanpcf** [microsoft/vscode#85318]
- VSCode Version:
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0
- OS Version(Local):
ProductName:	Mac OS X
ProductVersion:	10.15
BuildVersion:	19A602
- OS Version(remote):
Linux version 3.10.0-693.el7.x86_64
Steps to Reproduce:
1. press F5 to debug, will show below error.
![image](https://user-images.githubusercontent.com/13925796/69359649-f235f580-0cc3-11ea-9230-e94b0c642123.png)
2. python version
2.7.5
3. launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "cwd": "${workspaceFolder}/demo/guide-python",
            "console": "integratedTerminal"
        }
    ]
}
```
4. error
```
(.env) [@nmyjs.176.98 xgboost_new]# env PTVSD_SESSION_ID=1 PTVSD_LAUNCHER_PORT=39878 /search/odin/pcf/tools/.env/bin/python /root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher /search/odin/pcf/tools/xgboost_new/demo/guide-python/cross_validation.py 
E+00000.010: /handling #1 request "launch" from Adapter-1/
             Handler 'launch_request' (file u'/root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher/../../ptvsd/launcher/adapter.py', line 35)
             couldn't handle #1 request "launch" from Adapter-1:
             
             Traceback (most recent call last):
               File "/root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher/../../ptvsd/common/messaging.py", line 763, in _handle
                 result = handler(self)
               File "/root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher/../../ptvsd/launcher/adapter.py", line 147, in launch_request
                 debuggee.spawn(process_name, cmdline, cwd, env, redirect_output)
               File "/root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher/../../ptvsd/launcher/debuggee.py", line 76, in spawn
                 "pointerSize": struct.calcsize("P") * 8,
             TypeError: Struct() argument 1 must be string, not unicode
             
             Stack where logged:
               File "/usr/lib64/python2.7/threading.py", line 785, in __bootstrap
                 self.__bootstrap_inner()
               File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
                 self.run()
               File "/usr/lib64/python2.7/threading.py", line 765, in run
                 self.__target(*self.__args, **self.__kwargs)
               File "/root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher/../../ptvsd/common/messaging.py", line 1520, in _run_handlers
                 handler()
               File "/root/.vscode-server/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher/../../ptvsd/common/messaging.py", line 809, in _handle
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by egamma** [comment]
Please file the issue against the python extension.

**Comment by toutiay** [comment]
@egamma Is this problem solved? What should I do?
