### ISSUE TITLE
Smoke Test: debug smoke tests failed

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#85378]
1) Running Code
       Debug
         breakpoints:
     Error: Timeout: get element '.codicon-debug-breakpoint' after 20 seconds.
      at /home/dirkb/Projects/mseng/VSCode/vscode/test/automation/out/code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/dirkb/Projects/mseng/VSCode/vscode/test/automation/out/code.js:8:58)

  2) Running Code
       Debug
         stepOver, stepIn, stepOut:
     Error: Timeout: get elements 'div[id="workbench.view.debug"] .monaco-list-row .stack-frame' after 20 seconds.
      at /home/dirkb/Projects/mseng/VSCode/vscode/test/automation/out/code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/dirkb/Projects/mseng/VSCode/vscode/test/automation/out/code.js:8:58)

**Comment by isidorn** [comment]
I have moved the debug smoke test to integration tests.
Thus this is no longer valid.
The integration tests do not behave flaky so far.
