### ISSUE TITLE
E+00000.176: /handling #1 request "launch" from Adapter-1/

### ISSUE THREAD

**Issue by toutiay** [microsoft/vscode#85526]
PS E:\kuaishou_dd\dev\tools\publishConfig> & 'C:\Python27\python.exe' 'c:\Users\win 10\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\new_ptvsd\no_wheels\ptvsd\launcher' 'e:\kuaishou_dd\dev\tools\publishConfig\commit\publish.py'
E+00000.176: /handling #1 request "launch" from Adapter-1/
             Handler 'launch_request' (file u'c:\\Users\\win 10\\.vscode\\extensions\\ms-python.python-2019.11.50794\\pythonFiles\\lib\\python\\new_ptvsd\\no_wheels\\ptvsd\\launcher/../../ptvsd\\launcher\\adapter.py', line 35)
             couldn't handle #1 request "launch" from Adapter-1:

             Traceback (most recent call last):
               File "c:\Users\win 10\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\new_ptvsd\no_wheels\ptvsd\launcher/../../ptvsd\common\messaging.py", line 763, in _handle
                 result = handler(self)
               File "c:\Users\win 10\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\new_ptvsd\no_wheels\ptvsd\launcher/../../ptvsd\launcher\adapter.py", line 147, in launch_request
                 debuggee.spawn(process_name, cmdline, cwd, env, redirect_output)
               File "c:\Users\win 10\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\new_ptvsd\no_wheels\ptvsd\launcher/../../ptvsd\launcher\debuggee.py", line 64, in spawn                 "Couldn't spawn debuggee: {0}\n\nCommand line:{1!r}", exc, cmdline
             TypeError: unbound method cant_handle() must be called with Message instance as first argument (got unicode instance instead)

             Stack where logged:
               File "C:\Python27\lib\threading.py", line 774, in __bootstrap
                 self.__bootstrap_inner()
               File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
                 self.run()
               File "C:\Python27\lib\threading.py", line 754, in run
                 self.__target(*self.__args, **self.__kwargs)
               File "c:\Users\win 10\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\new_ptvsd\no_wheels\ptvsd\launcher/../../ptvsd\common\messaging.py", line 1520, in _run_handlers
                 handler()
               File "c:\Users\win 10\.vscode\extensions\ms-python.python-2019.11.50794\pythonFiles\lib\python\new_ptvsd\no_wheels\ptvsd\launcher/../../ptvsd\common\messaging.py", line 809, in _handle
                 self.describe(),

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
After updating the vscode one time, debugging the python file error.
No related error messages can be found online.

**Comment by toutiay** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Launcher[1] disconnected unexpectedly (#85318)](https://www.github.com/microsoft/vscode/issues/85318)

This problem has not been solved, what should I do?

**Comment by egamma** [comment]
Please file the issue against the python extension with detailed steps for how to reproduce the problem. The current steps are not sufficient.
