### ISSUE TITLE
navigation@<number> causes ERR Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#85671]
Version: 1.41.0-insider
Commit: 615732feae7228502eab60919d67837f7a625e7c
Date: 2019-11-27T05:36:11.009Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Reproducing #85576.

Steps to Reproduce:

1. Add the following to `package.json` in [hello-world-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-sample). This [doc](https://code.visualstudio.com/api/references/contribution-points#Sorting-inside-groups) is on `@<number>`

```diff
diff --git a/helloworld-sample/package.json b/helloworld-sample/package.json
index 3c5d17f..0552c87 100644
--- a/helloworld-sample/package.json
+++ b/helloworld-sample/package.json
@@ -21,7 +21,16 @@
                                "command": "extension.helloWorld",
                                "title": "Hello World"
                        }
-               ]
+               ],
+               "menus": {
+                       "editor/context": [
+                         {
+                               "command": "extension.helloWorld",
+                               "group": "navigation@100"
+                         }
+                       ]
+               }
+
        },
        "scripts": {
                "vscode:prepublish": "npm run compile",
```

2. Execute the sample.
3. Open a new file and right-click.

```
  ERR Cannot read property 'title' of undefined: TypeError: Cannot read property 'title' of undefined
    at _compareMenuItems (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1707:336)
    at Array.sort (<anonymous>)
    at e._build (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1706:144)
    at new e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:658)
    at createMenu (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:361)
    at e._getMenuActions (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1813:213)
    at e.showContextMenu (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1813:77)
    at e._onContextMenu (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1812:915)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1811:927
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:114:740)
    at s.n.onContextMenu (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2141:461)
    at s.emitContextMenu (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2021:595)
    at t.ViewController.emitContextMenu (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1785:869)
    at g._onContextMenu (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2006:1006)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2005:257
    at HTMLDivElement.<anonymous> (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:554:273)
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Thanks for the logs and repo steps 👏
