### ISSUE TITLE
Unable to search Marketplace

### ISSUE THREAD

**Issue by habovh** [microsoft/vscode#85684]
- VSCode Version: 1.40.2
- OS Version: macOS 10.15.1

I can't search for extensions from within VSCode. Note that the "Recommended" extensions section is populated when the search input is empty, and that I can access marketplace extensions in VSCode if I opened them from my web browser.

It might be related to #85402 but I'm not sure, since I'm not having the same output and behaviour.
#81814 might be a possible duplicate, but again the debug log is not the same.

Steps to Reproduce:

1. Open VSCode
2. Search for extensions
3. See "No extensions found." no matter what the query is

### Console output

```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4286 Overwriting grammar scope name to file mapping for scope source.ruby.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/ruby/syntaxes/ruby.tmLanguage.json.
New grammar file: file:///Users/jordanbecker/.vscode/extensions/wingrunr21.vscode-ruby-0.26.0/syntaxes/ruby.cson.json
register @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4286
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1541   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
log.ts:196   ERR view descriptor extensions.recommendedList not found: Error: view descriptor extensions.recommendedList not found
    at e.find (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5023:441)
    at e.setCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5022:254)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5063:867
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:115:286)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:110:965
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:115:286)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:110:819
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:115:286)
    at t.DefaultRecommendedExtensionsView.set headerVisible [as headerVisible] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:533:763)
    at re.updateViewHeaders (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5040:636)
    at removePanels (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5039:730)
    at re.onDidRemoveViews (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5064:279)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5061:622
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:115:286)
    at e.onDidChangeViewDescriptors (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5025:29)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5021:326
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:115:286)
    at y.onContextChanged (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5020:633)
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:115:306)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:110:965
    at t.PauseableEmitter.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:115:286)
    at t.PauseableEmitter.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:116:69)
    at _.setContext (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1696:580)
    at m.set (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1695:35)
    at re.doSearch (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5979:541)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5978:184
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:145:398
extensionsViews.ts:254 Error querying extensions gallery Canceled
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by AlbertWhite** [comment]
@habovh I also had this problem and does not find a direct solution yet. By the way we can install extensions with command line https://code.visualstudio.com/docs/editor/extension-gallery#_command-line-extension-management Hope it helps.
