### ISSUE TITLE
code . return error after last update - errno: -4071

### ISSUE THREAD

**Issue by clemabd** [microsoft/vscode#85728]
Hi, 

I updated my VS Code from 1.37 to 

Version: 1.40.2 (system setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

I use WSL and I enter `code .` to open a VS code on each service I work with. 

Since the last update, code . return : 
````
net.js:282
    err = this._handle.open(fd);
                       ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:282:24)
    at createWritableStdioStream (internal/process/stdio.js:179:18)
    at process.getStdout [as stdout] (internal/process/stdio.js:28:14)
    at Object.<anonymous> (C:\Program Files\Microsoft VS Code\resources\electron.asar\browser\init.js:43:13)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:850:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'uv_pipe_open'
}
```

I will revert to a previous version for the moment
Have a nice day

**Comment by sgehrman** [comment]
same issue.  I'm on Linux
