### ISSUE TITLE
Can't Save Any File

### ISSUE THREAD

**Issue by haurand** [microsoft/vscode#85723]
Issue Type: <b>Bug</b>

Unable to save any files. 

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (5.89GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-anchors|Exo|1.6.1
comment-labels|jam|0.1.0
prettify-json|moh|0.0.3
vetur|oct|0.22.6
commentbars|zfz|0.0.10

(1 theme extensions excluded)

</details>

**Comment by whizsid** [comment]
What is the error message are you getting?

**Comment by sandy081** [comment]
Are you able to repro by disabling all extensions.

**Comment by chenxiaoyao6228** [comment]
Got the same issue

## had tried the following 
* deleted file and recreate
* disabled all extensions and reload

## error message showed in devtools console
```bash
mainThreadExtensionService.ts:65 [[object Object]]Cannot read property 'trim' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'trim' of undefined
	at GitService.<anonymous> (c:\Users\Allen\.vscode\extensions\huizhou.githd-2.1.0\out\src\gitService.js:369:35)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\Allen\.vscode\extensions\huizhou.githd-2.1.0\out\src\gitService.js:4:58)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:66
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] 2019-11-30T12:29:17.437Z - debug: [ImportOrganizer] OrganizeOnSave is deactivated through config
log.ts:196   ERR doSave(43) - exit - resulted in a save error: Error: Unable to write file (Error: File Modified Since) h {scheme: "file", authority: "", path: "/c:/Users/Allen/Desktop/blog/packages/facade/src/hook.js", query: "", fragment: "", …}
notificationsAlerts.ts:40 Failed to save 'hook.js': The content of the file is newer. Please compare your version with the file contents.
onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:580
addNotification @ notifications.ts:171
notify @ notificationService.ts:101
onSaveError @ saveErrorHandler.ts:179
onSaveError @ textFileEditorModel.ts:903
(anonymous) @ textFileEditorModel.ts:763
Promise.then (async)
(anonymous) @ textFileEditorModel.ts:720
processTicksAndRejections @ internal/process/task_queues.js:89
Promise.then (async)
doSave @ textFileEditorModel.ts:672
save @ textFileEditorModel.ts:600
(anonymous) @ textFileService.ts:741
doSaveAllFiles @ textFileService.ts:740
doSaveAll @ textFileService.ts:621
saveAll @ textFileService.ts:615
save @ textFileService.ts:563
(anonymous) @ fileCommands.ts:207
B @ fileCommands.ts:127
handler @ fileCommands.ts:515
invokeFunction @ instantiationService.ts:67
_tryExecuteCommand @ commandService.ts:84
(anonymous) @ commandService.ts:73
Promise.then (async)
executeCommand @ commandService.ts:73
_doDispatch @ abstractKeybindingService.ts:195
_dispatch @ abstractKeybindingService.ts:154
(anonymous) @ keybindingService.ts:222
extensionsViews.ts:254 Error querying extensions gallery Error
(anonymous) @ extensionsViews.ts:254
Promise.then (async)
query @ extensionsViews.ts:253
(anonymous) @ extensionsViews.ts:202
a @ async.ts:23
show @ extensionsViews.ts:202
show @ extensionsViews.ts:936
(anonymous) @ extensionsViewlet.ts:538
onDidAddViews @ extensionsViewlet.ts:537
(anonymous) @ viewsViewlet.ts:81
fire @ event.ts:580
onDidChangeViewDescriptors @ views.ts:470
(anonymous) @ views.ts:252
fire @ event.ts:580
onContextChanged @ views.ts:197
fire @ event.ts:582
(anonymous) @ event.ts:73
fire @ event.ts:580
fire @ event.ts:644
setContext @ contextKeyService.ts:296
set @ contextKeyService.ts:180
doSearch @ extensionsViewlet.ts:527
(anonymous) @ extensionsViewlet.ts:499
(anonymous) @ async.ts:211
Promise.then (async)
trigger @ async.ts:205
triggerSearch @ extensionsViewlet.ts:499
(anonymous) @ extensionsViewlet.ts:417
fire @ event.ts:582
(anonymous) @ suggestEnabledInput.ts:171
(anonymous) @ textModel.ts:236
fire @ event.ts:580
endDeferredEmit @ textModel.ts:3051
pushEditOperations @ textModel.ts:1144
_innerExecuteCommands @ cursor.ts:906
executeCommands @ cursor.ts:864
_executeEditOperation @ cursor.ts:494
_externalExecuteCommands @ cursor.ts:829
trigger @ cursor.ts:752
executeCommands @ codeEditorWidget.ts:1031
runCoreEditingCommand @ coreCommands.ts:1633
runEditorCommand @ coreCommands.ts:1541
(anonymous) @ editorExtensions.ts:176
invokeFunction @ instantiationService.ts:67
invokeWithinContext @ codeEditorWidget.ts:362
runCommand @ editorExtensions.ts:169
handler @ editorExtensions.ts:101
invokeFunction @ instantiationService.ts:67
_tryExecuteCommand @ commandService.ts:84
(anonymous) @ commandService.ts:73
Promise.then (async)
executeCommand @ commandService.ts:73
_doDispatch @ abstractKeybindingService.ts:195
_dispatch @ abstractKeybindingService.ts:154
(anonymous) @ keybindingService.ts:222
request.ts:40 POST https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery net::ERR_CONNECTION_CLOSED
```

## more info
Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by sandy081** [comment]
>  (c:\Users\Allen\.vscode\extensions\huizhou.githd-2.1.0\out\src\gitService.js:369:35)
	at Generator.next (<anonymous>)

I see extension `huizhou.githd` still enabled. I see this is coming from this extension. Please files the issue against it.
