### ISSUE TITLE
Extension tests 

### ISSUE THREAD

**Issue by mpminardi** [microsoft/vscode#85779]
I have come across an issue with an extension I am working on where the extension tests seem to be launching my webpacked extension from `dist` which causes intermittent failures due to commands being registered twice in classes that are supposed to be singletons among other things.

This has started happening after changing activation events to the following:
`	"activationEvents": [
		"*"
	]`
(e.g., activating my extension on startup of VSCode). 

If the `dist` folder **does not** exist, then my tests work as expected but produce a stacktrace similar to:

```
Activating extension `vscode-samples.webpack-sample` failed:  Cannot find module '/Users/minardi/vscode-extension-samples/webpack-sample/dist/extension'
Require stack:
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
Here is the error stack:  Error: Cannot find module '/Users/minardi/vscode-extension-samples/webpack-sample/dist/extension'
Require stack:
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
	at Function._resolveFilename (internal/modules/cjs/loader.js:627:15)
	at Function.<anonymous> (internal/modules/cjs/loader.js:531:27)
	at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:796:852)
	at Function.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:765:302)
	at Function._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:761:870)
	at Module.require (internal/modules/cjs/loader.js:685:19)
	at require (internal/modules/cjs/helpers.js:16:16)
	at Function.s [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:32:963)
	at d._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:766:484)
	at d._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:677:300)
	at d._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:676:360)
	at Object.actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:674:296)
	at Object._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:506:21)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:505:632
	at Array.map (<anonymous>)
	at Object._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:505:620)
	at Object.activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:503:413)
	at d._activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:675:24)
	at d._handleEagerExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:678:800)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:682:215

  Dummy Suite
    ✓ Dummy Test
  1 passing (26ms)

```

which again seems to imply that the extension from `dist` is being loaded at some point. I also added `--disable-extensions` to the launch.json as a sanity measure and that seems to have no effect.

I would expect that the extension from the `dist` folder is not activated in this way and that the source from `out/test/` is used instead. 

I have forked the webpack example extension and added logic which will demonstrate this behaviour (at https://github.com/mpminardi/vscode-extension-samples/tree/activation-bug)

**Version Information:**

- VSCode Version: Version: 1.40.2 Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
- OS Version: Mac OS X 10.14.6

**Steps to Reproduce:**

1. Clone and checkout https://github.com/mpminardi/vscode-extension-samples/tree/activation-bug
2. Run extension tests through the IDE without a `dist` folder
3. Observe the stack trace which shows that VSCode is attempting to activate the extension from `dist`

**Comment by alexandrudima** [comment]
When we launch the launch config "Extension Tests", it will invoke VS Code with the argument `--extensionTestsPath=${workspaceFolder}/out/test`. This comes from  https://github.com/mpminardi/vscode-extension-samples/commit/e93ef583da6b76405533743414c12f3e0e6154b8#diff-75b3f59d0012145b7219d971d67b339bR26

VS Code will then load and run `/out/test/index.js`. That file will use as `testsRoot` the path `/out/` (defined at https://github.com/mpminardi/vscode-extension-samples/commit/e93ef583da6b76405533743414c12f3e0e6154b8#diff-978f82f90891ceea49219da62c1401a2R12), so it will look for tests under `/out/**/**.test.js`. So far so good, because tests are not part of the bundled output, so loading them from `/out/` makes sense.

But those tests are written to load code relative to them, so they will end up loading `/out/math.js`.

Finally, VS Code must load the extension because it is `*` activated and that is part of the contract of running tests -- the extension must be loaded and activated as necessary. But VS Code will respect the path described in `package.json`'s `main` field, which is `"./dist/extension"`.

@jrieken I think this is a problem specific to this sample, our built-in extensions don't have the `main` field pointing to `/dist`, it must be a build step which massages it...

**Comment by billchenxi** [comment]
I am running the sample extension from VS Code on MacOS, I have a similar issue, and I don't know what I need to do:
```
Activating extension 'undefined_publisher.medium' failed: Cannot find module '/Users/bill/Documents/GitHub/medium/out/extension.js' Require stack: - /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js.
```

**Comment by billchenxi** [comment]
My suggestion reinstall npm and node: https://stackoverflow.com/questions/44363066/error-cannot-find-module-lib-utils-unsupported-js-while-using-ionic

**Comment by frenya** [comment]
I am using a workaround described here https://github.com/microsoft/vscode-docs/issues/3632

It uses a global `json` tool to modify `package.json` just for the execution of unit tests.

**Comment by steadman1** [comment]
a fresh install of node.js and vscode solved the issue for me

**Comment by timvahlbrock** [comment]
This seems to be somewhat stale, but the problem persists. I assumed that this might be resolved by removing the `extensionDevelopmentPath` param from the launch configuration, so that VSCode will no longer load the extension from source. But VSCode will then fail to launch with the following notification.
![image](https://user-images.githubusercontent.com/25803754/230308253-4058f822-7555-463c-82bd-e7454d8ea909.png)
Clicking continue does have no effect. I assumed that this would be because the extension development host would then not be opened, so I gave a quick shot at fixing this by adding the following statement in the VSCode Source at https://github.com/microsoft/vscode/blob/1379f0375440df946adc62f7afb8375dd45d5adf/src/vs/platform/launch/electron-main/launchMainService.ts#L130

```
else if(!!args.extensionTestsPath) {
  await this.windowsMainService.open(baseConfig);
}
```

This didn't help, but I think providing the possibility to have `extensionTestsPath` without `extensionDevelopmentPath` in the launch configuration might be a viable solution to this problem.
