### ISSUE TITLE
vscode shows `any` for types that are not any

### ISSUE THREAD

**Issue by hayes** [microsoft/vscode#85961]
- VSCode Version: 1.40.2 (also tried 1.39 and insider) 
- OS Version: OSX 10.15.1

Steps to Reproduce: Unfortunately I have not yet been able to repo in an isolated test case.  It seems to be related to something in our private code base.

Does this issue occur when all extensions are disabled?: Yes

Basically, what we observe is that sometimes types in vscode are displayed as any when they should be some other type. This has been happening more frequently as our project has grown, and now happens often enough that developing in this code base is becoming quite painful.  It does not appear to be deterministic, and restarting vscode will often resolve these issues.   I am not sure if there is some timeout behavior that is causing this (I have not been able to find anything any documentation for this). 

<img width="375" alt="Screen Shot 2019-12-02 at 11 58 21 AM" src="https://user-images.githubusercontent.com/816527/69991187-18e20080-14fc-11ea-9931-65b3aa3cfa47.png">
<img width="998" alt="Screen Shot 2019-12-02 at 11 58 28 AM" src="https://user-images.githubusercontent.com/816527/69991196-1bdcf100-14fc-11ea-877e-8cbf74d5018b.png">

The above images show that the field function is displayed as any, but one of the properties of the first arguments has a type error.  This arg does not have any explicit types, and is inferred from the function that is reported as any in vscode.

**Comment by mjbvz** [comment]
Please share a minimal, reproducible example. Unfortunately we can't investigate this without one

**Comment by mjbvz** [comment]
One other thing to check: run the `Developer: Toggle developer tools` command in VS Code and look in the developer console. Are there any typescript related errors printed in there?

**Comment by hayes** [comment]
Good call on checking dev tools, it looks like there was an error:

```
ERR <semantic> TypeScript Server Error (3.7.2)
this.fileExistsWithCache is not a function
TypeError: this.fileExistsWithCache is not a function
    at Object.Project.fileExists (tsserver.js:134568:29)
    at Object.ConfiguredProject.fileExists (tsserver.js:135681:49)
    at tryGetModuleNameAsNodeModule (tsserver.js:99470:43)
    at tsserver.js:99306:88
    at Object.mapDefined (tsserver.js:565:30)
    at Object.getModuleSpecifiers (tsserver.js:99306:29)
    at getSpecifierForModuleSymbol (tsserver.js:37087:62)
    at tsserver.js:36953:39
    at Array.map (<anonymous>)
    at getSymbolChain (tsserver.js:36951:58)
    at lookupSymbolChainWorker (tsserver.js:36935:52)
    at lookupSymbolChain (tsserver.js:36928:24)
    at symbolToTypeNode (tsserver.js:37094:29)
    at typeReferenceToTypeNode (tsserver.js:36594:40)
    at typeToTypeNodeHelper (tsserver.js:36328:95)
    at addPropertyToElementList (tsserver.js:36741:59)
    at createTypeNodesFromResolvedType (tsserver.js:36687:25)
    at createTypeNodeFromObjectType (tsserver.js:36517:35)
    at visitAndTransformType (tsserver.js:36487:34)
    at createAnonymousTypeNode (tsserver.js:36442:36)
    at typeToTypeNodeHelper (tsserver.js:36367:28)
    at symbolToParameterDeclaration (tsserver.js:36884:41)
    at tsserver.js:36829:101
    at Array.map (<anonymous>)
    at signatureToSignatureDeclarationHelper (tsserver.js:36829:67)
    at createTypeNodeFromObjectType (tsserver.js:36506:49)
    at createAnonymousTypeNode (tsserver.js:36447:32)
    at typeToTypeNodeHelper (tsserver.js:36367:28)
    at addPropertyToElementList (tsserver.js:36741:59)
    at createTypeNodesFromResolvedType (tsserver.js:36687:25)
    at createTypeNodeFromObjectType (tsserver.js:36517:35)
    at createAnonymousTypeNode (tsserver.js:36447:32)
    at typeToTypeNodeHelper (tsserver.js:36367:28)
    at tsserver.js:36156:106
    at withContext (tsserver.js:36201:37)
    at Object.typeToTypeNode (tsserver.js:36156:28)
    at Object.getTypeNodeIfAccessible (tsserver.js:104180:27)
    at annotate (tsserver.js:121297:31)
    at annotateParameters (tsserver.js:121252:25)
    at doChange (tsserver.js:121201:25)
    at tsserver.js:121102:109
    at Function.ChangeTracker.with (tsserver.js:119320:17)
    at Object.getCodeActions (tsserver.js:121102:64)
    at tsserver.js:120361:121
    at Object.flatMap (tsserver.js:468:25)
    at Object.getFixes (tsserver.js:120361:23)
    at tsserver.js:131044:35
    at Object.flatMap (tsserver.js:468:25)
    at Object.getCodeFixesAtPosition (tsserver.js:131042:23)
    at IOSession.Session.getCodeFixes (tsserver.js:140677:64)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139462:61)
    at tsserver.js:140870:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140861:28)
    at IOSession.Session.executeCommand (tsserver.js:140870:33)
    at IOSession.Session.onMessage (tsserver.js:140893:35)
    at Interface.<anonymous> (tsserver.js:142208:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17): Error: <semantic> TypeScript Server Error (3.7.2)
this.fileExistsWithCache is not a function
TypeError: this.fileExistsWithCache is not a function
    at Object.Project.fileExists (tsserver.js:134568:29)
    at Object.ConfiguredProject.fileExists (tsserver.js:135681:49)
    at tryGetModuleNameAsNodeModule (tsserver.js:99470:43)
    at tsserver.js:99306:88
    at Object.mapDefined (tsserver.js:565:30)
    at Object.getModuleSpecifiers (tsserver.js:99306:29)
    at getSpecifierForModuleSymbol (tsserver.js:37087:62)
    at tsserver.js:36953:39
    at Array.map (<anonymous>)
    at getSymbolChain (tsserver.js:36951:58)
    at lookupSymbolChainWorker (tsserver.js:36935:52)
    at lookupSymbolChain (tsserver.js:36928:24)
    at symbolToTypeNode (tsserver.js:37094:29)
    at typeReferenceToTypeNode (tsserver.js:36594:40)
    at typeToTypeNodeHelper (tsserver.js:36328:95)
    at addPropertyToElementList (tsserver.js:36741:59)
    at createTypeNodesFromResolvedType (tsserver.js:36687:25)
    at createTypeNodeFromObjectType (tsserver.js:36517:35)
    at visitAndTransformType (tsserver.js:36487:34)
    at createAnonymousTypeNode (tsserver.js:36442:36)
    at typeToTypeNodeHelper (tsserver.js:36367:28)
    at symbolToParameterDeclaration (tsserver.js:36884:41)
    at tsserver.js:36829:101
    at Array.map (<anonymous>)
    at signatureToSignatureDeclarationHelper (tsserver.js:36829:67)
    at createTypeNodeFromObjectType (tsserver.js:36506:49)
    at createAnonymousTypeNode (tsserver.js:36447:32)
    at typeToTypeNodeHelper (tsserver.js:36367:28)
    at addPropertyToElementList (tsserver.js:36741:59)
    at createTypeNodesFromResolvedType (tsserver.js:36687:25)
    at createTypeNodeFromObjectType (tsserver.js:36517:35)
    at createAnonymousTypeNode (tsserver.js:36447:32)
    at typeToTypeNodeHelper (tsserver.js:36367:28)
    at tsserver.js:36156:106
    at withContext (tsserver.js:36201:37)
    at Object.typeToTypeNode (tsserver.js:36156:28)
    at Object.getTypeNodeIfAccessible (tsserver.js:104180:27)
    at annotate (tsserver.js:121297:31)
    at annotateParameters (tsserver.js:121252:25)
    at doChange (tsserver.js:121201:25)
    at tsserver.js:121102:109
    at Function.ChangeTracker.with (tsserver.js:119320:17)
    at Object.getCodeActions (tsserver.js:121102:64)
    at tsserver.js:120361:121
    at Object.flatMap (tsserver.js:468:25)
    at Object.getFixes (tsserver.js:120361:23)
    at tsserver.js:131044:35
    at Object.flatMap (tsserver.js:468:25)
    at Object.getCodeFixesAtPosition (tsserver.js:131042:23)
    at IOSession.Session.getCodeFixes (tsserver.js:140677:64)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139462:61)
    at tsserver.js:140870:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140861:28)
    at IOSession.Session.executeCommand (tsserver.js:140870:33)
    at IOSession.Session.onMessage (tsserver.js:140893:35)
    at Interface.<anonymous> (tsserver.js:142208:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
	at Function.create (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:63732)
	at h.dispatchResponse (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:56670)
	at h.dispatchMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:55568)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:55044
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47:207)
	at t.Reader.onLengthData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:61946)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:53:61594)
	at Socket.emit (events.js:200:13)
	at Socket.EventEmitter.emit (domain.js:471:20)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
```

**Comment by hayes** [comment]
So far I have not been able to create a repo, spent some time on it, but have not found a small subset of our code base that exhibits the same behavior.  But I may have some more time to get a smaller repo next week.

**Comment by hayes** [comment]
I am not sure the above error is related, reloading the editor, I don't see the same error, but I do still see that same behavior.  I'll update here if I find out anything else.

**Comment by mjbvz** [comment]
Same stack trace as https://github.com/microsoft/TypeScript/issues/35035 but I'm not sure it would cause this issue
