### ISSUE TITLE
Breaking with workspace TS version 3.7.2

### ISSUE THREAD

**Issue by jpike88** [microsoft/vscode#85999]
- VSCode Version: 1.40.2
- OS Version: macOS Catalina

Steps to Reproduce:

1. Have the tslint extension installed.
2. use workspace version of typescript.

![Screen Shot 2019-12-03 at 11 57 01 am](https://user-images.githubusercontent.com/9585787/70021822-94a78000-15c4-11ea-94da-9d6b88d9a795.png)

3. No linting. It's broken.
4. It works if I select 'use vscode version' even though it's the same TS version

**Comment by mjbvz** [comment]
Are you sure that this regressed between 1.40.1 and 1.40.2 and that nothing else about your setup has changed? No extension updates or new tslint versions?

Here are the VS Code changes: https://github.com/microsoft/vscode/compare/1.40.1...1.40.2

**Comment by jpike88** [comment]
almost positive, I saw my developer upgrade right next to me and the issue broke immediately on update

**Comment by jpike88** [comment]
I should add I already had this problem on 1.40.2, so watching him upgrade was to confirm my suspicion

**Comment by mjbvz** [comment]
And they were definitely on 1.40.1, and not 1.39?

**Comment by jpike88** [comment]
Yes positive

**Comment by mjbvz** [comment]
1.40.2 + workspace TS works fine for me:

<img width="807" alt="Screen Shot 2019-12-02 at 9 58 17 PM" src="https://user-images.githubusercontent.com/12821956/70024415-de558380-154e-11ea-9141-ac9728f07cfc.png">

Does this happen in all projects? What about very simple ones?

**Comment by jpike88** [comment]
Interesting: the issue only occurs in my angular project files. Disabling my angular vscode plugin did not help.

Typescript kicks in fine, but tslint doesn't seem to be kicking in.

But if I remove my @Component, and @Input decorators, it works fine. Imports weren't modifed, so even if it's importing other components that doesn't seem to be a problem.

Looks like this is specifically related to decorators interfering with tslint plugin. But the trigger was still the VSCode upgrade.

**Comment by jpike88** [comment]
Tried to reproduce it with https://github.com/PatrickJS/angular-starter, couldn't do it. Seems specific to our project for now.

Found this error in the log:

```
Err 13023 [13:52:10.523] Exception on executing command delayed processing of request 377:

    Cannot read property 'length' of undefined

    TypeError: Cannot read property 'length' of undefined
        at checkNumericLiteralValueSize (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:65762:77)
        at checkGrammarNumericLiteral (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:65755:13)
        at checkExpressionWorker (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:58127:21)
        at checkExpression (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:58066:38)
        at checkVoidExpression (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:56904:13)
        at checkExpressionWorker (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:58178:28)
        at checkExpression (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:58066:38)
        at getTypeOfExpression (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:58042:58)
        at getRegularTypeOfExpression (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:63621:48)
        at getTypeOfNode (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:63532:24)
        at Object.getTypeAtLocation (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:33188:31)
        at getBuiltinTypeFromTs (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:29483:32)
        at TypeScriptSymbolQuery.getBuiltinType (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:28798:28)
        at AstType.get [as undefinedType] (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:28301:63)
        at AstType.visitInterpolation (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:28198:25)
        at Interpolation.visit (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:7174:28)
        at ASTWithSource.visit (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:7290:29)
        at AstType.getDiagnostics (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:28003:28)
        at getExpressionDiagnostics (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:28394:18)
        at ExpressionDiagnosticsVisitor.diagnoseExpression (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:28629:61)
        at ExpressionDiagnosticsVisitor.visitBoundText (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:28569:18)
        at BoundTextAst.visit (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:10816:28)
        at visit (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11127:41)
        at /Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11129:29
        at Array.forEach (<anonymous>)
        at templateVisitAll (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11128:14)
        at visit (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11112:34)
        at /Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11097:17
        at ExpressionDiagnosticsVisitor.RecursiveTemplateAstVisitor.visitChildren (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11114:13)
        at ExpressionDiagnosticsVisitor.RecursiveTemplateAstVisitor.visitElement (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11090:25)
        at ExpressionDiagnosticsVisitor.visitElement (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:28603:43)
        at ElementAst.visit (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:10948:28)
        at visit (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11127:41)
        at /Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11129:29
        at Array.forEach (<anonymous>)
        at templateVisitAll (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11128:14)
        at visit (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11112:34)
        at /Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11097:17
        at ExpressionDiagnosticsVisitor.RecursiveTemplateAstVisitor.visitChildren (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11114:13)
        at ExpressionDiagnosticsVisitor.RecursiveTemplateAstVisitor.visitElement (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11090:25)
        at ExpressionDiagnosticsVisitor.visitElement (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:28603:43)
        at ElementAst.visit (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:10948:28)
        at visit (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11127:41)
        at /Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11129:29
        at Array.forEach (<anonymous>)
        at templateVisitAll (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11128:14)
        at visit (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11112:34)
        at /Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11097:17
        at ExpressionDiagnosticsVisitor.RecursiveTemplateAstVisitor.visitChildren (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11114:13)
        at ExpressionDiagnosticsVisitor.RecursiveTemplateAstVisitor.visitElement (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11090:25)
        at ExpressionDiagnosticsVisitor.visitElement (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:28603:43)
        at ElementAst.visit (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:10948:28)
        at visit (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11127:41)
        at /Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11129:29
        at Array.forEach (<anonymous>)
        at templateVisitAll (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11128:14)
        at visit (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11112:34)
        at /Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11097:17
        at ExpressionDiagnosticsVisitor.RecursiveTemplateAstVisitor.visitChildren (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11114:13)
        at ExpressionDiagnosticsVisitor.RecursiveTemplateAstVisitor.visitElement (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11090:25)
        at ExpressionDiagnosticsVisitor.visitElement (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:28603:43)
        at ElementAst.visit (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:10948:28)
        at visit (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11127:41)
        at /Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11129:29
        at Array.forEach (<anonymous>)
        at templateVisitAll (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:11128:14)
        at getTemplateExpressionDiagnostics (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:28388:9)
        at getTemplateDiagnostics (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:50752:37)
        at LanguageServiceImpl.getDiagnostics (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:51009:62)
        at Object.getSemanticDiagnostics (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:71010:55)
        at TSLintPlugin.getSemanticDiagnostics (/Users/joshpike/Projects/aquipa/node_modules/typescript-tslint-plugin/out/plugin.js:93:29)
        at Proxy.intercept.getSemanticDiagnostics (/Users/joshpike/Projects/aquipa/node_modules/typescript-tslint-plugin/out/plugin.js:73:25)
        at IOSession.Session.semanticCheck (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:139717:52)
        at /Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:139758:31
        at MultistepOperation.executeAction (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:138911:25)
        at /Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:138892:100
        at IOSession.Session.executeWithRequestId (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:140861:28)
        at Object.executeWithRequestId (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:139526:87)
        at Immediate._onImmediate (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:138892:41)
        at processImmediate (internal/timers.js:439:21)
```

**Comment by jpike88** [comment]
I see this error:

```
    Could not find source file: '/Users/joshpike/Projects/aquipa/client/src/components/app/plant-general-details/plant-general-details.component.ts'.

    Error: Could not find source file: '/Users/joshpike/Projects/aquipa/client/src/components/app/plant-general-details/plant-general-details.component.ts'.
        at getValidSourceFile (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:130492:29)
        at Proxy.getSyntacticDiagnostics (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:130706:52)
        at IOSession.Session.syntacticCheck (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:139721:87)
        at checkOne (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:139753:27)
        at MultistepOperation.executeAction (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:138911:25)
        at /Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:138901:100
        at IOSession.Session.executeWithRequestId (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:140861:28)
        at Object.executeWithRequestId (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:139526:87)
        at Timeout._onTimeout (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:138901:41)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7)
```

That makes no sense, as that path exists. I suspect something to do with how workspace paths are handled in the update?

**Comment by mjbvz** [comment]
That error is in the TS Server so it unlikely any VS Code changes around workspaces could have broken things. It's possible something with the electron update file watching could have changed something, although we would generally expect other extensions to be effected as well

Can you share the project or small repo project so I can try to investigate?

**Comment by jpike88** [comment]
deleting and reinstalling vscode fixed the issue...

**Comment by jpike88** [comment]
false alarm still a problem

**Comment by jpike88** [comment]
its tied to the typescript version

**Comment by jpike88** [comment]
TS 3.6.4 -> 3.7.2 is causing the issue

**Comment by jpike88** [comment]
error in log:

```
Err 35    [11:21:8.644] Exception on executing command {"seq":9,"type":"request","command":"definitionAndBoundSpan","arguments":{"file":"/Users/joshpike/Projects/aquipa/client/src/components/app/plant-general-details/plant-general-details.component.ts","line":520,"offset":29}}:

    Could not find source file: '/Users/joshpike/Projects/aquipa/client/src/components/app/plant-general-details/plant-general-details.component.ts'.

    Error: Could not find source file: '/Users/joshpike/Projects/aquipa/client/src/components/app/plant-general-details/plant-general-details.component.ts'.
        at getValidSourceFile (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:130492:29)
        at Object.getDefinitionAndBoundSpan (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:130813:73)
        at Proxy.getDefinitionAndBoundSpan (/Users/joshpike/Projects/aquipa/node_modules/@angular/language-service/bundles/language-service.umd.js:71029:35)
        at IOSession.Session.getDefinitionAndBoundSpan (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:139891:83)
        at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:139249:61)
        at /Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:140870:88
        at IOSession.Session.executeWithRequestId (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:140861:28)
        at IOSession.Session.executeCommand (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:140870:33)
        at IOSession.Session.onMessage (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:140893:35)
        at Interface.<anonymous> (/Users/joshpike/Projects/aquipa/node_modules/typescript/lib/tsserver.js:142208:27)
        at Interface.emit (events.js:200:13)
        at Interface._onLine (readline.js:314:10)
        at Interface._normalWrite (readline.js:459:12)
        at Socket.ondata (readline.js:170:10)
        at Socket.emit (events.js:200:13)
        at addChunk (_stream_readable.js:294:12)
        at readableAddChunk (_stream_readable.js:275:11)
        at Socket.Readable.push (_stream_readable.js:210:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

Could not find source file is a weird error, that path DEFINITELY exists.
