### ISSUE TITLE
Sync: Failed to sync keybindings if keybindings.json file doesn't exist

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#86094]
Testing https://github.com/microsoft/vscode/issues/85944

After running a second instance pointing to a fresh user data dir, settings were successfully synced but then this appeared in the logs:

```
[2019-12-03 16:08:44.986] [userDataSync] [error] ["Error: Unable to read file (Error: File not found (/tmp/tmp.DEqspUHO2E/User/keybindings.json))","    at _.doReadAsFileStream (file:///home/joao/Downloads/code-insider-1575351656/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1592:434)"]
```

Also, extensions didn't get synced at all... I wonder if it's because the whole sync process stopped in this error?

**Comment by joaomoreno** [comment]
After I created an empty file `/tmp/tmp.DEqspUHO2E/User/keybindings.json`, I got these errors:

```
[2019-12-03 16:10:49.970] [userDataSync] [error] TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Object.t.merge (file:///home/joao/Downloads/code-insider-1575351656/VSCode-linux-x64/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:366:201)
    at e.generatePreview (file:///home/joao/Downloads/code-insider-1575351656/VSCode-linux-x64/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:385:464)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by joaomoreno** [comment]
Once I set that file's contents to `[]`, everything worked, including extensions syncing.

**Comment by joaomoreno** [comment]
> Also, extensions didn't get synced at all... I wonder if it's because the whole sync process stopped in this error?

Created https://github.com/microsoft/vscode/issues/86096 to address this

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/86062
