### ISSUE TITLE
NVM causes strange terminal errors

### ISSUE THREAD

**Issue by deathgaze** [microsoft/vscode#86277]
Sometimes I get this when I change NVM versions, sometimes I don't. I guess it's starting after I change NVM versions and reboot.

```bash
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
Require stack:
- /usr/local/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:152:3)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/npm/bin/npm-cli.js' ]
}
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `npm config delete prefix` or `nvm use --delete-prefix v13.2.0 --silent` to unset it.
```
Following the first instruction doesn't work:

```
$ npm config delete prefix
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
Require stack:
- /usr/local/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:152:3)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/npm/bin/npm-cli.js' ]
```

Entering `nvm use --delete-prefix v13.2.0 --silent` restores usage of NPM, but I'm forced to run it every time I open a new terminal and ONLY in VS Code. What in the world is going on here? Is there a way to prevent this error without modifying my startup files all the time to accommodate each specific version?

### System Info
```

CPUs | Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | 3, 4, 3
Memory (System) | 16.00GB (2.99GB free)
Process Argv |  
Screen Reader | no
VM | 0%
```

### Extensions

```

Extension | Author (truncated) | Version
-- | -- | --
better-comments | aar | 2.0.5
atlascode | atl | 2.1.5
bb-spectacle | bb- | 0.3.0
better-toml | bun | 0.3.2
npm-intellisense | chr | 1.3.0
path-intellisense | chr | 1.4.2
vscode-eslint | dba | 1.9.1
vscode-npm-script | eg2 | 0.3.9
vsc-material-theme | Equ | 30.0.0
prettier-vscode | esb | 3.11.0
glitch | gli | 0.1.3
gc-excelviewer | Gra | 2.1.32
dotenv | mik | 1.0.1
python | ms- | 2019.11.50794
cpptools | ms- | 0.26.2
vetur | oct | 0.22.6
material-icon-theme | PKi | 3.9.2
prisma | Pri | 0.0.17
vscode-graphql | Pri | 0.2.2
promise-snippets | pro | 0.2.3
vscode-yaml | red | 0.6.1
sass-indented | syl | 1.7.1
language-stylus | sys | 1.11.0

```

**Comment by deathgaze** [comment]
https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/integrated-terminal.md#why-is-nvm-complaining-about-a-prefix-option-when-the-integrated-terminal-is-launched
