### ISSUE TITLE
unable to connect to remote docker using docker-mac

### ISSUE THREAD

**Issue by marcpawl** [microsoft/vscode#86443]
- VSCode Version:
- OS Version:
Version: 1.41.0-insider
Commit: 7f1975a4fb29d0a788c21f17eb2aad056fec22d8
Date: 2019-12-04T10:18:55.163Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0

Steps to Reproduce:
1. Working over VPN from home to work.
2. Setup connection to rhel remote docker container user docker-machine.
3. Change .bashrc to have:
# Docker Machine
eval $(docker-machine env remotedev)

# Visual Code
export PATH=${PATH}:"/Applications/Visual Studio Code - Insiders.app//Contents/Resources/app/bin"

4. Launch code-insiders 
5. Select containders panel
6Select Other Containers
7 Choose executing container on remote 
8.  New window pops up with Installing Dev Container scrolling by and never closing.
9 Select Details
[1 ms] Start: Resolving remote
[5 ms] Setting up container rhel72_64

[640 ms] Start: Check Docker is running
[1278 ms] Start: Inspecting container
[1809 ms] Start: Run in container: uname -m

After an hour VPN timed out, but Installing Dev Container was doing what ever it was trying to do.

Does this issue occur when all extensions are disabled?:
Did not try since containers is an extension

See for similar problem
Node Remote Debug takes up to 1 min to attach when using Docker for Mac #69118

**Comment by marcpawl** [comment]
render3.log has
[2019-12-05 21:3[2019-12-05 21:37:31.167] [renderer3] [error] spawn docker ENOENT: Error: spawn docker ENOENT
        at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
        at onErrorNT (internal/child_process.js:456:16)
        at processTicksAndRejections (internal/process/task_queues.js:84:9)7:31.167] [renderer3] [error] spawn docker ENOENT: Error: spawn docker ENOENT
        at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
        at onErrorNT (internal/child_process.js:456:16)
        at processTicksAndRejections (internal/process/task_queues.js:84:9)


The Mac (client) does not have docker installed.  (Too old)

On remote machine ./devcontainer.json
The docker-compose.yml is in the container.  But I did not get to the point where I could choose a folder.
{
    "name": "dcr",
    "dockerComposeFile": "../../logs/docker/docker-compose.yml",
    "service": "rhel72_64",
    "workspaceFolder": ".",
    "shutdownAction": "stopCompose"
}

**Comment by chrmarti** [comment]
When you say the Mac does not have docker installed, are you saying it does not have the `docker` CLI command available? Which version of the Remote-Containers extension do you have installed?
