### ISSUE TITLE
Cannot read property 'dragStartDisposable' of undefined

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#86602]
I am seeing this with steps such as:
* be in a multi root workspace
* have no outgoing changes
* open SCM view
* click on second repo
* type into an editor of a file of that repo
* wait until file shows up as outgoing
* undo from the view and wait until change goes away
* repeat

```
 ERR Cannot read property 'dragStartDisposable' of undefined: TypeError: Cannot read property 'dragStartDisposable' of undefined
    at ListView.removeItemFromDOM (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listView.js:436:18)
    at ListView._splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listView.js:166:22)
    at ListView.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listView.js:154:29)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/splice.js:13:45
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/splice.js:13:30)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:948:67
    at EventBufferer.bufferEvents (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:657:23)
    at TreeNodeList.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/list/listWidget.js:948:32)
    at TreeNodeList.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/abstractTree.js:851:19)
    at Object.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:245:22)
    at IndexTreeModel.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/indexTreeModel.js:102:27)
    at ObjectTreeModel._setChildren (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/objectTreeModel.js:61:24)
    at ObjectTreeModel.setChildren (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/objectTreeModel.js:30:18)
    at CompressedObjectTreeModel._setChildren (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:141:24)
    at CompressedObjectTreeModel.setChildren (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:110:18)
    at CompressibleObjectTreeModel.setChildren (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:288:24)
    at WorkbenchCompressibleObjectTree.setChildren (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/browser/ui/tree/objectTree.js:114:24)
    at ViewModel.refresh (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/scm/browser/repositoryPane.js:366:27)
    at ViewModel.onDidSpliceGroup (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/scm/browser/repositoryPane.js:344:18)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/scm/browser/repositoryPane.js:319:147
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:458:38)
    at MainThreadSCMResourceGroup.splice (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadSCM.js:41:31)
    at MainThreadSCMProvider.$spliceGroupResourceStates (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadSCM.js:163:27)
    at MainThreadSCM.$spliceResourceStates (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadSCM.js:267:22)
    at RPCProtocol._doInvokeHandler (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:331:27)
    at RPCProtocol._invokeHandler (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:316:45)
    at RPCProtocol._receiveRequest (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:243:32)
    at RPCProtocol._receiveOneMessage (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:171:26)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:61:52
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:458:38)
    at BufferedEmitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:361:35)
    at PersistentProtocol._receiveMessage (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:580:37)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:454:83
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:458:38)
    at ProtocolReader.acceptChunk (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:187:37)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:156:61
    at Socket.listener (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.net.js:16:40)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
fileEditorTracker.js:256 
```

**Comment by joaomoreno** [comment]
Easier repro:

1. Open single repo, no changes
2. Try to hide the repo by right-clicking the title then choosing `Hide`
3. Make a change

:boom:

**Comment by sandy081** [comment]
@joaomoreno I am not able to hide the repo at all.. Not sure if this is the fix?

**Comment by joaomoreno** [comment]
All good. 👍
