### ISSUE TITLE
renderer1: Unable to read file

### ISSUE THREAD

**Issue by kjeremy** [microsoft/vscode#86843]
Issue Type: <b>Bug</b>

I am seeing a lot of the following in the OUTPUT window:

```
[2019-12-12 14:51:24.168] [renderer1] [error] Unable to read file (EntryNotFound (FileSystemError)): Error: Unable to read file (EntryNotFound (FileSystemError))
    at _.doReadAsFileStream (file:///C:/Users/jkolb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1591:434)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[2019-12-12 14:51:38.601] [renderer1] [error] Unable to read file (EntryNotFound (FileSystemError)): Error: Unable to read file (EntryNotFound (FileSystemError))
    at _.doReadAsFileStream (file:///C:/Users/jkolb/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1591:434)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (4.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ron|a5h|0.5.0
better-toml|bun|0.3.2
bracket-pair-colorizer-2|Coe|0.0.29
dart-code|Dar|3.7.1
flutter|Dar|3.7.1
vscode-eslint|dba|1.9.1
gitlens|eam|10.2.0
pubspec-assist|jer|0.3.6
ra-lsp|mat|0.0.1
python|ms-|2019.11.50794
remote-wsl|ms-|0.41.5
cpptools|ms-|0.26.2
vscode-typescript-tslint-plugin|ms-|1.2.3
material-icon-theme|PKi|3.9.2
show-offset|ram|0.0.4
vscode-icons|vsc|9.6.0
debug|web|0.23.1

(2 theme extensions excluded)

</details>

**Comment by romanlex** [comment]
same problem
[2019-12-17 13:34:34.314] [renderer1] [error] Unable to read file (EntryNotFound (FileSystemError)): Error: Unable to read file (EntryNotFound (FileSystemError))
    at _.doReadAsFileStream (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1591:434)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

**Comment by bpasero** [comment]
Without some steps how to get there it is hard to track this down.

**Comment by kjeremy** [comment]
I just vscode. That's it.

**Comment by bpasero** [comment]
I will add some logging for tomorrows build so that we at least know which file path this is.

**Comment by bpasero** [comment]
@kjeremy @romanlex ok can you please post the output when trying with our insiders build:  You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by fluentgcc** [comment]
@bpasero 
I found the clue.
When open folder  in remote ssh server, if the path of the folder  is in a soft link dir, the git has some error occurred.  In this case, git changes highligt will not work.


```
[2019-12-18 17:37:35.885] [renderer6] [error] Unable to read file 'gitfs:/root/vision2/hubconf.py.git?path=%2Froot%2Fvision2%2Fhubconf.py&ref=' (EntryNotFound (FileSystemError)): Error: Unable to read file 'gitfs:/root/vision2/hubconf.py.git?path=%2Froot%2Fvision2%2Fhubconf.py&ref=' (EntryNotFound (FileSystemError))
    at _.doReadAsFileStream (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1593:614)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by alexduros** [comment]
@bpasero 
I ran through the kind of error in my case.

Basically, the error occured each time a debug session failed silently at startup (still trying to understand why, btw, I thought it was related to vscode react-native extension since this is the kind of debug session I was running) 

```
[2019-12-22 11:39:34.582] [renderer1] [error] Unable to read file 'gitfs:/Users/usern/Projects/ProjectName/.vscode/launch.json.git?path=%2FUsers%2Fusern%2FProjects%ProjectName%2F.vscode%2Flaunch.json&ref=' (EntryNotFound (FileSystemError)): Error: Unable to read file 'gitfs:/Users/usern/Projects/ProjectName/.vscode/launch.json.git?path=%2FUsers%2Fusern%2FProjects%ProjectName%2F.vscode%2Flaunch.json&ref=' (EntryNotFound (FileSystemError))
    at _.doReadAsFileStream (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1591:26)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

But I could understand that I have a gitfs error. 
Basically, I have a workspace as following : 

```
| .vscode --> not versionned through git
| - project1/ --> versionned through git
...
| - projectn/ -> versionned through git
```

As a consequence, `.vscode` might be in error while trying to `gitfs` it.
However, the root cause of the error is unclear to me.

**Comment by DylanSp** [comment]
I had the same error appear when opening a directory through a symlink; when not using the symlink, the error disappears.

**Comment by joaomoreno** [comment]
@bpasero It's an expected error that the matching git version of a file doesn't exist. When using the text document content provider API this error wasn't showing up. When using the FS API, it does. How can we suppress it?

**Comment by bpasero** [comment]
@joaomoreno if you give me steps how to reproduce this error and tell me which operation it is triggering, I can look into how the error bubbles up. Unfortunately we seem to be missing a good stacktrace here to understand who is triggering this.

**Comment by bpasero** [comment]
To reproduce: simply open a file in the editor that is not under a source control (e.g. outside the workspace).
