### ISSUE TITLE
[vscode.typescript-language-features] provider FAILED

### ISSUE THREAD

**Issue by sajico** [microsoft/vscode#86881]
Issue Type: <b>Bug</b>

[2019-12-13 15:38:24.271] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2019-12-13 15:38:24.271] [exthost] [error] Error: <semantic> TypeScript Server Error (3.4.5)
No Project.
Error: No Project.
    at Object.ThrowNoProject (tsserver.js:123461:23)
    at ProjectService.doEnsureDefaultProjectForFile (tsserver.js:126300:131)
    at ProjectService.ensureDefaultProjectForFile (tsserver.js:126295:75)
    at IOSession.Session.getFileAndProjectWorker (tsserver.js:129803:87)
    at IOSession.Session.getFileAndProject (tsserver.js:129786:29)
    at IOSession.Session.getApplicableRefactors (tsserver.js:130240:31)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:129066:61)
    at tsserver.js:130466:88
    at IOSession.Session.executeWithRequestId (tsserver.js:130457:28)
    at IOSession.Session.executeCommand (tsserver.js:130466:33)
    at IOSession.Session.onMessage (tsserver.js:130488:35)
    at Interface.<anonymous> (tsserver.js:131789:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
	at Function.create (c:\Users\mitsu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:47388)
	at h.dispatchResponse (c:\Users\mitsu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:206361)
	at h.dispatchMessage (c:\Users\mitsu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:205259)
	at c:\Users\mitsu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:204735
	at l.fire (c:\Users\mitsu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:893)
	at t.Reader.onLengthData (c:\Users\mitsu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:211825)
	at Socket.<anonymous> (c:\Users\mitsu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:211473)
	at Socket.emit (events.js:200:13)
	at Socket.EventEmitter.emit (domain.js:471:20)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
[2019-12-13 15:40:49.238] [exthost] [info] ExtensionService#_doActivateExtension vscode.html-language-features {"startup":false,"extensionId":{"value":"vscode.html-language-features","_lower":"vscode.html-language-features"},"activationEvent":"onLanguage:html"}
[2019-12-13 15:40:49.238] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/mitsu/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/html-language-features/client/dist/htmlMain

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.6.0
project-manager|ale|10.9.1
vscode-intelephense-client|bme|1.3.4
sqlformatter|bre|0.0.7
npm-intellisense|chr|1.3.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.9.1
put-in-tags|dig|1.0.0
git-extension-pack|don|0.1.3
githistory|don|0.4.11
gitlens|eam|10.2.0
vscode-npm-script|eg2|0.3.9
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
docker-explorer|for|0.1.6
docker-extension-pack|for|0.0.1
vscode-lombok|Gab|0.9.9
beautify|Hoo|1.5.0
docthis|joe|0.7.1
vscode-phpfmt|kok|1.0.30
vscode-docker|ms-|0.9.0
vscode-language-pack-ja|MS-|1.41.1
vscode-typescript-tslint-plugin|ms-|1.2.3
vetur|oct|0.22.6
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.13.0
vscode-manifest-yaml|Piv|1.13.0
vscode-spring-boot|Piv|1.13.0
vscode-jsp|pth|0.0.3
java|red|0.54.2
format-html-in-php|rif|1.6.1
LiveServer|rit|5.6.1
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|1.8.0
sass-indented|syl|1.7.1
ayu|tea|0.18.0
vsfire|tob|1.4.1
vscode-status-bar-format-toggle|tom|2.0.0
type-doc-vscode|Tre|0.0.35
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.23.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.21.0
vscode-maven|vsc|0.20.0
vscode-spring-boot-dashboard|vsc|0.1.6
vscode-spring-initializr|vsc|0.4.6
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.7.2
vscode-open-in-github|ziy|1.3.6

(3 theme extensions excluded)

</details>

**Comment by sajico** [comment]
[1.40] The TypeScript language service died 5 times right after it got started. The service will not be restarted #84618

**Comment by sajico** [comment]
Reopen for information sharing.

**Comment by mjbvz** [comment]
Does this reproduce with TypeScript 3.7+ (you are using 3.4.5 in your workspace)
