### ISSUE TITLE
Cannot read property 'filter' of null

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8691]
Saw this in my console running out of sources:

```
[79656:0703/110220:INFO:CONSOLE(248)] "Cannot read property 'filter' of null: TypeError: Cannot read property 'filter' of null
    at DebugEditorModelManager.onModelAdded (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/debug/browser/debugEditorModelManager.js:70:76)
    at CallbackList.invoke (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/callbackList.js:57:43)
    at Emitter.fire (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:84:40)
    at ModelServiceImpl.createModel (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/editor/common/services/modelServiceImpl.js:293:32)
    at TextFileEditorModel.BaseTextEditorModel.doCreateTextEditorModel (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/common/editor/textEditorModel.js:69:43)
    at file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/common/editor/textEditorModel.js:63:30
    at Promise_ctor.CompletePromise_then [as then] (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1566:49)
    at TextFileEditorModel.BaseTextEditorModel.createTextEditorModel (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/common/editor/textEditorModel.js:62:89)
    at file:////Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/parts/files/common/editors/textFileEditorModel.js:196:64
    at Object.notifySuccess [as _notify] (file:////Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/winjs.base.raw.js:1170:59)",
```

**Comment by joaomoreno** [comment]
Any repro steps?

Also, from the code review, I don't think anything was fixed at all. Can you explain which of the four methods that were modified could actually return `null`?

**Comment by isidorn** [comment]
No repro steps - sorry!
Thanks for the code review - my original thought was that the JSON.parse can return null but I see that can not happen since I always call `.map` on that. So yes, it seems that this change did not have an impact - reopening and asigining to august to look into (not imporatnt since nobody got this issue in the meantime)

**Comment by isidorn** [comment]
Investigated and no idea how the `model.breakpoints` can be null. The only idea I had was that you were reloading vscode and some objects got disposed and some not.

Closing until somebody sees it again - then please let me know if this happened while reloading vscode.
