### ISSUE TITLE
Electron 7: failing test (window namespace tests active editor not always correct)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#87330]
This started to fail recently with updating to latest Electron 7 on macOS only ([build failure](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=63925&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7)):

```
1) window namespace tests active editor not always correct... #49125:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(vscode_1.window.activeTextEditor === editorA)

      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (/Users/runner/runners/2.163.1/work/1/s/extensions/vscode-api-tests/src/singlefolder-tests/window.test.ts:155:4)
      at processTicksAndRejections (internal/process/task_queues.js:89:5)

```

**Comment by bpasero** [comment]
This seems to be the remote integration tests [1], not normal ones. Though I cannot reproduce...

[1] `./resources/server/test/test-remote-integration.sh`
