### ISSUE TITLE
使用vscode输入 npm install 报错 throw er; // Unhandled 'error' event ，但是使用cmd npm install却不会报错

### ISSUE THREAD

**Issue by ChillyBreeze1998** [microsoft/vscode#87701]
PS D:\desktop\vue-element-admin-master> npm run dev

> vue-element-admin@4.2.1 dev D:\desktop\vue-element-admin-master
> vue-cli-service serve

D:\desktop\vue-element-admin-master>"node"  "D:\desktop\vue-element-admin-master\node_modules\.bin\\..\_@vue_cli-service@3.5.3@@vue\cli-service\bin\vue-cli-service.js" serve
 INFO  Starting development server...
 10% building 2/2 modules 0 activei ｢wds｣: Project is running at http://localhost:8085/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from D:\desktop\vue-element-admin-master\public
i ｢wds｣: 404s will fallback to /index.html
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/c', 'start', '""', '/b', 'http://localhost:8085/' ]
}
PS D:\desktop\vue-element-admin-master>

**Comment by mjbvz** [comment]
This does not look related to VS Code
