### ISSUE TITLE
Intellisense not working consistently on 1.41

### ISSUE THREAD

**Issue by tomonline** [microsoft/vscode#87836]
Issue Type: <b>Bug</b>

Hi,

I am using VS Code 1.41 on Windows and I noticed that there was an issue with Intellisense suggesting auto-imports.  

If an import was missing, the item is red-underlined, and pressing Ctrl+Space works once by showing suggested imports.  However, if I try to use it a second time, on the same file, same import or even anywhere in the application it fails to work, returning just 'No suggestions'

Interestingly though, hovering over the item with the red underline and then selecting 'Quick Fix' does provide the suggested import consistently.  However, this is a lot slower than the keyboard method.

I have downgraded back to 1.40.2 and the functionality has returned with Ctrl+Space working consistently again.

Could you suggest what is the issue here with 1.41?

Thanks
Tom

VS Code version: Code 1.41
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.95GB (15.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.14.1
vscode-color|ans|0.4.5
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.33.0
vscode-simpler-icons|dav|1.6.5
gitlens|eam|10.2.0
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|3.18.0
auto-rename-tag|for|0.1.1
terminal|for|0.0.10
md2reader|gdr|0.8.0
Angular2|joh|8.3.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
json-to-ts|Mar|1.5.5
vscode-docker|ms-|0.9.0
vsliveshare|ms-|1.0.1404
debugger-for-chrome|msj|4.12.3
vscode-react-native|msj|0.13.2
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
html5-boilerplate|sid|1.0.3
vscode-icons|vsc|9.7.0
markdown-all-in-one|yzh|2.6.1

</details>

**Comment by kieferrm** [comment]
@tomonline I'm guessing you are talking about JavaScript? Can you please provide short example that exhibits the problem? Thank you!

**Comment by 1nfility** [comment]
Same issue on Darwin x64 19.0.0 (Catalina).

example: `
const request = require('request');
// request. - No intellisense to give properties
`

**Comment by tomonline** [comment]
@kieferrm Apologies - yes it's javascript, though to be specific, it's a Typescript file generated from Angular CLI.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)

The first time I invoke intellisense via Ctrl+Space, VSC suggests which file to import:
![image](https://user-images.githubusercontent.com/17877069/71575434-d6084e00-2ae4-11ea-9fe4-5baeabcbd4a3.png)

The scond time I invoke intellisense via Ctrl+Space, VSC provides no suggestions:
![image](https://user-images.githubusercontent.com/17877069/71575445-e7515a80-2ae4-11ea-929a-3f0ae1811f5a.png)


An error is thrown in DevTools, as follows:

>   ERR <semantic> TypeScript Server Error (3.7.3)
Cannot read property 'symbol' of undefined
TypeError: Cannot read property 'symbol' of undefined
    at tsserver.js:106151:69
    at Object.forEach (tsserver.js:170:30)
    at Object.get (tsserver.js:106144:24)
    at getSymbolsFromOtherSourceFileExports (tsserver.js:107274:79)
    at getGlobalCompletions (tsserver.js:107103:49)
    at tryGetGlobalSymbols (tsserver.js:107015:25)
    at getCompletionData (tsserver.js:106813:22)
    at Object.getCompletionsAtPosition (tsserver.js:106177:34)
    at Object.getCompletionsAtPosition (tsserver.js:130777:35)
    at IOSession.Session.getCompletions (tsserver.js:140414:64)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139394:61)
    at tsserver.js:140929:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140920:28)
    at IOSession.Session.executeCommand (tsserver.js:140929:33)
    at IOSession.Session.onMessage (tsserver.js:140952:35)
    at Interface.<anonymous> (tsserver.js:142267:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17): Error: <semantic> TypeScript Server Error (3.7.3)
Cannot read property 'symbol' of undefined
TypeError: Cannot read property 'symbol' of undefined
    at tsserver.js:106151:69
    at Object.forEach (tsserver.js:170:30)
    at Object.get (tsserver.js:106144:24)
    at getSymbolsFromOtherSourceFileExports (tsserver.js:107274:79)
    at getGlobalCompletions (tsserver.js:107103:49)
    at tryGetGlobalSymbols (tsserver.js:107015:25)
    at getCompletionData (tsserver.js:106813:22)
    at Object.getCompletionsAtPosition (tsserver.js:106177:34)
    at Object.getCompletionsAtPosition (tsserver.js:130777:35)
    at IOSession.Session.getCompletions (tsserver.js:140414:64)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139394:61)
    at tsserver.js:140929:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140920:28)
    at IOSession.Session.executeCommand (tsserver.js:140929:33)
    at IOSession.Session.onMessage (tsserver.js:140952:35)
    at Interface.<anonymous> (tsserver.js:142267:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
	at Function.create (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:47388)
	at h.dispatchResponse (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:206557)
	at h.dispatchMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:205455)
	at c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:204931
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:893)
	at t.Reader.onLengthData (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:212021)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:211669)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/microsoft/TypeScript/issues/35036

@tomonline If you have a change, please share steps to reproduce this issue upstream (such as the code  that causes this)

**Comment by 1nfility** [comment]
> Same issue on Darwin x64 19.0.0 (Catalina).
> VSC Version: 1.41.1
> 
> example: `const request = require('request'); // request. - No intellisense to give properties`

Also occurs with javascript, not only typescript.
