### ISSUE TITLE
Unable to launch application on OSX

### ISSUE THREAD

**Issue by wahello** [microsoft/vscode#87878]
- Version: 1.41.1:
- OS Version: 10.14.6 (18G95)

Steps to Reproduce:

1. update python by `brew upgrade python`
2. In terminal `vscode  somefolder`  ps `alias vscode="/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code" ` in .bash_profile
 The log is 
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 62, in <module>
    import os
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 49, in <module>
    import posixpath as path
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 17, in <module>
    import warnings
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/warnings.py", line 8, in <module>
    import types
  File "types.py", line 3, in <module>
    import numpy as np
ImportError: No module named numpy
/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code: line 10: ./MacOS/Electron: No such file or directory
```

**Comment by egamma** [comment]
/needsMoreInfo

Please see https://stackoverflow.com/questions/40185437/no-module-named-numpy-visual-studio-code does the answer there cover your issue?
