### ISSUE TITLE
The VS Code Server failed to start

### ISSUE THREAD

**Issue by sayhellohi** [microsoft/vscode#87884]
windows 10
vs code : 1.41.1
Linux version 3.10.0-957.1.3.el7.x86_64 
the output like this:
[09:40:45.551] "install" wrote data to terminal: "***********"
[09:40:45.570] > 
> 
[09:40:46.159] > f8247cfcb5b8: running
> 
[09:40:46.214] > Acquiring lock on /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d73
> 5645c0/vscode-remote-lock.26076a4de974ead31f97692a0d32f90d735645c0
> 
[09:40:46.214] > Found existing installation at /u/yy9ab/.vscode-server/bin/26076a4de974ead31f976
> 92a0d32f90d735645c0...
> 
[09:40:46.235] > MODULE_VERSION_STACK=3.2.10
> MANPATH=:/opt/puppetlabs/puppet/share/man
> XDG_SESSION_ID=14046
> SELINUX_ROLE_REQUESTED=
> SHELL=/bin/bash
> SSH_CLIENT=128.143.136.18 57956 22
> SELINUX_USE_CURRENT_RANGE=
> GENII_INSTALL_DIR=/opt/genesis2-xcg
> USER=yy9ab
> VSCODE_AGENT_FOLDER=/u/yy9ab/.vscode-server
> PATH=/usr/local/bin:/usr/bin:/opt/genesis2-xcg:/opt/puppetlabs/bin
> MAIL=/var/mail/yy9ab
> MODULE_VERSION=3.2.10
> PWD=/u/yy9ab
> LANG=en_US.UTF-8
> MODULEPATH=/sw/centos/Modules/modulefiles:/sw/linux-any/Modules/modulefiles
> LOADEDMODULES=
> SELINUX_LEVEL_REQUESTED=
> KRB5CCNAME=KEYRING:persistent:2500888
> HOME=/u/yy9ab
> SHLVL=2
> LOGNAME=yy9ab
> CVS_RSH=ssh
[09:40:46.241] > 
> SSH_CONNECTION=128.143.136.18 57956 128.143.67.248 22
> MODULESHOME=/sw/centos/Modules/3.2.10
> LESSOPEN=||/usr/bin/lesspipe.sh %s
> XDG_RUNTIME_DIR=/run/user/2500888
> BASH_FUNC_module()=() {  eval `/sw/centos/Modules/$MODULE_VERSION/bin/modulecmd 
> bash $*`
> }
> _=/usr/bin/printenv
> Starting server...
> Waiting for server log...
[09:40:46.254] > 
> 
[09:40:46.745] > Waiting for server log...
> 
[09:40:47.247] > Waiting for server log...
> 
[09:40:47.750] > Waiting for server log...
> 
[09:40:48.257] > Waiting for server log...
> 
[09:40:48.760] > Waiting for server log...
> 
[09:40:49.267] > Waiting for server log...
> 
[09:40:49.770] > Waiting for server log...
> 
[09:40:50.273] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
[09:40:50.285] > 
> Server did not start successfully. Full server log >>>
> Error: Cannot find module 'iconv-lite'
> Require stack:
[09:40:50.293] > 
> - /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/boots
> trap-amd.js
> - /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/vs/se
> rver/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15) 
>     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
[09:40:50.300] > 
>     at t.load (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d73564
> 5c0/out/vs/loader.js:16:119)
>     at e.load (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d73564
> 5c0/out/vs/loader.js:13:586)
>     at i (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/o
> ut/vs/loader.js:29:189)
>     at Object.errorback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d3
> 2f90d735645c0/out/vs/loader.js:29:313)
>     at e.triggerErrorback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0
[09:40:50.305] > 
> d32f90d735645c0/out/vs/loader.js:13:955)
>     at /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/
> vs/loader.js:13:659
>     at ReadFileContext.callback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f9
> 7692a0d32f90d735645c0/out/vs/loader.js:16:494)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/bo
> otstrap-amd.js',
>     '/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/vs
> /server/main.js'
[09:40:50.310] > 
>   ],
>   phase: 'loading',
>   moduleId: 'iconv-lite',
>   neededBy: [ 'vs/base/node/encoding' ]
> }
> Error: Cannot find module 'applicationinsights'
> Require stack:
> - /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/boots
> trap-amd.js
> - /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/vs/se
> rver/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15) 
>     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at t.load (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d73564
> 5c0/out/vs/loader.js:16:119)
[09:40:50.317] > 
>     at e.load (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d73564
> 5c0/out/vs/loader.js:13:586)
>     at i (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/o
> ut/vs/loader.js:29:189)
>     at Object.errorback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d3
> 2f90d735645c0/out/vs/loader.js:29:313)
[09:40:50.322] > 
>     at e.triggerErrorback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0
> d32f90d735645c0/out/vs/loader.js:13:955)
>     at /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/
> vs/loader.js:13:659
>     at ReadFileContext.callback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f9
> 7692a0d32f90d735645c0/out/vs/loader.js:16:494)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/bo
> otstrap-amd.js',
>     '/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/vs
> /server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'applicationinsights',
[09:40:50.327] > 
>   neededBy: [ 'vs/platform/telemetry/node/appInsightsAppender' ]
> }
> Error: Cannot find module 'cookie'
> Require stack:
> - /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/boots
> trap-amd.js
> - /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/vs/se
> rver/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15) 
>     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at t.load (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d73564
> 5c0/out/vs/loader.js:16:119)
>     at e.load (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d73564
> 5c0/out/vs/loader.js:13:586)
>     at i (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/o
> ut/vs/loader.js:29:189)
>     at Object.errorback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d3
> 2f90d735645c0/out/vs/loader.js:29:313)
>     at e.triggerErrorback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0
> d32f90d735645c0/out/vs/loader.js:13:955)
>     at /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/
> vs/loader.js:13:659
>     at ReadFileContext.callback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f9
[09:40:50.332] > 
> 7692a0d32f90d735645c0/out/vs/loader.js:16:494)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/bo
> otstrap-amd.js',
>     '/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/vs
> /server/main.js'
>   ],
>   phase: 'loading',
[09:40:50.338] > 
>   moduleId: 'cookie',
>   neededBy: [ 'vs/server/webClientServer' ]
> }
> Error: Cannot find module 'semver-umd'
> Require stack:
> - /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/boots
> trap-amd.js
> - /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/vs/se
> rver/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15) 
>     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at t.load (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d73564
> 5c0/out/vs/loader.js:16:119)
>     at e.load (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d73564
> 5c0/out/vs/loader.js:13:586)
>     at i (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/o
> ut/vs/loader.js:29:189)
>     at Object.errorback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d3
> 2f90d735645c0/out/vs/loader.js:29:313)
>     at e.triggerErrorback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0
> d32f90d735645c0/out/vs/loader.js:13:955)
>     at /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/
> vs/loader.js:13:659
>     at ReadFileContext.callback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f9
> 7692a0d32f90d735645c0/out/vs/loader.js:16:494)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/bo
[09:40:50.343] > 
> otstrap-amd.js',
>     '/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/vs
> /server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'semver-umd',
>   neededBy: [
>     'vs/workbench/services/extensions/node/extensionPoints',
>     'vs/platform/extensionManagement/node/extensionManagementService',
>     'vs/code/node/cliProcessMain'
>   ]
> }
> Error: Cannot find module 'vscode-minimist'
> Require stack:
> - /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/boots
> trap-amd.js
> - /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/vs/se
> rver/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15) 
>     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at t.load (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d73564
> 5c0/out/vs/loader.js:16:119)
>     at e.load (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d73564
> 5c0/out/vs/loader.js:13:586)
>     at i (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/o
> ut/vs/loader.js:29:189)
>     at Object.errorback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d3
> 2f90d735645c0/out/vs/loader.js:29:313)
>     at e.triggerErrorback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0
> d32f90d735645c0/out/vs/loader.js:13:955)
>     at /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/
> vs/loader.js:13:659
>     at ReadFileContext.callback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f9
> 7692a0d32f90d735645c0/out/vs/loader.js:16:494)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/bo
> otstrap-amd.js',
>     '/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/vs
> /server/main.js'
[09:40:50.349] > 
>   ],
>   phase: 'loading',
>   moduleId: 'vscode-minimist',
>   neededBy: [ 'vs/platform/environment/node/argv' ]
> }
> Error: Cannot find module 'yauzl'
> Require stack:
> - /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/boots
> trap-amd.js
> - /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/vs/se
> rver/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15) 
>     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at t.load (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d73564
> 5c0/out/vs/loader.js:16:119)
>     at e.load (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d73564
> 5c0/out/vs/loader.js:13:586)
[09:40:50.354] > 
>     at i (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/o
> ut/vs/loader.js:29:189)
>     at Object.errorback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d3
> 2f90d735645c0/out/vs/loader.js:29:313)
>     at e.triggerErrorback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0
> d32f90d735645c0/out/vs/loader.js:13:955)
>     at /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/
> vs/loader.js:13:659
>     at ReadFileContext.callback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f9
> 7692a0d32f90d735645c0/out/vs/loader.js:16:494)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/bo
> otstrap-amd.js',
>     '/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/vs
> /server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'yauzl',
>   neededBy: [ 'vs/base/node/zip' ]
> }
> Error: Cannot find module 'yazl'
[09:40:50.359] > 
> Require stack:
> - /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/boots
> trap-amd.js
> - /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/vs/se
> rver/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15) 
>     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at t.load (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d73564
> 5c0/out/vs/loader.js:16:119)
>     at e.load (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d73564
> 5c0/out/vs/loader.js:13:586)
>     at i (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/o
> ut/vs/loader.js:29:189)
>     at Object.errorback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d3
> 2f90d735645c0/out/vs/loader.js:29:313)
>     at e.triggerErrorback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0
> d32f90d735645c0/out/vs/loader.js:13:955)
>     at /u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/
> vs/loader.js:13:659
>     at ReadFileContext.callback (/u/yy9ab/.vscode-server/bin/26076a4de974ead31f9
> 7692a0d32f90d735645c0/out/vs/loader.js:16:494)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/bo
> otstrap-amd.js',
>     '/u/yy9ab/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/out/vs
> /server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'yazl',
>   neededBy: [ 'vs/base/node/zip' ]
[09:40:50.365] > 
> }
> <<< End of server log
> f8247cfcb5b8##32##
> 
[09:40:50.671] "install" terminal command done
[09:40:50.671] Install terminal quit with output: f8247cfcb5b8##32##
[09:40:50.671] Received install output: f8247cfcb5b8##32##
[09:40:50.672] Resolver error: The VS Code Server failed to start
[09:40:50.675] ------

[10:03:26.387] ConfigFileWatcher: start watching file:///c%3A/Users/yy9ab/.ssh/config
[10:03:26.387] ConfigFileWatcher: adding save listener
[10:03:26.387] ConfigFileWatcher: adding close listener
[10:03:26.511] ConfigFileWatcher: closing walkThrough:/c%3A/Users/yy9ab/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page?%7B%22moduleId%22%3A%22vs%2Fworkbench%2Fcontrib%2Fwelcome%2Fpage%2Fbrowser%2Fvs_code_welcome_page%22%7D
[10:03:44.229] ConfigFileWatcher: saving file:///c%3A/Users/yy9ab/.ssh/config
[10:03:44.229] ConfigFileWatcher: firing change event for file:///c%3A/Users/yy9ab/.ssh/config

PS: i have remove the process of vscode on linux, but  it seems get more erros. Any suggestion will be appreciate!

**Comment by sayhellohi** [comment]
I have solved by rename the .vscode-serve to any other name, and let it regenerate a new folder. And it works!
