### ISSUE TITLE
Path must be a string. Received null

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8793]
Note that with the Electron update some `fs` and `path` methods do stricter checks. I think before you could pass in null to `path.extname` without an error. Now I get this:

```
[20895:0706/113131:INFO:CONSOLE(248)] "Path must be a string. Received null: TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1429:5)
    at LanguageProvider.handles (/home/ticino/development/monaco/extensions/typescript/out/typescriptMain.js:188:30)
    at TypeScriptServiceClientHost.findLanguage (/home/ticino/development/monaco/extensions/typescript/out/typescriptMain.js:283:26)
    at TypeScriptServiceClientHost.handles (/home/ticino/development/monaco/extensions/typescript/out/typescriptMain.js:278:23)
    at Timeout._onTimeout (/home/ticino/development/monaco/extensions/typescript/out/typescriptMain.js:60:181)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)", source: file:////home/ticino/development/monaco/out/vs/workbench/electron-browser/shell.js (248)

```

**Comment by dbaeumer** [comment]
@jrieken can you have a look. This is triggered by the JS project status. Looks like the resolved path is null.

**Comment by isidorn** [comment]
We reverted the electron-update -> verified
