### ISSUE TITLE
Typescript extenion keeps crashing

### ISSUE THREAD

**Issue by andrejpk** [microsoft/vscode#88069]
Issue Type: <b>Bug</b>

Editing javascript and typescript projects and recently the Typescript extension is crashing repeatedly at random. Reloading the code window helps for a while but the problem seems to return every few hours. There's no consistent pattern.

VS Code version: Code - Insiders 1.41.0-insider (599c076d91be1374cf51004cec610f3bcaf4c9cd, 2019-11-22T07:25:24.031Z)
OS version: Windows_NT x64 10.0.19536

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3999)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (9.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (77)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.12.2
LinkCheckMD|bla|0.3.1
azuretoolsforvscode|bra|2.0.2
vscode-markdownlint|Dav|0.33.0
docs-article-templates|doc|0.2.7
docs-authoring-pack|doc|0.1.5
docs-images|doc|0.0.2
docs-markdown|doc|0.2.29
docs-metadata|doc|1.0.4
docs-preview|doc|0.3.36
docs-yaml|doc|0.2.4
prettier-vscode|esb|3.18.0
Ionide-fsharp|Ion|4.4.2
kubernetes-snippets|ipe|0.1.9
Scala|itr|0.1.7
presentationmode|jsp|1.1.5
vscode-home-assistant|kee|1.4.5
graphql-for-vscode|kum|1.15.3
Kotlin|mat|1.7.0
rainbow-csv|mec|1.4.0
vscode-azureappservice|ms-|0.16.2
vscode-azurefunctions|ms-|0.20.1
vscode-azurestorage|ms-|0.7.2
vscode-azureterraform|ms-|0.3.0
vscode-cosmosdb|ms-|0.11.0
vscode-docker|ms-|0.9.0
vscode-kubernetes-tools|ms-|1.0.9
mssql|ms-|1.8.0
python|ms-|2020.1.55524-dev
vscode-ai|ms-|0.6.8
remote-containers|ms-|0.94.0
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
remote-ssh-explorer|ms-|0.48.0
remote-wsl|ms-|0.41.6
vscode-remote-extensionpack|ms-|0.19.0
azure-account|ms-|0.8.7
azurecli|ms-|0.4.6
cpptools|ms-|0.26.3-insiders2
csharp|ms-|1.21.9
powershell|ms-|2019.12.0
vscode-azureextensionpack|ms-|0.0.9
vsliveshare|ms-|1.0.1404
vsonline|ms-|1.0.1424
team|ms-|1.161.0
azurerm-vscode-tools|msa|0.8.3
azure-hdinsight|msh|1.1.7
debugger-for-chrome|msj|4.12.3
vetur|oct|0.22.6
vscode-jest|Ort|3.1.0
material-icon-theme|PKi|3.9.2
platformio-ide|pla|1.10.0
polacode|pnp|0.3.4
java|red|0.55.1
vscode-xml|red|0.10.1
vscode-yaml|red|0.6.1
partial-diff|ryu|1.4.0
prettier-vscode-space-parenthesis|sch|0.17.101
code-settings-sync|Sha|3.4.3
vscode-autohotkey|sle|0.2.2
code-spell-checker|str|1.7.20
vscode-markdown-paste-image|tel|0.12.3
bootstrap4-vscode|the|6.1.0
pdf|tom|0.5.1
usql-vscode-ext|usq|0.2.15
vscodeintellicode|Vis|1.2.2
application-insights|Vis|0.4.2
azure-iot-edge|vsc|1.20.0
azure-iot-toolkit|vsc|2.15.0
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.0
vscode-maven|vsc|0.20.1
debug|web|0.24.0
vscode-import-cost|wix|2.12.0
ReactSnippets|xab|2.4.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce with all extensions disabled?

Also, how exactly is it crashing?

**Comment by andrejpk** [comment]
I was getting the box on the bottom-right of the Code window saying the Typescript Extension crashed 5 times. Restarting Code fixed it for a while. I'll be working with it more this weekend so I'll post if it's still happening. If it is, I'll try with all extensions disabled.

**Comment by tgreen7** [comment]
@andrejpk I am seeing constant crashes as well.

I added the setting ```"typescript.tsserver.log": "verbose",``` and then got the following log error next time it crashed.

<details>
  <summary>Typescript log</summary>
  
  Err 1262  [9:14:42.827] Exception on executing command {"seq":2,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"/Users/taoh/Sites/lims/client/src-design/containers/ChangePasswordFormContainer.js","fileContent":"/* Copyright (C) 2018 TeselaGen Biotechnology, Inc. */\n\nimport { connect } from \"react-redux\";\nimport { compose } from \"redux\";\nimport ChangePasswordForm from \"../components/Settings/Forms/ChangePasswordForm\";\nimport auth from \"../../src-shared/auth\";\n\nconst mapDispatchToProps = () => ({\n  onSubmit: values => {\n    return auth\n      .changePassword({\n        newPassword: values.newPassword,\n        oldPassword: values.oldPassword\n      })\n      .then(() => {\n        window.toastr.success(\"Password successfully updated.\");\n      })\n      .catch(error => {\n        const msg =\n          (error.response && error.response.data && error.response.data.err) ||\n          \"An error occurred\";\n        window.toastr.error(\n          (msg + \". Could not update password.\").replace(\"..\", \".\")\n        );\n        return Promise.reject(error);\n      });\n  }\n});\n\nexport default compose(\n  connect(\n    null,\n    mapDispatchToProps\n  )\n)(ChangePasswordForm);\n","projectRootPath":"/Users/taoh/Sites/lims","scriptKindName":"JS"},{"file":"/Users/taoh/Sites/lims/client/src-shared/api.js","fileContent":"/* Copyright (C) 2018 TeselaGen Biotechnology, Inc. */\nimport axios from \"axios\";\nimport {\n  addRequestInterceptorsToAxios,\n  addResponseInterceptorsToAxios\n} from \"./axiosInterceptors\";\n\nlet api;\n\ntry {\n  // if window is undefined will throw error\n  // log error is omitted if is called from server\n  if (window.api) {\n    api = window.api;\n  } else {\n    api = axios.create({\n      baseURL: localStorage.getItem(\"serverURI\")\n    });\n    addRequestInterceptorsToAxios(api);\n    addResponseInterceptorsToAxios(api);\n    window.api = api;\n  }\n} catch (error) {\n  if (!global) console.error(error);\n}\n\nexport default api;\n","projectRootPath":"/Users/taoh/Sites/lims","scriptKindName":"JS"},{"file":"/Users/taoh/Sites/lims/client/src-shared/axiosInterceptors.js","fileContent":"/* Copyright (C) 2018 TeselaGen Biotechnology, Inc. */\nimport appGlobals from \"./appGlobals\";\nimport uniqid from \"uniqid\";\nimport { addPendingRequest, cancelPendingRequest } from \"./requestTracker\";\nimport { get, set } from \"lodash\";\nimport simulateLatency from \"./simulateLatency\";\nimport { logTrackedRequests } from \"./requestTracker\";\nimport { getAuthToken } from \"./auth/authTokenMethods\";\n\nfunction addAuthTokenToRequest(request) {\n  if (getAuthToken()) {\n    request.headers.Authorization = \"Bearer \" + getAuthToken();\n  }\n\n  return request;\n}\n\nfunction invalidTokenHandler(error) {\n  const response = error.response;\n  if (\n    response.data &&\n    !response.data.success &&\n    response.data.isAuthorization\n  ) {\n    if (appGlobals.logout) {\n      console.error(\n        \"Logging out because token was invalid, please check the server for more information.\"\n      );\n      if (!response.data.isReviewApp) {\n        localStorage.setItem(\"tokenError\", true);\n      }\n      return appGlobals.logout();\n    } else {\n      console.warn(\"appGlobals.logout not defined, cant execute logout\");\n    }\n  }\n\n  return Promise.reject(error);\n}\n\nfunction addRequestInterceptorsToAxios(axiosInstance) {\n  logTrackedRequests(`[AXIOS] Adding Request Interceptor to axios`);\n  axiosInstance.interceptors.request.use(config => {\n    //console.log(`[AXIOS] Request interceptor being called`);\n    const key = uniqid();\n    const t0 = Date.now();\n    set(config, \"meta.requestTrackingId\", key);\n    logTrackedRequests(\n      `[AXIOS] Request interceptor being called with key: ${key} at ${t0}`\n    );\n    addPendingRequest(key, \"axios\");\n    // return addAuthTokenToRequest(config);\n    return simulateLatency().then(() => {\n      logTrackedRequests(\n        `[AXIOS] Delayed request being called: ${key} ${Date.now() -\n          t0} ms later`\n      );\n      return addAuthTokenToRequest(config);\n    });\n  });\n}\n\nfunction addResponseInterceptorsToAxios(axiosInstance) {\n  axiosInstance.interceptors.response.use(\n    response => {\n      const key = get(response, \"config.meta.requestTrackingId\");\n      cancelPendingRequest(key, \"axios\");\n      return response;\n    },\n    error => {\n      const key = get(error, \"response.config.meta.requestTrackingId\");\n      cancelPendingRequest(key, \"axios\");\n      return invalidTokenHandler(error);\n    }\n  );\n}\n\nexport { addRequestInterceptorsToAxios, addResponseInterceptorsToAxios };\n","projectRootPath":"/Users/taoh/Sites/lims","scriptKindName":"JS"},{"file":"/Users/taoh/Sites/lims/client/src-test/auth/index.js","fileContent":"/* Copyright (C) 2018 TeselaGen Biotechnology, Inc. */\n\nimport axios from \"axios\";\nimport api from \"../api\";\nimport joinUrl from \"url-join\";\n\n// axios.defaults.withCredentials = true;\n\nlet localStorage;\n\n// If we're testing, use a local storage polyfill\nif (global.process && process.env.NODE_ENV === \"test\") {\n  localStorage = require(\"localStorage\");\n} else {\n  // If not, use the browser one\n  localStorage = global.window.localStorage;\n}\n\nconst authTokenName = \"authToken-teselagen\";\n\nlet auth = {\n  getAuthToken() {\n    return localStorage.getItem(authTokenName);\n  },\n\n  setAuthToken(token) {\n    localStorage.setItem(authTokenName, token);\n    return token;\n  },\n\n  removeAuthToken,\n\n  resetPassword(data) {\n    return axios.request({\n      method: \"POST\",\n      baseURL: localStorage.getItem(\"serverURI\"),\n      url: \"/reset\",\n      withCredentials: true,\n      data\n    });\n  },\n  /**\n   * Logs the current user out\n   */\n  async logout() {\n    const tokenError = localStorage.getItem(\"tokenError\");\n    const darkMode = localStorage.getItem(\"darkMode\") === \"true\";\n    const serverURI = localStorage.getItem(\"serverURI\");\n    let ssoResponse;\n    if (localStorage.getItem(\"azureAuthenticated\") === \"true\") {\n      removeAuthToken(\"authToken\");\n      ssoResponse = await api.post(\"/adlogout\");\n    } else if (localStorage.getItem(\"samlAuthenticated\") === \"true\") {\n      ssoResponse = await api.post(\"/samllogout\");\n    }\n    localStorage.clear();\n    console.warn(\"Stored reset in progress...\");\n\n    window.teGlobalStore.dispatch({\n      type: \"APOLLO_STORE_RESET\",\n      observableQueryIds: []\n    });\n\n    console.warn(\"APOLLO REFRESH\");\n\n    // persist user darkmode setting\n    if (darkMode) {\n      localStorage.setItem(\"darkMode\", true);\n    }\n    // this will allow us to login after forced logout\n    // without it would send login to localhost:4000\n    if (serverURI) {\n      localStorage.setItem(\"serverURI\", serverURI);\n    }\n    if (tokenError) localStorage.setItem(\"tokenError\", tokenError);\n    if (ssoResponse) {\n      window.location.replace(ssoResponse.data.logoutUrl);\n    } else {\n      if (window.frontEndConfig.clientBasePath) {\n        // window.location.href = \"/build/client/login\";\n        window.location.href = joinUrl(\n          window.frontEndConfig.clientBasePath,\n          \"/login\"\n        );\n      } else {\n        window.location.href = \"/login\";\n      }\n    }\n  },\n  /**\n   * Registers a user and then logs them in\n   * @param  {string} username The username of the user\n   * @param  {string} password The password of the user\n   */\n  register(data, noLogin) {\n    return axios\n      .request({\n        method: \"POST\",\n        baseURL: localStorage.getItem(\"serverURI\"),\n        url: \"/register\",\n        data\n      })\n      .then(res => {\n        return noLogin ? res : auth.login(data);\n      });\n  },\n\n  changePassword(data, userId) {\n    return axios.request({\n      method: \"POST\",\n      baseURL: localStorage.getItem(\"serverURI\"),\n      url: \"/change-password\",\n      data: {\n        ...data,\n        userId\n      }\n    });\n  }\n};\n\nexport default auth;\n\nfunction removeAuthToken() {\n  localStorage.removeItem(authTokenName);\n}\n","projectRootPath":"/Users/taoh/Sites/lims","scriptKindName":"JS"},{"file":"/Users/taoh/Sites/lims/client/src-design/redux/sagas/submitDesignForAssembly/index.js","fileContent":"/* Copyright (C) 2018 TeselaGen Biotechnology, Inc. */\n\nimport { takeEvery, select, call, put } from \"redux-saga/effects\";\n// import { uniq } from 'lodash'\n// import React from 'react'\nimport actions from \"../../actions\";\n// import createJ5Inputs from './createJ5Inputs'\nimport sendToJ5 from \"./sendToJ5\";\nimport { handleSaveDesign } from \"../saveDesign/index\";\nimport { getDesign } from \"../../../../../tg-iso-design/selectors/designStateSelectors\";\n\nfunction* handleSubmitDesignForAssembly() {\n  yield call(window.toastr.success, \"Submitting for assembly\");\n  let design;\n  try {\n    design = yield select(getDesign);\n    yield put(\n      actions.j5.submitDesignForAssemblyStarted({ designId: design.id })\n    );\n\n    // Save the design first.\n    yield call(handleSaveDesign);\n\n    yield call(sendToJ5, design.id);\n  } catch (e) {\n    // TODO: Better handling.\n    console.error(e);\n    yield call(window.toastr.error, \"Error submitting for assembly.\");\n    yield put(\n      actions.j5.submitDesignForAssemblyFailed({ designId: design.id })\n    );\n  }\n}\n\nexport default function* watchSubmitDesignForAssembly() {\n  yield takeEvery(\n    actions.j5.submitDesignForAssembly,\n    handleSubmitDesignForAssembly\n  );\n}\n","projectRootPath":"/Users/taoh/Sites/lims","scriptKindName":"JS"},{"file":"/Users/taoh/Sites/lims/client/src-shared/auth/authTokenMethods.js","fileContent":"/* Copyright (C) 2018 TeselaGen Biotechnology, Inc. */\nconst authTokenName = \"authToken-teselagen\";\n\nexport const getAuthToken = () => {\n  return localStorage.getItem(authTokenName);\n};\n\nexport const setAuthToken = token => {\n  localStorage.setItem(authTokenName, token);\n  return token;\n};\n\nexport const removeAuthToken = () => {\n  localStorage.removeItem(authTokenName);\n};\n","projectRootPath":"/Users/taoh/Sites/lims","scriptKindName":"JS"},{"file":"/Users/taoh/Sites/lims/client/src-build/index.js","fileContent":"/* Copyright (C) 2018 TeselaGen Biotechnology, Inc. */\nimport React from \"react\";\nimport { setLogLevel } from \"webpack/hot/log\";\nimport ReactDOM from \"react-dom\";\nimport { Provider } from \"react-redux\";\nimport { ApolloProvider } from \"react-apollo\";\nimport appGlobals from \"./appGlobals\";\nimport client from \"../src-shared/apolloClient\";\n// needs to be above App because it is changing modelNameToLink\nimport \"./modelMappings\"; // eslint-disable-line\nimport \"./overrideReduxFormDefaults\"; // eslint-disable-line;\nimport App from \"./App\";\nimport store from \"./redux/store\";\nimport registerServiceWorker from \"./registerServiceWorker\";\n// this will import trc styles\nimport { toastr } from \"teselagen-react-components\"; // eslint-disable-line\nimport \"./bootstrap.css\";\nimport \"./app.css\";\n\nsetLogLevel(\"none\");\nappGlobals.apolloClient = client;\n\nconst rootEl = document.getElementById(\"root\");\n\nif (window.location.search.match(\"azureAuthenticated=true\")) {\n  localStorage.setItem(\"authenticated\", \"true\");\n  localStorage.setItem(\"azureAuthenticated\", \"true\");\n}\n\nif (window.location.search.match(\"samlAuthenticated=true\")) {\n  localStorage.setItem(\"authenticated\", \"true\");\n  localStorage.setItem(\"samlAuthenticated\", \"true\");\n}\n\nif (window.location.search.match(\"ldapAuthenticated=true\")) {\n  localStorage.setItem(\"authenticated\", \"true\");\n  localStorage.setItem(\"ldapAuthenticated\", \"true\");\n}\n\n//webpack magic to hot reload reducers\nif (module.hot && window.location.host.match(/localhost/)) {\n  module.hot.accept(\"./redux/reducers\", () => {\n    const nextRootReducer = require(\"./redux/reducers\").default;\n    store.replaceReducer(nextRootReducer);\n  });\n  // this was for create-react-app\n  // now that we switched to nwb I don't think it is needed\n\n  // module.hot.accept(\"./App\", () => {\n  //   const NextApp = require(\"./App\").default;\n  //   ReactDOM.render(\n  //     <ApolloProvider client={client}>\n  //       <Provider store={store}>\n  //         <NextApp />\n  //       </Provider>\n  //     </ApolloProvider>,\n  //     rootEl\n  //   );\n  // });\n}\n\nReactDOM.render(\n  <ApolloProvider client={client}>\n    <Provider store={store}>\n      <App />\n    </Provider>\n  </ApolloProvider>,\n  rootEl\n);\n\nregisterServiceWorker();\n","projectRootPath":"/Users/taoh/Sites/lims","scriptKindName":"JS"},{"file":"/Users/taoh/Sites/lims/client/src-design/index.js","fileContent":"/* Copyright (C) 2018 TeselaGen Biotechnology, Inc. */\nimport client from \"../src-shared/apolloClient\";\nimport \"./setServerURI\";\nimport React from \"react\";\nimport ReactDOM from \"react-dom\";\nimport { Provider } from \"react-redux\";\nimport { ApolloProvider } from \"react-apollo\";\nimport { FocusStyleManager } from \"@blueprintjs/core\";\nimport { Router } from \"react-router-dom\";\nimport store, { hist } from \"./redux/store\";\nimport { unregister } from \"./registerServiceWorker\";\nimport \"./App.css\";\nimport App from \"./App\";\n\nFocusStyleManager.onlyShowFocusOnTabs();\nconst rootEl = document.getElementById(\"root\");\n\nif (window.location.search.match(\"azureAuthenticated=true\")) {\n  localStorage.setItem(\"authenticated\", \"true\");\n  localStorage.setItem(\"azureAuthenticated\", \"true\");\n}\n\nif (window.location.search.match(\"samlAuthenticated=true\")) {\n  localStorage.setItem(\"authenticated\", \"true\");\n  localStorage.setItem(\"samlAuthenticated\", \"true\");\n}\n\nif (window.location.search.match(\"ldapAuthenticated=true\")) {\n  localStorage.setItem(\"authenticated\", \"true\");\n  localStorage.setItem(\"ldapAuthenticated\", \"true\");\n}\n\n// webpack magic to hot reload reducers\nif (module.hot && window.location.host.match(/localhost/)) {\n  module.hot.accept(\"./redux/reducers\", () => {\n    const nextRootReducer = require(\"./redux/reducers\").default;\n    store.replaceReducer(nextRootReducer);\n  });\n  // this was for create-react-app\n  // now that we switched to nwb I don't think it is needed\n\n  // module.hot.accept(\"./App\", () => {\n  //   const NextApp = require(\"./App\").default;\n  //   ReactDOM.render(\n  //     <ApolloProvider client={client}>\n  //       <Provider store={store}>\n  //         <NextApp />\n  //       </Provider>\n  //     </ApolloProvider>,\n  //     rootEl\n  //   );\n  // });\n}\n\nReactDOM.render(\n  <Provider store={store}>\n    <ApolloProvider client={client}>\n      <Router history={hist}>\n        <App />\n      </Router>\n    </ApolloProvider>\n  </Provider>,\n  rootEl\n);\nunregister();\n","projectRootPath":"/Users/taoh/Sites/lims","scriptKindName":"JS"}]}}:

    Debug Failure. False expression.

    Error: Debug Failure. False expression.
        at declareSymbol (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29212:22)
        at bindThisPropertyAssignment (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31366:25)
        at bindWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:31020:29)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30902:13)
        at bindConditionalExpressionFlow (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30247:13)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29586:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30913:21)
        at bindConditionalExpressionFlow (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30247:13)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29586:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30913:21)
        at bindExpressionStatement (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30106:13)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29568:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30913:21)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29495:94
        at bindEach (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29511:21)
        at bindEachFunctionsFirst (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29495:13)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29611:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30913:21)
        at visitNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:17622:24)
        at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:17752:21)
        at bindEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29519:16)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29614:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bindContainer (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29435:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30916:21)
        at visitNode (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:17622:24)
        at Object.forEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:17825:24)
        at bindEachChild (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29519:16)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29614:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30913:21)
        at bindCallExpressionFlow (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30357:21)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29596:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30913:21)
        at bindExpressionStatement (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30106:13)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29568:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30913:21)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29495:94
        at bindEach (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29511:21)
        at bindEachFunctionsFirst (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29495:13)
        at bindChildrenWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29605:21)
        at bindChildren (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29489:17)
        at bindContainer (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29435:17)
        at bind (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30916:21)
        at bindSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29068:17)
        at Object.bindSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29005:9)
        at initializeTypeChecker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:64384:20)
        at Object.createTypeChecker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33622:9)
        at Object.getTypeChecker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:95612:79)
        at synchronizeHostData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:130645:21)
        at Object.getProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:130727:13)
        at InferredProject.Project.updateGraphWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:135078:53)
        at InferredProject.Project.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:135021:42)
        at ProjectService.assignOrphanScriptInfoToInferredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:136832:25)
        at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138215:26)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138417:107
        at Object.mapDefined (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:565:30)
        at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138417:48)
        at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:139271:46)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:88
        at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140920:28)
        at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:33)
        at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140952:35)
        at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:142267:27)
        at Interface.emit (events.js:200:13)
        at Interface._onLine (readline.js:314:10)
        at Interface._normalWrite (readline.js:459:12)
        at Socket.ondata (readline.js:170:10)
        at Socket.emit (events.js:200:13)
        at addChunk (_stream_readable.js:294:12)
        at readableAddChunk (_stream_readable.js:275:11)
        at Socket.Readable.push (_stream_readable.js:210:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
</details>

I saw in another thread to try out the setting:
```"typescript.tsserver.maxTsServerMemory": 8000```

which hopefully will help.

**Comment by mjbvz** [comment]
@andrejpk Any updates?

**Comment by andrejpk** [comment]
Hi @mjbvz , it seems to have stopped, I haven't had the problem in about a week so let's close it and if it happens again, I'll try to catch more traces. Thanks for looking into it.
