### ISSUE TITLE
Fatal Python error: PyCOND_WAIT(gil_cond) failed

### ISSUE THREAD

**Issue by Haibao425** [microsoft/vscode#88740]
I am running in MacOS which is Catalina 10.15.2, I am running the latest VS code till now.

When I click Debug->Start Debugging for my simple python file, it report Fatal Python error: PyCOND_WAIT(gil_cond) failed.

If I clear the DEBUG CONSOLE window, and then the issue is gone.

ntel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)
--
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_offsurface_control: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | 2, 2, 2
Memory (System) | 32.00GB (2.00GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
logcat | abh | 0.0.7
android-dev-ext | ade | 0.8.0
gitstash | art | 3.2.0
code-gnu-global | aus | 0.2.2
vscode-django | bat | 0.19.0
path-intellisense | chr | 1.4.2
bracket-pair-colorizer | Coe | 1.0.61
evaluate-python-expression | cpr | 0.1.0
vsc-invoke | dch | 0.0.12
python-preview | don | 0.0.4
githistory | don | 0.4.13
python-extension-pack | don | 1.6.0
xml | Dot | 2.5.0
gitlens | eam | 10.2.0
vscode-great-icons | emm | 2.1.47
vscode-git-history | fab | 2.0.5
git-project-manager | fel | 1.7.1
pyfilesgen | ffa | 1.0.2
code-runner | for | 0.9.15
vscode-pull-request-github | Git | 0.14.0
gc-excelviewer | Gra | 2.1.32
vscode-test-explorer | hbe | 2.15.0
githd | hui | 2.2.0
output-colorizer | IBM | 0.1.2
path-autocomplete | ion | 1.13.3
latex-workshop | Jam | 8.6.0
sublime-babel-vscode | jos | 0.2.10
vsc-python-indent | Kev | 1.8.1
git-tree-compare | let | 1.7.1
fish-ide | lun | 0.4.0
MagicPython | mag | 1.1.0
python-path | mge | 0.0.11
git-graph | mhu | 1.21.0
vscode-language-pack-zh-hans | MS- | 1.41.2
pyright | ms- | 1.1.20
python | ms- | 2020.1.58038
remote-containers | ms- | 0.94.0
remote-ssh | ms- | 0.48.0
remote-ssh-edit | ms- | 0.48.0
remote-ssh-explorer | ms- | 0.48.0
cmake-tools | ms- | 1.2.3
cpptools | ms- | 0.26.2
csharp | ms- | 1.21.9
Go | ms- | 0.12.0
notepadplusplus-keybindings | ms- | 1.0.5
vscode-gitignore-generator | pio | 1.0.1
java | red | 0.55.1
vscode-yaml | red | 0.6.1
git-merger | sha | 0.4.1
trailing-spaces | sha | 0.3.1
fish-vscode | sky | 0.2.1
autoimport | ste | 1.5.3
vscodeintellicode | Vis | 1.2.3
vscode-java-debug | vsc | 0.24.0
vscode-java-dependency | vsc | 0.7.0
vscode-java-pack | vsc | 0.8.1
vscode-java-test | vsc | 0.22.0
vscode-maven | vsc | 0.20.2
vscode-icons | vsc | 9.7.0
jinja | who | 0.0.8
highlight-trailing-white-spaces | yba | 0.0.2
json | Zai | 1.0.2
material-theme | zhu | 3.2.1

**Comment by Haibao425** [comment]
[2020-01-16 16:45:37.968] [renderer1] [error] timeout after 500 ms: Error: timeout after 500 ms
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2821:819)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2821:250
    at async t.RawDebugSession.shutdown (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2819:336)
    at async R.terminate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5113:637)
[2020-01-16 16:45:52.621] [renderer1] [error] Server[1] disconnected unexpectedly: Error: Server[1] disconnected unexpectedly
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2821:819)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2821:250
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async R.fetchThreads (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5120:411)
    at async file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5120:917
[2020-01-16 16:46:01.919] [renderer1] [error] Server[1] disconnected unexpectedly: Error: Server[1] disconnected unexpectedly
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2821:819)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2821:250
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async R.fetchThreads (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5120:411)
    at async file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5120:917

**Comment by Haibao425** [comment]
Thread 0x0000700005770000 (most recent call first):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 299 in wait
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 551 in wait
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd.py", line 179 in _on_run
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 156 in run
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x000070000526d000 (most recent call first):
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 270 in _read_line
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 287 in _on_run
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 156 in run
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x0000700004d6a000 (most recent call first):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 299 in wait
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/queue.py", line 173 in get
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 398 in _on_run
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 156 in run
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x0000000114feedc0 (most recent call first):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 171 in islink
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 429 in _joinrealpath
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 395 in realpath
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 356 in _NormPath
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 343 in _NormPaths
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 715 in get_abs_path_real_path_and_base_from_file
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 741 in get_abs_path_real_path_and_base_from_frame
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_
bash-3.2$ env PTVSD_LAUNCHER_PORT=52193 /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 /Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFil
es/lib/python/new_ptvsd/no_wheels/ptvsd/launcher /Users/haibaoli/Projects/Python/module1/main.py --runs 5 
Fatal Python error: PyCOND_WAIT(gil_cond) failed

Thread 0x00007000085a6000 (most recent call first):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 299 in wait
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 551 in wait
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd.py", line 225 in _on_run
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 
156 in run
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007000080a3000 (most recent call first):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 299 in wait
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 551 in wait
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd.py", line 179 in _on_run
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 
156 in run
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x0000700007ba0000 (most recent call first):
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 270 in _read_line
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 287 in _on_run
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 156 in run
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x000070000769d000 (most recent call first):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 299 in wait
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/queue.py", line 173 in get
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 398 in _on_run
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 156 in run
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x000000010b63cdc0 (most recent call first):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 171 in islink
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 429 in _joinrealpath
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 395 in realpath
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 356 in _NormPath
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 343 in _NormPaths
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 715 in get_abs_path_real_path_and_base_from_file
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_file_utils.py", line 741 in get_abs_path_real_path_and_base_from_frame
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 427 in __call__
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1260 in enumerate
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd_tracing.py", line 189 in set_trace_to_threads
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd.py", line 879 in enable_tracing
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd.py", line 2649 in _locked_settrace
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/_vendored/pydevd/pydevd.py", line 2555 in settrace
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/../ptvsd/server/api.py", line 26 in _settrace
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/../ptvsd/server/api.py", line 209 in attach
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/../ptvsd/server/api.py", line 73 in debug
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/../ptvsd/__init__.py", line 109 in attach
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/../ptvsd/server/cli.py", line 182 in setup_debug_server
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/../ptvsd/server/cli.py", line 189 in run_file
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/../ptvsd/server/cli.py", line 361 in main
  File "/Users/haibaoli/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/__main__.py", line 45 in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85 in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193 in _run_module_as_main
bash-3.2$

**Comment by weinand** [comment]
Please file issue against Python extension.

**Comment by ZhongxiaYan** [comment]
I may have had a similar issue when I tried to debug, but I resolved it by removing all existing breakpoints

**Comment by chrissshe** [comment]
I have absolutely no idea why but `I resolved it by removing all existing breakpoints` worked for me as well. Thanks @ZhongxiaYan https://guides.github.com/features/mastering-markdown/
