### ISSUE TITLE
TypeScript server won't start

### ISSUE THREAD

**Issue by alexpaluzzi** [microsoft/vscode#88807]
Issue Type: <b>Bug</b>

Open a large repo and then open any .js or .ts file. No intellisense.

All extensions (except WSL remote) disabled. Tried with latest TS. It DOES work if I the project files are not in WSL2.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (1.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|Memory (System)|25.01GB (2.04GB free)|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.41.7
prettier-vscode|esb|3.18.0
vscode-typescript-next|ms-|3.8.20200115

</details>

**Comment by alexpaluzzi** [comment]
After opening and watching "Initializing js/ts server...". I verbose logging shows a whole mess of stuff, happy to put it all here if needed.
Some that stick out:

[Trace - 19:30:30.496] Response received: updateOpen (2). Request took 137986 ms. Success: true

This took over 2 minutes.

[Trace - 19:30:31.120] Response received: getSupportedCodeFixes (3). Request took 138609 ms. Success: true

This took another 2 minutes.

[Trace - 19:30:37.291] Response received: configure (4). Request took 144779 ms. Success: true

Another 2+ minutes.

Then it just kind of hangs. I noticed when I try to force some intellisense (with ctrl+space) I see these errors:

```
[Error  - 19:35:46.867] ReaderError
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be an integer. Received NaN
	at Function.concat (buffer.js:449:5)
	at l.append (/home/alex/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/extensions/typescript-language-features/dist/extension.js:1:210613)
	at t.Reader.onLengthData (/home/alex/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/extensions/typescript-language-features/dist/extension.js:1:211680)
	at Socket.<anonymous> (/home/alex/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/extensions/typescript-language-features/dist/extension.js:1:211607)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

I also just started getting this pop-up too:

![image](https://user-images.githubusercontent.com/1376892/72566951-d04f8e00-3882-11ea-937a-05dd68cc3d9a.png)

No idea if it's related but it's new all of the sudden. My max user watches are already 524288 (there are not nearly that many files in this project, not including node_modules) but I'm not ruling out some serious WSL2 weirdness here.
