### ISSUE TITLE
`format document` error

### ISSUE THREAD

**Issue by printjs** [microsoft/vscode#88935]
- VSCode Version: 
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
```
- OS Version: MacOs 10.15.2 (19C57)

Steps to Reproduce:

1.pressed `Format Document`
2.error occur

Does this issue occur when all extensions are disabled?: No

The error occur When I pressed `Format Document` to format code.
<syntax> TypeScript Server Error (3.7.4)
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at consumeTokenAndAdvanceScanner (tsserver.js:118215:30)
    at processChildNode (tsserver.js:118129:25)
    at processChildNodes (tsserver.js:118195:48)
    at tsserver.js:118081:21
    at visitNodes (tsserver.js:17627:24)
    at Object.forEachChild (tsserver.js:17731:21)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)
    at processChildNodes (tsserver.js:118195:48)
    at tsserver.js:118081:21
    at visitNodes (tsserver.js:17627:24)
    at Object.forEachChild (tsserver.js:17814:21)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)
    at tsserver.js:118079:21
    at visitNode (tsserver.js:17622:24)
    at Object.forEachChild (tsserver.js:17709:21)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)
    at processChildNodes (tsserver.js:118195:48)
    at tsserver.js:118081:21
    at visitNodes (tsserver.js:17627:24)
    at Object.forEachChild (tsserver.js:17801:24)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)
    at tsserver.js:118079:21
    at visitNode (tsserver.js:17622:24)
    at Object.forEachChild (tsserver.js:17902:24)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)
    at processChildNodes (tsserver.js:118195:48)
    at tsserver.js:118081:21
    at visitNodes (tsserver.js:17627:24)
    at Object.forEachChild (tsserver.js:17862:24)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)
    at tsserver.js:118079:21
    at visitNode (tsserver.js:17622:24)
    at Object.forEachChild (tsserver.js:17752:21)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)
    at processChildNodes (tsserver.js:118195:48)
    at tsserver.js:118081:21
    at visitNodes (tsserver.js:17627:24)
    at Object.forEachChild (tsserver.js:17815:21)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)
    at tsserver.js:118079:21
    at visitNode (tsserver.js:17622:24)
    at Object.forEachChild (tsserver.js:17803:24)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)
    at tsserver.js:118079:21
    at visitNode (tsserver.js:17622:24)
    at Object.forEachChild (tsserver.js:17812:24)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)
    at tsserver.js:118079:21
    at visitNode (tsserver.js:17622:24)
    at Object.forEachChild (tsserver.js:17716:21)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)
    at processChildNodes (tsserver.js:118195:48)
    at tsserver.js:118081:21
    at visitNodes (tsserver.js:17627:24)
    at Object.forEachChild (tsserver.js:17871:24)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)
    at tsserver.js:118079:21
    at visitNode (tsserver.js:17622:24)
    at Object.forEachChild (tsserver.js:17869:21)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)
    at processChildNodes (tsserver.js:118195:48)
    at tsserver.js:118081:21
    at visitNodes (tsserver.js:17627:24)
    at Object.forEachChild (tsserver.js:17862:24)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)
    at tsserver.js:118079:21
    at visitNode (tsserver.js:17622:24)
    at Object.forEachChild (tsserver.js:17752:21)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)
    at processChildNodes (tsserver.js:118195:48)
    at tsserver.js:118081:21
    at visitNodes (tsserver.js:17627:24)
    at Object.forEachChild (tsserver.js:17815:21)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)
    at tsserver.js:118079:21
    at visitNode (tsserver.js:17622:24)
    at Object.forEachChild (tsserver.js:17844:21)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)
    at tsserver.js:118079:21
    at visitNode (tsserver.js:17622:24)
    at Object.forEachChild (tsserver.js:17873:24)
    at processNode (tsserver.js:118078:20)
    at processChildNode (tsserver.js:118144:21)

**Comment by printjs** [comment]
@mjbvz Hi, I find out the error reason.
```
export class UtilsService {
    public TypeAssertion<T>(x: any): T {
        // tslint:disable-next-line: prefer-type-cast
        return (x as T);
    }
}
```
error
```
utils.TypeAssertion<<T>(...args: any[]) => T>(handler)
```
normal
```
utils.TypeAssertion<(...args: any[]) => any>(handler)
```

So,I don't understand what happen.Can you tell me the reason?

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/36363 to track upstream
