### ISSUE TITLE
Initializing TS/JS language features failing

### ISSUE THREAD

**Issue by JonWallsten** [microsoft/vscode#88956]
Version: 1.42.0-insider (user setup)
Commit: d72b2d372f5024a9193b37a3830bbbc459c0ef1b
Date: 2020-01-20T05:33:26.563Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open VSCode editor
2. Wait for "Initializing ts/js language features"
3. Check OUTPUT->Typescript

Does this issue occur when all extensions are disabled?: Yes

I've checked the other related bugs. 
I'm not storing files on another drive.
It started today after updating to latest insiders, has never happened before.

**Log**
```
[Info  - 08:45:48.467] Using tsserver from: c:\Users\<me>\repo\oas-web\node_modules\typescript\lib
[Info  - 08:45:48.483] <syntax> Log file: c:\Users\<me>\AppData\Roaming\Code - Insiders\logs\20200120T093955\exthost3\vscode.typescript-language-features\tsserver-log-94LB2D\tsserver.log
[Info  - 08:45:48.483] <syntax> Forking...
[Info  - 08:45:48.581] <syntax> Starting...
[Info  - 08:45:48.588] <semantic> Log file: c:\Users\<me>\AppData\Roaming\Code - Insiders\logs\20200120T093955\exthost3\vscode.typescript-language-features\tsserver-log-9mKcxz\tsserver.log
[Info  - 08:45:48.588] <semantic> Forking...
[Info  - 08:45:48.687] <semantic> Starting...
[Error  - 08:46:11.221] ReaderError
SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at t.Reader.onLengthData (c:\Users\<me>\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:218946)
	at Socket.<anonymous> (c:\Users\<me>\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:218616)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
[Error  - 08:46:11.223] ReaderError
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be an integer. Received NaN
	at Function.concat (buffer.js:449:5)
	at l.append (c:\Users\<me>\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:217622)
	at t.Reader.onLengthData (c:\Users\<me>\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:218689)
	at Socket.<anonymous> (c:\Users\<me>\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:218616)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
[Error  - 08:46:11.228] ReaderError
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be an integer. Received NaN
	at Function.concat (buffer.js:449:5)
	at l.append (c:\Users\<me>\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:217622)
	at t.Reader.onLengthData (c:\Users\<me>\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:218689)
	at Socket.<anonymous> (c:\Users\<me>\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:218616)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by JonWallsten** [comment]
@JonWallsten: Updating our project from TS 3.5.3 -> 3.7.5 seems to have solved the problem.

**Comment by mjbvz** [comment]
Closing as fixed in newer TS versions

**Comment by MikeMatusz** [comment]
So the TS language server in VSCode won't be compatibly unless you're using v3.7 in your project?  Angular 9 doesn't even support 3.7 yet (and all Angular developers will be able to upgrade to that immediately), so upgrading TS version isn't an option for everyone. Using the VS Code version isn't ideal either, because you might end up using features that aren't actually supported when you go to compile.

**Comment by mjbvz** [comment]
@MikeMatusz No. VS Code supports using TS versions back to 2.3 or so. However newer TS versions have fixes for many important tooling bugs
