### ISSUE TITLE
Debug Console error

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#88990]
I can't repro this now, but the debug console was sort of broken in one window after upgrading to today's Insiders.

I think the Debug Console was active when the window reloaded. After reloading, it was blank. I focused the output tab, then the debug console again, and got a notification like "Cannot toggle this view's visibility" or similar. And saw this error in the debug console.

```
[2020-01-20 10:39:36.771] [renderer2] [error] Cannot read property 'getInput' of undefined: TypeError: Cannot read property 'getInput' of undefined
    at e.selectSession (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5090:640)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5088:58
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:116:740)
    at t.ViewModel.setFocus (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2868:178)
    at j.focusStackFrame (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5498:849)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5495:137
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:116:740)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5482:704
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:116:740)
    at t.RawDebugSession.fireAdapterExitEvent (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2864:67)
    at t.RawDebugSession.stopAdapter (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2863:779)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

But it's working fine now

**Comment by isidorn** [comment]
Aha I think I know what caused this: I changed the Repl to use the new view infrastructure and the timing changed a bit. It gets registered a bit later and the actions that depend on it complain.
The action that depend on it are here https://github.com/microsoft/vscode/blob/e09632f8bf63eec8f8d58ed876b1c1426a11ee72/src/vs/workbench/contrib/debug/browser/repl.ts#L618

So it seems that now the actions are requested for a panel before it is fully constructed sometimes.
Also assigning @sandy081 and me.

**Comment by isidorn** [comment]
After discussing with @sandy081 we arrived on a solutoin that the Repl action should get the Repl view and not use a private service. This will simplify things.

**Comment by isidorn** [comment]
To verify: start debugging multiple debug sessions at the same time and verify there is no error in the chrome dev console and that the VS Code debug console works properly.
