### ISSUE TITLE
TypeScript language service crashes and restarts even after the "5 times" limit

### ISSUE THREAD

**Issue by AArnott** [microsoft/vscode#89062]
Issue Type: <b>Bug</b>

After following the steps [here](https://next.yarnpkg.com/advanced/editor-sdks#vscode) to enable VS Code's TypeScript language service to work with the new yarn 2 package format, I started seeing this message appear and disappear endlessly:

> The TypeScript language service died 5 times right after it got started. The service will not be restarted.

![tscrash](https://user-images.githubusercontent.com/3548/72860070-f90cc480-3c82-11ea-9024-02f2247c45b2.gif)

Two issues here: 

1. The language service crashes.
1. The IDE won't stop telling me that it won't keep trying.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.33.0
jshint|dba|0.10.21
vscode-eslint|dba|2.0.15
githistory|don|0.4.13
xml|Dot|2.5.0
gitlens|eam|10.2.0
remotehub|eam|0.5.0
EditorConfig|Edi|0.14.4
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.10
git-project-manager|fel|1.7.1
vscode-pull-request-github|Git|0.14.0
vscode-jasmine-test-adapter|hbe|1.6.2
vscode-test-explorer|hbe|2.15.0
docker-linter|hen|0.5.0
beautify|Hoo|1.5.0
docomment|k--|0.1.8
csharpfixformat|Leo|0.0.84
azure-pipelines|ms-|1.157.4
vscode-docker|ms-|0.9.0
remote-wsl|ms-|0.41.7
azure-account|ms-|0.8.8
cpptools|ms-|0.26.2
csharp|ms-|1.21.9
mono-debug|ms-|0.15.8
powershell|ms-|2020.1.0
vsliveshare|ms-|1.0.1510
vsonline|ms-|1.0.1507
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.5
vscode-versionlens|pfl|0.24.0
code-settings-sync|Sha|3.4.3
gitconfig|sid|2.0.1
vscodeintellicode|Vis|1.2.4
vscode-java-debug|vsc|0.24.0
vscode-java-pack|vsc|0.8.1
vscode-maven|vsc|0.20.2
vscode-icons|vsc|9.7.0
vsc-docker|Zim|0.34.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Nxt3** [comment]
@mjbvz  It happens to me as well on the latest Insiders build with all extensions disabled. Theses are the logs:

```
[Info  - 19:39:40.103] <main> Forking...
[Info  - 19:39:40.107] <main> Starting...
[Error  - 19:40:24.573] ReaderError
SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at t.Reader.onLengthData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:218987)
	at Socket.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:218657)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
[Error  - 19:40:24.576] ReaderError
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be an integer. Received NaN
	at Function.concat (buffer.js:449:5)
	at l.append (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:217663)
	at t.Reader.onLengthData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:218730)
	at Socket.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:218657)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
[Error  - 19:40:24.583] ReaderError
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be an integer. Received NaN
	at Function.concat (buffer.js:449:5)
	at l.append (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:217663)
	at t.Reader.onLengthData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:218730)
	at Socket.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:218657)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment]
Closing as not actionable without more info. Try the latest insiders build
