### ISSUE TITLE
Git Tree Compare extension is broken

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#89140]
Version: 1.42.0-insider
Commit: c4d53a19df8799f5d49a4f49a6900c499e6fa27c
Date: 2020-01-23T05:38:55.065Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

---

- Install https://marketplace.visualstudio.com/items?itemName=letmaik.git-tree-compare
- Go to a repo
- `git checkout -b feature`
- Make a change
- Git Tree Compare will show a tree of diffs against master branch, under Git Viewlet
- Clicking each file opens a diff view
- 🐛 This works in stable, but not insiders. Seems we have broken one API

Here is what I got:

```
notificationsAlerts.ts:40 Unable to open 'mainThreadDiagnostics.ts (Working Tree)': resource is not available.
onDidNotificationChange @ notificationsAlerts.ts:40
log.ts:197   ERR resource is not available: Error: resource is not available
    at v.createReferencedObject (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5754:457)
    at v.createReferencedObject (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5754:422)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async S.doCreateModelReference (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5755:964)
    at async e.resolve (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4194:372)
    at async Promise.all (index 0)
    at async a.createModel (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4175:105)
    at async a.resolve (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4174:819)
    at async e.setInput (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4176:436)
    at async p.doSetInput (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4079:375)
    at async p.openEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4077:968)
    at async file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5886:878
    at async e.openEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5885:800)
    at async e.openEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5730:483)
```

**Comment by joaomoreno** [comment]
Moved to https://github.com/letmaik/vscode-git-tree-compare/issues/56
