### ISSUE TITLE
JS/TS Language features error during initialization

### ISSUE THREAD

**Issue by Balrog994** [microsoft/vscode#89229]
Issue Type: <b>Bug</b>

Open visual studio code and load a project that uses a local Typescript 3.5.2 compiler

The following error is reported in the Output > Typescript window (partially anonymized)

```
[Info  - 14:15:58.344] Using tsserver from: c:\Progetti\***\Source\***\node_modules\typescript\lib
[Info  - 14:15:58.349] <syntax> Forking...
[Info  - 14:15:58.358] <syntax> Starting...
[Info  - 14:15:58.360] <semantic> Forking...
[Info  - 14:15:58.367] <semantic> Starting...
[Error  - 14:16:09.501] ReaderError
SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at t.Reader.onLengthData (c:\Users\***\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:218987)
	at Socket.<anonymous> (c:\Users\***\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:218657)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
[Error  - 14:16:09.503] ReaderError
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be an integer. Received NaN
	at Function.concat (buffer.js:449:5)
	at l.append (c:\Users\***\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:217663)
	at t.Reader.onLengthData (c:\Users\***\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:218730)
	at Socket.<anonymous> (c:\Users\***\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\typescript-language-features\dist\extension.js:1:218657)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.42.0-insider (f3dbcea32a6b52ce819dc863e778fb8517357f61, 2020-01-24T05:38:14.538Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (16.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
tsco|alj|1.0.16
vscode-typescript-refactors|can|0.0.22
xml|Dot|2.5.0
gitlens|eam|10.2.0
tsl-problem-matcher|eam|0.1.0
vscode-npm-script|eg2|0.3.10
todo-tree|Gru|0.0.166
intellij-idea-keybindings|k--|0.2.37
vscode-html-format|moh|0.0.3
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.1510
debugger-for-chrome|msj|4.12.5
vscode-react-native|msj|0.14.0
gulptasks|nic|1.3.1
material-icon-theme|PKi|3.9.2
vscode-multiclip|sle|0.1.5

</details>

**Comment by MikeMatusz** [comment]
Commented on the closed issue, but also going to repeat it here since I wouldn't want to see this one closed in haste.  Lots of developers can't just upgrade their application to use TS 3.7, so I'm not sure that's a valid reason to mark this resolved.

**Comment by mjbvz** [comment]
@Balrog994 What if you use TS 3.7.5 (VS Code's 1.42's version)?

**Comment by Balrog994** [comment]
I was able to reproduce the problem only using older versions of the typescript compiler.

Using the typescript version included with visual studio code it actually works as expected.

Me and my team can easily upgrade to the new typescript compiler but it may not be as easy for others, as @MikeMatusz pointed out.

**Comment by mjbvz** [comment]
@aeschli There are enough reports of people suddenly seeing this that I do think something has changed on the VS Code side. Specifically, I believe that `typescript-vscode-sh-plugin` is causing this.

Please make sure that that plugin does not write anything to stdout (https://github.com/aeschli/typescript-vscode-sh-plugin/blob/3ec91d8aa4e1ccc81e725b4b1ce2baa465fad7ad/src/index.ts#L24)

VS Code uses the stdout from the typescript server. If any arbitrary info is written to it, there will be issues. Please use the typescript log methods for writing output instead: https://github.com/microsoft/typescript-tslint-plugin/blob/master/src/logger.ts

**Comment by aeschli** [comment]
Thanks @mjbvz for the analysis and directions. I changed to using the logger.
