### ISSUE TITLE
Crash on Ubuntu 18.04.3

### ISSUE THREAD

**Issue by sakno** [microsoft/vscode#89370]
- VSCode Version: 1.41.1 (hash 26076a4de974ead31f97692a0d32f90d735645c0)
- OS Version: Ubuntu 18.04.3, Kernel 4.15.0-74-generic
- Desktop Environment: GNOME Shell 3.28.4 

vscode closes unexpectedly after startup in a few seconds. The same issue for Insiders build (1.42.0-insider, hash 35116fa958d6622df1c31b4d84810b999a858170). `--disable-extensions` with no luck. However, previous version of Insiders build was working perfectly. The issue is reproducible on X.org and Wayland.
`--verbose` flag shows nothing interesting:
```
(process:5964): Gtk-WARNING **: 21:49:47.742: Locale not supported by C library.
	Using the fallback 'C' locale.
[main 2020-01-27T19:49:47.951Z] Starting VS Code
[main 2020-01-27T19:49:47.952Z] from: /snap/code-insiders/357/usr/share/code-insiders/resources/app
[main 2020-01-27T19:49:47.952Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  version: false,
  help: false,
  telemetry: false,
  'list-extensions': false,
  'show-versions': false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'disable-extensions': true,
  'disable-gpu': false,
  'extension-development-confirm-save': false,
  logExtensionHostCommunication: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'disable-user-env-probe': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  trace: false,
  'force-user-env': false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-error': false,
  'allow-insecure-localhost': false
}
[5964:0127/214951.768254:INFO:CONSOLE(1594)] "%cTRACE", source: file:///snap/code-insiders/357/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js (1594)
Server response: <?xml version="1.0" encoding="UTF-8"
```

Information about crash from gdb:
```
Core was generated by `/snap/code-insiders/357/usr/share/code-insiders/code-insiders --disable-extensions'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fbc49b8775c in ?? ()
[Current thread is 1 (LWP 7796)]
(gdb) bt
#0  0x00007f8fedfc775c in ?? ()
   from /snap/core/current/lib64/ld-linux-x86-64.so.2
#1  0x00007f8fedfd0861 in ?? ()
   from /snap/core/current/lib64/ld-linux-x86-64.so.2
#2  0x00007f8fedfcb574 in ?? ()
   from /snap/core/current/lib64/ld-linux-x86-64.so.2
#3  0x00007f8fedfcfdb9 in ?? ()
   from /snap/core/current/lib64/ld-linux-x86-64.so.2
#4  0x00007f8fe762f5ad in ?? ()
   from /snap/core/current/lib/x86_64-linux-gnu/libc.so.6
#5  0x00007f8fedfcb574 in ?? ()
   from /snap/core/current/lib64/ld-linux-x86-64.so.2
#6  0x00007f8fe762f664 in __libc_dlopen_mode ()
   from /snap/core/current/lib/x86_64-linux-gnu/libc.so.6
#7  0x00007f8fe7601a85 in ?? ()
   from /snap/core/current/lib/x86_64-linux-gnu/libc.so.6
#8  0x00007f8fed79ca99 in __pthread_once_slow ()
   from /snap/core/current/lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00007f8fe7601ba4 in backtrace ()
   from /snap/core/current/lib/x86_64-linux-gnu/libc.so.6
```

**Comment by sakno** [comment]
The workaround is simple: I just switched from snap to deb package.

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders https://code.visualstudio.com/insiders ?

**Comment by sakno** [comment]
Unfortunately I can't say. Since my first post I switched to deb package instead of snap and I'm using Ubuntu 20.04.01 now.

**Comment by deepak1556** [comment]
Closing per above comment, thanks!
