### ISSUE TITLE
VS code does not close after git push

### ISSUE THREAD

**Issue by asmalik** [microsoft/vscode#89528]
Hi,
Every time after pushing my work in my azure repos, I was not abble to close the editor. 
Using exit under file menu does nothing either.
The problem happen 
I have to kill the process in window task manager in order to close it

I recorded the issue (please find it in the zip file).

Regards,

Malik

- VSCode Version: 1.41.1(system setup)
- OS Version: Windows_NT x64 10.0.18362
[Bug.zip](https://github.com/microsoft/vscode/files/4123664/Bug.zip)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by asmalik** [comment]
Ok I will do try

**Comment by bpasero** [comment]
Thanks

**Comment by asmalik** [comment]
Hi,
I had the same problem with vs insiders 

Best regards,
[tested on  vs insiders.zip](https://github.com/microsoft/vscode/files/4176347/tested.on.vs.insiders.zip)

Version: 1.43.0-insider (system setup)
Commit: beaf391bc53136912e4f0bbdfb7844ad954247db
Date: 2020-02-07T05:29:40.363Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by bpasero** [comment]
@asmalik thanks for the video that is really helpful to understand what you do. I cannot explain this behaviour. Can you run "`code --verbose`" from the command line and see that you capture the output, especially when you click on the File > Exit or window close buttons?

**Comment by asmalik** [comment]
Ok I'll do it

**Comment by bpasero** [comment]
Thanks

**Comment by asmalik** [comment]
Hi @bpasero,
Here is a new video after git push.

Thanks
[verbose_cmd.zip](https://github.com/microsoft/vscode/files/4187945/verbose_cmd.zip)

**Comment by bpasero** [comment]
@asmalik the interesting part is the output of the window you start first, can you:
* run "code --verbose" from the command line
* from that window that opens get to the stuck state where exit does nothing
* attach the output from the terminal you get

**Comment by asmalik** [comment]
@bpasero when I run the commande it lunch a new instance of vs code
Here is what I got:
[main 2020-02-12T15:37:32.508Z] Sending some foreground love to the running instance: 5632
[main 2020-02-12T15:37:32.512Z] Sending env to running instance...
[main 2020-02-12T15:37:32.573Z] Sent env to running instance. Terminating...
[main 2020-02-12T15:37:32.573Z] Lifecycle#kill()

**Comment by bpasero** [comment]
@asmalik yeah that is right, what I meant is: start the first version like that from the terminal. Ensure no other version is running. You should see a ton of output.

**Comment by asmalik** [comment]
@bpasero 
C:\WINDOWS\system32>code --verbose

[main 2020-02-12T15:44:52.073Z] Sending some foreground love to the running instance: 5632
[main 2020-02-12T15:44:52.076Z] Sending env to running instance...
[main 2020-02-12T15:44:52.140Z] Sent env to running instance. Terminating...
[main 2020-02-12T15:44:52.140Z] Lifecycle#kill()

C:\WINDOWS\system32>code --verbose

[main 2020-02-12T15:45:47.086Z] Starting VS Code
[main 2020-02-12T15:45:47.087Z] from: c:\Program Files\Microsoft VS Code\resources\app
[main 2020-02-12T15:45:47.087Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  version: false,
  help: false,
  telemetry: false,
  'list-extensions': false,
  'show-versions': false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'disable-extensions': false,
  'disable-gpu': false,
  'extension-development-confirm-save': false,
  logExtensionHostCommunication: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'disable-user-env-probe': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  trace: false,
  'force-user-env': false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false
}
[main 2020-02-12T15:45:47.090Z] Resolving machine identifier...
[main 2020-02-12T15:45:47.090Z] Resolved machine identifier: 1cbf50478655309b45ae95d6ffebbe29e51d3d1e8879e21b80d5e936ab84f0d0 (trueMachineId: undefined)
[main 2020-02-12T15:45:47.122Z] update#setState idle
[main 2020-02-12T15:45:47.124Z] [storage state.vscdb] open(c:\Users\Malik's PC\AppData\Roaming\Code\User\globalStorage\state.vscdb, retryOnBusy: true)
[main 2020-02-12T15:45:47.124Z] lifecycle (main): phase changed (value: 2)
[main 2020-02-12T15:45:47.125Z] windowsManager#open
[main 2020-02-12T15:45:47.187Z] lifecycle (main): phase changed (value: 3)
[main 2020-02-12T15:45:47.189Z] telemetry/optInStatus { optIn: true }
[main 2020-02-12T15:45:47.189Z] telemetry/update:win32SetupTarget { target: 'system' }
[main 2020-02-12T15:45:47.190Z] telemetry/machineIdFallback { usingFallbackGuid: false }
[main 2020-02-12T15:45:47.259Z] [storage state.vscdb] Trace (event): PRAGMA user_version = 1;
[main 2020-02-12T15:45:47.263Z] [storage state.vscdb] Trace (event): CREATE TABLE IF NOT EXISTS ItemTable (key TEXT UNIQUE ON CONFLICT REPLACE, value BLOB)
[main 2020-02-12T15:45:47.263Z] [storage state.vscdb] Trace (event): SELECT * FROM ItemTable
[main 2020-02-12T15:45:47.265Z] [storage state.vscdb] getItems(): 54 rows
[main 2020-02-12T15:45:47.340Z] getShellEnvironment: running on Windows, skipping
[main 2020-02-12T15:45:47.368Z] [storage state.vscdb] updateItems(): insert(Map(2) {telemetry.lastSessionDate => Wed, 12 Feb 2020 13:54:20 GMT, telemetry.currentSessionDate => Wed, 12 Feb 2020 15:45:47 GMT}), delete(Set(0) {})
[main 2020-02-12T15:45:47.369Z] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[main 2020-02-12T15:45:47.370Z] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('telemetry.lastSessionDate','Wed, 12 Feb 2020 13:54:20 GMT'),('telemetry.currentSessionDate','Wed, 12 Feb 2020 15:45:47 GMT')
[main 2020-02-12T15:45:47.372Z] [storage state.vscdb] Trace (event): END TRANSACTION
[7868:0212/164547.842:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164547.873:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164547.873:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164547.878:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164547.878:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164547.881:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164547.881:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.034:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.074:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[main 2020-02-12T15:45:48.070Z] IPC#vscode-workbenchReady
[7868:0212/164548.086:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.164:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.208:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.208:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.208:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.212:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.212:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.264:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.280:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.320:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.363:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.452:INFO:CONSOLE(333)] "Overwriting extension <<.liquid>> to now point to mime <<text/x-html>>", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (333)
[7868:0212/164548.504:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.504:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.508:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.528:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.580:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.680:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.768:INFO:CONSOLE(1572)] "%cDEBUG", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.768:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.883:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164548.883:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164549.423:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164549.423:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164549.423:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164549.423:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164549.423:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164549.423:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164549.423:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164549.483:INFO:CONSOLE(254)] "%c[Extension Host] %cLooking for parseable documents... %c(at c:\Users\Malik's PC\.vscode\extensions\zignd.html-css-class-completion-1.19.0\out\src\extension.js:28:21)", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (254)
[7868:0212/164549.507:INFO:CONSOLE(254)] "%c[Extension Host] %cFound no documents %c(at c:\Users\Malik's PC\.vscode\extensions\zignd.html-css-class-completion-1.19.0\out\src\extension.js:31:25)", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (254)
[7868:0212/164549.511:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164549.511:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164549.511:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164549.511:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164549.511:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164549.515:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164549.523:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164549.547:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164549.752:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164550.549:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164550.590:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164550.590:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164550.590:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164550.590:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164550.590:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164550.590:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164550.590:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164550.595:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164550.595:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164550.655:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164550.655:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164550.655:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164550.655:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[main 2020-02-12T15:45:50.662Z] RequestService#request https://update.code.visualstudio.com/api/update/win32-x64/stable/26076a4de974ead31f97692a0d32f90d735645c0
[7868:0212/164550.799:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164550.799:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164550.799:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)
[7868:0212/164550.956:INFO:CONSOLE(1572)] "%cTRACE", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js (1572)

**Comment by asmalik** [comment]
@bpasero 
[code_verbose.txt](https://github.com/microsoft/vscode/files/4193220/code_verbose.txt)

**Comment by bpasero** [comment]
@asmalik it also seems to me you are not on the latest version, can you update to 1.42?

That log does not contain anything after a few lines that points me into a direction unfortunately...

**Comment by asmalik** [comment]
@bpasero 
Ok i'll install the latest update.

**Comment by bpasero** [comment]
Good, let me know if that helps.

**Comment by asmalik** [comment]
Hello @bpasero,
Since I uninstalled the EasySettingBox software I did not ran into the the problem. I'm going to close the issue.
Thanks for your help
