### ISSUE TITLE
[FileExplorer] Tree element not found

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#89609]
I do not see this, but looks like the old tree error.

Reported by @jrieken
```
 ERR TreeError [FileExplorer] Tree element not found: [object Object]: Error: TreeError [FileExplorer] Tree element not found: [object Object]
    at CompressedObjectTreeModel.getCompressedNode (file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:223:23)
    at CompressedObjectTreeModel.isCollapsible (file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:187:41)
    at CompressibleObjectTreeModel.isCollapsible (file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:332:31)
    at CompressibleObjectTree.isCollapsible (file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/tree/abstractTree.js:1104:31)
    at WorkbenchCompressibleAsyncDataTree.expand (file:///Users/jrieken/Code/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:359:28)
    at async ExplorerView.onSelectResource (file:///Users/jrieken/Code/vscode/out/vs/workbench/contrib/files/browser/views/explorerView.js:505:17)
```

**Comment by joaomoreno** [comment]
Repro steps:

1. Open the `vscode` repo
