### ISSUE TITLE
TypeScript service died 5 times after got restarted

### ISSUE THREAD

**Issue by dalisoft** [microsoft/vscode#89638]
Issue Type: <b>Bug</b>

I just worked on JS project and suddenly happened and shown button to report issue

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.33.0
vscode-eslint|dba|2.0.15
EditorConfig|Edi|0.14.4
vscode-npm-script|eg2|0.3.10
LogFileHighlighter|emi|2.7.1
prettier-vscode|esb|3.20.0
reasonml|fre|1.0.38
customize-ui|ioc|0.1.32
monkey-patch|ioc|0.1.7
dotenv|mik|1.0.1
HTMLHint|mka|0.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3
material-icon-theme|PKi|3.9.2
vscode-yaml|red|0.6.1
postcss|ric|2.0.0
code-settings-sync|Sha|3.4.3
vscode-todo-highlight|way|1.0.4

</details>

**Comment by thanpolas** [comment]
This is becoming a real pain. I've lost quite some time troubleshooting this. With the help of verbose debug logs for typescript I discovered that the typescript module breaks on illegal JSDoc strings.

For instance this JSDoc string:

```
/**
 *
 * @param {Redis} redisClient Redis instance.
 */
```

Will break typescript with the following error I've pasted bellow. The problem is that this fails silently without giving the opportunity to fix. The workflow to fix the issue right now is opening the log file for each TS instance that fails, and they fail 5x times in a row, so it's 5 logs of the same failure.


### Error Log

Redacted sensitive info with `***`.

```
Info 57   [18:30:34.704] FileWatcher:: Added:: WatchInfo: /Users/thanpolas/Projects/***.js 500 Project:  WatchType: Closed Script info
Info 58   [18:30:34.746] FileWatcher:: Added:: WatchInfo: /Users/thanpolas/Projects/***.js 500 Project:  WatchType: Closed Script info
Err 59    [18:30:37.727] Exception on executing command {"seq":2,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"/Users/thanpolas/Projects/***.js","fileContent":"***","projectRootPath":"/Users/thanpolas/Projects/***","scriptKindName":"JS"}]}}:

    Cannot read property 'exports' of undefined

    TypeError: Cannot read property 'exports' of undefined
        at declareModuleMember (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29355:63)
        at delayedBindJSDocTypedefTag (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30699:29)
        at bindSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29071:17)
        at Object.bindSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29005:9)
        at initializeTypeChecker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:64384:20)
        at Object.createTypeChecker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33622:9)
        at Object.getTypeChecker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:95612:79)
        at synchronizeHostData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:130645:21)
        at Object.getProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:130727:13)
        at InferredProject.Project.updateGraphWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:135078:53)
        at InferredProject.Project.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:135021:42)
        at ProjectService.assignOrphanScriptInfoToInferredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:136832:25)
        at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138215:26)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138417:107
        at Object.mapDefined (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:565:30)
        at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138417:48)
        at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:139271:46)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:88
        at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140920:28)
        at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:33)
        at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140952:35)
        at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:142267:27)
        at Interface.emit (events.js:200:13)
        at Interface._onLine (readline.js:314:10)
        at Interface._normalWrite (readline.js:459:12)
        at Socket.ondata (readline.js:170:10)
        at Socket.emit (events.js:200:13)

```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

What if you upgrade your workspace to use `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)?

**Comment by dalisoft** [comment]
@mjbvz Thanks for quick reply. I don’t have time to do these steps. For me not critical this bug, just shown as notification and recommended me to Submit as issue, i did it for let you know. 
Should mention, when this happened, autocompletation also was stopped. 
If you want you can close issue

**Comment by mjbvz** [comment]
Let me know if you see this in insiders with extensions disabled

**Comment by thanpolas** [comment]
hello @mjbvz, I confirm the issue persists when all extensions have been disabled and VSC restarted. This is an issue that a lot of my collegues have in multiple companies.

Something changed in the parsing of the docblocks, all our codebases used to work perfectly fine.

My VSC version:

```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```
