### ISSUE TITLE
TypeScript service died 5 times after got restarted 

### ISSUE THREAD

**Issue by thanpolas** [microsoft/vscode#89689]
I was in issue #89638 which was abruptly closed unfairly.

Please don't close this issue until it's resolved, this is a rampant issue that needs addressing:

![related issues](https://cdn-std.droplr.net/files/acc_551565/X58dbZ)

**Comment by thanpolas** [comment]
I am posting my history on this issue again:

This is becoming a real pain. I've lost quite some time troubleshooting this. With the help of verbose debug logs for typescript I discovered that the typescript module breaks on illegal JSDoc strings.

For instance this JSDoc string:

```
/**
 *
 * @param {Redis} redisClient Redis instance.
 */
```

Will break typescript with the following error I've pasted bellow. The problem is that this fails silently without giving the opportunity to fix. The workflow to fix the issue right now is opening the log file for each TS instance that fails, and they fail 5x times in a row, so it's 5 logs of the same failure.


### Error Log

Redacted sensitive info with `***`.

```
Info 57   [18:30:34.704] FileWatcher:: Added:: WatchInfo: /Users/thanpolas/Projects/***.js 500 Project:  WatchType: Closed Script info
Info 58   [18:30:34.746] FileWatcher:: Added:: WatchInfo: /Users/thanpolas/Projects/***.js 500 Project:  WatchType: Closed Script info
Err 59    [18:30:37.727] Exception on executing command {"seq":2,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"/Users/thanpolas/Projects/***.js","fileContent":"***","projectRootPath":"/Users/thanpolas/Projects/***","scriptKindName":"JS"}]}}:

    Cannot read property 'exports' of undefined

    TypeError: Cannot read property 'exports' of undefined
        at declareModuleMember (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29355:63)
        at delayedBindJSDocTypedefTag (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:30699:29)
        at bindSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29071:17)
        at Object.bindSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:29005:9)
        at initializeTypeChecker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:64384:20)
        at Object.createTypeChecker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:33622:9)
        at Object.getTypeChecker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:95612:79)
        at synchronizeHostData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:130645:21)
        at Object.getProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:130727:13)
        at InferredProject.Project.updateGraphWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:135078:53)
        at InferredProject.Project.updateGraph (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:135021:42)
        at ProjectService.assignOrphanScriptInfoToInferredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:136832:25)
        at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138215:26)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138417:107
        at Object.mapDefined (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:565:30)
        at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138417:48)
        at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:139271:46)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:88
        at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140920:28)
        at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:33)
        at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140952:35)
        at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:142267:27)
        at Interface.emit (events.js:200:13)
        at Interface._onLine (readline.js:314:10)
        at Interface._normalWrite (readline.js:459:12)
        at Socket.ondata (readline.js:170:10)
        at Socket.emit (events.js:200:13)

```




I confirm the issue persists when all extensions have been disabled and VSC restarted. This is an issue that a lot of my collegues have in multiple companies.

Something changed in the parsing of the docblocks, all our codebases used to work perfectly fine.

My VSC version:

```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

**Comment by thanpolas** [comment]
@mjbvz to reproduce the issue, open a new VSC without extensions, create a javascript file and add paste the following:

```javascript
/**
 * Test
 *
 * @param {Redis} client Redis client.
 */
const fn = async (client) => {
};
```

**Comment by mjbvz** [comment]
I can't repo this in an empty folder containing that js file

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by thanpolas** [comment]
hey @mjbvz the problem persists with the latest VS Code insiders build.

The problem is that I can't reproduce it on an empty repository either.

The issue triggers on my private project when I input an illegal JSDoc param as I've described above. At this point all I can offer is the error log pasted above.

If I manage to create a setup case I will get back to you. But please, this is a real issue that needs chasing down.

**Comment by mjbvz** [comment]
We can't investigate this without repo steps: https://github.com/microsoft/TypeScript/issues/35214

Please provide an example repo that demonstrates the issue

**Comment by thanpolas** [comment]
@mjbvz the users of this software (VSCode) have massively indicated there is a real problem. In the open source community it always remains debatable whose responsibility it is to chase down and figure out how to fix the problem. 

I will leave that decision to you. If you feel like that's the users' responsibility as you've stated here, then so be it.

I have dedicated more hours on this topic than I should have and have demonstrated through a simple github issue search that the issue is rampant as reported by multiple users.

I will not investigate further as I don't believe an editor should take up more of my time than it needs to be installed and configured on my PC. An editor is a tool I should not be bothered with or bleed time for.

I'd much rather switch to another editor.

**Comment by mjbvz** [comment]
You are probably a developer so ask yourself: what exactly do you expect us to do without logs and without a repo? The reason you see a lot of issues with similar names is because there are tons of different root causes that can trigger these symptoms.

If you can not help that’s fine, but don’t keep complaining then that we’re not fixing your issue

**Comment by thanpolas** [comment]
I am not complaining, I am stating it because that is what is happening. I have helped as much as I could by providing logs and a rough repro case.

Do not shoot the messenger @mjbvz, I am not the problem.

**Comment by thanpolas** [comment]
The issue is reproducible on one of my OSS packages: https://github.com/thanpolas/middlewarify

clone the project and open it with VSC.

I suspect the issue is with the way modules are exported:

```js
const modName = module.exports = {};
```

**Comment by mjbvz** [comment]
Thanks! I've opened https://github.com/microsoft/TypeScript/issues/36983 to track this upstream

**Comment by RyanCavanaugh** [comment]
@thanpolas really appreciate the repro information, big thanks!
