### ISSUE TITLE
Smoke Test CSS failures

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#89796]
On Windows, the following CSS smoke tests are failing.

```
7) Running Code
       CSS
         verifies warnings for the empty rule:
     Error: Timeout: get element '.panel.markers-panel' after 20 seconds.
      at C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:8:58)

  8) Running Code
       CSS
         verifies that warning becomes an error once setting changed:
     Error: Timeout: get element '.panel.markers-panel' after 20 seconds.
      at C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:8:58)
```

**Comment by sbatten** [comment]
yea, looks like this css selector should be updated https://github.com/microsoft/vscode/blob/2205002a2c64f1e3d9021ef042c1d89002bb89b3/test/automation/src/problems.ts#L15
