### ISSUE TITLE
Smoke Test debug failures

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#89797]
On Windows the following debug smoke tests are failing

```
9) Running Code
       Debug
         configure launch json:
     Error: ENOENT: no such file or directory, open 'C:\Users\alros\AppData\Local\Temp\t216528tOfleY3NHzi\vscode-smoketest-express\.vscode\launch.json'
      at Object.openSync (fs.js:443:3)
      at Object.readFileSync (fs.js:343:35)
      at Context.<anonymous> (out\areas\debug\debug.test.js:20:32)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  10) Running Code
       Debug
         start debugging:
     Error: Timeout: get element '.statusbar.debugging' after 20 seconds.
      at C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:8:58)

  11) Running Code
       Debug
         focus stack frames and variables:
     Error: Timeout: get elements 'div[id="workbench.view.debug"] .debug-variables .monaco-list-row .expression' after 20 seconds.      at C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:8:58)

  12) Running Code
       Debug
         stepOver, stepIn, stepOut:
     Error: Timeout: get elements 'div[id="workbench.view.debug"] .monaco-list-row .stack-frame' after 20 seconds.
      at C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:8:58)

  13) Running Code
       Debug
         continue:
     Error: Timeout: click '.debug-toolbar .action-label[title*="Continue"]' after 20 seconds.
      at C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:8:58)

  14) Running Code
       Debug
         debug console:
     Error: Timeout: get text content ' .monaco-editor[data-uri$="debug:replinput"] .view-lines' after 20 seconds.
      at C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:8:58)

  15) Running Code
       Debug
         debug console link:
     Error: Timeout: get text content ' .monaco-editor[data-uri$="debug:replinput"] .view-lines' after 20 seconds.
      at C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:8:58)
```

**Comment by isidorn** [comment]
I have moved the debug smoke test to integration tests.
Thus this is no longer valid.
The integration tests do not behave flaky so far.
