### ISSUE TITLE
Smoke Test status bar test failing

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#89798]
The following status bar smoke test is failing

```
 16) Running Code
       Statusbar
         verifies that 'Problems View' appears when clicking on 'Problems' status element:
     Error: Timeout: get element '.panel.markers-panel' after 20 seconds.
      at C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\alros\repos\vscode\vscode\test\automation\out\code.js:8:58)
```

**Comment by alexr00** [comment]
I verified this one manually and it is ok.

**Comment by bpasero** [comment]
I see the problems view opening properly, but we might have an issue finding the problems panel given this selector: `static PROBLEMS_VIEW_SELECTOR = '.panel.markers-panel';`

**Comment by sandy081** [comment]
/duplicate 

https://github.com/microsoft/vscode/issues/89796
