### ISSUE TITLE
default error in debug

### ISSUE THREAD

**Issue by buldi** [Microsoft/vscode#8999]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 4.4.0-29-generic

Steps to Reproduce:

1. start code
2. HELP->Toggle Developers Tools

Error: 13...*

shell.ts:416 Cannot read property 'version' of undefined: TypeError: Cannot read property 'version' of undefined
    at t.Object.defineProperty.get [as latestVersion] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:81:21735)
    at t.Object.defineProperty.get [as outdated] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:81:23158)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:105:4512
    at Array.reduce (native)
    at e.onServiceChange (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:105:4480)
    at e.invoke (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:37:16332)
    at e.fire (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:37:18116)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:81:24683
    at Object.g [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:7416)
    at Object.W.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:10994)

**Comment by joaomoreno** [comment]
#8859
