### ISSUE TITLE
Integration tests: terminal throws exceptions

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90046]
Seeing this when running integration tests with latest today:

```
Unknown terminal: 18: Error: Unknown terminal: 18
    at MainThreadTerminalService._getTerminalProcess (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadTerminalService.js:282:23)
    at MainThreadTerminalService.$sendProcessReady (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadTerminalService.js:229:18)
    at RPCProtocol._doInvokeHandler (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:331:27)
    at RPCProtocol._invokeHandler (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:316:45)
    at RPCProtocol._receiveRequest (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:243:32)
    at RPCProtocol._receiveOneMessage (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:171:26)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:61:52
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:459:38)
    at BufferedEmitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:361:35)
    at PersistentProtocol._receiveMessage (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:580:37)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:454:83
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:459:38)
    at ProtocolReader.acceptChunk (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:187:37)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:156:61
    at Socket.listener (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.net.js:16:40)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
```

```
[46612:0205/072944.291888:INFO:CONSOLE(1)] "xterm.js: Terminal.open was called on an element that was not attached to the DOM", source: /Users/bpasero/Development/Microsoft/monaco/node_modules/xterm/lib/xterm.js (1)
Unknown terminal: 14: Error: Unknown terminal: 14
    at MainThreadTerminalService._getTerminalProcess (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadTerminalService.js:282:23)
    at MainThreadTerminalService.$sendProcessReady (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/api/browser/mainThreadTerminalService.js:229:18)
    at RPCProtocol._doInvokeHandler (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:331:27)
    at RPCProtocol._invokeHandler (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:316:45)
    at RPCProtocol._receiveRequest (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:243:32)
    at RPCProtocol._receiveOneMessage (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:171:26)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/services/extensions/common/rpcProtocol.js:61:52
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:459:38)
    at BufferedEmitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:361:35)
    at PersistentProtocol._receiveMessage (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:580:37)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:454:83
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:459:38)
    at ProtocolReader.acceptChunk (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:187:37)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:156:61
    at Socket.listener (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.net.js:16:40)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by bpasero** [comment]
Looking at test output for 1 week now, I cannot stand this exception as I always think something is broken. PR: https://github.com/microsoft/vscode/pull/90581
