### ISSUE TITLE
Upgrade VSCode to 1.3.0 and cannot load/install extensions

### ISSUE THREAD

**Issue by renkun-ken** [Microsoft/vscode#9007]
- VSCode Version: 1.3.0
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Upgrade VSCode from a previous version (1.2.x) to 1.3.0
2. Open VSCode and no extension is loaded, nor can I install any extensions.
3. Toggle Developer Tools and a lot of errors occurs increasingly and when I try to install an extension more of the same error occurs.

Here's the error message:

```
workbench.main.js:115 Cannot read property 'call' of undefined: TypeError: Cannot read property 'call' of undefined,    at e.onCommonRequest (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:20045),    at e.onMessage (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19889),    at /usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19697,    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:23531),    at emitOne (events.js:90:13),    at Socket.emit (events.js:182:7),    at readableAddChunk (_stream_readable.js:153:18),    at Socket.Readable.push (_stream_readable.js:111:10),    at Pipe.onread (net.js:531:20)e.onUnexpectedError @ workbench.main.js:115(anonymous function) @ workbench.main.js:115e.onUnexpectedError @ workbench.main.js:37u @ workbench.main.js:37(anonymous function) @ workbench.main.js:38(anonymous function) @ workbench.main.js:38
workbench.main.js:38 WARNING: Promise with no error callback:45
```

A screenshot:

![untitled-1 - visual studio code_024](https://cloud.githubusercontent.com/assets/4662568/16708949/819a7740-4635-11e6-8d03-2eeead945a3b.png)

**Comment by bpasero** [comment]
Please see https://github.com/Microsoft/vscode/issues/8859#issuecomment-231410408 for a solution!

**Comment by renkun-ken** [comment]
This solves my problem, thanks!
