### ISSUE TITLE
Attempts to use remote-ssh but the window crashes

### ISSUE THREAD

**Issue by nekome** [microsoft/vscode#90191]
Issue Type: <b>Bug</b>

Using remote-ssh to the Linux environment on WSL and other VMs, VScode crashes with a message that the window has crashed.
No error message detail is displayed because it is forcibly terminated.

- Source Environment
Windows 10 pro (newer)
VSCode (1.42.0)

- distination environment
WSL: DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
VM: DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

[![2020-02-07_10h01_13](https://user-images.githubusercontent.com/10954236/73992652-1c2db880-4993-11ea-9d13-c7eab8eab40b.png)
](url)
-----------------------------------------------------------------------
VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|25.96GB (14.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform-autocomplete|erd|0.0.8
terraform|mau|1.4.0
vscode-language-pack-ja|MS-|1.42.2
remote-containers|ms-|0.101.0
remote-ssh|ms-|0.49.0
remote-ssh-edit|ms-|0.49.0
remote-wsl|ms-|0.42.3
vscode-remote-extensionpack|ms-|0.19.0
azure-account|ms-|0.8.8
code-settings-sync|Sha|3.4.3

</details>

**Comment by roblourens** [comment]
Can you give more details? What steps exactly did you do before this? And does vscode work fine in other scenarios?

**Comment by nekome** [comment]
thank you for your reply.
I will write a little more in detail.

Environment
-----------------------------------------------------------------------  
```
PC_A (Windows 10 pro)
PC_B (Windows 10 pro)

PC_A  -----> [ PC_B ----------> VirtualBox ----------> VirtualBox Linux (ubuntu) ]  
  L--------> [ PC_A ----------> WSL (ubuntu) ] 

PC_B ---->[ PC_B ----------> VirtualBox ----------> VirtualBox Linux (ubuntu) ] 

```
-----------------------------------------------------------------------  
I cannot connect to VirtualBox Linux and WSL Linux with remote-ssh from PC_A.
PC_B can connect normally to VirtualBox Linux (ubuntu) and can edit files.
The VSCode version is the same for both.
The SSH uses the following.
`C:\Windows\System32\OpenSSH\ssh.exe`

Other things I tried.
- re-installed VSCode 2 times.
- installed insider VSCode.
- re-install open-ssh on Windows.
- disabled anti-virus software.
-----------------------------------------------------------------------
screenshots of the error messages.

PC_A  -----> [ PC_B ----------> VirtualBox ----------> VirtualBox Linux (ubuntu) ]

Steps: 
Click "Remote-ssh connect to Host..."
Connecting to "VirtualBox Linux (ubuntu)"
An error message is displayed and can't open files in VirtualBox Linux (ubuntu).
![2020-02-08_18h04_00](https://user-images.githubusercontent.com/10954236/74083016-c3e5dc00-4aa2-11ea-929d-6d130ade7d76.png)

[ PC_A ----------> WSL (ubuntu) ] 

Steps: 
Click "Remote-WSL: New window."
Connecting to WSL (ubuntu).
An error message is displayed and can't open files in WSL (ubuntu).
![2020-02-08_18h10_29](https://user-images.githubusercontent.com/10954236/74083018-c47e7280-4aa2-11ea-9ee8-2e4988cb3dd5.png)


PC_A remote-ssh log
```
[18:19:15.953] Remote server is listening on port 41527
[18:19:15.953] Parsed server configuration: {"agentPort":41527,"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/1000"}
[18:19:15.955] Starting forwarding server. localPort 56040 -> socksPort 56037 -> remotePort 41527
[18:19:15.956] Forwarding server listening on 56040
[18:19:15.956] Waiting for ssh tunnel to be ready
[18:19:15.957] Tunneled remote port 41527 to local port 56040
[18:19:15.957] Resolved "ssh-remote+mkubuvm" to "127.0.0.1:56040"
[18:19:15.958] [Forwarding server 56040] Got connection 0
[18:19:15.965] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"success","osReleaseId":"ubuntu","arch":"x86_64","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0"},"measures":{"resolveAttempts":1,"retries":1}}
[18:19:15.966] ------
[18:19:16.029] [Forwarding server 56040] Got connection 1
[18:19:16.030] [Forwarding server 56040] Got connection 2
```
VSCode LOG (Window)
```
[2020-02-08 18:19:16.073] [renderer4] [error] read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
[2020-02-08 18:19:46.025] [renderer4] [error] [remote-connection] The time limit has been reached for a connection. Error:
[2020-02-08 18:19:46.025] [renderer4] [error] Error: Time limit reached
    at file:///F:/Dropbox/xyzxyz/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:1769:272
[2020-02-08 18:19:46.025] [renderer4] [error] [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
[2020-02-08 18:19:46.025] [renderer4] [error] Error: Time limit reached
    at file:///F:/Dropbox/xyzxyz/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:1769:272
```
VSCode LOG (Main)
```
[2020-02-08 18:16:59.959] [main] [info] update#setState idle
[2020-02-08 18:17:29.959] [main] [info] update#setState checking for updates
[2020-02-08 18:17:30.072] [main] [info] update#setState idle
[2020-02-08 18:18:47.345] [main] [error] [VS Code]: render process crashed!
[2020-02-08 18:18:51.192] [main] [error] [VS Code]: render process crashed!
[2020-02-08 18:18:55.186] [main] [error] [VS Code]: render process crashed!
```

PC_B remote-ssh log
```
[18:11:10.624] Remote server is listening on port 41527
[18:11:10.624] Parsed server configuration: 
{"agentPort":41527,"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/1000"}
[18:11:10.626] Starting forwarding server. localPort 49374 -> socksPort 49358 -> remotePort 41527
[18:11:10.626] Forwarding server listening on 49374
[18:11:10.627] Waiting for ssh tunnel to be ready
[18:11:10.628] [Forwarding server 49374] Got connection 0
[18:11:10.629] Tunneled remote port 41527 to local port 49374
[18:11:10.630] Resolved "ssh-remote+mkubu" to "127.0.0.1:49374"
[18:11:10.647] ------
[18:11:10.687] [Forwarding server 49374] Got connection 1
[18:11:10.688] [Forwarding server 49374] Got connection 2
```

**Comment by roblourens** [comment]
Hm, so what are the differences between your setup with PC A and PC B? Any differences in the network configuration? Also I don't understand this diagram

`PC_A  -----> [ PC_B ----------> VirtualBox ----------> VirtualBox Linux (ubuntu) ]  `

Is PC A connecting via PC B?

**Comment by nekome** [comment]
PC_A and PC_B had used the same VSCode binary via Dropbox.
VSCode on PC_A had been crashing when trying to connect to an Ubuntu in a virtual box on PC_B using remote-SSH since 2 months ago.

PC_A connects to Ubuntu through a Virtual box on PC_B.
PC_A --- (ssh) --- > PC_B's virtual box --- (SSH via Virtualbox NAT) ---> Ubuntu on Virtual box.

PC_A also connects to WSL hosted by PC_A itself.
PC_A to WSL is also unable to connect.

**Comment by roblourens** [comment]
Thanks for explaining. I don't think that how they connect or what they connect to makes a difference here, I can't see that causing a crash.

I am more interested in 

> PC_A and PC_B had used the same VSCode binary via Dropbox.


Could you try installing vscode on PC_A itself?

**Comment by nekome** [comment]
thank you for your help.

I have installed VScode by an installer to PC_A.
but the same error occurred.
![2020-02-16_19h21_37](https://user-images.githubusercontent.com/10954236/74603545-cc1fc600-50f7-11ea-9782-2947ea1d2dbd.png)

**Comment by roblourens** [comment]
Is it possible that you have a firewall or something else blocking communication with the remote server?

**Comment by nekome** [comment]
I temporarily disabled Kaspersky, but could not connect to the virtual machine via remote ssh.
Next, I uninstalled Kaspersky. 
Finally, I can now connect to the virtual machine via remote ssh.

Thank you for your help!
