### ISSUE TITLE
Python extension failing to install in remote server (ssh) with Unknown system error -122

### ISSUE THREAD

**Issue by gilesknap** [microsoft/vscode#90207]
## Environment data

- VS Code version: 1.41.1
- Microsoft Python Extension version: 2020.1.58038
- OS and version: 
  - client: Ubuntu 19.10
  - remote host: Redhat 7
- Python version: 
  - client: 3.7.5
  - remote: 3.7.2 

## Problem
(I originally posted this in https://github.com/microsoft/vscode-python/issues/9914 but have been asked to post to vscode)

The extension ms-python.python fails to install when I am running vscode remote server, the error reported is `Unknown system error -122`
Other extensions GitLens, LocalHistory, TodoTree installed in remote server with no issue.
The remote server is connected over ssh and all other features of remote VSCode seem fine.
When running VSCode in local mode on both the client and remote host, there are no issues and the python extension loads.

I have tried rebooting the remote server and deleting remote .vscode-server. Then attempting to install the python extension only with no other extensions. The error persists.

## Remote Server Log
```
[2020-02-05 11:17:09.749] [remoteagent] [info] Extension host agent started.
[2020-02-05 11:17:10.466] [remoteagent] [info] [127.0.0.1][bef2fa09][ManagementConnection] New connection established.
[2020-02-05 11:17:10.518] [remoteagent] [info] [127.0.0.1][62f7d07c][ExtensionHostConnection] New connection established.
[2020-02-05 11:17:11.186] [remoteagent] [info] [127.0.0.1][62f7d07c][ExtensionHostConnection] <6149> Launched Extension Host Process.
[2020-02-05 11:17:38.359] [remoteagent] [info] Installing extension: ms-python.python
[2020-02-05 11:17:40.328] [remoteagent] [info] Downloaded extension: ms-python.python /tmp/5aed8d4d-ee76-46e3-a5bc-68db21569178
[2020-02-05 11:18:26.880] [remoteagent] [error] Failed to install extension: ms-python.python Unknown system error -122: Unknown system error -122, close
[2020-02-05 11:20:11.094] [remoteagent] [info] Installing the extension: ms-python.python
[2020-02-05 11:20:50.044] [remoteagent] [error] Failed to install the extension: ms-python.python Unknown system error -122: Unknown system error -122, close
```
## Window Log
```
[2020-02-05 11:42:05.203] [renderer1] [error] [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
[2020-02-05 11:42:05.203] [renderer1] [error] Error: Connecting was canceled
    at e.resolveAuthority (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3494:473)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async B._scanAndHandleExtensions (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3847:200)
    at async B._initialize (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3371:119)
[2020-02-05 11:42:05.294] [renderer1] [error] Connecting was canceled: Error: Connecting was canceled
    at e.resolveAuthority (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3494:473)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async B._scanAndHandleExtensions (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3847:200)
    at async B._initialize (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3371:119)
[2020-02-05 11:46:06.617] [renderer1] [error] Error while installing 'ms-python.python' extension in the remote server. Unknown system error -122: Unknown system error -122, close
[2020-02-05 11:46:06.617] [renderer1] [info] Trying to download 'ms-python.python' extension locally and install
```
## Remote Extensions Log
```
[2020-02-05 11:44:56.183] [exthost] [info] extension host started
[2020-02-05 11:44:56.317] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2020-02-05 11:44:56.318] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/hgv27681/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/extensions/debug-auto-launch/dist/extension
[2020-02-05 11:44:56.386] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2020-02-05 11:44:56.387] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/hgv27681/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/extensions/emmet/dist/extension
[2020-02-05 11:44:56.472] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.git","_lower":"vscode.git"},"activationEvent":"*"}
[2020-02-05 11:44:56.472] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/hgv27681/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/extensions/git/dist/main
[2020-02-05 11:44:56.600] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-02-05 11:44:56.600] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/hgv27681/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/extensions/merge-conflict/dist/extension
[2020-02-05 11:44:56.655] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-02-05 11:44:56.656] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/hgv27681/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d735645c0/extensions/search-result/dist/extension.js
[2020-02-05 11:44:56.664] [exthost] [info] eager extensions activated
```

**Comment by gilesknap** [comment]
Thanks for the quick response. I had already searched through all other issues and did not see system error -22 elsewhere (a couple of system error -86 but they look like different problems). The issue you reference does not look similar to me.
