### ISSUE TITLE
Terminal Extension pty terminals should respect dimension overrides

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90437]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=67143&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=384d930d-6775-58a0-3817-a8714909e89a&l=398

```
  1) window namespace tests Terminal Extension pty terminals should respect dimension overrides:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: 105 == 10
      + expected - actual

      -105
      +10
      
      at extensions\vscode-api-tests\src\singlefolder-tests\terminal.test.ts:395:8
      at l.fire (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:48:652)
      at y.$acceptTerminalDimensions (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:662:970)
      at processTicksAndRejections (internal/process/task_queues.js:89:5)

```

**Comment by Tyriar** [comment]
I was disabling it in https://github.com/microsoft/vscode/pull/90101, was just waiting on a test pass before merging.
