### ISSUE TITLE
Typescript Built in Plugin is failing again and again

### ISSUE THREAD

**Issue by Shub1427** [microsoft/vscode#90668]
Issue Type: <b>Bug</b>

Typescript Server keeps on dying in MacOS.

_The TypeScript language service died 5 times right after it got started. The service will not be restarted._

Typescript server log error:

```
[Info  - 09:47:18.847] Killing TS Server
[Info  - 09:47:18.876] TSServer exited
[Info  - 09:47:18.876] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 09:47:18.879] <syntax> Forking...
[Info  - 09:47:18.882] <syntax> Starting...
[Info  - 09:47:18.884] <semantic> Forking...
[Info  - 09:47:18.887] <semantic> Starting...
[Info  - 09:47:28.996] Killing TS Server
[Info  - 09:47:29.28] TSServer exited
[Info  - 09:47:29.28] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 09:47:29.32] <syntax> Forking...
[Info  - 09:47:29.39] <syntax> Starting...
[Info  - 09:47:29.41] <semantic> Forking...
[Info  - 09:47:29.45] <semantic> Starting...
[Info  - 09:47:39.29] Killing TS Server
[Info  - 09:47:39.57] TSServer exited
[Info  - 09:47:39.57] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 09:47:39.60] <syntax> Forking...
[Info  - 09:47:39.65] <syntax> Starting...
[Info  - 09:47:39.66] <semantic> Forking...
[Info  - 09:47:39.71] <semantic> Starting...
```

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 5, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.0.15
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.4
prettify-json|moh|0.0.3
sublime-keybindings|ms-|4.0.6
vetur|oct|0.23.0
lorem-ipsum|Tyr|1.2.0
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by Shub1427** [comment]
I tried disabling/enabling some plugins (specifically linter plugins) as they might mess with TS extension code, but with no effect.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

If it does, please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the **first time** the path to the semantic error log file is printed. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs from the crashed instance .

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by Shub1427** [comment]
## Error Logs

> tsserver.log [7gVktN]
```
Info 0    [9:46:30.379] Starting TS Server
Info 1    [9:46:30.379] Version: 3.7.3
Info 2    [9:46:30.379] Arguments: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/pd/bntz0rrx17l9c3cfjwj8cn3csnfqbw/T/vscode-typescript861363580/2724ed7ffe15b47b10d4/tscancellation-3fb548ff31aec0ec6e78.tmp* --logVerbosity verbose --logFile /Users/subroto.biswas/Library/Application Support/Code/logs/20200215T094519/exthost1/vscode.typescript-language-features/tsserver-log-7gVktN/tsserver.log --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
Info 3    [9:46:30.379] Platform: darwin NodeVersion: 12 CaseSensitive: false
Info 4    [9:46:30.382] Binding...
Info 5    [9:46:30.393] request:
    {"seq":0,"type":"request","command":"configure","arguments":{"hostInfo":"vscode","preferences":{"providePrefixAndSuffixTextForRename":true,"allowRenameOfImportPath":true}}}
Info 6    [9:46:30.394] Host information vscode
Info 7    [9:46:30.394] response:
    {"seq":0,"type":"response","command":"configure","request_seq":0,"success":true}
Perf 8    [9:46:30.395] 0::configure: async elapsed time (in milliseconds) 1.8951
Info 9    [9:46:30.395] request:
    {"seq":1,"type":"request","command":"compilerOptionsForInferredProjects","arguments":{"options":{"module":"commonjs","target":"es2016","jsx":"preserve","allowJs":true,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true}}}
Info 10   [9:46:30.396] Scheduled: *ensureProjectForOpenFiles*
Perf 11   [9:46:30.396] 1::compilerOptionsForInferredProjects: elapsed time (in milliseconds) 1.1763
Info 12   [9:46:30.397] response:
    {"seq":0,"type":"response","command":"compilerOptionsForInferredProjects","request_seq":1,"success":true,"body":true}
Info 13   [9:46:30.397] request:
    {"seq":2,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"untitled:^Untitled-1","fileContent":"","projectRootPath":"","scriptKindName":"JSX"},{"file":"","fileContent":"","projectRootPath":"","scriptKindName":"JS"}]}}
Info 14   [9:46:30.398] Search path: 
Info 15   [9:46:30.399] ConfigFilePresence:: Current Watches: :: File: tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: untitled:^Untitled-1 Status: File added to open files impacted by this config file
Info 16   [9:46:30.399] ConfigFilePresence:: Current Watches: :: File: jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: untitled:^Untitled-1 Status: File added to open files impacted by this config file
Info 17   [9:46:30.399] For info: untitled:^Untitled-1 :: Config file name: jsconfig.json
Info 18   [9:46:30.400] Opened configuration file jsconfig.json
Info 19   [9:46:30.472] FileWatcher:: Added:: WatchInfo: jsconfig.json 2000 Project: jsconfig.json WatchType: Config file
Info 20   [9:46:30.477] event:
    {"seq":0,"type":"event","event":"projectLoadingStart","body":{"projectName":"jsconfig.json","reason":"Creating possible configured project for untitled:^Untitled-1 to open"}}
Info 21   [9:46:30.637] Config: jsconfig.json : { ... }
Err 22    [9:46:30.705] Exception on executing command {"seq":2,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"untitled:^Untitled-1","fileContent":"","projectRootPath":"","scriptKindName":"JSX"},{"file":"","fileContent":"","projectRootPath":"","scriptKindName":"JS"}]}}:

    Cannot read property 'path' of undefined

    TypeError: Cannot read property 'path' of undefined
        at ProjectService.updateNonInferredProjectFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137442:43)
        at ProjectService.addFilesToNonInferredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137332:22)
        at ProjectService.updateRootAndOptionsOfNonInferredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137480:22)
        at ProjectService.loadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137416:22)
        at ProjectService.createAndLoadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137356:22)
        at ProjectService.createLoadAndUpdateConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137361:36)
        at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138186:44)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138417:107
        at Object.mapDefined (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:565:30)
        at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138417:48)
        at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:139271:46)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:88
        at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140920:28)
        at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:33)
        at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140952:35)
        at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:142267:27)
        at Interface.emit (events.js:200:13)
        at Interface._onLine (readline.js:314:10)
        at Interface._normalWrite (readline.js:459:12)
        at Socket.ondata (readline.js:170:10)
        at Socket.emit (events.js:200:13)
        at addChunk (_stream_readable.js:294:12)
        at readableAddChunk (_stream_readable.js:275:11)
        at Socket.Readable.push (_stream_readable.js:210:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
Info 23   [9:46:30.705] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":2,"success":false,"message":"Error processing request. Cannot read property 'path' of undefined\nTypeError: Cannot read property 'path' of undefined\n    at ProjectService.updateNonInferredProjectFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137442:43)\n    at ProjectService.addFilesToNonInferredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137332:22)\n    at ProjectService.updateRootAndOptionsOfNonInferredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137480:22)\n    at ProjectService.loadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137416:22)\n    at ProjectService.createAndLoadConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137356:22)\n    at ProjectService.createLoadAndUpdateConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:137361:36)\n    at ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138186:44)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138417:107\n    at Object.mapDefined (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:565:30)\n    at ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138417:48)\n    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:139271:46)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:88\n    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140920:28)\n    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:33)\n    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140952:35)\n    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:142267:27)\n    at Interface.emit (events.js:200:13)\n    at Interface._onLine (readline.js:314:10)\n    at Interface._normalWrite (readline.js:459:12)\n    at Socket.ondata (readline.js:170:10)\n    at Socket.emit (events.js:200:13)\n    at addChunk (_stream_readable.js:294:12)\n    at readableAddChunk (_stream_readable.js:275:11)\n    at Socket.Readable.push (_stream_readable.js:210:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)"}
```
-----
> ti-50592.log
```
[9:46:39.636] Global cache location '/Users/subroto.biswas/Library/Caches/typescript/3.7', safe file path '/applications/visual studio code.app/contents/resources/app/extensions/node_modules/typescript/lib/typingsafelist.json', types map path /applications/visual studio code.app/contents/resources/app/extensions/node_modules/typescript/lib/typesmap.json
[9:46:39.686] Processing cache location '/Users/subroto.biswas/Library/Caches/typescript/3.7'
[9:46:39.688] Trying to find '/Users/subroto.biswas/Library/Caches/typescript/3.7/package.json'...
[9:46:39.698] Loaded content of '/Users/subroto.biswas/Library/Caches/typescript/3.7/package.json': { ... }
[9:46:39.699] Loaded content of '/Users/subroto.biswas/Library/Caches/typescript/3.7/package-lock.json'
[9:46:39.732] Adding entry into typings cache: 'abbrev' => '/Users/subroto.biswas/Library/Caches/typescript/3.7/node_modules/@types/abbrev/index.d.ts'
...
...
512 lines of different cache entries
...
...
[9:46:42.919] Finished processing cache location '/Users/subroto.biswas/Library/Caches/typescript/3.7'
[9:46:42.919] Process id: 50598
[9:46:42.921] NPM location: npm (explicit '--npmLocation' not  provided)
[9:46:42.921] validateDefaultNpmLocation: true
[9:46:42.922] Npm config file: /Users/subroto.biswas/Library/Caches/typescript/3.7/package.json
[9:46:42.922] Updating types-registry npm package...
[9:46:42.922] Exec: npm install --ignore-scripts types-registry@latest
```

-----

> tsserver.log [9CA8V3]
```
Info 0    [9:46:39.128] Starting TS Server
Info 1    [9:46:39.129] Version: 3.7.3
Info 2    [9:46:39.129] Arguments: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/pd/bntz0rrx17l9c3cfjwj8cn3csnfqbw/T/vscode-typescript861363580/2724ed7ffe15b47b10d4/tscancellation-51a57c071000402cd4e0.tmp* --logVerbosity verbose --logFile /Users/subroto.biswas/Library/Application Support/Code/logs/20200215T094519/exthost1/vscode.typescript-language-features/tsserver-log-9CA8V3/tsserver.log --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
Info 3    [9:46:39.129] Platform: darwin NodeVersion: 12 CaseSensitive: false
Info 4    [9:46:39.131] Binding...
Info 5    [9:46:39.147] request:
    {"seq":0,"type":"request","command":"configure","arguments":{"hostInfo":"vscode","preferences":{"providePrefixAndSuffixTextForRename":true,"allowRenameOfImportPath":true}}}
Info 6    [9:46:39.148] Host information vscode
Info 7    [9:46:39.148] response:
    {"seq":0,"type":"response","command":"configure","request_seq":0,"success":true}
Perf 8    [9:46:39.149] 0::configure: async elapsed time (in milliseconds) 2.2670
Info 9    [9:46:39.149] request:
    {"seq":1,"type":"request","command":"compilerOptionsForInferredProjects","arguments":{"options":{"module":"commonjs","target":"es2016","jsx":"preserve","allowJs":true,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true}}}
Info 10   [9:46:39.150] Scheduled: *ensureProjectForOpenFiles*
Perf 11   [9:46:39.150] 1::compilerOptionsForInferredProjects: elapsed time (in milliseconds) 0.8996
Info 12   [9:46:39.150] response:
    {"seq":0,"type":"response","command":"compilerOptionsForInferredProjects","request_seq":1,"success":true,"body":true}
Info 13   [9:46:39.150] request:
    {"seq":2,"type":"request","command":"geterr","arguments":{"delay":0,"files":["...*.js","untitled:^Untitled-1"]}}
Info 14   [9:46:39.151] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":2}}
Perf 15   [9:46:39.151] 2::geterr: async elapsed time (in milliseconds) 0.9206
Info 16   [9:46:39.151] request:
    {"seq":3,"type":"request","command":"definitionAndBoundSpan","arguments":{"file":"...*.js","line":49,"offset":30}}
Info 17   [9:46:39.151] Structure before ensureProjectForOpenFiles:
Info 18   [9:46:39.151] Open files: 
Info 18   [9:46:39.151] Structure after ensureProjectForOpenFiles:
Info 19   [9:46:39.151] Open files: 
Err 19    [9:46:39.151] Could not find file "...*.js".
All files are: []
Err 20    [9:46:39.229] Could not find file "...*.js".
All files are: []
Err 21    [9:46:39.229] Exception on executing command {"seq":3,"type":"request","command":"definitionAndBoundSpan","arguments":{"file":"...*.js","line":49,"offset":30}}:

    No Project.

    Error: No Project.
        at Object.ThrowNoProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:133314:23)
        at ProjectService.doEnsureDefaultProjectForFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:136599:131)
        at ProjectService.ensureDefaultProjectForFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:136594:75)
        at IOSession.Session.getFileAndProjectWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140251:87)
        at IOSession.Session.getFileAndProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140234:29)
        at IOSession.Session.getDefinitionAndBoundSpan (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:139947:31)
        at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:139308:61)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:88
        at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140920:28)
        at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:33)
        at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140952:35)
        at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:142267:27)
        at Interface.emit (events.js:200:13)
        at Interface._onLine (readline.js:314:10)
        at Interface._normalWrite (readline.js:459:12)
        at Socket.ondata (readline.js:170:10)
        at Socket.emit (events.js:200:13)
        at addChunk (_stream_readable.js:294:12)
        at readableAddChunk (_stream_readable.js:275:11)
        at Socket.Readable.push (_stream_readable.js:210:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
Info 22   [9:46:39.229] response:
    {"seq":0,"type":"response","command":"definitionAndBoundSpan","request_seq":3,"success":false,"message":"Error processing request. No Project.\nError: No Project.\n    at Object.ThrowNoProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:133314:23)\n    at ProjectService.doEnsureDefaultProjectForFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:136599:131)\n    at ProjectService.ensureDefaultProjectForFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:136594:75)\n    at IOSession.Session.getFileAndProjectWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140251:87)\n    at IOSession.Session.getFileAndProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140234:29)\n    at IOSession.Session.getDefinitionAndBoundSpan (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:139947:31)\n    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:139308:61)\n    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:88\n    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140920:28)\n    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140929:33)\n    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:140952:35)\n    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:142267:27)\n    at Interface.emit (events.js:200:13)\n    at Interface._onLine (readline.js:314:10)\n    at Interface._normalWrite (readline.js:459:12)\n    at Socket.ondata (readline.js:170:10)\n    at Socket.emit (events.js:200:13)\n    at addChunk (_stream_readable.js:294:12)\n    at readableAddChunk (_stream_readable.js:275:11)\n    at Socket.Readable.push (_stream_readable.js:210:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)"}
Info 23   [9:46:39.230] event:
    {"seq":0,"type":"event","event":"typingsInstallerPid","body":{"pid":50598}}
Info 24   [9:46:39.401] Running: *ensureProjectForOpenFiles*
```


## Details

I have removed as much personal content as possible, if that affects with your debugging let me know. Other than that, I have moved to VSCode v1.41.1, but getting the same error, guess it happens due to TS version. This bug seems to be critical, because it keeps on consuming the 100% CPU usage and thus have to close the editor itself.

**Comment by mjbvz** [comment]
Looks like you are using an older TS version in your workspace (3.7.3). Did you try the insiders build with TS 3.8?

Possible duplicate of one of these issues: https://github.com/microsoft/TypeScript/issues?q=is%3Aissue+updateNonInferredProjectFiles+is%3Aclosed

**Comment by Shub1427** [comment]
I moved towards using VSCode Insiders build. Till now I haven't faced the issue. WE can close the issue, as it has been resolved in TS v8+.
Thanks for all your help and time, @mjbvz
