### ISSUE TITLE
Error of token transformation

### ISSUE THREAD

**Issue by timdelawe** [Microsoft/vscode#9066]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 3.16.0-73-generic

I tested JavaScript and CSS: The Syntax highlighting doesn't work at all.
The error message is: Mode error while token transfomation of input.

HTML works fine!

**Comment by timdelawe** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/17140558/16729223/5391abde-476b-11e6-9989-abc02a5f3030.png)

**Comment by timdelawe** [comment]
I have to correct my-self: the syntax highlighting of the HTML file is starting but reaches only until a code line around 50 before the mentioned error comes up.

**Comment by alexandrudima** [comment]
@timdelawe We have recently identified two major issues on Linux:
#8859 - updating does not shut down previous running instance gracefully (requires to manually kill vscode left-over processes)
#8876 - updating does not remove old files correctly

Is it possible you suffer from one of these issues on Linux? Is there any message in the console (command line where you launch it from or Help > Toggle Developer Tools)?

As for the Windows issue, that might be related to the contents of the file. Is it possible to share them here?

**Comment by timdelawe** [comment]
I restarted the OS and retried but the issue still comes up. So I think #8859 is okay for me. 

I attached the output from the console:

![error](https://cloud.githubusercontent.com/assets/17140558/16732406/49b3333c-477d-11e6-8064-1f93488076db.png)

**Comment by alexandrudima** [comment]
@timdelawe Thank you! I am sorry you are definitely hitting #8876 

Here is the workaround recommended by @Tyriar: https://github.com/Microsoft/vscode/issues/8876#issuecomment-231425705

```
sudo rm -rf /usr/share/code/resources/app/node_modules/vscode-textmate/node_modules
```

From that issue:
```
shell.ts:416 Module version mismatch. Expected 47, got 46.: Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules/vscode-textmate/node_modules/oniguruma/lib/oniguruma.js:4:17)
    at Object.<anonymous> (/usr/share/code/resources/app/node_modules/vscode-textmate/node_modules/oniguruma/lib/oniguruma.js:69:4)e.onUnexpectedError @ shell.ts:416(anonymous function) @ shell.ts:318e.onUnexpectedError @ errors.ts:73u @ errors.ts:88t._updateTokensUntilLine @ textModelWithTokens.ts:629t._revalidateTokensNow @ textModelWithTokens.ts:575t._warmUpTokens @ textModelWithTokens.ts:530t.onBeforeAttached @ model.ts:129t._attachModel @ commonCodeEditor.ts:752t._attachModel @ codeEditorWidget.ts:460t.setModel @ commonCodeEditor.ts:263(anonymous function) @ textFileEditor.ts:149g @ winjs.base.raw.js:1170W.enter @ winjs.base.raw.js:852i.Class.define._run @ winjs.base.raw.js:1068i.Class.define._completed @ winjs.base.raw.js:1036i.Class.define.then @ winjs.base.raw.js:1566O.enter @ winjs.base.raw.js:747i.Class.define._run @ winjs.base.raw.js:1068i.Class.define._setCompleteValue @ winjs.base.raw.js:1052g @ winjs.base.raw.js:1170W.enter @ winjs.base.raw.js:852i.Class.define._run @ winjs.base.raw.js:1068i.Class.define._completed @ winjs.base.raw.js:1036(anonymous function) @ modelBuilder.ts:129emitNone @ events.js:85emit @ events.js:179endReadableNT @ _stream_readable.js:913_combinedTickCallback @ internal/process/next_tick.js:74_tickCallback @ internal/process/next_tick.js:98
messageService.ts:119 The mode has failed while tokenizing the input.e.doShow @ messageService.ts:119e.show @ messageService.ts:103e.onUnexpectedError @ shell.ts:420(anonymous function) @ shell.ts:318e.onUnexpectedError @ errors.ts:73u @ errors.ts:88t._updateTokensUntilLine @ textModelWithTokens.ts:629t._revalidateTokensNow @ textModelWithTokens.ts:575t._warmUpTokens @ textModelWithTokens.ts:530t.onBeforeAttached @ model.ts:129t._attachModel @ commonCodeEditor.ts:752t._attachModel @ codeEditorWidget.ts:460t.setModel @ commonCodeEditor.ts:263(anonymous function) @ textFileEditor.ts:149g @ winjs.base.raw.js:1170W.enter @ winjs.base.raw.js:852i.Class.define._run @ winjs.base.raw.js:1068i.Class.define._completed @ winjs.base.raw.js:1036i.Class.define.then @ winjs.base.raw.js:1566O.enter @ winjs.base.raw.js:747i.Class.define._run @ winjs.base.raw.js:1068i.Class.define._setCompleteValue @ winjs.base.raw.js:1052g @ winjs.base.raw.js:1170W.enter @ winjs.base.raw.js:852i.Class.define._run @ winjs.base.raw.js:1068i.Class.define._completed @ winjs.base.raw.js:1036(anonymous function) @ modelBuilder.ts:129emitNone @ events.js:85emit @ events.js:179endReadableNT @ _stream_readable.js:913_combinedTickCallback @ internal/process/next_tick.js:74_tickCallback @ internal/process/next_tick.js:98
index.html?config={"pathArguments"%3A["%2Fhome%2Fdaniel%2Fdev%2FMicrosoft%2Fvscode"]%2C"programStar…:28 [uncaught exception]: TypeError: Cannot read property 'publisher' of undefinedonError @ index.html?config={"pathArguments"%3A["%2Fhome%2Fdaniel%2Fdev%2FMicrosoft%2Fvscode"]%2C"programStar…:28(anonymous function) @ index.html?config={"pathArguments"%3A["%2Fhome%2Fdaniel%2Fdev%2FMicrosoft%2Fvscode"]%2C"programStar…:100emitOne @ events.js:90emit @ events.js:182window.onerror @ /usr/share/code/resources/electron.asar/renderer/init.js:107n.globals.onerror @ errorTelemetry.ts:64
index.html?config={"pathArguments"%3A["%2Fhome%2Fdaniel%2Fdev%2FMicrosoft%2Fvscode"]%2C"programStar…:31 TypeError: Cannot read property 'publisher' of undefined
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:96:27943
    at Array.every (native)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:96:27908
    at Array.filter (native)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:96:27880
    at i.Class.define.done (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:14123)
    at Object.g [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:7558)
    at Object.W.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:10994)
    at i.Class.define._run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:12822)
    at i.Class.define._completed (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:30:12263)onError @ index.html?config={"pathArguments"%3A["%2Fhome%2Fdaniel%2Fdev%2FMicrosoft%2Fvscode"]%2C"programStar…:31(anonymous function) @ index.html?config={"pathArguments"%3A["%2Fhome%2Fdaniel%2Fdev%2FMicrosoft%2Fvscode"]%2C"programStar…:100emitOne @ events.js:90emit @ events.js:182window.onerror @ /usr/share/code/resources/electron.asar/renderer/init.js:107n.globals.onerror @ errorTelemetry.ts:64
```

**Comment by timdelawe** [comment]
It worked, Thank you!
