### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90813]
Noticed this in my selfhost web log:

```
ERR Cannot read property 'push' of undefined: TypeError: Cannot read property 'push' of undefined
    at g.addMatch (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:3912:755)
    at http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:3913:946
    at Array.forEach (<anonymous>)
    at p.handleFindMatch (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:3913:856)
    at u.$handleFileMatch (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:3912:213)
    at g._doInvokeHandler (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:3572:464)
    at g._invokeHandler (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:3572:156)
    at g._receiveRequest (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:3570:817)
    at g._receiveOneMessage (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:3569:623)
    at http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:3567:821
```

Looking at the number of "`!`" used, I am not surprised:

https://github.com/microsoft/vscode/blob/12215af89154f3b3eaeb92e7dc77fa7d024b47de/src/vs/workbench/api/browser/mainThreadSearch.ts#L86

**Comment by roblourens** [comment]
Thanks. Have some types shared between file and text search where they really shouldn't be, especially after strict null checking
