### ISSUE TITLE
ERR Illegal value for lineNumber: Error: Illegal value for lineNumber

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90814]
Noticed this in my selfhost web log, I think it may originate from https://github.com/microsoft/vscode/commit/49cb313760f879295f7f481ff18112cb7864d7cf

```
ERR Illegal value for lineNumber: Error: Illegal value for lineNumber
    at N.getLineContent (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:1355:838)
    at z._getAriaLabel (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:2307:430)
    at z._updateMatchesCount (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:2307:83)
    at z._onStateChanged (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:2306:171)
    at http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:2302:558
    at c.fire (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:117:102)
    at r.changeMatchInfo (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:815:800)
    at p.research (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:2290:420)
    at new p (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:2289:274)
    at x._start (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:2330:774)
```

**Comment by connor4312** [comment]
Pinging @bpasero for steps :)

**Comment by Tyriar** [comment]
Verified via code review
