### ISSUE TITLE
Word Wrap Not Working on PowerShell Integrated Terminal

### ISSUE THREAD

**Issue by dfp127** [microsoft/vscode#90835]
Version: 1.42.0 (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

- OS Version:
Windows 10 v1909 Build 18363.592

When typing long lines in PowerShell Integrated Terminal you get an error when you reach the end of the line instead of the text wrapping as it does in a normal PS Console.

Steps to Reproduce:

1. Open a PowerShell Script, the PS Integrated Console will open.
2. Type a PS command that is longer than the terminal window

Does this issue occur when all extensions are disabled?: Yes/No - Unknown, you have to have the PowerShell extension enabled to produce the error.

ERROR MESSAGE:
An error occurred while reading input:

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 9.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.InsertInput(StringBuilder inputLine, Int32 promptStartCol, Int32 promptStartRow, String insertedInput, Int32 cursorIndex, Int32 insertIndex, Int32 replaceLength, Int32 finalCursorIndex)
   at Microsoft.PowerShell.EditorServices.Console.ConsoleReadLine.<ReadLine>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PowerShell.EditorServices.EditorServicesPSHostUserInterface.<StartReplLoop>d__103.MoveNext()

**Comment by Tyriar** [comment]
This is specific to the [powershell extension](https://github.com/PowerShell/vscode-powershell), it should be fixed in the [preview version of the extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview).

/duplicate https://github.com/microsoft/vscode/issues/78967
