### ISSUE TITLE
TypeError: Cannot read property 'setViewVisible' of undefined

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90836]
Found this in my web selfhost console, originating from `layout.ts` it seems.

```
 ERR Cannot read property 'setViewVisible' of undefined: TypeError: Cannot read property 'setViewVisible' of undefined
    at W.setMenubarVisibility (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:5807:152)
    at W.doUpdateLayoutConfiguration (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:5789:541)
    at http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:5787:203
    at c.fire (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:117:102)
    at C.triggerConfigurationChange (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:4555:220)
    at C.onDefaultConfigurationChanged (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:4549:402)
    at http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:4541:583
    at c.fire (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:117:102)
    at Object.registerConfigurations (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:1659:278)
    at Object.registerConfiguration (http://localhost:9777/static/out/vs/workbench/workbench.web.api.js:1658:900)
```

**Comment by bpasero** [comment]
Similar to https://github.com/microsoft/vscode/issues/101650

**Comment by sbatten** [comment]
same as similar issue. we try to operate on the grid too early, so just adding a check in this operation to prevent issues.

**Comment by Tyriar** [comment]
Verified via code review
