### ISSUE TITLE
Typescript Hangs on save-all

### ISSUE THREAD

**Issue by s4m0r4m4** [microsoft/vscode#90889]
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:

1. Open Workspace, which uses workspace's version of typescript (3.5.3) rather than VS Code's 3.7.5. 
2. Open multiple typescript files
3. File -> Save All (Ctrl + Shift +S)
4. In most cases, but not always, the developer console displays:
```
 ERR <semantic> TypeScript Server Error (3.5.3)
Could not find sourceFile: 'c:/AIMDev/Projects/BART/Web/Applications/bart-status-dashboard/src/app/location-row/location-row.component.ts'.
Error: Could not find sourceFile: 'c:/AIMDev/Projects/BART/Web/Applications/bart-status-dashboard/src/app/location-row/location-row.component.ts'.
    at getValidSourceFile (c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:121885:23)
    at Object.getApplicableRefactors (c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:122657:24)
    at IOSession.Session.getApplicableRefactors (c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:131427:53)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:130245:61)
    at c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:131671:88
    at IOSession.Session.executeWithRequestId (c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:131662:28)
    at IOSession.Session.executeCommand (c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:131671:33)
    at IOSession.Session.onMessage (c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:131693:35)
    at Interface.<anonymous> (c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:132984:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17): Error: <semantic> TypeScript Server Error (3.5.3)
Could not find sourceFile: 'c:/AIMDev/Projects/BART/Web/Applications/bart-status-dashboard/src/app/location-row/location-row.component.ts'.
Error: Could not find sourceFile: 'c:/AIMDev/Projects/BART/Web/Applications/bart-status-dashboard/src/app/location-row/location-row.component.ts'.
    at getValidSourceFile (c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:121885:23)
    at Object.getApplicableRefactors (c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:122657:24)
    at IOSession.Session.getApplicableRefactors (c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:131427:53)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:130245:61)
    at c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:131671:88
    at IOSession.Session.executeWithRequestId (c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:131662:28)
    at IOSession.Session.executeCommand (c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:131671:33)
    at IOSession.Session.onMessage (c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:131693:35)
    at Interface.<anonymous> (c:\AIMDev\CI (Web)\Applications\bart-status-dashboard\node_modules\typescript\lib\tsserver.js:132984:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
	at Function.create (c:\Users\A9FZGZZ\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:49149)
	at h.dispatchResponse (c:\Users\A9FZGZZ\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:213785)
	at h.dispatchMessage (c:\Users\A9FZGZZ\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:212703)
	at c:\Users\A9FZGZZ\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:212179
	at l.fire (c:\Users\A9FZGZZ\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:541)
	at t.Reader.onLengthData (c:\Users\A9FZGZZ\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:219256)
	at Socket.<anonymous> (c:\Users\A9FZGZZ\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:218904)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```
4. I have verified that the source file does indeed exist at that location.
5. I have also verified that this occurs if I switch to VS Code's built-in typescript version 3.7.5.

Does this issue occur when all extensions are disabled?: I was not able to reproduce this with --disable-extension. It appears to be related to the built-in typescript-language-features extension.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions (except the built in ones) disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by s4m0r4m4** [comment]
I spent an hour working with the VS Code insiders build with installed extensions disabled, and it did not reproduce. 

Any suggestions on how to identify which extension is causing the issue? I am doing Angular dev, so I have the Angular Language Service, Debugger for Chrome, TSLint, and a few other extensions installed.

**Comment by mjbvz** [comment]
Thanks for testing. The most likely candidates are tslint or angular since both of those tie into the typescript language service

**Comment by s4m0r4m4** [comment]
Ok great, I will follow up with those two plugins to figure out what's happening. Is there any way to get access to more debug details? The stack above doesn't provide info about what's calling the typescript-language-features extension.

**Comment by mjbvz** [comment]
Try following up with the extensions once you find which one triggers this. They should tell you how to collect logs to investigate this
