### ISSUE TITLE
Extensions not working since 1.42.1 update

### ISSUE THREAD

**Issue by Quiwy** [microsoft/vscode#90985]
Hi,

This morning I had to restart VScodium to update to version 1.42.1 and since then no extension is working.

If I disable all the extensions, well, vscodium still working without extensions, logical.

Informations:

```
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-14T10:21:44.789Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```

```
 codium.cmd --list-extensions
Error: Le module sp├®cifi├® est introuvable.
\\?\C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at bindings (C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\node_modules.asar\spdlog\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\node_modules.asar\spdlog\index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at t.load (C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\out\vs\loader.js:16:119)
    at e.load (C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\out\vs\loader.js:13:586)
    at i (C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\out\vs\loader.js:29:189)
    at Object.errorback (C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\out\vs\loader.js:29:313)
    at e.triggerErrorback (C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\out\vs\loader.js:13:955)
    at C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\out\vs\loader.js:13:659
    at ReadFileContext.callback (C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\out\vs\loader.js:16:494)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous5===' ]
}
bierner.emojisense
bierner.markdown-checkbox
bierner.markdown-emoji
bierner.markdown-footnotes
bierner.markdown-image-size
bierner.markdown-preview-github-styles
CoenraadS.bracket-pair-colorizer-2
eamodio.gitlens
EditorConfig.EditorConfig
eriklynd.json-tools
fatihacet.gitlab-workflow
GrapeCity.gc-excelviewer
HackMD.vscode-hackmd
henriiik.docker-linter
hnw.vscode-auto-open-markdown-preview
jebbs.plantuml
lacroixdavid1.vscode-format-context-menu
Mebrahtom.plantumlpreviewer
mhutchie.git-graph
mohsen1.prettify-json
ms-azuretools.vscode-docker
ms-python.python
ms-vscode.cpptools
ronzhong.cppcheckcmd
shd101wyy.markdown-preview-enhanced
SirTori.indenticator
yzane.markdown-pdf
yzhang.markdown-all-in-one
ZainChen.json
```

What I expect:
Extensions working

Didnt't found any relevant issue.

Thank you for the help you can provide.

**Comment by IllusionMH** [comment]
Most likely you should report this issue in VSCodium repo (that provided custom build) and not VS Code repo itself.

**Comment by Quiwy** [comment]
> 
> 
> Most likely you should report this issue in VSCodium repo (that provided custom build) and not VS Code repo itself.

Opened here: https://github.com/VSCodium/vscodium/issues/337
