### ISSUE TITLE
TS Server fatal error:  Cannot read property 'exports' of undefined

### ISSUE THREAD

**Issue by bookman920** [microsoft/vscode#91198]
Issue Type: <b>Bug</b>

**TypeScript Version:** 1.0.0
**Steps to reproduce crash**
1.
2.
3.
** TS Server Error Stack **
```
TypeError: Cannot read property 'exports' of undefined
    at declareModuleMember (tsserver.js:30317:63)
    at delayedBindJSDocTypedefTag (tsserver.js:31740:29)
    at bindSourceFile (tsserver.js:30018:17)
    at Object.bindSourceFile (tsserver.js:29951:9)
    at initializeTypeChecker (tsserver.js:66243:20)
    at Object.createTypeChecker (tsserver.js:34747:9)
    at Object.getTypeChecker (tsserver.js:98366:79)
    at synchronizeHostData (tsserver.js:135154:21)
    at Proxy.getProgram (tsserver.js:135236:13)
    at InferredProject.Project.updateGraphWorker (tsserver.js:139710:53)
    at InferredProject.Project.updateGraph (tsserver.js:139653:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (tsserver.js:141629:25)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:143059:26)
    at tsserver.js:143324:107
    at Object.mapDefined (tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143324:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144188:46)
    at tsserver.js:145931:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145922:28)
    at IOSession.Session.executeCommand (tsserver.js:145931:33)
    at IOSession.Session.onMessage (tsserver.js:145955:35)
    at Interface.<anonymous> (tsserver.js:147270:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.43.0-insider (e6a45f4242ebddb7aa9a229f85555e8a3bd987e2, 2020-02-21T05:42:20.536Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (3.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Same error stack as https://github.com/microsoft/TypeScript/issues/36983

Closing as upstream
