### ISSUE TITLE
TS Server fatal error:  Cannot read property 'checkJsDirective' of undefined

### ISSUE THREAD

**Issue by selfrefactor** [microsoft/vscode#91247]
Issue Type: <b>Bug</b>

**TypeScript Version:** 1.0.0
**Steps to reproduce crash**
1.
2.
3.
** TS Server Error Stack **
```
TypeError: Cannot read property 'checkJsDirective' of undefined
    at ProjectService.telemetryOnOpenFile (tsserver.js:143789:79)
    at tsserver.js:143868:76
    at Array.forEach (<anonymous>)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143868:37)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144722:46)
    at tsserver.js:146465:88
    at IOSession.Session.executeWithRequestId (tsserver.js:146456:28)
    at IOSession.Session.executeCommand (tsserver.js:146465:33)
    at IOSession.Session.onMessage (tsserver.js:146489:35)
    at Interface.<anonymous> (tsserver.js:147804:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.43.0-insider (e6a45f4242ebddb7aa9a229f85555e8a3bd987e2, 2020-02-21T05:40:52.685Z)
OS version: Linux x64 5.3.0-41-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|15.49GB (3.87GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color-pick|ada|0.6.2
vscode-unfancy-file-icons|ale|3.3.0
ng-template|Ang|0.900.14
chalice-icon-theme|art|1.2.3
path-intellisense|chr|1.4.2
gitlens|eam|10.2.1
vscode-open-in-node-modules|fab|1.1.1
auto-run-command|gab|1.5.0
vscode-angular-html|gha|1.7.0
vscode-icon-theme|jtl|1.6.5
autorun|kri|1.0.0
vscode-js-annotations|lan|0.11.0
vscode-docker|ms-|0.10.0
atom-keybindings|ms-|3.0.6
vscode-typescript-next|ms-|3.9.20200222
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.6
color-highlight|nau|2.3.0
angular-console|nrw|11.1.3
tsimporter|pmn|2.0.1
subtle-brackets|raf|3.0.0
vscode-seedling-icon-theme|ras|0.5.0
magic-beans|sel|0.19.0
niketa|sel|2.10.5
indenticator|Sir|0.6.0
guides|spy|0.9.3
tabnine-vscode|Tab|2.2.2
highlight-matching-tag|vin|0.9.6
vscodeintellicode|Vis|1.2.5

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Are you using the built-in TS version?

**Comment by selfrefactor** [comment]
Yes, I do.

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/36984 to track upstream
