### ISSUE TITLE
Web: terminal open failed

### ISSUE THREAD

**Issue by HuangJunjia** [microsoft/vscode#91358]
- VSCode Version: 1.42.1
- OS Version: MacOS 10.15.3

Steps to Reproduce:

1. `git checkout 1.42.1`
2. `yarn`
3. `yarn watch` && `yarn web`
4. `new terminal`
5. terminal can open but it is blank
6. open chrome devtools console log **ERR**
  ```
  ERR Not implemented: Error: Not implemented
	at WorkerExtHostTerminalService.$requestDefaultShellAndArgs (http://localhost:8080/static/out/vs/workbench/api/common/extHostTerminalService.js:489:19)
	at RPCProtocol._doInvokeHandler (http://localhost:8080/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:331:27)
	at RPCProtocol._invokeHandler (http://localhost:8080/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:316:45)
	at RPCProtocol._receiveRequest (http://localhost:8080/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:243:32)
	at RPCProtocol._receiveOneMessage (http://localhost:8080/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:171:26)
	at http://localhost:8080/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:61:52
	at Emitter.fire (http://localhost:8080/static/out/vs/base/common/event.js:459:38)
	at http://localhost:8080/static/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:44:25
  ```
7. system terminal log 
```
Error: ENOENT: no such file or directory, stat '/Users/vscode/remote/web/node_modules/vscode-textmate/release/main.js.map'
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is by design as the web worker extension host cannot host terminals
