### ISSUE TITLE
NLS smoke test fails

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#91447]
Testing https://github.com/microsoft/vscode/issues/91337

Ubuntu 19.10

- extract `1.43.0-insider-89cafb24e5/` to `~/vscode/1.43.0-insider-89cafb24e5`
- run `yarn smoketest --build ~/vscode/1.43.0-insider-89cafb24e5/VSCode-linux-x64/` from the VSCode repo master.

```
1) VSCode Smoke Tests (Electron)
       Localization
         starts with 'DE' locale and verifies title and viewlets text is in German:
     Error: Timeout: get text content '.monaco-workbench .part.sidebar > .title > .title-label > h2' after 20 seconds.
      at /home/martin/workspaces/vscode/test/automation/out/code.js:176:23
      at Generator.next (<anonymous>)
      at fulfilled (/home/martin/workspaces/vscode/test/automation/out/code.js:9:58)

```

**Comment by aeschli** [comment]
dup of #91433
