### ISSUE TITLE
Smoke tests: EADDRINUSE when trying to rerun web tests

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#91452]
Testing https://github.com/microsoft/vscode/issues/91337

1. Run ` yarn smoketest --build ~/Downloads/vscode-server-darwin-web --web --browser chromium` (where build path is to wherever the web bits actually are)
2. Tests finish, there was one failure. Run the exact same command

I get an address already in use error:
```
  VSCode Smoke Tests (Web)
Server stderr: Ignoring option browser: not supported for server.

Server stdout: 

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*



Server stdout: IP Address: 10.89.4.20

Server stdout: IP Address: 10.211.55.2
IP Address: 10.37.129.2

Server stderr: [11:26:19] Error occurred in server

Server stderr: [11:26:19] Error: listen EADDRINUSE: address already in use :::8000
    at Server.setupListenHandle [as _listen2] (net.js:1226:14)
    at listenInCluster (net.js:1274:12)
    at Server.listen (net.js:1362:7)
    at ge._start (/Users/ramacfar/Downloads/vscode-server-darwin-web/out/vs/server/remoteExtensionHostAgent.js:468:638)
    at ge.start (/Users/ramacfar/Downloads/vscode-server-darwin-web/out/vs/server/remoteExtensionHostAgent.js:463:213) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 8000
}
```

**Comment by Tyriar** [comment]
You can kill the process using the port manually, I don't think we clean it up correctly atm.

**Comment by bpasero** [comment]
I pushed https://github.com/microsoft/vscode/commit/afcaaa613186832493bb1813dee048890a3c2a2f to resolve this.
