### ISSUE TITLE
Error: WebKit revision is not downloaded. Run "npm install"

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#91539]
#91337 MacOS webkit

Not sure where to run `npm install`, the error says: `Error: WebKit revision is not downloaded. Run "npm install"`.

```
yarn smoketest --build /Users/chrmarti/Development/repos/tmp/vscode-server-darwin-web --web --browser webkit
yarn run v1.22.0
$ cd test/smoke && node test/index.js --build /Users/chrmarti/Development/repos/tmp/vscode-server-darwin-web --web --browser webkit


*** Test data: /var/folders/1r/v4708sbs30jfn87m512fcfnm0000gn/T/t80087o5q36HB6MZdB
*** Preparing smoketest setup...
*** Cloning test project repository...
*** Running yarn...
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > eslint-plugin-import@2.16.0" has incorrect peer dependency "eslint@2.x - 5.x".
[4/4] 🔨  Building fresh packages...
*** Smoketest setup done!

  VSCode Smoke Tests (Web)
Server stderr: Ignoring option browser: not supported for server.

Server stdout:

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*



Server stdout: IP Address: 192.168.0.32

Server stdout: IP Address: 10.211.55.2
IP Address: 10.37.129.2

Server stdout: Extension host agent listening on 8000

Server stdout: Web UI available at http://localhost:8000/?tkn=f4060b3d-a89a-4def-9b7d-c2be0367aeda



Server stdout: [09:46:13] Extension host agent started.

(node:80087) UnhandledPromiseRejectionWarning: Error: WebKit revision is not downloaded. Run "npm install"
    at WebKit._launchServer (/Users/chrmarti/Development/repos/vscode/node_modules/playwright-core/lib/server/webkit.js:95:23)
    at async WebKit.launch (/Users/chrmarti/Development/repos/vscode/node_modules/playwright-core/lib/server/webkit.js:57:46)
(node:80087) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:80087) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by chrmarti** [comment]
Had to `git clean -xfd` to get `yarn` to download the browsers.
