### ISSUE TITLE
Webkit smoke-test: web.sh not found

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#91532]
#91337 

```
$ yarn smoketest --web --browser webkit
yarn run v1.22.0
$ cd test/smoke && node test/index.js --web --browser webkit


*** Test data: /var/folders/1r/v4708sbs30jfn87m512fcfnm0000gn/T/t49636hbi0owevYqGW
*** Preparing smoketest setup...
*** Cloning test project repository...
*** Running yarn...
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > eslint-plugin-import@2.16.0" has incorrect peer dependency "eslint@2.x - 5.x".
[4/4] 🔨  Building fresh packages...
*** Smoketest setup done!

  VSCode Smoke Tests (Web)
    1) "before all" hook
    2) "after all" hook in "VSCode Smoke Tests (Web)"


  0 passing (6s)
  2 failing

  1) VSCode Smoke Tests (Web)
       "before all" hook:
     Uncaught Error: spawn /Users/chrmarti/Development/repos/vscode/resources/server/web.sh ENOENT
      at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
      at onErrorNT (internal/child_process.js:456:16)
      at processTicksAndRejections (internal/process/task_queues.js:81:21)

  2) VSCode Smoke Tests (Web)
       "after all" hook in "VSCode Smoke Tests (Web)":
     TypeError: Cannot read property 'stop' of undefined
      at Context.<anonymous> (out/main.js:238:24)
      at processImmediate (internal/timers.js:439:21)



error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bpasero** [comment]
@chrmarti running out of sources requires you to run `gulp mixin-server`. But for endgame, please use `--build` parameter with a server+web drop.

**Comment by chrmarti** [comment]
The Smoke-Test wiki should mention that `gulp mixin-server` needs to be run. Reopening for that.
