### ISSUE TITLE
Cant install extension - Regresion

### ISSUE THREAD

**Issue by Rafailong** [Microsoft/vscode#9155]
- VSCode Version: 1.3
- OS Version: ubuntu 14.04 LTS 
- Node.js Version: 6.2.2

Hi there, I can't install extension in VSCode 1.3 I just updated my editor to 1.3 and want to install a theme 

`ext install theme-dracula`

I click the little green buttons to install the theme but nothing happens. I opened the Dev Tool and the following error appears.

```
shell.ts:416 Cannot read property 'call' of undefined: TypeError: Cannot read property 'call' of undefined,    at e.onCommonRequest (/opt/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcessMain.js:6:20045),    at e.onMessage (/opt/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcessMain.js:6:19889),    at /opt/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcessMain.js:6:19697,    at Socket.<anonymous> (/opt/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcessMain.js:6:23456),    at emitOne (events.js:90:13),    at Socket.emit (events.js:182:7),    at readableAddChunk (_stream_readable.js:153:18),    at Socket.Readable.push (_stream_readable.js:111:10),    at Pipe.onread (net.js:531:20)
```

Hope this can help!

**Comment by weinand** [comment]
dup of https://github.com/Microsoft/vscode/issues/8859
