### ISSUE TITLE
Build should restart when typescript crashes and not die

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#916]
```
*** Starting...
/Users/bpasero/Development/monaco/node_modules/gulp-tsb/lib/typescript/typescriptServices.js:35645
                throw e;
                      ^
TypeError: Cannot read property 'kind' of undefined
    at Object.nodeIsDecorated (/Users/bpasero/Development/monaco/node_modules/gulp-tsb/lib/typescript/typescriptServices.js:5708:21)
    at emitExpressionForPropertyName (/Users/bpasero/Development/monaco/node_modules/gulp-tsb/lib/typescript/typescriptServices.js:29648:28)
    at emitComputedPropertyName (/Users/bpasero/Development/monaco/node_modules/gulp-tsb/lib/typescript/typescriptServices.js:30183:17)
    at emitJavaScriptWorker (/Users/bpasero/Development/monaco/node_modules/gulp-tsb/lib/typescript/typescriptServices.js:34585:32)
    at emitNodeWithoutSourceMap (/Users/bpasero/Development/monaco/node_modules/gulp-tsb/lib/typescript/typescriptServices.js:34480:21)
    at emitNodeWithSourceMap (/Users/bpasero/Development/monaco/node_modules/gulp-tsb/lib/typescript/typescriptServices.js:29022:36)
    at emitNodeConsideringCommentsOption (/Users/bpasero/Development/monaco/node_modules/gulp-tsb/lib/typescript/typescriptServices.js:34472:21)
    at emitNodeWithCommentsAndWithSourcemap (/Users/bpasero/Development/monaco/node_modules/gulp-tsb/lib/typescript/typescriptServices.js:29036:21)
    at emitIndexedAccess (/Users/bpasero/Development/monaco/node_modules/gulp-tsb/lib/typescript/typescriptServices.js:30349:17)
    at emitJavaScriptWorker (/Users/bpasero/Development/monaco/node_modules/gulp-tsb/lib/typescript/typescriptServices.js:34589:32)
```

**Comment by joaomoreno** [comment]
Actually, now that I think about it... won't fix. These are very rare and it's good they jump in our faces since it's an opportunity for us to communicate the issue back to TypeScript.
