### ISSUE TITLE
Visual studio 2019 16.4.5 keeps closing + CPU high + Power Usage Very high

### ISSUE THREAD

**Issue by abhiz10** [microsoft/vscode#91663]
Visual studio 2019 16.4.5 keeps closing + CPU high + Power Usage Very high + while writing code it gets auto restart
![app error](https://user-images.githubusercontent.com/56038600/75426723-414a9100-596b-11ea-98b9-53ad8ddcde11.PNG)

I'm getting an Application error in Event Viewer
1)
Faulting application name: devenv.exe, version: 16.4.29806.167, time stamp: 0x5e3cf159
Faulting module name: KERNELBASE.dll, version: 10.0.18362.628, time stamp: 0x54734dee

2)
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxFactory.RazorCommentBlock(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxToken, Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxToken, Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxToken, Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxToken, Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxToken)
   at Microsoft.AspNetCore.Razor.Language.Legacy.TokenizerBackedParser`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ParseRazorComment()
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.ParseEmbeddedTransition(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode> ByRef)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.Balance(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode>, Microsoft.AspNetCore.Razor.Language.Legacy.BalancingModes, Microsoft.AspNetCore.Razor.Language.SyntaxKind, Microsoft.AspNetCore.Razor.Language.SyntaxKind, Microsoft.AspNetCore.Razor.Language.SourceLocation)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.Balance(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode>, Microsoft.AspNetCore.Razor.Language.Legacy.BalancingModes)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.TryParseCondition(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode> ByRef)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.ParseConditionalBlock(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode> ByRef, Block)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.ParseConditionalBlock(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode> ByRef, Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.CSharpTransitionSyntax, Boolean)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.ParseIfStatement(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode>, Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.CSharpTransitionSyntax)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.TryParseKeyword(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode> ByRef, System.Collections.Generic.IEnumerable`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxToken>, Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.CSharpTransitionSyntax)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.ParseStatement(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode> ByRef, Block)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.ParseStatement(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode> ByRef, Block)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.ParseCodeBlock(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode> ByRef, Block)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.ParseStatement(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode> ByRef, Block)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.ParseExpectedCodeBlock(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode> ByRef, Block)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.ParseConditionalBlock(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode> ByRef, Block)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.ParseConditionalBlock(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode> ByRef, Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.CSharpTransitionSyntax, Boolean)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.ParseConditionalBlock(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode>, Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.CSharpTransitionSyntax)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.TryParseKeyword(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode> ByRef, System.Collections.Generic.IEnumerable`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxToken>, Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.CSharpTransitionSyntax)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.ParseBlock()
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlMarkupParser.OtherParserBlock(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode> ByRef)
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlMarkupParser.ParseCodeTransition(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode> ByRef)
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlMarkupParser.ParseMarkupNode(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode> ByRef, ParseMode)
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlMarkupParser.ParseMarkupNodes(Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxListBuilder`1<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.RazorSyntaxNode> ByRef, ParseMode, System.Func`2<Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxToken,Boolean>)
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlMarkupParser.ParseDocument()
   at Microsoft.AspNetCore.Razor.Language.Legacy.RazorParser.Parse(Microsoft.AspNetCore.Razor.Language.RazorSourceDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorSyntaxTree.Parse(Microsoft.AspNetCore.Razor.Language.RazorSourceDocument, Microsoft.AspNetCore.Razor.Language.RazorParserOptions)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorParsingPhase.ExecuteCore(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.ProcessCore(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.ProcessDesignTime(Microsoft.AspNetCore.Razor.Language.RazorProjectItem)
   at Microsoft.VisualStudio.Editor.Razor.BackgroundParser+BackgroundThread.WorkerLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by gjsjohnmurray** [comment]
This GitHub repository is for Visual Studio **Code** which isn't the product you are having a problem with. Please close it here and report elsewhere.
