### ISSUE TITLE
[json] error log entries on code completions 

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#91747]
- code assist in a JSON file, e.g. `settings.json`, in the middle of a word
```json
{
    "json.trace.server": "verb|ose"
}
```
- Extension host log shows: 
```
[2020-02-28 11:33:54.185] [exthost] [error] [vscode.json-language-features] provider FAILED
[2020-02-28 11:33:54.185] [exthost] [error] Error: Receving unknown insert replace range.
	at asRange (/home/aeschli/workspaces/vscode/extensions/json-language-features/node_modules/vscode-languageclient/lib/codeConverter.js:220:19)
	at fillPrimaryInsertText (/home/aeschli/workspaces/vscode/extensions/json-language-features/node_modules/vscode-languageclient/lib/codeConverter.js:411:21)
	at Object.asCompletionItem (/home/aeschli/workspaces/vscode/extensions/json-language-features/node_modules/vscode-languageclient/lib/codeConverter.js:356:9)
	at resolveCompletionItem (/home/aeschli/workspaces/vscode/extensions/json-language-features/node_modules/vscode-languageclient/lib/client.js:846:145)
	at Object.resolveCompletionItem (/home/aeschli/workspaces/vscode/extensions/json-language-features/node_modules/vscode-languageclient/lib/client.js:853:27)
	at /home/aeschli/workspaces/vscode/out/vs/workbench/api/common/extHostLanguageFeatures.js:712:59
	at /home/aeschli/workspaces/vscode/out/vs/base/common/async.js:61:26
	at new Promise (<anonymous>)
	at Object.asPromise (/home/aeschli/workspaces/vscode/out/vs/base/common/async.js:60:16)
	at SuggestAdapter.resolveCompletionItem (/home/aeschli/workspaces/vscode/out/vs/workbench/api/common/extHostLanguageFeatures.js:712:28)
	at /home/aeschli/workspaces/vscode/out/vs/workbench/api/common/extHostLanguageFeatures.js:1393:81
	at ExtHostLanguageFeatures._withAdapter (/home/aeschli/workspaces/vscode/out/vs/workbench/api/common/extHostLanguageFeatures.js:1168:27)
	at ExtHostLanguageFeatures.$resolveCompletionItem (/home/aeschli/workspaces/vscode/out/vs/workbench/api/common/extHostLanguageFeatures.js:1393:25)
```

**Comment by aeschli** [comment]
The JSON language client massages all completion items to the new range:{ inserting, replacing } form.
When resolving, the client does not like that format.
