### ISSUE TITLE
Error Cannot run WSL: Disconnected

### ISSUE THREAD

**Issue by jeremiahhoyle** [microsoft/vscode#91971]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by jeremiahhoyle** [comment]
![image](https://user-images.githubusercontent.com/8938864/75810231-d2e14680-5d4f-11ea-8e6d-46fe13de53b0.png)

> [2020-03-03 19:02:10.025] The factory method of "vs/platform/product/common/product" has thrown an exception
[2020-03-03 19:02:10.025] SyntaxError: /home/jhoyle/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/product.json: Unexpected token  in JSON at position 0
[2020-03-03 19:02:10.025]     at JSON.parse (<anonymous>)
[2020-03-03 19:02:10.025]     at Object.Module._extensions..json (internal/modules/cjs/loader.js:799:27)
[2020-03-03 19:02:10.025]     at Module.load (internal/modules/cjs/loader.js:641:32)
[2020-03-03 19:02:10.025]     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
[2020-03-03 19:02:10.025]     at Module.require (internal/modules/cjs/loader.js:681:19)
[2020-03-03 19:02:10.025]     at require (internal/modules/cjs/helpers.js:16:16)
[2020-03-03 19:02:10.025]     at Function.s [as __$__nodeRequire] (/home/jhoyle/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/vs/loader.js:32:963)
[2020-03-03 19:02:10.025]     at Object.<anonymous> (/home/jhoyle/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/vs/server/remoteExtensionHostAgent.js:297:539)
[2020-03-03 19:02:10.025]     at Function.t._safeInvokeFunction (/home/jhoyle/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/vs/loader.js:20:548)
[2020-03-03 19:02:10.025]     at Function.t._invokeFactory (/home/jhoyle/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/vs/loader.js:20:795)
[2020-03-03 19:02:10.025]     at t.complete (/home/jhoyle/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/vs/loader.js:21:10)
[2020-03-03 19:02:10.025]     at s._onModuleComplete (/home/jhoyle/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/vs/loader.js:31:490)
[2020-03-03 19:02:10.025]     at s._resolve (/home/jhoyle/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/vs/loader.js:31:41)
[2020-03-03 19:02:10.025]     at s.defineModule (/home/jhoyle/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/vs/loader.js:25:184)
[2020-03-03 19:02:10.025]     at r (/home/jhoyle/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/vs/loader.js:32:180)
[2020-03-03 19:02:10.025]     at c (/home/jhoyle/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/vs/loader.js:16:958)
[2020-03-03 19:02:10.025]     at Object.<anonymous> (/home/jhoyle/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/vs/server/remoteExtensionHostAgent.js:278:680)
[2020-03-03 19:02:10.025]     at Object.<anonymous> (/home/jhoyle/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/vs/server/remoteExtensionHostAgent.js:480:442)
[2020-03-03 19:02:10.025]     at t._createAndEvalScript (/home/jhoyle/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/vs/loader.js:17:3)
[2020-03-03 19:02:10.025]     at /home/jhoyle/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/out/vs/loader.js:16:639
[2020-03-03 19:02:10.025]     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3) {
[2020-03-03 19:02:10.025]   phase: 'factory',
[2020-03-03 19:02:10.025]   moduleId: 'vs/platform/product/common/product'
[2020-03-03 19:02:10.025] }
[2020-03-03 19:02:10.026] VS Code Server for WSL closed unexpectedly.
[2020-03-03 19:02:10.026] For help with startup problems, go to
[2020-03-03 19:02:10.026] https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips

>

**Comment by aeschli** [comment]
Can you check the content of ` /home/jhoyle/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054/product.json`?

Build 1.41.1 (c47d83b293181d9be64f27ff093689e8e7aed054) has been out there for a long time and works for me. So maybe `product.json` got corrupted?

You can also try to delete ` /home/jhoyle/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054` and restart again.

**Comment by jeremiahhoyle** [comment]
That works thank you!!
