### ISSUE TITLE
autoAttachChildProcesses looses uncaught exception output

### ISSUE THREAD

**Issue by jcmalek** [microsoft/vscode#91980]
Version of VS Code: 1.42.1
Version of Node: v.12.16.1
Operating system: Windows 10 Professional 1909
All extensions disabled

Reproducible steps:
(1) test.js (intended to throw an exception):
console.log(blah.hi);

(2) launch.json:
```js
{
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch TypeError test",
      "program": "${workspaceFolder}/src/test.js",
      "autoAttachChildProcesses": true,
    },
  ]
}
```
What I expected to see in the "Debug Console":
```
C:\Program Files\nodejs\node.exe --inspect-brk=41761 src\test.js 
Debugger listening on ws://127.0.0.1:41761/d10059aa-3777-4c4e-98d5-655526606c60
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
ReferenceError: blah is not defined
    at Object.<anonymous> (c:\Users\CMalek\Desktop\Web-Server\src\test.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:1155:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

What I actually saw in the "Debug Console":
( nothing )

What I actually saw in the "Terminal" tab:
PS C:\Users\CMalek\Desktop\Web-Server> cd 'c:\Users\CMalek\Desktop\Web-Server'; & 'C:\Program Files\nodejs\node.exe' '--inspect-brk=7022' 'src\test.js'
Debugger listening on ws://127.0.0.1:7022/a652a5e3-21a4-4399-956e-6d1363219665
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...

Errors from Dev Tools Console:
```
xterm.js: Terminal.open was called on an element that was not attached to the DOM
  | e._log | @ | c:\Program Files\Mic…term\lib\xterm.js:1
-- | -- | -- | --
  | e.warn | @ | c:\Program Files\Mic…term\lib\xterm.js:1
  | t.open | @ | c:\Program Files\Mic…term\lib\xterm.js:1
  | e.open | @ | c:\Program Files\Mic…term\lib\xterm.js:1
  | (anonymous) | @ | terminalInstance.ts:573
  | processTicksAndRejections | @ | internal/process/task_queues.js:89
  | Promise.then (async) |   |  
  | _attachToElement | @ | terminalInstance.ts:558
  | attachToElement | @ | terminalInstance.ts:547
  | p | @ | terminalTab.ts:192
  | _addChild | @ | terminalTab.ts:105
  | split | @ | terminalTab.ts:47
  | (anonymous) | @ | terminalTab.ts:351
  | attachToElement | @ | terminalTab.ts:351
  | m | @ | terminalTab.ts:250
  | _createInstance | @ | instantiationService.ts:117
  | createInstance | @ | instantiationService.ts:82
  | createTerminal | @ | terminalService.ts:613
  | $createTerminal | @ | mainThreadTerminalService.ts:97
  | _doInvokeHandler | @ | rpcProtocol.ts:398
  | _invokeHandler | @ | rpcProtocol.ts:383
  | _receiveRequest | @ | rpcProtocol.ts:299
  | _receiveOneMessage | @ | rpcProtocol.ts:226
  | (anonymous) | @ | rpcProtocol.ts:101
  | fire | @ | event.ts:582
  | fire | @ | ipc.net.ts:453
  | _receiveMessage | @ | ipc.net.ts:733
  | (anonymous) | @ | ipc.net.ts:592
  | fire | @ | event.ts:582
  | acceptChunk | @ | ipc.net.ts:239
  | (anonymous) | @ | ipc.net.ts:200
  | t | @ | ipc.net.ts:28
  | emit | @ | events.js:200
  | addChunk | @ | _stream_readable.js:294
  | readableAddChunk | @ | _stream_readable.js:275
  | Readable.push | @ | _stream_readable.js:210
  | onStreamRead | @ | internal/stream_base_commons.js:166
```

**Comment by connor4312** [comment]
Since this issue was written we have a [new debugger](https://github.com/microsoft/vscode-js-debug/) which has better behavior around attaching to process trees. Please let us know if you're still running into this issue in VS Code 1.50 or above.
