### ISSUE TITLE
Translation export fails

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#92352]
Exporting translation fails with the following error message:

```` 
[05:10:46] Finished optimize-vscode after 106597 ms

[05:10:46] Starting vscode-translations-export ...

[05:10:47] 'vscode-translations-export' errored after 17 min

[05:10:47] Error: No item ID or value specified: {"id":"add","message":""}

    at XLF.addStringItem (c:\_shift\vscode\vscode\build\lib\i18n.js:159:23)

    at XLF.toString (c:\_shift\vscode\vscode\build\lib\i18n.js:117:26)

    at Stream.<anonymous> (c:\_shift\vscode\vscode\build\lib\i18n.js:548:51)

    at Stream.stream.write (c:\_shift\vscode\vscode\node_modules\through\index.j

s:26:11)

    at DestroyableTransform.ondata (c:\_shift\vscode\vscode\node_modules\readabl

e-stream\lib\_stream_readable.js:612:20)

    at DestroyableTransform.emit (events.js:198:13)

    at DestroyableTransform.EventEmitter.emit (domain.js:466:23)

    at addChunk (c:\_shift\vscode\vscode\node_modules\readable-stream\lib\_strea

m_readable.js:284:12)

    at readableAddChunk (c:\_shift\vscode\vscode\node_modules\readable-stream\li

b\_stream_readable.js:271:11)

    at DestroyableTransform.Readable.push (c:\_shift\vscode\vscode\node_modules\

readable-stream\lib\_stream_readable.js:238:10)

    at DestroyableTransform.Transform.push (c:\_shift\vscode\vscode\node_modules

\readable-stream\lib\_stream_transform.js:146:32)

    at Pumpify.onReadable (c:\_shift\vscode\vscode\node_modules\to-through\index

.js:25:14)

    at Pumpify.emit (events.js:198:13)

    at Pumpify.EventEmitter.emit (domain.js:466:23)

    at emitReadable_ (c:\_shift\vscode\vscode\node_modules\readable-stream\lib\_

stream_readable.js:497:10)

    at emitReadable (c:\_shift\vscode\vscode\node_modules\readable-stream\lib\_s

tream_readable.js:491:65)
````

**Comment by dbaeumer** [comment]
I couldn't reproduce this on tag `1.43.0`. 

The exception is generated since the actual message is the empty string. There is not reason why we shouldn't allow this.

**Comment by janbaltus** [comment]
c:\_shift\vscode\vscode>gulp --max-old-space-size=8192 vscode-translations-export

[06:13:20] Node flags detected: --max-old-space-size=8192
[06:13:20] Respawned to PID: 6408
[06:13:42] Using gulpfile c:\_shift\vscode\vscode\gulpfile.js
[06:13:42] Starting 'vscode-translations-export'...
[06:13:42] Starting clean-out-build ...
[06:13:45] Finished clean-out-build after 3333 ms
[06:13:45] Starting compile-build ...
[06:13:54] Starting compilation...
[06:21:05] Finished compilation with 0 errors after 430528 ms
[06:21:05] Finished compile-build after 439923 ms
[06:21:05] Starting clean-extensions-build ...
[06:21:06] Finished clean-extensions-build after 876 ms
[06:21:06] Starting bundle-extensions-build ...
[06:25:13] Bundled extension: python\extension.webpack.config.js...
[06:26:35] Bundled extension: git-ui\extension.webpack.config.js...
[06:27:13] Bundled extension: search-result\extension.webpack.config.js...
[06:27:22] Bundled extension: debug-auto-launch\extension.webpack.config.js...
[06:27:23] Bundled extension: debug-server-ready\extension.webpack.config.js...
[06:27:27] Bundled extension: jake\extension.webpack.config.js...
[06:27:27] Bundled extension: gulp\extension.webpack.config.js...
[06:27:28] Bundled extension: image-preview\extension.webpack.config.js...
[06:27:28] Bundled extension: grunt\extension.webpack.config.js...
[06:27:29] Bundled extension: vscode-account\extension.webpack.config.js...
[06:27:37] Bundled extension: configuration-editing\extension.webpack.config.js.
..
[06:27:37] Bundled extension: github-authentication\extension.webpack.config.js.
..
[06:27:38] Bundled extension: merge-conflict\extension.webpack.config.js...
[06:27:53] Bundled extension: php-language-features\extension.webpack.config.js.
..
[06:28:02] Bundled extension: npm\extension.webpack.config.js...
[06:28:03] Bundled extension: css-language-features\extension.webpack.config.js.
..
[06:28:05] Bundled extension: extension-editing\extension.webpack.config.js...
[06:28:06] Bundled extension: json-language-features\server\extension.webpack.co
nfig.js...
[06:28:09] Bundled extension: emmet\extension.webpack.config.js...
[06:28:11] Bundled extension: html-language-features\extension.webpack.config.js
...
[06:28:13] Bundled extension: json-language-features\extension.webpack.config.js
...
[06:28:18] Bundled extension: typescript-language-features\extension.webpack.con
fig.js...
[06:28:23] Bundled extension: git\extension.webpack.config.js...
[06:28:30] Bundled extension: css-language-features\server\extension.webpack.con
fig.js...
[06:28:30] Bundled extension: markdown-language-features\extension.webpack.confi
g.js...
[06:28:36] Bundled extension: html-language-features\server\extension.webpack.co
nfig.js...
[06:28:41] Finished bundle-extensions-build after 454570 ms
[06:28:41] Starting bundle-marketplace-extensions-build ...
[06:28:41] Downloading extension: ms-vscode.node-debug@1.44.2 ...
[06:28:41] Downloading extension: ms-vscode.node-debug2@1.42.1 ...
[06:28:41] Downloading extension: ms-vscode.references-view@0.0.49 ...
[06:28:41] Downloading extension: ms-vscode.js-debug-nightly@2020.3.317 ...
[06:28:41] Downloading extension: ms-vscode.js-debug-companion@0.0.4 ...
[06:28:47] Finished bundle-marketplace-extensions-build after 6150 ms
[06:28:47] Starting compile-extensions-build ...
[06:28:47] Finished compile-extensions-build after 0 ms
[06:28:47] Starting clean-out-vscode ...
[06:28:47] Finished clean-out-vscode after 133 ms
[06:28:47] Starting optimize-vscode ...
CSS INLINING IMAGE AT out-build\vs\editor\contrib\colorPicker\images\opacity-bac
kground.png MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\contrib\comments\browser\media\reac
tion-light.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\contrib\comments\browser\media\reac
tion-dark.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\contrib\comments\browser\media\reac
tion-hc.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\contrib\extensions\browser\media\lo
ading.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\contrib\feedback\browser\media\info
.svg MORE THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
CSS INLINING IMAGE AT out-build\vs\workbench\contrib\welcome\code-icon.svg MORE
THAN ONCE. CONSIDER CONSOLIDATING CSS RULES
[06:30:40] Finished optimize-vscode after 112705 ms
[06:30:40] Starting vscode-translations-export ...
[06:30:41] 'vscode-translations-export' errored after 17 min
[06:30:41] Error: No item ID or value specified: {"id":"add","message":""}
    at XLF.addStringItem (c:\_shift\vscode\vscode\build\lib\i18n.js:159:23)
    at XLF.toString (c:\_shift\vscode\vscode\build\lib\i18n.js:117:26)
    at Stream.<anonymous> (c:\_shift\vscode\vscode\build\lib\i18n.js:548:51)
    at Stream.stream.write (c:\_shift\vscode\vscode\node_modules\through\index.j
s:26:11)
    at DestroyableTransform.ondata (c:\_shift\vscode\vscode\node_modules\readabl
e-stream\lib\_stream_readable.js:612:20)
    at DestroyableTransform.emit (events.js:198:13)
    at DestroyableTransform.EventEmitter.emit (domain.js:466:23)
    at addChunk (c:\_shift\vscode\vscode\node_modules\readable-stream\lib\_strea
m_readable.js:284:12)
    at readableAddChunk (c:\_shift\vscode\vscode\node_modules\readable-stream\li
b\_stream_readable.js:271:11)
    at DestroyableTransform.Readable.push (c:\_shift\vscode\vscode\node_modules\
readable-stream\lib\_stream_readable.js:238:10)
    at DestroyableTransform.Transform.push (c:\_shift\vscode\vscode\node_modules
\readable-stream\lib\_stream_transform.js:146:32)
    at Pumpify.onReadable (c:\_shift\vscode\vscode\node_modules\to-through\index
.js:25:14)
    at Pumpify.emit (events.js:198:13)
    at Pumpify.EventEmitter.emit (domain.js:466:23)
    at emitReadable_ (c:\_shift\vscode\vscode\node_modules\readable-stream\lib\_
stream_readable.js:497:10)
    at emitReadable (c:\_shift\vscode\vscode\node_modules\readable-stream\lib\_s
tream_readable.js:491:65)

**Comment by dbaeumer** [comment]
@janbaltus is this on master ?

**Comment by dbaeumer** [comment]
Could reproduce on master. For 1.43.0 (the stable build from yesterday) please export the translation on that version

**Comment by dbaeumer** [comment]
The problematic code is here:

https://github.com/Microsoft/vscode/blob/master/src/vs/platform/theme/common/iconRegistry.ts#L144

@aeschli can you comment on why you need to externalize empty strings?

**Comment by dbaeumer** [comment]
@janbaltus can you comment on whether your translation platfrom can handle items with an empty message (e.g. `""`).

**Comment by janbaltus** [comment]
The localization platform can handle empty string.
