### ISSUE TITLE
https://vscode-update.azurewebsites.net/api/releases/stable appears to be down

### ISSUE THREAD

**Issue by adunndevster** [microsoft/vscode#92388]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. yo code

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({ responseText:
   'Unable to connect to https://vscode-update.azurewebsites.net/api/releases/stable. Error: connect ETIMEDOUT 40.83.182.206:443',
  status: 404 })
    at module.exports.emit (events.js:187:17)
    at module.exports.EventEmitter.emit (domain.js:448:20)
    at Immediate.setImmediate (C:\Users\addun\AppData\Roaming\npm\node_modules\generator-code\node_modules\yeoman-generator\lib\index.js:668:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by qq745639151** [comment]
Excuseme, I have meet the same problem,Can you share your solution with me?

**Comment by msx752** [comment]
i had same issue too, i tried several times `yo code` then it worked i don't know how.
