### ISSUE TITLE
TS Server fatal error:  Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by akbarsahata** [microsoft/vscode#92424]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.7.5
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
TypeError: Cannot read property 'path' of undefined
    at ProjectService.updateNonInferredProjectFiles (tsserver.js:137473:43)
    at ProjectService.addFilesToNonInferredProject (tsserver.js:137363:22)
    at ProjectService.updateRootAndOptionsOfNonInferredProject (tsserver.js:137511:22)
    at ProjectService.loadConfiguredProject (tsserver.js:137447:22)
    at ProjectService.createAndLoadConfiguredProject (tsserver.js:137387:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (tsserver.js:137392:36)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:138217:44)
    at tsserver.js:138448:107
    at Object.mapDefined (tsserver.js:565:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:138448:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139302:46)
    at tsserver.js:140960:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140951:28)
    at IOSession.Session.executeCommand (tsserver.js:140960:33)
    at IOSession.Session.onMessage (tsserver.js:140983:35)
    at Interface.<anonymous> (tsserver.js:142298:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 5, 3|
|Memory (System)|8.00GB (0.91GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|2.1.1
swagger-viewer|Arj|2.2.2
vscode-eslint|dba|2.1.1
gitlens|eam|10.2.1
vscode-peacock|joh|3.6.0
vscode-map-preview|jum|0.5.1
dotenv|mik|1.0.1
vscode-docker|ms-|1.0.0
vscode-kubernetes-tools|ms-|1.1.0
Go|ms-|0.13.1
material-icon-theme|PKi|4.0.1
vscode-yaml|red|0.7.2
bunker|sld|1.1.6
vscode-wakatime|Wak|4.0.0
vscode-proto3|zxh|0.4.2

</details>

**Comment by mjbvz** [comment]
You are using an old TS version (3.7.5)

Do yo see this with TypeScript 3.8+?

**Comment by akbarsahata** [comment]
I just updated the ts version. will update if same issue occurs

**Comment by mjbvz** [comment]
Closing as more info needed to see if this happens in 3.8+ as well
