### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by GabrielNorell** [microsoft/vscode#92710]
Issue Type: <b>Bug</b>

Hi,
I downloaded Ananconda to get its modules. Everything went smoothly until I tried to import a module. When I hit run I got this error message:
  1. Check that you expected to use Python3.7 from "C:\Users\egabnor5\Anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

Answer:
I have multiple verisons of Python installed and are presently running "Python 3.7.6 64-bit ('base': conda)". 

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-7Y30 CPU @ 1.00GHz (4 x 1608)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.4.67516-dev
vscode-yaml|red|0.7.2

</details>

**Comment by GabrielNorell** [comment]
`PS C:\Users\egabnor5\OneDrive – Jämtlands Gymnasieförbund\Desktop\python_work> & C:/Users/egabnor5/Anaconda3/python.exe "c:/Users/egabnor5/OneDrive – Jämtlands Gymnasieförbund/Desktop/python_work/testcon.py"
C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 24,
in <module>
    from . import multiarray
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 7,
in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: Det går inte att hitta den angivna modulen.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/egabnor5/OneDrive – Jämtlands Gymnasieförbund/Desktop/python_work/testcon.py", line 1, in <module>
    import numpy
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 54,
in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\egabnor5\Anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: Det går inte att hitta den angivna modulen.

PS C:\Users\egabnor5\OneDrive – Jämtlands Gymnasieförbund\Desktop\python_work> conda activate base
conda : The term 'conda' is not recognized as the name of a cmdlet, function, script fi
le, or operable program. Check the spelling of the name, or if a path was included, ver
ify that the path is correct and try again.
At line:1 char:1
+ conda activate base
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundExcept 
   ion
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\egabnor5\OneDrive – Jämtlands Gymnasieförbund\Desktop\python_work> & C:/Users/egabnor5/Anaconda3/python.exe "c:/Users/egabnor5/OneDrive – Jämtlands Gymnasieförbund/Desktop/python_work/testcon.py"
C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 24,
in <module>
    from . import multiarray
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 7,
in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: Det går inte att hitta den angivna modulen.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/egabnor5/OneDrive – Jämtlands Gymnasieförbund/Desktop/python_work/testcon.py", line 1, in <module>
    import numpy
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 54,
in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\egabnor5\Anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: Det går inte att hitta den angivna modulen.`

**Comment by GabrielNorell** [comment]
`PS C:\Users\egabnor5\OneDrive – Jämtlands Gymnasieförbund\Desktop\python_work> & C:/Users/egabnor5/Anaconda3/python.exe "c:/Users/egabnor5/OneDrive – Jämtlands Gymnasieförbund/Desktop/python_work/testcon.py"
C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 24,
in <module>
    from . import multiarray
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 7,
in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: Det går inte att hitta den angivna modulen.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/egabnor5/OneDrive – Jämtlands Gymnasieförbund/Desktop/python_work/testcon.py", line 1, in <module>
    import numpy
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 54,
in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\egabnor5\Anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: Det går inte att hitta den angivna modulen.

PS C:\Users\egabnor5\OneDrive – Jämtlands Gymnasieförbund\Desktop\python_work> conda activate base
conda : The term 'conda' is not recognized as the name of a cmdlet, function, script fi
le, or operable program. Check the spelling of the name, or if a path was included, ver
ify that the path is correct and try again.
At line:1 char:1
+ conda activate base
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundExcept 
   ion
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\egabnor5\OneDrive – Jämtlands Gymnasieförbund\Desktop\python_work> & C:/Users/egabnor5/Anaconda3/python.exe "c:/Users/egabnor5/OneDrive – Jämtlands Gymnasieförbund/Desktop/python_work/testcon.py"
C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 24,
in <module>
    from . import multiarray
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 7,
in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: Det går inte att hitta den angivna modulen.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/egabnor5/OneDrive – Jämtlands Gymnasieförbund/Desktop/python_work/testcon.py", line 1, in <module>
    import numpy
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 54,
in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\egabnor5\Anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: Det går inte att hitta den angivna modulen.`

**Comment by GabrielNorell** [comment]
This was the complete (and extensive) error message:

PS C:\Users\egabnor5\OneDrive – Jämtlands Gymnasieförbund\Desktop\python_work> & C:/Users/egabnor5/Anaconda3/python.exe "c:/Users/egabnor5/OneDrive – Jämtlands Gymnasieförbund/Desktop/python_work/testcon.py"
C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 24,
in <module>
    from . import multiarray
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 7,
in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: Det går inte att hitta den angivna modulen.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/egabnor5/OneDrive – Jämtlands Gymnasieförbund/Desktop/python_work/testcon.py", line 1, in <module>
    import numpy
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 54,
in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\egabnor5\Anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: Det går inte att hitta den angivna modulen.

PS C:\Users\egabnor5\OneDrive – Jämtlands Gymnasieförbund\Desktop\python_work> conda activate base
conda : The term 'conda' is not recognized as the name of a cmdlet, function, script fi
le, or operable program. Check the spelling of the name, or if a path was included, ver
ify that the path is correct and try again.
At line:1 char:1
+ conda activate base
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundExcept 
   ion
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\Users\egabnor5\OneDrive – Jämtlands Gymnasieförbund\Desktop\python_work> & C:/Users/egabnor5/Anaconda3/python.exe "c:/Users/egabnor5/OneDrive – Jämtlands Gymnasieförbund/Desktop/python_work/testcon.py"
C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\__init__.py:140: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 24,
in <module>
    from . import multiarray
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 7,
in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: Det går inte att hitta den angivna modulen.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/egabnor5/OneDrive – Jämtlands Gymnasieförbund/Desktop/python_work/testcon.py", line 1, in <module>
    import numpy
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\egabnor5\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 54,
in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "C:\Users\egabnor5\Anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: Det går inte att hitta den angivna modulen.

**Comment by GabrielNorell** [comment]
I reinstalled Anaconda and this time "added to PATH"
