### ISSUE TITLE
TS Server fatal error:  Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by scharepmc2hr** [microsoft/vscode#92782]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.4.5
**TS Server Error Stack**
```
TypeError: Cannot read property 'path' of undefined
    at ProjectService.updateNonInferredProjectFiles (tsserver.js:127107:43)
    at ProjectService.addFilesToNonInferredProject (tsserver.js:127002:22)
    at ProjectService.updateRootAndOptionsOfNonInferredProject (tsserver.js:127145:22)
    at ProjectService.loadConfiguredProject (tsserver.js:127081:22)
    at ProjectService.createAndLoadConfiguredProject (tsserver.js:127026:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (tsserver.js:127031:36)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:127839:44)
    at tsserver.js:128055:76
    at Array.forEach (<anonymous>)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:128055:37)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:128801:46)
    at tsserver.js:130466:88
    at IOSession.Session.executeWithRequestId (tsserver.js:130457:28)
    at IOSession.Session.executeCommand (tsserver.js:130466:33)
    at IOSession.Session.onMessage (tsserver.js:130488:35)
    at Interface.<anonymous> (tsserver.js:131789:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment]
You are using an old TypeScript version: 3.4

Does this reproduce if you use TS 3.8?
