### ISSUE TITLE
Web integration test: flaky terminal tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#92826]
Seeing 2 test failures today for integration tests in Web (https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=69743&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=c9c1d16f-6a21-57a3-556a-d7a168909c84):

```
2020-03-17T05:50:36.9920373Z   1) window namespace tests Terminal sendText immediately after createTerminal should not throw:
2020-03-17T05:50:36.9920968Z 
2020-03-17T05:50:36.9921640Z       AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: f {
2020-03-17T05:50:36.9922286Z   _creationOptions: {
2020-03-17T05:50:36.9923948Z     name: undefined,
2020-03-17T05:50:36.9924516Z     shellArgs: undefined,
2020-03-17T05:50:36.9925366Z     shellPath: undefined
2020-03-17T05:50:36.9926089Z   },
2020-03-17T05:50:36.9926596Z   _disposed: false,
2020-03-17T05:50:36.9927152Z   _idPromise: Promise {
2020-03-17T05:50:36.9927690Z     <pending>
2020-03-17T05:50:36.9928185Z   },
2020-03-17T05:50:36.9928720Z   _idPromiseComplete: [Function],
2020-03-17T05:50:36.9929310Z   _name: undefined,
2020-03-17T05:50:36.9929860Z   _pidPromise: Promise {
2020-03-17T05:50:36.9930395Z     <pending>
2020-03-17T05:50:36.9930886Z   },
2020-03-17T05:50:36.9931419Z   _pidPromiseComplete: [Function],
2020-03-17T05:50:36.9932034Z   _proxy: [Object: null prototype] {
2020-03-17T05:50:36.9932658Z     '$createTerminal': [Function],
2020-03-17T05:50:36.9933265Z     '$sendProcessData': [Function],
2020-03-17T05:50:36.9933855Z     '$sendText': [Function]
2020-03-17T05:50:36.9934385Z   },
2020-03-17T05:50:36.9934889Z   _queuedRequests: [
2020-03-17T05:50:36.9935406Z     g {
2020-03-17T05:50:36.9936128Z       _args: [
2020-03-17T05:50:36.9936718Z         'echo "foo"',
2020-03-17T05:50:36.9937353Z    ... == f {
2020-03-17T05:50:36.9937865Z   _creationOptions: {
2020-03-17T05:50:36.9938591Z     cwd: undefined,
2020-03-17T05:50:36.9939281Z     env: undefined,
2020-03-17T05:50:36.9939916Z     name: undefined,
2020-03-17T05:50:36.9940549Z     shellArgs: undefined,
2020-03-17T05:50:36.9941177Z     shellPath: undefined
2020-03-17T05:50:36.9941757Z   },
2020-03-17T05:50:36.9942345Z   _disposed: false,
2020-03-17T05:50:36.9942989Z   _id: 1,
2020-03-17T05:50:36.9943635Z   _idPromise: Promise {
2020-03-17T05:50:36.9944278Z     1
2020-03-17T05:50:36.9945098Z   },
2020-03-17T05:50:36.9945723Z   _name: 'Starting...',
2020-03-17T05:50:36.9946413Z   _pidPromise: Promise {
2020-03-17T05:50:36.9947072Z     <pending>
2020-03-17T05:50:36.9947676Z   },
2020-03-17T05:50:36.9948368Z   _pidPromiseComplete: [Function],
2020-03-17T05:50:36.9962604Z   _proxy: [Object: null prototype] {
2020-03-17T05:50:36.9963926Z     '$createTerminal': [Function],
2020-03-17T05:50:36.9964649Z     '$sendProcessData': [Function],
2020-03-17T05:50:36.9965336Z     '$sendText': [Function]
2020-03-17T05:50:36.9965948Z   },
2020-03-17T05:50:36.9966542Z   _queuedRequests: [],
2020-03-17T05:50:36.9967175Z   isOpen: false
2020-03-17T05:50:36.9967755Z }
2020-03-17T05:50:36.9968325Z       + expected - actual
2020-03-17T05:50:36.9968806Z 
2020-03-17T05:50:36.9969348Z        {
2020-03-17T05:50:36.9969920Z       -  "_cols": 0
2020-03-17T05:50:36.9970551Z          "_creationOptions": {
2020-03-17T05:50:36.9971221Z       +    "cwd": [undefined]
2020-03-17T05:50:36.9971883Z       +    "env": [undefined]
2020-03-17T05:50:36.9972600Z            "name": [undefined]
2020-03-17T05:50:36.9973300Z            "shellArgs": [undefined]
2020-03-17T05:50:36.9974829Z            "shellPath": [undefined]
2020-03-17T05:50:36.9975654Z          }
2020-03-17T05:50:36.9976268Z       -  "_disposed": true
2020-03-17T05:50:36.9976928Z       -  "_exitStatus": {
2020-03-17T05:50:36.9977585Z       -    "code": [undefined]
2020-03-17T05:50:36.9978214Z       -  }
2020-03-17T05:50:36.9978850Z       +  "_disposed": false
2020-03-17T05:50:36.9979489Z          "_id": 1
2020-03-17T05:50:36.9980160Z          "_idPromise": "[object Promise]"
2020-03-17T05:50:36.9980889Z       -  "_idPromiseComplete": [undefined]
2020-03-17T05:50:36.9981652Z          "_name": "Starting..."
2020-03-17T05:50:36.9982274Z          "_pidPromise": "[object Promise]"
2020-03-17T05:50:36.9982937Z          "_pidPromiseComplete": [Function]
2020-03-17T05:50:36.9983536Z          "_proxy": {
2020-03-17T05:50:36.9984161Z            "$startSendingDataEvents": [Function]
2020-03-17T05:50:36.9989164Z            "$stopSendingDataEvents": [Function]
2020-03-17T05:50:36.9989924Z          }
2020-03-17T05:50:36.9990497Z          "_queuedRequests": []
2020-03-17T05:50:36.9991105Z       -  "_rows": 0
2020-03-17T05:50:36.9991670Z       -  "isOpen": false
2020-03-17T05:50:36.9992249Z       +  "isOpen": true
2020-03-17T05:50:36.9992784Z        }
2020-03-17T05:50:36.9993267Z       
2020-03-17T05:50:36.9993924Z       at extensions\vscode-api-tests\src\singlefolder-tests\terminal.test.ts:25:6
2020-03-17T05:50:36.9994846Z       at e.fire (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:51:497)
2020-03-17T05:50:36.9996048Z       at e.$acceptTerminalOpened (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:707:362)
2020-03-17T05:50:36.9997193Z       at e._doInvokeHandler (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:745:683)
2020-03-17T05:50:36.9998311Z       at e._invokeHandler (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:745:375)
2020-03-17T05:50:36.9999450Z       at e._receiveRequest (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:744:14)
2020-03-17T05:50:37.0000564Z       at e._receiveOneMessage (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:742:832)
2020-03-17T05:50:37.0001658Z       at d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:741:34
2020-03-17T05:50:37.0002729Z       at e.fire (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:51:497)
2020-03-17T05:50:37.0003787Z       at v.fire (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:203:274)
2020-03-17T05:50:37.0004842Z       at d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:911:179
2020-03-17T05:50:37.0005870Z       at e.fire (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:51:497)
2020-03-17T05:50:37.0007074Z       at v.fire (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:203:274)
2020-03-17T05:50:37.0008190Z       at t.PersistentProtocol._receiveMessage (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:207:629)
2020-03-17T05:50:37.0009523Z       at d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:204:824
2020-03-17T05:50:37.0010422Z       at e.fire (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:51:497)
2020-03-17T05:50:37.0011357Z       at p.acceptChunk (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:200:737)
2020-03-17T05:50:37.0012292Z       at d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:200:89
2020-03-17T05:50:37.0013182Z       at e.fire (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:51:497)
2020-03-17T05:50:37.0016338Z       at m._acceptChunk (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:211:791)
2020-03-17T05:50:37.0019938Z       at d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:209:977
2020-03-17T05:50:37.0021076Z       at Socket.t (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:209:185)
2020-03-17T05:50:37.0022034Z       at addChunk (_stream_readable.js:294:12)
2020-03-17T05:50:37.0022828Z       at readableAddChunk (_stream_readable.js:275:11)
2020-03-17T05:50:37.0023651Z       at Socket.Readable.push (_stream_readable.js:210:10)
2020-03-17T05:50:37.0024482Z       at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
2020-03-17T05:50:37.0025080Z 
2020-03-17T05:50:37.0025774Z   2) window namespace tests Terminal name in constructor should set terminal.name:
2020-03-17T05:50:37.0026370Z 
2020-03-17T05:50:37.0027236Z       AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: f {
2020-03-17T05:50:37.0028010Z   _creationOptions: {
2020-03-17T05:50:37.0028673Z     name: 'a',
2020-03-17T05:50:37.0029963Z     shellArgs: undefined,
2020-03-17T05:50:37.0030703Z     shellPath: undefined
2020-03-17T05:50:37.0031345Z   },
2020-03-17T05:50:37.0031962Z   _disposed: false,
2020-03-17T05:50:37.0032637Z   _idPromise: Promise {
2020-03-17T05:50:37.0033282Z     <pending>
2020-03-17T05:50:37.0033919Z   },
2020-03-17T05:50:37.0034580Z   _idPromiseComplete: [Function],
2020-03-17T05:50:37.0035292Z   _name: 'a',
2020-03-17T05:50:37.0035951Z   _pidPromise: Promise {
2020-03-17T05:50:37.0036597Z     <pending>
2020-03-17T05:50:37.0037183Z   },
2020-03-17T05:50:37.0037832Z   _pidPromiseComplete: [Function],
2020-03-17T05:50:37.0038592Z   _proxy: [Object: null prototype] {
2020-03-17T05:50:37.0039425Z     '$createTerminal': [Function],
2020-03-17T05:50:37.0040147Z     '$dispose': [Function],
2020-03-17T05:50:37.0040880Z     '$sendProcessData': [Function],
2020-03-17T05:50:37.0041627Z     '$sendProcessExit': [Function],
2020-03-17T05:50:37.0042373Z     '$sendProcessReady': [Function],
2020-03-17T05:50:37.0043081Z     '$sendPro... == f {
2020-03-17T05:50:37.0043879Z   _creationOptions: {
2020-03-17T05:50:37.0044498Z     cwd: undefined,
2020-03-17T05:50:37.0045112Z     env: undefined,
2020-03-17T05:50:37.0045715Z     name: 'a',
2020-03-17T05:50:37.0046339Z     shellArgs: undefined,
2020-03-17T05:50:37.0046989Z     shellPath: undefined
2020-03-17T05:50:37.0047633Z   },
2020-03-17T05:50:37.0048127Z   _disposed: false,
2020-03-17T05:50:37.0048639Z   _id: 4,
2020-03-17T05:50:37.0049155Z   _idPromise: Promise {
2020-03-17T05:50:37.0049666Z     4
2020-03-17T05:50:37.0050142Z   },
2020-03-17T05:50:37.0050675Z   _name: 'a',
2020-03-17T05:50:37.0051208Z   _pidPromise: Promise {
2020-03-17T05:50:37.0051741Z     <pending>
2020-03-17T05:50:37.0052226Z   },
2020-03-17T05:50:37.0052748Z   _pidPromiseComplete: [Function],
2020-03-17T05:50:37.0053359Z   _proxy: [Object: null prototype] {
2020-03-17T05:50:37.0053979Z     '$createTerminal': [Function],
2020-03-17T05:50:37.0054751Z     '$dispose': [Function],
2020-03-17T05:50:37.0057495Z     '$sendProcessData': [Function],
2020-03-17T05:50:37.0058263Z     '$sendProcessExit': [Function],
2020-03-17T05:50:37.0059027Z     '$sendProcessReady': [Function],
2020-03-17T05:50:37.0059678Z     '...
2020-03-17T05:50:37.0060483Z       + expected - actual
2020-03-17T05:50:37.0061157Z 
2020-03-17T05:50:37.0061737Z        {
2020-03-17T05:50:37.0062371Z       +  "_cols": 0
2020-03-17T05:50:37.0063065Z          "_creationOptions": {
2020-03-17T05:50:37.0063802Z       +    "cwd": [undefined]
2020-03-17T05:50:37.0064516Z       +    "env": [undefined]
2020-03-17T05:50:37.0065202Z            "name": "a"
2020-03-17T05:50:37.0065915Z            "shellArgs": [undefined]
2020-03-17T05:50:37.0066662Z            "shellPath": [undefined]
2020-03-17T05:50:37.0067354Z          }
2020-03-17T05:50:37.0067999Z       -  "_disposed": true
2020-03-17T05:50:37.0068692Z       -  "_exitStatus": {
2020-03-17T05:50:37.0069386Z       -    "code": [undefined]
2020-03-17T05:50:37.0070159Z       -  }
2020-03-17T05:50:37.0070749Z       +  "_disposed": false
2020-03-17T05:50:37.0071382Z          "_id": 4
2020-03-17T05:50:37.0072031Z          "_idPromise": "[object Promise]"
2020-03-17T05:50:37.0072742Z       -  "_idPromiseComplete": [undefined]
2020-03-17T05:50:37.0073411Z          "_name": "a"
2020-03-17T05:50:37.0074154Z          "_pidPromise": "[object Promise]"
2020-03-17T05:50:37.0074782Z          "_pidPromiseComplete": [Function]
2020-03-17T05:50:37.0077043Z          "_proxy": {
2020-03-17T05:50:37.0077719Z            "$startSendingDataEvents": [Function]
2020-03-17T05:50:37.0078405Z            "$stopSendingDataEvents": [Function]
2020-03-17T05:50:37.0079009Z          }
2020-03-17T05:50:37.0079610Z          "_queuedRequests": []
2020-03-17T05:50:37.0080186Z       -  "isOpen": false
2020-03-17T05:50:37.0080738Z       +  "_rows": 0
2020-03-17T05:50:37.0081280Z       +  "isOpen": true
2020-03-17T05:50:37.0081908Z        }
2020-03-17T05:50:37.0082349Z       
2020-03-17T05:50:37.0082911Z       at extensions\vscode-api-tests\src\singlefolder-tests\terminal.test.ts:72:6
2020-03-17T05:50:37.0083682Z       at e.fire (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:51:497)
2020-03-17T05:50:37.0088472Z       at e.$acceptTerminalOpened (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:707:362)
2020-03-17T05:50:37.0089725Z       at e._doInvokeHandler (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:745:683)
2020-03-17T05:50:37.0090615Z       at e._invokeHandler (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:745:375)
2020-03-17T05:50:37.0091462Z       at e._receiveRequest (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:744:14)
2020-03-17T05:50:37.0092309Z       at e._receiveOneMessage (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:742:832)
2020-03-17T05:50:37.0093127Z       at d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:741:34
2020-03-17T05:50:37.0093929Z       at e.fire (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:51:497)
2020-03-17T05:50:37.0094942Z       at v.fire (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:203:274)
2020-03-17T05:50:37.0095845Z       at d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:911:179
2020-03-17T05:50:37.0096744Z       at e.fire (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:51:497)
2020-03-17T05:50:37.0097682Z       at v.fire (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:203:274)
2020-03-17T05:50:37.0098666Z       at t.PersistentProtocol._receiveMessage (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:207:629)
2020-03-17T05:50:37.0099700Z       at d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:204:824
2020-03-17T05:50:37.0100765Z       at e.fire (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:51:497)
2020-03-17T05:50:37.0101709Z       at p.acceptChunk (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:200:737)
2020-03-17T05:50:37.0102640Z       at d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:200:89
2020-03-17T05:50:37.0103607Z       at e.fire (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:51:497)
2020-03-17T05:50:37.0104543Z       at m._acceptChunk (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:211:791)
2020-03-17T05:50:37.0105482Z       at d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:209:977
2020-03-17T05:50:37.0106398Z       at Socket.t (d:\a\1\vscode-reh-web-win32-x64\out\vs\server\remoteExtensionHostProcess.js:209:185)
2020-03-17T05:50:37.0107195Z       at addChunk (_stream_readable.js:294:12)
2020-03-17T05:50:37.0108032Z       at readableAddChunk (_stream_readable.js:275:11)
2020-03-17T05:50:37.0108657Z       at Socket.Readable.push (_stream_readable.js:210:10)
2020-03-17T05:50:37.0109458Z       at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by Tyriar** [comment]
@bpasero feel free to skip them if needed, they're known to be flaky. This was my top priority for debt week but it was completely consumed with the settings sync preview.

**Comment by bpasero** [comment]
@Tyriar you mean flaky in general or only for web?

**Comment by Tyriar** [comment]
Flaky in general, it seems especially on web though.

**Comment by bpasero** [comment]
We can leave them running, I am not seeing them failing often, just found this one. It is not something to look at now, but eventually. Will revisit if I see this again more frequently.

**Comment by bpasero** [comment]
@Tyriar ok seeing them fail again today, pushing to disable them when running in web via checking for `env.UIKInd === UIKind.web`.

Your tests seem to have a questionable use of `done`, I see one error being that `done` is called multiple times. Why do you not rewrite to use async and promises?

 ```
 3) window namespace tests Terminal onDidCloseTerminal event fires when terminal is disposed:
     Error: done() called multiple times
```

**Comment by bpasero** [comment]
Another one: https://github.com/microsoft/vscode/commit/9f2cc0cc799929002cebaebc065c3a13ceed4948

**Comment by bpasero** [comment]
I ended up disabling them all for web: https://github.com/microsoft/vscode/commit/c0eea2a712471a4d242d15704cfa968241d63280

**Comment by KnisterPeter** [comment]
Maybe this has now leaked from the tests into the code itself.
I'm creating a new terminal within an extension using the `createTerminal` API and give it a pseudo terminal.
Sometimes the terminal is shown but no output is displayed and `sendText` does not work.
But I can also see no error or trace.

This happens for me in vscode 1.44.2 unter linux.

**Comment by joaomoreno** [comment]
@Tyriar Is this still an issue?
