### ISSUE TITLE
git integration tests fail in stable builds

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#92842]
@jrieken Assigning for dispatch. Are the built-in extensions not flagged as such in the integration tests and should that be fixed?

```
[2228:0317/103357.172:INFO:CONSOLE(2786)] "Activating extension 'vscode.git' failed: [vscode.git]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscode.git.", source: file:///D:/a/1/VSCode-win32-x64/resources/app/out/vs/workbench/workbench.desktop.main.js (2786)
    1) "before all" hook
  22 passing (2s)
  1 failing
  1) git smoke test "before all" hook:
     Error: [vscode.git]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api vscode.git
      at a (d:\a\1\VSCode-win32-x64\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:515:620)
      at Object.t.checkProposedApiEnabled (d:\a\1\VSCode-win32-x64\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:515:982)
      at Object.registerDiffInformationCommand (d:\a\1\VSCode-win32-x64\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:793:295)
      at d:\a\1\s\extensions\git\src\commands.ts:250:21
      at Array.map (<anonymous>)
      at new CommandCenter (d:\a\1\s\extensions\git\src\commands.ts:246:31)
      at createModel (d:\a\1\s\extensions\git\src\main.ts:82:3)
      at activate (d:\a\1\s\extensions\git\src\main.ts:168:17)
```

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/commit/1bd8e5b76bcfbe8a9a26422006afd6e4c46348f2
