### ISSUE TITLE
Console report 'fillRect' is not a function

### ISSUE THREAD

**Issue by Deliay** [microsoft/vscode#92906]
Issue Type: <b>Bug</b>

Disable all extensions still can reproduce....

```
  ERR l.fillRect is not a function: TypeError: l.fillRect is not a function
    at h._render (file:///C:/Program Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:2181:878)
    at h.render (file:///C:/Program Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:2181:279)
    at z._actualRender (file:///C:/Program Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:2198:865)
    at file:///C:/Program Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:2197:910
    at K (file:///C:/Program Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:2201:350)
    at z._renderNow (file:///C:/Program Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:2197:899)
    at z.restoreState (file:///C:/Program Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:2199:116)
    at e.restoreViewState (file:///C:/Program Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:2215:600)
    at w.setInput (file:///C:/Program Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:5089:951)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async p.doSetInput (file:///C:/Program Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:4185:825)
    at async p.openEditor (file:///C:/Program Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:4184:464)
    at async file:///C:/Program Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:5609:902
    at async e.restoreEditors (file:///C:/Program Files/VSCode/resources/app/out/vs/workbench/workbench.desktop.main.js:5604:131)
```

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 4075)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (32.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.1
mocode|Del|0.0.4
gitlens|eam|10.2.1
plantuml|jeb|2.13.6
language-haskell|jus|2.7.0
vscode-docker|ms-|1.0.0
csharp|ms-|1.21.14
python|ms-|2020.2.64397
remote-ssh|ms-|0.50.0
remote-ssh-edit|ms-|0.50.0
remote-wsl|ms-|0.42.3
powershell|ms-|2020.3.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vetur|oct|0.24.0
java|red|0.58.0
glassit|s-n|0.1.6
language-stylus|sys|1.11.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.2
vscode-maven|vsc|0.21.1

</details>

**Comment by alexdima** [comment]
@Deliay Do you have any steps? Does this happen all the time for you or only sometimes? Do you see an overview ruler rendered under the vertical scrollbar or is that always missing on your machine?
