### ISSUE TITLE
VSCode on MacOS must be Force Quit if Terminal Confirm On Exit is enabled.

### ISSUE THREAD

**Issue by Firaenix** [microsoft/vscode#92997]
- VSCode Version:  1.43.1
- OS Version: MacOS Catalina

Steps to Reproduce:

1. Turn on "Terminal > Integrated > Confirm on Exit"
2. Open a VSCode window.
3. Open an Integrated Terminal
4. CMD+Q or Code > Quit Visual Studio Code from the Taskbar.
5. VSCode will still be open, but it will not close, you must Force Quit for it to actually exit.

Does this issue occur when all extensions are disabled?: Yes

Stack Trace from Developer Tools:
```
ERR A system error occurred (ESRCH, No such process): Error: ESRCH, No such process
    at t.enableInspectPort (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4125:706)
    at e.getInspectPort (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3869:612)
    at e.getInspectPort (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4228:850)
    at e._onDidChangeResponsiveChange (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4559:38)
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:101:994)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3743:821
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:101:974)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3868:288
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:101:974)
    at e._setResponsiveState (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3854:980)
    at e._checkUnresponsive (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3854:809)
    at g.runner (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3854:76)
    at g.doRun (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:137:756)
    at g.onTimeout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:137:722)
```

**Comment by Tyriar** [comment]
I think this is due to https://github.com/microsoft/vscode/issues/92881

/duplicate
