### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by mssngr** [microsoft/vscode#93285]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.7.3
**Steps to reproduce crash**
1. Have 4 tabs open with .tsx files
2. Work late into the night
3. Burn your pants with your flaming hot laptop
**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at ProjectService.applyChangesInOpenFiles (tsserver.js:138402:34)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139271:46)
    at tsserver.js:140929:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140920:28)
    at IOSession.Session.executeCommand (tsserver.js:140929:33)
    at IOSession.Session.onMessage (tsserver.js:140952:35)
    at Interface.<anonymous> (tsserver.js:142267:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.44.0-insider (0926b534553f3ff2f0cff0a741550a97df199706, 2020-03-23T08:11:36.196Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 4, 4|
|Memory (System)|16.00GB (3.62GB free)|
|Process Argv|-psn_0_536707|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.1.8
vscode-eslint|dba|2.1.1
prettier-vscode|esb|3.20.0
case-sensitive-add-next|jac|0.0.6
vscode-peacock|joh|3.6.0
vscode-styled-components|jpo|0.0.29
chat|kar|0.32.1
dotenv|mik|1.0.1
vsliveshare|ms-|1.0.1783
vsliveshare-audio|ms-|0.1.80
vsliveshare-pack|ms-|0.3.4
material-icon-theme|PKi|4.0.1
scala|sca|0.3.9
metals|sca|1.8.4
vscode-status-bar-format-toggle|tom|2.0.0

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Do you see this with TypeScript 3.8+?

**Comment by mssngr** [comment]
Nope, was 3.7.3. I had a _lot_ of TS tabs open throughout the night, coding. At this particular point, I only had 4 open. But, I was probably giving the compiler a run for its money. The crash happened a couple more times, but I only logged this one.

**Comment by mjbvz** [comment]
Please test using 3.8+ too because this bug may have already been fixed
