### ISSUE TITLE
Smoke: search tests show an error even though they succeed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93292]
On macOS:

```
 Search
** Timeout!
Error: Active element not found. Current active element is 'HTML > BODY.vs-dark.vscode-theme-defaults-themes-dark_plus-json.file-icons-enabled.mac'. Looking for .search-view .search-widget .search-container .monaco-inputbox textarea
    at WindowDriver.isActiveElement (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/driver/browser/baseDriver.js:63:23)
    at WindowDriverChannel.call (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/driver/node/driver.js:130:60)
    at ChannelServer.onPromise (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.js:203:35)
    at ChannelServer.onRawMessage (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.js:185:33)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.js:145:73
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:457:42)
    at EventEmitter.fn (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:257:44)
    at EventEmitter.emit (events.js:203:13)
    at Object.onMessage (electron/js2c/renderer_init.js:2399:16)
      ✓ searches for body & checks for correct result number
      ✓ searches only for *.js files & checks for correct result number
      ✓ dismisses result & checks for correct result number

```

**Comment by roblourens** [comment]
The previous test changes the sidebar position and resets settings at the end, but the settings reset takes a second to actually apply, and interferes with the first time the search test tries to focus the search viewlet, then it retries and continues. I changed the preferences test to wait for the sidebar to reset, which is slightly hacky but I think it's fine.
