### ISSUE TITLE
Consider using a different Razor grammar

### ISSUE THREAD

**Issue by mechanic22** [microsoft/vscode#93407]
Sorry in advance if this isn't where I am supposed to post this, but I did try some searching and couldn't find much and actually didn't know how to search, but anyway. I notice that inline syntax highlighting for cshtml seems to have an issue when using an inline C# chunk inside of an attribute of an html tag. 

For example, notice how the closing parentheses is red along with the double quotes.
![image](https://user-images.githubusercontent.com/26332509/77558312-c9e42080-6e88-11ea-8f5d-85354f41373c.png)

I am on version 1.43.2 of vscode in windows 10 x64, and my language mode is set to autodetect, which looks like it defaults to aspnetcorerazor, however i tried changing it to Razor and the same thing shows. 

It doesn't affect the actual build, it is just an annoyance when looking at it.

For reference, here is how it looks in Visual Studio Community 2019

![image](https://user-images.githubusercontent.com/26332509/77558943-935ad580-6e89-11ea-9ab4-003197e799b1.png)

Here is my vscode info:
Version: 1.43.2 (user setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by alexr00** [comment]
Can you please provide an example I can copy/paste? Does the issue still occur if you disable all extensions?

**Comment by mechanic22** [comment]
I tried it with all extensions disabled and here are the results
Here is a super simple example. Single file

```
@page

<a asp-page="Index" class="@(true ? "dark" : "false")">Hello</a>
```

And how it looks 
![image](https://user-images.githubusercontent.com/26332509/77680394-e0aa7600-6f61-11ea-9f49-a7d4e268fd2d.png)


The same file in Visual Studio Community 2019 for reference
![image](https://user-images.githubusercontent.com/26332509/77680490-046dbc00-6f62-11ea-9f61-44c57efc9ea6.png)

**Comment by alexr00** [comment]
We get our Razor grammar from https://github.com/demyte/language-cshtml
But it looks like that repository has been archived.
If you know of a better/maintained textmate razor grammar I can look into using that instead!

**Comment by mechanic22** [comment]
> We get our Razor grammar from https://github.com/demyte/language-cshtml
> But it looks like that repository has been archived.
> If you know of a better/maintained textmate razor grammar I can look into using that instead!

Sorry I don't work with grammars, nor know of where to even look for them. I just reported an issue that I noticed while doing basic web development using your EDI

**Comment by joakimriedel** [comment]
Experiencing the same issue when sending a string to a component as detailed in this issue: https://github.com/dotnet/aspnetcore/issues/19466

For example, I get this syntax highlighting issue due to sending strings to the partial tag helper:

![image](https://user-images.githubusercontent.com/429478/81834806-c5abb980-9541-11ea-8537-a3aae5784b77.png)

Same section in VS2019:

![image](https://user-images.githubusercontent.com/429478/81834912-eb38c300-9541-11ea-8fe6-970fd700774c.png)

Also get errors in Razor Output (set to Messages logging) when opening the same file that might or might not be related to this;

```
[Error - 16:08:41] Request textDocument/hover failed.
  Message: Internal Error - System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at Microsoft.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index)
   at Microsoft.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position)
   at Microsoft.AspNetCore.Razor.LanguageServer.Hover.RazorHoverEndpoint.Handle(HoverParams request, CancellationToken cancellationToken) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/RazorHoverEndpoint.cs:line 95
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(TDescriptor descriptor, Request request, CancellationToken token)
  Code: -32602 
[Error - 16:08:41] Failed to handle notification razor/languageQuery - System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at Microsoft.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index)
   at Microsoft.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position)
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorLanguageEndpoint.Handle(RazorLanguageQueryParams request, CancellationToken cancellationToken) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageEndpoint.cs:line 143
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(TDescriptor descriptor, Request request, CancellationToken token)
```

**Comment by miqm** [comment]
@alexr00 any update on this? is this going to be ever fixed?

**Comment by mikesigs** [comment]
I have similar problems with code highlighting. Here are a couple more examples:

Red seems to indicate a missing method, but the method exists. F12 even navigates to it.
![image](https://user-images.githubusercontent.com/811177/132957864-e95ac6ce-9d5b-4946-b50c-b8ea32d3490c.png)


Inline lambdas don't highlight properly either.
![image](https://user-images.githubusercontent.com/811177/132957880-e15e248a-9985-49fa-8941-f9a9dcd3ae83.png)


Please note, my code compiles and runs fine. It's just the highlighting showing false negatives.

**Comment by jpinto3488** [comment]
I have the same issue, anyone has found a workaround or extension to make this work properly?

**Comment by miqm** [comment]
Use visual studio :)

**Comment by alexr00** [comment]
Completed with https://github.com/microsoft/vscode/issues/163149.
