### ISSUE TITLE
Extensions smoketest failures

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93714]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=70747&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=05af1eac-c39c-5c75-1e3f-dd115ec8907d&l=100

```
1) VSCode Smoke Tests (Electron)
       Extensions
         install and activate vscode-smoketest-check extension:
     Error: Timeout: click 'div.extensions-viewlet[id="workbench.view.extensions"] .monaco-list-row[aria-label="vscode-smoketest-check. Press enter for extension details."] .extension li[class='action-item'] .extension-action.install' after 20 seconds.
      at /Users/runner/runners/2.165.2/work/1/s/test/automation/out/code.js:176:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/runners/2.165.2/work/1/s/test/automation/out/code.js:9:58)

  2) VSCode Smoke Tests (Electron)
       Localization
         "before all" hook for "starts with 'DE' locale and verifies title and viewlets text is in German":
     Error: Timeout: click 'div.extensions-viewlet[id="workbench.view.extensions"] .monaco-list-row[aria-label="German Language Pack for Visual Studio Code. Press enter for extension details."] .extension li[class='action-item'] .extension-action.install' after 20 seconds.
      at /Users/runner/runners/2.165.2/work/1/s/test/automation/out/code.js:176:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/runners/2.165.2/work/1/s/test/automation/out/code.js:9:58)

```

**Comment by sandy081** [comment]
Fixed by 13b38d2a494612ace32c4fb878824d6329d4c51e
