### ISSUE TITLE
Unable to Debug Through Remote SSH Tunnel

### ISSUE THREAD

**Issue by koskorya** [microsoft/vscode#94008]
- VSCode Version: 1.43.2
- OS Version: Mac Cataline 10.15.4 SSH=> Ubuntu 16.04.6 LTS

Steps to Reproduce:

1. Remote connect via SSH
2. Click `Run and Debug` for a `Python File` containing only a print statement
3. Receive pop-up error:
```Session[1] timed out waiting for <debugpy.adapter.components.missing.<locals>.Missing object at 0x7f530b61c978> to connect``` 

with a terminal error:
```
env DEBUGPY_LAUNCHER_PORT=34795 /nail/home/rkosko/venv/bin/python3 /nail/home/rkosko/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher /nail/home/rkosko/repos/shootie/app/test.py 
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nail/home/rkosko/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher/__main__.py", line 80, in <module>
    main()
  File "/nail/home/rkosko/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher/__main__.py", line 42, in main
    launcher.connect(launcher_port)
  File "/nail/home/rkosko/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/no_wheels/debugpy/launcher/../../debugpy/launcher/__init__.py", line 27, in connect
    sock.connect(("127.0.0.1", launcher_port))
ConnectionRefusedError: [Errno 111] Connection refused
``` 

I believe the debugger should be executing `/nail/home/rkosko/.vscode-server/extensions/ms-python.python-2020.3.69010/pythonFiles/ptvsd_launcher.py` instead of the `debugpy` file.

Does this issue occur when all extensions are disabled?: Yes

**Comment by koskorya** [comment]
good bot ^
