### ISSUE TITLE
Can't install any extension

### ISSUE THREAD

**Issue by brian952** [microsoft/vscode#94205]
Issue Type: <b>Bug</b>

Hello,

I am having trouble to install extension directly through vscode. It said "Failed to install'xxxxxx' "

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:34:57.037Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (1.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by brian952** [comment]
> Please follow these steps
> 
> * Help -> Toggle Developer Tools -> Network
> * Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
> * To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
> * If it is not a network issue, please share the logs from the following locations
>   
>   * Help -> Toggle Developer Tools -> Console
>   * View -> Command Pallette... -> Toggle Shared Process -> Console
>   * View -> Open View… -> Log (Shared)
>   * View -> Open View… -> Log (Window)

Hello,

I had tried the steps you advised, but it did not work for me. 
<img width="799" alt="Screen Shot 2020-04-02 at 2 11 36 PM" src="https://user-images.githubusercontent.com/46903521/78275673-79a23980-74ec-11ea-8d46-1330521659d4.png">
<img width="799" alt="Screen Shot 2020-04-02 at 2 06 49 PM" src="https://user-images.githubusercontent.com/46903521/78275692-80c94780-74ec-11ea-941a-df774f8b82c3.png">

**Comment by brian952** [comment]
> Please follow these steps
> 
> * Help -> Toggle Developer Tools -> Network
> * Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
> * To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
> * If it is not a network issue, please share the logs from the following locations
>   
>   * Help -> Toggle Developer Tools -> Console
>   * View -> Command Pallette... -> Toggle Shared Process -> Console
>   * View -> Open View… -> Log (Shared)
>   * View -> Open View… -> Log (Window)

[2020-04-01 16:33:19.481] [sharedprocess] [info] main {"machineId":"6c9d2bc8f91b89624add29c0abeae7fb42bf539fa1cdb2e3e57cd668fa9bcead","windowId":2}
[2020-04-01 16:33:59.493] [sharedprocess] [info] Starting to clean up unused language packs.
[2020-04-01 17:05:36.511] [sharedprocess] [info] Installing extension: ms-ceintl.vscode-language-pack-zh-hans
[2020-04-01 17:05:36.514] [sharedprocess] [error] Failed to install extension: ms-ceintl.vscode-language-pack-zh-hans EACCES: permission denied, open '/Users/brianwen/.vscode/extensions/.obsolete'
[2020-04-02 14:04:17.542] [sharedprocess] [info] Installing extension: ms-ceintl.vscode-language-pack-zh-hans
[2020-04-02 14:04:17.545] [sharedprocess] [error] Failed to install extension: ms-ceintl.vscode-language-pack-zh-hans EACCES: permission denied, open '/Users/brianwen/.vscode/extensions/.obsolete'
[2020-04-02 14:04:43.179] [sharedprocess] [info] Installing extension: ms-ceintl.vscode-language-pack-zh-hans
[2020-04-02 14:04:43.181] [sharedprocess] [error] Failed to install extension: ms-ceintl.vscode-language-pack-zh-hans EACCES: permission denied, open '/Users/brianwen/.vscode/extensions/.obsolete'
[2020-04-02 14:06:34.736] [sharedprocess] [info] Installing extension: vscjava.vscode-maven
[2020-04-02 14:06:34.739] [sharedprocess] [error] Failed to install extension: vscjava.vscode-maven EACCES: permission denied, open '/Users/brianwen/.vscode/extensions/.obsolete'
[2020-04-02 14:06:43.807] [sharedprocess] [info] Installing extension: vscjava.vscode-maven
[2020-04-02 14:06:43.811] [sharedprocess] [error] Failed to install extension: vscjava.vscode-maven EACCES: permission denied, open '/Users/brianwen/.vscode/extensions/.obsolete'

**Comment by brian952** [comment]
[2020-04-01 16:33:16.939] [renderer1] [error] [storage state.vscdb] exec(): Error: SQLITE_READONLY: attempt to write a readonly database
[2020-04-01 16:33:16.949] [renderer1] [error] [storage state.vscdb] open(): Unable to open DB due to Error: SQLITE_READONLY: attempt to write a readonly database
[2020-04-01 16:33:16.957] [renderer1] [error] [storage state.vscdb] open(): Unable to use backup due to Error: EACCES: permission denied, unlink '/Users/brianwen/Library/Application Support/Code/User/workspaceStorage/1583607088306/state.vscdb'
[2020-04-01 16:33:19.605] [renderer1] [error] EACCES: permission denied, open '/Users/brianwen/.vscode/extensions/.obsolete': Error: EACCES: permission denied, open '/Users/brianwen/.vscode/extensions/.obsolete'
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:482:761
    at async Promise.all (index 1)
[2020-04-01 16:33:39.760] [renderer1] [error] Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f'): Error: Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f')
    at _.writeFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1665:572)
[2020-04-01 16:33:42.544] [renderer1] [error] Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f'): Error: Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f')
    at _.writeFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1665:572)
[2020-04-01 16:33:44.361] [renderer1] [error] Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f'): Error: Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f')
    at _.writeFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1665:572)
[2020-04-01 16:44:11.847] [renderer1] [error] Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f'): Error: Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f')
    at _.writeFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1665:572)
[2020-04-01 16:44:14.093] [renderer1] [error] Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f'): Error: Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f')
    at _.writeFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1665:572)
[2020-04-01 16:44:15.538] [renderer1] [error] Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f'): Error: Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f')
    at _.writeFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1665:572)
[2020-04-01 16:44:18.224] [renderer1] [error] Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f'): Error: Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f')
    at _.writeFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1665:572)
[2020-04-01 16:44:20.206] [renderer1] [error] Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f'): Error: Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f')
    at _.writeFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1665:572)
[2020-04-01 16:44:22.151] [renderer1] [error] Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f'): Error: Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f')
    at _.writeFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1665:572)
[2020-04-01 16:44:26.033] [renderer1] [error] Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f'): Error: Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f')
    at _.writeFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1665:572)
[2020-04-01 16:44:28.733] [renderer1] [error] Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f'): Error: Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f')
    at _.writeFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1665:572)
[2020-04-01 16:44:31.031] [renderer1] [error] Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f'): Error: Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f')
    at _.writeFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1665:572)
[2020-04-01 16:44:33.529] [renderer1] [error] Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f'): Error: Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f')
    at _.writeFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1665:572)
[2020-04-01 16:45:37.813] [renderer1] [error] Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f'): Error: Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f')
    at _.writeFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1665:572)
[2020-04-01 16:47:48.006] [renderer1] [error] Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f'): Error: Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f')
    at _.writeFile (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1665:572)
[2020-04-01 17:05:36.548] [renderer1] [error] EACCES: permission denied, open '/Users/brianwen/.vscode/extensions/.obsolete': scanningUser: EACCES: permission denied, open '/Users/brianwen/.vscode/extensions/.obsolete'
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:482:761
    at async Promise.all (index 0)
    at async j.installFromGallery (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:471:260)
[2020-04-02 14:04:17.577] [renderer1] [error] EACCES: permission denied, open '/Users/brianwen/.vscode/extensions/.obsolete': scanningUser: EACCES: permission denied, open '/Users/brianwen/.vscode/extensions/.obsolete'
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:482:761
    at async Promise.all (index 0)
    at async j.installFromGallery (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:471:260)
[2020-04-02 14:04:30.875] [renderer1] [error] No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
[2020-04-02 14:04:43.259] [renderer1] [error] EACCES: permission denied, open '/Users/brianwen/.vscode/extensions/.obsolete': scanningUser: EACCES: permission denied, open '/Users/brianwen/.vscode/extensions/.obsolete'
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:482:761
    at async Promise.all (index 0)
    at async j.installFromGallery (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:471:260)
[2020-04-02 14:06:34.792] [renderer1] [error] EACCES: permission denied, open '/Users/brianwen/.vscode/extensions/.obsolete': scanningUser: EACCES: permission denied, open '/Users/brianwen/.vscode/extensions/.obsolete'
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:482:761
    at async Promise.all (index 0)
    at async j.installFromGallery (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:471:260)
[2020-04-02 14:06:40.596] [renderer1] [error] [backup tracker] One or many editors that are dirty could not be saved to the backup location.: Error: Unable to write file 'vscode-userdata:/Users/brianwen/Library/Application Support/Code/User/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f' (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Users/brianwen/Library/Application Support/Code/Backups/1583607088306/file/51efc27cc331227e33c1a3ae13d7607f')
[2020-04-02 14:06:43.870] [renderer1] [error] EACCES: permission denied, open '/Users/brianwen/.vscode/extensions/.obsolete': scanningUser: EACCES: permission denied, open '/Users/brianwen/.vscode/extensions/.obsolete'
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:482:761
    at async Promise.all (index 0)
    at async j.installFromGallery (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:471:260)
[2020-04-02 14:07:26.715] [renderer1] [error] No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
[2020-04-02 14:13:18.466] [renderer1] [error] No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.

**Comment by sandy081** [comment]
It seems you do not have permissions to `.vscode` folder where extensions are installed. Please fix the permissions to get this fixed.

**Comment by brian952** [comment]
> It seems you do not have permissions to `.vscode` folder where extensions are installed. Please fix the permissions to get this fixed.

Thank you. Works perfectly now!
