### ISSUE TITLE
Cannot read property 'setEnableSplitViewResizing' of undefined.

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#94271]
1. Running out of source with latest. Did the whole `yarn watch` dance
2. Open a file, click on open diff view

Get the following error notification

```
Unable to open 'users.js (Working Tree)': Cannot read property 'setEnableSplitViewResizing' of undefined.
```

In the developer console there is a whole stack trace.
The split view crashes and everything is broken.
This will probably not reproduce on your machine, but I hope the stack trace and the errors will shed some light on this.

```
 ERR Assertion Failed: argument is undefined or null: Error: Assertion Failed: argument is undefined or null
    at Object.assertIsDefined (file:///Users/isidor/Development/vscode/out/vs/base/common/types.js:105:19)
    at TextDiffEditor.layout (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/textEditor.js:146:47)
    at EditorControl.layout (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:178:44)
    at EditorGroupView.layout (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:1205:36)
    at LeafNode.layout (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/grid/gridview.js:495:23)
    at VerticalViewItem.layout (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/splitview/splitview.js:76:23)
    at SplitView.layoutViews (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/splitview/splitview.js:628:26)
    at SplitView.relayout (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/splitview/splitview.js:535:18)
    at SplitView.onViewChange (file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/splitview/splitview.js:404:22)
    at file:///Users/isidor/Development/vscode/out/vs/base/browser/ui/splitview/splitview.js:462:70
    at file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:67:138
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:457:42)
    at file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:44:93
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:457:42)
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:460:45)
    at EditorControl.doSetActiveEditorPane (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:109:50)
    at EditorControl.doShowEditorPane (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:63:22)
    at EditorControl.openEditor (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:48:41)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:667:69
    at EditorGroupView.doShowEditor (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:679:23)
    at EditorGroupView.doOpenEditor (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:651:47)
    at EditorGroupView.openEditor (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:592:63)
    at EditorService.openEditor (file:///Users/isidor/Development/vscode/out/vs/workbench/services/editor/browser/editorService.js:386:76)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/api/browser/mainThreadEditors.js:253:30
    at InstantiationService.invokeFunction (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:43:24)
    at CommandService._tryExecuteCommand (file:///Users/isidor/Development/vscode/out/vs/workbench/services/commands/common/commandService.js:75:63)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/services/commands/common/commandService.js:65:51
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by isidorn** [comment]
This was caused by my local change to set diff editor to be readonly. However this might have uncovered an issue in the layouting, thus leaving this open.

If you want to repro add the following line [here](https://github.com/microsoft/vscode/blob/56df825f8412d48e1eb45d4c164e7483563593c8/src/vs/editor/browser/widget/diffReview.ts#L114)
`this._diffEditor.updateOptions({ readOnly: true });`

**Comment by sbatten** [comment]
@isidorn I don't much about this code, but this broke because of the order of the following lines.

https://github.com/microsoft/vscode/blob/92f642718dcce41b0c808552080a22c8bf0e4f4c/src/vs/editor/browser/widget/diffEditorWidget.ts#L358-L375

Note that your `updateOptions` call happens inside the contructor called on the first line 358. UpdateOptions requires that the strategy already be set on the `DiffEditorWidget` that is passed into the constructor which doesn't happen until line 371 in the snippet seen above.

**Comment by isidorn** [comment]
Ok, thanks @sbatten for looking into it.
However I thought this uncovers a flow in the grid view. If all is good, there is nothing to fix in the diffEditorWidget since I did not end up pushing that code thus closing
