### ISSUE TITLE
Visual Studio Code - HTML language server crash 

### ISSUE THREAD

**Issue by sdombora** [microsoft/vscode#94301]
- VSCode Version: 1.43.2.
- OS Version: Ubuntu 20.04, 18.04

HTML language server errors

[Info  - 7:58:46] Connection to server got closed. Server will restart.
[Error - 7:58:48] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:71723)
	at Object.dispose (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:54997)
	at t.LanguageClient.handleConnectionClosed (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:55172)
	at t.LanguageClient.handleConnectionClosed (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:125015)
	at t (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:53321)
	at r.invoke (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:83262)
	at i.fire (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:83994)
	at V (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:63656)
	at r.invoke (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:83262)
	at i.fire (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:83994)
	at t.IPCMessageReader.fireClose (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:86182)
	at ChildProcess.<anonymous> (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:88163)
	at ChildProcess.emit (events.js:208:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 7:58:48] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:71723)
	at Object.dispose (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:54997)
	at t.LanguageClient.handleConnectionClosed (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:55172)
	at t.LanguageClient.handleConnectionClosed (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:125015)
	at t (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:53321)
	at r.invoke (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:83262)
	at i.fire (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:83994)
	at V (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:63656)
	at r.invoke (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:83262)
	at i.fire (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:83994)
	at t.IPCMessageReader.fireClose (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:86182)
	at ChildProcess.<anonymous> (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:88163)
	at ChildProcess.emit (events.js:208:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 7:58:48] Request textDocument/documentHighlight failed.
Error: Connection got disposed.
	at Object.dispose (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:71723)
	at Object.dispose (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:54997)
	at t.LanguageClient.handleConnectionClosed (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:55172)
	at t.LanguageClient.handleConnectionClosed (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:125015)
	at t (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:53321)
	at r.invoke (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:83262)
	at i.fire (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:83994)
	at V (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:63656)
	at r.invoke (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:83262)
	at i.fire (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:83994)
	at t.IPCMessageReader.fireClose (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:86182)
	at ChildProcess.<anonymous> (/snap/code/28/usr/share/code/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:88163)
	at ChildProcess.emit (events.js:208:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)

Steps to Reproduce:

1. Install ubuntu desktop without any customizattion
2. Install Visual Studio Code
3. Load any  html file  with 50-60 lines containing about 10  lines script tag for javascript  
4. define 2-3 javascript variables with value from the DOM structure. 
5. add new table line tag with two chidren (ech defined with createElement
6. add the new row to a table in the document.

Tried several times, same result Complete crash of the os, both on ubuuntu 18.04 and 20.04 (this was a trial after the 18.04 version did not work).

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Can you paste the example here?
