### ISSUE TITLE
Issues while setup vscode source code cloned from github

### ISSUE THREAD

**Issue by bhavyasf** [microsoft/vscode#94443]
- VSCode Version: 1.43.2
- OS Version: Linux Mint 19.3

Steps to Reproduce:

1.clone vs code from github
2.do yarn install
Some errors came and i fixed it but after resolving each error one by one, i am now stuck in this.
```yarn install v1.22.4
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.1: The platform "linux" is incompatible with this module.
info "fsevents@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info vscode-windows-ca-certs@0.2.0: The platform "linux" is incompatible with this module.
info "vscode-windows-ca-certs@0.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info vscode-windows-registry@1.0.2: The platform "linux" is incompatible with this module.
info "vscode-windows-registry@1.0.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-foreground-love@0.2.0: The platform "linux" is incompatible with this module.
info "windows-foreground-love@0.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-mutex@0.3.0: The platform "linux" is incompatible with this module.
info "windows-mutex@0.3.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-process-tree@0.2.4: The platform "linux" is incompatible with this module.
info "windows-process-tree@0.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/14] ⠐ keytar
[2/14] ⠐ native-is-elevated
[3/14] ⠐ native-keymap
[4/14] ⠐ native-watchdog
error /home/bhavya/Documents/vscode/node_modules/native-keymap: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/bhavya/Documents/vscode/node_modules/native-keymap
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@12.16.1 | linux | x64
gyp info find Python using Python version 2.7.17 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/home/bhavya/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/bhavya/Documents/vscode/node_modules/native-keymap/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/bhavya/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/bhavya/.cache/node-gyp/7.1.11/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/bhavya/.cache/node-gyp/7.1.11',
gyp info spawn args   '-Dnode_gyp_dir=/home/bhavya/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/bhavya/.cache/node-gyp/7.1.11/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/bhavya/Documents/vscode/node_modules/native-keymap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
Package xkbfile was not found in the pkg-config search path.
Perhaps you should add the directory containing `xkbfile.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xkbfile' found
gyp: Call to '${PKG_CONFIG:-pkg-config} x11 xkbfile --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/bhavya/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12
gyp ERR! System Linux 5.3.0-45-generic
gyp ERR! command "/home/bhavya/.nvm/versions/node/v12.16.1/bin/node" "/home/bhavya/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/bhavya/Documents/vscode/node_modules/native-keymap```


<!-- Launch with `code --disable-extensions` to check. -->
Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Please go through our guide: https://github.com/microsoft/vscode/wiki/How-to-Contribute

Namely, the error clearly states:

```
No package 'x11' found
No package 'xkbfile' found
```

You're missing `libx11-dev` and `libxkbfile-dev`.
