### ISSUE TITLE
Cannot connect to the Extentions Marketplace.

### ISSUE THREAD

**Issue by gima1997** [microsoft/vscode#94484]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

When i want to get extentions.But all the time it dislplay as "We cannot connect to the Extensions Marketplace at this time,Please try again later"

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
html-class-suggestions|And|1.0.7
phpserver|bra|2.4.6
quick-html-previewer|dai|1.0.1
live-html-previewer|hdg|0.3.0
vscode-phpfmt|kok|1.0.30
vscode-html-format|moh|0.0.4
format-html-in-php|rif|1.6.2
LiveServer|rit|5.6.1
json-script-tag|sis|0.2.2
html-preview-vscode|tht|0.2.5
html-validate-vscode|Tob|0.2.0
html-snippets|wge|0.1.5

</details>

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by markusylisiurunen** [comment]
I have the same problem when trying to install an extension. I've attached parts of the requested logs below.

From View -> Open View... -> Log (Window)

```
[2020-04-06 14:03:19.796] [renderer5] [error] connect ECONNREFUSED /Users/markusylisiurunen/Library/Application Support/Code/1.43.2-shared.sock: Unknown (UserDataSyncError) undefined: connect ECONNREFUSED /Users/markusylisiurunen/Library/Application Support/Code/1.43.2-shared.sock
    at Function.toUserDataSyncError (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2607:524)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5080:337
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-04-06 14:03:19.796] [renderer5] [error] connect ECONNREFUSED /Users/markusylisiurunen/Library/Application Support/Code/1.43.2-shared.sock: Error: connect ECONNREFUSED /Users/markusylisiurunen/Library/Application Support/Code/1.43.2-shared.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
[2020-04-06 14:03:22.117] [renderer5] [error] Error: connect ECONNREFUSED /Users/markusylisiurunen/Library/Application Support/Code/1.43.2-shared.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
[2020-04-06 14:03:22.118] [renderer5] [error] connect ECONNREFUSED /Users/markusylisiurunen/Library/Application Support/Code/1.43.2-shared.sock: Error: connect ECONNREFUSED /Users/markusylisiurunen/Library/Application Support/Code/1.43.2-shared.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
[2020-04-06 14:06:35.518] [renderer5] [error] connect ECONNREFUSED /Users/markusylisiurunen/Library/Application Support/Code/1.43.2-shared.sock: Error: connect ECONNREFUSED /Users/markusylisiurunen/Library/Application Support/Code/1.43.2-shared.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
[2020-04-06 14:06:35.519] [renderer5] [error] connect ECONNREFUSED /Users/markusylisiurunen/Library/Application Support/Code/1.43.2-shared.sock: Unknown (UserDataSyncError) undefined: connect ECONNREFUSED /Users/markusylisiurunen/Library/Application Support/Code/1.43.2-shared.sock
    at Function.toUserDataSyncError (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2607:524)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5080:337
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-04-06 14:06:35.520] [renderer5] [error] connect ECONNREFUSED /Users/markusylisiurunen/Library/Application Support/Code/1.43.2-shared.sock: Error: connect ECONNREFUSED /Users/markusylisiurunen/Library/Application Support/Code/1.43.2-shared.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
[2020-04-06 14:06:37.893] [renderer5] [error] Error: connect ECONNREFUSED /Users/markusylisiurunen/Library/Application Support/Code/1.43.2-shared.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
[2020-04-06 14:06:37.896] [renderer5] [error] connect ECONNREFUSED /Users/markusylisiurunen/Library/Application Support/Code/1.43.2-shared.sock: Error: connect ECONNREFUSED /Users/markusylisiurunen/Library/Application Support/Code/1.43.2-shared.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
```

From Developer Tools Console:

<img width="859" alt="Screenshot 2020-04-06 at 14 04 19" src="https://user-images.githubusercontent.com/8409947/78552520-52ab7680-7810-11ea-9c62-6b5c3a13976f.png">

Neither View -> Open View… -> Log (Shared) or View -> Command Pallette... -> Toggle Shared Process -> Console showed any errors. Same for network requests, everything seemed to come back as 200 (however, I think the marketplace requests never were sent out).

**Comment by sandy081** [comment]
Seems like you have network issues. Did you try all steps mentioned above?

**Comment by markusylisiurunen** [comment]
Yes, no issues with any of those or with any other program/browser.

**Comment by sandy081** [comment]
Do you have any proxy set ups?

**Comment by gima1997** [comment]
Sir,
" please share the logs from the following locations ".According to your
comment, What are the logs that you mentioned?

**Comment by sandy081** [comment]
Please go through the comment.. its clearly mentioned there

**Comment by markusylisiurunen** [comment]
@sandy081 I don't have any vpn/proxy set up. Do you have a specific API endpoint I could try to query outside of VS Code to verify that my machine is able to connect to that?

**Comment by sandy081** [comment]
https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

**Comment by markusylisiurunen** [comment]
I tried that already based on your previous message, it works just fine.

**Comment by sandy081** [comment]
Ah hold on.. you have socket issues connecting to shared process. Please restart your machine once and try?

**Comment by gima1997** [comment]
when i go through ,
View -> Command Pallette... -> Toggle Shared Process -> Console
![console](https://user-images.githubusercontent.com/45139663/78580617-47783b00-7850-11ea-9dcf-ac07034e2b8e.jpg)

Help -> Toggle Developer Tools -> Console
![toggle developer](https://user-images.githubusercontent.com/45139663/78580855-aa69d200-7850-11ea-8270-0768136b84db.jpg)

View -> Open View… -> Log (Shared)
![logShared](https://user-images.githubusercontent.com/45139663/78581128-151b0d80-7851-11ea-8a76-e48c1ca4097b.jpg)

View -> Open View… -> Log (Window)
![logWindow](https://user-images.githubusercontent.com/45139663/78581188-2c59fb00-7851-11ea-8d61-2f46622e6d89.jpg)

**Comment by sandy081** [comment]
@gima1997 It seems you have network connection issues - `ERR_TUNNEL_CONNECTION_FAILED`.

Could be you are behind a proxy server. Please refer to this link https://code.visualstudio.com/docs/setup/network for help.
