### ISSUE TITLE
TS Server fatal error:  Cannot read property 'languageServiceRefCount' of undefined

### ISSUE THREAD

**Issue by Mossop** [microsoft/vscode#94498]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
Unknown, just popped up while I was looking over a file.
**TS Server Error Stack**
```
TypeError: Cannot read property 'languageServiceRefCount' of undefined
    at releaseDocumentWithKey (tsserver.js:112241:13)
    at Object.releaseDocument (tsserver.js:112236:20)
    at tsserver.js:135319:45
    at Object.forEach (tsserver.js:167:30)
    at Proxy.dispose (tsserver.js:135318:20)
    at InferredProject.Project.close (tsserver.js:139542:38)
    at InferredProject.close (tsserver.js:140420:40)
    at ProjectService.removeProject (tsserver.js:141660:25)
    at ProjectService.cleanupAfterOpeningFile (tsserver.js:143206:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143404:26)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.44.0-insider (e8dbc5ea6092ba73ae70069d3e730f2cc56addff, 2020-04-03T22:09:44.908Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (9.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-zonefile|Com|0.0.4
vscode-eslint|dba|2.1.2
chmod|dle|1.1.1
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|4.0.0
vscode-firefox-debug|fir|2.7.1
backticks|fra|1.6.0
mozillacpp|fra|0.2.0
vscode-sshfs|Kel|1.17.0
vscode-webidl|keq|0.0.1
hg|Kri|1.3.1
restructuredtext|lex|123.0.0
code-coverage|mar|1.2.0
rust-analyzer|mat|0.2.108
python|ms-|2020.3.71659
remote-ssh-edit-nightly|ms-|2020.4.3780
remote-ssh-nightly|ms-|2020.4.3780
cpptools|ms-|0.27.0
vscode-typescript-tslint-plugin|ms-|1.2.3
idl|myt|0.3.1
autotrim|Nat|1.0.6
vscode-jest|Ort|3.1.1
material-icon-theme|PKi|4.0.1
vscode-hexdump|sle|1.7.2
vscode-lldb|vad|1.5.0

(1 theme extensions excluded)

</details>

**Comment by Mossop** [comment]
Looks like microsoft/TypeScript#37500
