### ISSUE TITLE
RangeError: byte length of Uint32Array should be a multiple of 4

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#94521]
```
ERR byte length of Uint32Array should be a multiple of 4: RangeError: byte length of Uint32Array should be a multiple of 4
    at new Uint32Array (<anonymous>)
    at fromLittleEndianBuffer (file:///Users/jrieken/Code/vscode/out/vs/workbench/api/common/shared/semanticTokensDto.js:42:20)
    at Object.decodeSemanticTokensDto (file:///Users/jrieken/Code/vscode/out/vs/workbench/api/common/shared/semanticTokensDto.js:105:21)
    at MainThreadDocumentSemanticTokensProvider.provideDocumentSemanticTokens (file:///Users/jrieken/Code/vscode/out/vs/workbench/api/browser/mainThreadLanguageFeatures.js:613:45)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

This was spotted by @jrieken when working. There are no steps to reproduce because this has to do with how a specific part of an extension host message (the semantic tokens dto) aligns on bytes in the underlying nodejs stream.

I can reproduce through unit testing.

This can lead to semantic tokens becoming stale and not updating.

**Comment by alexdima** [comment]
The fix is now in `master` and also in `release/1.44`

**Comment by alexdima** [comment]
There is a unit test for this case and there are no steps to verify => giving `verified` label.
