### ISSUE TITLE
arch yarn request failed install error

### ISSUE THREAD

**Issue by mytalala** [microsoft/vscode#94550]
- 1.38.0.r9916.g8918d05cb5-1;
- 5.4.23-1-MANJARO;

Steps to Reproduce:

1. Type ```pamac install code-git```

Error:

```
Trace: 
  Error: https://registry.yarnpkg.com/applicationinsights/-/applicationinsights-1.0.8.tgz: Request failed "0 undefined"
      at ResponseError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:696:66)
      at new ResponseError (/usr/lib/node_modules/yarn/lib/cli.js:802:124)
      at Request.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:67057:16)
      at Request.emit (events.js:198:13)
      at Request.module.exports.Request.onRequestResponse (/usr/lib/node_modules/yarn/lib/cli.js:141625:10)
      at ClientRequest.emit (events.js:203:15)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
      at TLSSocket.socketOnData (_http_client.js:451:20)
      at TLSSocket.emit (events.js:198:13)
```

Pamac log:

```
yarn install v1.22.4
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/diagnostic-channel-publishers/-/diagnostic-channel-publishers-0.2.1.tgz: Request failed \"0 undefined\"".
info If you think this is a bug, please open a bug report with the information provided in "/var/tmp/pamac-build-ir/code-git/src/vscode/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mytalala** [comment]
i don't know which package required
but installing blender saved me

pls add required dependency

**Comment by RMacfarlane** [comment]
We do not maintain this arch linux package. Perhaps you could comment here https://aur.archlinux.org/packages/code-git/

Since this seems to be building from source, the list of dependencies is here: https://github.com/Microsoft/vscode/wiki/How-to-Contribute#prerequisites
