### ISSUE TITLE
VSCode Smoke Tests: changes 'workbench.action.toggleSidebarPosition' command key binding and verifies it

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#94665]
```
1) VSCode Smoke Tests (Electron)
       Preferences
         changes 'workbench.action.toggleSidebarPosition' command key binding and verifies it:
     Error: Timeout: get element '.keybindings-list-container div[aria-label="Keybinding is Control+U."]' after 20 seconds.
      at /Users/bpasero/Development/Microsoft/monaco/test/automation/out/code.js:174:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/bpasero/Development/Microsoft/monaco/test/automation/out/code.js:9:58)
```

I did some recent changes around quick open, please let me know if this is nothing you broke recently.

**Comment by sandy081** [comment]
I think this is because of the aria label changes I did recently
