### ISSUE TITLE
TS Server fatal error:  Debug Failure. Expected 3 === 4. Registered script kind should match new script kind. /users/andreasolsson/code/cplan/cdab.cplan/untitled:^untitled-3

### ISSUE THREAD

**Issue by nonameolsson** [microsoft/vscode#94759]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.7.2
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. Expected 3 === 4. Registered script kind should match new script kind. /users/andreasolsson/code/cplan/cdab.cplan/untitled:^untitled-3
    at Object.assertEqual (tsserver.js:1970:17)
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (tsserver.js:130673:34)
    at tryReuseStructureFromOldProgram (tsserver.js:95339:28)
    at Object.createProgram (tsserver.js:94926:30)
    at synchronizeHostData (tsserver.js:130596:26)
    at Proxy.getProgram (tsserver.js:130688:13)
    at InferredProject.Project.updateGraphWorker (tsserver.js:135039:53)
    at InferredProject.Project.updateGraph (tsserver.js:134982:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (tsserver.js:136778:25)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:138156:26)
    at tsserver.js:138358:107
    at Object.mapDefined (tsserver.js:565:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:138358:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139212:46)
    at tsserver.js:140870:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140861:28)
    at IOSession.Session.executeCommand (tsserver.js:140870:33)
    at IOSession.Session.onMessage (tsserver.js:140893:35)
    at Interface.<anonymous> (tsserver.js:142208:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.44.0-insider (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T21:42:32.364Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (79)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
commit-message-editor|ada|0.12.2
codesnap|adp|1.0.27
Bookmarks|ale|11.0.0
another-project-manager|ale|0.0.1
vscode-color|ans|0.4.5
i18n-ally|ant|1.15.2
aesop|asy|0.1.2
git-temporal-vscode|bee|1.0.0
commit-reminder|Bit|0.0.2
coddx-alpha|cod|0.2.28
codestream|Cod|7.0.0
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.0.29
vscode-markdownlint|Dav|0.34.0
vscode-eslint|dba|2.1.2
githistory|don|0.6.3
es7-react-js-snippets|dsz|2.7.1
git-cheatsheet|dzh|1.1.1
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|4.1.1
vscode-todo-plus|fab|4.16.0
file-icons|fil|1.0.23
auto-rename-tag|for|0.1.1
docker-explorer|for|0.1.7
todo-tree|Gru|0.0.171
rest-client|hum|0.23.2
search-node-modules|jas|1.3.0
vscode-icontheme-js-nomo|jay|0.0.3
docthis|joe|0.7.1
bracket-peek|jom|1.2.0
vscode-styled-components|jpo|0.0.29
theme-karyfoundation-themes|kar|20.0.3
vscode-go-to-mdn|kby|1.1.1
git-graph|mhu|1.22.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.15
azure-pipelines|ms-|1.165.1
vscode-docker|ms-|1.0.0
csharp|ms-|1.21.16
network-edge-devtools|ms-|1.0.0
vscode-edge-devtools|ms-|1.0.7
mssql|ms-|1.9.0
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.9
js-debug-companion|ms-|0.0.4
node-debug2|ms-|1.42.1
references-view|ms-|0.0.50
vsliveshare|ms-|1.0.1947
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
vscode-react-native|msj|0.14.2
color-highlight|nau|2.3.0
vscode-jest|Ort|3.1.1
vsnotes|pat|0.7.1
vscode-versionlens|pfl|0.25.0
material-icon-theme|PKi|4.0.1
vscode-fileutils|sle|3.0.1
code-spell-checker|str|1.8.0
code-spell-checker-swedish|str|0.1.3
ayu|tea|0.18.0
git-rebase-shortcuts|tre|1.0.5
errorlens|use|3.1.0
highlight-matching-tag|vin|0.9.6
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.0.0
quokka-vscode|Wal|1.0.285
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.7.0
material-theme|zhu|3.2.5
vscode-open-in-github|ziy|1.3.6
vscode-proto3|zxh|0.4.2

(37 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Do you see this with TS 3.8+?

**Comment by nonameolsson** [comment]
@mjbvz This ocurred with TypeScript `3.7.2`. This isn't the first time I've gotten the problem. It has happened at least 10 times, before I submitted this issue.

**Comment by mjbvz** [comment]
Do you see this with TS 3.8+? The bug was likely already fixed in newer TS versions...

**Comment by nonameolsson** [comment]
I haven't used TS 3.8+ yet, so no, I haven't seen it with that version :)

**Comment by mjbvz** [comment]
Please test with the version
