### ISSUE TITLE
Cannot run global search, cannot open files from command pallet, cannot run default build task...

### ISSUE THREAD

**Issue by fenomchris** [microsoft/vscode#94924]
- VSCode Version: 1.44.0
- OS Version: macOS 10.15.4

Steps to Reproduce:

1. Open workspace
2. Try and search

Does this issue occur when all extensions are disabled?: Yes

Logs:
`[2020-04-10 11:40:29.780] [renderer3] [error] ENOPRO: No file system provider found for resource 'ccfs://current-sandbox/'
    at e.withProvider (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1629:872)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async e.doWatch (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1640:941)
[2020-04-10 11:40:29.805] [renderer3] [error] No file system provider found for resource 'ccfs://current-sandbox/.vscode': ENOPRO: No file system provider found for resource 'ccfs://current-sandbox/.vscode'
    at e.withProvider (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1629:872)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async exists (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1632:292)
    at async Promise.all (index 0)
[2020-04-10 11:40:32.311] [renderer3] [error] No file system provider found for resource 'ccfs://current-sandbox/.git/config': ENOPRO: No file system provider found for resource 'ccfs://current-sandbox/.git/config'
    at e.withProvider (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1629:872)
    at async exists (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1632:292)
    at async Promise.all (index 0)
[2020-04-10 11:40:32.322] [renderer3] [error] No file system provider found for resource 'ccfs://current-sandbox/pom.xml': ENOPRO: No file system provider found for resource 'ccfs://current-sandbox/pom.xml'
    at e.withProvider (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1629:872)
    at async exists (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1632:292)
    at async Promise.all (index 0)
[2020-04-10 11:40:34.546] [renderer3] [error] issue not found c-1
`

**Comment by SqrTT** [comment]
+1
> /usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4376 No search provider registered for scheme: ccfs, 

workspace contains file System `ccfs`, provider for it implemented in extension https://marketplace.visualstudio.com/items?itemName=SqrTT.prophet.
I as author of the extension can't implement search provider since it's only in proposed API

**Comment by fenomchris** [comment]
Issue is in prophet plugin, closing this ticket

**Comment by SqrTT** [comment]
this is not issue with plugin itself

**Comment by SqrTT** [comment]
filed new issue #94928
