### ISSUE TITLE
TS Server fatal error:  Cannot read property 'languageServiceRefCount' of undefined

### ISSUE THREAD

**Issue by bugaro** [microsoft/vscode#95053]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1. Open tsx file
**TS Server Error Stack**
```
TypeError: Cannot read property 'languageServiceRefCount' of undefined
    at releaseDocumentWithKey (tsserver.js:112241:13)
    at Object.releaseDocument (tsserver.js:112236:20)
    at tsserver.js:135319:45
    at Object.forEach (tsserver.js:167:30)
    at Proxy.dispose (tsserver.js:135318:20)
    at InferredProject.Project.close (tsserver.js:139542:38)
    at InferredProject.close (tsserver.js:140420:40)
    at ProjectService.removeProject (tsserver.js:141660:25)
    at ProjectService.cleanupAfterOpeningFile (tsserver.js:143206:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143404:26)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - OSS 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T19:57:59.162Z)
OS version: Linux x64 5.4.31-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) Silver N5000 CPU @ 1.10GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.59GB (2.85GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.1.0
gitlens|eam|10.2.1
prettier-vscode|esb|4.2.0
vscode-docker|ms-|1.0.0
vscode-icons|vsc|10.1.1

</details>

**Comment by bugaro** [comment]
https://www.github.com/microsoft/vscode/issues/94498
