### ISSUE TITLE
CodeLens references in Notebooks throws error

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#95135]
Version: 1.45.0-insider
Commit: 44c5185373d5f209cd6c0b5d29a216fb801da34e
Date: 2020-04-10T19:43:46.226Z (2 days ago)
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Clicking on a CodeLens for references gives me this:

![image](https://user-images.githubusercontent.com/2644648/79144614-1f1e9e00-7d74-11ea-9b81-b98667e43b13.png)

Looking at the Dev Tools, it looks like we've got a nice stack trace:

```
ERR Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
	at asHoverContent (/Users/tyleonha/Code/PowerShell/vscode/vscode-powershell/node_modules/vscode-languageclient/lib/protocolConverter.js:101:27)
	at asHover (/Users/tyleonha/Code/PowerShell/vscode/vscode-powershell/node_modules/vscode-languageclient/lib/protocolConverter.js:134:31)

ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.

ERR TreeError [ReferencesWidget] Data tree node not found: [object Object]: Error: TreeError [ReferencesWidget] Data tree node not found: [object Object]
    at x.getDataNode (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1078:66)
    at x.reveal (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1077:643)
    at e._revealReference (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2712:634)
    at e.setSelection (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2710:915)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2718:290

ERR Unable to read file '/vscode-notebook:/Users/tyleonha/Code/PowerShell/Misc/notebook.ps1, cell 6' (Error: Unable to resolve non-existing file '/vscode-notebook:/Users/tyleonha/Code/PowerShell/Misc/notebook.ps1, cell 6'): Error: Unable to read file '/vscode-notebook:/Users/tyleonha/Code/PowerShell/Misc/notebook.ps1, cell 6' (Error: Unable to resolve non-existing file '/vscode-notebook:/Users/tyleonha/Code/PowerShell/Misc/notebook.ps1, cell 6')
    at e.doReadAsFileStream (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1632:809)
```

cc @rebornix

**Comment by TylerLeonhardt** [comment]
This seems fixed in insiders 🎉

![image](https://user-images.githubusercontent.com/2644648/80002407-714a7800-8474-11ea-8078-a1a42255cf64.png)

**Comment by isidorn** [comment]
Adding the verified label as user has verified it.
