### ISSUE TITLE
Build with python3

### ISSUE THREAD

**Issue by eagleoflqj** [microsoft/vscode#95176]
Python2 is deprecated. Ubuntu 20.04 LTS has already removed it.
Just tried building code-oss on Ubuntu 20.04 by making /usr/bin/python point to python3, and the build was successful.
Maybe it's time to move to python3?

**Comment by joaomoreno** [comment]
Can you show me where we depend on python3?

**Comment by eagleoflqj** [comment]
Without /usr/bin/python linking to python3, I got this error:
```
liumeo@liumeo-ubuntu:~/github/vscode$ yarn
yarn install v1.22.4
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.1: The platform "linux" is incompatible with this module.
info "fsevents@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info vscode-windows-ca-certs@0.2.0: The platform "linux" is incompatible with this module.
info "vscode-windows-ca-certs@0.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info vscode-windows-registry@1.0.2: The platform "linux" is incompatible with this module.
info "vscode-windows-registry@1.0.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-foreground-love@0.2.0: The platform "linux" is incompatible with this module.
info "windows-foreground-love@0.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-mutex@0.3.0: The platform "linux" is incompatible with this module.
info "windows-mutex@0.3.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-process-tree@0.2.4: The platform "linux" is incompatible with this module.
info "windows-process-tree@0.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/14] ⠁ keytar
[6/14] ⠁ spdlog
[9/14] ⠁ vscode-sqlite3
[7/14] ⠁ vscode-nsfw
error /home/liumeo/github/vscode/node_modules/vscode-sqlite3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/liumeo/github/vscode/node_modules/vscode-sqlite3
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.16.2 | linux | x64
gyp info find Python using Python version 3.8.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/liumeo/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/liumeo/github/vscode/node_modules/vscode-sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/liumeo/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/liumeo/.cache/node-gyp/7.2.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/liumeo/.cache/node-gyp/7.2.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/liumeo/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/liumeo/.cache/node-gyp/7.2.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/liumeo/github/vscode/node_modules/vscode-sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/liumeo/github/vscode/node_modules/vscode-sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3280000/sqlite3.c
/bin/sh: 1: python: not found
make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3280000/sqlite3.c] Error 127
make: Leaving directory '/home/liumeo/github/vscode/node_modules/vscode-sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/liumeo/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-21-generic
gyp ERR! command "/home/liumeo/.nvm/versions/node/v12.16.2/bin/node" "/home/liumeo/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/liumeo/github/vscode/node_modules/vscode-sqlite3
gyp ERR! node -v v12.16.2
```
vscode-sqlite3 needs python2 or 3 to run extract.py. gyp can find my python3.8.2, but doesn't use it.

**Comment by joaomoreno** [comment]
If Python3 works for you, keep on using it. We won't change the developer docs unless absolutely necessary or obviously advantageous.
