### ISSUE TITLE
file explorer: cant create new files at top level

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#95205]
From source, Ubuntu:

- open a folder without any subfolders
- in the file explorer click on the 'create file' action or use the context menu
- nothing happens

Dev tools console shows:
```
  ERR TreeError [FileExplorer] Tree element not found: [object Object]: Error: TreeError [FileExplorer] Tree element not found: [object Object]
    at CompressedObjectTreeModel.getCompressedNode (file:///home/martin/workspaces/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:223:23)
    at CompressedObjectTreeModel.expandTo (file:///home/martin/workspaces/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:203:41)
    at CompressibleObjectTreeModel.expandTo (file:///home/martin/workspaces/vscode/out/vs/base/browser/ui/tree/compressedObjectTreeModel.js:344:31)
    at CompressibleObjectTree.reveal (file:///home/martin/workspaces/vscode/out/vs/base/browser/ui/tree/abstractTree.js:1162:24)
    at WorkbenchCompressibleAsyncDataTree.reveal (file:///home/martin/workspaces/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:428:23)
    at file:///home/martin/workspaces/vscode/out/vs/workbench/contrib/files/browser/views/explorerView.js:157:35
```

**Comment by isidorn** [comment]
Fixed in latest. Thanks for reporting!

**Comment by danlester** [comment]
However, there doesn't seem to be a way to drag a file to move it to the very top-level folder. This seems to be a design failure - I don't think there is a bug as such.

This is in Mac 1.44.2. Thank you.
