### ISSUE TITLE
URI malformed

### ISSUE THREAD

**Issue by jaybee82** [microsoft/vscode#95241]
- VSCode Version: 1.45.0-insider
- OS Version: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. click (Menu) Help / 'check for updates'
2. click (Sidebar) Settings / 'Check for updates' 

Does this issue occur when all extensions are disabled?: Yes

URI malformed notification appears while hit 'check for updates' in reported locations
Error message in console:

URIError: URI malformed
	at decodeURIComponent (<anonymous>)
	at Url.parse (url.js:340:19)
	at Object.urlParse [as parse] (url.js:150:13)
	at Function.e.makeRequest (c:\Tools\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\client\dist\jsonMain.js:1:76537)
	at Timeout.s [as _onTimeout] (c:\Tools\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\client\dist\jsonMain.js:1:95593)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)

**Comment by IllusionMH** [comment]
Cannot reproduce this one.

```
Version: 1.45.0-insider (user setup)
Commit: c8826e4ff5246775ebee0fb932402de6af55ddc8
Date: 2020-04-14T05:58:16.222Z
OS: Windows_NT x64 10.0.18363
```

**Comment by jaybee82** [comment]
![image](https://user-images.githubusercontent.com/34724117/79302503-ddfdc980-7eec-11ea-996b-7b8415a64f92.png)

**Comment by joaomoreno** [comment]
Can you reproduce if you disable extensions? `code --disable-extensions`?

**Comment by jaybee82** [comment]
yes, same behavior with disabled extensions:
![image](https://user-images.githubusercontent.com/34724117/79571281-3c78a280-80bb-11ea-9c3a-a964d59a99c8.png)

Also same issue even with elevated rights

**Comment by joaomoreno** [comment]
Does the error appear *exactly* when you run the check for updates?
