### ISSUE TITLE
Exception opening web out of sources

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#95341]
Steps to Reproduce:

1. `./resources/server/web.sh`
2. check console

```
 ERR Cannot read property 'name' of undefined: TypeError: Cannot read property 'name' of undefined
    at ExplorerViewPaneContainer.getTitle (http://localhost:9888/static/out/vs/workbench/browser/parts/views/viewPaneContainer.js:667:196)
    at PaneContainerViewlet.getTitle (http://localhost:9888/static/out/vs/workbench/browser/panecomposite.js:62:47)
    at SidebarPart.showComposite (http://localhost:9888/static/out/vs/workbench/browser/parts/compositePart.js:143:61)
    at SidebarPart.doOpenComposite (http://localhost:9888/static/out/vs/workbench/browser/parts/compositePart.js:70:18)
    at SidebarPart.openComposite (http://localhost:9888/static/out/vs/workbench/browser/parts/compositePart.js:43:25)
    at SidebarPart.doOpenViewlet (http://localhost:9888/static/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:175:29)
    at SidebarPart.openViewlet (http://localhost:9888/static/out/vs/workbench/browser/parts/sidebar/sidebarPart.js:136:33)
    at http://localhost:9888/static/out/vs/workbench/browser/workbench.js:295:58
    at Workbench.restoreWorkbench (http://localhost:9888/static/out/vs/workbench/browser/workbench.js:300:19)
    at http://localhost:9888/static/out/vs/workbench/browser/workbench.js:82:36
```

**Comment by bpasero** [comment]
This causes my web workspace to not populate any folders.

**Comment by sbatten** [comment]
try now @bpasero?

**Comment by bpasero** [comment]
Ah thanks, I was about to push that change myself.

It is still a pity that TS does not null-check array access. Imho we are totally blind when it comes to arrays. Maybe @mjbvz could lobby for a new strict flag to enable this.
