### ISSUE TITLE
Regular expression search in file causes editor to freeze

### ISSUE THREAD

**Issue by seahindeniz** [microsoft/vscode#95589]
**TypeScript Version:** 3.9.0-dev.20200417
**Steps to reproduce crash**
1. Create a new file
2. Paste 59972 of |_(vertical line)_ character
3. Search | character using regular expression

**Additionally**, I am facing another issue that might be related to this.
When I try to create a new regular expression in search box and when I type |_(vertical line)_ on a normal JS file while the regular expression(.*) button has checked, vscode suddenly freeze itself and my OS shows me this after ~30 seconds
Here is the file https://jsfiddle.net/traBolic/0L9dmrwj/
![image](https://user-images.githubusercontent.com/5789670/79632357-4ce65700-8167-11ea-843e-ec43059d23d4.png)

**TS Server Error Stack**
```
RangeError: Maximum call stack size exceeded
    at bindBinaryExpressionFlow (tsserver.js:31773:30)
    at bindChildrenWorker (tsserver.js:31172:21)
    at bindChildren (tsserver.js:31081:17)
    at bind (tsserver.js:32611:21)
    at doWithConditionalBranches (tsserver.js:31401:13)
    at bindCondition (tsserver.js:31406:13)
    at bindLogicalExpression (tsserver.js:31736:17)
    at bindBinaryExpressionFlow (tsserver.js:31822:33)
    at bindChildrenWorker (tsserver.js:31172:21)
    at bindChildren (tsserver.js:31081:17)
    at bind (tsserver.js:32611:21)
    at doWithConditionalBranches (tsserver.js:31401:13)
    at bindCondition (tsserver.js:31406:13)
    at bindLogicalExpression (tsserver.js:31736:17)
    at bindBinaryExpressionFlow (tsserver.js:31822:33)
    at bindChildrenWorker (tsserver.js:31172:21)
    at bindChildren (tsserver.js:31081:17)
    at bind (tsserver.js:32611:21)
    at doWithConditionalBranches (tsserver.js:31401:13)
    at bindCondition (tsserver.js:31406:13)
    at bindLogicalExpression (tsserver.js:31736:17)
    at bindBinaryExpressionFlow (tsserver.js:31822:33)
    at bindChildrenWorker (tsserver.js:31172:21)
    at bindChildren (tsserver.js:31081:17)
    at bind (tsserver.js:32611:21)
    at doWithConditionalBranches (tsserver.js:31401:13)
    at bindCondition (tsserver.js:31406:13)
    at bindLogicalExpression (tsserver.js:31736:17)
    at bindBinaryExpressionFlow (tsserver.js:31822:33)
    at bindChildrenWorker (tsserver.js:31172:21)
    at bindChildren (tsserver.js:31081:17)
    at bind (tsserver.js:32611:21)
    at doWithConditionalBranches (tsserver.js:31401:13)
    at bindCondition (tsserver.js:31406:13)
    at bindLogicalExpression (tsserver.js:31736:17)
    at bindBinaryExpressionFlow (tsserver.js:31822:33)
    at bindChildrenWorker (tsserver.js:31172:21)
    at bindChildren (tsserver.js:31081:17)
    at bind (tsserver.js:32611:21)
    at doWithConditionalBranches (tsserver.js:31401:13)
    at bindCondition (tsserver.js:31406:13)
    at bindLogicalExpression (tsserver.js:31736:17)
    at bindBinaryExpressionFlow (tsserver.js:31822:33)
    at bindChildrenWorker (tsserver.js:31172:21)
    at bindChildren (tsserver.js:31081:17)
    at bind (tsserver.js:32611:21)
    at doWithConditionalBranches (tsserver.js:31401:13)
    at bindCondition (tsserver.js:31406:13)
    at bindLogicalExpression (tsserver.js:31736:17)
    at bindBinaryExpressionFlow (tsserver.js:31822:33)
    at bindChildrenWorker (tsserver.js:31172:21)
    at bindChildren (tsserver.js:31081:17)
    at bind (tsserver.js:32611:21)
    at doWithConditionalBranches (tsserver.js:31401:13)
    at bindCondition (tsserver.js:31406:13)
    at bindLogicalExpression (tsserver.js:31736:17)
    at bindBinaryExpressionFlow (tsserver.js:31822:33)
    at bindChildrenWorker (tsserver.js:31172:21)
    at bindChildren (tsserver.js:31081:17)
    at bind (tsserver.js:32611:21)
    at doWithConditionalBranches (tsserver.js:31401:13)
    at bindCondition (tsserver.js:31406:13)
    at bindLogicalExpression (tsserver.js:31736:17)
    at bindBinaryExpressionFlow (tsserver.js:31822:33)
    at bindChildrenWorker (tsserver.js:31172:21)
    at bindChildren (tsserver.js:31081:17)
    at bind (tsserver.js:32611:21)
    at doWithConditionalBranches (tsserver.js:31401:13)
    at bindCondition (tsserver.js:31406:13)
    at bindLogicalExpression (tsserver.js:31736:17)
    at bindBinaryExpressionFlow (tsserver.js:31822:33)
    at bindChildrenWorker (tsserver.js:31172:21)
    at bindChildren (tsserver.js:31081:17)
    at bind (tsserver.js:32611:21)
    at doWithConditionalBranches (tsserver.js:31401:13)
    at bindCondition (tsserver.js:31406:13)
    at bindLogicalExpression (tsserver.js:31736:17)
    at bindBinaryExpressionFlow (tsserver.js:31822:33)
    at bindChildrenWorker (tsserver.js:31172:21)
    at bindChildren (tsserver.js:31081:17)
    at bind (tsserver.js:32611:21)
    at doWithConditionalBranches (tsserver.js:31401:13)
    at bindCondition (tsserver.js:31406:13)
    at bindLogicalExpression (tsserver.js:31736:17)
    at bindBinaryExpressionFlow (tsserver.js:31822:33)
    at bindChildrenWorker (tsserver.js:31172:21)
    at bindChildren (tsserver.js:31081:17)
    at bind (tsserver.js:32611:21)
    at doWithConditionalBranches (tsserver.js:31401:13)
    at bindCondition (tsserver.js:31406:13)
    at bindLogicalExpression (tsserver.js:31736:17)
    at bindBinaryExpressionFlow (tsserver.js:31822:33)
    at bindChildrenWorker (tsserver.js:31172:21)
    at bindChildren (tsserver.js:31081:17)
    at bind (tsserver.js:32611:21)
    at doWithConditionalBranches (tsserver.js:31401:13)
    at bindCondition (tsserver.js:31406:13)
    at bindLogicalExpression (tsserver.js:31736:17)
    at bindBinaryExpressionFlow (tsserver.js:31822:33)
    at bindChildrenWorker (tsserver.js:31172:21)
```

---
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-96-generic

**Comment by mjbvz** [comment]
Adding @rebornix for the file search issue

**Comment by mjbvz** [comment]
@seahindeniz I'm having trouble reproducing the typescript error. What exactly do you mean by `Paste 59972 of |(vertical line) character`. Is that pasting `59972` copies of `|` into the document?

**Comment by seahindeniz** [comment]
Ah, yess @mjbvz sorry. ~59972 copies of `|` character

**Comment by mjbvz** [comment]
Thanks. I'm going to mark that as won't fix. TypeScript is parsing those as a number of logical expressions. The parsing/anaylysis on this super long expression will  eventually hit the max call stack. However in real world code, you are very unlikely to ever hit this issue

**Comment by seahindeniz** [comment]
Yeah, I agree and it was only for testing the second problem that I have faced and added as additional in to the description. I wouldn't even trouble to paste copies of | character but here I am :slightly_smiling_face:

**Comment by rebornix** [comment]
For the file search issue, it's a duplicate. Search is running in the same process as the UI so a long running one can break the UI.
