### ISSUE TITLE
remote-debugging-port=9222 broken since last update !

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#95628]
Since the last update All my applications debuging seem broken ?
![image](https://user-images.githubusercontent.com/24865815/79683190-43580000-81f6-11ea-88e5-b14cdd24c7af.png)
Windows not allow copyPast , but i think it mean 
```
cannot connect to runtime process timeout After 10000 ms - (reason not valid target )
```
Did you guys do something in the last update, i read all the update log, and cant find what just append !
It append after vscode make the auto-update.

Note: all my app start correctly but close After de delay of vscode !
![image](https://user-images.githubusercontent.com/24865815/79683337-4ef7f680-81f7-11ea-9aa8-d71c25c846d1.png)

I also check ports with `resmon.exe` to be sure no other thing use the port ! 
[image](https://user-images.githubusercontent.com/24865815/79683964-ca5ba700-81fb-11ea-83e9-507b82bdd71e.png)

Am lost!
Any tips , suggest are welcome !

---
The verbose give this
```
2020-4-19, 08:47:58.023 UTC
[08:47:58.023 UTC] OS: win32 x64
[08:47:58.023 UTC] Adapter node: v12.8.1 x64
[08:47:58.023 UTC] vscode-chrome-debug-core: 6.7.52
[08:47:58.023 UTC] debugger-for-chrome: 1.0.18
[08:47:58.023 UTC] From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"nwjs","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"fr","supportsProgressReporting":true})
[08:47:58.024 UTC] To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"Toutes les exceptions","filter":"all","default":false},{"label":"Exceptions non interceptées","filter":"uncaught","default":false}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true,"supportsEvaluateForHovers":true,"supportsLoadedSourcesRequest":true,"supportsRestartRequest":true,"supportsSetExpression":true,"supportsLogPoints":true}}
[08:47:58.024 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"ClientRequest/initialize","data":{"Versions.DebugAdapterCore":"6.7.52","Versions.DebugAdapter":"1.0.18","successful":"true","timeTakenInMilliseconds":"2.319799","requestType":"request"}}}
[08:47:58.024 UTC] From client: launch({"type":"nwjs","request":"launch","name":"Launch NWjs","runtimeExecutable":"C:\\Users\\InformatiqueLepage\\Documents\\Dev\\repo\\DDBEV/node_modules/nw/nwjs/nw.exe","runtimeArgs":["--disable-raf-throttling","--remote-debugging-port=9222"],"webRoot":"C:\\Users\\InformatiqueLepage\\Documents\\Dev\\repo\\DDBEV/dist","port":9222,"reloadAfterAttached":true,"trace":"verbose","__sessionId":"a7432165-7710-40ad-9f44-b845fa13c660"})
[08:47:58.024 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStarted","data":{"Versions.DebugAdapterCore":"6.7.52","Versions.DebugAdapter":"1.0.18","request":"launch","args":["type","request","name","runtimeExecutable","runtimeArgs","webRoot","port","reloadAfterAttached","trace","__sessionId","breakOnLoadStrategy","pathMapping","sourceMaps","sourceMapPathOverrides","targetFilter","smartStep","showAsyncStacks"]}}}
[08:47:58.024 UTC] spawn('C:\Users\InformatiqueLepage\Documents\Dev\repo\DDBEV/node_modules/nw/nwjs/nw.exe', ["--remote-debugging-port=9222","--disable-raf-throttling","--remote-debugging-port=9222","."])
[08:47:58.024 UTC] Getting browser and debug protocol version via http://127.0.0.1:9222/json/version
[08:47:58.024 UTC] Discovering targets via http://127.0.0.1:9222/json/list
[08:48:00.026 UTC] HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
[08:48:00.026 UTC] Discovering targets via http://127.0.0.1:9222/json
[08:48:00.026 UTC] HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
[08:48:00.027 UTC] There was an error connecting to http://127.0.0.1:9222/json/version : connect ECONNREFUSED 127.0.0.1:9222
[08:48:02.029 UTC] HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
[08:48:02.230 UTC] Getting browser and debug protocol version via http://127.0.0.1:9222/json/version
[08:48:02.230 UTC] Discovering targets via http://127.0.0.1:9222/json/list
[08:48:04.233 UTC] HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
[08:48:04.233 UTC] There was an error connecting to http://127.0.0.1:9222/json/version : connect ECONNREFUSED 127.0.0.1:9222
[08:48:04.234 UTC] HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
[08:48:04.234 UTC] Discovering targets via http://127.0.0.1:9222/json
[08:48:06.235 UTC] HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
[08:48:06.437 UTC] Getting browser and debug protocol version via http://127.0.0.1:9222/json/version
[08:48:06.437 UTC] Discovering targets via http://127.0.0.1:9222/json/list
[08:48:08.439 UTC] HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
[08:48:08.439 UTC] Discovering targets via http://127.0.0.1:9222/json
[08:48:08.440 UTC] HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
[08:48:08.440 UTC] There was an error connecting to http://127.0.0.1:9222/json/version : connect ECONNREFUSED 127.0.0.1:9222
[08:48:10.442 UTC] HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:9222
[08:48:10.443 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"ClientRequest/launch","data":{"Versions.DebugAdapterCore":"6.7.52","Versions.DebugAdapter":"1.0.18","successful":"false","exceptionType":"firstChance","exceptionMessage":"Connexion impossible au processus de runtime. Expiration du délai après {_timeout} ms - (raison : {_error}).","exceptionName":"Error","exceptionStack":"Error: Connexion impossible au processus de runtime. Expiration du délai après {_timeout} ms - (raison : {_error}).\n    at Object.runtimeConnectionTimeout (errors.js:91:12)\n    at chromeConnection.js:110:49\n    at processTicksAndRejections (internal/process/task_queues.js:85:5)","exceptionId":"2010","timeTakenInMilliseconds":"12435.0069","requestType":"request","numberOfChromeCmdLineSwitchesBeingUsed":"2"}}}
[08:48:10.443 UTC] To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":false,"message":"Connexion impossible au processus de runtime. Expiration du délai après 10000 ms - (raison : Connexion impossible à la cible : connect ECONNREFUSED 127.0.0.1:9222).","body":{"error":{"id":2010,"format":"Connexion impossible au processus de runtime. Expiration du délai après {_timeout} ms - (raison : {_error}).","variables":{"_error":"Connexion impossible à la cible : connect ECONNREFUSED 127.0.0.1:9222","_timeout":"10000"}}}}
[08:48:10.577 UTC] From client: disconnect({"restart":false})

```

---
- VSCode Version:
Version : 1.44.2 (user setup)
Validation : ff915844119ce9485abfe8aa9076ec76b5300ddd
Date : 2020-04-16T16:36:23.138Z
Électron : 7.1.11
Chrome : 78.0.3904.130
Node.js : 12.8.1
V8 : 7.8.279.23-electron.0
OS : Windows_NT x64 10.0.18363

---
- OS Version:
win10

---

**Comment by djmisterjon** [comment]
ok forget me , not sure why but it seem now `9229` ! 
9222 not work ! anymore ! 
Weird, am open to any theory to understand :)
