### ISSUE TITLE
vscode.workspace.fs.readDirectory() does not get all files under %USERPROFILE%\AppData\Local\Microsoft\WindowsApps

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#95828]
(for Python extension use)

- VSCode Version:1.44.2
- OS Version: Microsoft Windows 10 [Version 10.0.18362.778]

Steps to Reproduce:
1. Call `vscode.workspace.fs.readDirectory()` on `"C:\Users\*****\AppData\Local\Microsoft\WindowsApps"`

Notes:
![image](https://user-images.githubusercontent.com/3840081/79945417-93b3a580-8422-11ea-8537-3581ff235178.png)

I am not sure if they are regular symlinks, since `dir \a` does not show them as symlinks:
```
C:\Users\*****\AppData\Local\Microsoft\WindowsApps>dir /a
 Volume in drive C is OSDisk
 Volume Serial Number is CCED-E58F

 Directory of C:\Users\karth\AppData\Local\Microsoft\WindowsApps

04/16/2020  12:51 PM    <DIR>          .
04/16/2020  12:51 PM    <DIR>          ..
04/16/2020  12:51 PM    <DIR>          Backup
03/10/2020  01:15 AM    <DIR>          CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc
03/24/2020  07:48 PM                 0 debian.exe
04/14/2020  11:59 PM                 0 GameBarElevatedFT_Alias.exe
04/16/2020  12:51 PM                 0 idle.exe
04/16/2020  12:51 PM                 0 idle3.8.exe
04/16/2020  12:51 PM                 0 idle3.exe
11/09/2019  02:15 AM    <DIR>          Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
11/13/2019  10:09 AM    <DIR>          Microsoft.MicrosoftEdge_8wekyb3d8bbwe
04/14/2020  11:59 PM    <DIR>          Microsoft.XboxGamingOverlay_8wekyb3d8bbwe
11/13/2019  10:09 AM                 0 MicrosoftEdge.exe
04/16/2020  12:51 PM                 0 pip.exe
04/16/2020  12:51 PM                 0 pip3.8.exe
04/16/2020  12:51 PM                 0 pip3.exe
04/16/2020  12:51 PM                 0 python.exe
04/16/2020  12:51 PM                 0 python3.8.exe
04/16/2020  12:51 PM                 0 python3.exe
04/16/2020  12:51 PM    <DIR>          PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0
04/16/2020  12:51 PM                 0 pythonw.exe
04/16/2020  12:51 PM                 0 pythonw3.8.exe
04/16/2020  12:51 PM                 0 pythonw3.exe
03/24/2020  07:48 PM    <DIR>          TheDebianProject.DebianGNULinux_76v4gfsz19hv4
03/10/2020  01:15 AM                 0 ubuntu.exe
              16 File(s)              0 bytes
               9 Dir(s)  42,065,428,480 bytes free
```

**Comment by int19h** [comment]
Far says they're reparse points:

![image](https://user-images.githubusercontent.com/1175142/79946278-7d0e4e00-8424-11ea-8254-2bc9db3f1071.png)

**Comment by bpasero** [comment]
Since I do not have a folder `WindowsApps` in that directory  I tried to reproduce reading from `C:\` where `Documents and Settings` also seems to be a reparse point. I see the folder appearing properly:

![image](https://user-images.githubusercontent.com/900690/80073436-11bd9c80-8548-11ea-81f1-dbd8bb4874f4.png)

Using code: `console.log(await vscode.workspace.fs.readDirectory(vscode.Uri.parse('file:///c:/')));`

**Comment by int19h** [comment]
Reparse points are a low-level mechanism that is used to implement a bunch of different things in NTFS - hard links, symlinks, junctions etc. This is a particular variety of reparse point that appears to be specific to the Windows Store, so I don't think this can be reproduced without it.

The folder is probably created lazily when apps are first installed. Try installing Python from the Store: https://www.microsoft.com/en-us/p/python-38/9mssztt1n39l

**Comment by bpasero** [comment]
This seems to be a node.js bug, I can neither `lstat` nor `stat` the children of that folder :

```
> fs.statSync("c:\\Users\\bpasero\\AppData\\Local\\Microsoft\\WindowsApps\\GameBarElevatedFT_Alias.exe")                 
Thrown:                                                                                                                  
{ Error: UNKNOWN: unknown error, stat 'c:\Users\bpasero\AppData\Local\Microsoft\WindowsApps\GameBarElevatedFT_Alias.exe' 
    at Object.statSync (fs.js:855:3)                                                                                     
  errno: -4094,                                                                                                          
  syscall: 'stat',                                                                                                       
  code: 'UNKNOWN',                                                                                                       
  path:                                                                                                                  
   'c:\\Users\\bpasero\\AppData\\Local\\Microsoft\\WindowsApps\\GameBarElevatedFT_Alias.exe' }                           
> fs.lstatSync("c:\\Users\\bpasero\\AppData\\Local\\Microsoft\\WindowsApps\\GameBarElevatedFT_Alias.exe")                
Thrown:                                                                                                                  
{ Error: UNKNOWN: unknown error, lstat 'c:\Users\bpasero\AppData\Local\Microsoft\WindowsApps\GameBarElevatedFT_Alias.exe'
    at Object.lstatSync (fs.js:845:3)                                                                                    
  errno: -4094,                                                                                                          
  syscall: 'lstat',                                                                                                      
  code: 'UNKNOWN',                                                                                                       
  path:                                                                                                                  
   'c:\\Users\\bpasero\\AppData\\Local\\Microsoft\\WindowsApps\\GameBarElevatedFT_Alias.exe' }                           
>                                                                                                                        
```

Can you report it? VSCode needs the stat to know what thing it deals with.

**Comment by karthiknadig** [comment]
Reported on node https://github.com/nodejs/node/issues/33024

**Comment by TylerLeonhardt** [comment]
New upstream issue: https://github.com/nodejs/node/issues/36790

**Comment by bpasero** [comment]
I cannot recall why I set the "fixed-in-electron-11" label, I assume this is still an issue?
