### ISSUE TITLE
Failed to watch ref .git/refs/remotes/origin/master, is most likely packed

### ISSUE THREAD

**Issue by tedpelas** [microsoft/vscode#96176]
- VSCode Version: 1.44.2
- OS Version: Darwin x64 19.3.0

Steps to Reproduce:

1. `Pull` -OR- `Sync` from pre-existing Remote repo
2. Output Error:
```
> git remote --verbose
Failed to watch ref '/Users/ted/git/xxxx/.git/refs/remotes/origin/master', is most likely packed.
Error: ENOENT: no such file or directory, watch '/Users/ted/git/xxxx/.git/refs/remotes/origin/master'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1270:11)
    at Object.t.watch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1:598268)
    at T.updateTransientWatchers (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1:83870)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:517)
    at e.updateModelState (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:1:102740)
> git config --get commit.template
```

More details:
```bash
$ git remote --verbose
origin	git@github.com:tedpelas/xxxx.git (fetch)
origin	git@github.com:tedpelas/xxxx.git (push)

$ ls -l .git/refs/remotes/origin/
-rw-r--r--  1 ted  staff  32 Apr 26 09:40 HEAD

$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
  remotes/origin/test
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by tedpelas** [comment]
```bash
$ ls -l .git/refs/remotes/origin/
-rw-r--r--  1 ted  staff  32 Apr 26 09:40 HEAD
```
