### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by brianpham93** [microsoft/vscode#96188]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143381:34)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.45.0-insider (a250df703de955a38aed427a917bce8278ab3331, 2020-04-24T20:46:59.782Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|-psn_0_2753184|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
turbo-console-log|Cha|1.4.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
githistory|don|0.6.4
gitlens|eam|10.2.1
prettier-vscode|esb|4.5.0
vscode-mocha-test-adapter|hbe|2.3.0
vscode-test-explorer|hbe|2.18.0
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
azure-pipelines|ms-|1.165.1
vscode-azureappservice|ms-|0.16.5
vscode-azurefunctions|ms-|0.22.0
vscode-azureresourcegroups|ms-|0.1.0
vscode-azurestorage|ms-|0.9.0
vscode-azurevirtualmachines|ms-|0.1.0
vscode-cosmosdb|ms-|0.12.2
vscode-docker|ms-|1.1.0
azure-account|ms-|0.8.9
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.0.11
azurerm-vscode-tools|msa|0.9.1
autoimport|ste|1.5.3
terminal-tabs|Tyr|0.2.0
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.1.1
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.3.1

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Same error stack as https://github.com/microsoft/TypeScript/issues/38076

Closing as upstream
