### ISSUE TITLE
TS Server fatal error:  Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by hackers267** [microsoft/vscode#96191]
We have written the needed data into your clipb
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.9.0-dev.20200425
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
TypeError: Cannot read property 'get' of undefined
    at resolveModuleNamesReusingOldState (tsserver.js:100162:92)
    at processImportedModules (tsserver.js:101608:35)
    at findSourceFile (tsserver.js:101351:17)
    at tsserver.js:101180:85
    at getSourceFileFromReferenceWorker (tsserver.js:101147:34)
    at processSourceFile (tsserver.js:101180:13)
    at processRootFile (tsserver.js:101003:13)
    at tsserver.js:101578:21
    at Object.forEach (tsserver.js:167:30)
    at processLibReferenceDirectives (tsserver.js:101573:16)
    at findSourceFile (tsserver.js:101348:21)
    at tsserver.js:101180:85
    at getSourceFileFromReferenceWorker (tsserver.js:101147:34)
    at processSourceFile (tsserver.js:101180:13)
    at processRootFile (tsserver.js:101003:13)
    at tsserver.js:101578:21
    at Object.forEach (tsserver.js:167:30)
    at processLibReferenceDirectives (tsserver.js:101573:16)
    at findSourceFile (tsserver.js:101348:21)
    at tsserver.js:101180:85
    at getSourceFileFromReferenceWorker (tsserver.js:101147:34)
    at processSourceFile (tsserver.js:101180:13)
    at processRootFile (tsserver.js:101003:13)
    at tsserver.js:101578:21
    at Object.forEach (tsserver.js:167:30)
    at processLibReferenceDirectives (tsserver.js:101573:16)
    at findSourceFile (tsserver.js:101348:21)
    at tsserver.js:101180:85
    at getSourceFileFromReferenceWorker (tsserver.js:101147:34)
    at processSourceFile (tsserver.js:101180:13)
    at processRootFile (tsserver.js:101003:13)
    at tsserver.js:101578:21
    at Object.forEach (tsserver.js:167:30)
    at processLibReferenceDirectives (tsserver.js:101573:16)
    at findSourceFile (tsserver.js:101348:21)
    at tsserver.js:101180:85
    at getSourceFileFromReferenceWorker (tsserver.js:101147:34)
    at processSourceFile (tsserver.js:101180:13)
    at processRootFile (tsserver.js:101003:13)
    at tsserver.js:101578:21
    at Object.forEach (tsserver.js:167:30)
    at processLibReferenceDirectives (tsserver.js:101573:16)
    at findSourceFile (tsserver.js:101348:21)
    at tsserver.js:101180:85
    at getSourceFileFromReferenceWorker (tsserver.js:101147:34)
    at processSourceFile (tsserver.js:101180:13)
    at processRootFile (tsserver.js:101003:13)
    at tsserver.js:101578:21
    at Object.forEach (tsserver.js:167:30)
    at processLibReferenceDirectives (tsserver.js:101573:16)
    at findSourceFile (tsserver.js:101348:21)
    at tsserver.js:101180:85
    at getSourceFileFromReferenceWorker (tsserver.js:101147:34)
    at processSourceFile (tsserver.js:101180:13)
    at processRootFile (tsserver.js:101003:13)
    at tsserver.js:101578:21
    at Object.forEach (tsserver.js:167:30)
    at processLibReferenceDirectives (tsserver.js:101573:16)
    at findSourceFile (tsserver.js:101348:21)
    at tsserver.js:101180:85
    at getSourceFileFromReferenceWorker (tsserver.js:101147:34)
    at processSourceFile (tsserver.js:101180:13)
    at processRootFile (tsserver.js:101003:13)
    at tsserver.js:101578:21
    at Object.forEach (tsserver.js:167:30)
    at processLibReferenceDirectives (tsserver.js:101573:16)
    at findSourceFile (tsserver.js:101348:21)
    at tsserver.js:101180:85
    at getSourceFileFromReferenceWorker (tsserver.js:101147:34)
    at processSourceFile (tsserver.js:101180:13)
    at processRootFile (tsserver.js:101003:13)
    at tsserver.js:99927:60
    at Object.forEach (tsserver.js:167:30)
    at Object.createProgram (tsserver.js:99927:16)
    at synchronizeHostData (tsserver.js:138653:26)
    at Proxy.getProgram (tsserver.js:138745:13)
    at InferredProject.Project.updateGraphWorker (tsserver.js:143237:53)
    at InferredProject.Project.updateGraph (tsserver.js:143180:42)
    at updateProjectIfDirty (tsserver.js:144444:45)
    at Array.forEach (<anonymous>)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:146556:41)
    at tsserver.js:146825:97
    at Object.flatMap (tsserver.js:465:25)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:146825:41)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:147688:46)
    at tsserver.js:149451:88
    at IOSession.Session.executeWithRequestId (tsserver.js:149442:28)
    at IOSession.Session.executeCommand (tsserver.js:149451:33)
    at IOSession.Session.onMessage (tsserver.js:149475:35)
    at Interface.<anonymous> (tsserver.js:150791:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code - Insiders 1.45.0-insider (a250df703de955a38aed427a917bce8278ab3331, 2020-04-24T10:02:48.114Z)
OS version: Windows_NT x64 10.0.19613

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (3.77GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
vscode-tomcat|ada|0.11.1
Bookmarks|ale|11.1.0
project-manager|ale|10.12.0
toolkit-vscode|ali|2020.4.2
i18n-ally|ant|2.0.3
eggjs|ati|0.3.1
vscode-auto-schema|axe|0.1.0
vscode-comment-autocomplete|axe|0.4.2
apex-javadoc|bta|1.0.3
gitignore|cod|0.6.0
vscode-mysql-client|cwe|1.8.4
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.1
prettier-vscode|esb|4.5.0
vscode-jest-runner|fir|0.4.15
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.2
vscode-pull-request-github|Git|0.15.0
todo-tree|Gru|0.0.173
rest-client|hum|0.23.2
output-colorizer|IBM|0.1.2
comment-translate|int|1.4.2
path-autocomplete|ion|1.13.6
vscode-deno|jus|1.6.0
vscode-deno-extensionpack|jus|0.2.0
vscode-regexp-preivew|Lul|1.0.0
javadoc-tools|mad|1.4.0
git-graph|mhu|1.22.0
import-sorter|mik|3.3.1
vscode-docker|ms-|1.1.0
vscode-edge-devtools|ms-|1.0.7
python|ms-|2020.4.74986
remote-containers|ms-|0.112.0
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-typescript-next|ms-|3.9.20200425
vsliveshare|ms-|1.0.2048
vsonline|ms-|1.0.2096
debugger-for-chrome|msj|4.12.6
debugger-for-edge|msj|1.0.14
uuid-generator|net|0.0.4
vetur|oct|0.24.0
vscode-react-refactor|pla|1.0.5
vscode-p3c|Rec|0.1.2
java|red|0.60.0
vscode-xml|red|0.11.0
git-commit-plugin|red|0.0.5
vscode-leetcode|she|0.16.2
id-gen|sil|1.1.1
vscode-fileutils|sle|3.0.1
rewrap|stk|1.9.1
code-spell-checker|str|1.8.0
unique-window-colors|stu|1.0.51
vscode-input-sequence|tom|0.2.0
vscodeintellicode|Vis|1.2.6
vscode-java-debug|vsc|0.25.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.9.0
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.21.2
vscode-icons|vsc|10.1.1
codetour|vsl|0.0.23
gistfs|vsl|0.0.66
quokka-vscode|Wal|1.0.289
vscode-surround|yat|1.0.2
vscode-intelli-refactor|ypr|0.1.1

(1 theme extensions excluded)

</details>
oard because it was too large to send. Please paste.

**Comment by mjbvz** [comment]
Thanks. Same call stack as https://github.com/microsoft/TypeScript/issues/37938
