### ISSUE TITLE
Notebook UI popped dev tools and displayed stack trace when clicking out of markdown cell

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#96207]
Version: 1.45.0-insider
Commit: d342048538c28d54afd1c6beea03f3a89af04359
Date: 2020-04-23T07:46:52.128Z (3 days ago)
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

Not sure exactly what I did... but I think I...
1. Created a new markdown cell at the bottom of my file
2. Typed in it
3. Clicked _below_ the new cell

Dev tools popped and:
```
[uncaught exception]: Error: Could not call remote method 'setIgnoreMenuShortcuts'. Check that the method signature is correct. Underlying error: Object has been destroyed
Underlying stack: Error: Object has been destroyed
    at electron/js2c/browser_init.js:6764:63
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)

onUnexpectedError @ bootstrap-window.js:209
bootstrap-window.js:212 Error: Could not call remote method 'setIgnoreMenuShortcuts'. Check that the method signature is correct. Underlying error: Object has been destroyed
Underlying stack: Error: Object has been destroyed
    at electron/js2c/browser_init.js:6764:63
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)

    at electron/js2c/browser_init.js:6766:17
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)
onUnexpectedError @ bootstrap-window.js:212
remote.js:221 Uncaught Error: Could not call remote method 'setIgnoreMenuShortcuts'. Check that the method signature is correct. Underlying error: Object has been destroyed
Underlying stack: Error: Object has been destroyed
    at electron/js2c/browser_init.js:6764:63
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)

    at electron/js2c/browser_init.js:6766:17
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)
log.ts:197   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
bootstrap-window.js:209 [uncaught exception]: Error: Could not call remote method 'setIgnoreMenuShortcuts'. Check that the method signature is correct. Underlying error: Object has been destroyed
Underlying stack: Error: Object has been destroyed
    at electron/js2c/browser_init.js:6764:63
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)

onUnexpectedError @ bootstrap-window.js:209
bootstrap-window.js:212 Error: Could not call remote method 'setIgnoreMenuShortcuts'. Check that the method signature is correct. Underlying error: Object has been destroyed
Underlying stack: Error: Object has been destroyed
    at electron/js2c/browser_init.js:6764:63
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)

    at electron/js2c/browser_init.js:6766:17
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)
onUnexpectedError @ bootstrap-window.js:212
remote.js:221 Uncaught Error: Could not call remote method 'setIgnoreMenuShortcuts'. Check that the method signature is correct. Underlying error: Object has been destroyed
Underlying stack: Error: Object has been destroyed
    at electron/js2c/browser_init.js:6764:63
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)

    at electron/js2c/browser_init.js:6766:17
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)
bootstrap-window.js:209 [uncaught exception]: Error: Could not call remote method 'setIgnoreMenuShortcuts'. Check that the method signature is correct. Underlying error: Object has been destroyed
Underlying stack: Error: Object has been destroyed
    at electron/js2c/browser_init.js:6764:63
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)

onUnexpectedError @ bootstrap-window.js:209
(anonymous) @ bootstrap-window.js:52
emit @ events.js:203
./lib/renderer/init.ts.window.onerror @ init.ts:188
n.globals.onerror @ errorTelemetry.ts:20
dispatchEvent @ web-view-impl.ts:124
(anonymous) @ guest-view-internal.ts:85
emit @ events.js:203
onMessage @ init.ts:59
bootstrap-window.js:212 Error: Could not call remote method 'setIgnoreMenuShortcuts'. Check that the method signature is correct. Underlying error: Object has been destroyed
Underlying stack: Error: Object has been destroyed
    at electron/js2c/browser_init.js:6764:63
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)

    at electron/js2c/browser_init.js:6766:17
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)
onUnexpectedError @ bootstrap-window.js:212
(anonymous) @ bootstrap-window.js:52
emit @ events.js:203
./lib/renderer/init.ts.window.onerror @ init.ts:188
n.globals.onerror @ errorTelemetry.ts:20
dispatchEvent @ web-view-impl.ts:124
(anonymous) @ guest-view-internal.ts:85
emit @ events.js:203
onMessage @ init.ts:59
error-utils.ts:14 Uncaught Error: Could not call remote method 'setIgnoreMenuShortcuts'. Check that the method signature is correct. Underlying error: Object has been destroyed
Underlying stack: Error: Object has been destroyed
    at electron/js2c/browser_init.js:6764:63
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)

    at electron/js2c/browser_init.js:6766:17
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)
deserialize @ error-utils.ts:14
exception @ remote.js:221
metaToValue @ remote.js:225
remoteMemberFunction @ remote.js:125
setIgnoreMenuShortcutsForWebview @ webviewElement.ts:218
setIgnoreMenuShortcuts @ webviewElement.ts:211
(anonymous) @ webviewElement.ts:190
dispatchEvent @ web-view-impl.ts:124
(anonymous) @ guest-view-internal.ts:85
emit @ events.js:203
onMessage @ init.ts:59
bootstrap-window.js:209 [uncaught exception]: Error: Could not call remote method 'setIgnoreMenuShortcuts'. Check that the method signature is correct. Underlying error: Object has been destroyed
Underlying stack: Error: Object has been destroyed
    at electron/js2c/browser_init.js:6764:63
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)

onUnexpectedError @ bootstrap-window.js:209
(anonymous) @ bootstrap-window.js:52
emit @ events.js:203
./lib/renderer/init.ts.window.onerror @ init.ts:188
n.globals.onerror @ errorTelemetry.ts:20
dispatchEvent @ web-view-impl.ts:124
(anonymous) @ guest-view-internal.ts:85
emit @ events.js:203
onMessage @ init.ts:59
bootstrap-window.js:212 Error: Could not call remote method 'setIgnoreMenuShortcuts'. Check that the method signature is correct. Underlying error: Object has been destroyed
Underlying stack: Error: Object has been destroyed
    at electron/js2c/browser_init.js:6764:63
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)

    at electron/js2c/browser_init.js:6766:17
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)
onUnexpectedError @ bootstrap-window.js:212
(anonymous) @ bootstrap-window.js:52
emit @ events.js:203
./lib/renderer/init.ts.window.onerror @ init.ts:188
n.globals.onerror @ errorTelemetry.ts:20
dispatchEvent @ web-view-impl.ts:124
(anonymous) @ guest-view-internal.ts:85
emit @ events.js:203
onMessage @ init.ts:59
error-utils.ts:14 Uncaught Error: Could not call remote method 'setIgnoreMenuShortcuts'. Check that the method signature is correct. Underlying error: Object has been destroyed
Underlying stack: Error: Object has been destroyed
    at electron/js2c/browser_init.js:6764:63
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)

    at electron/js2c/browser_init.js:6766:17
    at EventEmitter.<anonymous> (electron/js2c/browser_init.js:6617:21)
    at EventEmitter.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3949:23)
    at WebContents.emit (events.js:203:13)
```

**Comment by TylerLeonhardt** [comment]
cc @rebornix

**Comment by rebornix** [comment]
Clicking on an empty area of the webview throws this error, which I don't understand why as clicking on some DOM elements is fine.

I pushed a change to check if `webContents` is destroyed or not but I don't understand why. @deepak1556 can you help on this one?

**Comment by TylerLeonhardt** [comment]
I sadly keep hitting this (at one point it was repeatedly happening until I clicked somewhere else in VS Code. I hope we can resolve this.

**Comment by isidorn** [comment]
I can not reproduce this with latest thus adding verified label.
@TylerLeonhardt please let us know if you still see this

**Comment by deepak1556** [comment]
The underlying issue will be fixed once https://github.com/microsoft/vscode/issues/95955 is handled.
