### ISSUE TITLE
TS Server fatal error:  Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by argarner** [microsoft/vscode#96322]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

**TypeScript Version:** 3.7.5
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
TypeError: Cannot read property 'path' of undefined
    at ProjectService.updateNonInferredProjectFiles (tsserver.js:137473:43)
    at ProjectService.addFilesToNonInferredProject (tsserver.js:137363:22)
    at ProjectService.updateRootAndOptionsOfNonInferredProject (tsserver.js:137511:22)
    at ProjectService.loadConfiguredProject (tsserver.js:137447:22)
    at ProjectService.createAndLoadConfiguredProject (tsserver.js:137387:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (tsserver.js:137392:36)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:138217:44)
    at tsserver.js:138448:107
    at Object.mapDefined (tsserver.js:565:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:138448:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:139302:46)
    at tsserver.js:140960:88
    at IOSession.Session.executeWithRequestId (tsserver.js:140951:28)
    at IOSession.Session.executeCommand (tsserver.js:140960:33)
    at IOSession.Session.onMessage (tsserver.js:140983:35)
    at Interface.<anonymous> (tsserver.js:142298:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 18.7.0

<details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
TabOut|alb|0.1.6
Bookmarks|ale|11.1.0
ng-template|Ang|0.901.3
indented-block-highlighting|byi|1.0.7
turbo-console-log|Cha|1.4.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
transformer|dak|1.6.0
vscode-markdownlint|Dav|0.35.1
githistory|don|0.6.5
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
vscode-npm-script|eg2|0.3.11
prettier-vscode|esb|4.5.0
git-commits|Exe|3.2.1
vscode-firefox-debug|fir|2.7.2
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.2
docker-explorer|for|0.1.7
angular2-switcher|inf|0.3.3
vscode-angular2-emmet|jak|2.0.3
vscode-hacker-typer|jev|0.1.1
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.7.0
sublime-babel-vscode|jos|0.2.10
vscode-gutter-preview|kis|0.26.1
node-module-intellisense|lei|1.5.0
rainbow-csv|mec|1.7.0
gitignore|mic|1.0.1
dotenv|mik|1.0.1
sublime-keybindings|ms-|4.0.7
debugger-for-chrome|msj|4.12.6
sqltools|mtx|0.21.7
reload|nat|0.0.6
color-highlight|nau|2.3.0
angular-console|nrw|11.1.3
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.1.0
LiveServer|rit|5.6.1
partial-diff|ryu|1.4.1
code-settings-sync|Sha|3.4.3
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
markdown-all-in-one|yzh|2.8.0

</details>

**Comment by mjbvz** [comment]
Do you see this using TypeScript 3.8+?

**Comment by argarner** [comment]
@mjbvz 
- `error notarget No matching version found for typescript@3.8.0`
- installed typescript@3.8 instead, which installed 3.8.3
- `ERROR in The Angular Compiler requires TypeScript >=3.6.4 and <3.8.0 but 3.8.3 was found instead.`
- localhost:4200 displays `Cannot GET /`

**Comment by mjbvz** [comment]
What if you use VS Code's built-in version of typescript (3.8.3) instead of your workspace version?

**Comment by argarner** [comment]
Okay ran `ng update @angular/material` first and it sorted the incompatibility error. After updating to 3.8.3 along with all my Angular deps, it appears to be fixed. Thanks @mjbvz
