### ISSUE TITLE
Problem matchers for error messages that span multiple lines

### ISSUE THREAD

**Issue by massimocode** [microsoft/vscode#9635]
- VSCode Version: 1.4.0-insider 01a3f8
- OS Version: Windows 10 x64

I'm unable to get a message built up from several lines in the output. In the output below, I would like the message to contain the spec name, and the reason it failed. Any ideas if this is possible?

I have the following output from NUnit:

```
Project dotnettesting (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
NUnit .NET Core Runner 3.4.0 
Copyright (C) 2016 Charlie Poole
Runtime Environment
    OS Platform: Windows
     OS Version: 10.0.10586
        Runtime: win10-x64
Test Files
    c:\projects\dotnettesting\bin\Debug\netcoreapp1.0\dotnettesting.dll
Errors and Failures
1) Failed : CalculatorSpec.ShouldFail
  Expected: 0
  But was:  3
at CalculatorSpec.ShouldFail() in c:\projects\dotnettesting\Calculator.spec.cs:line 12
2) Failed : CalculatorSpec.Will_Fail
  Expected: 0
  But was:  3
at CalculatorSpec.Will_Fail() in c:\projects\dotnettesting\Calculator.spec.cs:line 17
Run Settings
    WorkDirectory: c:\projects\dotnettesting
Test Run Summary
  Overall result: Failed
  Test Count: 3, Passed: 1, Failed: 2, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 2, Errors: 0, Invalid: 0
  Start time: 2016-07-22 19:16:50Z
    End time: 2016-07-22 19:16:51Z
    Duration: 0.362 seconds
Results saved as c:\projects\dotnettesting\TestResult.xml
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.
```

I have configured the following problem matcher:

``` json
"pattern": [
    {
        "regexp": "^\\d+\\) Failed.*$"
    },
    {
        "regexp": "^(.*)$",
        "message": 1
    },
    {
        "regexp": "^(.*)$",
        "message": 1
    },
    {
        "regexp": "^at (.*\\(\\)) in (.*):line (\\d+)$",
        "location": 3,
        "file": 2
    }
]
```

**Comment by dbaeumer** [comment]
It is partly possible but without actually capturing both messages. A message can only be captured once. Can you share a project showing this output. Then I can have a look why it doesn't work?

**Comment by massimocode** [comment]
@dbaeumer sure, I've just uploaded the sample project here:
https://github.com/massimocode/dotnettesting

Let me know if you need anything else

**Comment by dbaeumer** [comment]
@massimocode thanks for the example. I cloned it and run the task, however it produces the following output for me (which I have to admit is not parseable by the framework right now):
```
Project dotnettesting (.NETCoreApp,Version=v1.0) will be compiled because Input items removed from last build
Compiling dotnettesting for .NETCoreApp,Version=v1.0
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:01.5436183
 
NUnit .NET Core Runner 3.4.0 
Copyright (C) 2016 Charlie Poole
Runtime Environment
    OS Platform: Windows
     OS Version: 10.0.14393
        Runtime: win10-x64
Test Files
    p:\mseng\VSCode\Playgrounds\bugs\dotnettesting\bin\Debug\netcoreapp1.0\dotnettesting.dll
Run Settings
    WorkDirectory: p:\mseng\VSCode\Playgrounds\bugs\dotnettesting
Test Run Summary
  Overall result: Passed
  Test Count: 3, Passed: 3, Failed: 0, Inconclusive: 0, Skipped: 0
  Start time: 2016-08-15 10:22:13Z
    End time: 2016-08-15 10:22:13Z
    Duration: 0.233 seconds
Results saved as p:\mseng\VSCode\Playgrounds\bugs\dotnettesting\TestResult.xml
SUMMARY: Total: 1 targets, Passed: 1, Failed: 0.
```

I am using `dotnet --version`: `1.0.0-preview2-003121`

**Comment by massimocode** [comment]
@dbaeumer Apologies for that, the code I checked in had passing unit tests (so no errors to report).

I have since updated the repository to have the same 2 failing tests as in the original issue description.

The repository is here:
https://github.com/massimocode/dotnettesting

Thanks!

**Comment by dbaeumer** [comment]
I will have another look then. Thanks.

**Comment by indiejames** [comment]
I need this same functionality (capturing a message across multiple lines). I also have output from my tests like

  Expected: 0
  But was:  3

that I would like to capture as the 'message'.

**Comment by dbaeumer** [comment]
@indiejames we are working on making tasks API so that people can code this. Having a declarative approach to this requires me to invent a programming language in JSON :-(

**Comment by dbaeumer** [comment]
It is `OnDeck` but not planned for a specific milestone.

**Comment by jpihl** [comment]
I had the same issue with gtest. I found a workaround which might help some people until this feature is available.

Here's my problemMatcher for gtest:
```
"problemMatcher": {
    "owner": "cpp",
    "fileLocation": ["relative", "${workspaceRoot}/test/src/"],
    "severity": "error",
    "pattern": [{
        "regexp": "^(.*):(\\d+):\\s+.*$",
        "file": 1,
        "line": 2
    },
    {
        "regexp": "^((:?Value of:.*)|(:?  Actual: .*)|(:?Expected: .*))$",
        "message": 1,
        "loop": true
    }]
}
```
I'm on linux so I can't build your test project, but I bet it can be done in a similar way.

The drawback of this approach is that it will produce a problem per line in the problem message, but you get the error message(s) when you hover over the line.
![gtest_problemmatcher](https://user-images.githubusercontent.com/583663/34044426-2f873918-e1a5-11e7-92e4-53c03e88072b.png)

**Comment by AshleyYakeley** [comment]
This is a pain point for Haskell users, too. Here's a typical multi-line error from GHC:
```
    /home/ashley/Projects/Haskell/Truth/pinafore/lib/Pinafore/Language/Read.hs:253:28: error:
        • Could not deduce (ToTypeF
                              (Pinafore.Language.Type.PinaforeType baseedit)
                              Pinafore.Entity.Predicate)
            arising from a use of ‘qConstExpr’
          from the context: HasPinaforeEntityEdit baseedit
            bound by the type signature for:
                       readExpression3 :: forall baseedit.
                                          HasPinaforeEntityEdit baseedit =>
                                          Parser (PinaforeTypeCheck (QExpr baseedit))
            at lib/Pinafore/Language/Read.hs:(210,1)-(212,50)
        • In the second argument of ‘($)’, namely ‘qConstExpr p’
          In the second argument of ‘($)’, namely ‘return $ qConstExpr p’
          In a stmt of a 'do' block: return $ return $ qConstExpr p
        |
    253 |          return $ return $ qConstExpr p) <|>
        |                            ^^^^^^^^^^^^

```
The best I can do with the current `problemMatcher` is capture the first line of the full message (`• Could not deduce (ToTypeF`).

**Comment by AshleyYakeley** [comment]
If I wanted a quick fix for this, I'd create an `append` boolean JSON key similar to `loop`, but appending the message to the current problem instead of outputting a new problem.

**Comment by AshleyYakeley** [comment]
So it looks like the UI work done in 1.31 on multi-line messages is part of a fix to this issue, but providing an API is still to be done, is that correct?

**Comment by alexr00** [comment]
The UI work will be useful for this, but yes, there is still Task API that will need to be added.

**Comment by cmeiklejohn** [comment]
> If I wanted a quick fix for this, I'd create an `append` boolean JSON key similar to `loop`, but appending the message to the current problem instead of outputting a new problem.

Did you ever come up with a good solution for this?  I'm using Koka and I've got similar issues with multi-line error messages.  I'm fine with capturing them only for the hover output, but I can't seem to write a problem matcher that captures them correctly.

Here's a typical error:

```
/mnt/c/Users/chris/Documents/GitHub/koka-example/src/test.kk(3,14): error: Invalid type
  type context : fun test() : io {
                 }
  type         :              io
  inferred kind: E
  expected kind: V
  because      : The result of a function type must be a type
```

My current matcher is good enough for capturing the first line:

```
"pattern": [
                    {
                        "regexp": "(.*?)[(](\\d+),\\s?(\\d+)[)]: (error|warning): (.*)",
                        "file": 1,
                        "line": 2,
                        "column": 3,
                        "severity": 4,
                        "message": 5
                    }
                ]
```

...but, ideally I'd like to capture the remaining lines in the hover output.  Is there any easy way to do this?

**Comment by AshleyYakeley** [comment]
Currently there is no way to do this, I believe.

**Comment by benny-medflyt** [comment]
It would be nice if visual studio code problemMatcher could parse a "universal" JSON format. so you could configure your task as:

    "pattern": "json"

and then the output of the program would be expected to be (single-line) JSON lines such as:

```json
{"message": "Unknown variable pictur", "location": {"line": 4, "col": 12}, "severity": "error"}
```

Since it is JSON, the "message" field can contain "\n" characters for errors that span multiple lines. And everyone can write their own custom filter scripts (in any language they want) that will convert the output of their favorite program into this universal JSON output format.

As a bonus, this format can be extended in the future. For example, for the hypothetical error above, my compiler might give me a hint such as: "perhaps you meant picture". This could result in a "quickfix" field such as:

```json
{ ..., "quickfix": [{"title": "Rename to picture", "replacementLocation": {"line": 4, "startCol": 12, "endCol": 18}, "replacementText": "picture" }]}
```

Many tools already have a JSON output format (for example [tslint](https://github.com/palantir/tslint) `--format json`), VSCode could help by encouraging a standardized format

**Comment by ncannasse** [comment]
+1 for JSON support for problems matcher, or any other way to solve this issue that's been around for many years ;)

**Comment by alexr00** [comment]
This would be solved by programmatic problem matching. Duplicate of https://github.com/microsoft/vscode/issues/59337

**Comment by Tyriar** [comment]
I did some exploration with problem matchers on the weekend and I really wanted this. I suspect the reason it was closed in favor of https://github.com/microsoft/vscode/issues/59337 was because the terminal didn't expose an API to do this but we could now do that fairly easily with the serialization work that happened in the terminal to implement reconnection.

I was trying to get a nice problem matcher with a multi-line message for mocha errors and to do that I ended up needing to do a custom mocha reporter to output a specific format and then repeating the message capture several times. The problem is the exact number of the `TRACE:` message captures needed to exist, otherwise the problem matcher wouldn't accept it.

![image](https://user-images.githubusercontent.com/2193314/173403107-2cab3326-977e-4765-97ca-b5d0f686a98d.png)

Problem matcher I used:

```json
      "problemMatcher": {
        "owner": "javascript",
        "severity": "error",
        "fileLocation": "absolute",
        "pattern": [
          {
            "regexp": "^\\s*File: ([^ ]+):(\\d+)",
            "file": 1,
            "line": 2,
          },
          { "regexp": "^\\s*Trace: (.+)", "message": 1 },
          { "regexp": "^\\s*Trace: (.+)", "message": 1 },
          { "regexp": "^\\s*Trace: (.+)", "message": 1 },
          { "regexp": "^\\s*Trace: (.+)", "message": 1 },
          { "regexp": "^\\s*Trace: (.+)", "message": 1 },
          { "regexp": "^\\s*Trace: (.+)", "message": 1 },
          { "regexp": "^\\s*Trace: (.+)", "message": 1 },
          { "regexp": "^\\s*Trace: (.+)", "message": 1 },
          { "regexp": "^\\s*Trace: (.+)", "message": 1 },
          { "regexp": "^\\s*Trace: (.+)", "message": 1 },
          { "regexp": "^\\s*Trace: (.+)", "message": 1 },
          { "regexp": "^\\s*Trace: (.+)", "message": 1 },
          { "regexp": "^\\s*Trace: (.+)", "message": 1 }
        ]
      }
```

The result after pressing F8 means I wouldn't even have to open the terminal 😍 

![image](https://user-images.githubusercontent.com/2193314/173403189-c0eabf17-a8d6-4c64-b04d-c69a96a00abf.png)

I would expect something like this to work instead:

```json
        "pattern": [
          {
            "regexp": "^\\s*File: ([^ ]+):(\\d+)",
            "file": 1,
            "line": 2,
          },
          { "regexp": "^\\s*Trace: (.+)", "message": 1, "repeat": true },
        ]
```

Without a problem matcher there is the issue of the message potentially containing empty lines which would need to be supported but I would expect something like this to work for the regular "spec" reporter:

```json
"pattern": [
  {
    "regexp": "^\\s*(AssertionError: .+)",
    "file": 1,
    "line": 2,
    "message": 1
  },
  {
    "regexp": "...", // not "at ...", not sure how to do that without looking it up
    "message": 1,
    // Repeats the message until it no longer matches, needs to handle empty lines as well
    "repeatMessage": true
  },
]
```

**Comment by alx9r** [comment]
The method [described previously](https://github.com/microsoft/vscode/issues/9635#issuecomment-352007126) by @jpihl seems to only show one error in 1.76.2:

![image](https://user-images.githubusercontent.com/11237922/227397767-5dbe7b38-cf5a-46ef-91c2-033f51de1f55.png)

**Comment by alx9r** [comment]
I tried every combination of emitting message output from by build and VS Code problem matcher that I could think of.  I don't think meaningful display of multi-line problem messages of any kind is possible using any UI feature (except the editor) in 1.76.2.  I definitely welcome an example demonstrating meaningful display of multiline messages.  I have good control over what my build system emits, so if VS Code can be coerced into displaying a multiline message I expect I can adapt to that.

As a stop-gap I configured my build to dump each multiline message to a file and mention that file as a problem.  The result is easily the best multiline problem user experience I have achieved using VS Code, but it's still extra steps to see view the right problems and far from ideal.  At least I no longer have to hunt through terminal output to find details of test failures though.

Here is a screenshot of the UI for multiline problem messages with this approach:

![image](https://user-images.githubusercontent.com/11237922/227726427-ab6f874c-c9ab-4d99-8142-a4c61333293d.png)

**Comment by gar1t** [comment]
To pile on, Python's `doctest` reports errors in blocks that span lines.

Sample output:

```
**********************************************************************
File "test.md", line 1, in test.md
Failed example:
    print("hello")
Expected:
    goodbye
Got:
    hello
**********************************************************************
1 items had failures:
   1 of   1 in test.md
***Test Failed*** 1 failures.
```

**Comment by lloeki** [comment]
I've come to this issue from trying to parse Ruby's Minitest output in some meaningful way (using `Minitest::Reporters::DefaultReporter`, the original minitest reporter having basically the same format with a few irrelevant variations)

For reference, here's a typical `Minitest` output (which does not not report skips):

```
  1) Failure:
Graft::HookPoint::.const_exist?::when given a string of existing Constant#test_0001_anonymous [spec/graft/hook_point_spec.rb:56]:
Expected: false
  Actual: true

  2) Error:
Graft::HookPoint::.parse::when an valid class method notation#test_0001_anonymous:
RuntimeError: 
    spec/graft/hook_point_spec.rb:49:in `block (4 levels) in <top (required)>'
```

Here's a typical `Minitest::Reporters::DefaultReporter` output (which does report skips):

```
Error:
Graft::HookPoint::.parse::when an valid class method notation#test_0001_anonymous:
RuntimeError: 
    spec/graft/hook_point_spec.rb:49:in `block (4 levels) in <top (required)>'

Skipped:
Graft::HookPoint::.resolve_const::when given a string of existing Constant#test_0004_anonymous [/Users/loic.nageleisen/Source/github.com/DataDog/graft-rb/spec/graft/hook_point_spec.rb:78]:
FIXME: This is not working as expected

Failure:
Graft::HookPoint::.const_exist?::when given a string of existing Constant#test_0001_anonymous [/Users/loic.nageleisen/Source/github.com/DataDog/graft-rb/spec/graft/hook_point_spec.rb:56]
Minitest::Assertion: Expected: false
  Actual: true
```

We'll work with the latter.

So here how it goes, I have three `problemMatcher`s:

```
        "problemMatcher": [
```

First, attempting to capture `Error`s (i.e there was an uncaught exception); VSCode is thoroughly unhappy with that one, it doesn't even want to match on grounds that `file`+`line` are captured too far down the list:

```
            {
                "owner": "ruby",
                "fileLocation": "absolute",
                "severity": "error",
                "pattern": [
                    {
                        "regexp": "^(Error):$",
                        "message": 1
                    },
                    // Capture test
                    {
                        "regexp": "^(.*)#.*?:$",
                        "message": 1,
                    },
                    // Capture exception
                    {
                        "regexp": "^(.*):$",
                        "message": 1,
                    },
                    // Capture path
                    {
                        "regexp": "^\\s*\\[(\\S+):([0-9]+)\\]$",
                        "file": 2,
                        "line": 3
                    },
                ]
            },
```

Then we have this for test `Failure`s (i.e an assertion failed); the following works, but if I uncomment anything starting with the third pattern it suddenly fails to match:

```
          {
                "owner": "ruby",
                "fileLocation": "absolute",
                "severity": "error",
                "pattern": [
                    {
                        "regexp": "^(Failure):$",
                        "message": 1
                    },
                    {
                        "regexp": "^(.*)#.* \\[(\\S+):([0-9]+)\\]$",
                        "message": 1,
                        "file": 2,
                        "line": 3
                    },
                //  Sadly VSCode has problems with multiline messages: https://github.com/microsoft/vscode/issues/9635
                //  {
                //      "regexp": "^.*(Expected: .*)$",
                //      "message": 1,
                //  },
                //  {
                //      "regexp": "^.*(Actual: .*)$",
                //      "message": 1,
                //  }
                ]
            },
```

Interestingly enough the reason for the match failure is visible when trying something like @Tyriar did (just eat with `"regexp": "^(.*)$"` repeatedly and shove it in `message: 1`): it becomes obvious that the second line was matched by the second pattern but then the third pattern attempts to match against the second line AGAIN instead of the third.

Finally the third one, for `Skip`s; this one almost works but suffers the same fate as the one before, uncommenting the last item has it matched against the same second line instead of the third:

```
            {
                "owner": "ruby",
                "fileLocation": "absolute",
                "severity": "info",
                "pattern": [
                    {
                        "regexp": "^(Skipped):$",
                        "message": 1,
                    },
                    // Capture path
                    {
                        "regexp": "^(.*) \\[(\\S+):([0-9]+)\\]:$",
                        "file": 2,
                        "line": 3
                    },
                    // Capture test
                    {
                        "regexp": "^(.*)#.*?$",
                        "message": 1,
                    },
                //  Sadly VSCode has problems with multiline messages: https://github.com/microsoft/vscode/issues/9635
                //  // Capture skip message
                //  {
                //      "regexp": "^(.*)$",
                //      "message": 1,
                //  },
                ]
            }
```

It all gets really odd if you add/replace with a bunch of these `"regexp": "^(.*)$"` and restart VSCode, you see that it eventually goes forward for some obscure reason and ends up matching against the third line, and the same process repeats: it takes a while for it to then match on the fourth, etc... And then if you rerun a couple fo times or make some changes, eventually it stops and only the second line is ever matched against, repeatedly.

I've attached a couple or three screenshots:

- first one is running the task once _right after a project reopen_: only the `Failure` one matches, but it looks like it works; the `Skip` one may have been mismatching on an incorrect line.

  <img width="506" alt="Screenshot 2024-07-16 at 11 53 19" src="https://github.com/user-attachments/assets/462f1406-d57c-443a-a3dd-316feb964783">

- second one is running the task a second time _with no changes whatsoever_: the `Failure` now matches repeatedly on the second line, and the `Skip` one appears to work and captures the skip reason.

  <img width="1237" alt="Screenshot 2024-07-16 at 11 53 36" src="https://github.com/user-attachments/assets/0b948551-2b30-4661-abae-65173f25a629">

- third one is running the task a third time _with no changes whatsoever_: both the `Failure` and `Skip` now match repeatedly on the second line.

  <img width="1235" alt="Screenshot 2024-07-16 at 11 53 44" src="https://github.com/user-attachments/assets/5eeb7cb4-e026-49b8-943f-7c4f9e3c53ce">

Again, there was _no change whatsoever_ between these runs, merely re-running the task again, which produced _identical output_.

So overall `"message": 1` accumulation across lines appears to work just fine and I am happy with the resulting UI:

<img width="525" alt="Screenshot 2024-07-16 at 12 11 37" src="https://github.com/user-attachments/assets/ff20ee39-7850-4527-87e3-16502003058f">

<img width="896" alt="Screenshot 2024-07-16 at 12 11 45" src="https://github.com/user-attachments/assets/6aae3648-d85c-4e8e-ad9b-8427a411db49">

... but matching multiple lines, each with a distinct pattern, appears to be broken in some way.

**Comment by Nippey** [comment]
Hello,
let me provide sampe output from the Greenhills compiler, these messages are multiline as well:
```
"C:\ghs\comp_202015\ansi\stdint.h", line 40: error #256: invalid redeclaration
          of type name "uint32_t" (declared at line 218 of
          "..\..\..\source\driver\src\general\headerfile.h")
    typedef unsigned int uint32_t;

"..\..\..\source\middleware\driver\sourcefile.c", line 214: error #70:
          incomplete type is not allowed
      struct _addr addr;
                  ^

```
Errors are always terminated by a dual-linechange.
What also would be interesting, if the "column" matcher would also ingest a string instead of a number and will count the number of characters.
This way one could easily parse these things: `                     ^`

This regex parses the output just fine if used with Python.re:
`^\"(?<file>[^\"]+)\", line (?<line>\d+): (?<severity>[^#]+) #(?<code>[^:]+):(:?\s*\r?\n\s+)?(?<message>(.|\r?\n)*?)(:?\r?\n){2}`

But it seems VSCode is missing the "multiline" modifier in its matcher...

**Comment by ForsakenHarmony** [comment]
I don't know if I'm doing something wrong, but I can't get my problem matcher to parse more than the 2nd line, after that I keep getting the same line

Output:
```
ERROR in ./src/extension/extension.ts
  × Module build failed:
  ├─▶   ×
  │     │   × Expression expected
```

Matcher:
```
"problemMatcher": {
  "owner": "rspack",
  "source": "rspack",
  "severity": "error",
  "pattern": [
    {
      "kind": "file",
      "regexp": "^(ERROR) in ([^\\s].*)$",
      "severity": 1,
      "file": 2,
      // "message": 1
    },
    {
      "kind": "file",
      "regexp": "^  \\xD7 (.+):$",
      "message": 1,
    },
    {
      "regexp": "^  (.+)$",
      "message": 1
    },
  ]
},
```

Result:
![Image](https://github.com/user-attachments/assets/5004d1ca-db50-4dad-8201-143b8c41c012)


Why is the next regex getting the same line passed in again?

**Comment by GufNZ** [comment]
> But it seems VSCode is missing the "multiline" modifier in its matcher...

What happens if you start your regexes with `(?m)`?  @Nippey

**Comment by Nippey** [comment]
@GufNZ what does this do? Is it a Modifier or Matcher?

If I just place it right in front, it fails:
```Error: The string (?m)^"(?<file>[^"]+)", line (?<line>\d+): (?<severity>[^#]+) #(?<code>[^:]+):(:?\s*\r?\n\s+)? is not a valid regular expression.```

**Comment by chrisfindlayST** [comment]
It's an options modifier, either around a subexpression or like that at the start, for the entire regex.  The fact that vsCode doesn't recognise it is just rude.
