### ISSUE TITLE
TS Server fatal error:  Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by AjitZK** [microsoft/vscode#96471]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1. Just open VS Code

**TS Server Error Stack**
```
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (tsserver.js:19148:110)
    at Object.parseJsonText (tsserver.js:18972:26)
    at Object.parseJsonText (tsserver.js:18793:23)
    at ProjectService.loadConfiguredProject (tsserver.js:142258:33)
    at ProjectService.createAndLoadConfiguredProject (tsserver.js:142240:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (tsserver.js:142245:36)
    at ProjectService.assignProjectToOpenedScriptInfo (tsserver.js:143101:44)
    at tsserver.js:143396:107
    at Object.mapDefined (tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144260:46)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|113, 49, 23|
|Memory (System)|16.00GB (1.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color|ans|0.4.5
touch-bar-display|bla|1.3.1
prettier-toml|bod|0.1.0
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.29
docs-markdown|doc|0.2.66
gitlens|eam|10.2.1
vscode-npm-script|eg2|0.3.11
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|4.5.0
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.2
todo-tree|Gru|0.0.173
vscode-styled-components|jpo|0.0.29
coffeelinter|lky|1.4.0
dotenv|mik|1.0.1
vscode-azureterraform|ms-|0.3.0
vscode-docker|ms-|1.1.0
vscode-kubernetes-tools|ms-|1.2.0
python|ms-|2020.4.76186
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
azure-account|ms-|0.8.9
cpptools|ms-|0.27.0
vscode-react-native|msj|0.15.0
color-highlight|nau|2.3.0
vetur|oct|0.24.0
github-actions-vscode|Oma|2.7.0
material-icon-theme|PKi|4.1.0
vscode-css-peek|pra|3.0.2
nginx-formatter|ray|0.0.8
vscode-yaml|red|0.7.2
nunjucks|ron|0.2.3
mako|tom|0.2.0
vscodeintellicode|Vis|1.2.6
vscode-ansible|vsc|0.5.2
vscode-nginx|wil|0.7.2
vscode-import-cost|wix|2.12.0
html-css-class-completion|Zig|1.19.0

(3 theme extensions excluded)

</details>

**Comment by AjitZK** [comment]
Didn't realize it was duplicated.
