### ISSUE TITLE
[vscode.typescript-language-features] provider FAILED Error: No Project.

### ISSUE THREAD

**Issue by apupier** [microsoft/vscode#96546]
- VSCode Version: 1.44.2
- OS Version: Fedora 31

Steps to Reproduce:
don't know. I tried to launch my VS Code Extension and it was blocked.  A notification stays "Intializing JS/TS languages features"
1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

in Log (Extension Host):

```
[2020-04-29 11:41:21.413] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2020-04-29 11:41:21.413] [exthost] [error] Error: <semantic> TypeScript Server Error (3.8.3)
No Project.
Error: No Project.
    at Object.ThrowNoProject (tsserver.js:137981:23)
    at ProjectService.doEnsureDefaultProjectForFile (tsserver.js:141451:131)
    at ProjectService.ensureDefaultProjectForFile (tsserver.js:141446:75)
    at IOSession.Session.getFileAndProjectWorker (tsserver.js:145272:87)
    at IOSession.Session.getFileAndProject (tsserver.js:145255:29)
    at IOSession.Session.getApplicableRefactors (tsserver.js:145701:31)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (tsserver.js:144528:61)
    at tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (tsserver.js:145994:28)
    at IOSession.Session.executeCommand (tsserver.js:146003:33)
    at IOSession.Session.onMessage (tsserver.js:146027:35)
    at Interface.<anonymous> (tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
	at Function.create (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:52622)
	at e.dispatchResponse (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:220920)
	at e.dispatchMessage (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:219838)
	at /usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:219314
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:48:497)
	at t.Reader.onLengthData (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:227976)
	at Socket.<anonymous> (/usr/share/code/resources/app/extensions/typescript-language-features/dist/extension.js:1:227624)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

![Screenshot from 2020-04-29 11-47-50](https://user-images.githubusercontent.com/1105127/80582599-48475b80-8a0f-11ea-8c32-7d663a66d10a.png)

workaround: close and reopen VS Code instance

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by apupier** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

I reproduced only one time in my normal VS Code environment. As this is not 100% reproduceable, testing in insider won't help.
