### ISSUE TITLE
Show Environment Info command doesn't show in correct place when the widget is not visible

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#96639]
With this setting (the default):

```
"terminal.integrated.environmentChangesIndicator": "warnonly"
```

Running the command currently looks like this:

![image](https://user-images.githubusercontent.com/2193314/80643960-c27edc80-8a1d-11ea-9809-69a0f083374e.png)

**Comment by Tyriar** [comment]
Also see this in console when I do that:

```
[10884:0429/133127.182:INFO:CONSOLE(118)] "Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at DisposableStore.add (file:///E:/GitHub/microsoft/vscode/out/vs/base/common/lifecycle.js:118:38)
    at EnvironmentVariableInfoWidget._register (file:///E:/GitHub/microsoft/vscode/out/vs/base/common/lifecycle.js:145:36)
    at EnvironmentVariableInfoWidget._showHover (file:///E:/GitHub/microsoft/vscode/out/vs/workbench/contrib/terminal/browser/widgets/environmentVariableInfoWidget.js:75:22)
    at EnvironmentVariableInfoWidget.focus (file:///E:/GitHub/microsoft/vscode/out/vs/workbench/contrib/terminal/browser/widgets/environmentVariableInfoWidget.js:64:22)
    at TerminalInstance.showEnvironmentInfoHover (file:///E:/GitHub/microsoft/vscode/out/vs/workbench/contrib/terminal/browser/terminalInstance.js:1183:50)
    at Object.run (file:///E:/GitHub/microsoft/vscode/out/vs/workbench/contrib/terminal/browser/terminalActions.js:1301:126)
    at handler (file:///E:/GitHub/microsoft/vscode/out/vs/platform/actions/common/actions.js:293:52)
    at InstantiationService.invokeFunction (file:///E:/GitHub/microsoft/vscode/out/vs/platform/instantiation/common/instantiationService.js:43:24)
    at CommandService._tryExecuteCommand (file:///E:/GitHub/microsoft/vscode/out/vs/workbench/services/commands/common/commandService.js:75:63)
    at file:///E:/GitHub/microsoft/vscode/out/vs/workbench/services/commands/common/commandService.js:65:51
    at async Object.accept (file:///E:/GitHub/microsoft/vscode/out/vs/platform/quickinput/browser/commandsQuickAccess.js:111:33)", source: file:///E:/GitHub/microsoft/vscode/out/vs/base/common/lifecycle.js (118) 
```
