### ISSUE TITLE
An unexpected error prevented the window from closing (Cannot read property 'isDirty' of undefined).

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#96725]
```
Version: 1.45.0-insider (user setup)
Commit: a0fe37870c42e0704a492cdc6b8550b4cf23f63c
Date: 2020-04-30T05:39:08.281Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

I'm unsure how I got into this state, but I can't close VS Code or reload the window. Stack sohwn when I try to exit:

```
  ERR Cannot read property 'isDirty' of undefined: TypeError: Cannot read property 'isDirty' of undefined
    at e.getAllDirtyEditors (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5917:87)
    at e.saveAll (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5916:638)
    at e.doSaveAllBeforeShutdown (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5710:472)
    at e.onBeforeShutdownWithDirty (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5708:312)
    at e.onBeforeShutdown (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5708:140)
    at file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2972:264
    at e.fire (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at e.handleBeforeShutdown (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4184:876)
    at EventEmitter.<anonymous> (file:///C:/Users/Connor/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4184:129)
    at EventEmitter.emit (events.js:203:13)
    at Object.onMessage (electron/js2c/renderer_init.js:3659:16)
```

**Comment by bpasero** [comment]
I cannot explain this, it seems the editor tabs model think there is an editor that does not exist anymore. Needs steps to get any further.

**Comment by bpasero** [comment]
Upon second thought, this can maybe happen if an editor fails to serialize on shutdown. Given we have quite a few new editors, maybe this happens more often now. Marking as candidate to look into and guard against this condition.

**Comment by connor4312** [comment]
Yea, if I recall correctly this happened after I had been playing around with notebooks/custom editors in that window.

**Comment by bpasero** [comment]
@connor4312 if you can try to reproduce, it would still be great to have steps

**Comment by bpasero** [comment]
I have a feeling this could well be notebooks given how the `serialize` always returns data but the `deserialize` may not.

https://github.com/microsoft/vscode/blob/dc348340fd1a6c583cb63a1e7e6b4fd657e01e01/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L72-L91

//cc @rebornix to check if that is a problem. If you know for a fact that you cannot serialize the notebook, please already signal that by returning `undefined` from the `serialize` method.

**Comment by rebornix** [comment]
@jrieken added this, I guess we just need to return `undefined when `!(input instanceof NotebookEditorInput)`?

**Comment by bpasero** [comment]
To clarify: it is perfectly valid to return `undefined` in either of the 2 methods. I pushed a fix to handle this properly on my end. I just wanted to point out that it is always better to return `undefined` early (from the `serialize`) to reduce the data we store in SQLite.

**Comment by jrieken** [comment]
> If you know for a fact that you cannot serialize the notebook, please already signal that by returning undefined from the serialize method.

But my [assertion](https://github.com/microsoft/vscode/blob/0593e5b600cca44c09f193769b2420f260691a85/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L73) that the notebook editor input factory is only called with "my" inputs is valid, right? Or should I assume that it is called with any kind of input and return undefined then?

**Comment by bpasero** [comment]
@jrieken yeah that assumption is right, you will only be called for inputs you register for.

**Comment by connor4312** [comment]
I don't think anyone has a consistent repro for this, so I will mark it as verified unless I run into it again.
