### ISSUE TITLE
Cannot connect to Extensions marketplace 

### ISSUE THREAD

**Issue by sambres** [microsoft/vscode#96974]
Issue Type: <b>Bug</b>

When I open Visual Studio Code - Insiders, all of my extensions are not working, I have the error message "We cannot connect to the Extensions Marketplace at this time, please try again later.".

And I have these errors in the DevTool:
```
/snap/code-insiders/434/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:259 [Extension Host] TypeError: Cannot read property 'createOnigString' of undefined	
    at Grammar.createOnigString (/snap/code-insiders/434/usr/share/code-insiders/resources/app/node_modules.asar/vscode-textmate/release/main.js:2601:30)	  
    at Grammar._tokenize (/snap/code-insiders/434/usr/share/code-insiders/resources/app/node_modules.asar/vscode-textmate/release/main.js:2697:33)	  
    at Grammar.tokenizeLine2 (/snap/code-insiders/434/usr/share/code-insiders/resources/app/node_modules.asar/vscode-textmate/release/main.js:2670:22)	  
    at DocumentDecoration.tokenizeLine (/home/asambres/.vscode-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.0.29/out/src/documentDecoration.js:232:55)	  
    at DocumentDecoration.tokenizeDocument (/home/asambres/.vscode-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.0.29/out/src/documentDecoration.js:116:38)	  
    at DocumentDecorationManager.updateDocument (/home/asambres/.vscode-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.0.29/out/src/documentDecorationManager.js:33:32)	  
    at /home/asambres/.vscode-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.0.29/out/src/documentDecorationManager.js:94:30 (  
    at /home/asambres/.vscode-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.0.29/out/src/documentDecorationManager.js:96:41)  
```

```
/snap/code-insiders/434/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR Cannot read property 'important' of undefined: TypeError: Cannot read property 'important' of undefined  
    at e.fetch (file:///snap/code-insiders/434/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6605:708)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async e.doActivate (file:///snap/code-insiders/434/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6605:343)
    at async Promise.all (index 2)
    at async e.activateProactiveRecommendations (file:///snap/code-insiders/434/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6723:681)    
```

VS Code version: Code - Insiders 1.45.0-insider (d4b8ec9da3bf1061a948fbb1b0d9d3db750cc79f, 2020-05-05T07:09:48.406Z)
OS version: Linux x64 5.3.0-51-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 3543)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 1|
|Memory (System)|15.49GB (1.69GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.0.29
prettier-vscode|esb|4.5.0
prettify-json|moh|0.0.3
python|ms-|2020.4.76186
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.3.1

(5 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
> all of my extensions are not working

Do you mean extensions are not running?

Can you please disable bracer pair colorizer extension and try?

**Comment by sambres** [comment]
Yes I meant the extensions are not running.
Indeed I disabled bracer pair colorizer and somehow the extensions were running again. 

Thank you!
