### ISSUE TITLE
Dragging every view outside of the panel breaks the panel

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#97007]
1. Drag every panel view to activity bar

Now the panel looks like this:

![image](https://user-images.githubusercontent.com/22350/81083986-9370db00-8ef5-11ea-8b8a-ff81ff126085.png)

- I can't seem to drag the views back to the back using DND
- What is the `...`?

**Comment by sandy081** [comment]
@sbatten This fix is causing following error

```
ERR Assertion Failed: argument is undefined or null: Error: Assertion Failed: argument is undefined or null
    at Object.assertIsDefined (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/types.js:86:19)
    at PanelPart.createComposite (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/compositePart.js:89:149)
    at PanelPart.doOpenComposite (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/compositePart.js:56:36)
    at PanelPart.openComposite (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/compositePart.js:43:25)
    at PanelPart.doOpenPanel (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/panel/panelPart.js:313:29)
    at PanelPart.onDidRegisterPanels (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/panel/panelPart.js:110:38)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/panel/panelPart.js:181:74
    at Emitter.fire (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/common/event.js:457:42)
    at PanelRegistry.registerComposite (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/composite.js:205:33)
    at PanelRegistry.registerPanel (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/panel.js:32:19)
    at ViewsService.registerPanel (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsService.js:375:67)
    at ViewsService.registerViewletOrPanel (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsService.js:331:30)
    at ViewsService.onDidRegisterViewContainer (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsService.js:98:22)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsService.js:38:89
    at Array.forEach (<anonymous>)
    at new ViewsService (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/parts/views/viewsService.js:38:59)
    at InstantiationService._createInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:88:20)
    at InstantiationService._createServiceInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:177:29)
    at InstantiationService._createServiceInstanceWithOwner (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:165:29)
    at InstantiationService._createAndCacheServiceInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:156:43)
    at InstantiationService._getOrCreateServiceInstance (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:113:29)
    at Object.get (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:36:45)
    at Workbench.initLayout (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/layout.js:146:22)
    at file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/workbench.js:67:26
    at InstantiationService.invokeFunction (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/instantiation/common/instantiationService.js:43:24)
    at Workbench.startup (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/browser/workbench.js:61:38)
    at DesktopMain.open (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/electron-browser/desktop.main.js:61:52)
```

Looks like now panel view is trying to get rendered even before panel part is rendered.
