### ISSUE TITLE
Cannot read property '_eventEmitter' of undefined:

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#97017]
Running out of sources

- Open any file and following error is seen in the console

```
ERR Cannot read property '_eventEmitter' of undefined: TypeError: Cannot read property '_eventEmitter' of undefined
    at onDidChangeContent (file:///Users/sandy081/work/vscode/out/vs/editor/common/model/textModel.js:225:29)
    at Object.onFirstListenerAdd (file:///Users/sandy081/work/vscode/out/vs/base/common/event.js:108:36)
    at _event (file:///Users/sandy081/work/vscode/out/vs/base/common/event.js:395:43)
    at MarkerDecorationsService._onModelAdded (file:///Users/sandy081/work/vscode/out/vs/editor/common/services/markerDecorationsServiceImpl.js:94:114)
    at Emitter.fire (file:///Users/sandy081/work/vscode/out/vs/base/common/event.js:460:45)
    at ModelServiceImpl.createModel (file:///Users/sandy081/work/vscode/out/vs/editor/common/services/modelServiceImpl.js:360:36)
    at TextFileEditorModel.doCreateTextEditorModel (file:///Users/sandy081/work/vscode/out/vs/workbench/common/editor/textEditorModel.js:80:47)
    at TextFileEditorModel.createTextEditorModel (file:///Users/sandy081/work/vscode/out/vs/workbench/common/editor/textEditorModel.js:75:29)
    at TextFileEditorModel.doCreateTextModel (file:///Users/sandy081/work/vscode/out/vs/workbench/services/textfile/common/textFileEditorModel.js:323:40)
    at TextFileEditorModel.loadFromContent (file:///Users/sandy081/work/vscode/out/vs/workbench/services/textfile/common/textFileEditorModel.js:312:26)
    at TextFileEditorModel.loadFromFile (file:///Users/sandy081/work/vscode/out/vs/workbench/services/textfile/common/textFileEditorModel.js:256:33)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async TextFileEditorModelManager.resolve (file:///Users/sandy081/work/vscode/out/vs/workbench/services/textfile/common/textFileEditorModelManager.js:234:43)
    at async FileEditorInput.doResolveAsText (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/files/common/editors/fileEditorInput.js:175:21)
    at async NativeTextFileEditor.setInput (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/files/browser/editors/textFileEditor.js:89:43)
    at async EditorControl.doSetInput (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:132:21)
    at async EditorControl.openEditor (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/parts/editor/editorControl.js:50:39)
    at async file:///Users/sandy081/work/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:668:44
    at async EditorGroupView.openEditor (file:///Users/sandy081/work/vscode/out/vs/workbench/browser/parts/editor/editorGroupView.js:593:52)
    at async EditorService.openEditor (file:///Users/sandy081/work/vscode/out/vs/workbench/services/editor/browser/editorService.js:393:56)
    at async AnythingQuickAccessProvider.openAnything (file:///Users/sandy081/work/vscode/out/vs/workbench/contrib/search/browser/anythingQuickAccess.js:698:21)
```

This started occurring after 64d29b001b4ebbf5fb0a49bf7837841d37ba37e2 - where I just added debounce to the `onDidContentChange` event. Not sure what I am doing wrong here.

**Comment by alexdima** [comment]
That is not an `Event`. It must be invoked correctly with a proper `this`.

**Comment by sandy081** [comment]
I changed from Event.debounce to use Delayer.

> That is not an Event

This is being accepted by our Event util. Not sure what has to be the fix here to avoid further similar usages in future.

@joaomoreno

**Comment by joaomoreno** [comment]
> Not sure what has to be the fix here to avoid further similar usages in future.

I don't know either. We're definitely not going to add a structural difference to every single event in our codebase.
