### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by briped** [microsoft/vscode#97031]
- VSCode Version: 1.44.2 and 1.45.0-insider (both x64 system installs)
- OS Version: Windows 10 Pro version 2004

Steps to Reproduce:

1. Install VS Code
2. Start VS Code

Does this issue occur when all extensions are disabled?: Yes/No
Yes

The few screenshots are taken only after installing Insiders build and testing. As the errors and the experience is the same I deemed this enough.

![VSCode-DisabledExtensionsStillBugged](https://user-images.githubusercontent.com/4194602/81109925-24a67880-8f1b-11ea-9f79-e7860c08d1b5.jpg)

I have tried `Code.exe --disable-extensions`, extension hosts still crashes.

I have tried removing all `%userprofile\.vscode` and `%userprofile%\AppData\Roaming\Code` then starting VS code. Same problem.

I have tried uninstalling VS Code and installing it again. Same problem.

I have tried disabling Windows Defender Antivirus Real-time protection, even though nothing is being caught or quarantined. Same problem.

I have tried installing VS Code Insiders, to see if it was an issue only with stable 1.44.2. Same problem.

I have tried `"Code - Insiders.exe" --disable-extensions`. Same problem.
![VSCode-DisableExtensionsCmd](https://user-images.githubusercontent.com/4194602/81109924-240de200-8f1b-11ea-932b-b3c2c2096303.jpg)

I have tried "Help > Report Issue" within VS Code. Does nothing.

I have found several other bug reports with this error message, which all seem to have been closed with a reference to either [94858](https://github.com/microsoft/vscode/issues/94858) or [94829](https://github.com/microsoft/vscode/issues/94829). None of those two bugs match what I experience. It's not AV (I've tested with Windows Defender disabled) and nothing about code-runner.run not found.
One [comment on 94829](https://github.com/microsoft/vscode/issues/94829#issuecomment-611898709) mentions clicking on errors and warning in the VS Code status bar to get the wanted error messages. This shows nothing.

If opening the developer tools and looking in the JS Console, the following errors are shown.

![VSCode-JSConsole](https://user-images.githubusercontent.com/4194602/81109922-23754b80-8f1b-11ea-85e5-9d1666a4ab8c.jpg)

> bootstrap-window.js:209 [uncaught exception]: Error: read ENOENT
> onUnexpectedError @ bootstrap-window.js:209
> bootstrap-window.js:212 Error: read ENOENT
>     at Pipe.onStreamRead (internal/stream_base_commons.js:183)
> onUnexpectedError @ bootstrap-window.js:212
> events.js:180 Uncaught Error: read ENOENT
>     at Pipe.onStreamRead (internal/stream_base_commons.js:183)
> abstractExtensionService.ts:155 Extension host terminated unexpectedly. Code:  1  Signal:  null
> _onExtensionHostCrashed @ abstractExtensionService.ts:155
> notificationsAlerts.ts:40 Extension host terminated unexpectedly.
> onDidChangeNotification @ notificationsAlerts.ts:40
> extensionHost.ts:212 Extension Host
> extensionHost.ts:213 events.js:180
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: read ENOENT
>     at Pipe.onStreamRead (internal/stream_base_commons.js:183:27)
> Emitted 'error' event at:
>     at emitErrorNT (internal/streams/destroy.js:91:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
>     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
>   errno: 'ENOENT',
>   code: 'ENOENT',
>   syscall: 'read'
> }

**Comment by briped** [comment]
Did a quick peek in the event logs to see if anything interesting caught my eye. When starting VS Code, the following warning shows in the System log:

```
Log Name:      System
Source:        Microsoft-Windows-DistributedCOM
Date:          05-05-2020 22:02:56
Event ID:      10016
Task Category: None
Level:         Warning
Keywords:      Classic
User:          HOSTNAME\username
Computer:      Hostname
Description:
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user HOSTNAME\username SID (S-1-5-21-xxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx-xxxx) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-DistributedCOM" Guid="{1B562E86-B7AA-4131-BADC-B6F3A001407E}" EventSourceName="DCOM" />
    <EventID Qualifiers="0">10016</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8080000000000000</Keywords>
    <TimeCreated SystemTime="2020-05-05T20:02:56.6832563Z" />
    <EventRecordID>11924</EventRecordID>
    <Correlation ActivityID="{048267d9-d667-4fa4-9c1c-47f92414ce36}" />
    <Execution ProcessID="1116" ThreadID="21220" />
    <Channel>System</Channel>
    <Computer>Hostname</Computer>
    <Security UserID="S-1-5-21-xxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx-xxxx" />
  </System>
  <EventData>
    <Data Name="param1">application-specific</Data>
    <Data Name="param2">Local</Data>
    <Data Name="param3">Activation</Data>
    <Data Name="param4">{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}</Data>
    <Data Name="param5">{15C20B67-12E7-4BB6-92BB-7AFF07997402}</Data>
    <Data Name="param6">HOSTNAME</Data>
    <Data Name="param7">username</Data>
    <Data Name="param8">S-1-5-21-xxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx-xxxx</Data>
    <Data Name="param9">LocalHost (Using LRPC)</Data>
    <Data Name="param10">Unavailable</Data>
    <Data Name="param11">Unavailable</Data>
  </EventData>
</Event>
```

**Comment by briped** [comment]
Closed by accident

**Comment by briped** [comment]
Today VS Code worked without any issue. I haven't made any changes since opening this ticket.
Checked if the error in the Event Log was still there. It is still there, so it doesn't seem to have any relevance.
