### ISSUE TITLE
vscode not opening directory, opens with a empty untitled file

### ISSUE THREAD

**Issue by balupton** [microsoft/vscode#97048]
- VSCode Version: 1.44.2
- OS Version: macos 10.15.4 (19E287)

```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

Steps to Reproduce:

```
> code . --verbose --disable-extensions

[main 2020-05-06T04:29:14.956Z] Sending env to running instance...
[main 2020-05-06T04:29:14.984Z] Sent env to running instance. Terminating...
[main 2020-05-06T04:29:14.984Z] Lifecycle#kill()
```

Same result when trying to open a folder via the ui, as well as dragging a folder onto the dock icon.

Opening developer tools produces the following errors in the console

```
uncaught exception]: Error: ENOENT: no such file or directory, uv_cwd

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42:25)
    at process.cwd (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/graceful-fs/polyfills.js:10:19)
    at q.resolveSingleFolderWorkspaceInitializationPayload (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7065:171)
    at q.resolveWorkspaceInitializationPayload (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7064:563)
    at q.initServices (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7064:21)
    at q.open (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7061:715)
    at Object.t.main (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7066:444)
    at file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.js:8:763
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
onUnexpectedError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-window.js:5
/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-window.js:6 Error: ENOENT: no such file or directory, uv_cwd

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42)
    at process.cwd (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/graceful-fs/polyfills.js:10)
    at q.resolveSingleFolderWorkspaceInitializationPayload (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7065)
    at q.resolveWorkspaceInitializationPayload (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7064)
    at q.initServices (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7064)
    at q.open (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7061)
    at Object.t.main (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7066)
    at workbench.js:8
    at processTicksAndRejections (internal/process/task_queues.js:85)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:46
onUnexpectedError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-window.js:6
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3826 [mauve.terraform]: Command `terraform.validate` appears multiple times in the `commands` section.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3826 [mauve.terraform]: Command `terraform.reindex` appears multiple times in the `commands` section.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3826 [mauve.terraform]: Command `terraform.preview-graph` appears multiple times in the `commands` section.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3826 [mauve.terraform]: Command `terraform.show-plan` appears multiple times in the `commands` section.
2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:262 [Extension Host] (node:12820) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:262
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3826 Activating extension 'esbenp.prettier-vscode' failed: ENOENT: no such file or directory, uv_cwd.
_logMessageInConsole @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3826
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2855 Failed to install support for joining sessions using a browser link. You can still join sessions manually.
onDidChangeNotification @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2855
```

this is the user config I am using https://github.com/balupton/dotfiles/blob/master/.scripts/users/balupton/vscode/settings.json

**Comment by balupton** [comment]
vscode insiders is unaffected

```

Version: 1.45.0-insider
Commit: d4b8ec9da3bf1061a948fbb1b0d9d3db750cc79f
Date: 2020-05-05T07:13:27.726Z (21 hrs ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

**Comment by balupton** [comment]
Setting the settings to `{}` which restarted vscode, then pasting the settings back in, seems to have fixed the issue
