### ISSUE TITLE
Assertion Failed: argument is undefined or null

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#97052]
Start vscode out of source, notice exception in the developer console
fyi @bpasero

```
ERR Assertion Failed: argument is undefined or null: Error: Assertion Failed: argument is undefined or null
    at Object.assertIsDefined (file:///Users/isidor/Development/vscode/out/vs/base/common/types.js:86:19)
    at PanelPart.createComposite (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/compositePart.js:89:149)
    at PanelPart.doOpenComposite (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/compositePart.js:56:36)
    at PanelPart.openComposite (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/compositePart.js:43:25)
    at PanelPart.doOpenPanel (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:313:29)
    at PanelPart.onDidRegisterPanels (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:110:38)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:181:74
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:457:42)
    at PanelRegistry.registerComposite (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/composite.js:205:33)
    at PanelRegistry.registerPanel (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/panel.js:32:19)
    at ViewsService.registerPanel (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/views/viewsService.js:375:67)
    at ViewsService.registerViewletOrPanel (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/views/viewsService.js:331:30)
    at ViewsService.onDidRegisterViewContainer (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/views/viewsService.js:98:22)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/views/viewsService.js:38:89
    at Array.forEach (<anonymous>)
    at new ViewsService (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/views/viewsService.js:38:59)
    at InstantiationService._createInstance (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:88:20)
    at InstantiationService._createServiceInstance (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:177:29)
    at InstantiationService._createServiceInstanceWithOwner (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:165:29)
    at InstantiationService._createAndCacheServiceInstance (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:156:43)
    at InstantiationService._getOrCreateServiceInstance (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:113:29)
    at Object.get (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:36:45)
    at Workbench.initLayout (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/layout.js:146:22)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/browser/workbench.js:67:26
    at InstantiationService.invokeFunction (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:43:24)
    at Workbench.startup (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/workbench.js:61:38)
    at DesktopMain.open (file:///Users/isidor/Development/vscode/out/vs/workbench/electron-browser/desktop.main.js:61:52)
```

**Comment by bpasero** [comment]
I pinged @sandy081 too

**Comment by sandy081** [comment]
Caused by https://github.com/Microsoft/vscode/issues/97007
