### ISSUE TITLE
TS Server fatal error:  Debug Failure. Expected 2 === 4. Registered script kind should match new script kind. c:/users/****/projects/opened/rest_api_server/untitled:^untitled-1

### ISSUE THREAD

**Issue by EgorCloud** [microsoft/vscode#97061]
We have written the needed d**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. Expected 2 === 4. Registered script kind should match new script kind. c:/users/****/projects/opened/rest_api_server/untitled:^untitled-1
    at Object.assertEqual (c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2043:17)
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135295:34)
    at tryReuseStructureFromOldProgram (c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98176:28)
    at Object.createProgram (c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97765:30)
    at synchronizeHostData (c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135218:26)
    at Proxy.getProgram (c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135310:13)
    at InferredProject.Project.updateGraphWorker (c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:139786:53)
    at InferredProject.Project.updateGraph (c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:139729:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:141705:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143132:26)
    at c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143396:107
    at Object.mapDefined (c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144260:46)
    at c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145994:28)
    at IOSession.Session.executeCommand (c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146003:33)
    at IOSession.Session.onMessage (c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146027:35)
    at Interface.<anonymous> (c:\Users\****\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```ata into your clipboard because it was too large to send. Please paste.

**Comment by IllusionMH** [comment]
/needsMoreInfo

What are steps to reproduce this issue?

**Comment by EgorCloud** [comment]
created an undefined file. Change Language mode to TypeScript. Closed an undefined file

**Comment by mjbvz** [comment]
TS Server trace of the crash:

```
[Trace  - 04:19:59.138] <syntax> Sending request: updateOpen (6). Response expected: yes. Current queue length: 0
Arguments: {
    "changedFiles": [],
    "closedFiles": [],
    "openFiles": [
        {
            "file": "untitled:^Untitled-1",
            "fileContent": " f  ",
            "projectRootPath": "/Users/matb/projects/san",
            "scriptKindName": "TSX"
        }
    ]
}
[Trace  - 04:19:59.138] <semantic> Sending request: updateOpen (9). Response expected: yes. Current queue length: 0
Arguments: {
    "changedFiles": [],
    "closedFiles": [],
    "openFiles": [
        {
            "file": "untitled:^Untitled-1",
            "fileContent": " f  ",
            "projectRootPath": "/Users/matb/projects/san",
            "scriptKindName": "TSX"
        }
    ]
}
[Trace  - 04:19:59.140] <syntax> Response received: updateOpen (6). Request took 2 ms. Success: true 
Result: true
[Trace  - 04:19:59.143] <semantic> Response received: updateOpen (9). Request took 5 ms. Success: false . Message: Error processing request. Debug Failure. Expected 4 === 3. Registered script kind should match new script kind. /users/matb/projects/san/untitled:^untitled-1
Error: Debug Failure. Expected 4 === 3. Registered script kind should match new script kind. /users/matb/projects/san/untitled:^untitled-1
    at Object.assertEqual (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:2043:17)
    at getOrCreateSourceFileByPath (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:135295:34)
    at Object.getOrCreateSourceFile [as getSourceFile] (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:135253:24)
    at findSourceFile (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:99143:29)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:99005:77)
    at processSourceFile (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:99020:13)
    at processRootFile (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:98843:13)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:97809:60
    at Object.forEach (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:167:30)
    at Object.createProgram (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:97809:16)
    at synchronizeHostData (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:135218:26)
    at Proxy.getProgram (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:135310:13)
    at InferredProject.Project.updateGraphWorker (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:139786:53)
    at InferredProject.Project.updateGraph (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:139729:42)
    at ProjectService.assignOrphanScriptInfoToInferredProject (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:141705:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:143132:26)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:143396:107
    at Object.mapDefined (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:144260:46)
    at /Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:145994:28)
    at IOSession.Session.executeCommand (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:146003:33)
    at IOSession.Session.onMessage (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:146027:35)
    at Interface.<anonymous> (/Users/matb/projects/san/node_modules/typescript/lib/tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

And log file: [tsserver.log](https://github.com/microsoft/vscode/files/4714736/tsserver.log)
