### ISSUE TITLE
Capabilites for vscode.markwodn.preview.editor already set

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#97060]
VS Code out of source. Open a markdown file. Open multi root workspace. Notice error in dev console

```
ERR Capabilities for vscode.markdown.preview.editor already set: Error: Capabilities for vscode.markdown.preview.editor already set
    at CustomEditorService.registerCustomEditorCapabilities (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/customEditor/browser/customEditors.js:192:27)
    at MainThreadWebviews.registerEditorProvider (file:///Users/isidor/Development/vscode/out/vs/workbench/api/browser/mainThreadWebview.js:232:43)
    at MainThreadWebviews.$registerTextEditorProvider (file:///Users/isidor/Development/vscode/out/vs/workbench/api/browser/mainThreadWebview.js:223:22)
    at RPCProtocol._doInvokeHandler (file:///Users/isidor/Development/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:336:31)
    at RPCProtocol._invokeHandler (file:///Users/isidor/Development/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:321:49)
    at RPCProtocol._receiveRequest (file:///Users/isidor/Development/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:248:36)
    at RPCProtocol._receiveOneMessage (file:///Users/isidor/Development/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:176:30)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:66:56
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:457:42)
    at BufferedEmitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.net.js:362:35)
    at PersistentProtocol._receiveMessage (file:///Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.net.js:581:37)
    at file:///Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.net.js:455:83
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:457:42)
    at ProtocolReader.acceptChunk (file:///Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.net.js:188:37)
    at file:///Users/isidor/Development/vscode/out/vs/base/parts/ipc/common/ipc.net.js:157:61
    at Socket.listener (file:///Users/isidor/Development/vscode/out/vs/base/parts/ipc/node/ipc.net.js:17:40)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by isidorn** [comment]
I can still reproduce this with latest Out of Source.
@mjbvz did you try my steps, or am I missing something?

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/99053
Thus removing bug label so we do not verify
