### ISSUE TITLE
[rename on type] Language client is not ready yet

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#97062]
[2020-05-06 09:45:11.550] [renderer1] [error] Language client is not ready yet: Error: Language client is not ready yet
	at t.LanguageClient.sendRequest (/usr/share/code-insiders/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:42925)
	at Object.provideOnTypeRenameRanges (/usr/share/code-insiders/resources/app/extensions/html-language-features/client/dist/htmlMain.js:1:117024)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:666:459
	at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:51:988
	at new Promise (<anonymous>)
	at Object.t.asPromise (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:51:960)
	at k.provideOnTypeRenameRanges (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:666:430)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:690:71
	at e._withAdapter (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:685:862)
	at e.$provideOnTypeRenameRanges (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:690:49)
	at e._doInvokeHandler (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:788:757)
	at e._invokeHandler (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:788:449)
	at e._receiveRequest (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:787:69)
	at e._receiveOneMessage (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:970)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:784:213
	at e.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
	at v.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:232:615)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:957:179
	at e.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
	at v.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:232:615)
	at t.PersistentProtocol._receiveMessage (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:237:17)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:234:155
	at e.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
	at p.acceptChunk (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:230:129)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:229:483
	at Socket.t (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:238:565)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)

**Comment by connor4312** [comment]
@aeschli do you have verification steps for this?

**Comment by aeschli** [comment]
- enable the `"editor.renameOnType": true`
- open an HTML file, set the cursor on a tag and reload VSCode
- Check that there's no message in the dev console
