### ISSUE TITLE
Search: replaces first search result with a replace term

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#97120]
```
 1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Search
           replaces first search result with a replace term:
     Error: Timeout: get element '.search-view .messages[aria-hidden="true"] .message>span' after 20 seconds.
      at /Users/runner/runners/2.166.4/work/1/s/test/automation/out/code.js:174:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/runners/2.166.4/work/1/s/test/automation/out/code.js:9:58)

```

**Comment by sandy081** [comment]
I have not changed anything here recently so unassigning myself.
