### ISSUE TITLE
Build: integration test leading into renderer crash

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#97132]
The CI build on Windows hit the renderer crash during integration test run:

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=74277&view=logs&j=935a53e5-ce00-51d1-185d-b2f737723cea&t=a140d952-71c8-5ed6-fe55-f2b4c01d1569&l=477

This was luckily with the work included to create crash reports and the published artefacts are here: https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=74277&view=artifacts&type=publishedArtifacts

**Comment by bpasero** [comment]
This time I am seeing one on macOS and there is actually a native stack trace [1]

```
[9219:0601/120229.649495:INFO:CONSOLE(209)] "[uncaught exception]: Error: write EPIPE", source: /Users/runner/runners/2.169.0/work/1/s/out/bootstrap-window.js (209)
Error: async hook stack has become corrupted (actual: 7692, expected: 0)
[9219:0601/120229.649572:INFO:CONSOLE(212)] "Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:146:25)
    at writeGeneric (internal/stream_base_commons.js:137:3)
    at Socket._writeGeneric (net.js:698:11)
    at doWrite (_stream_writable.js:418:12)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at NodeSocket.write (file:///Users/runner/runners/2.169.0/work/1/s/out/vs/base/parts/ipc/node/ipc.net.js:45:25)
    at ProtocolWriter._writeNow (file:///Users/runner/runners/2.169.0/work/1/s/out/vs/base/parts/ipc/common/ipc.net.js:258:26)
    at Immediate.<anonymous> (file:///Users/runner/runners/2.169.0/work/1/s/out/vs/base/parts/ipc/common/ipc.net.js:250:26)
    at processImmediate (internal/timers.js:439:21)", source: /Users/runner/runners/2.169.0/work/1/s/out/bootstrap-window.js (212)
[9219:0601/120229.649646:INFO:CONSOLE(180)] "Uncaught Error: write EPIPE", source: events.js (180)
 1: 0x109c334b4 node::InternalCallbackScope::Close() [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x109c33369 node::InternalCallbackScope::Close() [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x109c33773 node::InternalCallbackScope::Close() [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x109c339a1 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x109c67075 node::EmitAsyncDestroy(node::Environment*, node::async_context) [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x109da1dcd uv_check_stop [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x109d9c529 uv_run [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x1044d91f1 AtomInitializeICUandStartNode [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x106700262 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
10: 0x106710274 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x106710747 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x10676dd63 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
13: 0x1066a88aa v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
14: 0x10676d6cf v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
15: 0x7fff34dd6a54 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
16: 0x7fff34dd69f3 __CFRunLoopDoSource0 [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
17: 0x7fff34dd680d __CFRunLoopDoSources0 [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
18: 0x7fff34dd5529 __CFRunLoopRun [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
19: 0x7fff34dd4b23 CFRunLoopRunSpecific [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
20: 0x7fff3748b2a8 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] [/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation]
21: 0x10676e271 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
22: 0x10676d098 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
23: 0x106710c28 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
24: 0x1066e4c27 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
25: 0x109aef600 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
26: 0x105da605c v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
27: 0x107ebc439 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
28: 0x104f4f384 AtomInitializeICUandStartNode [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
29: 0x1043973d4 AtomMain [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
30: 0x10434f3a5  [/Users/runner/runners/2.169.0/work/1/s/.build/electron/Code - OSS.app/Contents/Frameworks/Code - OSS Helper (Renderer).app/Contents/MacOS/Code - OSS Helper (Renderer)]
31: 0x7fff6edcfcc9 start [/usr/lib/system/libdyld.dylib]
[main 2020-06-01T12:02:29.678Z] [VS Code]: renderer process crashed!

```

[1] https://dev.azure.com/vscode/VSCode/_build/results?buildId=44827&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=a83823bd-5dbd-5313-d0d6-a425f162cca0&l=1013

**Comment by deepak1556** [comment]
Another run https://dev.azure.com/vscode/VSCode/_build/results?buildId=45542&view=results


The uncaught exception stack

```
[9219:0601/120229.649572:INFO:CONSOLE(212)] "Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:146:25)
    at writeGeneric (internal/stream_base_commons.js:137:3)
    at Socket._writeGeneric (net.js:698:11)
    at doWrite (_stream_writable.js:418:12)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at NodeSocket.write (file:///Users/runner/runners/2.169.0/work/1/s/out/vs/base/parts/ipc/node/ipc.net.js:45:25)
    at ProtocolWriter._writeNow (file:///Users/runner/runners/2.169.0/work/1/s/out/vs/base/parts/ipc/common/ipc.net.js:258:26)
    at Immediate.<anonymous> (file:///Users/runner/runners/2.169.0/work/1/s/out/vs/base/parts/ipc/common/ipc.net.js:250:26)
    at processImmediate (internal/timers.js:439:21)", source: /Users/runner/runners/2.169.0/work/1/s/out/bootstrap-window.js (212)
```

When write happens at [NodeSocker.write](https://github.com/microsoft/vscode/blob/master/src/vs/base/parts/ipc/node/ipc.net.ts#L60), we have a check `this.socket.destroyed` to avoid writing when the writable end is destroyed, but I don't think we are protecting against when the readable end has closed the pipe. Would be good to trace whats causing it.

Also it would be good if we setup an error handler on the socket https://nodejs.org/dist/latest-v12.x/docs/api/net.html#net_event_error_1 to avoid bringing down the renderer with uncaught exception.

/cc @jrieken

**Comment by bpasero** [comment]
@deepak1556 I can reliably reproduce this crash running out of sources. Steps:
* run `scripts/test-integration.sh`
* wait until the colorization tests are hit (look for e.g. `bat-test.bat`)
* hit `Ctrl+C` in the terminal to kill the process

Output:

```
 ✓ cpp-test.cc (293ms)
^CError: async hook stack has become corrupted (actual: 7622, expected: 0)
 1: 0x105afc384 node::InternalCallbackScope::Close() [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x105afc239 node::InternalCallbackScope::Close() [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x105afc643 node::InternalCallbackScope::Close() [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x105afc871 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
[48549:0609/102843.667675:INFO:CONSOLE(212)] "[uncaught exception]: Error: write EPIPE", source: /Users/bpasero/Development/Microsoft/monaco/out/bootstrap-window.js (212)
 5: 0x105b2ff45 node::EmitAsyncDestroy(node::Environment*, node::async_context) [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x105c6ac9d uv_check_stop [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
[48549:0609/102843.667731:INFO:CONSOLE(215)] "Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:146:25)
    at writeGeneric (internal/stream_base_commons.js:137:3)
    at Socket._writeGeneric (net.js:698:11)
    at Socket._write (net.js:710:8)
    at doWrite (_stream_writable.js:418:12)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at NodeSocket.write (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/node/ipc.net.js:45:25)
    at ProtocolWriter._writeNow (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:258:26)
    at Immediate.<anonymous> (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/base/parts/ipc/common/ipc.net.js:250:26)
    at processImmediate (internal/timers.js:439:21)", source: /Users/bpasero/Development/Microsoft/monaco/out/bootstrap-window.js (215)
 7: 0x105c653f9 uv_run [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 8: 0x1003a28f1 AtomInitializeICUandStartNode [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 9: 0x1025c9062 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
[48549:0609/102843.667984:INFO:CONSOLE(180)] "Uncaught Error: write EPIPE", source: events.js (180)
10: 0x1025d9074 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
11: 0x1025d9547 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x102636b63 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
13: 0x1025716aa v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
14: 0x1026364cf v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
15: 0x7fff336bcf12 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
16: 0x7fff336bceb1 __CFRunLoopDoSource0 [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
17: 0x7fff336bcccb __CFRunLoopDoSources0 [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
18: 0x7fff336bb9fa __CFRunLoopRun [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
19: 0x7fff336baffe CFRunLoopRunSpecific [/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation]
20: 0x7fff35d4f2a8 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] [/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation]
21: 0x102637071 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
22: 0x102635e98 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
23: 0x1025d9a28 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
24: 0x1025ada27 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
25: 0x1059b84d0 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
26: 0x101c6ee5c v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
27: 0x103d85239 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
28: 0x100e18a84 AtomInitializeICUandStartNode [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
29: 0x100260ad4 AtomMain [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
30: 0x1002183a5  [/Users/bpasero/Development/Microsoft/monaco/.build/electron/Code - OSS.app/Contents/Frameworks/Code - OSS Helper (Renderer).app/Contents/MacOS/Code - OSS Helper (Renderer)]
31: 0x7fff6d46acc9 start [/usr/lib/system/libdyld.dylib]
32: 0x1b 
[main 2020-06-09T08:28:43.688Z] [VS Code]: renderer process crashed!
```

**Comment by joaomoreno** [comment]
Just hit a new one here: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=80929&view=logs&j=935a53e5-ce00-51d1-185d-b2f737723cea&t=a140d952-71c8-5ed6-fe55-f2b4c01d1569

**Comment by jrieken** [comment]
@deepak1556 I don't understand what I should do here? Those stack traces show `write` but that's protected against destroyed streams.

**Comment by deepak1556** [comment]
Fixed by https://github.com/microsoft/vscode/pull/103122

**Comment by bpasero** [comment]
Awesome to see a fix for this ❤️
