### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by nhrones** [microsoft/vscode#97258]
**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1. copied new tsconfig.json 'content' to existing project

**TS Server Error Stack**
```
Error: Debug Failure.
    at assertDefined (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2077:24)
    at Object.assertEachDefined (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2084:17)
    at resolveModuleNamesWorker (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97713:155)
    at resolveModuleNamesReusingOldState (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98059:19)
    at processImportedModules (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99448:35)
    at findSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99191:17)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99418:21
    at Object.forEach (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99413:16)
    at findSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99188:21)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99418:21
    at Object.forEach (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99413:16)
    at findSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99188:21)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99418:21
    at Object.forEach (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99413:16)
    at findSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99188:21)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99418:21
    at Object.forEach (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99413:16)
    at findSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99188:21)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99418:21
    at Object.forEach (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99413:16)
    at findSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99188:21)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99418:21
    at Object.forEach (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99413:16)
    at findSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99188:21)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99418:21
    at Object.forEach (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99413:16)
    at findSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99188:21)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99418:21
    at Object.forEach (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99413:16)
    at findSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99188:21)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97809:60
    at Object.forEach (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at Object.createProgram (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97809:16)
    at synchronizeHostData (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135218:26)
    at Proxy.getProgram (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135310:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:139786:53)
    at ConfiguredProject.Project.updateGraph (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:139729:42)
    at ConfiguredProject.updateGraph (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:140654:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:142246:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143101:44)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143396:107
    at Object.mapDefined (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144260:46)
    at c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145994:28)
    at IOSession.Session.executeCommand (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146003:33)
    at IOSession.Session.onMessage (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146027:35)
    at Interface.<anonymous> (c:\Users\nhron\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
```We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by nhrones** [comment]
This was a problem in a unique situation.  I was building a node app that
built .d.ts files from WebIDL files.  I forgot to 'exclude' the folder that
received the new .d.ts files.
This created a very unstable TS environment.  Once I 'excluded' the output
folder in tsconfig.json, I could no longer reproduce this error.
Thanks for the quick reply.

**Comment by mjbvz** [comment]
Ok, let me know if you hit this again or if you have reliable steps to reproduce this.
