### ISSUE TITLE
Cant open specific jupyter notebook 

### ISSUE THREAD

**Issue by SwiftPredator** [microsoft/vscode#97309]
- VSCode Version: 1.45
- OS Version: MacOS 10.14.4

Steps to Reproduce:
 Hello,

yesterday my vscode and notebook worked fine. But today after the notebook crashed and i tried to stop the kernel, which failed duo timeout. I forced vscode to close. Now when i try to open the notebook, i get the following output from the verbose log:

[I 00:00:59.072 NotebookApp] Creating new notebook in /
[I 00:00:59.144 NotebookApp] Kernel started: 8341e7f8-8413-4f56-9323-0d6736c6e5b3
[I 00:01:04.098 NotebookApp] Creating new notebook in /
[I 00:01:04.123 NotebookApp] Kernel started: 95f0a119-21ad-4cca-81b0-87bff5a6cca6
[I 00:01:04.734 NotebookApp] Kernel shutdown: 8341e7f8-8413-4f56-9323-0d6736c6e5b3
[I 00:01:05.041 NotebookApp] Creating new notebook in /
[W 00:01:05.055 NotebookApp] Got events for closed stream None
 %c(at t (/Users/ironmonkeyapps/.vscode/extensions/ms-python.python-2020.4.76186/out/client/extension.js:1:6134)) color: blue color:  color: grey", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (259)
[4962:0509/000106.204110:INFO:CONSOLE(259)] "%c[Extension Host] %cInfo Python Extension: 2020-05-09 00:01:05: Web view react rendered %c(at t (/Users/ironmonkeyapps/.vscode/extensions/ms-python.python-2020.4.76186/out/client/extension.js:1:6134)) color: blue color:  color: grey", source: file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js (259)
[main 2020-05-08T22:01:09.074Z] [VS Code]: render process crashed!
[main 2020-05-08T22:01:09.333Z] telemetry/windowerror { type: 2 }

in VSCode a message pops up, which says the window crashed please reopen or close.
I can create a new jupyter notebook which works fine, but the one i try to open crashes every time.
I also can read that the crash comes basically from the python extension, but maybe someone has an idea how i can fix it or where i can get a solution for this. 

Thanks for your help.

Does this issue occur when all extensions are disabled?: Yes/No
No, but without the python extension i cant start a juypter notebook at all.

**Comment by SwiftPredator** [comment]
After reinstalling the python and extension and vscode it worked again.
