### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression: Script should not exist and not be open already

### ISSUE THREAD

**Issue by jahirvidrio** [microsoft/vscode#97371]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.7.5
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. False expression: Script should not exist and not be open already
    at ProjectService.applyChangesInOpenFiles (c:\Users\sergi\Documents\WebStorm\tecmm-app\node_modules\typescript\lib\tsserver.js:138420:34)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\sergi\Documents\WebStorm\tecmm-app\node_modules\typescript\lib\tsserver.js:139302:46)
    at c:\Users\sergi\Documents\WebStorm\tecmm-app\node_modules\typescript\lib\tsserver.js:140960:88
    at IOSession.Session.executeWithRequestId (c:\Users\sergi\Documents\WebStorm\tecmm-app\node_modules\typescript\lib\tsserver.js:140951:28)
    at IOSession.Session.executeCommand (c:\Users\sergi\Documents\WebStorm\tecmm-app\node_modules\typescript\lib\tsserver.js:140960:33)
    at IOSession.Session.onMessage (c:\Users\sergi\Documents\WebStorm\tecmm-app\node_modules\typescript\lib\tsserver.js:140983:35)
    at Interface.<anonymous> (c:\Users\sergi\Documents\WebStorm\tecmm-app\node_modules\typescript\lib\tsserver.js:142298:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A9-9410 RADEON R5, 5 COMPUTE CORES 2C+3G    (2 x 2895)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.45GB (4.64GB free)|
|Process Argv|C:\Users\sergi\Documents\WebStorm\tecmm|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.35.1
vscode-eslint|dba|2.1.5
lualinter|dcr|1.0.3
es7-react-js-snippets|dsz|2.7.1
EditorConfig|Edi|0.14.5
vscode-npm-script|eg2|0.3.11
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
auto-rename-tag|for|0.1.2
pwa-tools|joh|0.1.0
remote-wsl|ms-|0.44.2
cpptools|ms-|0.27.1
vsliveshare|ms-|1.0.2106
LiveServer|rit|5.6.1
editorconfig-gen|Ryu|0.0.2
svg-preview|Sim|2.8.3
lua|sum|0.16.3
vscode-arduino|vsc|0.3.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Do you see this issue when using TS 3.9+?
