### ISSUE TITLE
Unable to debug code

### ISSUE THREAD

**Issue by mrash14** [microsoft/vscode#97391]
Issue Type: <b>Bug</b>

Hi, after I update fedora and vscode, when I run debug trow an error in Developer Tool (console) and no more. now I cannot run my code. simple launch of django project. console error is:

ERR timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3061:355)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3060:679
    at async t.RawDebugSession.shutdown (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3058:772)

mrash14@gmail.com

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:10:24.511Z)
OS version: Linux x64 5.6.10-300.fc32.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2101)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.52GB (6.87GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|0.20.0
systemd-unit-file|coo|1.0.6
gitlens|eam|10.2.1
beautify|Hoo|1.5.0
rest-client|hum|0.23.2
dotenv|mik|1.0.1
python|ms-|2020.4.76186
azure-account|ms-|0.8.11
cpptools|ms-|0.27.1
team|ms-|1.161.0
sqltools|mtx|0.21.7
vscode-protolint|ple|0.3.0
vscodeintellicode|Vis|1.2.7
clang-format|xav|1.9.0
vscode-proto3|zxh|0.4.2

</details>

**Comment by mrash14** [comment]
problem resolved when I remove my Vitualenv and recreate it. if you show me the real error, it helps me to resolve this problem. The main problem is .so file puthonlib-3.7 is deleted in new fedora 32.
