### ISSUE TITLE
 Cannot read property 'templateData' of null

### ISSUE THREAD

**Issue by vscodeerrors** [microsoft/vscode#97452]
Issue Id: <b>68bafaaf-314b-72c5-33ee-e626d1c2161a</b><br /><br />*Versions* <br />- 1.45.0<br />-  d4b8ec9da3bf1061a948fbb1b0d9d3db750cc79f<br />-  ece7aaee861d7261a728d52ce436c667030ce17d<br />-  fd5d9a30259bb2bebab3e62dfd8315c2e1b27744<br />-  4bd206856db30c27d38aa0f1fbe74bac6156edc7<br />-  abb4a35cfc26102f93fd00df7b59ce1a19c2017a<br />-  a0fe37870c42e0704a492cdc6b8550b4cf23f63c<br />*Stack* <br />TypeError: Cannot read property 'templateData' of null<br />[/vs/base/browser/ui/list/listView.ts#743:58 (removeItemFromDOM)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/browser/ui/list/listView.ts#L743:58 (removeItemFromDOM))<br />[/vs/base/browser/ui/list/listView.ts#384:8 (_splice)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/browser/ui/list/listView.ts#L384:8 (_splice))<br />[/vs/base/browser/ui/list/listView.ts#371:15 (splice)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/browser/ui/list/listView.ts#L371:15 (splice))<br />[/vs/base/browser/ui/list/splice.ts#17:34](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/browser/ui/list/splice.ts#L17:34)<br />    at Array.forEach (<anonymous>)<br />[/vs/base/browser/ui/list/splice.ts#17:19 (splice)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/browser/ui/list/splice.ts#L17:19 (splice))<br />[/vs/base/browser/ui/list/listWidget.ts#1297:56 (fn)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/browser/ui/list/listWidget.ts#L1297:56 (fn))<br />[/vs/base/common/event.ts#819:12 (bufferEvents)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/common/event.ts#L819:12 (bufferEvents))<br />[/vs/base/browser/ui/list/listWidget.ts#1297:21 (splice)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/browser/ui/list/listWidget.ts#L1297:21 (splice))<br />[/vs/base/browser/ui/tree/abstractTree.ts#1178:8 (splice)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/browser/ui/tree/abstractTree.ts#L1178:8 (splice))<br />[/vs/base/browser/ui/tree/indexTreeModel.ts#337:12 (refilter)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/browser/ui/tree/indexTreeModel.ts#L337:12 (refilter))<br />[/vs/base/browser/ui/tree/objectTreeModel.ts#248:13 (refilter)](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/browser/ui/tree/objectTreeModel.ts#L248:13 (refilter))<br />[/vs/base/browser/ui/tree/abstractTree.ts#1551:13](https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/src/vs/base/browser/ui/tree/abstractTree.ts#L1551:13)<br />    at e.updateFilter (out/vs/workbench/<br />

**Comment by sandy081** [comment]
@joaomoreno Can you please help in shedding some light on when can this happen?

**Comment by joaomoreno** [comment]
@sandy081 I really don't know. Better yet would be to come up with a better error message which would drive us to the right place, do you have any suggestions?

**Comment by sandy081** [comment]
I really do not understand when can this happen.. 😞  but it seems to be triggered while updating the problems filter.

**Comment by kuroyuki** [comment]
Hi!
I've also got "Cannot read property 'templateData' of null: TypeError: Cannot read property 'templateData' of null" and Source Control on sidebar shows nothing. 
It happens all the time if I make any changes with sources.

Here is the VSCode output: 
```
abstractExtensionService.ts:415 [ms-vscode.powershell]: Command `workbench.action.debug.start` appears multiple times in the `commands` section.
abstractExtensionService.ts:415 [ms-vscode.powershell]: Command `workbench.action.closePanel` appears multiple times in the `commands` section.
abstractExtensionService.ts:415 [ms-vscode.powershell]: Command `workbench.action.positionPanelLeft` appears multiple times in the `commands` section.
abstractExtensionService.ts:415 [ms-vscode.powershell]: Command `workbench.action.positionPanelBottom` appears multiple times in the `commands` section.
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.swift.
Old grammar file: file:///c%3A/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/swift/syntaxes/swift.tmLanguage.json.
New grammar file: file:///c%3A/Users/User/.vscode/extensions/kasik96.swift-0.2.0/syntaxes/swift.tmLanguage
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///c%3A/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///c%3A/Users/User/.vscode/extensions/redhat.vscode-yaml-0.8.0/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:45
console.ts:137 [Extension Host] (node:9180) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:137
console.ts:137 [Extension Host] (node:9180) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:137
log.ts:197   ERR Cannot read property 'domNode' of null: TypeError: Cannot read property 'domNode' of null
    at E.updateItemInDOM (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:512:636)
    at E.render (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:510:905)
    at E.updateElementHeight (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:506:377)
    at O.updateElementHeight (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:547:655)
    at Object.updateElementHeight (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:119:927)
    at t.IndexTreeModel.updateElementHeight (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:104:685)
    at t.ObjectTreeModel.updateElementHeight (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:112:728)
    at c.updateElementHeight (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:118:686)
    at t.CompressibleObjectTreeModel.updateElementHeight (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:121:776)
    at B.updateElementHeight (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1112:242)
    at e.updateHeight (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7256:98)
    at a (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7229:214)
    at l (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7229:316)
    at e.renderElement (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7229:443)
    at c.renderElement (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1112:937)
    at x.renderElement (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1084:219)
    at W.renderElement (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:541:312)
    at E.insertItemInDOM (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:511:912)
    at E._splice (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:508:54)
    at E.splice (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:506:699)
    at file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:994
    at Array.forEach (<anonymous>)
    at t.CombinedSpliceable.splice (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:981)
    at file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:547:565
    at t.EventBufferer.bufferEvents (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:98:214)
    at O.splice (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:547:532)
    at O.splice (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1097:878)
    at Object.splice (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:119:868)
    at t.IndexTreeModel.splice (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:104:116)
    at t.ObjectTreeModel._setChildren (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:111:499)
    at t.ObjectTreeModel.setChildren (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:111:371)
    at c._setChildren (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:117:159)
    at c.setChildren (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:116:409)
    at t.CompressibleObjectTreeModel.setChildren (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:120:771)
    at B.setChildren (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1114:255)
    at Oe.refresh (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7241:820)
    at Oe._onDidSpliceRepositories (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7239:1004)
    at Oe.setVisible (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7240:984)
    at c.fire (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:821)
    at Ge.setVisible (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6387:92)
    at file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6405:328
    at Array.map (<anonymous>)
    at y.setVisible (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6405:319)
    at i.setVisible (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3903:24)
    at e.showComposite (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5753:975)
    at e.doOpenComposite (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5751:1007)
    at e.openComposite (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5751:539)
    at e.doOpenViewlet (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6346:900)
    at e.openViewlet (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6346:313)
    at e.run (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6178:913)
    at s.runAction (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:123:740)
    at s.run (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:123:598)
    at e.onClick (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:974:176)
    at Immediate._onImmediate (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:973:727)
    at processImmediate (internal/timers.js:439:21)
log.ts:197   ERR Cannot read property 'templateData' of null: TypeError: Cannot read property 'templateData' of null
    at E.removeItemFromDOM (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:513:504)
    at E._splice (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:506:964)
    at E.splice (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:506:699)
    at file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:994
    at Array.forEach (<anonymous>)
    at t.CombinedSpliceable.splice (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:30:981)
    at file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:547:565
    at t.EventBufferer.bufferEvents (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:98:214)
    at O.splice (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:547:532)
    at O.splice (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1097:878)
    at Object.splice (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:119:868)
    at t.IndexTreeModel.splice (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:104:116)
    at t.ObjectTreeModel._setChildren (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:111:499)
    at t.ObjectTreeModel.setChildren (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:111:371)
    at c._setChildren (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:117:159)
    at c.setChildren (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:116:409)
    at t.CompressibleObjectTreeModel.setChildren (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:120:771)
    at B.setChildren (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1114:255)
    at Oe.refresh (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7241:820)
    at Oe._onDidSpliceRepositories (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7239:1004)
    at Oe.setVisible (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:7241:531)
    at c.fire (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:821)
    at Ge.setVisible (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6387:92)
    at file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6405:328
    at Array.map (<anonymous>)
    at y.setVisible (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6405:319)
    at i.setVisible (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3903:24)
    at e.hideActiveComposite (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5755:399)
    at e.doOpenComposite (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5751:680)
    at e.openComposite (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5751:539)
    at e.doOpenViewlet (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6346:900)
    at e.openViewlet (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6346:313)
    at e.run (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6178:913)
    at s.runAction (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:123:740)
    at s.run (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:123:598)
    at e.onClick (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:974:176)
    at Immediate._onImmediate (file:///C:/Users/User/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:973:727)
    at processImmediate (internal/timers.js:439:21)
```

**Comment by joaomoreno** [comment]
@kuroyuki Your issue is https://github.com/microsoft/vscode/issues/102358

**Comment by richardtallent** [comment]
I don't know if this is related, but this error is coming up for me occasionally right after the Source Control tab goes blank (I have to restart VS Code to get my git stuff back).

**Comment by kuroyuki** [comment]
recently I've updated to 1.47.2 version and it looks like the problem gone: 
Source Control tab works fine

**Comment by sandy081** [comment]
Closing this because this error information is too old and have not seen this being reported.
