### ISSUE TITLE
Can't connect to the extensions Marketplace 

### ISSUE THREAD

**Issue by Astero-H** [microsoft/vscode#97484]
Issue Type: <b>Bug</b>

1- Launch Vs Code
2- Click on Tab Extensions
=> Message received : "We cannot connect to the Extensios Marketplace at this time, please try again later" 

N.B : I'm not behind a proxy - I re-installed VSCode

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by loganrosen** [comment]
For me it only happens when I'm in a certain workspace. When I open a regular window and am not in that workspace, I'm able to see extensions. Based on the error messages, it looks like it might have something to do with the workplace extension recommendation logic.

[Console log from Help -> Toggle Developer Tools -> Console](https://github.com/microsoft/vscode/files/4612433/console.log). Nothing from the second bullet.

Log (Window):
```
[2020-05-11 18:31:51.941] [renderer5] [error] Cannot read property 'important' of undefined: TypeError: Cannot read property 'important' of undefined
    at e.fetch (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6606:708)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async e.doActivate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6606:343)
    at async Promise.all (index 2)
    at async e.activateProactiveRecommendations (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6724:681)
[2020-05-11 18:31:55.772] [renderer5] [error] No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
[2020-05-11 18:32:58.679] [renderer5] [error] No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
[2020-05-11 18:33:09.043] [renderer5] [error] Cannot read property 'important' of undefined: TypeError: Cannot read property 'important' of undefined
    at e.fetch (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6606:708)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async e.doActivate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6606:343)
    at async Promise.all (index 2)
    at async e.activateProactiveRecommendations (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6724:681)
[2020-05-11 18:33:17.299] [renderer5] [error] Cannot read property 'important' of undefined: TypeError: Cannot read property 'important' of undefined
    at e.fetch (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6606:708)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async e.doActivate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6606:343)
    at async Promise.all (index 2)
    at async e.activateProactiveRecommendations (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6724:681)
[2020-05-11 18:33:19.361] [renderer5] [error] Cannot read property 'important' of undefined: TypeError: Cannot read property 'important' of undefined
    at e.fetch (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6606:708)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async e.doActivate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6606:343)
    at async Promise.all (index 2)
    at async e.activateProactiveRecommendations (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6724:681)
```

Log (Shared):
```
[2020-05-11 18:27:50.719] [sharedprocess] [info] main {"machineId":"6c9d2bc8f91b89624add29c0abeae7fb42bf539fa1cdb2e3e57cd668fa9bcead","windowId":2}
[2020-05-11 18:27:51.094] [sharedprocess] [info] Deleted from disk ms-vsliveshare.vsliveshare /Users/lrosen/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.2104
[2020-05-11 18:27:51.199] [sharedprocess] [info] Deleted from disk johnpapa.vscode-peacock /Users/lrosen/.vscode/extensions/johnpapa.vscode-peacock-3.7.0
[2020-05-11 18:27:51.204] [sharedprocess] [info] Deleted from disk esbenp.prettier-vscode /Users/lrosen/.vscode/extensions/esbenp.prettier-vscode-4.5.0
[2020-05-11 18:28:30.742] [sharedprocess] [info] Starting to clean up unused language packs.
```

**Comment by loganrosen** [comment]
The specific problematic line of code appears to be [here](https://github.com/microsoft/vscode/blob/5b33ba2a133459d7523dee5479d59049189f5234/src/vs/workbench/contrib/extensions/browser/configBasedRecommendations.ts#L57), at least for my case. cc @sandy081

**Comment by sandy081** [comment]
Fixed by 1b9cd97

**Comment by sandy081** [comment]
To repro/verify:

- Open a workspace that has `.git/config` that has remote other than `github.com`
- When such a workspace is opened, recommendations in the extensions viewlet shows this message.

**Comment by ravi0725** [comment]
@sandy081 
Hi Sandeep, I follow each and every step you mentioned in the above post and attaching the result for the same. 
I am also not able to download "Salesforce Extension Pack", getting error "We can not connect to extension market place this time". 
Please help me on this.

**Help -> Toggle Developer Tools -> Network**
![image](https://user-images.githubusercontent.com/26737364/84235012-cb7dc600-ab12-11ea-8c9c-dcd1e343ea2e.png)
**To confirm its a DNS issue check if you can access this page** https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default,

_**_Yes I am able to open the link and see the image._**_

**Help -> Toggle Developer Tools -> Console**
`Failed to load resource: net::ERR_TIMED_OUT
workbench.desktop.main.js:1642   ERR net::ERR_TIMED_OUT: Error: net::ERR_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2623:21)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TIMED_OUT
2workbench.desktop.main.js:6668 Error querying extensions gallery Canceled
(anonymous) @ workbench.desktop.main.js:6668
workbench.desktop.main.js:6668 Error querying extensions gallery XHR timeout: undefinedms
(anonymous) @ workbench.desktop.main.js:6668
marketplace.visualstudio.com/_apis/public/gallery/extensionquery:1 Failed to load resource: net::ERR_TIMED_OUT`

**View -> Command Pallette... -> Toggle Shared Process -> Console**
`2az764295.vo.msecnd.net/extensions/marketplace.json:1 Failed to load resource: net::ERR_TIMED_OUT`

**Log (shared)**
`[2020-06-10 11:50:32.933] [sharedprocess] [info] main {"machineId":"48fe33e62508cacf66f14a567d671e76e5f2563e2186c3f7681e1ce13e22add6","windowId":2}
[2020-06-10 11:51:13.033] [sharedprocess] [info] Starting to clean up unused language packs.
`

**log(window)**
`[2020-06-10 11:51:03.595] [renderer1] [error] net::ERR_TIMED_OUT: Error: net::ERR_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2623:21)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)`

Thanks

**Comment by ayeza-khan** [comment]
solution that work for me  
![Untitled](https://user-images.githubusercontent.com/65211526/85820760-68399800-b790-11ea-8902-36ec7dbf0618.png)
