### ISSUE TITLE
Error: LinkedMap got modified during iteration

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#97494]
* Run from sources:

```
ERR LinkedMap got modified during iteration.: Error: LinkedMap got modified during iteration.
    at LinkedMap.forEach (file:///Users/alex/src/vscode/out/vs/base/common/map.js:627:27)
    at EditorMemento.cleanUp (file:///Users/alex/src/vscode/out/vs/workbench/browser/parts/editor/baseEditor.js:237:19)
    at EditorMemento.saveState (file:///Users/alex/src/vscode/out/vs/workbench/browser/parts/editor/baseEditor.js:229:22)
    at file:///Users/alex/src/vscode/out/vs/workbench/browser/parts/editor/baseEditor.js:103:39
    at Map.forEach (<anonymous>)
    at NativeTextFileEditor.saveState (file:///Users/alex/src/vscode/out/vs/workbench/browser/parts/editor/baseEditor.js:101:44)
    at NativeTextFileEditor.saveState (file:///Users/alex/src/vscode/out/vs/workbench/contrib/files/browser/editors/textFileEditor.js:201:23)
    at file:///Users/alex/src/vscode/out/vs/workbench/common/component.js:17:22
    at Emitter.fire (file:///Users/alex/src/vscode/out/vs/base/common/event.js:457:42)
    at NativeStorageService.flush (file:///Users/alex/src/vscode/out/vs/platform/storage/node/storageService.js:163:39)
    at file:///Users/alex/src/vscode/out/vs/workbench/browser/workbench.js:154:32
    at Emitter.fire (file:///Users/alex/src/vscode/out/vs/base/common/event.js:457:42)
    at file:///Users/alex/src/vscode/out/vs/base/common/event.js:56:106
    at file:///Users/alex/src/vscode/out/vs/base/common/event.js:67:138
    at Emitter.fire (file:///Users/alex/src/vscode/out/vs/base/common/event.js:457:42)
    at file:///Users/alex/src/vscode/out/vs/base/common/event.js:44:93
    at Emitter.fire (file:///Users/alex/src/vscode/out/vs/base/common/event.js:457:42)
    at file:///Users/alex/src/vscode/out/vs/base/common/event.js:56:106
    at Emitter.fire (file:///Users/alex/src/vscode/out/vs/base/common/event.js:457:42)
    at handler (file:///Users/alex/src/vscode/out/vs/base/parts/ipc/common/ipc.js:393:46)
    at ChannelClient.onResponse (file:///Users/alex/src/vscode/out/vs/base/parts/ipc/common/ipc.js:444:17)
    at ChannelClient.onBuffer (file:///Users/alex/src/vscode/out/vs/base/parts/ipc/common/ipc.js:433:33)
    at file:///Users/alex/src/vscode/out/vs/base/parts/ipc/common/ipc.js:302:73
    at Emitter.fire (file:///Users/alex/src/vscode/out/vs/base/common/event.js:457:42)
    at EventEmitter.fn (file:///Users/alex/src/vscode/out/vs/base/common/event.js:257:44)
    at EventEmitter.emit (events.js:203:13)
    at Object.onMessage (electron/js2c/renderer_init.js:2422:16)
```

cc @dbaeumer

**Comment by bpasero** [comment]
@dbaeumer wanna take this? Looks like a similar issue to what you fixed here:

https://github.com/microsoft/vscode/blob/d3a10a33b3c73f34106bdd7513adb6ed2a431456/src/vs/workbench/browser/parts/editor/baseEditor.ts#L259-L260

**Comment by joaomoreno** [comment]
@bpasero @dbaeumer 

I just hit this in my Selfhost. I noticed since I tried opening the Git Output log and it was simply empty: there wasn't an editor rendered there. The bug was gone after reloading the window, so I can't repro.

**Comment by dbaeumer** [comment]
Fixed via https://github.com/microsoft/vscode/pull/97603.
