### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by salvadorcom3** [microsoft/vscode#97575]
**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at LineIndex.edit (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146547:30)
    at ScriptVersionCache._getSnapshot (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146376:47)
    at ScriptVersionCache.lineOffsetToPosition (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146395:29)
    at TextStorage.lineOffsetToPosition (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:138521:33)
    at ScriptInfo.lineOffsetToPosition (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:138867:41)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:144269:56
    at Object.next (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:579:33)
    at ProjectService.applyChangesToFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143416:46)
    at ProjectService.applyChangesInOpenFiles (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143383:30)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:144260:46)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:145994:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146003:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146027:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
