### ISSUE TITLE
Cant convert 'require' to 'import' in TS

### ISSUE THREAD

**Issue by Sardonyx78** [microsoft/vscode#97645]
- VSCode Version: 1.45.0
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Simply make a ts file and import anything by using CommonJS
2. Quick Fix > Convert all 'require' to 'import'

Does this issue occur when all extensions are disabled?: Yes/No
**Yes**

### Whole Error Stack
```
<semantic> TypeScript Server Error (3.8.3)
Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isIdentifier'.
Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isIdentifier'.
    at Object.cast (c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:1371:25)
    at getInfo (c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130213:95)
    at doChange (c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130203:22)
    at c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130200:134
    at c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124558:153
    at eachDiagnostic (c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124566:21)
    at c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124558:92
    at Function.ChangeTracker.with (c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123413:17)
    at Object.codeFixAll (c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124558:60)
    at Object.getAllCodeActions (c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130200:68)
    at Object.getAllFixes (c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124545:81)
    at Proxy.getCombinedCodeFix (c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135675:31)
    at IOSession.Session.getCombinedCodeFix (c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145760:56)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144516:61)
    at c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145994:28)
    at IOSession.Session.executeCommand (c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146003:33)
    at IOSession.Session.onMessage (c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146027:35)
    at Interface.<anonymous> (c:\Users\BoraC\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also, please share some example code

**Comment by Sardonyx78** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
> 
> Also, please share some example code

I dont use insiders and as I said:
> Does this issue occur when all extensions are disabled?: Yes/No
> Yes

a document with
```typescript
const REST = require('./Utils/REST.js');
const { EventEmitter } = require('events');
const GateWay = require('./WebSocket/WebSocket.js');
const Cocktail = require('./Utils/Cocktail.js');
``` 
will do the trick

**Comment by mjbvz** [comment]
Please test on insiders

**Comment by Sardonyx78** [comment]
Latest vs insiders has the same problem too

**Comment by mjbvz** [comment]
Thanks for testing. The conversion works for me with that snippet:

![May-13-2020 11-48-52](https://user-images.githubusercontent.com/12821956/81852374-c62b5c80-950f-11ea-9100-9856eead4ee7.gif)

I suspect the issue depends the rest of the file content (or the rest of your project). Please share a complete minimal project that causes this error
