### ISSUE TITLE
Fail to run new devcontainer

### ISSUE THREAD

**Issue by minjunsz** [microsoft/vscode#97668]
- VSCode Version: 1.45.0 (same on 1.46.0-insider)
- OS Version: Microsoft windows 10 Education 10.0.18362
- Docker Engine Version: 19.03.8
- Docker Desktop Version: 2.3.0.2

Steps to Reproduce:

1. I used "ms-vscode-remote.remote-containers" extension.
2. In the command palette, use "Remote-Containers: Open Folder in Container..."
3. Select any docker image (I used Alpine 3.10). Then Error occurred building the image.

I have used vscode with docker for few months. This error occurred after I updated my docker engine. I manually run docker container on my terminal and it works, so I thought this is a compatibility issue from vscode. Error messages are following.

Error: Unable to start terminal process: CreateProcess failed
        at new WindowsPtyAgent (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsPtyAgent.js:77:36)
        at new WindowsTerminal (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsTerminal.js:50:24)
        at Object.spawn (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\index.js:28:12)
        at c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:5211
        at async Object.t.runCommand (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:8512)
        at async c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:162431
        at async Object.t.openDockerfileDevContainer (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:162334)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by minjunsz** [comment]
If I manually run a docker container with -t option, I could attach my vscode successfully.
It seems like "remote-containers" extension failed to instantiate a new container with pseudo-TTY allocation.
I wonder whether I'd rather open this issue on a different repository.

**Comment by chrmarti** [comment]
/duplicate microsoft/vscode-remote-release#2975

Fixed with 0.117.1 of the Remote-Containers extension.
