### ISSUE TITLE
Error When Trying to Open VSCODE remote container

### ISSUE THREAD

**Issue by nidhinnyc** [microsoft/vscode#97677]
Issue Type: <b>Bug</b>

`[513 ms] Start: Run: docker build -f c:\Users\RYZEN\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\scripts\volumeBootstrap.Dockerfile -t vsc-volume-bootstrap c:\Users\RYZEN\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\scripts
[606 ms] Error: Unable to start terminal process: CreateProcess failed
        at new WindowsPtyAgent (c:\Users\RYZEN\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsPtyAgent.js:77:36)
        at new WindowsTerminal (c:\Users\RYZEN\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsTerminal.js:50:24)
        at Object.spawn (c:\Users\RYZEN\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\index.js:28:12)
        at c:\Users\RYZEN\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:5211
        at async Object.t.runCommand (c:\Users\RYZEN\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:8512)
        at async c:\Users\RYZEN\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:118726
        at async Object.D [as cloneAndBuildRepository] (c:\Users\RYZEN\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:118585)
        at async Object.t.openDockerfileRepoDevContainer (c:\Users\RYZEN\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:165567)`

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363
Fetching remote diagnostics for 'Dev Container' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'Dev Container' failed.
</details>Extensions: none

**Comment by chrmarti** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/2975

Fixed with 0.117.1 of the Remote-Containers extension.
