### ISSUE TITLE
Running Test Discovery with Pytest flapping  

### ISSUE THREAD

**Issue by erlichsefi** [microsoft/vscode#97747]
## Environment data

-   VS Code version: 1.44.0
-   Extension version (available under the Extensions sidebar):  2020.5.78807
-   OS and version: MACOS Mojave 10.14.6
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.10
-  Pytest version: 4.0.1 ( can't upgrade due to dependency )
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pyenv
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977):  Default
-   Value of the `python.languageServer` setting: Default

## Expected behaviour

Running discovery with pytest find all tests. 

## Actual behaviour

```
Running discovery flaps, sometimes the discovery fails and sometimes succeeds,
the error the keep repeating is a follows:

Test Discovery failed: 
 < remove trackback >
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "<my path> /.pyenv/virtualenv/lib/python3.6/site-packages/_pytest/main.py", line 181, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "<my path>/.pyenv/virtualenv/lib/python3.6/site-packages/_pytest/config/__init__.py", line 629, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "<my path>/.pyenv/virtualenv/lib/python3.6/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "<my path>/.pyenv/virtualenv/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File <my path>/.pyenv/virtualenv/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "<my path>/.pyenv/virtualenv/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "<my path>/.pyenv/virtualenv/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "<my path>/.pyenv/virtualenv/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<my path>/.pyenv/virtualenv/lib/python3.6/site-packages/_pytest/cacheprovider.py", line 313, in pytest_configure
INTERNALERROR>     config.cache = Cache.for_config(config)
INTERNALERROR>   File "<my path>/.pyenv/virtualenv/lib/python3.6/site-packages/_pytest/cacheprovider.py", line 47, in for_config
INTERNALERROR>     cachedir.mkdir()
INTERNALERROR>   File "<folder> /.pyenv/versions/3.6.10/lib/python3.6/pathlib.py", line 1248, in mkdir
INTERNALERROR>     self._accessor.mkdir(self, mode)
INTERNALERROR>   File "<folder>/.pyenv/versions/3.6.10/lib/python3.6/pathlib.py", line 387, in wrapped
INTERNALERROR>     return strfunc(str(pathobj), *args)
INTERNALERROR> FileExistsError: [Errno 17] File exists: '<my path>/.pytest_cache'

Traceback (most recent call last):
  File "<folder>/.vscode/extensions/ms-python.python-2020.5.78807/pythonFiles/testing_tools/run_adapter.py", line 22, in <module>
    main(tool, cmd, subargs, toolargs)
  File "<folder>/.vscode/extensions/ms-python.python-2020.5.78807/pythonFiles/testing_tools/adapter/__main__.py", line 100, in main
    parents, result = run(toolargs, **subargs)
  File "<folder>/.vscode/extensions/ms-python.python-2020.5.78807/pythonFiles/testing_tools/adapter/pytest/_discovery.py", line 44, in discover
    raise Exception("pytest discovery failed (exit code {})".format(ec))
Exception: pytest discovery failed (exit code 3)
  
```
## Steps to reproduce:

Create two folders ( folder1, folder2 ) and put in each one script with pytest cases, then set settings.json to:
```
{
    "python.pythonPath": "<env path >/.pyenv/virtualenv/bin/python3.6",
    "git.ignoreLimitWarning": true,
    "python.testing.pytestArgs": [
        "${workspaceFolder}/folder1",
       "${workspaceFolder}/folder2"
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.nosetestsEnabled": false,
    "python.testing.pytestEnabled": true,
    "terminal.integrated.env.osx": {
        "PYTHONPATH": "${env:PYTHONPATH}:${workspaceFolder}/"
    }
}
```

Is seems a mutual exclusion issue when multiple threads are trying to update `'<my path>/.pytest_cache'` since when I change the number of folders in  `"python.testing.pytestArgs"` in settings.json the problem stops and if there is more then a single folder waiting some time between clicking on discovery helps to reduce the number of discoveries I need to run until succeeding.

**Comment by alexdima** [comment]
This appears to be an issue with the python extension. Please create an issue directly against the extension at https://github.com/microsoft/vscode-python
