### ISSUE TITLE
TS Server fatal error:  Debug Failure.

### ISSUE THREAD

**Issue by debjava** [microsoft/vscode#97819]
After installing deno extension in VS Code, VS code is getting crashed. I got the exceptions to paste here.

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure.
    at assertDefined (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2077:24)
    at Object.assertEachDefined (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2084:17)
    at resolveModuleNamesWorker (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97713:155)
    at resolveModuleNamesReusingOldState (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98059:19)
    at processImportedModules (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99448:35)
    at findSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99191:17)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99418:21
    at Object.forEach (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99413:16)
    at findSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99188:21)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99418:21
    at Object.forEach (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99413:16)
    at findSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99188:21)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99418:21
    at Object.forEach (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99413:16)
    at findSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99188:21)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99418:21
    at Object.forEach (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99413:16)
    at findSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99188:21)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99418:21
    at Object.forEach (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99413:16)
    at findSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99188:21)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99418:21
    at Object.forEach (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99413:16)
    at findSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99188:21)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99418:21
    at Object.forEach (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99413:16)
    at findSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99188:21)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99418:21
    at Object.forEach (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at processLibReferenceDirectives (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99413:16)
    at findSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99188:21)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:85
    at getSourceFileFromReferenceWorker (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98987:34)
    at processSourceFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:99020:13)
    at processRootFile (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:98843:13)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97809:60
    at Object.forEach (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:167:30)
    at Object.createProgram (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:97809:16)
    at synchronizeHostData (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135218:26)
    at Proxy.getProgram (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135310:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:139786:53)
    at ConfiguredProject.Project.updateGraph (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:139729:42)
    at ConfiguredProject.updateGraph (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:140654:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:142246:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143101:44)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143396:107
    at Object.mapDefined (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144260:46)
    at c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145994:28)
    at IOSession.Session.executeCommand (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146003:33)
    at IOSession.Session.onMessage (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146027:35)
    at Interface.<anonymous> (c:\devsoftwares\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
```

**Comment by mjbvz** [comment]
Do you only see this when deno is installed?

**Comment by mjbvz** [comment]
Also, please test this in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)

**Comment by debjava** [comment]
> Do you only see this when deno is installed?

Yes, after installation of deno extension.
