### ISSUE TITLE
Smoke test failure on search

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#97837]
The latest 1.45.1 stable candidate consistently (3/3 attempts) fails with the following issue on smoketests:

```
 1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Search
           replaces first search result with a replace term:
     Error: Timeout: get text content '.search-view .messages' after 20 seconds.                                                                            
      at /home/connor/Documents/Github/vscode/test/automation/out/code.js:174:23                                                                            
      at Generator.next (<anonymous>)                                         
      at fulfilled (/home/connor/Documents/Github/vscode/test/automation/out/code.js:9:58)                                                                  
                       
```

State during the failure:

![](https://memes.peet.io/img/20-05-0d3d875d-f6a4-49d2-a546-bb8455a600ac.png)

```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-51-generic
```

**Comment by connor4312** [comment]
Indicated it's fixed in master.
