### ISSUE TITLE
Can not pull or push to User-Cert protected remote Git 

### ISSUE THREAD

**Issue by y-marion** [microsoft/vscode#97908]
# Issue Type: <b>Bug</b>

## Steps to reproduce

1. Have a git respitory which is hosted on a user cert protected environment
2. have an entry in the gitconfig file:
```[http "https://git.host.com/"]
	sslCert = "<path_to_folder>/crt.pem"
	sslKey = "<path_to_folder>/key.pem"
	sslCertPasswordProtected = true
```
3. try to push and pull
results in 
```
git pull --tags origin master
Missing or invalid credentials.
Error: Bad status code: 500
    at ClientRequest.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js:1:2250)
    at Object.onceWrapper (events.js:291:20)
    at ClientRequest.emit (events.js:203:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:575:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at Socket.socketOnData (_http_client.js:449:22)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
fatal: unable to access 'https://git.host.com/some/repo.git/': unable to set private key file: '<path_to_folder>/key.pem' type PEM
```
(v1.45.1)

```/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh: line 3: 81290 Trace/BPT trap: 5       VSCODE_GIT_ASKPASS_PIPE="$VSCODE_GIT_ASKPASS_PIPE" "$VSCODE_GIT_ASKPASS_NODE" "$VSCODE_GIT_ASKPASS_MAIN" $*
fatal: unable to access 'https://git.host.com/some/repo.git/': unable to set private key file: '<path_to_folder>/key.pem' type PEM
```
 (v1.44.2)

Prio to Version 1.44 this worked without a problem. It still works in a normal console, but it's rather tedious not to be able to do it from within vscode. 
I've tried restarting vscode without all extensions, but the error still persists.
If i downgrade to v1.43.2 it works again.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.57GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by y-marion** [comment]
Still happens with VSCode Version: 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
Git Version is 2.27.0

**Comment by y-marion** [comment]
This is fixed if Terminal Authentication for Extensions -> Git is set to false. Default is true.
Still weird why this was not an issue before version 1.44.
Should this issue be closed because of this? @joaomoreno

**Comment by joaomoreno** [comment]
Yes, if you use certificate authentication with HTTPS, you need to disable the Terminal Auth. 👍

**Comment by y-marion** [comment]
@joaomoreno Alright. But this is not documented and worked without this setting before 1.44. Furthermore, the visual GIT-Client (not in the integrated Terminal) still produces this error, even with the setting set to false.
This both worked prior to Version 1.44.x ...

**Comment by joaomoreno** [comment]
You can also disable the `github.gitAuthentication` setting and that should get the visual git client working again.

**Comment by y-marion** [comment]
> You can also disable the `github.gitAuthentication` setting and that should get the visual git client working again.

This does not seem to fix it. I still get the "Missing or invalid credentials" error (immediatly after trying to pull something), with the same error as above.

```Missing or invalid credentials.
Error: Bad status code: 500
    at ClientRequest.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js:1:2250)
    at Object.onceWrapper (events.js:291:20)
    at ClientRequest.emit (events.js:203:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:575:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at Socket.socketOnData (_http_client.js:449:22)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
fatal: unable to access 'https://git.host.com/some/repo.git/': unable to set private key file: '/<PATH_TO_FILE>/key.pem' type PEM```

**Comment by joaomoreno** [comment]
That's odd 🤔 Maybe `github.gitAuthentication` requires a VS Code restart? Does it work if you restart VS Code after changing that setting?

**Comment by y-marion** [comment]
> That's odd 🤔 Maybe `github.gitAuthentication` requires a VS Code restart? Does it work if you restart VS Code after changing that setting?

Sorry for the late reply @joaomoreno :
no, it doesn't change anything :( i still get the same error as above.
it doesn't bother me as much, as i'm not regularly using it
