### ISSUE TITLE
TS Server fatal error:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by MinhNguyenWre** [microsoft/vscode#97975]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
RangeError: Maximum call stack size exceeded
    at new URLSearchParams (internal/url.js:126:14)
    at URL.onParseComplete (internal/url.js:236:26)
    at parse (<anonymous>)
    at new URL (internal/url.js:319:5)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:14:21)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/remote_module_resolver.js:40:84)
    at Object.resolve (/Users/truongnguyen/.vscode/extensions/justjavac.vscode-deno-1.31.0/node_modules/typescript-deno-plugin/out/module_resolver/universal_module_resolver.js:11:66)
```

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|8.00GB (0.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.5
tsimportsorter|doz|2.0.7
gitlens|eam|10.2.1
prettier-vscode|esb|4.7.0
vscode-deno|jus|1.31.0
mongodb-vscode|mon|0.0.2
alphabetical-sorter|ue|2.0.1
vscode-icons|vsc|10.1.1
sort-js-object-keys|zen|1.0.6

</details>

**Comment by mjbvz** [comment]
Please file this against the deno extension
