### ISSUE TITLE
Unexpected: The specified task is missing an execution

### ISSUE THREAD

**Issue by badsyntax** [microsoft/vscode#98080]
- VSCode Version: 1.45.1
- OS Version: macos-10.15

Steps to Reproduce:

I can only reproduce this in CI (using [vscode-test](https://github.com/microsoft/vscode-test)), using Github Action ([macos-latest](https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md)).  I cannot reproduce using linux or windows. I also cannot reproduce on my MacOS 10.15 desktop machine.

I'm effectively doing:

```ts
vscode.tasks.executeTask(
  new vscode.Task(
    {
      type: 'tasktype',
    },
    'Task Name',
    'tasktype',
    new vscode.ShellExecution('./command')
  )
);
```

<details><summary>And I get this error & stack.</summary>

```
 Unexpected: The specified task is missing an execution: Error: Unexpected: The specified task is missing an execution
at e.getTaskExecution (/Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:863:72)
at e.$onDidStartTaskProcess (/Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:861:200)
at e._doInvokeHandler (/Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:788:757)
at e._invokeHandler (/Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:788:449)
at e._receiveRequest (/Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:787:120)

at e._receiveOneMessage (/Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:970)
at /Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:784:213
at e.fire (/Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
at v.fire (/Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:232:615)
at /Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:957:179
at e.fire (/Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
at v.fire (/Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:232:615)
at t.PersistentProtocol._receiveMessage (/Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:237:17)
at /Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:234:155
at e.fire (/Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
at p.acceptChunk (/Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:230:129)
at /Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:229:483
at Socket.t (/Users/runner/runners/2.262.1/work/vscode-gradle/vscode-gradle/extension/.vscode-test/vscode-1.45.1/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:238:565)
at Socket.emit (events.js:203:13)
at addChunk (_stream_readable.js:295:12)
at readableAddChunk (_stream_readable.js:276:11)
at Socket.Readable.push (_stream_readable.js:210:10)
at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```
</details>

I've tried a bunch of things to find the cause of this error, but have not had any luck. I don't understand how/why this error occurs, and I'm unable to catch it. Can you offer any advice and what I can do to debug this?

Does this issue occur when all extensions are disabled?: Yes

**Comment by badsyntax** [comment]
Hi @alexr00 

Unfortunately I'm seeing this race condition again. While the fix for https://github.com/microsoft/vscode/issues/96643 solved the race condition for the state of my code at that time, after moving some code around i'm seeing the race condition again.

Unfortunately I can't provide a repo because it's racy and it looks like it depends on the load on the machine, and will only show when the machine is under heavy load and running slowly. 

I can reliably reproduce this in [my CI](https://github.com/badsyntax/vscode-gradle/runs/771641892?check_suite_focus=true) and local (running tests on a [specific branch](https://github.com/badsyntax/vscode-gradle/tree/nested-projects) of my extension).

I have however recorded a video: https://i.imgur.com/8MzWs6T.mp4

This appears to be the sequence of events:

1. `$onDidStartTask` is called, which calls `getTaskExecution` passing in an execution object
2. `$onDidStartTaskProcess` is called, which calls `getTaskExecution` passing in execution as a string, but at this point the execution has not been saved to the `_taskExecution` map, so when it tries to get the task execution (string) from the `_taskExecution` map, it doesn't exist and throws an error.

**Comment by alexr00** [comment]
Thanks for all the details. The problem seems pretty clear, so I've pushed a fix. However, I can't repro the issue, so I can't verify it. Please let me know if the next insiders build still has this problem!

**Comment by badsyntax** [comment]
Sure will do! How can i check when the next insiders build will be released?

**Comment by alexr00** [comment]
The `unreleased` label on this issue will be removed when it's in the insiders build. That's probably the easiest way to check. Generally, they are released every 24ish hours.

**Comment by badsyntax** [comment]
It doesn't appear a new insiders was released in the past 24hrs. I'll check again tomorrow.

**Comment by badsyntax** [comment]
hi @alexr00 I have verified this change fixes the bug 🎉 

Using insiders, I'm no longer getting this error [in CI](https://github.com/badsyntax/vscode-gradle/actions/runs/138289430) nor in local. 

I'll continue to run my CI tests using insiders until 1.47.0 is released. Thanks!
