### ISSUE TITLE
Could not create web workers when running mocha tests

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#9836]
1. vscode repo, run mocha tests
2. notice the following warning:
`Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/Microsoft/monaco-editor#faq
Worker is not defined`

**Comment by jrieken** [comment]
@isidorn do you know more about this?

**Comment by isidorn** [comment]
@jrieken here's the stack trace, let me know if you need anything else

```
 at Object.logOnceWebWorkerWarning (/Users/isidor/Development/vscode/out/vs/base/common/worker/workerClient.js:12:23)
    at EditorWorkerClient._getOrCreateWorker (/Users/isidor/Development/vscode/out/vs/editor/common/services/editorWorkerServiceImpl.js:224:36)
    at EditorWorkerClient._getProxy (/Users/isidor/Development/vscode/out/vs/editor/common/services/editorWorkerServiceImpl.js:232:62)
    at EditorWorkerClient._withSyncedResources (/Users/isidor/Development/vscode/out/vs/editor/common/services/editorWorkerServiceImpl.js:246:25)
    at EditorWorkerClient.computeLinks (/Users/isidor/Development/vscode/out/vs/editor/common/services/editorWorkerServiceImpl.js:262:25)
    at /Users/isidor/Development/vscode/out/vs/editor/common/services/editorWorkerServiceImpl.js:36:138
    at CompletePromise_ctor.CompletePromise_then [as then] (/Users/isidor/Development/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)
    at Object.EditorWorkerServiceImpl._registration.modes_1.LinkProviderRegistry.register.provideLinks (/Users/isidor/Development/vscode/out/vs/editor/common/services/editorWorkerServiceImpl.js:36:99)
    at /Users/isidor/Development/vscode/out/vs/editor/contrib/links/common/links.js:11:77
    at /Users/isidor/Development/vscode/out/vs/base/common/async.js:27:24
    at new Promise_ctor (/Users/isidor/Development/vscode/out/vs/base/common/winjs.base.raw.js:1641:17)
    at Object.asWinJsPromise (/Users/isidor/Development/vscode/out/vs/base/common/async.js:26:16)
    at /Users/isidor/Development/vscode/out/vs/editor/contrib/links/common/links.js:11:28
    at Array.map (native)
    at getLinks (/Users/isidor/Development/vscode/out/vs/editor/contrib/links/common/links.js:10:78)
    at /Users/isidor/Development/vscode/out/vs/editor/contrib/links/common/links.js:66:16
    at TestInstantiationService.InstantiationService.invokeFunction (/Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:47:34)
    at Object.instantiationService.stub.executeCommand (/Users/isidor/Development/vscode/out/vs/workbench/test/node/api/extHostApiCommands.test.js:29:74)
    at MainThreadCommands.$executeCommand (/Users/isidor/Development/vscode/out/vs/workbench/api/node/mainThreadCommands.js:42:63)
    at /Users/isidor/Development/vscode/out/vs/workbench/test/node/api/testThreadService.js:73:49
    at Object.notifySuccess [as _notify] (/Users/isidor/Development/vscode/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.state_success_notify.enter (/Users/isidor/Development/vscode/out/vs/base/common/winjs.base.raw.js:852:30)
    at Promise_ctor._Base.Class.define._run (/Users/isidor/Development/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)
    at Promise_ctor._Base.Class.define._completed (/Users/isidor/Development/vscode/out/vs/base/common/winjs.base.raw.js:1036:18)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by jrieken** [comment]
@joaomoreno When running `./scripts/test.sh` don't we have a full browser environment?

**Comment by joaomoreno** [comment]
@jrieken Yeah the **integration** tests should be a full Electron env. The unit tests, on the other hand, are just Node with JSDom.
