### ISSUE TITLE
TS Server fatal error:  Cannot read property 'languageServiceRefCount' of undefined

### ISSUE THREAD

**Issue by nonameolsson** [microsoft/vscode#98369]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.5.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
TypeError: Cannot read property 'languageServiceRefCount' of undefined
    at releaseDocumentWithKey (/Users/andreasolsson/Code/Alterview.Opus/Client.Booking/node_modules/typescript/lib/tsserver.js:101869:13)
    at Object.releaseDocument (/Users/andreasolsson/Code/Alterview.Opus/Client.Booking/node_modules/typescript/lib/tsserver.js:101864:20)
    at /Users/andreasolsson/Code/Alterview.Opus/Client.Booking/node_modules/typescript/lib/tsserver.js:122070:45
    at Object.forEach (/Users/andreasolsson/Code/Alterview.Opus/Client.Booking/node_modules/typescript/lib/tsserver.js:292:30)
    at Proxy.dispose (/Users/andreasolsson/Code/Alterview.Opus/Client.Booking/node_modules/typescript/lib/tsserver.js:122069:20)
    at InferredProject.Project.close (/Users/andreasolsson/Code/Alterview.Opus/Client.Booking/node_modules/typescript/lib/tsserver.js:126088:38)
    at InferredProject.close (/Users/andreasolsson/Code/Alterview.Opus/Client.Booking/node_modules/typescript/lib/tsserver.js:126689:40)
    at ProjectService.removeProject (/Users/andreasolsson/Code/Alterview.Opus/Client.Booking/node_modules/typescript/lib/tsserver.js:127664:25)
    at ProjectService.cleanupAfterOpeningFile (/Users/andreasolsson/Code/Alterview.Opus/Client.Booking/node_modules/typescript/lib/tsserver.js:129060:30)
    at ProjectService.applyChangesInOpenFiles (/Users/andreasolsson/Code/Alterview.Opus/Client.Booking/node_modules/typescript/lib/tsserver.js:129241:22)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Users/andreasolsson/Code/Alterview.Opus/Client.Booking/node_modules/typescript/lib/tsserver.js:129980:46)
    at /Users/andreasolsson/Code/Alterview.Opus/Client.Booking/node_modules/typescript/lib/tsserver.js:131671:88
    at IOSession.Session.executeWithRequestId (/Users/andreasolsson/Code/Alterview.Opus/Client.Booking/node_modules/typescript/lib/tsserver.js:131662:28)
    at IOSession.Session.executeCommand (/Users/andreasolsson/Code/Alterview.Opus/Client.Booking/node_modules/typescript/lib/tsserver.js:131671:33)
    at IOSession.Session.onMessage (/Users/andreasolsson/Code/Alterview.Opus/Client.Booking/node_modules/typescript/lib/tsserver.js:131693:35)
    at Interface.<anonymous> (/Users/andreasolsson/Code/Alterview.Opus/Client.Booking/node_modules/typescript/lib/tsserver.js:132984:27)
    at Interface.emit (events.js:210:5)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
```

VS Code version: Code - Insiders 1.46.0-insider (da98a19a5d6724367bd99c8ec3b8f55054be37d1, 2020-05-20T23:28:34.587Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 8, 7|
|Memory (System)|16.00GB (1.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (69)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
codesnap|adp|1.0.27
project-manager|ale|11.0.1
i18n-ally|ant|2.2.0
codestream|Cod|7.2.5
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.1.3
vscode-markdownlint|Dav|0.35.2
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
es7-react-js-snippets|dsz|2.7.1
git-cheatsheet|dzh|1.1.1
gitlens|eam|10.2.1
EditorConfig|Edi|0.14.5
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
fold-imports|era|1.0.1
prettier-vscode|esb|4.7.0
file-icons|fil|1.0.24
docker-explorer|for|0.1.7
vscode-pull-request-github-insiders|Git|2020.5.28261
todo-tree|Gru|0.0.176
rest-client|hum|0.23.2
search-node-modules|jas|1.3.0
docthis|joe|0.7.1
vscode-styled-components|jpo|0.0.29
theme-karyfoundation-themes|kar|20.0.3
vscode-go-to-mdn|kby|1.1.1
kite|kit|0.114.0
pop-n-lock-theme-vscode|Lux|3.28.2
git-graph|mhu|1.22.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.15
azure-pipelines|ms-|1.170.0
vscode-docker|ms-|1.2.0
network-edge-devtools|ms-|1.0.0
vscode-edge-devtools|ms-|1.0.7
mssql|ms-|1.9.0
remote-containers|ms-|0.117.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.2
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.8.11
js-debug-companion|ms-|1.0.2
node-debug2|ms-|1.42.3
references-view|ms-|0.0.57
vsliveshare|ms-|1.0.2236
team|ms-|1.161.0
debugger-for-chrome|msj|4.12.8
debugger-for-edge|msj|1.0.14
vscode-react-native|msj|0.16.0
color-highlight|nau|2.3.0
vscode-jest|Ort|3.2.0
material-icon-theme|PKi|4.1.0
code-spell-checker|str|1.9.0
code-spell-checker-swedish|str|0.1.3
ayu|tea|0.18.0
git-rebase-shortcuts|tre|1.0.5
errorlens|use|3.1.1
vscodeintellicode|Vis|1.2.7
vscode-icons|vsc|10.1.1
quokka-vscode|Wal|1.0.290
vscode-todo-highlight|way|1.0.4
vscode-webhint|web|1.5.5
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|2.8.0
material-theme|zhu|3.7.0

(14 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
You are using an old TypeScript version. This should already be fixed in TS 3.9: https://github.com/microsoft/TypeScript/issues/37500
