### ISSUE TITLE
Open folder does not open folders

### ISSUE THREAD

**Issue by mrgirgin** [microsoft/vscode#98402]
- VSCode Version: 
1.45.1
5763d909d5f12fe19f215cbfdd29a91c0fa9208a
x64
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

1. Run `code .` on any directory. Alternative, Run code, and use the GUI to open a directory.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sliiser** [comment]
Running into the same issue. 100% reproducible with any folder with all extensions disabled.

Calling `code .` in the folder opens vscode, but there is no folder open. The outliner prompts to "Open Folder". Clicking it and choosing a folder does nothing. No change.

- VSCode version:
  1.45.1
  5763d909d5f12fe19f215cbfdd29a91c0fa9208a
  x64
- OS version: macOS Mojave 10.14.2 (18C54)


Errors from dev tools:
```bootstrap-window.js:209 [uncaught exception]: Error: ENOENT: no such file or directory, uv_cwd

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42:25)
    at process.cwd (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/graceful-fs/polyfills.js:10:19)
    at q.resolveSingleFolderWorkspaceInitializationPayload (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7233:171)
    at q.resolveWorkspaceInitializationPayload (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7232:563)
    at q.initServices (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7232:21)
    at q.open (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7229:715)
    at Object.t.main (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7234:444)
    at file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.js:8:763
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
onUnexpectedError @ bootstrap-window.js:209
(anonymous) @ bootstrap-window.js:52
emit @ events.js:203
./lib/renderer/init.ts.window.onerror @ init.ts:188
error (async)
(anonymous) @ init.ts:183
./lib/renderer/init.ts @ init.ts:232
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
NativeModule.compile @ internal/bootstrap/loaders.js:302
NativeModule.compileForPublicLoader @ internal/bootstrap/loaders.js:219
loadNativeModule @ internal/modules/cjs/helpers.js:23
Module._load @ internal/modules/cjs/loader.js:630
Module._load @ electron/js2c/asar.js:717
Module._load @ electron/js2c/asar.js:717
Module.runMain @ internal/modules/cjs/loader.js:944
(anonymous) @ internal/main/run_main_module.js:17
bootstrap-window.js:212 Error: ENOENT: no such file or directory, uv_cwd

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42)
    at process.cwd (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/graceful-fs/polyfills.js:10)
    at q.resolveSingleFolderWorkspaceInitializationPayload (desktop.main.ts:276)
    at q.resolveWorkspaceInitializationPayload (desktop.main.ts:253)
    at q.initServices (desktop.main.ts:217)
    at q.open (desktop.main.ts:111)
    at Object.t.main (desktop.main.ts:343)
    at workbench.js:33
    at processTicksAndRejections (internal/process/task_queues.js:85)
    at errors.ts:26
```

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/2259
