### ISSUE TITLE
preference sync - vscode insiders 

### ISSUE THREAD

**Issue by sarbbottam** [microsoft/vscode#98407]
- VSCode Version: 1.46.0-insider
- OS Version: Linux x64 4.19.98-08076-g24ab33fb8e14

```
Version: 1.46.0-insider
Commit: e1d8f5155c0db5ffdc130c9aa0f14efac02dfdfb
Date: 2020-05-13T18:15:00.101Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.19.98-08076-g24ab33fb8e14
```

Steps to Reproduce:

1. open Visual Studio Code Insiders
2. open command palette [ctrl + shift +p]
3. type preference
4. select "Preference Sync: Turn On... "
5. follow the instructions to turn on "Preference Sync"
6. Open Output Console [ctrl + k; ctrl + h]
7. Choose Log (Preference Sync) 

![Screenshot 2020-05-22 at 4 39 46 PM](https://user-images.githubusercontent.com/949380/82716208-24141e80-9c4b-11ea-8ffc-2820788fa949.png)

Does this issue occur when all extensions are disabled?: Yes ✅ 

```
[2020-05-22 16:31:46.916] [userDataSync] [info] Auto Sync: Started
[2020-05-22 16:31:47.430] [userDataSync] [info] Settings: No changes found during synchronizing settings.
[2020-05-22 16:31:47.469] [userDataSync] [info] Keybindings: No changes found during synchronizing keybindings.
[2020-05-22 16:31:47.471] [userDataSync] [info] Snippets: No changes found during synchronizing snippets.
[2020-05-22 16:31:47.474] [userDataSync] [info] GlobalState: Skipped removing commandPalette.mru.cache in remote storage. It is not registered to sync.
[2020-05-22 16:31:47.474] [userDataSync] [info] GlobalState: Skipped removing commandPalette.mru.counter in remote storage. It is not registered to sync.
[2020-05-22 16:31:47.476] [userDataSync] [info] GlobalState: No changes found during synchronizing ui state.
[2020-05-22 16:31:47.496] [userDataSync] [info] GlobalState: Updated last synchronized ui state
[2020-05-22 16:31:47.648] [userDataSync] [error] TypeError: t.map is not a function
    at Object.t.merge (file:///usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:405:288)
    at e.generatePreview (file:///usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:439:48)
    at async e.performSync (file:///usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:438:85)
    at async e.doSync (file:///usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:427:954)
    at async e.sync (file:///usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:426:431)
    at async e.sync (file:///usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:501:906)
    at async e.sync (file:///usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:488:596)
[2020-05-22 16:31:47.648] [userDataSync] [error] extensions: t.map is not a function
[2020-05-22 16:31:47.648] [userDataSync] [info] Sync done. Took 732ms
[2020-05-22 16:31:49.085] [userDataSync] [info] Auto Sync: Triggered.
[2020-05-22 16:31:49.160] [userDataSync] [info] Settings: No changes found during synchronizing settings.
[2020-05-22 16:31:49.164] [userDataSync] [info] Keybindings: No changes found during synchronizing keybindings.
[2020-05-22 16:31:49.167] [userDataSync] [info] Snippets: No changes found during synchronizing snippets.
[2020-05-22 16:31:49.171] [userDataSync] [info] GlobalState: Skipped removing commandPalette.mru.cache in remote storage. It is not registered to sync.
[2020-05-22 16:31:49.172] [userDataSync] [info] GlobalState: Skipped removing commandPalette.mru.counter in remote storage. It is not registered to sync.
[2020-05-22 16:31:49.172] [userDataSync] [info] GlobalState: No changes found during synchronizing ui state.
[2020-05-22 16:31:49.449] [userDataSync] [error] TypeError: t.map is not a function
    at Object.t.merge (file:///usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:405:288)
    at e.generatePreview (file:///usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:439:48)
    at async e.performSync (file:///usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:438:85)
    at async e.doSync (file:///usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:427:954)
    at async e.sync (file:///usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:426:431)
    at async e.sync (file:///usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:501:906)
    at async e.sync (file:///usr/share/code-insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:488:596)
[2020-05-22 16:31:49.449] [userDataSync] [error] extensions: t.map is not a function
[2020-05-22 16:31:49.449] [userDataSync] [info] Sync done. Took 364ms
```

**Comment by sarbbottam** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Settings sync asks to turn off without doing anything (#94174)](https://www.github.com/microsoft/vscode/issues/94174)
> * [TypeError: Cannot convert undefined or null to object  (#94175)](https://www.github.com/microsoft/vscode/issues/94175)

Verified, not duplicate of the ☝️

**Comment by sarbbottam** [comment]
Works fine Mac
```
Version: 1.46.0-insider
Commit: da98a19a5d6724367bd99c8ec3b8f55054be37d1
Date: 2020-05-20T23:28:34.587Z (2 days ago)
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 19.4.0
```

**Comment by sarbbottam** [comment]
Works fine in the 
```
Version: 1.46.0-insider
Commit: 2591ede95a52400d5d22989b16706f9b8b4831da
Date: 2020-05-22T21:12:53.428Z
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Linux x64 4.19.98-08076-g24ab33fb8e14
```
