### ISSUE TITLE
Wont start - javascript error

### ISSUE THREAD

**Issue by rsemenoff** [microsoft/vscode#98477]
- VSCode Version:1.45.0
- OS Version:Version	10.0.18363 Build 18363

Steps to Reproduce:

1.Start vscode

Does this issue occur when all extensions are disabled?: Yes/No
Cannot test
The following error message appears in a popup window, and from command line : 

C:\Users\Rwsin>code
Error: Cannot find module 'minimist'
Require stack:
- C:\Users\Rwsin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- C:\Users\Rwsin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at t.load (C:\Users\Rwsin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:119)
    at e.load (C:\Users\Rwsin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:13:586)
    at i (C:\Users\Rwsin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:29:189)
    at Object.errorback (C:\Users\Rwsin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:29:313)
    at e.triggerErrorback (C:\Users\Rwsin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:13:955)
    at C:\Users\Rwsin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:13:659
    at ReadFileContext.callback (C:\Users\Rwsin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:494)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Rwsin\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\bootstrap-amd.js',
    'C:\\Users\\Rwsin\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\cli.js'
  ],
  phase: 'loading',
  moduleId: 'minimist',
  neededBy: [ 'vs/platform/environment/node/argv' ]
}

**Comment by CMarshall92** [comment]
Have you attempted to clear the appdata folder for vs code?

**Comment by rsemenoff** [comment]
No, why would I do that?

**Comment by rsemenoff** [comment]
After clearing appdata and reinstalling, it works. But to reinstall I had to kill 3 zombie processes of vscode, which may have been the original problem. It seems to be back to normal minus all the extensions.

**Comment by kieferrm** [comment]
@rsemenoff it seems your installation was corrupted. Did the problem occur right after you restarted VS Code to apply an update?

**Comment by rsemenoff** [comment]
Ive been using vscode for 6 months but it stopped working after the most recent windows update . Thanks to cmarshall92 for the tip on reinstalling.  I might also mention that i have been editing files within wsl although that seems to have been working.  I also recently installed windirstat and have run a virus scan after using it once.

**Comment by rsemenoff** [comment]
Vscode itself never seems to update for me, maybe because im offline most of the time. This time I think the vscode update actually took place along with the windows update.
