### ISSUE TITLE
Unable to debug extensions in Insiders or master of VS Code

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#98638]
Version: 1.46.0-insider
- Commit: 876f2e70f9a2e1988887f8ca82294418afac15a2
- Date: 2020-05-27T05:41:02.088Z
- Electron: 7.2.4
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 19.4.0

Steps to Reproduce:

1. Download VS Code Python extension repo.
2. Build and start debugging.
3. Open a Python file
4. Python extension is expected to activate but never activates.
- Some times it gets activated after 5 minutes

**Some more issues related to debugging (if extension starts after 5 minutes):**
* Break points are not hit
* Stopping debugger doesn't work
* Stopping the launched VS Code instance doesn't stop the debugger. At this point VS Code is in a broken state, I cannot click stop on the debugger nor can I start debugging again (even with new configuration names).

Experienced same behaviour with VS Code Master.

Does this issue occur when all extensions are disabled?: Yes

[exthost-f2eefb.cpuprofile.txt](https://github.com/microsoft/vscode/files/4686943/exthost-f2eefb.cpuprofile.txt)
[exthost-ec7c17.cpuprofile.txt](https://github.com/microsoft/vscode/files/4686944/exthost-ec7c17.cpuprofile.txt)
[exthost-bbfcce.cpuprofile.txt](https://github.com/microsoft/vscode/files/4686945/exthost-bbfcce.cpuprofile.txt)
[exthost-0dd858.cpuprofile.txt](https://github.com/microsoft/vscode/files/4686946/exthost-0dd858.cpuprofile.txt)

<details>
<summary>Logs from console window (attaached the coresponding cpu profile files)
</summary>

```
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.log.
Old grammar file: file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/extensions/log/syntaxes/log.tmLanguage.json.
New grammar file: file:///Users/donjayamanne/.vscode-insiders/extensions/emilast.logfilehighlighter-2.8.0/syntaxes/log.tmLanguage
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.python.
Old grammar file: file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/extensions/python/syntaxes/MagicPython.tmLanguage.json.
New grammar file: file:///Users/donjayamanne/.vscode-insiders/extensions/magicstack.magicpython-1.1.0/grammars/MagicPython.tmLanguage
register @ TMScopeRegistry.ts:45
console.ts:137 [Extension Host] (node:12807) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:27:3))
t.log @ console.ts:137
console.ts:137 [Extension Host] (node:12807) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:27:3))
t.log @ console.ts:137
console.ts:137 [Extension Host] 2020-05-27T06:41:59.672Z - debug: [TypescriptHero] Setting up extension and activatables. (at ConsoleLogTransport.log (/Users/donjayamanne/.vscode-insiders/extensions/rbbit.typescript-hero-3.0.0/out/src/utilities/logger.js:45:25))
console.ts:137 [Extension Host] 2020-05-27T06:41:59.675Z - debug: [ImportOrganizer] Setting up ImportOrganizer. (at ConsoleLogTransport.log (/Users/donjayamanne/.vscode-insiders/extensions/rbbit.typescript-hero-3.0.0/out/src/utilities/logger.js:45:25))
console.ts:137 [Extension Host] 2020-05-27T06:41:59.676Z - debug: [TypescriptHero] Starting up extension and activatables. (at ConsoleLogTransport.log (/Users/donjayamanne/.vscode-insiders/extensions/rbbit.typescript-hero-3.0.0/out/src/utilities/logger.js:45:25))
console.ts:137 [Extension Host] 2020-05-27T06:41:59.676Z - info: [ImportOrganizer] Starting up ImportOrganizer. (at ConsoleLogTransport.log (/Users/donjayamanne/.vscode-insiders/extensions/rbbit.typescript-hero-3.0.0/out/src/utilities/logger.js:45:25))
console.ts:137 [Extension Host] [vscode-icons] v10.1.1 activated! (at /Users/donjayamanne/.vscode-insiders/extensions/vscode-icons-team.vscode-icons-10.1.1/dist/src/vscode-icons.bundle.js:9:199424)
log.ts:197   ERR timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3096:190)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3095:451
    at async t.RawDebugSession.shutdown (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3093:536)
extensionHost.ts:222 Extension Host
extensionHost.ts:223 Debugger attached.
extensionHost.ts:222 Extension Host
extensionHost.ts:223 Debugger attached.
log.ts:191  WARN UNRESPONSIVE extension host, 'ms-vscode.js-debug-nightly' took 99% of 5200.033ms, saved PROFILE here: '/var/folders/56/9h11nzxj6b78yvk72vsngk140000gn/T/exthost-0dd858.cpuprofile' Array(4)
api.github.com/search/issues?q=is:issue+state:open+in:title+repo:Microsoft/vscode-pwa+%22Extension+causes+high+cpu+load%22:1 Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
log.ts:197   ERR Server returned 422: Error: Server returned 422
    at Object.t.asText (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1863:16)
    at b (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3106:378)
    at async e._processCpuProfile (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5021:635)
log.ts:197   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
extensionHost.ts:222 Extension Host
extensionHost.ts:223 Debugger attached.
log.ts:191  WARN UNRESPONSIVE extension host, 'ms-vscode.js-debug-nightly' took 99% of 5155.553ms, saved PROFILE here: '/var/folders/56/9h11nzxj6b78yvk72vsngk140000gn/T/exthost-f2eefb.cpuprofile' (4) [{…}, {…}, {…}, {…}]
request.ts:40 GET https://api.github.com/search/issues?q=is:issue+state:open+in:title+repo:Microsoft/vscode-pwa+%22Extension+causes+high+cpu+load%22 422 (Unprocessable Entity)
(anonymous) @ request.ts:40
t.request @ request.ts:18
request @ requestService.ts:34
b @ extensionsSlowActions.ts:98
invokeFunction @ instantiationService.ts:61
_processCpuProfile @ extensionsAutoProfiler.ts:166
async function (async)
_processCpuProfile @ extensionsAutoProfiler.ts:133
_onDidChangeResponsiveChange @ extensionsAutoProfiler.ts:82
processTicksAndRejections @ internal/process/task_queues.js:85
async function (async)
_onDidChangeResponsiveChange @ extensionsAutoProfiler.ts:46
fire @ event.ts:589
(anonymous) @ abstractExtensionService.ts:138
fire @ event.ts:587
(anonymous) @ extensionHostProcessManager.ts:182
fire @ event.ts:587
_setResponsiveState @ rpcProtocol.ts:163
_checkUnresponsive @ rpcProtocol.ts:150
(anonymous) @ rpcProtocol.ts:104
doRun @ async.ts:651
onTimeout @ async.ts:645
setTimeout (async)
schedule @ async.ts:632
_checkUnresponsive @ rpcProtocol.ts:153
(anonymous) @ rpcProtocol.ts:104
doRun @ async.ts:651
onTimeout @ async.ts:645
setTimeout (async)
schedule @ async.ts:632
_checkUnresponsive @ rpcProtocol.ts:153
(anonymous) @ rpcProtocol.ts:104
doRun @ async.ts:651
onTimeout @ async.ts:645
setTimeout (async)
schedule @ async.ts:632
_onWillSendRequest @ rpcProtocol.ts:126
_remoteCall @ rpcProtocol.ts:436
t.<computed>.i.charCodeAt.t.<computed> @ rpcProtocol.ts:190
(anonymous) @ mainThreadDecorations.ts:52
setTimeout (async)
_processQueue @ mainThreadDecorations.ts:48
(anonymous) @ mainThreadDecorations.ts:34
enqueue @ mainThreadDecorations.ts:31
provideDecorations @ mainThreadDecorations.ts:92
_fetchData @ decorationsService.ts:277
(anonymous) @ decorationsService.ts:225
fire @ event.ts:587
$onDidChange @ mainThreadDecorations.ts:114
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
log.ts:197   ERR Server returned 422: Error: Server returned 422
    at Object.t.asText (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1863:16)
    at b (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3106:378)
    at async e._processCpuProfile (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5021:635)
extensionHost.ts:222 Extension Host
extensionHost.ts:223 Debugger attached.
log.ts:191  WARN UNRESPONSIVE extension host, 'ms-vscode.js-debug-nightly' took 99% of 5181.693ms, saved PROFILE here: '/var/folders/56/9h11nzxj6b78yvk72vsngk140000gn/T/exthost-bbfcce.cpuprofile' (4) [{…}, {…}, {…}, {…}]
request.ts:40 GET https://api.github.com/search/issues?q=is:issue+state:open+in:title+repo:Microsoft/vscode-pwa+%22Extension+causes+high+cpu+load%22 422 (Unprocessable Entity)
(anonymous) @ request.ts:40
t.request @ request.ts:18
request @ requestService.ts:34
b @ extensionsSlowActions.ts:98
invokeFunction @ instantiationService.ts:61
_processCpuProfile @ extensionsAutoProfiler.ts:166
async function (async)
_processCpuProfile @ extensionsAutoProfiler.ts:133
_onDidChangeResponsiveChange @ extensionsAutoProfiler.ts:82
processTicksAndRejections @ internal/process/task_queues.js:85
async function (async)
_onDidChangeResponsiveChange @ extensionsAutoProfiler.ts:46
fire @ event.ts:589
(anonymous) @ abstractExtensionService.ts:138
fire @ event.ts:587
(anonymous) @ extensionHostProcessManager.ts:182
fire @ event.ts:587
_setResponsiveState @ rpcProtocol.ts:163
_checkUnresponsive @ rpcProtocol.ts:150
(anonymous) @ rpcProtocol.ts:104
doRun @ async.ts:651
onTimeout @ async.ts:645
setTimeout (async)
schedule @ async.ts:632
_checkUnresponsive @ rpcProtocol.ts:153
(anonymous) @ rpcProtocol.ts:104
doRun @ async.ts:651
onTimeout @ async.ts:645
setTimeout (async)
schedule @ async.ts:632
_checkUnresponsive @ rpcProtocol.ts:153
(anonymous) @ rpcProtocol.ts:104
doRun @ async.ts:651
onTimeout @ async.ts:645
setTimeout (async)
schedule @ async.ts:632
_checkUnresponsive @ rpcProtocol.ts:153
(anonymous) @ rpcProtocol.ts:104
doRun @ async.ts:651
onTimeout @ async.ts:645
setTimeout (async)
schedule @ async.ts:632
_onWillSendRequest @ rpcProtocol.ts:126
_remoteCall @ rpcProtocol.ts:436
t.<computed>.i.charCodeAt.t.<computed> @ rpcProtocol.ts:190
_onDelta @ mainThreadDocumentsAndEditors.ts:407
(anonymous) @ mainThreadDocumentsAndEditors.ts:342
_updateStateOnModelAdd @ mainThreadDocumentsAndEditors.ts:213
fire @ event.ts:589
createModel @ modelServiceImpl.ts:484
doCreateTextEditorModel @ textEditorModel.ts:98
createTextEditorModel @ textEditorModel.ts:92
doCreateTextModel @ textFileEditorModel.ts:422
loadFromContent @ textFileEditorModel.ts:406
loadFromFile @ textFileEditorModel.ts:341
processTicksAndRejections @ internal/process/task_queues.js:85
log.ts:197   ERR Server returned 422: Error: Server returned 422
    at Object.t.asText (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1863:16)
    at b (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3106:378)
    at async e._processCpuProfile (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5021:635)
extensionHost.ts:222 Extension Host
extensionHost.ts:223 Debugger attached.
log.ts:191  WARN UNRESPONSIVE extension host, 'ms-vscode.js-debug-nightly' took 100% of 5166.411ms, saved PROFILE here: '/var/folders/56/9h11nzxj6b78yvk72vsngk140000gn/T/exthost-ec7c17.cpuprofile' (4) [{…}, {…}, {…}, {…}]
request.ts:40 GET https://api.github.com/search/issues?q=is:issue+state:open+in:title+repo:Microsoft/vscode-pwa+%22Extension+causes+high+cpu+load%22 422 (Unprocessable Entity)
(anonymous) @ request.ts:40
t.request @ request.ts:18
request @ requestService.ts:34
b @ extensionsSlowActions.ts:98
invokeFunction @ instantiationService.ts:61
_processCpuProfile @ extensionsAutoProfiler.ts:166
async function (async)
_processCpuProfile @ extensionsAutoProfiler.ts:133
_onDidChangeResponsiveChange @ extensionsAutoProfiler.ts:82
processTicksAndRejections @ internal/process/task_queues.js:85
async function (async)
_onDidChangeResponsiveChange @ extensionsAutoProfiler.ts:46
fire @ event.ts:589
(anonymous) @ abstractExtensionService.ts:138
fire @ event.ts:587
(anonymous) @ extensionHostProcessManager.ts:182
fire @ event.ts:587
_setResponsiveState @ rpcProtocol.ts:163
_checkUnresponsive @ rpcProtocol.ts:150
(anonymous) @ rpcProtocol.ts:104
doRun @ async.ts:651
onTimeout @ async.ts:645
setTimeout (async)
schedule @ async.ts:632
_checkUnresponsive @ rpcProtocol.ts:153
(anonymous) @ rpcProtocol.ts:104
doRun @ async.ts:651
onTimeout @ async.ts:645
setTimeout (async)
schedule @ async.ts:632
_checkUnresponsive @ rpcProtocol.ts:153
(anonymous) @ rpcProtocol.ts:104
doRun @ async.ts:651
onTimeout @ async.ts:645
setTimeout (async)
schedule @ async.ts:632
_onWillSendRequest @ rpcProtocol.ts:126
_remoteCall @ rpcProtocol.ts:436
t.<computed>.i.charCodeAt.t.<computed> @ rpcProtocol.ts:190
dispose @ mainThreadLanguageFeatures.ts:175
(anonymous) @ lifecycle.ts:119
clear @ lifecycle.ts:119
dispose @ lifecycle.ts:112
dispose @ codelens.ts:28
(anonymous) @ lifecycle.ts:119
clear @ lifecycle.ts:119
dispose @ lifecycle.ts:112
(anonymous) @ codelens.ts:113
setTimeout (async)
(anonymous) @ codelens.ts:113
processTicksAndRejections @ internal/process/task_queues.js:85
Promise.finally (async)
(anonymous) @ codelens.ts:110
(anonymous) @ editorExtensions.ts:277
invokeFunction @ instantiationService.ts:61
_tryExecuteCommand @ commandService.ts:84
(anonymous) @ commandService.ts:73
processTicksAndRejections @ internal/process/task_queues.js:85
Promise.then (async)
executeCommand @ commandService.ts:73
$executeCommand @ mainThreadCommands.ts:83
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
log.ts:197   ERR Server returned 422: Error: Server returned 422
    at Object.t.asText (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1863:16)
    at b (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3106:378)
    at async e._processCpuProfile (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5021:635)


```

</details>

<details>
<summary>Logs from console window (another instance)</summary>

```

abstractExtensionService.ts:485 Extension 'ms-python.python cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ abstractExtensionService.ts:485
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.log.
Old grammar file: file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/extensions/log/syntaxes/log.tmLanguage.json.
New grammar file: file:///Users/donjayamanne/.vscode-insiders/extensions/emilast.logfilehighlighter-2.8.0/syntaxes/log.tmLanguage
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.python.
Old grammar file: file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/extensions/python/syntaxes/MagicPython.tmLanguage.json.
New grammar file: file:///Users/donjayamanne/.vscode-insiders/extensions/magicstack.magicpython-1.1.0/grammars/MagicPython.tmLanguage
register @ TMScopeRegistry.ts:45
console.ts:137 [Extension Host] (node:6509) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:27:3))
t.log @ console.ts:137
console.ts:137 [Extension Host] (node:6509) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:27:3))
t.log @ console.ts:137
console.ts:137 [Extension Host] 2020-05-27T06:25:37.825Z - debug: [TypescriptHero] Setting up extension and activatables. (at ConsoleLogTransport.log (/Users/donjayamanne/.vscode-insiders/extensions/rbbit.typescript-hero-3.0.0/out/src/utilities/logger.js:45:25))
console.ts:137 [Extension Host] 2020-05-27T06:25:37.828Z - debug: [ImportOrganizer] Setting up ImportOrganizer. (at ConsoleLogTransport.log (/Users/donjayamanne/.vscode-insiders/extensions/rbbit.typescript-hero-3.0.0/out/src/utilities/logger.js:45:25))
console.ts:137 [Extension Host] 2020-05-27T06:25:37.829Z - debug: [TypescriptHero] Starting up extension and activatables. (at ConsoleLogTransport.log (/Users/donjayamanne/.vscode-insiders/extensions/rbbit.typescript-hero-3.0.0/out/src/utilities/logger.js:45:25))
console.ts:137 [Extension Host] 2020-05-27T06:25:37.830Z - info: [ImportOrganizer] Starting up ImportOrganizer. (at ConsoleLogTransport.log (/Users/donjayamanne/.vscode-insiders/extensions/rbbit.typescript-hero-3.0.0/out/src/utilities/logger.js:45:25))
console.ts:137 [Extension Host] [vscode-icons] v10.1.1 activated! (at /Users/donjayamanne/.vscode-insiders/extensions/vscode-icons-team.vscode-icons-10.1.1/dist/src/vscode-icons.bundle.js:9:199424)
log.ts:197   ERR timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3096:190)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3095:451
    at async t.RawDebugSession.shutdown (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3093:536)
extensionHost.ts:222 Extension Host
extensionHost.ts:223 Debugger attached.
log.ts:191  WARN UNRESPONSIVE extension host, 'ms-vscode.js-debug-nightly' took 99% of 5832.741ms, saved PROFILE here: '/var/folders/56/9h11nzxj6b78yvk72vsngk140000gn/T/exthost-af72f8.cpuprofile' Array(4)
api.github.com/search/issues?q=is:issue+state:open+in:title+repo:Microsoft/vscode-pwa+%22Extension+causes+high+cpu+load%22:1 Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
log.ts:197   ERR Server returned 422: Error: Server returned 422
    at Object.t.asText (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1863:16)
    at b (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3106:378)
    at async e._processCpuProfile (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5021:635)
extensionHost.ts:222 Extension Host
extensionHost.ts:223 Debugger attached.
log.ts:191  WARN UNRESPONSIVE extension host, 'ms-vscode.js-debug-nightly' took 99% of 5149.632ms, saved PROFILE here: '/var/folders/56/9h11nzxj6b78yvk72vsngk140000gn/T/exthost-e04a8d.cpuprofile' Array(4)
api.github.com/search/issues?q=is:issue+state:open+in:title+repo:Microsoft/vscode-pwa+%22Extension+causes+high+cpu+load%22:1 Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
log.ts:197   ERR Server returned 422: Error: Server returned 422
    at Object.t.asText (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1863:16)
    at b (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3106:378)
    at async e._processCpuProfile (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5021:635)
console.ts:137 [Extension Host] Error: Unexpected SIGPIPE	at process.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap.js:5:80)	at process.emit (events.js:203:13) (at process.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap.js:5:74))
t.log @ console.ts:137
console.ts:137 [Extension Host] Error: Unexpected SIGPIPE	at process.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap.js:5:80)	at process.emit (events.js:203:13) (at process.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap.js:5:74))
t.log @ console.ts:137
console.ts:137 [Extension Host] Error: Unexpected SIGPIPE	at process.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap.js:5:80)	at process.emit (events.js:203:13) (at process.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap.js:5:74))
t.log @ console.ts:137
console.ts:137 [Extension Host] Error: Unexpected SIGPIPE	at process.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap.js:5:80)	at process.emit (events.js:203:13) (at process.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap.js:5:74))
t.log @ console.ts:137
extensionHost.ts:222 Extension Host
extensionHost.ts:223 Debugger attached.
log.ts:197   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
log.ts:191  WARN UNRESPONSIVE extension host, 'ms-vscode.js-debug-nightly' took 99% of 5187.464ms, saved PROFILE here: '/var/folders/56/9h11nzxj6b78yvk72vsngk140000gn/T/exthost-86ff0f.cpuprofile' (4) [{…}, {…}, {…}, {…}]
request.ts:40 GET https://api.github.com/search/issues?q=is:issue+state:open+in:title+repo:Microsoft/vscode-pwa+%22Extension+causes+high+cpu+load%22 422 (Unprocessable Entity)
(anonymous) @ request.ts:40
t.request @ request.ts:18
request @ requestService.ts:34
b @ extensionsSlowActions.ts:98
invokeFunction @ instantiationService.ts:61
_processCpuProfile @ extensionsAutoProfiler.ts:166
async function (async)
_processCpuProfile @ extensionsAutoProfiler.ts:133
_onDidChangeResponsiveChange @ extensionsAutoProfiler.ts:82
processTicksAndRejections @ internal/process/task_queues.js:85
async function (async)
_onDidChangeResponsiveChange @ extensionsAutoProfiler.ts:82
log.ts:197   ERR Server returned 422: Error: Server returned 422
    at Object.t.asText (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1863:16)
    at b (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3106:378)
    at async e._processCpuProfile (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5021:635)

```

</details>

I have attached the CPU profile for `ms-vscode.js-debug-nightly`. Not sure this is what's causing the issues.

Also, the message `Note: Using the "preview" debug extension` appears in my `DEBUG CONSOLE`. I don't remember seeing this last week.

**Comment by connor4312** [comment]
Hi,

Can you please enable `trace: true` in your launch config and share the resulting log file here?

**Comment by DonJayamanne** [comment]
> debug.javavscript.usePreview

Awesome that's what I was looking for. I thought it gets set automatically when using the insider build,.

Will provide the rest of the info

**Comment by DonJayamanne** [comment]
* *Extension did not start even after 10 minutes.
* Unable to stop the debugger as well.

[console.log](https://github.com/microsoft/vscode/files/4690800/console.log)
[exthost-404c29.cpuprofile.txt](https://github.com/microsoft/vscode/files/4690801/exthost-404c29.cpuprofile.txt)
[exthost-933e3d.cpuprofile.txt](https://github.com/microsoft/vscode/files/4690802/exthost-933e3d.cpuprofile.txt)
[vscode-debugadapter-2.json.txt](https://github.com/microsoft/vscode/files/4690803/vscode-debugadapter-2.json.txt)
[vscode-debugadapter-3.json.txt](https://github.com/microsoft/vscode/files/4690804/vscode-debugadapter-3.json.txt)

**Comment by connor4312** [comment]
Thanks, one thing that jumps out at me is that it looks like we're scanning a bunch of node_modules; you have your outFiles set to 

```
[
  "/Users/donjayamanne/Desktop/Development/vsc/pythonVSCode/out/**/*"
]
```

and it looks like there's a path pythonVSCode/out/node_modules/.... Updating your outFiles to

```
[
  "/Users/donjayamanne/Desktop/Development/vsc/pythonVSCode/out/**/*",
  "!/Users/donjayamanne/Desktop/Development/vsc/pythonVSCode/out/node_modules**/*"
]
```

may resolve the issue for you

**Comment by DonJayamanne** [comment]
> In the meantime you can flip debug.javavscript.usePreview to opt-out of the new debug extension if it's a blocker.

Doesn't seem to work in Insiders version. Seems to always use the preview debug extension.

Anyway I can turn this off for insiders or master build of VS Code?

**Comment by DonJayamanne** [comment]
>  it looks like there's a path pythonVSCode/out/node_modules/.... Updating your outFiles to

Woo hoo, that worked. CLosing this issue as resolved.

**Comment by connor4312** [comment]
> Doesn't seem to work in Insiders version. Seems to always use the preview debug extension.

I realized I typo'd the option name above, it's `debug.javascript.usePreview` (for reference in case you need it again :) )

**Comment by DonJayamanne** [comment]
Oh yes, thats right. works well now. Thanks
