### ISSUE TITLE
Smoke test: install and activate vscode-smoketest-check extension

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98736]
I have not seen this test fail before, only now (https://dev.azure.com/monacotools/Monaco/_build/results?buildId=76620&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=05af1eac-c39c-5c75-1e3f-dd115ec8907d&l=79):

```
1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Extensions
           install and activate vscode-smoketest-check extension:
     Error: Timeout: get element '.extension-editor .monaco-action-bar .action-item:not(.disabled) .extension-action.uninstall' after 20 seconds.
      at /Users/runner/runners/2.168.2/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/runners/2.168.2/work/1/s/test/automation/out/code.js:9:58)

```

**Comment by IllusionMH** [comment]
Can it be related to #98726?

**Comment by sandy081** [comment]
/duplicate

You are absolutely correct.
