### ISSUE TITLE
Extensions won't install on latest build Mac OS

### ISSUE THREAD

**Issue by gajama** [microsoft/vscode#98747]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.46.0-insider (1d268b701376470bc638100fbe17d283404ac559, 2020-05-28T08:45:32.560Z)
OS version: Darwin x64 19.5.0

I think this may be related to #98737 which is on a Windows system

Edit: Just seen #98726 which is the same.

**What I'm trying to do:** Install an extension from the extension list. (markdown-lint in the logs below)

**What happens:** it fails with message suggesting I try manual install. I've tried numerious extensions with the same error and same messages in the logs. Manual install did work.

**What did I expect to happen:** the extension would install successfully.

**Things I tried:**

- Did a clean install of Code Insiders.

- Checked it was still working in release version of VS Code - it is.

- Gave VS Code Insiders app Full Disk Access permissions to see if that made any difference. It didn't

- Turned it off and on again.

- Also tried to switch to portable mode as per https://code.visualstudio.com/docs/editor/portable to see if that made any difference - it didn't. I'm not sure portable mode worked at all - it didn't seem to use the code-insiders-portable-data folder.

**Logs:**

- render1.log

```
[2020-05-28 16:59:30.083] [renderer1] [error] No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
[2020-05-28 17:00:42.340] [renderer1] [error] Cannot read property 'isDefault' of undefined: unknown: Cannot read property 'isDefault' of undefined
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:555:192
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

- main.log

```
[2020-05-28 16:59:30.073] [main] [error] [uncaught exception in main]: Error: No application in the Launch Services database matches the input criteria.
[2020-05-28 16:59:30.073] [main] [error] Error: No application in the Launch Services database matches the input criteria.
```

- sharedprocess.log

```
[2020-05-28 17:00:41.706] [sharedprocess] [info] Installing extension: davidanson.vscode-markdownlint
[2020-05-28 17:00:42.136] [sharedprocess] [info] Downloaded extension: davidanson.vscode-markdownlint /var/folders/zx/y9z8k95n2s912gqvs_ykkvw00000gn/T/9fcf5219-be95-4cf1-972b-75f60e8c0acc
[2020-05-28 17:00:42.153] [sharedprocess] [error] Failed to install extension: davidanson.vscode-markdownlint Cannot read property 'isDefault' of undefined
```

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gajama** [comment]
Duplicate of: #98726
