### ISSUE TITLE
I cannot refactor my code with VsCode it gives TypeScript server error(3.8.3) debug failiure

### ISSUE THREAD

**Issue by hanzlahabib** [microsoft/vscode#98784]
```
<semantic> TypeScript Server Error (3.8.3)
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at getPos (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123278:22)
    at assignPositionsToNode (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124064:27)
    at visitNode (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72887:23)
    at Object.visitEachChild (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:73104:117)
    at assignPositionsToNode (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124061:30)
    at visitNode (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72887:23)
    at Object.visitEachChild (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:73104:63)
    at assignPositionsToNode (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124061:30)
    at visitNode (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72887:23)
    at Object.visitEachChild (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:73104:63)
    at assignPositionsToNode (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124061:30)
    at visitNode (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72887:23)
    at Object.visitEachChild (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:73104:63)
    at assignPositionsToNode (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124061:30)
    at visitNode (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72887:23)
    at Object.visitEachChild (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:73142:46)
    at assignPositionsToNode (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124061:30)
    at visitNode (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72887:23)
    at Object.visitEachChild (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:73172:42)
    at assignPositionsToNode (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124061:30)
    at Object.visitNodes (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72938:48)
    at assignPositionsToNodeArray (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124069:30)
    at Object.visitEachChild (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:73166:45)
    at assignPositionsToNode (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124061:30)
    at visitNode (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72887:23)
    at visitFunctionBody (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:72991:23)
    at Object.visitEachChild (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:73204:464)
    at assignPositionsToNode (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124061:30)
    at getNonformattedText (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124045:56)
    at getFormattedTextOfNode (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124026:26)
    at format (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124009:52)
    at computeNewText (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124012:23)
    at c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123982:89
    at Array.map (<anonymous>)
    at c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123981:50
    at Array.map (<anonymous>)
    at Object.getTextChangesFromChanges (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123967:86)
    at ChangeTracker.getChanges (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:123935:45)
    at extractFunctionInScope (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131617:43)
    at getFunctionExtractionAtIndex (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131306:24)
    at Object.getEditsForAction (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130902:28)
    at Object.getEditsForRefactor (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:124598:41)
    at Proxy.getEditsForRefactor (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:135907:32)
    at IOSession.Session.getEditsForRefactor (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145708:59)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144531:61)
    at c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145994:28)
    at IOSession.Session.executeCommand (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146003:33)
    at IOSession.Session.onMessage (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146027:35)
    at Interface.<anonymous> (c:\Users\Sidra Riaz\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

- VSCode Version: 1.45.1 (user setup)
- OS Version: Windows_NT x64 10.0.18.362

Steps to Reproduce:

1. Select code which i want to extract/refactor
2. Press Cntl+Shift+R || right click and select refactor action

Does this issue occur when all extensions are disabled?: Yes
It fails after disabling extentions

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by hanzlahabib** [comment]
@mjbvz  i need to verify that is there difference in vs Code insider build? 
i already disabled my current extensions to test it but it still reproduces

**Comment by hanzlahabib** [comment]
@mjbvz  i have isntalled insider build, i was not able to reproduce same issue,

**Comment by mjbvz** [comment]
Thanks for testing. The insiders build includes a new TypeScript version which I suspect fixed this issue then. This TypeScript version should also ship with VS Code 1.46
