### ISSUE TITLE
TypeError: Cannot read property 'getRepositoryRoot' of null

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#9885]
HEAD, running out of workspace 

I see the following errors in the console.
```
[28049:0728/105243:INFO:CONSOLE(31)] "TypeError: Cannot read property 'getRepositoryRoot' of null
    at OpenInDiffAction.isEnabled (file:////home/aeschli/workspaces/vscode/out/vs/workbench/parts/git/browser/gitActions.contribution.js:47:52)
    at OpenInDiffAction.Object.defineProperty.set [as input] (file:////home/aeschli/workspaces/vscode/out/vs/workbench/browser/parts/editor/baseEditor.js:433:37)
    at file:////home/aeschli/workspaces/vscode/out/vs/workbench/browser/parts/editor/baseEditor.js:331:34
    at Array.forEach (native)
    at FileEditorActionContributor.EditorInputActionContributor.getActions (file:////home/aeschli/workspaces/vscode/out/vs/workbench/browser/parts/editor/baseEditor.js:330:31)
    at file:////home/aeschli/workspaces/vscode/out/vs/workbench/browser/actionBarRegistry.js:242:61
    at Array.forEach (native)
    at ActionBarRegistry.getActionBarActionsForContext (file:////home/aeschli/workspaces/vscode/out/vs/workbench/browser/actionBarRegistry.js:239:41)
    at TabsTitleControl.TitleControl.getEditorActionsForContext (file:////home/aeschli/workspaces/vscode/out/vs/workbench/browser/parts/editor/titleControl.js:221:77)
    at TabsTitleControl.TitleControl.getEditorActions (file:////home/aeschli/workspaces/vscode/out/vs/workbench/browser/parts/editor/titleCont
```

**Comment by joaomoreno** [comment]
Happens during shutdown.
