### ISSUE TITLE
Debugging tests don't start anymore

### ISSUE THREAD

**Issue by evowilliamson** [microsoft/vscode#98877]
- VSCode Version:1.45.1
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1.Start any project
2.Discover the tests
3.Click the lense "Debug test"

Does this issue occur when all extensions are disabled?: Yes/No
Tests are not discovered with this option

After discovering the tests, any test in any project have stopped working. I remember just before there was a message regarding runpy in the right lower corner, saying that it couldn't run and asked me to try with sudo. I clicked "yes". After this action, no tests can be debugged when I click the "Debug Test" lense, nothing happens. 

```
I have the following standard config:
        {
            "name": "Debug Tests",
            "type": "python",
            "request": "test",
            "console": "integratedTerminal",
            "justMyCode": false
        }    ]

```
I inspected the developer tools section and it throws the following error when I start a debug session through the lense or through a 

```
console.ts:137 [Extension Host] (node:10318) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
3
log.ts:197   ERR timeout after 1000 ms: Error: timeout after 1000 ms
    at t.RawDebugSession.handleErrorResponse (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3061:355)
    at file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3060:679
    at async t.RawDebugSession.shutdown (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3058:772)

```

**Comment by evowilliamson** [comment]
Will report with https://github.com/microsoft/vscode-python
