### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by OYaipen** [microsoft/vscode#98892]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. False expression.
    at ProjectService.applyChangesInOpenFiles (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143381:34)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:144260:46)
    at /usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:145994:28)
    at IOSession.Session.executeCommand (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146003:33)
    at IOSession.Session.onMessage (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146027:35)
    at Interface.<anonymous> (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.4.0-33-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|7.67GB (1.12GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
Bookmarks|ale|11.2.0
vscode-deno|axe|4.0.0
vscode-tailwindcss|bra|0.2.0
npm-intellisense|chr|1.3.0
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.1.4
systemd-unit-file|coo|1.0.6
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
gitlens|eam|10.2.1
EditorConfig|Edi|0.15.1
vsc-material-theme|Equ|32.6.0
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|4.7.0
auto-close-tag|for|0.5.7
auto-rename-tag|for|0.1.3
svg|joc|1.2.0
vscode-deno|jus|1.34.0
debugger-for-chrome|msj|4.12.8
color-highlight|nau|2.3.0
vetur|oct|0.24.0
material-icon-theme|PKi|4.1.0
vscode-css-peek|pra|3.0.2
vscode-graphql|Pri|0.2.14
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?
