### ISSUE TITLE
Yo code command gives error

### ISSUE THREAD

**Issue by manojmkv** [microsoft/vscode#98935]
- VSCode Version: 1.45.1
- OS Version: Windows 10

Steps to Reproduce:

1. After running npm install -g yo generator-code when I run second command: Yo code then it returns me below error:

C:\development\ScriptMigration\VSCodeExtension>yo code

     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to the Visual  │
    |--(o)--|    │   Studio Code Extension  │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Error: Promise rejected with value: {
  responseText: 'Unable to connect to https://vscode-update.azurewebsites.net/api/releases/stable. Error: unable to get local issuer certificate',
  status: 404
}
    at C:\Users\vermam\AppData\Roaming\npm\node_modules\yo\node_modules\loud-rejection\index.js:27:12
    at Array.forEach (<anonymous>)
    at EventEmitter.<anonymous> (C:\Users\vermam\AppData\Roaming\npm\node_modules\yo\node_modules\loud-rejection\index.js:23:24)
    at EventEmitter.emit (events.js:311:20)
    at EventEmitter.emit (domain.js:482:12)
    at emit (C:\Users\vermam\AppData\Roaming\npm\node_modules\yo\node_modules\signal-exit\index.js:78:11)
    at processEmit [as emit] (C:\Users\vermam\AppData\Roaming\npm\node_modules\yo\node_modules\signal-exit\index.js:156:5)
    at process.topLevelDomainCallback (domain.js:137:15)

Does this issue occur when all extensions are disabled?: Yes/No: I dint check this.

**Comment by egamma** [comment]
/needsMoreInfo

>when I run second command

What is the command you are running, please provide detailed information about the executed commands.

Can you still reproduce this today?

**Comment by manojmkv** [comment]
@egamma  I installed yo generator-code  globally then I am running command: yo code. for this command I am getting below error :
C:\development\ScriptMigration\development\UtilityRelated>yo code

     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to the Visual  │
    |--(o)--|    │   Studio Code Extension  │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Error: Promise rejected with value: {
  responseText: 'Unable to connect to https://vscode-update.azurewebsites.net/api/releases/stable. Error: unable to get local issuer certificate',
  status: 404
}
    at C:\Users\vermam\AppData\Roaming\npm\node_modules\yo\node_modules\loud-rejection\index.js:27:12
    at Array.forEach (<anonymous>)
    at EventEmitter.<anonymous> (C:\Users\vermam\AppData\Roaming\npm\node_modules\yo\node_modules\loud-rejection\index.js:23:24)
    at EventEmitter.emit (events.js:311:20)
    at EventEmitter.emit (domain.js:482:12)
    at emit (C:\Users\vermam\AppData\Roaming\npm\node_modules\yo\node_modules\signal-exit\index.js:78:11)
    at processEmit [as emit] (C:\Users\vermam\AppData\Roaming\npm\node_modules\yo\node_modules\signal-exit\index.js:156:5)
    at process.topLevelDomainCallback (domain.js:137:15)

Let me know if you need any further details.

**Comment by egamma** [comment]
@mnovakovic could you use `yo code` before and it stopped working? Are you behind a proxy?

see also https://github.com/microsoft/vscode/issues/92388

**Comment by manojmkv** [comment]
I am using it first time. I have setup proxy "http.proxyStrictSSL": false.
