### ISSUE TITLE
Capabilities for vscode.markdown.preview.editor already set

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#99053]
Got this in the developer console while using vscode insiders. I do not have exact steps but I hope the stack trace is useful enough.

```
 ERR Capabilities for vscode.markdown.preview.editor already set: Error: Capabilities for vscode.markdown.preview.editor already set
    at e.registerCustomEditorCapabilities (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5578:391)
    at e.registerEditorProvider (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6369:566)
    at e.$registerTextEditorProvider (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6369:248)
    at e._doInvokeHandler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4532:683)
    at e._invokeHandler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4532:375)
    at e._receiveRequest (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4531:14)
    at e._receiveOneMessage (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4529:832)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4528:34
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at v.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:433:97)
    at t.PersistentProtocol._receiveMessage (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:437:451)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:434:635
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at g.acceptChunk (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:430:532)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:429:832
    at Socket.t (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:439:12)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by mjbvz** [comment]
I can repro:

1. Start with a single folder
1. Open a markdown file
1. Then add a folder to the workspace

**Comment by mjbvz** [comment]
This is caused by the fact that when we restart the extension host in this case, we  don't call `dispose` or dispose of the extension's subscriptions. Webview's currently rely on this.

Will investigate this for June

**Comment by mjbvz** [comment]
@alexdima Is there any way to either:

- Ensure that certain disposables are cleaned up when the extension host restarts?
- Detect that the extension host has restarted?

**Comment by alexdima** [comment]
@mjbvz The extension host can crash at any time and VS Code should function normally after an extension restart. The architecture is built to support this and the way to do so is to place all extension host related disposables in `mainThread*` actors. So basically `MainThreadWebviews` will be disposed when the extension host goes down (regardless of reason). That is the place to clean up all state in the workbench associated to that particular extension host instance.

**Comment by mjbvz** [comment]
Thanks @alexdima! I was able to use that to fix this issue
