### ISSUE TITLE
smoke: notebook prints timeout

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#99112]
Testing #99012
Ubuntu 18.04

From master:
- uncomment all other smoke tests in test/smoke/src/main.ts
- `yarn smoketest`

Running the notebook tests prints the following error:
```
  VSCode Smoke Tests (Electron)
    VSCode Smoke Tests (Electron)
      Notebooks
        ✓ inserts/edits code cell
        ✓ inserts/edits markdown cell
        ✓ moves focus as it inserts/deletes a cell
** Timeout!
Error: Active element not found. Current active element is 'HTML > BODY.linux > DIV.monaco-workbench.linux.chromium.nopanel.file-icons-enabled.vs-dark.vscode-theme-defaults-themes-dark_plus-json > DIV.monaco-grid-view > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.vertical > DIV.split-view-container > DIV.split-view-view.visible > DIV.monaco-grid-branch-node > DIV.monaco-split-view2.horizontal > DIV.split-view-container > DIV.split-view-view.visible > DIV#workbench.parts.activitybar.part.activitybar.left > DIV.content > DIV.composite-bar > DIV.monaco-action-bar.vertical > UL.actions-container > LI.action-item.checked'. Looking for .quick-input-widget .quick-input-box input
    at WindowDriver.isActiveElement (file:///home/martin/workspaces/vscode/out/vs/platform/driver/browser/baseDriver.js:63:23)
    at WindowDriverChannel.call (file:///home/martin/workspaces/vscode/out/vs/platform/driver/node/driver.js:130:60)
    at ChannelServer.onPromise (file:///home/martin/workspaces/vscode/out/vs/base/parts/ipc/common/ipc.js:203:35)
    at ChannelServer.onRawMessage (file:///home/martin/workspaces/vscode/out/vs/base/parts/ipc/common/ipc.js:185:33)
    at file:///home/martin/workspaces/vscode/out/vs/base/parts/ipc/common/ipc.js:145:73
    at Emitter.fire (file:///home/martin/workspaces/vscode/out/vs/base/common/event.js:457:42)
    at EventEmitter.fn (file:///home/martin/workspaces/vscode/out/vs/base/common/event.js:257:44)
    at EventEmitter.emit (events.js:203:13)
    at Object.onMessage (electron/js2c/renderer_init.js:2422:16)
        ✓ moves focus in and out of output
```

Still, the tests seem to pass

**Comment by aeschli** [comment]
Also the error does not show when running against `--build`

**Comment by roblourens** [comment]
I didn't see this today but I think I have seen this kind of thing before and I'll look at it again in debt week.

**Comment by roblourens** [comment]
Lots of changes since then, can't repro
