### ISSUE TITLE
Connecting to remote Codespace partially works but resolver status stays on "Opening remote" and extensions are not visible

### ISSUE THREAD

**Issue by jkeech** [microsoft/vscode#99202]
- VSCode Version: 1.45.1
- OS Version: macOS Catalina 10.15.4

Steps to Reproduce:

1. Issue reported at https://github.com/MicrosoftDocs/vsonline/issues/455
2. User created a Codespace from VS Code desktop, and after creation, clicked "Connect"
3. Connection succeeded and files showed up in the file explorer
4. Remote explorer viewlet does not show up in the activity bar, but the Codespaces extension did activate because the Creation Log webview showed up. No extensions show up in the installed extensions viewlet.
5. Bottom left corner still shows "Opening remote..."

Does this issue occur when all extensions are disabled?: I don't think so, because it requires the Codespaces extension in order to connect.

**Comment by alexdima** [comment]
@jkeech I have read through MicrosoftDocs/vsonline#455 but I have to say that it contains basically 0 information. AFAICT the steps are to connect to a specific codespace that always fails from the desktop.

It is not clear to me if this is a problem with:
* the desktop side of things (e.g. old extension version, patched VS Code installation on disk)
* the server side of things (e.g. large workspace where the file watcher consumes a lot of RAM which might prohibit the extension host connection from going through) -- this is unlikely since the web client is reported to be OK.
* the connection (e.g. bad firewall rule which always blocks any outgoing request) -- this is IMHO very likely

I am really sorry, but I have no idea what is wrong given the lack of steps / information, it can basically be anything.

**Comment by jkeech** [comment]
Do you know how it would be possible for the connection to the remote server to be established (file explorer populates, etc) but the resolver still says "Opening remote"? In a video that the user sent me privately, it also shows that the extensions do not show up in the activity bar or the extensions viewlet. I'm not sure how to investigate this partial success failure mode. If it was a firewall issue, I would expect the whole connection to be blocked.

**Comment by alexdima** [comment]
VS Code establishes two connections to the remote machine:
- one that we call the management connection: this one is responsible for FS operations, extension management (installing/uninstalling), extension scanning on disk.
- one that we call the extension host connection: this one works by spawning an extension host process on the remote machine and is basically the communication to the extension host.

From what you are describing, the second one fails. It is possible that the server fails to spawn the extension host (unlikely since that also happens in the web ui case) or that the desktop resolver has some kind of issue and the connection does not go through.

**Comment by jkeech** [comment]
@alexdima, another Codespaces user reported this issue at https://github.com/MicrosoftDocs/vsonline/issues/499#issuecomment-640905863

The renderer logs have an error that looks suspicious (pasted below). @nemosupremo said it only seems to happen when opening the non-default workspace, although I'm not sure if that's related.

```
[2020-06-08 14:27:25.922] [renderer3] [error] Unexpected token { in JSON at position 119594: SyntaxError: Unexpected token { in JSON at position 119594
    at JSON.parse (<anonymous>)
    at _ (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:410:329)
    at y.onBuffer (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:415:72)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:413:368
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at v.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:424:97)
    at t.PersistentProtocol._receiveMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:428:451)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:425:635
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at g.acceptChunk (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:421:532)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:420:832
    at Socket.t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:431:812)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
```
