### ISSUE TITLE
Notebook: OId cell contents showing up again

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#99277]
Testing #98985
Version: 1.46.0-insider
Commit: 595d2b9b916d063aadfc2c1a8c8f6df5b45572a8
Date: 2020-06-03T05:33:25.873Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-51-generic

Not reprodcuble after a VSCode restart,

I added code cells. The new code cell had the content of a cell I previously deleted

Dev tools showed
```
/usr/share/code-insi….desktop.main.js:94     at e.registerListeners (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6442:760)
    at new e (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6439:631)
    at d._createInstance (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1649:255)
    at d.createInstance (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1648:683)
    at new e (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2278:508)
    at d._createInstance (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1649:255)
    at d.createInstance (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1648:683)
    at e.renderTemplate (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3714:843)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:540:918
    at Array.map (<anonymous>)
    at z.renderTemplate (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:540:909)
    at t.RowCache.alloc (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:296:490)
    at e.insertItemInDOM (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:511:224)
    at e._splice (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:507:859)
    at e.splice (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:506:467)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:30:994
    at Array.forEach (<anonymous>)
    at t.CombinedSpliceable.splice (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:30:981)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:547:144
    at t.EventBufferer.bufferEvents (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:98:214)
    at e.splice (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:547:111)
    at e.splice2 (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3246:431)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3243:937
    at Array.forEach (<anonymous>)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3243:715
    at e.fire (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at e.createCell (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3282:392)
    at e.insertNotebookCell (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:7059:249)
    at Object.runWithContext (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3669:701)
    at Object.run (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3663:279)
    at handler (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1834:871)
    at d.invokeFunction (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1648:212)
    at e._tryExecuteCommand (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3916:37)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3915:774
    at async s.run (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:123:52)
```

**Comment by rebornix** [comment]
The bug should already be resolved now in Insiders.
