### ISSUE TITLE
Open custom pawdraw editor closed upon reload

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#99293]
I had an opened, not-dirty, pawdraw editor open.
I reloaded. Immediately upon reload, I could see my pawdraw tab, but instead of loading the editor, it closed.

Console errors
```
  ERR Unable to read file 'c:\Users\alros\AppData\Roaming\Code - Insiders\User\workspaceStorage\2bbf3bac731b9476d49701d150b87366\vscode-samples.cat-customs\12874523091' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'c:\Users\alros\AppData\Roaming\Code - Insiders\User\workspaceStorage\2bbf3bac731b9476d49701d150b87366\vscode-samples.cat-customs\12874523091'): EntryNotFound (FileSystemError): Unable to read file 'c:\Users\alros\AppData\Roaming\Code - Insiders\User\workspaceStorage\2bbf3bac731b9476d49701d150b87366\vscode-samples.cat-customs\12874523091' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'c:\Users\alros\AppData\Roaming\Code - Insiders\User\workspaceStorage\2bbf3bac731b9476d49701d150b87366\vscode-samples.cat-customs\12874523091')
	at _handleError (c:\Users\alros\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:667:25)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async Function.create (c:\Users\alros\.vscode-insiders\extensions\custom-editor-sample\out\pawDrawEditor.js:40:26)
	at async PawDrawEditorProvider.openCustomDocument (c:\Users\alros\.vscode-insiders\extensions\custom-editor-sample\out\pawDrawEditor.js:166:26)
	at async K.$createCustomDocument (c:\Users\alros\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:788:230)
log.ts:197   ERR EntryNotFound (FileSystemError): Unable to read file 'c:\Users\alros\AppData\Roaming\Code - Insiders\User\workspaceStorage\2bbf3bac731b9476d49701d150b87366\vscode-samples.cat-customs\12874523091' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'c:\Users\alros\AppData\Roaming\Code - Insiders\User\workspaceStorage\2bbf3bac731b9476d49701d150b87366\vscode-samples.cat-customs\12874523091')
	at _handleError (c:\Users\alros\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:667:25)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async Function.create (c:\Users\alros\.vscode-insiders\extensions\custom-editor-sample\out\pawDrawEditor.js:40:26)
	at async PawDrawEditorProvider.openCustomDocument (c:\Users\alros\.vscode-insiders\extensions\custom-editor-sample\out\pawDrawEditor.js:166:26)
	at async K.$createCustomDocument (c:\Users\alros\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:788:230)
```

**Comment by alexr00** [comment]
I needed to reload before I could open that file again with the pawdraw editor.

**Comment by alexr00** [comment]
The path to cause a repro appears to be:
Make some drawings.
Do some undos and redos.
Keep the file open.
Reload.
