### ISSUE TITLE
Terminal "Error: Not implemented" on web

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#99303]
Issue Type: <b>Bug</b>

1. Be on latest master
2. Compile and mixin-server
3. yarn run web

Open the terminal in the browser, terminal is blank and this error is in the dev console:
```
ERR Not implemented: Error: Not implemented
	at WorkerExtHostTerminalService.$getDefaultShellAndArgs (http://localhost:8080/static/out/vs/workbench/api/common/extHostTerminalService.js:585:19)
	at RPCProtocol._doInvokeHandler (http://localhost:8080/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:336:31)
	at RPCProtocol._invokeHandler (http://localhost:8080/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:321:49)
	at RPCProtocol._receiveRequest (http://localhost:8080/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:248:36)
	at RPCProtocol._receiveOneMessage (http://localhost:8080/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:176:30)
	at http://localhost:8080/static/out/vs/workbench/services/extensions/common/rpcProtocol.js:66:56
	at Emitter.fire (http://localhost:8080/static/out/vs/base/common/event.js:457:42)
	at http://localhost:8080/static/out/vs/workbench/services/extensions/worker/extensionHostWorker.js:44:25
```

VS Code version: Code - Insiders 1.46.0-insider (595d2b9b916d063aadfc2c1a8c8f6df5b45572a8, 2020-06-03T05:38:33.098Z)
OS version: Darwin x64 18.7.0

**Comment by Tyriar** [comment]
It's not clear to me what should happen here. I could do a basic fake local echo shell such that people can test some things? @bpasero thoughts?

**Comment by bpasero** [comment]
@Tyriar yes it would be great if the terminal can be played with from `yarn web` even if just fake 👍

**Comment by Tyriar** [comment]
I'm going to hold off on this one as supporting terminals in `yarn web` doesn't provide much use, even for dev/test as most things won't work properly if there isn't a process backing it. Will look into this later on but it will probably be a message saying the terminal isn't supported.

**Comment by Tyriar** [comment]
This may still throw as the terminal request still goes out, but there is welcome support now as opposed to a broken terminal panel.
