### ISSUE TITLE
Error trying to execute code --list-extensions

### ISSUE THREAD

**Issue by nelsonc24** [Microsoft/vscode#9935]
- VSCode Version: Code 1.3.1 (e6b4afa, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Open cmd.
2. Type code --list-extensions

Getting:

SyntaxError: Unexpected token
    at Object.parse (native)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:7:16437
    at Object.v [as _notify] (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:4:28336)
    at Object.D.enter (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:4:31914)
    at r.Class.define._run (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:5:1739)
    at r.Class.define._completed (C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:5:1180)
    at C:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:4:29683
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)

![vs_issue2](https://cloud.githubusercontent.com/assets/10952301/17239875/b8222c0c-55aa-11e6-9bc4-a4807abdaa89.JPG)

**Comment by kieferrm** [comment]
@nelsonc24 works without a problem on Windows 10. Since you also filed #9933, I'm wondering if your install is corrupted. Can you try to reinstall vscode and see if the same problems persists?

**Comment by joaomoreno** [comment]
Proxy for sure.

**Comment by joaomoreno** [comment]
Actually unrelated to proxies.
