### ISSUE TITLE
Configured debug type 'extensionHost' is not supported

### ISSUE THREAD

**Issue by Meai1** [Microsoft/vscode#9961]
Probably easy to solve.. but I dont know how.

- VSCode Version:
1.4.0 from git
- OS Version:
Centos7

Steps to Reproduce:

1.  build from source, run scripts/code.sh
2. f5 on vscode-mock-debug sample project

> 32305:0729/121248:INFO:CONSOLE(80)] "Configured debug type 'extensionHost' is not supported.: Error: Configured debug type 'extensionHost' is not supported.
    at file:////home/pc/Desktop/vscode/out/vs/workbench/parts/debug/electron-browser/debugService.js:442:81
    at CompletePromise_then [as then] (file:////home/pc/Desktop/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)
    at file:////home/pc/Desktop/vscode/out/vs/workbench/parts/debug/electron-browser/debugService.js:428:18
    at Promise_ctor.CompletePromise_then [as then] (file:////home/pc/Desktop/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)
    at file:////home/pc/Desktop/vscode/out/vs/workbench/parts/debug/electron-browser/debugService.js:426:18
    at Object.notifySuccess [as _notify] (file:////home/pc/Desktop/vscode/out/vs/base/common/winjs.base.raw.js:1170:59)
    at Object.state_success_notify.enter (file:////home/pc/Desktop/vscode/out/vs/base/common/winjs.base.raw.js:852:30)
    at _Base.Class.define._run (file:////home/pc/Desktop/vscode/out/vs/base/common/winjs.base.raw.js:1068:29)
    at _Base.Class.define._completed (file:////home/pc/Desktop/vscode/out/vs/base/common/winjs.base.raw.js:1036:18)
    at Promise_ctor.CompletePromise_then [as then] (file:////home/pc/Desktop/vscode/out/vs/base/common/winjs.base.raw.js:1566:49)", source: file:////home/pc/Desktop/vscode/out/vs/workbench/services/message/browser/messageService.js (80)

**Comment by weinand** [comment]
@Meai1 please see https://github.com/Microsoft/vscode/issues/9559
