### ISSUE TITLE
TS Server fatal error:  path.charCodeAt is not a function

### ISSUE THREAD

**Issue by alexzhurov** [microsoft/vscode#99615]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
TypeError: path.charCodeAt is not a function
    at getEncodedRootLength (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:5984:24)
    at Object.isRootedDiskPath (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:5899:16)
    at Object.isExternalModuleNameRelative (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:10028:52)
    at secondaryLookup (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:28841:25)
    at resolveTypeReferenceDirective (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:28793:24)
    at resolveNamesWithLocalCache (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101728:38)
    at Object.resolveTypeReferenceDirectives (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:101773:20)
    at ConfiguredProject.Project.resolveTypeReferenceDirectives (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:139322:45)
    at Object.compilerHost.resolveTypeReferenceDirectives (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:135201:64)
    at resolveTypeReferenceDirectiveNamesWorker (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:97730:137)
    at Object.createProgram (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:97816:35)
    at synchronizeHostData (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:135218:26)
    at Proxy.getProgram (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:135310:13)
    at ConfiguredProject.Project.updateGraphWorker (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:139786:53)
    at ConfiguredProject.Project.updateGraph (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:139729:42)
    at ConfiguredProject.updateGraph (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:140654:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:142246:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143101:44)
    at /snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143396:107
    at Object.mapDefined (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:144260:46)
    at /snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:145994:28)
    at IOSession.Session.executeCommand (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146003:33)
    at IOSession.Session.onMessage (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:146027:35)
    at Interface.<anonymous> (/snap/code/33/usr/share/code/resources/app/extensions/node_modules/typescript/lib/tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 4.15.0-70-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 2184)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|39.28GB (17.86GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.0
jsrefactor|cms|2.20.6
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
jshint|dba|0.10.21
pgsql|dou|0.1.3
vscode-babel-coloring|dza|0.0.4
gitlens|eam|10.2.1
vscode-html-css|ecm|0.2.3
vscode-npm-script|eg2|0.3.12
vscode-great-icons|emm|2.1.47
prettier-vscode|esb|5.0.0
vue-format|feb|0.1.8
vscode-npm|fkn|3.3.0
auto-rename-tag|for|0.1.3
macros|ged|1.2.1
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
vscode-jetbrains-keybindings|isu|0.1.9
search-node-modules|jas|1.3.0
vs-color-picker|lih|1.0.0
vue|liu|0.1.5
camelcasenavigation|map|1.1.2
vscode-scss|mrm|0.9.0
vscode-language-pack-ru|MS-|1.45.1
python|ms-|2020.5.80290
remote-wsl|ms-|0.44.2
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.8
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.1.0
git-merger|sha|0.4.1
code-settings-sync|Sha|3.4.3
sc-themes|Syn|1.4.1
gitflow|vec|1.2.1
highlight-matching-tag|vin|0.9.9
vim|vsc|1.14.5
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.8.0
city-lights-icon-vsc|Yum|1.1.3
markdown-all-in-one|yzh|3.0.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by connor4312** [comment]
Does this happen if you use the latest TS 3.9.3?

If so, please provide reproduction steps if possible. Thanks!

/needsMoreInfo
