### ISSUE TITLE
Cannot read property 'onWillCloseEditor' of undefined

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#99682]
VS Code out of source

1. Have output view open
2. Reload 

Notice exception

```
ERR Cannot read property 'onWillCloseEditor' of undefined: TypeError: Cannot read property 'onWillCloseEditor' of undefined
    at OutputEditor.setEditorVisible (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/textEditor.js:141:51)
    at OutputEditor.setVisible (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/editor/baseEditor.js:76:22)
    at OutputViewPane.onDidChangeVisibility (file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/output/browser/outputView.js:86:29)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/contrib/output/browser/outputView.js:30:74
    at Emitter.fire (file:///Users/isidor/Development/vscode/out/vs/base/common/event.js:457:42)
    at OutputViewPane.setVisible (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/views/viewPaneContainer.js:128:57)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/views/viewPaneContainer.js:865:41
    at Array.map (<anonymous>)
    at ViewPaneContainer.setVisible (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/views/viewPaneContainer.js:865:22)
    at PaneContainerPanel.setVisible (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/panecomposite.js:36:40)
    at PanelPart.showComposite (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/compositePart.js:165:23)
    at PanelPart.doOpenComposite (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/compositePart.js:70:18)
    at PanelPart.openComposite (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/compositePart.js:43:25)
    at PanelPart.doOpenPanel (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:333:29)
    at PanelPart.openPanel (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/parts/panel/panelPart.js:337:33)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/browser/workbench.js:307:54
    at Workbench.restoreWorkbench (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/workbench.js:312:19)
    at file:///Users/isidor/Development/vscode/out/vs/workbench/browser/workbench.js:82:36
    at InstantiationService.invokeFunction (file:///Users/isidor/Development/vscode/out/vs/platform/instantiation/common/instantiationService.js:43:24)
    at Workbench.startup (file:///Users/isidor/Development/vscode/out/vs/workbench/browser/workbench.js:61:38)
    at DesktopMain.open (file:///Users/isidor/Development/vscode/out/vs/workbench/electron-browser/desktop.main.js:61:52)
```

**Comment by sandy081** [comment]
Caused by https://github.com/microsoft/vscode/commit/cb88b44212033b05f2c60425d7112d0876b9a757
