### ISSUE TITLE
Cannot read property 'filepath' of undefined

### ISSUE THREAD

**Issue by mudoo** [microsoft/vscode#99813]
Issue Type: <b>Bug</b>

TypeError: Cannot read property 'filepath' of undefined
	at eval (.././src/core/KeyDetector.ts:95:57)
	at Array.find (<anonymous>)
	at Function.getUsages (.././src/core/KeyDetector.ts:95:45)
	at ReviewCommentProvider.provideCommentingRanges (.././src/editor/reviewComments.ts:123:74)
	at c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:169
	at c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:136
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:52:108)
	at e.$provideCommentingRanges (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:129)
	at e._doInvokeHandler (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:804:1013)
	at e._invokeHandler (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:804:705)
	at e._receiveRequest (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:803:293)
	at e._receiveOneMessage (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:802:156)
	at c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:800:416
	at e.fire (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:222)
	at v.fire (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:239:274)
	at c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:975:649
	at e.fire (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:222)
	at v.fire (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:239:274)
	at t.PersistentProtocol._receiveMessage (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:243:629)
	at c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:240:824
	at e.fire (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:222)
	at p.acceptChunk (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:236:737)
	at c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:236:89
	at Socket.t (c:\Users\MM\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:245:185)
	at Socket.emit (events.js:203:13)
	at Socket.EventEmitter.emit (domain.js:476:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T09:03:20.462Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (10.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.2.0
i18n-ally|ant|2.2.4
insertnumbers|Asu|0.9.1
vscode-toggle-quotes|Bri|0.3.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.5
vscode-quick-select|dba|0.2.8
javascript-ejs-support|Dig|1.3.1
xml|Dot|2.5.0
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
vscode-projects-plus|fab|1.23.3
vscode-todo-plus|fab|4.17.1
auto-close-tag|for|0.5.7
code-runner|for|0.10.0
shell-format|fox|7.0.1
vue-snippets|hol|0.1.11
beautify|Hoo|1.5.0
output-colorizer|IBM|0.1.2
svelte-vscode|Jam|0.9.3
docthis|joe|0.7.1
rainbow-csv|mec|1.7.0
vscode-scss|mrm|0.9.0
vscode-language-pack-zh-hans|MS-|1.46.3
sublime-keybindings|ms-|4.0.7
vsliveshare|ms-|1.0.2302
prettier-standard-vscode|num|0.8.1
vetur|oct|0.24.0
fix-json|oli|0.1.2
vscode-versionlens|pfl|1.0.7
vscode-yaml|red|0.8.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.12
svg-preview|Sim|2.8.3
code-spell-checker|str|1.9.0
vscodeintellicode|Vis|1.2.8
quokka-vscode|Wal|1.0.294
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.8.0
local-history|xyz|1.8.1
markdown-all-in-one|yzh|3.0.0
material-theme|zhu|3.7.1

</details>

**Comment by sandy081** [comment]
It seems this is coming from an extension. Please file the issue against it.

**Comment by mudoo** [comment]
@sandy081 how to find out it?
