### ISSUE TITLE
TS Server fatal error:  Debug Failure. Text of property name cannot be read from non-literal-valued ComputedPropertyNames

### ISSUE THREAD

**Issue by coderkw** [microsoft/vscode#99814]
Issue Type: <b>Bug</b>

**TypeScript Version:** 3.8.3
**Steps to reproduce crash**
1.
2.
3.
**TS Server Error Stack**
```
Error: Debug Failure. Text of property name cannot be read from non-literal-valued ComputedPropertyNames
    at Object.getTextOfPropertyName (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:13264:33)
    at _loop_3 (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:27326:36)
    at convertObjectLiteralExpressionToJson (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:27368:17)
    at convertPropertyValueToJson (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:27424:32)
    at convertToObjectWorker (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:27309:16)
    at parseOwnConfigOfJsonSourceFile (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:28019:20)
    at parseConfig (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:27926:13)
    at parseJsonConfigFileContentWorker (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:27773:28)
    at Object.parseJsonSourceFileConfigFileContent (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:27740:16)
    at ProjectService.loadConfiguredProject (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:142263:44)
    at ProjectService.createAndLoadConfiguredProject (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:142240:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:142245:36)
    at ProjectService.assignProjectToOpenedScriptInfo (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143101:44)
    at g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143396:107
    at Object.mapDefined (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:562:30)
    at ProjectService.applyChangesInOpenFiles (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:143396:48)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:144260:46)
    at g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:145994:28)
    at IOSession.Session.executeCommand (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146003:33)
    at IOSession.Session.onMessage (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:146027:35)
    at Interface.<anonymous> (g:\ENV\vscode\resources\app\extensions\node_modules\typescript\lib\tsserver.js:147342:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
package-json-upgrade|cod|1.2.0
vscode-eslint|dba|2.1.5
gitlens|eam|10.2.2
prettier-vscode|esb|5.0.0
vscode-csscomb|mrm|5.3.1
vscode-language-pack-zh-hans|MS-|1.46.3
color-highlight|nau|2.3.0
vetur|oct|0.24.0
indent-rainbow|ode|7.4.0
vscode-import-cost|wix|2.12.0
material-theme|zhu|3.7.1

</details>

**Comment by mjbvz** [comment]
Do you see this in VS Code 1.46?
