### ISSUE TITLE
Extensions Smoke test failure

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99840]
```
VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Extensions
           install and activate vscode-smoketest-check extension:
     Error: Timeout: get text content 'div[id="workbench.parts.statusbar"] .statusbar-item[title="smoke test"]' after 20 seconds.
      at /Users/runner/runners/2.169.1/work/1/s/test/automation/out/code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/runners/2.169.1/work/1/s/test/automation/out/code.js:9:58)
```

**Comment by sandy081** [comment]
Caused by #98376
