### ISSUE TITLE
No auto-complete suggestions showing up, but Quick Fix has the correct import

### ISSUE THREAD

**Issue by drj17** [microsoft/vscode#99880]
Issue Type: <b>Bug</b>

1. Start adding React component tag. 
2. No suggestions show up
3. Right click to quick fix and correct import shows up

Example:
 ![example](https://user-images.githubusercontent.com/13426126/84402837-fb8c9e00-abd2-11ea-8dea-dfdf499080e7.gif)

I've tried on both the stable branch and the insider branch.  I've reinstalled vscode a couple times, removed all extensions, created a fresh tsconfig, nothing has seemed to work.

On every keypress I get this error in the developer console: 
```
  ERR <semantic> TypeScript Server Error (3.9.4)
Debug Failure.
Error: Debug Failure.
    at Object.getNameForExportedSymbol (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:110394:70)
    at pushSymbol (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113377:40)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113360:28
    at Map.forEach (<anonymous>)
    at getSymbolsFromOtherSourceFileExports (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113358:54)
    at getGlobalCompletions (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113117:49)
    at tryGetGlobalSymbols (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:113028:25)
    at getCompletionData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:112804:17)
    at Object.getCompletionsAtPosition (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:112166:34)
    at Proxy.getCompletionsAtPosition (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:138870:35)
    at IOSession.Session.getCompletions (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:148949:64)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:147886:61)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149526:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149517:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149526:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:149550:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:150866:27)
    at Interface.emit (events.js:203:13)
    at Interface._onLine (readline.js:316:10)
    at Interface._normalWrite (readline.js:461:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17): Error: <semantic> TypeScript Server Error (3.9.4)
Debug Failure.
```

VS Code version: Code - Insiders 1.47.0-insider (6efc0b6950cef0dbed0a59c23c656a3f2cfb6403, 2020-06-11T05:45:05.735Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (3.65GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Ardrete** [comment]
I have the same issue, I was trying to disable all the extensions but with no luck
My jsconfig file has 
`{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6"
  },
  "include": ["app/**/*", "internals/**/*", "server/**/*"]
}
`

**Comment by drj17** [comment]
I rolled back to Typescript 3.8.3 and it fixed the issue for me.
