### ISSUE TITLE
Notebook smoketest failure

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#99940]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=78251&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=05af1eac-c39c-5c75-1e3f-dd115ec8907d&l=80

```
1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Notebooks
           inserts/edits markdown cell:
     Error: Timeout: get text content '.notebook-editor .monaco-list-row.focused .markdown h2' after 20 seconds.
      at /Users/runner/runners/2.169.1/work/1/s/test/automation/out/code.js:182:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/runners/2.169.1/work/1/s/test/automation/out/code.js:9:58)

```

**Comment by roblourens** [comment]
Have made lots of changes since then, can't repro it
